### ISSUE TITLE
Remove @InitialRoute or make it optional

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#10]
There is nothing special about the initial route compared to other routes.
It should be possible to make this a material/cupertino/custom route so that a back navigation will use the correct animation.

Currently it always is a `MaterialPageRoute` and it is required. In order to circumvent this, I always create a dummy route with `@InitialRoute()` but don't use it.

**Comment by Milad-Akarie** [comment]
Hey @kuhnroyal, it is actually treated differently from the other routes. 
The initial route name must be "/"  so the back button is automatically hidden, as it's considered the bottom of the stack. also the navigator will automatically call "/" on build.
You have a point regarding the back animation tho.
I can use the initial flag as a property in all of the types?
@CupertinoRoute(initial:true)
Or maybe
@CupertinoRoute.Initial to prevent passing parameters.

**Comment by Milad-Akarie** [comment]
Hey @kuhnroyal  checkout version 0.2.1, you can now use any type of routes as an initial route => @CupertinotRoute(initial: true)
