### ISSUE TITLE
Custom navigator key

### ISSUE THREAD

**Issue by visual-velocity** [Milad-Akarie/auto_route_library#100]
How do we pass user own custom navigator key and how do you get navigator key from this package

**Comment by visual-velocity** [comment]
I need it for my production app

**Comment by Milad-Akarie** [comment]
Hey, @visual-velocity Sorry for the delay. 
Whats your setup?

**Comment by visual-velocity** [comment]
I added your package and called inside builder method. I need to add Catcher package but it require navigator key.
Issue
1. Need navigator key for catcher package
2. Is ExtendedNavigator can call/integrate without Builder method of MaterialApp widget in app. We are need builder method for other purpose .
Please solve my issue @Milad-Akarie because i need to publish my production app with your package and Catcher package asap.

**Comment by visual-velocity** [comment]
For handling all red-screen error and calling ErrorWidgetBuilder from root we need builder method. Inside builder how can we return multiple value/widget

**Comment by Milad-Akarie** [comment]
as for the custom key in your main method initiate the navigator key inside of Catcher with a GlobalKey of type Navigator not ExtendedNavigator like follows

```dart
 Catcher(MyApp(), navigatorKey: GlobalKey<NavigatorState>());
```

Then simply pass the key to the ExtendedNavigator instead of MaterialApp like follows
```dart
 return MaterialApp(
      builder: ExtendedNavigator<Router>(
      // pass your catcher key here
        key: Catcher.navigatorKey,
        router: Router(),
      ),

```

**Comment by Milad-Akarie** [comment]
What ever the package you're using directly in your builder it must have some sort of a wrapper for This's an example using  DevicePreivew package

```dart
return MaterialApp(
      builder: (context, nativeNavigator) => DevicePreview.appBuilder(
        context,
        ExtendedNavigator(router: Router()),
      ),
```


 if you're not gonna need any feature that ExtendedNavigator provides you can try this

```dart
 return MaterialApp(
        key: Catcher.navigatorKey,
        onGenerateRoute: Router().onGenerateRoute,
      ),
```

**Comment by visual-velocity** [comment]
I am very happy with your reply and I think it will help a lot and I want to thank you completely

**Comment by Milad-Akarie** [comment]
@visual-velocity Glad to help. you're welcome.

**Comment by visual-velocity** [comment]
**Error widget**
You can add error widget which will replace red screen of death. To add this into your app, see code below:

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: Catcher.navigatorKey,
      //********************************************
      builder: (BuildContext context, Widget widget) {
        Catcher.addDefaultErrorWidget(
            showStacktrace: true,
            title: "Custom error title",
            description: "Custom error description",
            maxWidthForSmallMode: 150);
        return widget;
      },
      //********************************************
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: ChildWidget()),
    );
  }
**You need to add in your MaterialApp or CupertinoApp builder method with Catcher.addDefaultErrorWidget(). This will add error handler for each widget in your app.**

Is it possible to add ExtendedNavigator inside the builder method of material app with Catcher.addDefaultErrorWidget()

**Comment by Milad-Akarie** [comment]
```dart
builder: (BuildContext context, Widget widget) {
// widget here is the native navigator and you're supposed to wrap it
// with other widgets if you need to
Catcher.addDefaultErrorWidget(
     showStacktrace: true,
     title: "Custom error title",
     description: "Custom error description",
     maxWidthForSmallMode: 150);
     // so instead of returning the native navigator
     // return ExtendedNavigator
     return ExtendedNavigator(router:Router(), key: Catcher.navigatorKey);
},
```

**Comment by visual-velocity** [comment]
> as for the custom key in your main method, initiate the navigator key inside of Catcher with a GlobalKey of type Navigator not ExtendedNavigator like follows
> 
> ```dart
>  Catcher(MyApp(), navigatorKey: GlobalKey<NavigatorState>());
> ```
> 
> Then simply pass the key to the ExtendedNavigator instead of MaterialApp like follows
> 
> ```dart
>  return MaterialApp(
>       builder: ExtendedNavigator<Router>(
>       // pass your catcher key here
>         key: Catcher.navigatorKey,
>         router: Router(),
>       ),
> ```

I'm trying to use your response but will get this response 
Unhandled Exception: type 'LabeledGlobalKey<NavigatorState>' is not a subtype of type 'GlobalKey<ExtendedNavigatorState<RouterBase>>'

**Comment by visual-velocity** [comment]
> ```dart
> builder: (BuildContext context, Widget widget) {
> // widget here is the native navigator and you're supposed to wrap it
> // with other widgets if you need to
> Catcher.addDefaultErrorWidget(
>      showStacktrace: true,
>      title: "Custom error title",
>      description: "Custom error description",
>      maxWidthForSmallMode: 150);
>      // so instead of returning the native navigator
>      // return ExtendedNavigator
>      return ExtendedNavigator(router:Router(), key: Catcher.navigatorKey);
> },
> ```

I'm getting this response / error 
Unhandled Exception: type 'LabeledGlobalKey<NavigatorState>' is not a subtype of type 'GlobalKey<ExtendedNavigatorState<RouterBase>>'

**Comment by Milad-Akarie** [comment]
Are you passing a Globalkey to Catcher()?

**Comment by visual-velocity** [comment]
Catcher(MyApp(), navigatorKey: new GlobalKey<NavigatorState>());

return MaterialApp(
navigatorKey: Catcher.navigatorKey,
      builder:(context,child){return  ExtendedNavigator<Router>(
        key: Catcher.navigatorKey,
        router: Router(),
      ),},

**Comment by visual-velocity** [comment]
Catcher(MyApp(), navigatorKey: new GlobalKey());

Inside the navigator key when you pass navigatorKey: new GlobalKey() is look like a custom navigator key that is defined inside Catcher , may be the issue is generated due to it.

**Comment by Milad-Akarie** [comment]
If you need to pass a predefined key to any widget you have to define the state type Globalkey<NavigatorState>() 
Anyways if you're initializing your key directly in the catcher constructor then you don't probably need a predefined key so just let catcher use its default key.
// Don't pass a key
`Catcher(MyApp());`

**Comment by Milad-Akarie** [comment]
Also don't pass the catcher navigator key to the materialApp, only pass  it to the extended navigator

**Comment by visual-velocity** [comment]
I already worked with this process but it's not working then i moved this path, can you suggest me is it fine or issue in future.

**Comment by visual-velocity** [comment]
Inside main function 
main(){
GlobalKey<ExtendedNavigatorState<Router>> navigatorKey = new GlobalKey<ExtendedNavigatorState<Router>>();
  CatcherOptions debugOptions = CatcherOptions(PageReportMode(showStackTrace: false), [
    ConsoleHandler(enableApplicationParameters: true,
        enableDeviceParameters: true,
        enableCustomParameters: true,
        enableStackTrace: true)
  ]);

Catcher(
  MyApp(),
    navigatorKey: navigatorKey,
  ),
    debugConfig: debugOptions,
    navigatorKey: navigatorKey
);
}

class MyApp extends StatefulWidget {
   final GlobalKey<ExtendedNavigatorState> navigatorKey;
  MyApp({this.navigatorKey});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
return MaterialApp(
navigatorKey: widget.navigatorKey,
builder: (context, child) {
            Catcher.addDefaultErrorWidget(
                showStacktrace: true,
                title: "Custom error title",
                description: "Custom error description",
                maxWidthForSmallMode: 150);
            return ExtendedNavigator<Router>(
              router: Router(),
              key: widget.navigatorKey,
            );
          },
);
}

**Comment by visual-velocity** [comment]
the app is working fine but i'm not sure that is it fine or issue. please suggest me.

**Comment by Milad-Akarie** [comment]
Catcher is expecting a 
`GlobalKey<NavigatorState>()`
Not 
`GlobalKey<ExtendedNavigatorState>()`

So just initialize your key with 
`final navigatorKey = GlobalKey<NavigatorState>()`

**Comment by visual-velocity** [comment]
let me check

**Comment by visual-velocity** [comment]
> Catcher is expecting a
> `GlobalKey<NavigatorState>()`
> Not
> `GlobalKey<ExtendedNavigatorState>()`
> 
> So just initialize your key with
> `final navigatorKey = GlobalKey<NavigatorState>()`

I m again getting error 
Unhandled Exception: type 'LabeledGlobalKey<NavigatorState>' is not a subtype of type 'GlobalKey<ExtendedNavigatorState<RouterBase>>'

**Comment by FakenMaster** [comment]
> Also don't pass the catcher navigator key to the materialApp, only pass it to the extended navigator

In case someone composing [wiredash]('https://github.com/wiredashio/wiredash-sdk') with auto_route , he should follow advice as above,only provide the navigatorkey to ExtendedNavigator.

`
class MyApp extends StatelessWidget {
  final _navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Wiredash(
      projectId: "YOUR-PROJECT-ID",
      secret: "YOUR-SECRET",
      navigatorKey: _navigatorKey,
      child: MaterialApp(
        //navigatorKey: _navigatorKey,
        title: 'Flutter Demo',
        builder: (context, child) => ExtendedNavigator(
            key: _navigatorKey,
            router: YOUR-ROUTER(),
        ),
      ),
    );
  }  
}
`
