### ISSUE TITLE
Auto Router in initState() of main.dart

### ISSUE THREAD

**Issue by IdemenB** [Milad-Akarie/auto_route_library#1000]
The use case is that the user should be navigated to a route upon opening a push notification.  I use OpenSignal for notifications and the listener to the payload of the push notification runs in initState() of main.dart. However, this is just before the AutoRoute object is initiated in main.dart; so any action with context.router ends with "AutoRouter operation requested with a context that does not include an AutoRouter."

I also tried the  WidgetsBinding.instance?.addPostFrameCallback.addPostFrameCallback() method to be able to have access to context in initState(), but it also fails with the router.

**Comment by Milad-Akarie** [comment]
@IdemenB @ydang204  don't you already have the router object inside of your root widget? no need to obtain the router using context.
