### ISSUE TITLE
Fill some of the route params from the parent?

### ISSUE THREAD

**Issue by AAverin** [Milad-Akarie/auto_route_library#1004]
Building nested navigation hierarchies, some of the context information is usually implied by the parent.
For example, I am building a `Guides List => Single Guide => Map` relationship. `Map` can also be used in other parts of the product and behave differently when it's in the Guide. How can `Map` now if it's in the Single Guide or not? Can some of the path/query params of MapRoute be filled by data, set in the Single Guide?

**Comment by Milad-Akarie** [comment]
@AAverin if you're talking about path/query params all you have to do is annotate the params inside of the child route and they will be delivered to it. 
you can also access parent route data anywhere inside child routes 
`context.routeData.parent?.pathParams`
