### ISSUE TITLE
How to use with LocalHistoryRoute?

### ISSUE THREAD

**Issue by kostadin-damyanov-prime** [Milad-Akarie/auto_route_library#1007]
Hello.

Is it possible to use this autoroute with `LocalHistoryRoute` from flutter? If yes then how is it done?

Reference: https://api.flutter.dev/flutter/widgets/LocalHistoryRoute-mixin.html

**Comment by Milad-Akarie** [comment]
@kostadin-damyanov-prime  yes, just add the entry 
  ```dart
ModalRoute.of(context)?.addLocalHistoryEntry(LocalHistoryEntry(onRemove: (){
                             // on entry removed
                          }));
```
