### ISSUE TITLE
[Exception] "setState() or markNeedsBuild() called during build" for pushAndPopUntil

### ISSUE THREAD

**Issue by coldstar96** [Milad-Akarie/auto_route_library#1010]
When calling ```router.pushAndPopUntil(SomeRoute, predicate: (_) => false)``` in AutoRouteGuard on cold start(before any view is presented), it causes this exception.

**Version**
auto_router: ^3.2.4

<details>
<summary>FlutterError (setState() or markNeedsBuild() called during build.</summary>
FlutterError (setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Overlay-[LabeledGlobalKey<OverlayState>#413a5]
The widget which was currently being built when the offending call was made was:
  RouteDataScope)
</details>

I replaced the call with router.replaceAll to fix on my end

**Comment by Milad-Akarie** [comment]
I tried this guard on root page but I could reproduce the issue. 
```dart
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    if (!isAuthenticated) {
      router.pushAndPopUntil(
        LoginRoute(onLoginResult: (_) {
          resolver.next();
          router.removeLast();
        }),
        predicate: (r) => false,
      );
    } else {
      resolver.next(true);
    }
  }
```
