### ISSUE TITLE
Remove AutoRouter() elevation 

### ISSUE THREAD

**Issue by alexisenp** [Milad-Akarie/auto_route_library#1011]
Im using [Wrapping routes](https://autoroute.vercel.app/basics/wrapping_routes) to make an appbar in the top and a menu to the rigth side of the web app, but the AutoRouter appear with elevation and it doest'n look good. How to remove the elevation ?
the body o
The scaffold's body of my wrapping widget is this:

`body: Row(
        children: const [
          Expanded(
            child: Text('Menu here'),
          ),
          Expanded(
            flex: 5,
            child: AutoRouter(),
          )
        ],
      ),`

The main page loaded in AutoRouter() is this:

`class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Principal'));
  }
}`

its look like this:

<img width="1440" alt="Captura de Pantalla 2022-04-02 a la(s) 20 36 44" src="https://user-images.githubusercontent.com/9923139/161404941-22da35ff-1ec8-4504-a561-94323e314828.png">

Thanks in advance.

**Comment by Milad-Akarie** [comment]
@alexisenp  This only happens in Cupertino Route transitions, it's the native navigator's doing. 
please refer to this 
https://stackoverflow.com/questions/53457772/why-there-is-a-shadow-between-nested-navigator

if you use CustomRoute instead of material the shadow should disappear.

**Comment by alexisenp** [comment]
Thanks, i forgot to answer before but right after your first answer i tried and it working perfect. 
Thanks for your work !!
