### ISSUE TITLE
Deep-linking issues using declarative router.

### ISSUE THREAD

**Issue by CRDEV00** [Milad-Akarie/auto_route_library#1012]
I'm using declarative routing to handle my auth, and I got 2 diff routers, one for auth user and another for unauthenticated user, each router has nested routes, and I'm not able to navigate between them,  is there any way to push or navigate to a different router using a declarative router.  I tried using navigateNamed() using a full path, pushing the router with their children.. nothing really worked.

**Comment by lam-nv** [comment]
Maybe, You and I have the same issue.

My issue happens when I tap on the deep link, the page with specified `initial: true will be pushed automatically.
