### ISSUE TITLE
[Question]: How to enable deeplinking in auto_route

### ISSUE THREAD

**Issue by Ayush-gupta-josh** [Milad-Akarie/auto_route_library#1016]
Is there any specific parameter I need to pass to enable deep linking in  auto_route to android and IOS devices

**Comment by MindMayhem** [comment]
https://docs.flutter.dev/development/ui/navigation/deep-linking

**Comment by Milad-Akarie** [comment]
@Ayush-gupta-josh after getting your deep-link you simply pass it to router.delegate(initialDeepLink: ''");

**Comment by Ayush-gupta-josh** [comment]
@Milad-Akarie currently I am using uni link dependency to support deep-link with auto route. Not sure above solution will help because I was in assumption that I will not required any extra package with auto-route to support deep-links. Whenever I try to deep-link route other than root route it never works so I have to use uni-link to re route it to specific route. May I am missing something here but not sure what

**Comment by Milad-Akarie** [comment]
@Ayush-gupta-josh yes, you need either uni-links or dynamic links the get the deep-link then you can pass it to auto_route so it can take you the respective destination.
