### ISSUE TITLE
[Question] Push route over AutoTabScaffold

### ISSUE THREAD

**Issue by MindMayhem** [Milad-Akarie/auto_route_library#1018]
Hi all! Is it possible to push new route over AutoTabScaffold with saving hierarchy of app

I need to load fullscreen page over autotabscaffold when user comes in app from deeplink, but seems like there's no way to build route over existing autotabscaffold (it incapsulate every route in it)

At the moment i can only create separated routes (`/item/:id` and `/ `, for example) and push it via button, function, etc

BUT, if i come to app via deeplink - it will build only one route without main route with AutoTabScaffold

![image](https://user-images.githubusercontent.com/39557395/161340495-0dba25dc-1568-44cc-bbe8-5bfd9b80abf0.png)

**Comment by Milad-Akarie** [comment]
hello @MindMayhem  please share your router setup

**Comment by francescreig** [comment]
Hello @Milad-Akarie, I am also interested on this topic. I also wanted to achieve this transition.
In my case my router setup would be like:
```dart
routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      path: '/splash',
      page: SplashPage,
    ),
    AutoRoute(
      path: '/home',
      page: HomePage,
      children: [
        ...tab1Routes,
        ...tab2Routes,
      ],
    ),
    RedirectRoute(path: '*', redirectTo: '/splash'),
  ],
```

On the `HomePage` is where I have set up the `AutoTabsScaffold`.
Where the `tab1Routes` and `tab2Routes` are defined on another packages respectively. 

Lets say on `tab1Routes` I have:
```dart
const tab1Routes = [
  AutoRoute(
    path: 'tab1',
    name: 'Tab1Router',
    page: EmptyRouterPage,
    children: [
      AutoRoute(
        path: '',
        page: Tab1ListsPage,
      ),
      AutoRoute(
        path: 'subtab1',
        page: SubPageTab1Page,
      ),
      AutoRoute(
        path: 'page-that-I-want-full-screen',
        page: PageThatIWantFullScreenPage,
      ),
      RedirectRoute(path: '*', redirectTo: ''),
    ],
  ),
];
```
Note that the `PageThatIWantFullScreenPage` is the one that it should be entirely full screen (without BottomNavigationBar or AppBar). Is it possible to be handled some way, maintaining this page on the `tab1Routes` list?

**Comment by Milad-Akarie** [comment]
@francescreig  Simplest way is to add some flag to the route meta data that indicates it's fullscreen then handle that in your tabsHosting widget

```dart
const tab1Routes = [
  AutoRoute(
    path: 'tab1',
    name: 'Tab1Router',
    page: EmptyRouterPage,
    children: [
      AutoRoute(
        path: '',
        page: Tab1ListsPage,
      ),
      AutoRoute(
        path: 'subtab1',
        page: SubPageTab1Page,
      ),
      AutoRoute(
        path: 'page-that-I-want-full-screen',
        page: PageThatIWantFullScreenPage,
       meta: {'fullScree': true}, // add flag here
      ),
      RedirectRoute(path: '*', redirectTo: ''),
    ],
  ),
];
```


then you can do something like this inside your widget

```dart
    final hideBottomNav = tabsRouter.topMatch.meta['fullscreen'] == true;
    return hideBottomNav
        ? null
        : BottomNavigationBar(
            currentIndex: tabsRouter.activeIndex,
            onTap: tabsRouter.setActiveIndex,
            items: [
               // items
            ],
          );
  }
```

other solution would be defining your full screen route out side of the tabsRouter

```dart
routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      path: '/splash',
      page: SplashPage,
    ),
    AutoRoute(
      path: '/home',
      page: HomePage,
      children: [
        ...tab1Routes,
        ...tab2Routes,
      ],
    ),
    AutoRoute(page: FullScreenPage), // here
    RedirectRoute(path: '*', redirectTo: '/splash'),
  ],
```
