### ISSUE TITLE
I have null-aware Warning when every loaded

### ISSUE THREAD

**Issue by hengchao** [Milad-Akarie/auto_route_library#1019]
auto_route-3.2.4/lib/src/router/widgets/auto_tabs_router.dart:181:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
/auto_route-3.2.4/lib/src/router/widgets/auto_route_navigator.dart:46:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
/auto_route-3.2.4/lib/src/router/provider/auto_route_information_provider.dart:20:36: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
          location: WidgetsBinding.instance?.window.defaultRouteName ??
                                   ^
/auto_route-3.2.4/lib/src/router/provider/auto_route_information_provider.dart:55:32: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      location: WidgetsBinding.instance!.window.defaultRouteName);
                               ^
/auto_route-3.2.4/lib/src/router/provider/auto_route_information_provider.dart:66:39: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    if (!hasListeners) WidgetsBinding.instance!.addObserver(this);
                                      ^
/auto_route-3.2.4/lib/src/router/provider/auto_route_information_provider.dart:73:39: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    if (!hasListeners) WidgetsBinding.instance!.removeObserver(this);
                                      ^
auto_route-3.2.4/lib/src/router/provider/auto_route_information_provider.dart:82:38: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    if (hasListeners) WidgetsBinding.instance!.removeObserver(this);

**Comment by Milad-Akarie** [comment]
Please print flutter doctor output here

**Comment by hengchao** [comment]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.13.0-0.0.pre.425, on Microsoft Windows [版本 10.0.19042.1586], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.1)
[!] Proxy Configuration
    ! NO_PROXY does not contain localhost
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 4 categories.

**Comment by sobimor** [comment]
I confirm this issue on the Flutter beta channel (2.13.0-0.1.pre).


`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.13.0-0.1.pre, on macOS 12.3.1 21E258 darwin-arm,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
`
