### ISSUE TITLE
[Feat. Req.] Some improvements for flutter web

### ISSUE THREAD

**Issue by valentinbercot** [Milad-Akarie/auto_route_library#102]
First of all your library is awesome! Really helpful it handles a lot of boilerplate and route guard is... simply awesome!

Before beginning I recommend you to add issue templates to help your community to provide clear issues like in [Flutter](https://github.com/flutter/flutter/tree/master/.github/ISSUE_TEMPLATE) or [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator/tree/master/.github/ISSUE_TEMPLATE)

## Use case

I'm using flutter for a iOS Android and Web project. Web is close to be on stable channel (currently in beta and not only on master)

I have some redirect in my app (oauth2 authorization code flow) with query params and it work pretty well with oauth2 uni_links and url_launcher for mobile apps but it doesn't work on web.

It could be great that calling a web url like /home?foo=bar with following code:

**home_page.dart**
```dart
class HomePage extends StatelessWidget {
  // Proposed annotation
  @queryParameter
  final String foo;

  const HomePage({Key key, this.foo}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: (foo != null) ? Text(foo) : Text("None"),
    );
  }
}
```

**router.dart**
```dart
@MaterialAutoRouter(
  generateNavigationHelperExtension: true,
  generateArgsHolderForSingleParameterRoutes: true,
)
class $Router {
  HomePage home;
}
```

It could display:
> bar

That could be a huge improvement to support flutter for web in a first time. Managing which parameter is allowed in URI could be achieved with annotations in route arguments ! (as proposed)

In a second time adding support to path parameter could be a good idea.

For example:

**items_page.dart**
```dart
class ItemsPage extends StatelessWidget {
  const ListPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // return list of items
    // on click on an item navigate to detail page
  }
}
```

**item_page.dart**
```dart
class ItemPage extends StatelessWidget {
  // Proposed annotation
  @pathParameter
  final String id;
  const ListPage({Key key, @required this.id}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(id),
    );
  }
}
```

**router.dart**
```dart
@MaterialAutoRouter(
  generateNavigationHelperExtension: true,
  generateArgsHolderForSingleParameterRoutes: true,
)
class $Router {
  ItemsPage items;

  // Proposed annotation
  @detailRoute(of: ItemsPage)
  ItemPage item;
}
```

Then I could call:

/items

It could display:
> list of items 

/items/bar

It could display:
> bar

## Proposal

There is some [articles](https://medium.com/flutter-community/advance-url-navigation-for-flutter-web-d8b5f2d424e6) about how to handle query parameters in flutter for web

**Comment by Milad-Akarie** [comment]
@valentinbercot count on it.

**Comment by visual-velocity** [comment]
We need this feature inside this library.

**Comment by melewetwo** [comment]
There is also a problem on web when using "@AdaptiveAutoRouter" annotation.
Platform.isAndroid, Platform.isIOS, etc. (Platform.[...] in general) is not available when on web. 
There should be a check like 
if (kIsWeb) { ... }

**Comment by Milad-Akarie** [comment]
@valentinbercot @visual-velocity 
check it out  auto_route: 0.6.0

**Comment by Milad-Akarie** [comment]
closing this for now

**Comment by valentinbercot** [comment]
Hi @Milad-Akarie, sorry to come back to you so late. That's a really good job !

I'll come back to you if I have other improvements for auto_route and/or injectable 😉
