### ISSUE TITLE
[Question] Nested Routes with an adaptive/responsive layout

### ISSUE THREAD

**Issue by AndrewProbityWeb** [Milad-Akarie/auto_route_library#1020]
I am trying to get nested routing to work with a resposive app. Essentially on a large screen, I want to show a list view and a detail view at the same time, and on a small screen to show either a list view or a detail view. I can get both to work individually but only with a different router set up. 

This router allows me to create the nested large screen layout where the list view and detail view appear on the same screen:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      path: "/books",
      name: "BooksRouter",
      page: BooksPage,
      children: [
        AutoRoute(path: ':bookId', page: BookDetailsPage),
        RedirectRoute(path: '*', redirectTo: ''),
      ],
    ),
  ],
)
class $AppRouter {}
```

This allows me to do a nested layout where they appear on different screens:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      path: "/books",
      name: "BooksRouter",
      page: EmptyRouterPage,
      children: [
        AutoRoute(path: '', page: BooksPage),
        AutoRoute(path: ':bookId', page: BookDetailsPage),
        RedirectRoute(path: '*', redirectTo: ''),
      ],
    ),
  ],
)
class $AppRouter {}
```

Is there away to do this so I can do both?

**Comment by Milad-Akarie** [comment]
@AndrewProbityWeb I think the best way to handle this to have a BooksDetailsPage widget inside of your BooksPage along with having it as a separate route that way you can always use the later setup and only have to handle responsiveness changes inside of your widget.
