### ISSUE TITLE
Home Index property of the AutoTabsScaffold isn't working.

### ISSUE THREAD

**Issue by BTonny** [Milad-Akarie/auto_route_library#1024]
Ive been trying to set the `currentIndex` of a `BottomNavigationBar` to an index other than 0(the default) when a page loads while using AutoTabsScaffold but found no alternative to set it. So i assumed the `homeIndex` property of the `AutoTabsScaffold` is right way to do it.

But it doesn't seem to work. still the currentIndex remains 0 by default on launching the app.

How can i change this?

**Comment by Milad-Akarie** [comment]
@BTonny homeIndex Property is neither an initialIndex nor activeIndex, when home index is set the page will pop when activeIndex == homeIndex otherwise it will redirect to homeIndex first. 

you can set the initial index by navigating to it.  meaning, treat it as a target child in a sub router as it really is. 

lets say your root page in is the Tabs hosting page in your router delegate.initialRoutes = [HomeRouteWithTabs(children: [TargetTabeRoute()])]

**Comment by apieceofcode1801** [comment]
@Milad-Akarie 
Let's say I return an `AutoTabsScaffold` like this. The `currentIndex` is default set by 0, how can change this value to 2 (In my case I want the `HomeRouter` as the initial router)? Thanks.
```
return AutoTabsScaffold(
      homeIndex: 2,
      routes: const [
        TVRouter(),
        SearchRouter(),
        HomeRouter(),
        DokoikuRouter(),
        NewsRouter()
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return BottomNavigationBar(
            selectedLabelStyle: AppFonts.jBold
                .copyWith(fontSize: 10, color: AppColors.textNormal),
            unselectedLabelStyle: AppFonts.jBold.copyWith(
                fontSize: 10, color: AppColors.textNormal.withOpacity(0.5)),
            selectedItemColor: AppColors.textMain,
            type: BottomNavigationBarType.fixed,
            iconSize: 28,
            currentIndex: tabsRouter.activeIndex,
            onTap: tabsRouter.setActiveIndex,
            items: [
              BottomNavigationBarItem(
                label: LocaleKeys.tab_tv_set.tr(),
                icon: TabIcon(IconImage.tab_tv, isActive: false),
                activeIcon: TabIcon(IconImage.tab_tv, isActive: true),
              ),
              BottomNavigationBarItem(
                label: LocaleKeys.tab_tv_search.tr(),
                icon: TabIcon(IconImage.tab_search, isActive: false),
                activeIcon: TabIcon(IconImage.tab_search, isActive: true),
              ),
              BottomNavigationBarItem(
                label: LocaleKeys.tab_home.tr(),
                icon: TabIcon(IconImage.tab_home, isActive: false),
                activeIcon: TabIcon(IconImage.tab_home, isActive: true),
              ),
              BottomNavigationBarItem(
                label: LocaleKeys.tab_where_to_go.tr(),
                icon: TabIcon(IconImage.tab_dokoiku, isActive: false),
                activeIcon: TabIcon(IconImage.tab_dokoiku, isActive: true),
              ),
              BottomNavigationBarItem(
                label: LocaleKeys.tab_news.tr(),
                icon: TabIcon(IconImage.tab_news, isActive: false),
                activeIcon: TabIcon(IconImage.tab_news, isActive: true),
              ),
            ]);
      },
    );
```

**Comment by apieceofcode1801** [comment]
Oh, I found the way that to set in my `HomeRouter ` will work.
```
AutoRoute(
          initial: true,
...)
```

**Comment by anhtuan23** [comment]
> @BTonny homeIndex Property is neither an initialIndex nor activeIndex, when home index is set the page will pop when activeIndex == homeIndex otherwise it will redirect to homeIndex first.
> 
> you can set the initial index by navigating to it. meaning, treat it as a target child in a sub router as it really is.
> 
> lets say your root page in is the Tabs hosting page in your router delegate.initialRoutes = [HomeRouteWithTabs(children: [TargetTabeRoute()])]

I need to set initial tab is Bottom Navigation Bar dynamically, so setting `initial: true` in root router is not an option.
Following @Milad-Akarie suggestion, here's how to do it:

```
MaterialApp.router(
        routerDelegate: _appRouter.delegate(
          initialRoutes: [
            const HomeRoute(children: [BookRoute()]),
          ],
        ),
        routeInformationParser: _appRouter.defaultRouteParser(),
        );
```
