### ISSUE TITLE
Error: Trying to navigate to a nested route without adding their parent first

### ISSUE THREAD

**Issue by zexross** [Milad-Akarie/auto_route_library#1025]
**Error**: Looks like you're trying to navigate to a nested route without adding their parent to stack first
try navigating to `parentA` -> `childA`

**Steps to Produce**: I am trying to between widgets (sub-tree navigation) using a state management solution. I passed the `AutoRouter()` widget in the tree where sub-routing is expected. While trying to navigate I get the above-mentioned error. Also, when I try my same routing setup in a different project it is working as expected. I tried finding the issue but failed.

- Router Setup:
```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: LoginScreen, name: 'LoginRoute', path: '/login'),
    AutoRoute(page: NoAccessView, name: 'NoAccessRoute', path: 'no_access'),
    AutoRoute(
      page: EmptyRouterPage,
      name: 'DashboardRoute',
      path: '/',
      initial: true,
      guards: [RouteGuard],
      children: [
        AutoRoute(path: '', page: DashBoardView),
        AutoRoute(
          page: UserView,
          name: 'UserViewRoute',
          path: ':userId',
          children: [
            AutoRoute(path: 'child_a', page: ChildAView),
            AutoRoute(path: 'child_b', page: ChildBView),
            AutoRoute(
                page: NoAccessView, name: 'NoAccessRoute', path: 'no_access')
          ],
        ),
        RedirectRoute(path: '*', redirectTo: ''),
      ],
    ),
  ],
)
class $WebRouter {}

```

- Code for navigation in `DashBoardView`:
```
onPressed: () {
    context.router.push(UserViewRoute(userId: userId));
    }
```

- Code for navigation in `UserViewRoute`(Where I face the error):
```
print('Routes in stack:${context.router.stack.map((e) => e.name).toList()}');
    _selectedIndex = index;
    if (index == 0) {
      context.router.push(ChildAViewRoute(user: user));
    }
```

The output for the above print statement is:
```
Routes in stack:[DashBoardViewRoute, UserViewRoute]
```

**Version**
Platform: Flutter Web
Flutter: 2.10.4
auto_route: ^3.2.4
auto_route_generator: ^3.2.3

Do let me know if more info is required!

**Comment by Milad-Akarie** [comment]
What route/widget are you navigating from?

**Comment by zexross** [comment]
Thanks for the quick reply!

I was trying to navigate from `UserViewRoute` to sub-route `ChildAViewRoute(user: user)`

**Comment by zexross** [comment]
Hello @Milad-Akarie ,

Sorry for pinging you again. Hope that's fine with you! I don't mean to take much of your time but if you can maybe suggest some things that I can try by which I can debug the error or maybe just understand more clearly what I am doing wrong will be really helpful. Or maybe provide any other suggestion that might be helpful.

If you can guide me a bit then maybe I will be able to resolve the issue and mention my finding or solution here as well.

Thanks for all the communication till now!

**Comment by Milad-Akarie** [comment]
@zexross the assertion implies that you need to push the parent route first, I'm not sure what's missing...

Please print(context.router) right where you're doing the navigation

**Comment by Milad-Akarie** [comment]
Does UserViewPage have an AutoRouter() widget to render child routes?

**Comment by zexross** [comment]
@Milad-Akarie I tried running the code again with the `print(context.router)`. Sharing the output here:
```
DashboardRoute Router
```

> Does UserViewPage have an AutoRouter() widget to render child routes?

Yes, it is using the `AutoRouter()` widget to render the child routes. If I have to describe the journey. `DashBoard` (initial Screen) -> `UserViewPage` -> `ChildAViewPage` (child widget in UserViewPage)


Steps to achieve this navigation:
```
// 1: In DashBoard via button click
context.router.push(UserViewRoute(userId: userId));

// 2: In UserViewPage to render child routes
context.router.push(ChildAViewRoute(user: user));
```

**Comment by zexross** [comment]
There is one more piece of info that I can share if it turns helpful.

When I replace the `context.router.push(ChildAViewRoute(user: user));` with:
```
context.router.push(UserViewPage(userId: userId, children: [ChildAViewRoute(user: user)]));
```

I do achieve the navigation but because of the use of `setState`. This navigation keeps on happening again and again in loop. I believe I can still make the code work but that will not allow me to understand the underlying issue here and thus will hinder me to use the package efficiently.

**Comment by saadqc** [comment]
@zexross : Did you find any solution? I am facing same issue

**Comment by zexross** [comment]
@saadqc Nothing yet. It still is a issue for me. Since, there are other things that I had prioritise I for the time being temporarily choose to navigate the sub widgets using index method and then changing the child widget accordingly using `setState`. But that way deep links within the page is not working currently. Looking forward for the ways through which I can understand what exactly am I doing wrong!

**Comment by saadqc** [comment]
thanks for the prompt response. I will spend sometime and update if I find any solution

**Comment by saadqc** [comment]
Not sure if it will help someone. But in my case, there was conflict with router names. I removed router name in child/nested routes and set the parent route name to "CustomerRouter"

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
        path: '/',
        page: MainScreen,
        initial: true,
        children: [
          AutoRoute(path: 'home', page: HomePage, initial: true),
          AutoRoute(path: 'profile',  page: ProfilePage),
          AutoRoute(path: 'vendors',  page: VendorPage),
          AutoRoute(path: 'customers', name: 'CustomerRouter', page: EmptyRouterPage, // this was set to CustomerRoute which had conflict with child page name 
              children: [
                AutoRoute(path: '', page: CustomerListPage),
                AutoRoute(path: ':customerId', name: 'CustomerDetailsRoute', page: CustomerDetailsPage)
              ]
          ),
          AutoRoute(path: 'take-photo', page: TakePhotoPage),
        ]
    )
  ],
)

class $AppRouter {}

```
