### ISSUE TITLE
Duplicate mapping key.

### ISSUE THREAD

**Issue by tenSunFree** [Milad-Akarie/auto_route_library#1029]
Duplicate mapping key.
<img width="557" alt="111" src="https://user-images.githubusercontent.com/23090085/162560699-89bce7ae-09cb-4098-846e-dfb8f86352c1.png">

maybe you can try to delete or block publish_to: none
<img width="314" alt="2022-04-09_145808" src="https://user-images.githubusercontent.com/23090085/162561183-8a6bb0e6-7178-4d18-af19-1ee338502e12.png">

**Comment by Milad-Akarie** [comment]
looks like it was fixed in one of the merges because I can't see it right now.
