### ISSUE TITLE
[dynamic] is not a class

### ISSUE THREAD

**Issue by YasserOJ** [Milad-Akarie/auto_route_library#103]
Hello,
when I am trying to generate the routes for my app using flutter pub run build_runner build

I'm getting an error and the generated class can't be generated 
 I only see [dynamic] is not a class in the generated class

**Comment by sennraf** [comment]
Did you try to clean and rebuild it? That worked for me.
`flutter packages pub run build_runner clean` and then `flutter packages pub run build_runner build`

**Comment by YasserOJ** [comment]
Hello,
yes I tried it and it still the same

**Comment by Milad-Akarie** [comment]
Hey @YasserOJ Can you show me your router setup?

**Comment by HosseinYousefi** [comment]
I have the same issue. It doesn't work with `[functional_widget](https://pub.dev/packages/functional_widget)` package.

**Comment by rafaelmpessoa** [comment]
I got it locally.

for my case, steps:
`flutter clean`
`flutter pub get`
`flutter pub run build_runner clean`
`flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by rafaelmpessoa** [comment]
I don't know why but I change the absolute path to relative path and works.

```
import 'home/home_page.dart';
import 'receive/receive_message/receive_message_page.dart';
import 'receive/receive_page.dart';
import 'receive/receive_qrcode/receive_qrcode_page.dart';
import 'receive/receive_value/receive_value_page.dart';
import 'transfer/transfer_feedback/transfer_feedback_page.dart';
import 'transfer/transfer_manual/account/transfer_manual_account_page.dart';
import 'transfer/transfer_manual/agency/transfer_manual_agency_page.dart';
import 'transfer/transfer_manual/bank_select/transfer_manual_bank_select_page.dart';
import 'transfer/transfer_manual/description/transfer_manual_description_page.dart';
import 'transfer/transfer_manual/ownership/transfer_manual_ownership_page.dart';
import 'transfer/transfer_page.dart';
import 'transfer/transfer_resume/transfer_resume_page.dart';
import 'transfer/transfer_value/transfer_value_page.dart';
```

**Comment by theweiweiway** [comment]
Closing issue due to:
- stale issue
- possible solution
