### ISSUE TITLE
White screen after refresh

### ISSUE THREAD

**Issue by mvkardashin** [Milad-Akarie/auto_route_library#1030]
I use auto_route 3.2.4.

In app , when I try to hot reload or hot restart , after process complete , the reloaded screen shows for a second and then went whole white

**Comment by Milad-Akarie** [comment]
make sure imitating the root router is not inside a build method.

**Comment by horlann** [comment]
i have the same problem,the root router is not inside a build method.
`
final appRouter = getIt<AppRouter>();

class Application extends StatefulWidget {
  const Application({Key? key}) : super(key: key);

  @override
  State<Application> createState() => _ApplicationState();
}

class _ApplicationState extends State<Application> {
  @override
  Widget build(BuildContext context) {
    return easy_local.EasyLocalization(
        supportedLocales: LangArraysInfo.getTranslateList(),
        path: 'assets/langList',
        child: Builder(builder: (context) {
          return MaterialApp.router(
            routerDelegate: appRouter.delegate(),
            routeInformationParser: appRouter.defaultRouteParser(),
            debugShowCheckedModeBanner: false,
            localizationsDelegates: context.localizationDelegates,
            supportedLocales: context.supportedLocales,
            locale: context.locale,
            color: Colors.green,

            builder: (context, router) => router!,
          );
        }));
  }
}`

**Comment by horlann** [comment]
> make sure imitating the root router is not inside a build method.

i cant fix this problem,i hope for your help

**Comment by mvkardashin** [comment]
Thanks to all.

Root router was in build method, when I moved it from build method, all work great.

**Comment by KDCinfo** [comment]
> > make sure imitating the root router is not inside a build method.
> 
> i cant fix this problem,i hope for your help

@horlann  Moving it out of the build didn't work for me either. I had to move it above, into main, and then pass it as a parameter back into the child widget.

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  final appRouter = AppRouter();

  runApp(
    MyApp(appRouter: appRouter),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
    required AppRouter appRouter,
  })  : _appRouter = appRouter,
        super(key: key);

  // final _appRouter = AppRouter(); // <-- This did not work for me.
  //                                 //     Had to move it up into main().
  final AppRouter _appRouter;

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: _appRouter.defaultRouteParser(),
      routerDelegate: _appRouter.delegate(),
    );
  }
}
```
