### ISSUE TITLE
some issue on line "router.dart:666"

### ISSUE THREAD

**Issue by nishit-dixit** [Milad-Akarie/auto_route_library#1031]
It seems like some internal problem is there with the package and I could not figure out why is it happening.
I'd like someone to help me find if this issue is not from package side.
version used: 3.2.4 

![image](https://user-images.githubusercontent.com/96907962/164159224-926329c3-be63-45c4-a936-c9dd66f4a6da.png)

**Comment by Milad-Akarie** [comment]
This code is from flutter package. 
how to reproduce this?

**Comment by nishit-dixit** [comment]
It happens only once when I reload or launch the app after that things work normally, it just show up in the terminal, if debugging or gets registered to crashlytics, if in release mode.
I'm not sure where to check for this...
I'm attaching the screenshot of the terminal on reloading the app.
![image](https://user-images.githubusercontent.com/96907962/165273240-ec1fa6cc-d8e9-41e4-9cf9-d61e8c3d96b7.png)


It looks like it occurs every time when the routes are being defined from root.
Also I'm using declarative routing for login.
