### ISSUE TITLE
Why each `push` call re-builds all routes in the navigation history?

### ISSUE THREAD

**Issue by bambinoua** [Milad-Akarie/auto_route_library#1032]
I use `auto_route` package for web project to test Navigation 2.0. I use `AutoRoureWrapper` interface to wrap each page with some common `PageScaffold` widget, i.e.
```
class SomePage extends StatefulWidget implements AutoRoureWrapper {
  static const title = '/some-page';
  ...
  Widget wrappedRoute(BuildContext context) {
    return PageScaffold(
      title: title,
      body: this,
    );
  }
  ...
}
```
```
class PageScaffold ... {
}

class _PageScaffoldState ... {
  ...

  @override
  Widget build(...) {
    return FutureBuilder<User>(
      future: futureToGetSidebarItems(),
      builder: (context, snapshot) {
        if(snapshot.hasData) {
          final items = snapshot.data;
          final initialRoute = _getInitialRoute(items);
          return Row(
            children: [
              Sidebar(items: items, initialRoute: initialRoute),
              const VerticalDivider(width: 1),
              Expanded(child: widget.body),
            ],
          );
        },
      },
    );
  }
}

```

I have a `Sidebar` widget which contains list of clickable links to switch to route, using
```
AutoRoute.of(context).pushNamed('<route name>');
```

Now I have a problem when I switch to new page (set new route). Pushing new route forces refresh of **all previously (pushed) created instances of `PageScaffold`** and `Sidebar` widget receives incorrect data. I.e.
 1. Push `Dashboard` page (after authentication). `[PageScaffold(body: Dashboard())]` is in history. Network request for user permissions is executed.
 2. Push `FirstPage` page. `[PageScaffold(body: Dashboard()), PageScaffold(body: FirstPage())]` is in history. 2 network requests for user permissions (pear each page) are executed.
3. Push `SecondPage` page. `[PageScaffold(body: Dashboard()), PageScaffold(body: FirstPage()),, PageScaffold(body: SecondPage())]` is in history. 3 network requests for user permissions (pear each page) are executed.
4. And so on...

**Why so? Why all pushed pages are refreshed and not only last one?** Or what I do wrong?

P.S. When I use default Navigation 1.0 it looks good. Yes, all pushed pages accumulates in history but only latest one is built.

**Comment by Milad-Akarie** [comment]
@bambinoua it had to do with AutoRouteWrapper interface, the method is called everytime the stack changes but the widget shouldn't rebuild. 
anyways, I fixed that and it'll be included in next build.
Thank you for reporting.
