### ISSUE TITLE
How can I use  ScrollController with auto route?

### ISSUE THREAD

**Issue by sh4msi** [Milad-Akarie/auto_route_library#1033]
Hi,
Thanks for the great package you developed🎉 

How can I use ScrollController with auto route?
I want to when I press the current tab again, Move on the page with the help of ScrollController

**Comment by Milad-Akarie** [comment]
@sh4msi  you mean like a PageView scroll effect?

**Comment by sh4msi** [comment]
> @sh4msi you mean like a PageView scroll effect?

Yes, that's the main goal.

  Of course, it would be great if I could have complete control over the scrolling controller

**Comment by sh4msi** [comment]
@Milad-Akarie ،is there no solution to this issue?

**Comment by Milad-Akarie** [comment]
@sh4msi I've been working on implementing a TabsRouter that works with PageView not sure if it's what you're looking for.
