### ISSUE TITLE
White screen on app start

### ISSUE THREAD

**Issue by horlann** [Milad-Akarie/auto_route_library#1034]
That is my app class
![image](https://user-images.githubusercontent.com/61031890/164552281-84cb9e20-d11f-4272-a5b7-4052e19e7c49.png)
happened only 1 time when approuter scaffold in buld

**Comment by horlann** [comment]
https://github.com/horlann/my_crypto my code

**Comment by Milad-Akarie** [comment]
@horlann
I couldn't run your App because of some firebase dep issue, any ways the code looks fine.
 I have a feeling that you're talking about the Native SplashScreen which is white by default, since you're using a Flutter widget as a SplashScreen
 please refer to this
 https://docs.flutter.dev/development/ui/advanced/splash-screen
 and this
 https://pub.dev/packages/flutter_native_splash
 
 let me know if you still have the issue

**Comment by horlann** [comment]
@Milad-Akarie it is 100% problem with materialapp.route(

**Comment by horlann** [comment]
@Milad-Akarie when i replace materialapp.route to default material app all works fine

**Comment by Milad-Akarie** [comment]
@horlann  Can you please strip all firebase deps in a new branch so I can run and check?

**Comment by horlann** [comment]
@Milad-Akarie yes certainly,you can look to branch "test"

**Comment by Milad-Akarie** [comment]
@horlann I'm not sure what's going on but removing the widgets wrapping Material App removes the white flicker.
I don't know how but it seems the wrapping widgets are causing the navigator initializing to be delayed.
https://user-images.githubusercontent.com/55059449/164730317-196b787f-d7ac-4e2d-aa48-2bc071d1bd00.mp4
you can try and use a placeholder widget inside of the delegate with the same background color so the transition is seemless.

**Comment by horlann** [comment]
@Milad-Akarie thank you!Looks like my problem was solved!But i have one question:why pages not showing immediately,them displaying take about 0,3 seconds?

**Comment by Milad-Akarie** [comment]
@horlann you mean after a hard reload?

**Comment by horlann** [comment]
Yes

**Comment by Milad-Akarie** [comment]
will this still happen if you run your App in Release mode?

**Comment by horlann** [comment]
I’m not sure,but it happens occasionally with white screen

**Comment by horlann** [comment]
And  it happens that there is no white screen using the widget easy_localization

**Comment by horlann** [comment]
Why auto_router didn’t work with easy_localization.I thing it should be popular bundle

**Comment by Milad-Akarie** [comment]
@horlann  No idea, the package seemed to be loading some asset files maybe that has some effect.

**Comment by horlann** [comment]
@Milad-Akarie but why is there no such effect when using the standard,only with autorouter

**Comment by Milad-Akarie** [comment]
@horlann  have you tested with the standard MaterailApp.router?

**Comment by dehypnosis** [comment]
Same problem here..

**Comment by itxtoledo** [comment]
Same here. Just add this will solve this issue:


In MaterialApp.router()

```
placeholder: (_) => Container(
                color: Colors.YOURCOLOR,
),
```

**Comment by matthiasn** [comment]
I experienced the same issue and fixed it in this [commit](https://github.com/matthiasn/lotti/commit/7114e18f5b0155d9c306eb7077a0130c2ca8bf2b) by setting the `scaffoldBackgroundColor` in the theme of `MaterialApp.router`, e.g. 

```
                theme: ThemeData(
                  primarySwatch: Colors.grey,
                  scaffoldBackgroundColor: Colors.blue,
                ),
```

**Comment by MatyasK** [comment]
so I'm looking at the same issue, however I can't change my scaffoldbgcolor bc I have to match this white screen with my splashscreen.

The placeholder seems to be removed from MaterialApp.router() what can I do to fix this?
This is my current setup:
![image](https://user-images.githubusercontent.com/15628788/180750526-72e7da07-4f4e-4bff-b39a-afcd85f88fe0.png)

**Comment by SeriousMonk** [comment]
Facing same issue. Even after setting the placeholder the problem persists. This is my configuration
```dart
return MaterialApp.router(
      scrollBehavior: EgoMenuScrollBehavior(),
      routerDelegate: _appRouter.delegate(
        placeholder: (context) => Container(color: themeOrangeColor)
      ),
      routeInformationParser: _appRouter.defaultRouteParser(),
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      debugShowCheckedModeBanner: false,
      title: appName,
      theme: ThemeData(
        primarySwatch: materialThemeOrangeColor,
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.white,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      builder: (context, child){
        /*return Scaffold(
          body: SizedBox.expand(
              child: Container(
                color: themeOrangeColor,
              )
          ),
        );*/
        globalContext = context;
        return child!;
      },
    );
```
If I return the Scaffold in the builder there is no white screen. If I however remove the builder, or return the child like in the code I shared the white screen appears between splash and the main page. This happens even if the main page is just  a Scaffold with an orange container as body.

**Comment by DevanshMathur** [comment]
Thanks @horlann, I solved my issue 
there are two ways to solve this issue
1. Remove localization deligate
2. Make 'load' method in localization delegate as synchronous method by using SynchronousFuture as used below in the class wher you have extends LocalizationsDelegate<AppLocalization>

  @override
  Future<AppLocalization> load(Locale locale) =>
      SynchronousFuture(getAppLocalization(locale));

  AppLocalization getAppLocalization(Locale locale) {
    var localizations = AppLocalization.getInstance;
    localizations.setLocale(locale);
    _locale = locale;
    return localizations;
  }

**Comment by alexeyselina** [comment]
@DevanshMathur didn't work for me. Even without delegates I see this 1-2 seconds white flash.

Solved with placeholder. According to [source](https://github.com/Milad-Akarie/auto_route_library/blob/63fee8f26d7ecb50d08afd3c470d1a34599da55b/auto_route/lib/src/router/controller/auto_router_delegate.dart) it offers this solution as primary instead of defining global scaffoldBackgroundColor in the Theme.

`/// A builder for the placeholder page that is shown`
`/// before the first route can be rendered. Defaults to`
 `/// an empty page with [Theme.scaffoldBackgroundColor].`
 `WidgetBuilder? placeholder;`
