### ISSUE TITLE
Shortened keyword

### ISSUE THREAD

**Issue by sanalkv** [Milad-Akarie/auto_route_library#104]
anyway to shorten  "  ExtendedNavigator.ofRouter<Router>(). " to some other small keyword ?

**Comment by Milad-Akarie** [comment]
Hey @sanalkv I hate long code my self lol
Do you have any suggestions?  I'm trying to keep it clear that the navigator we're using extends the native one.

**Comment by sanalkv** [comment]
I saw that the navigator keyword has been made Deprecated. I would suggest you to add "${router_class_name}Navigator" something like that, So that the keyword stays unique even if you   are using nested navigation. I also faced issue while importing routes, even if you use multiple navigation, all the generated code will have a class called Routes. It would be better if these class names and keywords are unique so that i can avoid prefixing .

**Comment by Milad-Akarie** [comment]
you can pass your preferred Routes class name to the MaterialAutoRouter() annotation

**Comment by sanalkv** [comment]
I saw that, well i was thinking, by default if its possible to make it unique, then that would be great. Anyways Thanks for the reply, expecting a unique navigator keyword pretty soon.

**Comment by theweiweiway** [comment]
Closing issue due to:
- no more long `ExtendedNavigator` in 1.x
