### ISSUE TITLE
Can `auto_route` handle path with few nested pages and arguments for them

### ISSUE THREAD

**Issue by fartem** [Milad-Akarie/auto_route_library#1042]
Hi. I have a question about can `auto_route` handle paths like `/root/category/?id=10&parentId=1/product/190`? In this example path have few pages and each page have arguments that I should put to the path.

**Comment by Milad-Akarie** [comment]
@fartem  auth_route was made for this. 
are you having troubles passing params?

**Comment by Milad-Akarie** [comment]
@fartem  the short answer is unfortunately no, maybe in future builds. 
closing this for now.
