### ISSUE TITLE
Detailed information about pushAndPopUntil

### ISSUE THREAD

**Issue by ihorkozar** [Milad-Akarie/auto_route_library#1044]
Why do the following combinations give different execution results:
1) 
AutoRouter.of(context).pushAndPopUntil(
                    const ARoute(),
                    predicate: (_) => false,
                  );
2) 
AutoRouter.of(context).popUntilRouteWithName(ARoute.name);
AutoRouter.of(context).push(ARoute());

For some reason, when using the second combination, the nested widgets dispose method does not work.
Maybe I'm missing some nuances of pushAndPopUntil (

**Comment by BrunoJurkovic** [comment]
Occurs to me as well, Flutter's default navigator's `pushAndRemoveUntil` works perfectly, while AutoRoute's doesn't push nor pop anything in the stack.
