### ISSUE TITLE
Route must have either a page or a redirect destination.

### ISSUE THREAD

**Issue by cipherhammouda** [Milad-Akarie/auto_route_library#1046]
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    MaterialRoute(page: IntroPage, initial: true),
    MaterialRoute(page: SignInPage),
    MaterialRoute(page: HomePage),
  ],
)
class $AppRouter {}

when I run flutter pub run build_runner watch --delete-conflicting-outputs

it returns :
[SEVERE] auto_route_generator:autoRouteGenerator on lib/core/presentation/routes/app_router.dart:

Route must have either a page or a redirect destination

**Comment by cipherhammouda** [comment]
Not sure what was the problem but I remove the constructor line from signinpage it worked so there you go

**Comment by Milad-Akarie** [comment]
@cipherhammouda  this usually happens when the page widget you're using is not imported correctly during generation.
