### ISSUE TITLE
Don’t Reevaluate When in a Page That Is Not Guarded

### ISSUE THREAD

**Issue by indmind** [Milad-Akarie/auto_route_library#1048]
Hi, I'm trying to make make an ebook app that implements AutoRedirectGuard and has this route:

- HomeRoute [OfflineGuard]
- BookDetailRoute [OfflineGuard]
- BookReaderRoute
- OfflinePage

as you can see, HomeRoute and BookDetailRoute have OfflineGuard, here is what my OfflineGuard looks  like
```dart

class OfflineGuard extends AutoRedirectGuard {
  // ...

  OfflineGuard(this._ref) {
    _auth.addListener(() {
      if (!_auth.isLoggedIn) {
        reevaluate();
      }
    });

    _subscription = Connectivity().onConnectivityChanged.listen(
      (ConnectivityResult result) async {
        try {
          await _dio.get('/test');
        } on DioError catch (e) {
          reevaluate();
        }
      },
    );
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) async {
    final connectivityResult = await (Connectivity().checkConnectivity());

    if (connectivityResult == ConnectivityResult.none) {
      // if still logged in, redirect to offline reader page
      if (_auth.isLoggedIn) {
        router.push(OfflineBooksRoute(
          nextCallback: (success) {
            if (success) {
              resolver.next(true);
              router.removeLast();
            }
          },
        ));
      // otherwise, redirect to login page
      } else {
        router.popUntilRoot();
        router.replace(LoginRoute(
          onLoginCallback: (success) {
            if (success) {
              resolver.next(true);
              router.removeLast();
            }
          },
        ));
      }
    } else {
      resolver.next();
    }
  }

  // ...
}
```

The expected behavior is that:
- When a user is in HomePage or BookDetailPage and suddenly they lost their network connection, they should be redirected to OfflinePage
- When a user is in BookReaderPage and suddenly they  lost their network connection, they SHOULD NOT be directed to OfflinePage

Current behavior:
- When a user is in BookReaderPage and suddenly they  lost their network connection, they still got redirected to OfflinePage

Is there anything I can do to solve my problem? thanks.

**Comment by Milad-Akarie** [comment]
the reevaluation happens to the first guarded page in the hierarchy, it doesn't matter what the current page is.
I don't believe your case is suitable with how `AutoRedirectGuard` works regardless of the name lol
 I'd suggest that you add a listener somewhere inside of you App and shape the navigating stack however you need.  

e.g inside of your App didChangeDependecies method you can do something like this

```dart
  _subscription = Connectivity().onConnectivityChanged.listen(
      (ConnectivityResult result) async {
        try {
          await _dio.get('/test');
        } on DioError catch (e) {
          final router = context.router;
            if(router.current.name == 'BookDetailPage'){
              router.replace(OffineReaderRoute());
            }
        }
      },
    );
  }
```
 
 feel free to re-open if you still have questions.
