### ISSUE TITLE
Need for more control during unknown routes case

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#105]
There are use cases where in we would be writing logic when we see an unknown route.

For example : 
In case of a multi module project which is handled by a main/core module that handles the routing , when the route name doesn't match any route for core module , we may wanna delegate the routing to other sub modules like so : 

```dart
class CoreRouter {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    
    switch (settings.name) {
      // ... handle all known routes of core router

      default:
        for (var module in allOtherModules) {
          var route = module.router.OnGenerateRoute(settings);
          if (route != null) {
            return route;
          }
        }

        return PageRouteBuilder(
          pageBuilder: (context, animation, secondaryAnimation) =>
              RouteNotFoundScreen(
                settings.name,
              ),
          transitionsBuilder: (context, animation, secondaryAnimation, child) {
            return child;
          },
        );
    }
  }
}
```

Can we add some annotation to code generator that lets us run some business logic when some unknown route case happens ? 

I feel like this would be a valuable addition , its not a breaking change anyway. 

### Make @unknownRoute annotation support Function field in the $Router class.

Currently the @unknownRoute annotation is assumed to be put over a class Field in the $Router.

What we can do is , also support a function `Route Function(RouteSettings settings)` that will get a callback whenever an unknown route is detected and expects that a route is returned.

Currently , the Unknown route class would be a widget class and would get only the `String routeName` parameter. so we won't have the full RouteSettings object.

### Add @unknownRouteHandler annotation.
Add @unknownRouteHandler annotation that is specified for a Function field (which accepsts routeSettings and return a `Route`) in `$Router` class  that is called just when the unknown route is detected. This is easier to implement and a relatively neat too.

- I'm looking forward to listening more possible suggestions , solutions etc for this issue from you @Milad-Akarie

**Comment by nateshmbhat** [comment]
any updates on this ? 

@Milad-Akarie

**Comment by Milad-Akarie** [comment]
Hey Nathan, I think an annotated method inside of the router class will do
the trick.

**Comment by nateshmbhat** [comment]
I mean the new @unkownRouteHandler   annotation example?

**Comment by nateshmbhat** [comment]
What if users need control on a particular route.? Say when landing route is got, they need to perform some logic.

Does the library currently allow this?


If not, can we add a parameter to the Route annotation class itself?

Something like routeHandler function that accepts the route settings and expects a Route in return.

**Comment by Milad-Akarie** [comment]
@nateshmbhat I don't know, I think that might make things a bit complex and A router shouldn't be responsible for such work.

That can still be done using a RouteGuard or a Navigation Observer though.

**Comment by Milad-Akarie** [comment]
> I mean the new @unkownRouteHandler annotation example which I suggested earlier ?

Exactly!

**Comment by nateshmbhat** [comment]
> That can still be done using a RouteGuard or a Navigation Observer though.

Hmm makes sense.

Unknown route handler annotation is fine then ?

**Comment by nateshmbhat** [comment]
Can you please implement that annotation ?

**Comment by Milad-Akarie** [comment]
Hey @nateshmbhat I still can't figure out a clean solid way of doing this.
I need to have $Router extend the generated Router or the other way around. 
Do you have any ideas?

**Comment by nateshmbhat** [comment]
I think we can do without meddling with the $Router.

We can accept a parameter called "unknownRouteHandler" function in the constructor of the generated Router class.

In the router generated code, when we hit an unknown route, we execute that function if it's not null.

**Comment by nateshmbhat** [comment]
This is a simple solution and Gives the user control over custom logic execution in unknown route for the router.

**Comment by nateshmbhat** [comment]
any updates on this ?

**Comment by Milad-Akarie** [comment]
Hey @nateshmbhat I apologize for the delay
would this work for you? 
https://pub.dev/packages/auto_route#handling-unknown-routes

**Comment by nateshmbhat** [comment]
Hi the above change is just a syntactic change to the same design that was there in 0.5.0.

If you see the Material App constructor, there is already a parameter called "unknownRouteHandler" which accepts a generate Route function.

I think we should add support for this.
If user is using native navigator he would mostly choose to use this parameter in the material app.

Are we supporting this in auto route?

**Comment by Milad-Akarie** [comment]
Yes if user choses to use the Native navigator they can use the unknownRouteHandler  in MaterialApp
so how about it?

**Comment by nateshmbhat** [comment]
Then I guess there's no issue. It's cool ✌️

Can you mention this with a code sample in the doc under unknown route handling ?

**Comment by Milad-Akarie** [comment]
It's mentioned now
Thanks for your efforts.
