### ISSUE TITLE
An incorrect current tab height inside a SigngleChildScrollView when using AutoTabsRouter

### ISSUE THREAD

**Issue by alexverbitsky** [Milad-Akarie/auto_route_library#1050]
I'm trying to implement a tab navigation at the top of the page. One tab has less content than another, so I'm facing the issue, that the ScrollView height is calculated by the largest child. And a smaller tab has a redundant scroll. I assume that happens because the tabs are added to the stack by the auto_route library.

Here is a demo: https://github.com/alexverbitsky/issue_auto_route_incorrect_tab_height

How can I avoid such behaviour? Thanks in advance.

Flutter doctor's output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
  auto_route: 3.2.4
  auto_route_generator: 3.2.3
  build_runner: 2.1.10

**Comment by Milad-Akarie** [comment]
@alexverbitsky
Please try the new AutoTabsRouter.tabBar implementation
closing this for now.
feel free to reopen if you still have an issue.
