### ISSUE TITLE
If Url path strategy is set, Url navigation is not happening with AutoRoute 

### ISSUE THREAD

**Issue by vishuck** [Milad-Akarie/auto_route_library#1054]
when I edit the Url it's not navigating . Instead I get the below error

------Main file-----------------
 MaterialApp.router(
                             
                             routerDelegate: _appRouter.delegate(),
                              routeInformationParser:
                                  _appRouter.defaultRouteParser(),

---------Error----------------------

Error: Can not resolve initial route
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5374:11)
at auto_router_delegate.AutoRouterDelegate.new.setInitialRoutePath (http://localhost:5000/packages/auto_route/src/router/provider/auto_route_information_provider.dart.lib.js:2050:19)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:40503:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:35432:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:36017:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:36055:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:35897:23)

**Comment by Milad-Akarie** [comment]
@vishuck There's no issue with using path url strategy in general, could you share your router setup? do you have an initial route set?

**Comment by vishuck** [comment]
This is my  router.dart 


@MaterialAutoRouter(

  routes: [
    AutoRoute(
      page: AuthRouter,
      initial: true,
    ),
    AutoRoute(
      page: ProjectRequests,
      path: 'event',
      guards: [EventGuard],
    ),
    AutoRoute(
      page: RecurringEventsList,
      path: 'eventRecurring/:parentEventId',
      guards: [EventGuard],
    ),

**Comment by vishuck** [comment]
HI Milad-Akarie,

This is my router.dart

@MaterialAutoRouter(

routes: [
AutoRoute(
page: AuthRouter,
initial: true,
),
AutoRoute(
page: ProjectRequests,
path: 'event',
guards: [EventGuard],
),
AutoRoute(
page: RecurringEventsList,
path: 'eventRecurring/:parentEventId',
guards: [EventGuard],
),

When I try to copy and paste the Url in the new browser  or when I
edit the url , It's throwing the error. can not resolve initial path.

added <base href='/'> in index.html.
configured firebase.json.
but its not working.

**Comment by Milad-Akarie** [comment]
@vishuck root routes should start with a '/', that might be the issue. 
try this
```dart
routes: [
AutoRoute(
page: AuthRouter,
initial: true,
),
AutoRoute(
page: ProjectRequests,
path: '/event',
guards: [EventGuard],
),
AutoRoute(
page: RecurringEventsList,
path: '/eventRecurring/:parentEventId',
guards: [EventGuard],
),
```

**Comment by vishuck** [comment]
Hi Milad-Akarie

                    Thank You. I will try this and get back to you.
Regards,
Vishnu C K

**Comment by vishuck** [comment]
Hi Milad-Akarie,

                      That worked fine for me. Thank you.
 Can you tell me how to set the query parameter while using a
DropDownbutton ?
 And In mobile, How will we navigate using the path ex:
home/feeds?id=534535 . where will  I pass the path while loading the app
(using AutoRoute).
note: Both web and mobile have the same router.dart, same paths, when i tap
on URL it should take me to the respective screen in the mobile app, so
where will i Pass the path in the mobile app.?

Regards,
Vishnu  C K

**Comment by Milad-Akarie** [comment]
@vishuck  you can pass the path to `delegate(initialDeepLink: 'your path')`

**Comment by vishuck** [comment]
When dropdown is tapped its not opening at all.
I am getting this error when I tap on it 
![dropdown](https://user-images.githubusercontent.com/93113415/168724013-5448d051-b7a4-4da6-85bb-2f9bb0fb0d6f.png)
![button](https://user-images.githubusercontent.com/93113415/168724053-619f593d-03f1-4b2e-8969-dd2bdb4c0911.png)
drop down code is below.
![dropdowncode](https://user-images.githubusercontent.com/93113415/168724324-e3d5d277-a5c4-4e68-9140-a9ca783310a0.png)

**Comment by Milad-Akarie** [comment]
@vishuck  no idea what's going on here, I don't think this's a navigation issue.
