### ISSUE TITLE
Disable null safety build runner ?

### ISSUE THREAD

**Issue by guillaumeboussion** [Milad-Akarie/auto_route_library#1056]
Hi, first, thanks for this amazing package that saved me many hours of custom implementation for nested routing..!

I'm trying to use auto_route library with build_runner, but each time my build_runner generate my router.gr.dart file, it does generate code with null safety, while I'm not using it in my project.

Is there a way to tell build_runner to generate code without NullSafety feature ?

My project's dart sdk is: ">=2.5.2 <3.0.0"

**Comment by Milad-Akarie** [comment]
Hello @guillaumeboussion I'm afraid there's no way to disable null safety now, maybe try older versions e.g 1.0.0

closing this now
