### ISSUE TITLE
Url query parameters not available after going through a AutoRedirectGuard

### ISSUE THREAD

**Issue by maks** [Milad-Akarie/auto_route_library#1058]
I'm seeing the very same thing as in #607 but with a webapp.

I have just 2 top level routes:
```
routes: <AutoRoute>[
    AutoRoute<ReaderScreen>(
      initial: true,
      path: "/reader",
      page: ReaderScreen,
      guards: [
        ReaderAuthGuard,
      ],
    ),
    AutoRoute<LoginScreen>(
      path: "/login",
      page: LoginScreen,
    ),
  ],
```

Now for my ReaderScreen I need a query param, so eg when I navigate to http://localhost:1234/reader?book=foobar

I expect then to get the query param in my reader widget, eg.
```
class ReaderScreen extends ConsumerStatefulWidget {
  const ReaderScreen({
    Key? key,
    @QueryParam("book") required this.book,
...
```
Now the above works fine without the AuthGuard, but with the authguard, after the `resolver.next(true);` call inside my authguards  `onNavigation()` the book parameter passed into ReaderScreen is null 😢 

Am I doing something wrong? or is there another way I should be implementing this?

**Comment by Milad-Akarie** [comment]
@maks I just tested this every way possible query param is passed everytime. 
how do I reproduce this? what's inside of your guard?

**Comment by maks** [comment]
@Milad-Akarie thank you for looking at this so quickly!

Sorry for not providing more details to start with.

I've created a repo with a minimal reproduction of the issue: https://github.com/maks/autoroute_queryparams
you can see the issue I'm having on the main branch, while I have another branch showing the query param working when the authguard is removed: https://github.com/maks/autoroute_queryparams/tree/no-authguard

**Comment by Milad-Akarie** [comment]
@maks  I didn't realize you were talking about `AutoRedirectGuard` I'll test it out. 
the guard is made so it can auto- redirect users to login screen for example if auth status doesn't allow the guarded screen, it was refactored in auto_route 4.0.0, can you please use the new code and let me know if you still get the issue?

**Comment by maks** [comment]
@Milad-Akarie thank you! I had not seen that you recently release 4.0.0
I just updated my example app above to `4.0.1`, as I'm now also using Flutter 3.0 and the new AutoRedirectGuard works with url query parameters 🎉 
Thanks again!
