### ISSUE TITLE
LoginRouteArgs can not be null because it has a required parameter

### ISSUE THREAD

**Issue by adpmhel24** [Milad-Akarie/auto_route_library#1059]
Why I got this error when i refresh the login page?

<img width="1042" alt="Screen Shot 2022-05-10 at 8 29 37 PM" src="https://user-images.githubusercontent.com/40779451/167628606-91804597-77a8-41b6-9c19-860b83cf1d48.png">

**Comment by Milad-Akarie** [comment]
@adpmhel24  if you want your route to be refreshed without problems you should only use path params or query params, so the params are always stored in the url.
when you hit the refresh button flutter re-runs your entire App with the URL in browser as initial link. 

closing this for now. 
Feel free to reopen if you have more questions.
