### ISSUE TITLE
Is it possible to set transition on initial route

### ISSUE THREAD

**Issue by Haidar0096** [Milad-Akarie/auto_route_library#106]
Right now I tried this:
```
@CustomAutoRouter(transitionsBuilder: TransitionsBuilders.slideLeft,durationInMilliseconds: 2000)
class $Router{
  @initial
  SplashScreen splashScreen;
  SignInScreen signInScreen;
}
```
But couldn't get the slide left animation to work on the initial route but it works on other routes,
can I do it to initial route as well?

**Comment by Milad-Akarie** [comment]
@Haidar0096 unfortunately that's not possible with the current Navigator setup.

**Comment by Haidar0096** [comment]
Thanks for the reply, are you saying this is not available due to your implementation or due to the framework limitations?

**Comment by Milad-Akarie** [comment]
@Haidar0096 The Navigator adds initial routes to the stack without any transitions. I believe what you need is working on the native side?

**Comment by Haidar0096** [comment]
> @Haidar0096 The Navigator adds initial routes to the stack without any transitions. I believe what you need is working on the native side?

So If I get you this(adding a transition to the initial route) is a limitation in the framework and not in the package.
And I think you are right I will try writing in the native side.
Thanks again!

**Comment by Haidar0096** [comment]
> > @Haidar0096 The Navigator adds initial routes to the stack without any transitions. I believe what you need is working on the native side?
> 
> So If I get you this(adding a transition to the initial route) is a limitation in the framework and not in the package.
> And I think you are right I will try writing in the native side.
> Thanks again!

@Milad-Akarie ??

**Comment by Milad-Akarie** [comment]
@Haidar0096 That's what I'm saying yes.
