### ISSUE TITLE
[Big Issue] AutoTabsRouter.tabBar + bottomNavBar lags

### ISSUE THREAD

**Issue by MindMayhem** [Milad-Akarie/auto_route_library#1061]
Hello, the problem is that when using AutoTabsRouter.tabBar in conjunction with BottomNavigationBar, tabBarView does not have time to switch between tabs when the user quickly switches tabs to BottomNavBar

AutoTabsRouter ignores tab clicks on BottomNavBar until transition animation ends

**Comment by Milad-Akarie** [comment]
@MindMayhem if you're going to use bottom navBar try AutoTabsRouter.pageView instead. 
could you show me some code?

**Comment by MindMayhem** [comment]
```
AutoTabsRouter.tabBar(
        homeIndex: 0,
        navigatorObservers: () => [HeroController()],
        routes:  ///,
        builder: (context,child,controller) => Scaffold(
                  backgroundColor:  ///,
        extendBody: true,
          body: child,
          bottomNavigationBar: BottomNavigationBar(
              backgroundColor:  ///,
              type: BottomNavigationBarType.fixed,
              items: const [
                BottomNavigationBarItem( ), // shortened for code-readability
                BottomNavigationBarItem( ), // shortened for code-readability
                BottomNavigationBarItem( ), // shortened for code-readability
                BottomNavigationBarItem( ), // shortened for code-readability
              ],
              currentIndex: controller.index,
              selectedItemColor: Colors.white,
              unselectedItemColor: Colors.grey,
              onTap: (index) => controller.index = index,
            ),
          ),
        ),
      );
```

I'll try pageView and write back

**Comment by MindMayhem** [comment]
Created another issue (https://github.com/Milad-Akarie/auto_route_library/issues/1062)

**Comment by Milad-Akarie** [comment]
@MindMayhem  I still don't understand the problem, could you video record what happens?

**Comment by Milad-Akarie** [comment]
@MindMayhem I tried with the simulator just now but I couldn't get it to rep-reduce this. 
I'm suspecting something thu 
inside of `AutoTabsRouter` line 555
try changing this line 
```dart
if (_controller!.activeIndex != _tabController.index && !_tabController.indexIsChanging) 
to this 
if (_controller!.activeIndex != _tabController.index) 
```
and see if it still happens
Make sure you you hard reload after doing this to make sure you're using the updated code.

let me know if this fixes your issue so I can update the source code.

**Comment by MindMayhem** [comment]
@Milad-Akarie nope, still can reproduce it, rebuilded whole app for be sure
But it makes little bit heavier to reproduce it, seems like it has little positive affection to this issue
![image](https://user-images.githubusercontent.com/39557395/167721852-221dc5a6-6557-40cb-a7e0-e79e40cf4640.png)
