### ISSUE TITLE
[Issue] AutoTabsRouter.pageView animates only on adjacent tabs

### ISSUE THREAD

**Issue by MindMayhem** [Milad-Akarie/auto_route_library#1062]
Hello again, there's another issue, now with **pageView**.

The router simply ignores the animation when we changing non-adjacent tabs, but when the animation changing to a adjacent tab (from the first to the second, for example) - everything works correctly

**Comment by Milad-Akarie** [comment]
@MindMayhem  That's actually closed for a reason, if you animate from index 0 to index 2 for example page controller animation goes throw 1 index as well resulting to weird page animation. 
so I just closed it for now until I find a way to fix that behaviour.
This's how the animation looks like without the check
https://user-images.githubusercontent.com/55059449/167706993-36e165cb-4388-4391-80bf-68f3b62a1219.mp4

TabBarView fixes this issue by replacing child views and faking the active one, maybe you can use that if your other issue is resolved. 

closing this for now.

**Comment by MindMayhem** [comment]
https://user-images.githubusercontent.com/39557395/167707029-5c7969a2-db74-4965-808a-5c4f85dfcfe5.mp4
