### ISSUE TITLE
[Issue] AutoTabsRouter.tabBar - visible TabBarView index changing while we change non-adjacent tab

### ISSUE THREAD

**Issue by MindMayhem** [Milad-Akarie/auto_route_library#1063]
Hello **again**

**TabBarView** in this package works differently than the usual TabBarView, there is a noticeable change in the index before the animation of changing tabs starts.
When we change adjacent tabs - everything works correctly, issue comes only on non-adjacent tabs

**Comment by Milad-Akarie** [comment]
@MindMayhem  How are you changing activeIndex?

**Comment by MindMayhem** [comment]
> @MindMayhem How are you changing activeIndex?

`context.tabsRouter.setActiveIndex(index);`

**Comment by MindMayhem** [comment]
https://user-images.githubusercontent.com/39557395/167706371-363af7db-544e-4e07-bd80-72d88e55d45c.mp4

Slowed by 5x, but it still noticeable on normal speed

**Comment by Milad-Akarie** [comment]
@MindMayhem Got it, I'll see what I can do.

**Comment by MindMayhem** [comment]
@Milad-Akarie interesting notice: when i made it using .builder instead of .tabBar - everything works correctly
Got code from https://github.com/Milad-Akarie/auto_route_library/pull/1052#issuecomment-1117719619

**Comment by Milad-Akarie** [comment]
@MindMayhem when you used builder you used the default `TabBarView` which doesn't have this issue, the default `TabBarView` is causing some other problems when integrated with deep-link and path navigation which when I tried to fix I screwed something in the default behaviour apparently. 
Using the `TabBarView` might be enough for your usecase, maybe you can keep that for now  until I find a way to fix the `CustomTabBarView`
