### ISSUE TITLE
auto_route.dart export duplicate 'src/router/widgets/auto_router.dart'

### ISSUE THREAD

**Issue by AlanNggg** [Milad-Akarie/auto_route_library#1064]
<img width="414" alt="Screenshot 2022-05-12 004312" src="https://user-images.githubusercontent.com/41237850/167903155-a94d54af-3c3f-4a6e-a8a8-06cea391bc98.png">
I found that export 'src/router/widgets/auto_route_navigator.dart' is missing. Maybe one of the export 'src/router/widgets/auto_router.dart' should be export 'src/router/widgets/auto_route_navigator.dart' ?

**Comment by Milad-Akarie** [comment]
fixed in version 4.0.1
