### ISSUE TITLE
How to showDialog with previous route in background

### ISSUE THREAD

**Issue by petoknm** [Milad-Akarie/auto_route_library#107]
I was using `showDialog()` with `AlertDialog` to display a dialog over the current route like so:

![Screenshot from 2020-05-19 11-49-51](https://user-images.githubusercontent.com/5087675/82312132-eb641300-99c6-11ea-99d2-099379a2dacb.png)

But when using `auto_route` with something like this:

```
class $Router {
  ...
  @MaterialRoute(fullscreenDialog: true)
  FeedbackDialog feedbackDialogRoute;
}
```

I get the dialog but in the background of the dialog I cannot see the previous route. I tried it with and without the `@MaterialRoute` decorator.

**Comment by Milad-Akarie** [comment]
@petoknm I think you might be confusing AlertDialogs with actual screen routes that's decorated as FullScreenDialogs. You can still use your alert dialogs as you used to without auto_route.
You can read more about it here 
https://material.io/components/dialogs#usage

**Comment by Milad-Akarie** [comment]
closing this for now. feel free to reopen if you have any more queries.
