### ISSUE TITLE
AutoRouteWrapper not working as well on Flutter 3.0.0

### ISSUE THREAD

**Issue by husainazkas** [Milad-Akarie/auto_route_library#1071]
I was use this way to wrap widget tree with bloc provider, this worked fine until upgraded the flutter version to 3.0.0

The error is just widget tree can't get the provider scoped. I know the solution, we can wrap widget tree with `builder` or put the provider outside the stateless/full widget, but the point of this issue is not the alternative way. I want to know how can I use AutoRouteWrapper again to wrap widget tree with bloc provider at current version.

Flutter SDK : 3.0.0
auto_route: 4.0.1

Thanks for every contributors!

**Comment by TechDockDev** [comment]
yes auto router is not working with flutter 3

**Comment by vcoutasso** [comment]
I'm also having issues with AutoRouteWrapper with the very same SDK and flutter_route versions

**Comment by Milad-Akarie** [comment]
@TechDockDev @vcoutasso  have you upgraded `auto_route_generator` as well?

**Comment by sobimor** [comment]
@Milad-Akarie 

I confirm the issue with the last version of auto_route and auto_route_generator.
`
auto_route: ^4.0.1 
`
`
auto_route_generator: ^4.0.0
`


flutter doctor: 
`
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
`

**Comment by Milad-Akarie** [comment]
@sobimor @vcoutasso @TechDockDev 
for some reason I had to wrap routes at generation time in version 4.0.0 to prevent unnecessary builds. 
but now that I realized it's confusing I'm gonna find a way to do it without the need for generation. 

for now running the generation should fix your issue.

**Comment by sobimor** [comment]
@Milad-Akarie 

My issue is solved by re-run build_runner.

@magician20 

Did you use the below command for running build_runner?

`flutter pub run build_runner build --delete-conflicting-outputs`

Because I had the same issue by running build_runner without the `--delete-conflicting-outputs` flag.

**Comment by vcoutasso** [comment]
My issue was solved by re-running `build_runner` with the `--delete-conflicting-outputs` flag, thanks @Milad-Akarie!

**Comment by Turbozanik** [comment]
Same here:
 
```This builder requires Dart inputs without syntax errors.
However, package:quiz_time/base/widgets/custom_toolbar.dart (or an existing part) contains the following errors.
custom_toolbar.dart:11:43: This requires the 'super-parameters' language feature to be enabled.

Try fixing the errors and re-running the build.

[INFO] Running build completed, took 18.0s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 47ms

[SEVERE] Failed after 18.0s
pub finished with exit code 1

```

Will this be fixed, or should I rollback to a lower flutter/auto_route version?

**Comment by Maqcel** [comment]
Any update on this. Facing same issue.
`auto_route: 4.0.1`
`auto_route_generator: 4.0.0`
`[✓] Flutter (Channel stable, 3.0.1, on macOS 12.0.1 21A559 darwin-arm, locale pl-PL)
    • Flutter version 3.0.1 at /opt/homebrew/Caskroom/flutter/2.10.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2`

**Comment by husainazkas** [comment]
> @Milad-Akarie
> 
> My issue is solved by re-run build_runner.
> 
> @magician20
> 
> Did you use the below command for running build_runner?
> 
> `flutter pub run build_runner build --delete-conflicting-outputs`
> 
> Because I had the same issue by running build_runner without the `--delete-conflicting-outputs` flag.

Thanks for advice! I tried this solution a few days ago and it worked.

After some inspection, the reason why we need to re-run build_runner with `--delete-conflicting-outputs` flag is in the generated file, the page will be wrapped with new stateless widget provided by auto_route package called as `WrappedRoute`.

So, I will close this issue. Thanks for everyone!
