### ISSUE TITLE
[Root router ] Router can  not navigate to 

### ISSUE THREAD

**Issue by vishuck** [Milad-Akarie/auto_route_library#1072]
Below is my router.dart
![router dart](https://user-images.githubusercontent.com/93113415/168245415-570d643a-8128-40d1-bbdf-9bb21e587019.png)

Navigation file
![navigation](https://user-images.githubusercontent.com/93113415/168245484-05cf37eb-78d9-4ec4-8de8-b067cd05ffc6.png)

error 
![error](https://user-images.githubusercontent.com/93113415/168245531-0e68baeb-4bdd-46b5-8d16-dfcae3db1709.png)

Not able to navigate to the child 
can you help me out what is the issue here .
Could not navigate from explorepage to exploresearch page

**Comment by Milad-Akarie** [comment]
@vishuck  According to your setup both `ExplorePage` and `ExploreSearchPage` should have an `AutoRouter` Widget  (to render child routes ) inside of them, is that the case?

**Comment by vishuck** [comment]
![explore navigation](https://user-images.githubusercontent.com/93113415/168426597-d1f80979-3cc2-4d12-9b75-18c0a42bbe6a.png)
yes both have AutoRouter

**Comment by vishuck** [comment]
Here exploresearchpage is the child of explore page 
This is in mobile app. since web app has the path , explore/search/ even i need the same in mobile app to map the path. 
first step: navigates to explore page
second  : should navigate to exploresearchpage.

But when  i take exploresearchpage out of the children its navigating , but when i add it as a child of explore page its throwing me the error .
