### ISSUE TITLE
How can I maintain state with AutoTabsScaffold

### ISSUE THREAD

**Issue by amanokerim** [Milad-Akarie/auto_route_library#1073]
I suspect that this is obvious thing, but anyway)

I have router:
```
    AutoRoute(guards: _welcomeAuth, page: MainPage, initial: true, children: [
      AutoRoute(path: 'feed', page: FeedPage),
      AutoRoute(path: 'ownLots', page: OwnLotsPage),
      AutoRoute(path: 'personal', page: PersonalAreaPage),
      AutoRoute(path: 'chats', page: ChatsPage),
      AutoRoute(path: 'legal', page: LegalInformationPage),
    ]),
```

And, AutoTabsScaffold:
```AutoTabsScaffold(
      routes: ...,
      appBarBuilder: ...,
      builder: (context, child, animation) => FadeTransition(
          opacity: animation,
          child: KeyedSubtree(
              key: ValueKey(context.tabsRouter.current.name), child: child)),
      bottomNavigationBuilder: (context, tabsRouter) => AppBottomNavigationBar(
        tabs: bottomTabs,
        currentIndex: tabsRouter.activeIndex,
        onTap: tabsRouter.setActiveIndex,
      ),
    );
    ```

And, each time, when I switch tabs, on my screens runs methods initState and dispose, and all data loads from the server.
How can I save data when changing tabs.

Tried maintainState: true on routes, didn't help.

**Comment by Milad-Akarie** [comment]
@amanokerim  state is maintained by default in `AutoTabsScaffold`
In your example the `KeyedSubtree` will create a newState eveytime the `ValueKey` changes, and tabsRouter.current is changed based on activeIndex. 
are you having the same behaviour without the KeyedSubtree widget?

**Comment by amanokerim** [comment]
@Milad-Akarie My bad(
Thought, that ValueKey reverts same key, when returning to the tab.
Thank you!
