### ISSUE TITLE
AutoRedirectGuard now requires canNavigate

### ISSUE THREAD

**Issue by vanth0me** [Milad-Akarie/auto_route_library#1075]
Hello,

I have been using AutoRedirectGuard to protect my routes based on my provider. With an addListener I could call reevaluate, to make sure the user is always authenticated in my provider.

With the new 4.0.0 version you now have to implement canNavigate, what to enter here? I couldn't find anything in the docs.

Thanks in advance!

**Comment by Milad-Akarie** [comment]
@vanth0me I needed to know whether  the guard can still allow routes to prevent unnecessary reevaluation. 
here's an example usage
https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/web/router/web_auth_guard.dart

**Comment by vanth0me** [comment]
Thanks for the example. These are a bit harder to find, maybe it's possible to make these more accessible?

**Comment by Milad-Akarie** [comment]
@vanth0me  I'll try to add a link in readme file.
