### ISSUE TITLE
NavLink is not found

### ISSUE THREAD

**Issue by chhinsras** [Milad-Akarie/auto_route_library#1077]
```
Column(
              children: [
                NavLink(label: 'Dashboard', destination: DashboardRoute()),
                NavLink(label: 'Changelogs', destination: const AuditRoute()),
                // NavLink(label: 'Settings', destination: const SettingsRoute()),
              ],
            ),
```

**Comment by Milad-Akarie** [comment]
@chhinsras  NavLink is simple class I made for the example to help keep  things clean
it looks something like this 

```dart
class NavLink {
  final PageRouteInfo route;
  final IconData icon;
  final String label;

  const NavLink({
    required this.route,
    required this.icon,
    required this.label,
  });
}
```

**Comment by chhinsras** [comment]
> @chhinsras NavLink is simple class I made for the example to help keep things clean it looks something like this
> 
> ```dart
> class NavLink {
>   final PageRouteInfo route;
>   final IconData icon;
>   final String label;
> 
>   const NavLink({
>     required this.route,
>     required this.icon,
>     required this.label,
>   });
> }
> ```

Thanks. it's better to update on the document for removing confusion.

**Comment by chhinsras** [comment]
Is it possible to style for active link like sidenav?

**Comment by jordandevogelaere** [comment]
Hi,

Where can I find the widget that uses the Navlink class?

```
Column(
              children: [
                NavLink(label: 'Dashboard', destination: DashboardRoute()),
                NavLink(label: 'Changelogs', destination: const AuditRoute()),
                // NavLink(label: 'Settings', destination: const SettingsRoute()),
              ],
            ),
```

Navlink is not a widget ...

Thanks for your help.

**Comment by chhinsras** [comment]
> Hi,
> 
> Where can I find the widget that uses the Navlink class?
> 
> ```
> Column(
>               children: [
>                 NavLink(label: 'Dashboard', destination: DashboardRoute()),
>                 NavLink(label: 'Changelogs', destination: const AuditRoute()),
>                 // NavLink(label: 'Settings', destination: const SettingsRoute()),
>               ],
>             ),
> ```
> 
> Navlink is not a widget ...
> 
> Thanks for your help.

create your own widget class "NavLink"

**Comment by jordandevogelaere** [comment]
@chhinsras I was already that far ;-) I was just wondering how to handle the navigation in the NavLink "widget". The example is not that clear. 

Thanks

**Comment by chhinsras** [comment]
> @chhinsras I was already that far ;-) I was just wondering how to handle the navigation in the NavLink "widget". The example is not that clear.
> 
> Thanks

FYI , please see this as reference https://github.com/chhinsras/MiniStarter/blob/main/hybrid/lib/routes/app_router.dart
