### ISSUE TITLE
Initialdeeplink navigation issue

### ISSUE THREAD

**Issue by vishuck** [Milad-Akarie/auto_route_library#1078]
Initial deep link navigates to the link provided for 2 secs and goes back to the normal route
could you please help me to resolve this

**Comment by Milad-Akarie** [comment]
@vishuck I can't possible tell what's causing that, could you make an example that reproduces the issue and invite me to it?

**Comment by adar2378** [comment]
I'm also having this issue. I will post a detailed observation regarding this. But what it looks like that when the is terminated and opens from a deep link then it goes to the deep link route and after 1-2 seconds it goes back to the initial route.

**Comment by ildarnm** [comment]
I face the same bug, but only on iOS. On android, the deep linking works perfectly.

**Comment by vishuck** [comment]
Hi @Milad-Akarie 

Can we connect regarding the issue ?

**Comment by melWiss** [comment]
is this fixed?
