### ISSUE TITLE
About implementing AppLifecycleState

### ISSUE THREAD

**Issue by ksmsk** [Milad-Akarie/auto_route_library#108]
I want to check auth state everytime app resumes. Is there a way to solve this in the library using guards or should i use standard flutter way `WidgetsBindingObserver` interface in every screen? Using `WidgetsBindingObserver` in screens didn't feel right to me as you need to check auth state in two places.

**Comment by Milad-Akarie** [comment]
Hey @ksmsk why not register WidgetsBindingObserver in your AppWidget?

**Comment by ksmsk** [comment]
hey @Milad-Akarie, if i register WidgetsBindingObserver in App Widget that would be before registering router so i can't use router for redirecting. i solved problem by creating a mixin for screen widgets. I just wonder if i can solve it by using guards or other tools in the library. i dig into source code and found out you can register route observers but couldn't be sure how to use them.

**Comment by atoumbre** [comment]
Hey @ksmsk 
Were you able to figure out a solution?

**Comment by ksmsk** [comment]
hey @atoumbre. I solved the problem by creating a landing screen.

routes.dart:
```dart
@MaterialAutoRouter()
class $Router {
  @initial
  LandingScreen landingScreenRoute;

  @GuardedBy([GuestOnlyGuard])
  LoginScreen loginScreenRoute;

  @GuardedBy([AuthGuard])
  TopicScreen topicScreenRoute;
  
  ...
}
```

landing_screen.dart:
```dart
class LandingScreen extends StatefulWidget {
  @override
  _LandingScreenState createState() => _LandingScreenState();
}

class _LandingScreenState extends State<LandingScreen>
    with WidgetsBindingObserver {
  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        final authState = getIt<AuthState>();
        if (!await authState.checkAuth()) {
          ExtendedNavigator.rootNavigator
              .pushReplacementNamed(Routes.loginScreenRoute);
        }
        break;
      default:
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    final authState = getIt<AuthState>();
    authState.checkAuth().then((authenticated) {
      if (authenticated) {
        ExtendedNavigator.rootNavigator
            .pushReplacementNamed(Routes.topicScreenRoute);
      } else {
        ExtendedNavigator.rootNavigator
            .pushReplacementNamed(Routes.loginScreenRoute);
      }
    }).catchError(() {
      authState.removeAuth();
      ExtendedNavigator.rootNavigator
          .pushReplacementNamed(Routes.loginScreenRoute);
    });
  }

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: CircularProgressIndicator(),
    );
  }
}
```
When app is started first time, it checks if user have valid authentication and registers `AppLifeCycleState` in the meanwhile. Since landing_screen can be initialized only one time i didnt need to dispose the observer. Only one registered observer will be available until app is closed. It's not the most elegant way but gets the job done.

**Comment by theweiweiway** [comment]
Closing issue due to:
- possible solution
- stale issue
