### ISSUE TITLE
Question about no transition animation pop

### ISSUE THREAD

**Issue by aboutlan** [Milad-Akarie/auto_route_library#1083]
I have a requirement that there are two buttons in the page, when I click button A there is a pop transition animation, but when I click button B there is no pop transition animation. I'm trying to dynamize the `reverseDurationInMilliseconds` parameter of `CustomRoute`, but it only allows passing in constants. I know that it is related to the code generator. So is there any other way to solve the problem? Thanks!

**Comment by Milad-Akarie** [comment]
@aboutlan unfortunately dynamic animation transitions is yet to come to auto_route.
