### ISSUE TITLE
Initial route transition 

### ISSUE THREAD

**Issue by moti0375** [Milad-Akarie/auto_route_library#109]
Hi,

Can InitialRoute have a transition?
I've tried to set it as following:
`//login_router.dart`
`@CustomRoute(initial: true, transitionsBuilder: slideRightTransition,durationInMilliseconds: 1000) `
`LoginPage loginPage;`

And adding the route as a widget like this:
`home: ExtendedNavigator<LoginRouter>(router: LoginRouter())`

But no transition happens.

**Comment by Milad-Akarie** [comment]
@moti0375 initial routes are added to the stack not pushed unless they're guarded
