### ISSUE TITLE
Introduce optional re-generating of specific routes

### ISSUE THREAD

**Issue by chrisoftech** [Milad-Akarie/auto_route_library#11]
Thanks for this awesome package to simplify routing.
In my use case, trying to provide a bloc to my route page seem impossible since the route file is auto regenerated on build_runner watch  thus clearing my changes made to the route.gr.dart file. My suggestion would be to annotate a specific route with @noAutoGenerate or something related to disable the route from re-generating.

thanks.

**Comment by Milad-Akarie** [comment]
Thanks for your efforts.
Fixed in v0.2.1 with AutoRouteWrapper 
see https://pub.dev/packages/auto_route#handling-wrapped-routes
