### ISSUE TITLE
Using guard on initial page causing white screen flickering

### ISSUE THREAD

**Issue by ksmsk** [Milad-Akarie/auto_route_library#110]
Using guards showing blank page before guarded route on initialization. it's like router tries to make transition from a blank page to initial page.

guard is simply return true for testing purpose:
```dart
class GuestOnlyGuard extends RouteGuard {
  @override
  Future<bool> canNavigate(
    ExtendedNavigatorState navigator,
    String routeName,
    Object arguments,
  ) async {
    return true;
  }
}
```
route:
```dart
@MaterialAutoRouter()
class $Router {
  @GuardedBy([GuestOnlyGuard])
  @initial
  LoginScreen loginScreenRoute;
}
```
app:
```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(builder: (_, __) {
      return ExtendedNavigator<Router>(
        router: Router(),
        guards: [AuthGuard(), GuestOnlyGuard()],
      );
    });
  }
}
```
i screencapped problem. i am hot restarting where flickering occurs.
![guardbug2](https://user-images.githubusercontent.com/17592227/82462468-47609180-9ac4-11ea-93c2-60d0161eba0e.gif)

**Comment by Milad-Akarie** [comment]
Hey @ksmsk for me to guard the initialRoute I had to push a blank white page first because navigator doesn't build unless it has at least one route in stack. 
That didn't happen before so I'm guessing you're either using custom transitions on the initial Route or something changed in flutter 1.17.1!

**Comment by ksmsk** [comment]
hey @Milad-Akarie, thanks for feedback. I tested it with minimal setup so i didn't use anything besides those code i put in issue as example. I tested again with another case and white page still visible splitsecond eventhough it didn't make transition animation. However i understand it's technical limitation. It would be nice if it can be customized. I will avoid using guard on initial route. Thanks again.

**Comment by sanalkv** [comment]
any update on this? can guard be used for initial page ?

**Comment by Milad-Akarie** [comment]
@ksmsk @sanalkv 
I wouldn't recommend guarding the initial route but if you need to, use a CustomRoute() with no transitions to avoid flickering.
Check out the new auto_route: 0.6.0

**Comment by sanalkv** [comment]
Thanks.
