### ISSUE TITLE
ScrollPhysics should be user defined for `AutoTabsRouter.tabBar()` and `AutoTabsRouter.pageView()`.

### ISSUE THREAD

**Issue by kishan-dhankecha** [Milad-Akarie/auto_route_library#1109]
### issue
- The physics while using `AutoTabsRouter.tabBar()` or `AutoTabsRouter.pageView()` is set to `ClampingScrollPhysics()`.
- In my app I doesnt want to allow user to scroll through tabview.

### preview

https://user-images.githubusercontent.com/68430205/173317490-cf5e7921-4b1f-4182-8e86-d894fb42ab3e.mp4

### solution
- Give the user option to choose physics themselves.
- Add optional parameters in both the constructors.

**Comment by 2shrestha22** [comment]
Any timeline to merge this update? We need this.

**Comment by Milad-Akarie** [comment]
done in version 4.1.0
