### ISSUE TITLE
AutoRouteWrapper not working in new version (4.0.1)

### ISSUE THREAD

**Issue by mojtabaghiasi** [Milad-Akarie/auto_route_library#1111]
I use wrappedRoute method to provide my bloc in widget context but after upgrading the library to the latest version (version 4.0.1), this method not working anymore and do not provide my bloc class to context.

**Comment by aldychris** [comment]
In my case the issue resolved after I rerun the build runner

**Comment by Milad-Akarie** [comment]
should be fixed in 4.1.0
