### ISSUE TITLE
Can't navigate/popAndPush by only changing path params

### ISSUE THREAD

**Issue by lucasdidur** [Milad-Akarie/auto_route_library#1112]
Hello,

I have a route like this:

```dart
    // Prova
    AutoRoute(
      path: '/prova',
      page: EmptyRouterPage,
      children: [
        AutoRoute(
          path: ':idProva',
          page: ProvaView,
        ),
        AutoRoute(
          path: ':idProva/contexto',
          page: ContextoProvaView,
        ),
        AutoRoute(
          path: ':idProva/questao/:ordem',
          page: QuestaoView,
        ),
        AutoRoute(
          path: ':idProva/resumo',
          page: ResumoRespostasView,
        ),
        AutoRoute(
          path: ':idProva/revisao/:ordem',
          page: QuestaoRevisaoView,
        ),
      ],
    ),
```

On `ProvaView`, `context.router.push(QuestaoViewRoute(idProva: provaStore.id, ordem: 0));`

and on `QuestaoView` `context.router.popAndPush(QuestaoViewRoute(idProva: widget.idProva, ordem: widget.ordem + 1));`

The page only updates when i use push, but in every navigation of QuestaoView I need to execute a dispose. So its necessary to use pop.

**Comment by Milad-Akarie** [comment]
@lucasdidur try adding `usesPathAsKey: true` to your `AutoRoute`

**Comment by mugikhan** [comment]
@Milad-Akarie Not working with replaceNamed(). Any update on this?
