### ISSUE TITLE
Hiding Bottom Navigation Bar

### ISSUE THREAD

**Issue by Kibby05** [Milad-Akarie/auto_route_library#1115]
Hi,

I am using the `AutoTabsScaffold` for managing my Scaffold Bottom Navigation Bar and It is providing the bottom Navigation bar to every screen. What would be the best approach for disabling the bottom navigation bar on certain screens?

**Comment by Ruslanbek0809** [comment]
Have you guys checked this: https://github.com/Milad-Akarie/auto_route_library/issues/732#issuecomment-933236803
