### ISSUE TITLE
Inherited arguments in nested routes

### ISSUE THREAD

**Issue by obrunsmann** [Milad-Akarie/auto_route_library#1116]
Hello,

I am searching for a way to pass same arguments to nested routes. For instance, you have a car detail page which has child pages for more information:

```dart
AutoRoute(page: CarPage, children: [
  AutoRoute(page: OverviewPage, initial: true),
  AutoRoute(page: TechnicalDataPage),
  AutoRoute(page: ImagesPage),
]),
```

Then I'd put an overview as initial route, but there is no way to pass the car to the route:

```cart
context.router.push(CarPage(car: car));
```

Should make the car also available to `OverviewPage` but indeed it's only available in `CarPage`.

**Comment by rlee1990** [comment]
I have the same issue.
