### ISSUE TITLE
activeGuardObserver.addListener does not run.

### ISSUE THREAD

**Issue by CristianKoh1** [Milad-Akarie/auto_route_library#1121]
auto_route: 4.0.0
auto_route_generator: 4.0.
<img width="660" alt="Captura de Pantalla 2022-06-20 a la(s) 3 50 14 p m" src="https://user-images.githubusercontent.com/45083832/174676240-2e02685a-7571-4b8e-9767-a5afe94d0112.png">
0

**Comment by Kiruel** [comment]
Agree, I just test today and the addListener is never call.

**Comment by u382514** [comment]
I'm having this issue as well in 5.0.1.
