### ISSUE TITLE
No API to replace specified route.

### ISSUE THREAD

**Issue by 623637646** [Milad-Akarie/auto_route_library#1122]
Let's say my current stack is `A,B,C` (A is the root page, C is the current page). 
I want to replace A with D. So the stack should be changed to `D,B,C`. 
Is this possible? I can't find an API to do this. 
Flutter API `Navigator` support this by `Navigator.of(context).replace(oldRoute: oldRoute, newRoute: newRoute)`

**Comment by Milad-Akarie** [comment]
You can rearrange your stack and pass it to replaceAll([])
Access stack router.stackData

**Comment by 623637646** [comment]
Thanks for your quick response. I tried this before but encountered 2 more issues.
1. The current stack is dynamic in my case, how can I get the current stack before passing to ` replaceAll([])`? 
2. In my case. Some pages are pushed by flutter API `Navigator.of(context).push()`.  Some pages are just from `showDialog` or `showModalBottomSheet`. In this case, if I do the `replaceAll([])` things. The pages flutter API pushed still shows to the user and the interaction is confusing. That is why I want to replace the specified page instead of replaceAll to make others pages all good.
