### ISSUE TITLE
useMaterial3 property in MaterialApp.router

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [Milad-Akarie/auto_route_library#1123]

**Comment by Milad-Akarie** [comment]
@Shahmirzali-Huseynov  this has nothing to do with this package I believe.

**Comment by Shahmirzali-Huseynov** [comment]
@Milad-Akarie why? We are using `MaterialApp.router `instead of `MaterialApp`. In MaterialApp have the useMaterial3 property, but not in MaterialApp.router.

**Comment by Shahmirzali-Huseynov** [comment]
@Milad-Akarie thanks

**Comment by brizaldi** [comment]
Hi @Milad-Akarie passing `useMaterial3` via `Theme.light().copyWith` is now deprecated, is there other way to support this feature?
