### ISSUE TITLE
How do we implement RoleGuard

### ISSUE THREAD

**Issue by chhinsras** [Milad-Akarie/auto_route_library#1128]
I expect to write role guard like this.

```
import 'package:auto_route/auto_route.dart';
import 'package:hybrid/helpers/helpers.dart';
import 'package:hybrid/services/account_service.dart';

class RoleGuard extends AutoRouteGuard {
  RoleGuard({required this.allowedRoles});
  List<String> allowedRoles = [];
  final AccountService _accountService = AccountService();

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    //  const allowedRoles = route.data.allowedRoles;
    print(router);
    print(allowedRoles);
    bool isAuthorized = _accountService
        .isAuthorized('Role', allowedRoles)
        .then((value) => value) as bool;

    if (!isAuthorized) {
      Toastr.showWarning(
          text: 'You are not authoroized to access the resource.');
      // router.push(());
    }
  }
}
```

Then define auto route like this

```
CustomRoute(
              page: DashboardPage,
              path: 'dashboard',
              initial: true,
              guards: [RoleGuard(allowedRoles: ['Admin', 'StoreManager'])]
)
```

Is it possible to implement something like this.

So when user route to specific url. it will trigger.

**Comment by neckaros** [comment]
Look at the documentation :

https://autoroute.vercel.app/advanced/route_guards

You have to call `resolver.next(true);`
If the user is authorized

**Comment by Milad-Akarie** [comment]
@chhinsras I'm still trying to figure a way to pass static Typed args to guards but for the time being your only option is to pass your roles to the route meta data and handle them inside of onNavigation method. 

`AutoRoute(...,guards: [RoleGuard], meta: {'StoreManager': true, 'Admin': true})`
inside of your guard
```dart
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final storeManager =  resolver.route.meta['StoreManager'] ?? false;
   }
```

**Comment by chhinsras** [comment]
> I understand that. One thing is how can I pass param to roleGuard from AutoRoute configuration

Thank you for your reply. it would be cleanner way. or maybe you find way better than this.

**Comment by chhinsras** [comment]
awww
