### ISSUE TITLE
Web does not support @AdaptiveAutoRouter annotation

### ISSUE THREAD

**Issue by melewetwo** [Milad-Akarie/auto_route_library#113]
There is also a problem on web when using "@AdaptiveAutoRouter" annotation.
Platform.isAndroid, Platform.isIOS, etc. (Platform.[...] in general) is not available when on web.
There should be a check like
if (kIsWeb) { ... }

**Comment by Milad-Akarie** [comment]
Hey, @melewetwo Are you saying that `Platform.isIOS` returns true on web Platform?

**Comment by melewetwo** [comment]
No. Getting the platform with this import

import 'dart:io' show Platform;

is not possible on web. It will throw an exception, so no router is created at all.
I added a check if on web platform in my pull request.

**Comment by Milad-Akarie** [comment]
fixed in auto_ruote 0.6.0. Thanks for your efforts @melewetwo!
