### ISSUE TITLE
【auto_route_annotations】I want to pass an argument to the toilet.

### ISSUE THREAD

**Issue by asai569** [Milad-Akarie/auto_route_library#1130]
hello

How can I pass an argument?
The code below is an example.
I want to know how to pass arguments.

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: Home, path: '/', initial: true),
    AutoRoute(page: Toilet(NoToiletPaper:　true  ), path: '/toilet'),
  ],
)
class $AppRouter {}
```

**Comment by TrGiLong** [comment]
@asai569 Create a wrapper for Toilet.

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: Home, path: '/', initial: true),
    AutoRoute(page: ToiletWithoutPaper, path: '/toilet'),
  ],
)
class $AppRouter {}

class ToiletWithoutPaper {...}
```

**Comment by asai569** [comment]
> @asai569 Create a wrapper for Toilet.
> 
> ```
> @MaterialAutoRouter(
>   replaceInRouteName: 'Screen,Route',
>   routes: <AutoRoute>[
>     AutoRoute(page: Home, path: '/', initial: true),
>     AutoRoute(page: ToiletWithoutPaper, path: '/toilet'),
>   ],
> )
> class $AppRouter {}
> 
> class ToiletWithoutPaper extends StatelessWidget {...}
> ```

I didn't expect the answer.  I asked if there was a way to write it using arguments.

**Comment by TrGiLong** [comment]
I don't think that you can directly pass args, because `page` accepts only `Type`. 

Wrapping helps you to pass args if you necessary need it.
