### ISSUE TITLE
AutoRoute AuthGuard with Riverpod

### ISSUE THREAD

**Issue by 58bits** [Milad-Akarie/auto_route_library#1131]
I've read in the docs here, [that](https://github.com/Milad-Akarie/auto_route_library#finalize-the-setup) - that we must initialize the router outside of the build function.

I was just wondering if there was anyway to get a 'ref' as provided by a Riverpod Consumer into AuthGuard so that we could use a configured stream or StateNotifierProvider to determine if a user is authenticated?

Something like...

`very authenticated = ref.read(authenticationProvider)`

Not 100% sure how this would work, or whether we could inject the ref into autoRoutes have they've been initialized? like

```dart
final _appRouter = AppRouter(authGuard: AuthGuard());

Widget build(BuildContext context, WidgetrRef ref) {
  _appRouter.setRef(ref)
  ...
}
```

Or maybe as at the moment, we need a separate top level auth service, that we can pass to AuthGuard - one that is not dependent on Riverpod or any other provider framework.

Thoughts?

UPDATE: I think this is probably the wrong approach. A top-level, or provider-independent authentication service class - which offers a subscription to authentication status is likely the better method. And then inside AuthGuard - this authentication status can be 'watched' or 'listened' to for changes. 

Will close this issue, although comments are welcome ;-)

**Comment by Shahmirzali-Huseynov** [comment]
So did you use `final _appRouter = AppRouter(authGuard: AuthGuard());` this approach?  using navigator withoud context

**Comment by 58bits** [comment]
Hi @Shahmirzali-Huseynov  - I ended up using the Riverpod Container in main.dart - although I'm still working on a Riverpod-based solution, and so my examples below may change - in particular as it may not be necessary to do it this way .


```dart
final container = ProviderContainer();

    // Global var declared as late final in core/router/app_router.dart
    // so that in can be accessed anywhere we import the router, but
    // initialized here within the scope of the ProviderContainer, which
    // AuthGuards requires.
    appRouterProvider = Provider<AppRouter>((ref) {
      return AppRouter(authGuard: AuthGuard(container: container));
    });

    runApp(
      // For widgets to be able to read providers, we need to wrap the entire
      // application in a "ProviderScope" widget.
      // Or in this case an "UncontrolledProviderScope" as we're using the
      // Riverpod ProviderContainer above
      // This is where the state of our providers will be stored.
      UncontrolledProviderScope(
        container: container,
        child: App(),
      ),
    );
```

And then an AuthGuard class like this...

```dart
class AuthGuard extends AutoRouteGuard {
  AuthGuard({required this.container});

  final ProviderContainer container;

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    // the navigation is paused until resolver.next() is called with either
    // true to resume/continue navigation or false to abort navigation
    var authState = container.read(authProvider);
    if(authState == const AuthenticationState.unauthenticated() || authState == const AuthenticationState.unknown()) {
      // we redirect the user to our sign in page
      router.push(SignInRoute(onResult: (success) {
        // if success == true the navigation will be resumed
        // else it will be aborted
        resolver.next(success);
      }));

    } else {
      resolver.next(true);
    }
  }

  // @override
  // void onNavigation(NavigationResolver resolver, StackRouter router) {
  //   container.read(accountModel).isAuthenticated().then(
  //         (authenticatd) => {
  //           if (authenticatd)
  //             {resolver.next(true)}
  //           else
  //             {
  //               Toastr.showWarning(
  //                   text: 'Access Denied, please login to continue.'),
  //               router.push(LoginRoute())
  //             }
  //         },
  //       );
  // }
}
```
