### ISSUE TITLE
The getter 'child' isn't defined for the type 'AutoRoutePage<dynamic>'

### ISSUE THREAD

**Issue by kingstertime** [Milad-Akarie/auto_route_library#1133]
Code:

    if (!isInternet$.value$) {
      if (AppRouter.stack.isEmpty ||
          AppRouter.stack.last.child is! NoInternetScreen) {
        AppRouter.push(NoInternetRoute());
      }
    } else {
      if (AppRouter.stack.isNotEmpty &&
          AppRouter.stack.last.child is NoInternetScreen) {
        AppRouter.removeLast();
      }
    }
In auto_route 4.0.0 it's work, but in 4.0.1 getter `child` was became private and can't get child. 

How can I solve this problem?

**Comment by kingstertime** [comment]
Or maybe I'm cooking it wrong?

**Comment by Milad-Akarie** [comment]
@kingstertime 
you can do something like 
`AppRouter.current.name == NoInternetRoute.name`
