### ISSUE TITLE
loop nested routes

### ISSUE THREAD

**Issue by anthonycuervo23** [Milad-Akarie/auto_route_library#1135]
I am using this library and is working very well, but now, I get to the point where I need the user to be able to open profile page, from there, open the friends page and be able to select a friend and navigate to their profile and also they can navigate to their friends page and see all their friends and navigate to their profile and so on... 

how can I achieve something like this while keeping the bottom navigation bar.

here an example of what I mean:
![Screen_Recording_2022-06-29_at_10_37_08_PM_AdobeExpress](https://user-images.githubusercontent.com/72933322/176540395-efa02b3c-f49a-4664-b2f2-69d4e44d60f3.gif)

**Comment by dineshkumar02** [comment]
I have used AutoTabsScaffold from this library, and specified the bottomnavigation bar and the routes, which I would like to route.

**Comment by Milad-Akarie** [comment]
@anthonycuervo23 are having trouble achieving this behaviour?
