### ISSUE TITLE
Looking for an example to show the loading indicator between the routes

### ISSUE THREAD

**Issue by dineshkumar02** [Milad-Akarie/auto_route_library#1136]
I have been using this library from last couple of months, and it's working good.

I am currently looking for a loading indicator, which I would like to show during the different routes.
I don't find any working example for this, and requesting to suggest or point me to the right location.

Thanks

**Comment by Milad-Akarie** [comment]
@dineshkumar02  are you talking about showing indicator when a guard is in progress?

**Comment by dineshkumar02** [comment]
@Milad-Akarie , I am  not using any gaurds in the code.

Whenever I do, context.router.push( Routing Page) expecting some kind of loading indicator.
Would you share any reference code for this please

**Comment by vedartm** [comment]
> @dineshkumar02 are you talking about showing indicator when a guard is in progress?

I am looking for this. Is there an example for this @Milad-Akarie?
