### ISSUE TITLE
How to properly restore page by provided url

### ISSUE THREAD

**Issue by EvaNizhni** [Milad-Akarie/auto_route_library#1139]
Good day, 

I have  a case when one user can copy link from address, then send it to another user and this user should open exactly the same page by provided address.

Is it possible to provide this behaviour automatically, or I should parse address on start of the app and then restore page?

Thank you in advance!

**Comment by Milad-Akarie** [comment]
@EvaNizhni that should be done automatically on web.

**Comment by EvaNizhni** [comment]
I created small example, and I can't do this automatically. The full example you can find in archive
[auto-router-example.zip](https://github.com/Milad-Akarie/auto_route_library/files/9037940/auto-router-example.zip)
.

Left part is navigation part. Right is content. Each page has id in address. I select the second page, copy address, go to another tab, paste address and on content part i have got content for initial first page. The gif is bellow.

https://user-images.githubusercontent.com/48185933/177119921-80926b4c-b303-497e-ba49-7dadb8f2f61d.mov

Could you please help me, how to save page content by concrete link?

**Comment by Milad-Akarie** [comment]
@EvaNizhni both of your routes [first,second] have the same path ':id', the result you're getting makes complete sense because both paths match /second

I suppose your setup should look something like this 



```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    CustomRoute(
      page: TheMainPage,
      initial: true,
      children: [
        CustomRoute(
          path: 'first',
         initial: true,
          page: TheFirstPage,
          transitionsBuilder: TransitionsBuilders.slideBottom,
          durationInMilliseconds: 300,
        ),
        CustomRoute(
          path: 'second',
          page: TheSecondPage,
          transitionsBuilder: TransitionsBuilders.slideBottom,
          durationInMilliseconds: 300,
        ),
      ],
    ),
  ],
)

```

**Comment by EvaNizhni** [comment]
@Milad-Akarie Thanks, It helps, but this close my way for configuring :id via @PathParam() form widget. Does it mean, that I can't use PathParam and open correct page on reload?

**Comment by xiprox** [comment]
> that should be done automatically on web.

@Milad-Akarie How about mobile? Any pointers on how to restore from a path? My use case is notifications that link to specific pages in the app.
