### ISSUE TITLE
Reload tab routes

### ISSUE THREAD

**Issue by filippomenchini** [Milad-Akarie/auto_route_library#1141]
Hi!
First of all, congrats for this library. One of the best ones available, I really like it!

I'm trying to create this behaviour:
if a user taps on a bottombar item two times, the page needs to be reloaded.

I was experimenting with AutoRouteObserver, but I can observe only when the selected page changes.
Is there a way to observe when a user taps a button on the bottombar?

**Comment by thantsinhtun-stone** [comment]
Yes, i also  need  this

**Comment by filippomenchini** [comment]
Hi @Milad-Akarie Thanks for answering!
Actually, yesterday I ended up using the same solution that you came up with.

Thanks again for your help!
