### ISSUE TITLE
Firebase analytics recommended way

### ISSUE THREAD

**Issue by excogitatr** [Milad-Akarie/auto_route_library#115]
Hey great package and it saved lot of time. Is there anyway recommended way to add firebase analytics with this package for `screen_view` event with this package other than using it like this?

```dart

MaterialApp(
  home: MyAppHome(),
  navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics),
  ],
);
```

**Comment by Milad-Akarie** [comment]
MaterialApp(
  builder: ExtendedNavigator (router:...,
  Observers: [
    FirebaseAnalyticsObserver(analytics: analytics),
  ],
);

**Comment by excogitatr** [comment]
Thanks, but what exactly will be the screen_view label. If the page name is HomePage, will it be logged as `HomePage` or `home-page` or `homePage`

**Comment by Milad-Akarie** [comment]
ya it will be logged as home-page unless you specify a route name prefix or exclusively specify a custom route name in AutoRoute() annotation

**Comment by excogitatr** [comment]
Great then. Thanks for the help!
