### ISSUE TITLE
Deep linking implementation

### ISSUE THREAD

**Issue by TesLake** [Milad-Akarie/auto_route_library#1153]
Hello I am trying to use deep linking on my Flutter project, I am using auto_route and following the docs in: [flutter docs](https://docs.flutter.dev/development/ui/navigation/deep-linking)

But every time I try opening using adb like this:
```
adb -e shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "http://flutterbooksample.com/book/1"
```
the app just opens in the initial route and not in the correct path, and I get this warning:
```
Starting: Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=http://flutterbooksample.com.. }
Warning: Activity not started, its current task has been brought to the front
```

I added this to my AndroidManifest.xml:
```
<!-- Deep linking -->
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="http" android:host="flutterbooksample.com" />
    <data android:scheme="https" />
</intent-filter>
```

My app.dart:
```
final appRouter = AppRouter();
...
MaterialApp.router(
          routerDelegate: appRouter.delegate(),
          routeInformationParser: appRouter.defaultRouteParser(),
          builder: (context, child) {
            return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: child!);
          },
...
```
My routes.dart:
```
@MaterialAutoRouter(
  routes: <AutoRoute>[
      AutoRoute(page: HomeScreen, initial: true),
      AutoRoute(page: BookScreen, path: 'book/'),
  ]
)
class $AppRouter {}

```

Flutter version: 3.0.2
auto_route: 4.2.1
android 11 on physical device

Does anyone have an example implementing deep linking with auto_route or somewhere I can find a tutorial?
Thank you.

**Comment by baiama** [comment]
You can use `initialDeepLink`, 

    routerDelegate: router.delegate(
          initialDeepLink: initialDeepLink,
        ),
        
final appRouter = AppRouter();
...
final initialDeepLink = getMyDeeplink();
...
MaterialApp.router(
          routerDelegate: appRouter.delegate(
           initialDeepLink: initialDeepLink,
          ),
          routeInformationParser: appRouter.defaultRouteParser(),
          builder: (context, child) {
            return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: child!);
          },
...

**Comment by jeffkelsey** [comment]
What is the implementation of "getMyDeeplink();"

Also why are there no examples of deeplinking in autrouter or around using the initialDeepLink property?

**Comment by tstarasinic** [comment]
I have similar problem. I am trying to use this package for push notifications, for foreground and background(app just dismissed  in background) it is working, but for opening push notifications when app is killed the same think happens as in the problem @TesLake described. What is the proper implementation of deep linking  and using it for push  notifications on ios. @Milad-Akarie I would really  appreciate if you can help me with that. If you ned more detailed explanation, I can provide this per request.

**Comment by SharbelOkzan** [comment]
@tstarasinic are you using [initialDeepLink](https://pub.dev/documentation/auto_route/latest/auto_route/AutoRouterDelegate/initialDeepLink.html) property ?

Use a package like [uni_links](https://pub.dev/documentation/auto_route/latest/auto_route/AutoRouterDelegate/initialDeepLink.html) to get the deeplink that launched the app, then pass that link to `initialDeepLink` of the `AutoRouterDelegate`
