### ISSUE TITLE
[Feature Request] Use a list placed in a separate variable instead of manually specifying "children" parameter

### ISSUE THREAD

**Issue by MindMayhem** [Milad-Akarie/auto_route_library#1155]
Hi, is it possible to give us possibility to separate our children lists into other variables?
Like this:

```
AutoRoute<void>(
              page: RouteWrapper,
              name: 'profile ',
              path: 'profile',
              children: profileRoutes, <-- separated to other variable
            )
            
 const List<AutoRoute> profileRoutes = [
  AutoRoute<void>(
    path: '',
    page: ProfilePage,
  ), ....,  ....,  ... ]
```

At the current moment build_runner drops with error:
`profileRoutes is not a class element`

Main question: is it possible in that package or we should pass all routes (and shared routes too) between all our routes even if they have similar routes?

**Comment by Milad-Akarie** [comment]
@MindMayhem  I'll take a look
