### ISSUE TITLE
navigating to different stackrouter child

### ISSUE THREAD

**Issue by casvanluijtelaar** [Milad-Akarie/auto_route_library#1158]
More of a question than an issue:

imagine having a routing setup like this:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/67225314/179984004-1d1c14be-4600-493b-b124-ebc42df21dce.png">

from inside `child 2` I'm trying to go to and open `child 1` with messing up the routing stack.

if I just use `pushNamed` it will bring me to the correct tab and open `child 1` but popping that route drops you back to `child 2`

I want to just go to the first `TabRouter` page and open `child 1` in its `stackRouter`

switching to the page by using `AutoTabsRouter.of(context).setActiveIndex(0)` gets me to the right  tab leaving the `stackRouter` stacks intact, then how to I push `child 1` onto the first `stackRouter` stack from inside `child 2`

**Comment by casvanluijtelaar** [comment]
...

**Comment by casvanluijtelaar** [comment]
please get rid of the stale bot, such a bad triaging tool...

**Comment by rezaskyhive** [comment]
I am facing the same issue, and basically tried everything, to get the right router from context.

any workaround for this issue?!

**Comment by Milad-Akarie** [comment]
@casvanluijtelaar @rezaskyhive  for some reason this my first time seeing this issue.
using navigate instead of push is the key here,
navigateTo(Tab1(children[Child1()])); 
if you want to go back from there use router.back():
