### ISSUE TITLE
Bug: Using variable names with '$' creates syntax errors in generated file.

### ISSUE THREAD

**Issue by iamsupercode** [Milad-Akarie/auto_route_library#1163]
To Reproduce:

- Create A Page that takes a parameter named **user$id** 
- Register Page in autoroutes
- Run flutter packages pub run build_runner build --delete-conflicting-outputs
- Check app_route.gr.dart for syntax errors 

In my case the result is this result below. Note the bolded text.

`
// ....app_route.gr.dart
  final String venue$id;

  @override
  String toString() {
    return 'ReservationBuilderRouteArgs{key: $key, onCreateReservation: $onCreateReservation, **venue$id: $venue$id**}';
  }`

**Comment by dafinoer** [comment]
i don't know, why use `$` for naming variable, just try revoke `$` at your naming variable. it will solve the problem.
