### ISSUE TITLE
Nested Navigation between Tabs

### ISSUE THREAD

**Issue by rocklyve** [Milad-Akarie/auto_route_library#1167]
Hey folk,
I have the current problem, that I'm not able to navigate to another tab directly into a nested route.

Tab 1 | Tab 2 | Tab 3 | Tab 4

Tab 1 has Screen 1.1, with a click, you come to Screen 1.2 and so on... same with Tab 2 and Screen 2.1 and 2.2 and so on... 

No I will navigate from e.g. Screen 1.4 of Tab 1 to Screen 3.4 of Tab 3

The current way for me is to navigate to Tab 3 and afterwards navigate to the nested route, which I have created for the specific page. Also I have used the Tab implementation with `AutoTabsScaffold`

Is there a way to directly jump to the screen and with a click on the back button, I would like to be able to decide, if I can switch back to the previous screen on the other tab or if I can click back on screen 3.4 and go to the screen 3.3?

I hope that there is a solution :) 
Thanks

**Comment by Milad-Akarie** [comment]
@rocklyve using router.navigateBack should take you back to the previous location no matter what.
