### ISSUE TITLE
router looking for "/" route even after providing the initial route

### ISSUE THREAD

**Issue by sanalkv** [Milad-Akarie/auto_route_library#117]
I have mentioned a route in  initialroute field, but still the router navigates to "/" before navigating to the mentioned initial route.
I didn't mention any @initial during code generation.

How can i navigate directly to the page mentioned in initial route field without pushing "/" route.

**Comment by Milad-Akarie** [comment]
Hey @sanalkv That's the native navigator doing, you could always try custom naming your initial route 'prefix/home' and don't annotate it with @initial.

**Comment by sanalkv** [comment]
i'm actually passing initial route based on conditions,
 `ExtendedNavigator<Router>(
              router: Router(),
              initialRoute: initialRoute,
            ),`
The initialRoute that im passing is not annotated with @initial.

**Comment by Milad-Akarie** [comment]
@sanalkv initial route doesn't mean root route inside of Flutter navigator it means initial destination 
if your routes map looks like this 
```
"/":HomePage
"/login":LoginPage
```

and you set the initial destination to "/login" Navigator is going to treat it as a deep link and push root first which is "/" then push "/login" so you have a working back stack

initial route is meant more for deep linking than deciding what page you should be your root page.
