### ISSUE TITLE
Part builder broken with analyzer 4.3.0 or newer

### ISSUE THREAD

**Issue by jmatth** [Milad-Akarie/auto_route_library#1172]
The [`analyzer`][analyzer] package published a new version 6 days ago. Using this new version causes `auto_route_generator` to fail with the error `Router class name must be prefixed with $` even when using the part builder. This can be reproduced just by updating `analyzer` to the latest version and attempting to run the build runners in the example project.

The underlying cause might be related to the [`LibraryElement.parts`][parts] field in the `analyzer` package, which is now marked as deprecated. That field's usage in [`auto_route_generator.dart`][auto_route_generator] seems to be the root of this bug. The deprecation message says to use the field `parts2` instead, but I don't have much experience with the `analyzer` package and it was not immediately obvious how to use the new field. 

[analyzer]: https://pub.dev/packages/analyzer/versions
[parts]: https://pub.dev/documentation/analyzer/latest/dart_element_element/LibraryElement/parts.html
[auto_route_generator]: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/lib/auto_route_generator.dart#L75

**Comment by jmatth** [comment]
I tracked down the change in the `analyzer` package that introduced this issue and filed dart-lang/sdk#49566.

**Comment by Milad-Akarie** [comment]
fixed in auto_route_generator 4.2.1
