### ISSUE TITLE
Web initial route issue [Minor issue]

### ISSUE THREAD

**Issue by FilledStacks** [Milad-Akarie/auto_route_library#118]
Hi there,

Thanks for this great package. I'm experiencing a problem with the onGenerateRoute on Web. I always get the "Route with name not found" error when starting up the app. I realised this is because on Flutter web, at least the latest version there's a blank navigation at the start. It navigates to "" (an empty string). I confirmed this by printing out the routeName in the generated onGenerateRoute function.

```
💡  onGenerateRoute - settings:
```

router.dart
```dart
@MaterialAutoRouter()
class $Router{
  @initial
  LandingView landingViewRoute;
  AuthenticationView authenticationViewRoute;
  DashboardView dashboardViewRoute;
  ProjectView projectViewRoute;
  ResetPassword resetPasswordViewRoute;
}
```
Don't be alarmed at the main file. I use the auto_route package ONLY to generate the onGenerateRoute for me. I don't use the extended router since I navigate with a navigation service to abstract the Get package's contextless navigation for my ViewModels. 

main.dart
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: locator<NavigationService>().navigatorKey,
      title: 'AppSkeletons',
      onGenerateRoute: Router().onGenerateRoute,
      // home: LandingView(),
      theme: ThemeData(
          unselectedWidgetColor: kcPrimaryColor,
          toggleableActiveColor: kcPrimaryColor,
          scaffoldBackgroundColor: kcBackgroundColor,
          primaryColor: kcPrimaryColor,
          textTheme: Theme.of(context)
              .textTheme
              .apply(fontFamily: 'Open Sans', bodyColor: kcPrimaryTextColor)),
      initialRoute: Routes.landingViewRoute,
    );
  }
}
```

In the case above it'll always start up the view on the red "No route view" because of that first navigation. I implemented a quick workaround and thought I'd let you know. I changed my onGenerateRoute function in main to go through an anonymous function first that checks the route and then sets it to the initial route if it's empty.

```dart
 onGenerateRoute: (RouteSettings settings) {
        log.v('onGenerateRoute-name:${settings.name}');
        if (settings.name == '') {
          log.v('Startup route broken. Change to initial route');
          settings = RouteSettings(name: '/');
        }
        return Router().onGenerateRoute(settings);
      },
```

This is just a temp workaround. I think checking kIsWeb and if it's empty in the generated code could help prevent this. I also don't know if it's just on my pc that it's happening. I'm on flutter

```
1.18,0-7.0.pre.46
```

Let me know if you need any other inputs.

**Comment by Milad-Akarie** [comment]
@FilledStacks I'll look into it.

**Comment by Milad-Akarie** [comment]
What's the value of Routes.landingViewRoute?
I can't reproduce!

**Comment by FilledStacks** [comment]
landingViewRoute is '/'

```dart
abstract class Routes {
  static const landingViewRoute = '/';
  static const authenticationViewRoute = '/authentication-view-route';
  static const dashboardViewRoute = '/dashboard-view-route';
  static const projectViewRoute = '/project-view-route';
  static const resetPasswordViewRoute = '/reset-password-view-route';
  static const all = {
    landingViewRoute,
    authenticationViewRoute,
    dashboardViewRoute,
    projectViewRoute,
    resetPasswordViewRoute,
  };
}
```

That's why I wanted to mark it as a minor issue since it might just be on my PC. I know Flutter web is not to be trusted yet

**Comment by Milad-Akarie** [comment]
I'm on MacBook/ Chrome everything works as expected. 
@FilledStacks Need your input in here 
https://github.com/Milad-Akarie/auto_route_library/issues/119

**Comment by FilledStacks** [comment]
@Milad-Akarie I wanted to keep this issue here for reference but I think I'll close it. It's still happening to me. i'm using Flutter through fvm, which shouldn't change anything but you never know. It's still happening on my side but I think I'll close this issue so you can focus on #119 .

About my input there. I don't have much to say yet. I'll add some feedback if I have any but for now I think any attempt to improve readability will be a effort in the right direction. I currently only use the package for the generated onGenerateRoute and the ViewArgumentGenerator. Love those features. I won't have much input on the other bits just yet since I don't get too deep into the package.
