### ISSUE TITLE
[Deep Link] iOS not getting initial route after first launch

### ISSUE THREAD

**Issue by jdbenito** [Milad-Akarie/auto_route_library#1184]
I am working on an app with both deep and universal linking support and we leverage the auto_route plugin.

In Android, opening a deep link when the app is not launched always triggers an initial route with the route specified in the deep link. iOS, unfortunately, does not do the same if it's starting from an unlaunched state -- i.e. the app is always just directed to the default route and not the actual route.

According to the official [Flutter documentation](https://docs.flutter.dev/development/ui/navigation/deep-linking):

> #### iOS (not launched)
> App gets initialRoute (“/”) and a short time after uses the RouteInformationParser to parse the route and call RouterDelegate.setNewRoutePath, which configures the Navigator with the corresponding Page.

Am I misinterpreting these docs? Is the **actual** initial route not pushed a short time after at all?

Has anyone else encountered this and what's your workaround?

=====
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-arm, locale en-CA)
• Flutter version 3.0.5 at /Users/jdbenito/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1 (4 weeks ago), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Users/jdbenito/Library/Android/sdk
• Platform android-32, build-tools 31.0.0
• ANDROID_HOME = /Users/jdbenito/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
• Xcode at /Applications/Xcode13_4.app/Contents/Developer
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.46.0

**Comment by Milad-Akarie** [comment]
@jdbenito  How and where are you reading the initial link?

**Comment by jdbenito** [comment]
We have an `AutoRoute` widget that is mapped to the "/app/*" path. This widget takes care of the parsing of the URL.

In Android, when launching the app via a deep/universal link, I typically see:
1.  the initial route (i.e. "/") first get loaded, 
2. followed by the "/app/*" route getting pushed

In iOS, I don't see #2 happening at all, if starting from an unlaunched state. 
Everything is fine though if the app is already running.

Here's a snippet of how we built our router:
```
...
return MaterialApp.router(
              title: ...,
              themeMode: ThemeMode.light,
              theme: AppThemes.lightTheme,
              darkTheme: AppThemes.darkTheme,
              localizationsDelegates: AppLocalizations.localizationsDelegates,
              supportedLocales: AppLocalizations.supportedLocales,
              routeInformationParser: _appRouter.defaultRouteParser(),
              routerDelegate: _appRouter.delegate(
                  navigatorObservers: _analytics.navObserverList),
              builder: ...
            );

```

**Comment by Milad-Akarie** [comment]
@jdbenito are you using the new deep-link flag in IOS?
```xml
<key>FlutterDeepLinkingEnabled</key>
<true/>
```
more info [here](https://docs.flutter.dev/development/ui/navigation/deep-linking)

**Comment by jdbenito** [comment]
Affirmative. That flag is set to TRUE.

**Comment by marvin-kolja** [comment]
@jdbenito I have the exact same problem! However, I don't think it's a problem of this package since my app does not use it.

I'm running the app with flutter `3.0.1` on iOS `15.5`. It seems that packages such as [`app_links`](https://github.com/llfbandit/app_links) work fine as a workaround, but I'm a bit stubborn to just give up, yet.

Have you found any fix, yet? If not, I'd create an issue on the flutter repo and link this issue.

**Comment by jdbenito** [comment]
Unfortunately not @marvin-kolja . I feel that there's some truth in the speculation that it's a bug within auto_route. 

As a workaround, I ended up pulling the [uni_links plugin](https://pub.dev/packages/uni_links).

**Comment by Milad-Akarie** [comment]
@jdbenito I'm not quite sure but I think the issue has to do with the scheme you're using
Here's  a demo using a custom scheme ( works perfectly )
![ios_deep_link_demo](https://user-images.githubusercontent.com/55059449/184661465-7c7ee1f9-60af-4190-bf8a-98037150c74a.gif)

**Comment by jdbenito** [comment]
@Milad-Akarie did you try it with the app not completely running yet in the background? -- i.e. the app should **start** solely from the link

**Comment by Milad-Akarie** [comment]
@jdbenito  Yes, the App was completely killed, not in the background.

**Comment by InAnadea** [comment]
I have the same issue. I use app links for deep linking on iOS. On Android deep linking works fine with any state of the application (launched, not launched). 
In `Info.plist` I added 
```
        <key>FlutterDeepLinkingEnabled</key>
	<true/>
```
In runner configuration I added my domain
<img width="560" alt="Screenshot 2022-11-02 at 16 30 54" src="https://user-images.githubusercontent.com/93736963/199516677-b4dbafad-1a08-47ff-8a49-478c6b823144.png">

On android I did the same
```
<!-- App linking -->
            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
            <intent-filter android:autoVerify="true" >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="https" />
                <data android:host="<my domain>" />
            </intent-filter>
```

On iOS I have an issue with opening the link when the application is completely closed. It opens the login screen and after pushing the home screen. On Android, all works fine.

Here is my routing scheme
```
routes: [
    AutoRoute(
      path: '/${RouteConstants.main}',
      page: MainScreen,
      initial: true,
      guards: [AuthGuard, QuizGuard],
      children: [
        // Common
        AutoRoute(
          path: RouteConstants.home,
          page: HomeScreen,
          initial: true,
        ),
    ....
    ]
  ),
  AutoRoute(
    path: '/${RouteConstants.login}',
    page: LogInScreen,
    guards: [QuizGuard],
  ),
...
]
```

**Comment by himankBellpost** [comment]
i'm still facing issue on ios for deeplinks using autoroute. i confirmed its working fine if I use applinks
