### ISSUE TITLE
Loss Widget tree after re-running

### ISSUE THREAD

**Issue by engelin** [Milad-Akarie/auto_route_library#1185]
I've met loss of widget tree after re-running like below:
https://user-images.githubusercontent.com/26742874/183485061-84906246-2496-4ebb-b4d0-fb028912c35b.mov

I configured this test app with flutter intl, and bloc.
Does anything I missed?

app_routes.dart
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      path: '/login',
      page: LoginPage,
    ),
    bottomNavRouter,
  ],
)
class $AppRouter {}

const bottomNavRouter = AutoRoute(
  path: '/nav',
  page: BottomNavigatorPage,
  children: <AutoRoute>[
    AutoRoute(
      path: 'category',
      page: CategoryPage,
    ),
    AutoRoute(
      path: 'brand',
      page: BrandPage,
    ),
    AutoRoute(
      path: 'home',
      page: HomePage,
    ),
    AutoRoute(
      path: 'wish',
      page: WishPage,
    ),
    AutoRoute(
      path: 'my',
      page: MyPage,
    )
  ],
);
```

app.dart
```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final appRouter = AppRouter();

    return MaterialApp.router(
      title: 'Auto route test',
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      debugShowCheckedModeBanner: false,
      theme: RouteTheme.light,
      darkTheme: RouteTheme.dark,
      routerDelegate: appRouter.delegate(),
      routeInformationParser: appRouter.defaultRouteParser(),
      builder: (context, router) => router!,
    );
  }
}
```

bottom_navigator.dart
```dart
class BottomNavigatorPage extends StatelessWidget {
  const BottomNavigatorPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      routes: const <PageRouteInfo>[
        CategoryRoute(),
        BrandRoute(),
        HomeRoute(),
        WishRoute(),
        MyRoute(),
      ],
      builder: (context, child, animation) {
        final tabsRouter = AutoTabsRouter.of(context);

        return Scaffold(
          body: FadeTransition(
            opacity: animation,
            child: child,
          ),
          bottomNavigationBar: BottomNavigationBar(
            currentIndex: tabsRouter.activeIndex,
            onTap: (index) {
              tabsRouter.setActiveIndex(index);
            },
            selectedIconTheme: const IconThemeData(
              color: Color(0xFFF89C0E),
            ),
            items: const <BottomNavigationBarItem>[
              BottomNavigationBarItem(
                label: 'category',
                icon: Icon(Icons.category),
              ),
              BottomNavigationBarItem(
                label: 'brand',
                icon: Icon(Icons.branding_watermark),
              ),
              BottomNavigationBarItem(
                label: 'home',
                icon: Icon(Icons.home_filled),
              ),
              BottomNavigationBarItem(
                label: 'wish',
                icon: Icon(Icons.heart_broken),
              ),
              BottomNavigationBarItem(
                label: 'my',
                icon: Icon(Icons.person),
              ),
            ],
          ),
        );
      },
    );
  }
}

```

**Comment by engelin** [comment]
Issue done as setting AppRouter as a global variable.

```dart
GetIt getIt = GetIt.instance;

void main() {
  getIt.registerSingleton<AppRouter>(AppRouter());

  runApp(const App());
}
```

**Comment by 1saifj** [comment]
Hi @engelin, Glad you resolved this issue!
I just have a question regarding the bottom nav in this approach :)!
Is the bottom nav will create its child whenever the tab gets **clicked**? if so, is there any way to register these widgets as a singleton? so that they can be initialized only once and not created on the bottom nav **onTab**.
Thanks

**Comment by engelin** [comment]
Hi @1saifj 

I think you don't need to use a singleton for bottom navigation bar. As the tab pages are registered just once.
The reason why each single tab seemed to be registered if clicking tile at the first time, is auto_tabs_router has been implemented using lazy loading internally I guess. Please refer the below.

[auto_tabs_router.dart](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/router/widgets/auto_tabs_router.dart#L338)
```dart
void _setup() {
    for (var i = 0; i < widget.stack.length; ++i) {
      if (i == widget.activeIndex || !widget.lazyLoad) {
        _initializedPagesTracker[i] = true;
        _didInitTabRoute(i);
      } else {
        _initializedPagesTracker[i] = false;
      }
    }
  }

  @override
  void didUpdateWidget(_IndexedStackBuilder oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.tabsHash != oldWidget.tabsHash) {
      _initializedPagesTracker.clear();
      _setup();
      return;
    }
    if (widget.lazyLoad &&
        _initializedPagesTracker[widget.activeIndex] != true) {
      _initializedPagesTracker[widget.activeIndex] = true;
      _didInitTabRoute(widget.activeIndex, oldWidget.activeIndex);
    } else if (widget.activeIndex != oldWidget.activeIndex) {
      _didChangeTabRoute(widget.activeIndex, oldWidget.activeIndex);
    }
  }
```

But I'm guessing @Milad-Akarie could answer your question rather that me.

I hope you find out the solution soon. :)

**Comment by Milad-Akarie** [comment]
@1saifj are you facing widget reloading issues?

**Comment by 1saifj** [comment]
> Hi @1saifj
> 
> I think you don't need to use a singleton for bottom navigation bar. As the tab pages are registered just once. The reason why each single tab seemed to be registered if clicking tile at the first time, is auto_tabs_router has been implemented using lazy loading internally I guess. Please refer the below.
> 
> [auto_tabs_router.dart](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/router/widgets/auto_tabs_router.dart#L338)
> 
> ```dart
> void _setup() {
>     for (var i = 0; i < widget.stack.length; ++i) {
>       if (i == widget.activeIndex || !widget.lazyLoad) {
>         _initializedPagesTracker[i] = true;
>         _didInitTabRoute(i);
>       } else {
>         _initializedPagesTracker[i] = false;
>       }
>     }
>   }
> 
>   @override
>   void didUpdateWidget(_IndexedStackBuilder oldWidget) {
>     super.didUpdateWidget(oldWidget);
>     if (widget.tabsHash != oldWidget.tabsHash) {
>       _initializedPagesTracker.clear();
>       _setup();
>       return;
>     }
>     if (widget.lazyLoad &&
>         _initializedPagesTracker[widget.activeIndex] != true) {
>       _initializedPagesTracker[widget.activeIndex] = true;
>       _didInitTabRoute(widget.activeIndex, oldWidget.activeIndex);
>     } else if (widget.activeIndex != oldWidget.activeIndex) {
>       _didChangeTabRoute(widget.activeIndex, oldWidget.activeIndex);
>     }
>   }
> ```
> 
> But I'm guessing @Milad-Akarie could answer your question rather that me.
> 
> I hope you find out the solution soon. :)

Thank you. it is clear.

**Comment by 1saifj** [comment]
> @1saifj are you facing widget reloading issues?

No, I am just asking but wondering if the same is possible with the Goroute package.

Thank you
