### ISSUE TITLE
Redirect with wildcard

### ISSUE THREAD

**Issue by Aqua-Ye** [Milad-Akarie/auto_route_library#1188]
Hi,

Is there a way to have a `RedirectRoute` with "wildcard"?
For example:
```
    RedirectRoute(
      path: '/profile/settings/*,
      redirectTo: '/settings/*,
    ),
```

Basically I want whatever is after the original path to be passed to the redirect path.

Thanks!

**Comment by Milad-Akarie** [comment]
@Aqua-Ye  in the current implementation you only have dynamic segment redirecting, but that's a good feature it's worth implementing. 

that's all you can do now 
```dart
  RedirectRoute(
      path: '/profile/settings/:segment',
      redirectTo: '/settings/:segment',
    ),
```

**Comment by Aqua-Ye** [comment]
> @Aqua-Ye in the current implementation you only have dynamic segment redirecting, but that's a good feature it's worth implementing.
> 
> that's all you can do now
> 
> ```dart
>   RedirectRoute(
>       path: '/profile/settings/:segment',
>       redirectTo: '/settings/:segment',
>     ),
> ```

I think your solution is great. Thanks!
