### ISSUE TITLE
[a11y] Focus not working in AutoTabScaffold's bottomNavigationBar

### ISSUE THREAD

**Issue by gilnobrega** [Milad-Akarie/auto_route_library#1189]
It is not possible to gain Focus on the `bottomNavigationBar` of `AutoTabScaffold`. Here's what I mean in `auto_route`'s example app:

https://user-images.githubusercontent.com/82336674/184321754-d22bc842-20c2-408c-a8b5-a1572fe7a7d0.mov

This is not the expected behaviour. I replaced `AutoTabScaffold` with a simple `Scaffold` and this is how it should behave:

https://user-images.githubusercontent.com/82336674/184321959-86f975fc-d690-49c6-9962-df9445c112e3.mov

**Comment by Milad-Akarie** [comment]
@gilnobrega  Do you know what's causing the issue?

**Comment by gilnobrega** [comment]
> @gilnobrega Do you know what's causing the issue?
I had a look through the code but I didn't find anything obvious that would cause the issue
Is there any kind of keyboard interaction that could be overriding focus?

**Comment by getBoolean** [comment]
@gilnobrega Did you ever find a workaround or fix? I am seeing the same issue with `AutoTabsScaffold` and `AutoTabsRouter`
