### ISSUE TITLE
Redesign base structure?

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#119]
Hello guys, 
@TarekkMA @nateshmbhat @ResoDev  @FilledStacks  @visual-velocity @valentinbercot 
I've been working on supporting Flutter web lately and along the way I realized AutoRoute needs some core changes to enhance readability, scalability and give users more control over their router classes.  
The new approach I have in mind requires lots of breaking changes mostly in the $Router (template) so I guess it's not that bad, but anyways I need your comments on the new approach and whether I should go for it. 

must people should be familiar with this path:component approach especially those coming from web. 

```dart
@MaterialAutoRouter()
class Router extends $Router {
  @Routes()
  static const routes = <String, dynamic>{ 

    '/': HomeScreen,

    '/users/{id}': MaterialRoute(
      SecondScreen,
      guards: [AuthGuard],
       ...other config
    ),
  };
}
```

for example handling unknown routes on your own should be a breeze 

```dart
@MaterialAutoRouter()
class Router extends $Router {
  @Routes()
  static const routes = <String, dynamic>{...};

 @override
  Route onRouteNotFound(RouteSettings settings) {
  // return your own 404 screen
    return MyUnknownRoute(settings):
  }
}
```
your thouths?

**Comment by valentinbercot** [comment]
Hi @Milad-Akarie,

First of all thank you for you interest in my feature request #102 !

I really like your approach and it's of course readable for web devs but I think also readable for mobile devs.

In my opinion mobile devs who wrote client API with Retrofit or Alamofire or consume API documentation in OAS / swagger / RAML format (as on [editor.swagger.io](http://editor.swagger.io/#/)) are confortable with path approach.

In your approach, required and optional query params are in `... other config` or in the widget with annotations as proposed in #102?

**Comment by visual-velocity** [comment]
Hi **@Milad-Akarie and @All**, 
 I liked your idea and implementation and it's really good but along with can you think about group router
**Grouped Routers** 
In addition to declaring Routes in your Router, you can also declare child Routers. Those routers will have it's Routes presented as being part of the father Router. We may also refer this pattern as Router Grouping or Grouped Routers. This allows for splitting a huge router that potentially could have many Routes, into smaller autonomous Routers that can be imported and grouped together in the main Router.
**DeepLinks or dynamic link or dynamic routes** support both **pathParameters** (using URL templates) and **queryParameters.** Those parameters will be passed to your Route as arguments as Strings, so keep that in mind when declaring the Route arguments.
@Route(deepLink: 'myRoute/:argumentName') 
**Implementation required**
Wildcard parameter matching
Querystring parameter parsing


// Modules Home → Product
ExtendedNavigator.of.pushNamed('/home/product/list');
ExtendedNavigator.of.pushNamed('/home/product/detail/:id');

// Inside Product module, use Modular.link and navigate between Product module routes
ExtendedNavigator.of.pushNamed('/list');
ExtendedNavigator.of.pushNamed('/detail/:id');

The parameter will, then, be pattern-matched when calling the given route. For example:
// In this case, `args.params['id']` will have the value `1`.
ExtendedNavigator.of.pushNamed('/product/1');

**Comment by Milad-Akarie** [comment]
@valentinbercot Some ppl like to use the native navigator and for that I need to treat arguments and queryParameters as equal. 
if arguments == null 
arguments =  parse queryParameters from url 

or I can only treat arguments as queryParameters if they're passed as a Map?

**Comment by Milad-Akarie** [comment]
@visual-velocity Yes nested routers are a part of the plan but the first release will only support first level deep linking user/{id} and query parameters 
also I'm planning on renaming `ExtendedNavigator to just XNavigator`

**Comment by nateshmbhat** [comment]
Sounds cool 😎. I suggest naming it   AutoNavigator  which mingles with the library properly

**Comment by Milad-Akarie** [comment]
@nateshmbhat sounds cool but still long lol

**Comment by visual-velocity** [comment]
No @Milad-Akarie Don't change it because we are using this library inside our production app or organization app. 
I am also using inside my production app.Changing the first thing will cost a lot of time and time cost will also go, if you need to change then you can think of using 'to' instead of 'of'.
**_ExtendeNavigator.to_**  instead of **_ExtendeNavigator.of_**

**Comment by visual-velocity** [comment]
Everyone has an own tag or brand name, and that makes their identity and I don't think it would be completely right to change it.

**Comment by Milad-Akarie** [comment]
@valentinbercot makes sense. I guess now that users will be using their own router instead of the generated one they can do something like this for easy access
```dart
class Router extends $Router{
 static ExtendedNavigatorState get navigator => ExtendedNavigator.ofRouter<Router>()
}
```

**Comment by Milad-Akarie** [comment]
@TarekkMA @nateshmbhat @ResoDev @FilledStacks @visual-velocity @valentinbercot
The new auto_route 0.6.0 is finally out. Please check it out and share your thoughts.

**Comment by zeeshanhussain** [comment]
@Milad-Akarie I am not sure if this is intended but on flutter web if I refresh the page or if I open a new route on another tab like /post/1, then in both the cases it redirects me back to '/' root.

**Comment by valentinbercot** [comment]
Hi @Milad-Akarie,

I'm sorry to come back to you so , you did an amazing job thanks a lot !
