### ISSUE TITLE
Navigating to a screen in the dependent package

### ISSUE THREAD

**Issue by saahilmehra** [Milad-Akarie/auto_route_library#1191]
I have added a local package as a dependency in my app. The local package also has it own screens and routes generated using auto router. I am facing error when trying to navigate from my app screen to local package screen. Both app and package use auto router for navigation.

Here is the code for navigating from app screen to local package screen:
`AutoRouter.of(context).push(const ChildProfileScreenRoute());`

Error:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
E/flutter (16215): #0      ListIterable.reduce (dart:_internal/iterable.dart:181:22)
E/flutter (16215): #1      RoutingController._matchOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:132:58)
E/flutter (16215): #2      StackRouter._push (package:auto_route/src/router/controller/routing_controller.dart:880:17)
E/flutter (16215): #3      StackRouter.push (package:auto_route/src/router/controller/routing_controller.dart:827:35)
E/flutter (16215): #4      _HomeScreenState.navigationOptions.<anonymous closure> (package:communica/ui/screens/caregiver/home_screen/home_screen.dart:350:34)
E/flutter (16215): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
E/flutter (16215): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (16215): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
E/flutter (16215): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
E/flutter (16215): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
E/flutter (16215): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (16215): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
E/flutter (16215): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
E/flutter (16215): #13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
E/flutter (16215): #14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
E/flutter (16215): #15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
E/flutter (16215): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
E/flutter (16215): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
E/flutter (16215): #18     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (16215): #19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (16215): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (16215): #21     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (16215): #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (16215): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)`

**Comment by Milad-Akarie** [comment]
@saahilmehra  Sadly that's not yet supported by auto_route.
