### ISSUE TITLE
[Feature Request] Implement API to manage Web History

### ISSUE THREAD

**Issue by NachiketaVadera** [Milad-Akarie/auto_route_library#1193]
Hey @Milad-Akarie. I was wondering if we can add a feature to manage (or at least omit) web history. go_router has a similar implementation [over here](https://gorouter.dev/web-history).

**Comment by Milad-Akarie** [comment]
Hey @NachiketaVadera  Router.neglect is from flutter package, technically it should work the same regardless of the navigation packag, but I remember it not working as expected so I'll just have to investigate the issue

**Comment by NachiketaVadera** [comment]
Hey, thanks! I should have been more clear with the request. I meant the property implementation like:
```dart
AutoRoute(page: Home, path: 'home', initial: true, neglect: true),
```

But it'd be cool to have Router.neglect working with the lib, really useful feature.

Do let me know if I can help in anyway. Thanks.

**Comment by Milad-Akarie** [comment]
@NachiketaVadera I see, but I'm not sure how that would work, what if you mark a child route as neglected, do we neglect the parent as well?

**Comment by Milad-Akarie** [comment]
@NachiketaVadera I've implemented a global neglect check in the new version, I guess you can work with that until we figure something out
`routeInformationProvider: _appRouter.routeInfoProvider(neglectWhen: (path) => true),`

**Comment by NachiketaVadera** [comment]
@Milad-Akarie Hey, that sounds good for the new version. 

I don't think we should mark the parent routes as neglected, only the explicitly marked routes and their children should get neglected.

**Comment by Milad-Akarie** [comment]
What if we push a parent with a child as the same time. '/parent/child'. That's the case I have in mind

**Comment by NachiketaVadera** [comment]
This is what it looks like in my head.

For example,
- /users/:userID/books/:bookID (we're neglecting book id)
- /settings

The web history of us going from a user (user/:userID) to a particular book and then to settings should ideally be:
```
/user/:userID
~~/user/:userID/books/:bookID~~ **(neglected)**
/settings
```
In this case, pressing the browser back from settings should go to /users/:userID/books. If we neglect books as well, the back button would go to users/:userID.

Would that makes sense?
