### ISSUE TITLE
AutoBackButton with showDialog

### ISSUE THREAD

**Issue by aaumond** [Milad-Akarie/auto_route_library#1196]
Hi,

When I use the `AutoLeadingButton` widget in an `AppBar`, if I open a dialog via the `showDialog` method, the button appears in the background of the modal.

![IMG_B82D48698934-1](https://user-images.githubusercontent.com/79145906/185746552-3e0cf950-473b-45e7-b3a7-6b034bfb3169.jpeg)

Is there any way to not display it in this case?

If I set the parameter `showBackIfParentCanPop` to false, when I use the navigation to nested pages, the back button will not appear anymore. This is annoying.

Do you have a solution?

Thanks in advance for your help.

**Comment by Milad-Akarie** [comment]
@aaumond  In the new version you're able to do something like this 
`AutoLeadingButton(ignorePagelessRoutes: true)`
PagelessRoutes = dialogs or any routes that's added to stack without using the pages API
