### ISSUE TITLE
Replacing all children from a router with a single route

### ISSUE THREAD

**Issue by David200337** [Milad-Akarie/auto_route_library#1198]
Hello,

I am currently building an app using auto route where I would like to navigate to a new route and replace all current children of that router with the new route.

Let's say I have following router setup:
```dart
@AdaptiveAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    CustomRoute(
      path: '/',
      initial: true,
      page: HomePage,
      name: 'HomeRouter',
      transitionsBuilder: TransitionsBuilders.noTransition,
      children: [
        AutoRoute(
          path: 'products',
          name: 'ProductRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: ProductListPage,
            ),
            AutoRoute(
              path: 'productId',
              page: ProductDetailPage,
            ),
            RedirectRoute(
              path: '*',
              redirectTo: '',
            ),
          ],
        ),
        AutoRoute(
          path: 'cart',
          name: 'CartRouter',
          page: EmptyRouterPage,
          children: [
            CustomRoute(
              path: '',
              page: CartPage,
              transitionsBuilder: TransitionsBuilders.noTransition,
            ),
            AutoRoute(
              path: 'check-out',
              page: CheckOutPage,
            ),
            AutoRoute(
              path: 'payment',
              page: PaymentPage,
            ),
            CustomRoute(
              path: 'order',
              page: OrderPage,
              transitionsBuilder: TransitionsBuilders.noTransition,
            ),
            RedirectRoute(
              path: '*',
              redirectTo: '',
            ),
          ],
        ),
      ],
    ),
  ],
)
```

My parent router (`HomeRouter`), which is used as a tabs router, includes two child routers called `ProductRouter` and `CartRouter` (the products and cart tab). Now when a user navigates through the cart he/she navigates from: `CartRoute` -> `CheckOutRoute` -> `PaymentRoute` -> `OrderRoute`.
So then, the router would look like the following:
```dart
HomeRouter(
  children: [
    CartRouter(
      children: [
        CartRoute(),
        CheckOutRoute(),
        PaymentRoute()
        OrderRoute(),
      ],
    ),
  ],
)
```

This means that when a user would be located on the `OrderRoute` page it is of course possible to navigate back to one of the child pages inside the `CartRouter` using the OS back button on Android or the right swipe on iOS, as these pages still exist on the stack. However, I would like to prevent the user from being able to return to any of the previous pages once he/she is on the `OrderRoute` page. 

I thought I could simply achieve this by calling the `replace()` method on the router once navigating to the `OrderRoute`, like so:
```dart
router.replace(const CartRouter(children: [OrderRoute()]));
```
But unfortunately this does not seem work. This results in an unhandled exception inside auto route's `_matchOrReportFailure`, when trying to throw an error: `StateError (Bad state: No element)`.
I also tried it with specifying root the router (`HomeRouter`), as well as with `replaceAll()` on the `router.root`, but nothing seemed to work.

Does anyone a have a suggestion?
Thank you in advance!

**Comment by Milad-Akarie** [comment]
Hello @David200337 from OrderPage if you call `context.router.replaceAll([OrderRoute()]);` you should get the result you need.

**Comment by David200337** [comment]
That's it!
Thank you so much!
