### ISSUE TITLE
[QUESTION] Hidden back icon from AppBar when navigate new route?

### ISSUE THREAD

**Issue by fabricioloupias** [Milad-Akarie/auto_route_library#120]
Hello guys..

**Description**
I will tell you a bit about my problem, I might pass it on in the documentation and I couldn't find it. When I navigate to a new route, the widget I use for that route has an AppBar. Is there a way that the back icon does not appear in that AppBar?

**Use case**
A use case would be that I am standing in a login widget and when I successfully login I want to go to the home screen. And from the home screen I have no need to go back.

**Possible solution**
One possible solution is to add an empty widget to the Leading of the AppBar. What this generates for me is that this widget takes up space, and when I add a title to the AppBar it shows next to that widget that is taking up space. 

`
Scaffold(
        appBar: AppBar(
          leading: Container(),
          title: Text("Home"),
        ),
      )
`

Another thing that the issue can solve is that from ExtendedNavigator you can call a method that acts in the same way as Navigator.pushReplacementNamed ()

**Comment by Milad-Akarie** [comment]
Hey, @fabricioloupias ExtendedNavigator is an an actual sub class of Navigator so the pushReplacementNamed should be there.
The App bar will automatically show the back button for any route that's not the initialRoute unless you set automaticallyImplyLeading  to false. 
```dart
AppBar(automaticallyImplyLeading: false),
```
Hope this helps.

**Comment by fabricioloupias** [comment]
> Hey, @fabricioloupias ExtendedNavigator is an an actual sub class of Navigator so the pushReplacementNamed should be there.
> The App bar will automatically show the back button for any route that's not the initialRoute unless you set automaticallyImplyLeading to false.
> 
> ```dart
> AppBar(automaticallyImplyLeading: false),
> ```

Its works fine, thank you!
