### ISSUE TITLE
Auto Route throws error on build runner

### ISSUE THREAD

**Issue by Coinmaster123456** [Milad-Akarie/auto_route_library#1201]
Auto Route throws an error at this code even though my router.dart should be fine:

![image](https://user-images.githubusercontent.com/70707774/186215307-ea8d0100-9670-4827-930c-af3ed58f0308.png)
### Buildrunner Output:
![image](https://user-images.githubusercontent.com/70707774/186215808-72adabbc-416d-4d7e-b5b4-a11070362bf3.png)

**Comment by tomassilgueira** [comment]
I have the same problem, did you find how to fix it? 😕
