### ISSUE TITLE
The "router.navigate" API doesn't respect Route Guards.

### ISSUE THREAD

**Issue by 623637646** [Milad-Akarie/auto_route_library#1206]
Thanks for your amazing library. I have a question here. 

Seems that only a kind of `router.push` API respects the route guards. 
Others like `router.navigate` API doesn't respect the route guards. 
For example, `router.navigate` to a route which has a guard, the guard will not be trigger in this case.
Is this expected? Personally, I think all router changes should respect the Route Guards.

**Comment by eXifreXi** [comment]
So, I just came across this and had a quick look. I have no idea why this is happening, but what I noticed is that called `router.navigate` in the AuthGuard, simply has no effect(?). I use `navigate` everywhere to navigate between screens, so I also had it in the AuthGuard. I replaced it with `replace` or just `push` and that seems to restore the functionality.

Not sure why it wouldn't work with `navigate` though.
