### ISSUE TITLE
Lagging analyzer dependency

### ISSUE THREAD

**Issue by tjarvstrand** [Milad-Akarie/auto_route_library#1209]
Hi,

auto_route_generator currently requires `analyzer` to be <= 4.4 which is two minor versions behind atm and that is making it incompatible with the latest versions of some other libraries. Would it be possible to set the upper boundary to <= 5.0?

**Comment by Milad-Akarie** [comment]
@tjarvstrand  done

**Comment by tjarvstrand** [comment]
Thanks! 🙂

**Comment by tim-eucalyptus** [comment]
Please update: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/pubspec.yaml

We're also having this issue.
