### ISSUE TITLE
Router push above the root 

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#1211]
Hey,
I don't mean to spam, but this issue is really critical for my app and I think others as well.
Please look at issue #782.

I have updated the bug repo https://github.com/naamapps/auto_route_bug.
Updated to latest auto_route 5.0.0 and flutter 3.0.

My main issue is with the first button.

1. Open dialog
2. Press open second page
3. The second page will appear behind the dialog! even when it is considered root (it hides the nav bar).

Please help!
Thanks

**Comment by Milad-Akarie** [comment]
Hello @naamapps I'm on mobile right now, I believe your problem has to do with using the wrong context when showing a dialog.. showDialog will push the dialog to the root Navigator unless useRootNqviagtor is set to false then it pushes it to the nearest Navigator.

So if you push your dialog to the root Navigator then push routes to a nested Navigator of course it's gonna be beneath it

-P1
----p1n1
----p1n2
-Pageless route (Dialog)

Think of p1n1 and p1n2 as widgets inside of the root page

I guess setting useRootNavigator to false should fix your problem

Using pushWidget is another story

**Comment by naamapps** [comment]
@Milad-Akarie You are right!
I didn't think of this that way.
I now set the useRootNavigator to false and use the correct context, and it now pushes above the dialog.
Thanks,
I will close both issues :)
