### ISSUE TITLE
Cannot setup AutoRouter using part builder (part-of generated file)

### ISSUE THREAD

**Issue by CartmanGD** [Milad-Akarie/auto_route_library#1216]
According to the [documentation](https://pub.dev/packages/auto_route#setup-and-usage), you can set up the generated AutoRouter file using a part-of file or not.

Generating without a part builder works just fine, while setup using the part builder leads to some issues.

The part-of generated file does not contain reference to the `delegate()` and `defaultRouteParser()` functions. 

**In order words, it is not possible to set up routing using part builder-generated files.**

```
part 'app_router.gr.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: AuthPage, initial: true),
    AutoRoute(page: TutorialPage),
    AutoRoute(page: LoginPage),
    AutoRoute(page: SmsVerificationPage),
  ],
)
class AppRouter extends _$AppRouter {}
```

As you can see, there is no reference to the `delegate()` and `defaultRouteParser()` functions.

![Screen Shot 2022-09-04 at 14 42 27](https://user-images.githubusercontent.com/110026289/188312712-e842b80e-1670-4455-89ea-4e314b663901.png)

**After rebuilding the file without a part builder, everything is just fine.**

Comparing the two generated files, with part-of and without, seems to be different.

![Screen Shot 2022-09-04 at 14 59 53](https://user-images.githubusercontent.com/110026289/188312781-72ba7979-f3fb-4fae-a5ac-e95506ff9f31.png)

**Comment by CartmanGD** [comment]
I have also opened an issue in [StackOverflow](https://stackoverflow.com/questions/73599119/flutter-auto-route-delegate-and-defaultrouteparser-functions-not-exists)

**Comment by aidan-mundy** [comment]
The `delegate()` and `defaultRouteParser()` methods are inherited from `RootStackRouter`, and I can confirm that this issue isn't present on a barebones Flutter 3.3.0 install with auto_route 5.0.1

This appears to be an issue in your environment. Those two files are fundamentally equivalent. The only differences are the imports being present in the generated file (instead of being consumed from the main file), and the imports are given a prefix.

**Comment by CartmanGD** [comment]
Hey, @aidan-mundy thanks for replying. What do you suggest? To upgrade the flutter version?

Here are my flutter doctor results

Doctor summary (to see all details, run flutter doctor -v):
**[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-IL)**
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)

**Comment by aidan-mundy** [comment]
@CartmanGD have you tried restarting your IDE or running the program on a device (on VSCode you should get a prompt that lets you ignore the compilation errors)? It may just be the IDE toolchain being stubborn. 

You could try a flutter version upgrade, but I can't imagine that's the problem.

**Comment by CartmanGD** [comment]
Hey @aidan-mundy, I have upgraded my Flutter to 3.3.1 and it does not solve the issue. Restarting the IDE also didn't help :/

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by SSebigo** [comment]
Same problem as @CartmanGD, I've reinstalled Flutter but still no luck.
I am using Flutter 3.3.1 on Windows 10.

**Comment by SSebigo** [comment]
Generating the ```.gr``` file without ```part``` and no extended class seems to work. But it means that I have to import the ```.gr``` file directly.

**Comment by FyndetNeo** [comment]
I experienced the same issue on a Mac. Maybe mention in the docs that this can be a point of failure.
