### ISSUE TITLE
automatic generate drawer from given userPermissions(authorization=> different roles/accesslevels/ organizational affiliation) 

### ISSUE THREAD

**Issue by Ronjack** [Milad-Akarie/auto_route_library#1219]
Hey Milad-Akarie, fiirst I wanted to say thank you for this auto-route package... its just pure gold! Very good work! 

Secondly I have a question(oh wonder :D):
 

The app which I am developing has 3 main requirements in relation to the routing/navigation: 
1. There are routes depending on different userroles(authorization)  
2. There are routes  depending on different customers(kind of cumbersome individualentwicklung individual development)
3. The drawer/nested drawer should autogenerated the menupoints from the routes 

currently I am handled the problem with a map which defines the visiblity, icons and authoriazionId 

![image](https://user-images.githubusercontent.com/16069241/188612750-aab6c9ca-c023-4690-9319-179b9b74e701.png)

now i am struggeling with the migration of the autorouter into my project. 

Can I define custom parameters into the AppRouter => for example icons for the in drawer generation? 

I think I can implement the functionId(authoriatzion)-CHECK and the project-name_CHECK into a RouteGuard => BUT! this will not prevent the drawer from displaying the menupoint doesnt it? 

maybe I am just not see the forest for the trees...^^ but i didnt find much about authorization .. only authentification 

 
THANK YOU FOR YOUR HARD WORK!

**Comment by Milad-Akarie** [comment]
Hello @Ronjack That's an interesting use-case, although I think that's more of a state-management area than navigation/routing.
why don't you just hide/show Navigation links ( AppRoutes ) based on user-state? 
I feel like I'm missing something here lol

**Comment by Ronjack** [comment]
Hello @Milad-Akarie yeah you are right. I just realized it, that approutes == navlinks. I read over the NavLinks sample in the docu, thanks! So i was on the right way.




BUT 
it seems that thats not a pure state-management topic :

Because:
-NavigationLinks checks wether user can see NavLinks in drawer to NavigateTo routes
-Navigation Links coupled with the AppRoutes 
-will be problematic if in a NestedAppRoute there needs to check the permission Level => on this point the drawer can not generate the menu from the NavigationLinks anymore


sample:

*drawer filters NavigationLinks depending on usersPermissionLevel && usersOrganisationBelonging*

(NavLink 1)
-> PageRoute 1(NavLink) // NOT visible for current user
childs:
----> PR 1.1 
----> PR 1.2 

(NavLink 2)
-> PR 2(NavLink) // visible
childs:
----> PR 2.1
----> PR 2.2

(NavLink 3) // visible
childs:
-> PR 3
----> PR 3.1
----> PR 3.2

(NavLink Settings)
-> PR Settings
childs:
----> PR SettingsFor 1.1 // not visible, because user not enough permission to see PageRoute 1...so no settings for 1.1 anyway 
----> PR SettingsFor 2.1  // visible 
----> PR SettingsFor 3.1  // visible

(maybe a little bit confusing and over the top - not critical or urgently - i just want to figure out the boundaries of this package and how much i can autogenerate with this) 

THANKS!
