### ISSUE TITLE
Flutter inspector rebuilds app

### ISSUE THREAD

**Issue by p02diada** [Milad-Akarie/auto_route_library#122]
Hi, I have used version 3.0.0 without problem but now with version 0.5.0 I have a problem that when I try to inspect flutter widgets from Android studio it send me to the first screen of the app. Maybe it could be because of not using the default navigator?

**Comment by Milad-Akarie** [comment]
@p02diada  it has to do with the navigator state not being kept since it's not inside of the MaterialApp anymore
This will fix it
```
class MyApp extends StatelessWidget {
  final _exNavigatorKey = GlobalKey<ExtendedNavigatorState>();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: ExtendedNavigator(
        key: _exNavigatorKey,
        router: Router(),
      ),
    );
  }
}
```
