### ISSUE TITLE
[config] initial route in tab (AutoTabsRouter), how to provide contructor arguments?

### ISSUE THREAD

**Issue by peterweb2005** [Milad-Akarie/auto_route_library#1226]
when route object is flagged initial: true, when has contructor arguments, need construct like:
```
      routerDelegate: appRouter.delegate(initialRoutes: [
        AppRoute(aaa),
        //Tab0Route(aaa),
      ]),
```

but when "initial" route object is in tab (childrend of the tab), such as my "Tab0Route",
how to construct?
as when construct as above still throw: 
can not be null because it has a required parameter

**Comment by kentnek** [comment]
any update on this?

**Comment by dedonnodev** [comment]
Same happen to "AutoTabsRouter":
```dart
AutoTabsRouter(
 routes: [
  ShopRoute(catalog: catalog),
  const ShopClientRoute(),
  ],
 ...
 )
```

throw "FlutterError (ShopRouteArgs can not be null because it has a required parameter)"

I think that it ignores args passed to Routes in "routes".

**Comment by ujwalbasnet1** [comment]
any updates on this?
