### ISSUE TITLE
[BUG] RedirectRoute with pathParam appends `path` and `redirectTo` in url

### ISSUE THREAD

**Issue by adar2378** [Milad-Akarie/auto_route_library#1231]
Hi @Milad-Akarie , thank you very much the great work with the library.

We have a route setup with redirect like this 
```Dart
RedirectRoute(path: '/', redirectTo: '/home'),
    RedirectRoute(path: '/cafe/:slug', redirectTo: '/home/cafe/:slug'),
    RedirectRoute(
        path: '/cafe/:slug/table/:tableId',
        redirectTo: '/home/cafe/:slug/table/:tableId'),
```

When we go to `/cafe/0/` it redreicts to `/home/cafe/0/` fine but the URL in the browser address bar gets appended with both `path` and `redirectTo`

https://user-images.githubusercontent.com/8059258/190317207-61ef3de5-339e-4d29-b0cb-bd129d74af83.mov

**Comment by adar2378** [comment]
This only happens if we're redirecting to a child route inside a tab router

**Comment by adar2378** [comment]
More simplified configuration
If we go to `/two/:slug` path then the browser URL will be something like  `http://localhost:51357/#/tabs/two/0/two/0`

```Dart
@CustomAutoRouter(
  transitionsBuilder: TransitionsBuilders.zoomIn,
  durationInMilliseconds: 300,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    RedirectRoute(redirectTo: '/tabs', path: '/'),
    RedirectRoute(redirectTo: '/tabs/two/:slug', path: '/two/:slug'),
    AutoRoute(
      path: '/page_a',
      page: PageA,
    ),
    AutoRoute(path: '/home/page_b/:slug', page: PageB),
    AutoRoute(
      path: '/tabs',
      page: HomeTabPage,
      children: [
        AutoRoute(
          initial: true,
          path: 'one',
          page: TabOnePage,
        ),
        AutoRoute(
          path: 'two/:slug',
          page: TabTwoPage,
        )
      ],
      guards: [PageGuard],
    ),
  ],
)
```

**Comment by logic-and-math** [comment]
@adar2378 I am facing the same issue, did you find any workaround?

**Comment by adar2378** [comment]
@logic-and-math You can use RouteParser to change the path. For example, if `/some_redirect_path` presents in the parsed location, then replace `/some_redirect_path` with `/actual_path` .

**Comment by Andreigr0** [comment]
@adar2378 this works, yes, but I think it should work as described in the first message using `RedirectRoute`s
