### ISSUE TITLE
[Web] Can not resolve initial route

### ISSUE THREAD

**Issue by ihorkozar** [Milad-Akarie/auto_route_library#1232]
Hello, when I try to open a page on a broken link (non-existent route), I get an error "Uncaught (in promise) Error: Can not resolve initial route" and a screen filled with one color. 
In theory, in this case, redirection to the initial route should occur.
Has anyone else encountered this and what's your workaround?

=====
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F79 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by Milad-Akarie** [comment]
Do you have a wild card redirect route at the end of your route list?
RedirectRoute(path: '*', to:'/')

**Comment by ihorkozar** [comment]
No, that's my mistake. Thanks for the quick response. But why not implement this logic by default ?

**Comment by Milad-Akarie** [comment]
Some prefer to show a 404 page, or some other page than home page, so guess it's better to be user configurable
