### ISSUE TITLE
Conditional initial page

### ISSUE THREAD

**Issue by artem-romanov** [Milad-Akarie/auto_route_library#1233]
Hello everyone. I'm trying to understand auto_route library, but can't find best way to set initial router on application start.

My option is that I have 3 main flows: user can either go to settings page, to login or to home page. It depends on my shared preferences settings and settings my app will receive from a server.

I do all necessary logic in `void main()`, waiting for all needed responses. There I need to select right router for my needs.

How I should implement it? I see there several solutions:
1) Create empty pseudo-splash screen, which will navigate to right route.
2) Create hacky auth guard and try to tweak there.
3) I also saw routerDelegate's initialRoute field. Still, not sure how to work with it, as it doesn't described in the docs.

All these ways looks not right to me. Is there any better way?

**Comment by canbi** [comment]
https://autoroute.vercel.app/advanced/authentication

**Comment by RareScrap** [comment]
Facing the same problem. Any progress on it?

**Comment by artem-romanov** [comment]
In case if someone curious. Ended with second option. By default my app pulls all the necessary data, then navigates to HomeScreen. There I'm using my initialising guard, which either proceed user in HomeScreen, or navigates him into SignUp or other screens.

It's working, although I'm still think solution kinda hacky.
