### ISSUE TITLE
Release 5.0.2?

### ISSUE THREAD

**Issue by tjarvstrand** [Milad-Akarie/auto_route_library#1237]
Hi!

https://github.com/Milad-Akarie/auto_route_library/issues/1209 solves a dependency issue and it would be great if there could be a new release made with that fix.

**Comment by tim-eucalyptus** [comment]
Need to make sure this is updated: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/pubspec.yaml

As of today on master it still is not.
