### ISSUE TITLE
Add support for guarding routes in AutoTabsScaffold

### ISSUE THREAD

**Issue by SeriousMonk** [Milad-Akarie/auto_route_library#1238]
Hi, this package is amazing!

As I understand guarding a Route that is a Tab is still not supported.

However I believe that a huge percentage of flutter app use some variant of a main page composed of an AutoTabsScaffold and a Drawer, BottomNavigationBar or NavigationRail. It is also very common to want to guard only the profile tab and leave the others unguarded.

Is this a feature that this package will support anytime in the near future?
If not what would be the best solution to obtain this behavior?

Thanks in advance.

**Comment by wamynobe** [comment]
Hi, can we reopen this issue?
