### ISSUE TITLE
active tab name

### ISSUE THREAD

**Issue by mrqaidi** [Milad-Akarie/auto_route_library#1242]
Hi

how   i am able to get active tab name and refresh that tab page   

`    final tabsRouter = context.tabsRouter;
    tabsRouter.addListener(() {
      if (tabsRouter.activeIndex == 0) {
        setState(() {});
      }
    });`

in code above  its only index

**Comment by jtdLab** [comment]
Are you using the `AutoTabsRouter` or `AutoTabsScaffold`?

**Comment by jtdLab** [comment]
Can u provide some more context. Im not sure what goal u trying to achive.

Doest navigation with tabs work already?
