### ISSUE TITLE
Persist queryParams

### ISSUE THREAD

**Issue by iTEEECH** [Milad-Akarie/auto_route_library#1247]
Hi,

Out of curiosity, does Auto_route allow to persist the queryparam provided to the parent to his children ?

Thank you for your help.

``` AutoRoute(
      path: '/',
      page: ContentPage,
      initial: true,
      children: [
        AutoRoute(
          page: HomePage,
          initial: false,
          path: '',
        ),
        AutoRoute(
          page: FormPage,
          initial: false,
          path: '',
        ),
      ],
    ),
```

**Comment by Milad-Akarie** [comment]
@iTEEECH Query params belong to the whole url not just a segment, what's your use case?

**Comment by iTEEECH** [comment]
Hi @Milad-Akarie !

Thanks for your answer.

I use a queryparams to retrieve a json file in order to generate a form dynamically. But I have a particularity that I need to have a home page with a button to access this form so I persist my queryparams.

I found a solution in the meantime by using a state provider through riverpod.

**Comment by lpickford-pixelbeard** [comment]
> @rsegecin popping routes typically adds a new entry to the history stack, on web I'd suggest you use router.navigateBack() which utilizes the browser's back behaviour.

It looks like this is no longer the case and queryParams aren't persisted when using `router.back()`, and `router.navigateBack()` is deprecated. Is there another way to navigate back to a previous page in the stack and still see the queryParams?

**Comment by lpickford-pixelbeard** [comment]
Yes, so we start at for example `/search?name=john`, then go to `/user/1`, then go back and the url is now just `/search`. The queryParam is still persisted in the search page itself, just not reflected in the URL in the browser anymore.

**Comment by mitinKevadiya** [comment]
Any update on this issue?
