### ISSUE TITLE
[iOS] Nested routes scroll-to-top

### ISSUE THREAD

**Issue by csondi10** [Milad-Akarie/auto_route_library#1249]
Hi!

I'm using nested routes with bottom nav bar.
I also want to have the scroll-to-top feature on iOS (when the view is scrolled and the user taps on the status bar the view scrolls to the top). This is a built-in Flutter feature on Apple platforms and working fine if I'm on a pushed route (e.g. open a detail page from a list by tapping a list item). However on the root routes it doens't work.
The `Scaffold` catches the tap event but the scroll controller has no clients. 
This is the code that should handle the tap (it's in `scaffold.dart`):

```
// On iOS, tapping the status bar scrolls the app's primary scrollable to the
  // top. We implement this by looking up the  primary scroll controller and
  // scrolling it to the top when tapped.
  void _handleStatusBarTap() {
    final ScrollController? primaryScrollController =
        PrimaryScrollController.of(context);
    if (primaryScrollController != null && primaryScrollController.hasClients) {
      primaryScrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 1000),
        curve: Curves.easeOutCirc,
      );
    }
  }
```

So the condition fails because `primaryScrollController.hasClients` always returns false if I'm on a root page on any tab.

Any ideas?

**Comment by migalv** [comment]
Have you tried wrapping your bottom navigation bar parent with a`PrimaryScrollController`?

**Comment by Milad-Akarie** [comment]
@csondi10 have you tried what @migalv suggested?
