### ISSUE TITLE
How to restore last path after restart app?

### ISSUE THREAD

**Issue by The28AWG** [Milad-Akarie/auto_route_library#1255]
How to open the last screen after closing the application?
Any recommendations for a mobile app?

**Comment by Milad-Akarie** [comment]
@The28AWG you can listen to url state changes and persist the path, then on launch check for stored path and use as `initialDeepLink`, this approach does not support non-path arguments of course.

**Comment by The28AWG** [comment]
@Milad-Akarie This is the first time I've heard of such a setting. Google didn't make it clear. Could you give more context?
