### ISSUE TITLE
[Question] Having a back button when using deep linking with nested routing and AutoTabsScaffold

### ISSUE THREAD

**Issue by sjoulbak** [Milad-Akarie/auto_route_library#1257]
Hi @Milad-Akarie 👋 

First of all, thank you for maintaining this amazing library!

I'm going to write my question in a way as how I would write a bug. My question is: Is it possible to realize the expected behavior using this library?

### Steps to reproduce
I've created an example app to fully showcase my question, which can be found at: https://github.com/sjoulbak/auto_route_deeplinking

In this app I used `AutoTabsScaffold` with the following routing structure:
```dart
AutoRoute(
  page: HomeView,
  initial: true,
  children: [
    AutoRoute(
      path: 'dashboard',
      name: 'DashboardRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(page: DashboardView, initial: true),
        AutoRoute(path: 'planning', page: PlanningView),
      ],
    ),
    AutoRoute(
      path: 'users',
      name: 'UsersRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(page: UsersView, initial: true),
        AutoRoute(path: 'user', page: UserView),
      ],
    ),
  ],
),
```

This structure works good while clicking through the app; on initial load the `DashboardView` is shown, where the user can navigate to `PlanningView` with a back button. The user can also navigate to `UsersView` by using the tabs, where the user can navigate to `UserView`.

This structure works not so good with deep linking enabled. I've configured deep linking for Android and iOS to listen to the scheme `whooff` with the host `whooff.nl`. 

My question is about having the app fully closed or only opened the app without navigating to the `UsersView` by using the tabs and trying to navigate to `UsersView` -> `UserView` by using deep linking with:
- Android: `adb shell am start -d whooff://whooff.nl/users/user`
- iOS: `xcrun simctl openurl booted whooff://whooff.nl/users/user`

### Expected behavior
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1494052/197198767-2241fe79-e8f3-4946-b6c3-1b71c1d21732.png">

I'm at the `UserView` and I can navigate back to `UsersView`.

### Actual behavior
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1494052/197198932-6ce2c2da-7dd7-4045-a1a4-fd68f41fe7a2.png">

I'm at the `UserView`, but I cannot navigate back to the `UsersView`.

**Extra note;** If I initially navigate to the `UsersView` and stay on that view or navigate back to the `DashboardView`, then I get the back button on the `UserView` when using deep linking. 

### System configuration
**Flutter doctor**:
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by Milad-Akarie** [comment]
@sjoulbak try to set includePrefixMatches to true in defaultPathParser

**Comment by sjoulbak** [comment]
Hi @Milad-Akarie! Thank you for you fast response! This fixes the scenario! 🎉
