### ISSUE TITLE
How to listener the pop from the previous page

### ISSUE THREAD

**Issue by azhengyongqin** [Milad-Akarie/auto_route_library#126]
### How to listener the pop from the previous page
I have a page *B*  that was opened from a network request interceptor  When *B* call `ExtendedNavigator.rootNavigator.pop();` it goes back to *A*. 

How do I listen to the router `pop` from B on page A，Because my page B is not `push` from page A . 

![image](https://user-images.githubusercontent.com/18138282/84390224-d5461d00-ac29-11ea-8423-d9fa490c3861.png)

**Comment by Milad-Akarie** [comment]
val result = await ExtendedNavigator.rootNavigator.pushNamed<ReturnType>(screenB)
then inside of B 
pop<ReturnType>(result)

**Comment by azhengyongqin** [comment]
call `"PushNamed (screenB)` is not on A ，call `pushNamed (screenB)` is in  public network interceptor class

**Comment by Milad-Akarie** [comment]
I'm gonna advise you to consider a more architected approach.
but if you're still going with this can always pass a callBack function to your networkRequest function and act upon the results
```dart
networkRequest((isLoggedIn) async {
val result = await ExtendedNavigator.rootNavigator.pushNamed(screenB)
}) `
```
which should return 
```dart
void networkRequest(Function(bool) onAuthResult){
   // do your calls here
  onAuthResult(isLoggedIn)
}

```

**Comment by azhengyongqin** [comment]
Thank you very much for your advice!
