### ISSUE TITLE
Nesting a TabBar top navigation inside a Bottom Nav structure

### ISSUE THREAD

**Issue by login3b7e** [Milad-Akarie/auto_route_library#1261]
Hello,

I'm trying to build an application that has a bottom navigation bar as main navigation between pages of the app, with some pages having another level of tabbed navigation (with a TabBar under the AppBar). I can't work out the best way to make this happen.

Simplifying it into the following example (with only 2 bottom tabs) it would be something like the following structure

- A BottomNavigationView page with a bottom navigation bar with 2 pages, Page1 and Page2 - this the main navigation
- Page1 has 2 tabs in a TabBar (TabA and TabB)
- Page2 has no tabs

and the router class (with some child routes removed for brevity) I made looks like

```
@MaterialAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: BottomNavigationView,
      children: [
        AutoRoute(
          path: 'page1',
          page: Page1View,
          children: [
            AutoRoute(
              path: 'tabA',
              name: 'TabARouter',
              page: EmptyRouterPage,
              children: [
                AutoRoute(path: '', page: TabAView),
              ],
            ),
            AutoRoute(
                path: 'tabB',
                name: 'TabBRouter',
                page: EmptyRouterPage,
                children: [
                  AutoRoute(path: '', page: TabBView),
                ]),
          ],
        ),
        AutoRoute(
          path: 'page2',
          name: 'page2Router',
          page: EmptyRouterPage,
          children: [
            AutoRoute(path: '', page: Page2View),
            AutoRoute(path: 'add', page: Page2AddView),
          ],
        ),
      ],
    ),
  ],
)
// extend the generated private router
class AppRouter extends _$AppRouter {}
```

The BottomNavigationView uses an AutoTabsScaffold

```
AutoTabsScaffold(
  // build the list of routes the tabs will navigate to
  routes: const [
        Page1Route(),
        Page2Route(),
      ],
  // build the bottom navigation bar
  bottomNavigationBuilder: (_, tabsRouter) => BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (index) {
        tabsRouter.setActiveIndex(index);
      },
      items: [
          const BottomNavigationBarItem(
            label: 'Page 1',
            icon: Icons.icon1,
          ),
          const BottomNavigationBarItem(
            label: 'Page 2',
            icon: Icons.icon2,
          ),
      ]
    ),
),
```

and for the tabs in Page1 the build method of Page1View returns an AutoTabsRouter with the tabBar constructor which adds another (nested) Scaffold

```
AutoTabsRouter.tabBar(
  routes: const [
    TabARouter(),
    TabBRouter(),
  ],
  builder: ((context, child, controller) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page 1'),
        leading: const AutoLeadingButton(),
        bottom: TabBar(
          controller: controller,
          tabs: const [
              Tab(child: Text('Tab A')),
              Tab(child: Text('Tab B')),
          ],
        ),
      ),
      body: child,
    );
  }),
)
```

This was the only way I was able to make this navigation structure work, but it's certainly not ideal and there is likely an issue with my understanding.

This approach has a nested scaffold on every page (one from the BottomNavigationView's AutoTabScaffold and one from the AutoTabsRouter.tabBar) which I will likely be problematic later on. Moving from Page1 to Page2 doesn't look all that great either because the Scaffold and AppBar are replaced, so the AppBar blinks momentarily in and out of existence.

I tried to make it work the appbar builder of the AutoTabsScaffold

```
AutoTabsScaffold(
  routes: [ bottom nav routes ],
  appBarBuilder: () => AppBar(
    bottom: if(tabsRouter.activeIndex == indexofpage1) TabBar(tabs: [ tabA, tabB ]),
  ),
  bottomNavigationBuilder: (_, tabsRouter ) => the bottom nav bar
)
```

but I don't know how to set up the Tabbar, its routes and controller properly and wasn't able to set the body of the scaffold to TabAView, TabBView (while on Page1) or a Page2 page. 

Can this be done in a correct way and if so what would be the recommended approach?

**Comment by Milad-Akarie** [comment]
do you have to build an AppBar in the nested tabs page? why not just build a TabBar?
