### ISSUE TITLE
Popping to another router

### ISSUE THREAD

**Issue by David200337** [Milad-Akarie/auto_route_library#1262]
Hi,

I am building an app using the auto route library with the `AutoTabsRouter`. The app has three tabs: explore, saved and account. The user is able to view the explore tab without the need to be logged in, but whenever either the saved or account tab is opened, (without being logged in) a widget displays letting the user know that logging in is required to view this page. Therefore, this widget has a button that redirects to login.

The problem is that whenever you press this button the login page opens fine, but it can't be closed.
My router looks like the following:
```dart
@AdaptiveAutoRouter(replaceInRouteName: 'Page,Route', routes: <AutoRoute>[
  CustomRoute(
    path: '/login',
    page: LoginPage,
    transitionsBuilder: TransitionsBuilders.noTransition,
  ),
  CustomRoute(
    path: '/register',
    page: RegisterPage,
    transitionsBuilder: TransitionsBuilders.noTransition,
  ),
  CustomRoute(
    path: '/',
    initial: true,
    page: HomePage,
    name: 'HomeRouter',
    maintainState: false,
    guards: [OnboardingGuard],
    children: [
      AutoRoute(
        path: 'explore',
        name: 'HouseRouter',
        page: EmptyRouterPage,
        children: [
          AutoRoute(
            path: '',
            page: HouseMapPage,
          ),
          AutoRoute(
            path: ':houseId',
            page: HouseDetailPage,
          ),
          RedirectRoute(
            path: '*',
            redirectTo: '',
          ),
        ],
      ),
      AutoRoute(
        path: 'saved',
        name: 'SavedRouter',
        page: EmptyRouterPage,
        children: [
          CustomRoute(
            path: '',
            page: SavedPage,
          ),
          AutoRoute(
            path: ':savedId',
            page: SavedDetailPage,
            guards: [AuthGuard],
          ),
          RedirectRoute(
            path: '*',
            redirectTo: '',
          ),
        ],
      ),
      AutoRoute(
        path: 'account',
        name: 'AccountRouter',
        page: EmptyRouterPage,
        children: [
          AutoRoute(
            path: '',
            page: AccountPage,
          ),
          AutoRoute(
            path: '',
            page: SettingsPage,
            guards: [AuthGuard],
          ),
          RedirectRoute(
            path: '*',
            redirectTo: '',
          ),
        ],
      ),
    ],
  ),
])
class AppRouter extends _$AppRouter {
  AppRouter({
    required AuthGuard authGuard,
    required OnboardingGuard onboardingGuard,
  }) : super(
          authGuard: authGuard,
          onboardingGuard: onboardingGuard,
        );
}
```
As shown above, the `HomeRouter` includes three nested routers: `HouseRouter`, `SavedRouter` and `AccountRouter`. Besides the `HomeRouter` are two other routes for login and registration.

So, once the user navigates to the `SavedPage` or the `AccountPage` a widget with the following button displays:
```dart
...
PrimaryButton(
  child: const Text('Login'),
  onPressed: () => AutoRouter.of(context).push(const LoginRoute()),
),
...
```
This button pushes the `LoginRoute` onto the stack so that the login page gets shown.
And this login page includes a close button, which pops the route:
```dart
...
IconButton(
  icon: SvgPicture.asset(
    'assets/icons/xmark.svg',
    width: 24,
    height: 24,
  ),
  onPressed: () => AutoRouter.of(context).pop(),
),
...
```
However, this pop does not seem to do anything (visually), although the route does appear to be popped from the stack... 
To debug this issue, I set a breakpoint before and after the pop. The stack of the router (Root Router) indeed includes two pages before the pop:

<img width="550" alt="Screenshot 2022-10-27 at 7 54 15 PM" src="https://user-images.githubusercontent.com/32228588/198363408-32460ee7-ac40-4fb3-bc24-53367d317c04.png">

And includes just one page afterwards, but still shows the login page:

<img width="550" alt="Screenshot 2022-10-27 at 7 56 21 PM" src="https://user-images.githubusercontent.com/32228588/198363725-08e15a16-bafa-4058-bdb6-2d51a1c5b40c.png">

Am I doing something wrong here, or may it be a bug?
Thank you in advance!

**Comment by wezooyuri** [comment]
Bumping, I've seen this issue too. No real explanation as to why this doesn't work in the docs.

**Comment by mcssym** [comment]
Hi, rather than `AutoRouter.of(context).pop()`  did you try `Navigator.of(context).pop()` ? Seeing your logs it seems AppRouter is updated but the actual Navigator is not.

**Comment by David-van-Mourik** [comment]
Hi @mcssym! Thanks for your suggestion, but unfortunately it did not seem to resolve the issue...
Although I did find out that a double tap on the close button (which calls `AutoRouter.of(context).pop()`) does pop the page surprisingly enough.

**Comment by David200337** [comment]
I'm closing this issue as @wezooyuri found the problem! It was due to a `router.push(const LoginRoute())` in the authentication guard. 😅

So each time when the pop would would take place on the login page, the authentication guard would push the login page onto the stack again, causing it to be shown again.

Thanks for everyone's help!
