### ISSUE TITLE
[QUESTION] How to create guard for deep linking?

### ISSUE THREAD

**Issue by InAnadea** [Milad-Akarie/auto_route_library#1267]
I need to disallow all deep links when a user is on a specific screen. Or show a confirmation dialog for navigating by link or not.

**Comment by Milad-Akarie** [comment]
all navigation event go throw guards, I'm not sure if I understand your question.

**Comment by InAnadea** [comment]
My app is in a specific state when I can't open deep links. For example I'm taking a test and I need to disable deep linking while I'm taking a test

**Comment by Milad-Akarie** [comment]
@InAnadea put a guard on the root page that prevents it

```dart
class DeepLinkGuard extends AutoRouteGuard {
  @override
  Future<void> onNavigation(NavigationResolver resolver, StackRouter router) async {
      // if current page is target page don't navigate
      if(router.current.name == TestRoute.name){
        resolver.next(false);
      }

   }
  }
```
