### ISSUE TITLE
RedirectRoute to '' fails

### ISSUE THREAD

**Issue by martinralfreindl** [Milad-Akarie/auto_route_library#1268]
I am trying to use RedirectRoute() to redirect the url www.mywebsite.com/sign-in/test to www.mywebsite.com/sign-in
on Flutter Web, but my runs into a "Uncaught Can not resolve initial route" error, when I try to navigate to the page 

    @MaterialAutoRouter(
      replaceInRouteName: 'Page,Route',
      routes: [
        // Defines the route for the landing page 
        AutoRoute(path: '/', page: LandingPage, initial: true),
    
        // Defines the routes for the sign-in pages
        AutoRoute(path: '/sign-in', name: 'SignInRouter', page: EmptyRouterPage,
          children: [
            AutoRoute(path: '', page: SignInPage),
            RedirectRoute(path: 'test', redirectTo: '')
          ]
        ),
      ],
    class $AppRouter {}

Am I missing something about how auto_route works? Is there an issue with my set-up?

**Comment by David200337** [comment]
Hey @martinralfreindl!

It might have something to do with the fact your `AppRouter` class is currently not extending from the auto generated `_$AppRouter` class.

You could try this:
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    // Defines the route for the landing page
    AutoRoute(
      path: '/',
      page: LandingPage,
      initial: true,
    ),

    // Defines the routes for the sign-in pages
    AutoRoute(
      path: '/sign-in',
      name: 'SignInRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(path: '', page: SignInPage),
        RedirectRoute(path: 'test', redirectTo: ''),
        
        // Alternatively, you could also replace the RedirectRoute path with '*'.
        RedirectRoute(path: '*', redirectTo: ''),
      ],
    ),
  ],
)
class AppRouter extends _$AppRouter {} // Ensure the auto generated class is extended from here.
```

You could also replace the redirect path with a wildcard (*) if you would like to redirect all following unspecified routes. In other words, this would redirect `/sign-in/{any unspecified following word}` to `/sign-in`.

Hope this helps!

**Comment by martinralfreindl** [comment]
Hey @David200337! 
I'm not using part builder (just have a standalone App Router class at the moment), so this didn't work for me.

**Comment by Milad-Akarie** [comment]
fixed
