### ISSUE TITLE
Flutter 1.2 compatability

### ISSUE THREAD

**Issue by AAllport** [Milad-Akarie/auto_route_library#127]
Upgrading to [flutter 1.2 (dev branch)](https://github.com/flutter/flutter/tree/1.20.0-0.0.pre) yields the following error.

I'll downgrade to stable in the meantime

```
I/flutter ( 6433): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#2050b):
I/flutter ( 6433): If no route is provided using home, routes, onGenerateRoute, or onUnknownRoute, a non-null callback
I/flutter ( 6433): for the builder property must be provided, and the other navigator-related properties, navigatorKey,
I/flutter ( 6433): initialRoute, and navigatorObservers, must have their initial values (null, null, and the empty
I/flutter ( 6433): list, respectively).
```

https://github.com/flutter/flutter/blob/1.20.0-0.0.pre/packages/flutter/lib/src/widgets/app.dart#L228-L245

**Comment by slavap** [comment]
@AAllport Not sure about you, but works for me in 1.20.0-2.0.pre

**Comment by AAllport** [comment]
Hmm, okay. I'll try getting a minimal example going to see if the issue is just localised to my current project!

**Comment by Milad-Akarie** [comment]
@AAllport don't pass anything navigator-related to Material App if you're using `builder: ExtendedNavigator()`
you can pass your config directly to `ExtendedNavigator()`
```dart
builder: ExtendedNavigator(intialRoute: ...,observers:...)
```

**Comment by AAllport** [comment]
So, here's the build function for our application
```dart
  @override
  Widget build(BuildContext context) => 
      MaterialApp(
        builder: (BuildContext context, Widget nativeNavigator) {
          Intl.defaultLocale = Localizations.localeOf(context).toString();
          return ExtendedNavigator<Router>(
            router: Router(),
            guards: [AuthGuard()],
          );
        },
        navigatorObservers: [FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())],
      );
```
(Although I have removed the theming and i18n just to keep the snip short)

I appreciate that It's not a completely standard setup, however, I don't believe it is too far out there to be considered out-of-scope.

`flutter version` output:
```
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (3 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

I'll be able to do a few more tests on a minimal project a bit later today

**Comment by Milad-Akarie** [comment]
@AAllport  try passing your FirebaseAnalyticsObserver to ExtendedNavigator's Observers not the materialApp's
``` dart
 @override
  Widget build(BuildContext context) => 
      MaterialApp(
        builder: (BuildContext context, Widget nativeNavigator) {
          Intl.defaultLocale = Localizations.localeOf(context).toString();
          return ExtendedNavigator<Router>(
            router: Router(),
            observers: [FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())]
            guards: [AuthGuard()],
          );
        },
   
      );
```

**Comment by AAllport** [comment]
Happy to confirm issue resolution, thanks!
