### ISSUE TITLE
AutoRouter builder cannot display content inside column

### ISSUE THREAD

**Issue by martinralfreindl** [Milad-Akarie/auto_route_library#1271]
Hi, 

I'm attempting to set a persistent header section across multiple pages (routes) in my website. I was hoping to use the AutoRouter builder property to make that happen, but I have been running into a  BoxConstraints forces an infinite height." error. 

**Router File:** 
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(path: '/', page: LandingPage, initial: true),
    AutoRoute(path: '/test', name: 'TestRouter', page: TestRouterPage,
      children: [
        AutoRoute(path: '', page: TestChildPage),
      ]
    )
  ]
)
class $AppRouter {}
```

**Test Router Page File:** 
```
class TestRouterPage extends StatelessWidget {
  const TestRouterPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AutoRouter(
        builder: (BuildContext context, Widget content) {
          return Column(
            children: [
              // persistent header goes here
              content
            ],
          );
        },
      ),
    );
  }
}
```

**Test Child Page File**
```
class TestChildPage extends StatelessWidget {
  const TestChildPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(color: Colors.blue, width: 100, height: 100);
  }
}
```

The issue seems to be that I am placing the content of the AutoRouter builder() function inside a column. I get the error even when I make my "Child Page" only display a simple container (as indicated in the example above). 

This issue is similar to the one that others have been facing [here](https://github.com/Milad-Akarie/auto_route_library/issues/561).

**Comment by Milad-Akarie** [comment]
@martinralfreindl AutoRouter-> Navigator needs a sized parent, just use Expanded(child: content) inside of the column
