### ISSUE TITLE
How to Block access to pages from address bar in Flutter Web ? 

### ISSUE THREAD

**Issue by daksh-pokar-shipsy** [Milad-Akarie/auto_route_library#1273]
I have web app, I want to block user from accessing pages using the addressbar, they can only navigate using the screens. How can we achieve this using auto route?

**Comment by moneer-muntazah** [comment]
hi try using `RedirectRoute`

**Comment by moneer-muntazah** [comment]
order matters so make sure your `RedirectRoute` is placed above the `AutoRoute` you want to prevent access to
