### ISSUE TITLE
[BUG] Array type QueryParam is not inserted correctly in the url

### ISSUE THREAD

**Issue by TheLiux** [Milad-Akarie/auto_route_library#1276]
## Current Behavior
When I navigate from page to page, array type query params are formatted as if they were a single value parameters.
With the parameter formatted this way, the deserialization of the parameters in [_normalizeSingleValues](https://github.com/Milad-Akarie/auto_route_library/blob/59c15601d42cad35a62cf9070fec893f95c99405/auto_route/lib/src/matcher/route_matcher.dart#L283-L285) fails to recognize the array type.
The bug becomes apparent when the page is refreshed in the browser.

### Example 
 ```dart
 void _navigate() {
    context.router.push(SecondRoute(testParams: const ['value1', 'value2']));
  }
 ```
 
Result: `www.example.com?testParams=[value1, +value2]`
 

## Expected Behavior
When I navigate from one page to another, the query params of type array are formatted correctly

### Example 
 ```dart
 void _navigate() {
    context.router.push(SecondRoute(testParams: const ['value1', 'value2']));
  }
 ```
 
Result: `www.example.com?testParams=value1&testParams=value2`

**Comment by KernelPanic92** [comment]
@Milad-Akarie The error probably occurs because the UrlState's _buildUri method is not checking for the "array" type at https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/router/parser/route_information_parser.dart#L122-L130
```dart
    if (lastSegment.queryParams.isNotEmpty) {
      var queries = lastSegment.queryParams.rawMap;
      for (var key in queries.keys) {
        var value = queries[key]?.toString() ?? '';
        if (value.isNotEmpty) {
          queryParams[key] = value.toString();
        }
      }
    }
```

### Possible solution
You could create a `_normalizeQueryParamValue` method to handle serialization properly:

```dart
dynamic _normalizeQueryParamValue(dynamic value) {
   if (value == null) {
      return null;
    }

    if (value is Iterable) {
      return value.map((el) => el?.toString()).toList();
    }

    if (value is! String) {
      value = value.toString();
    }

    if (value.isEmpty) {
      return null;
    }

    return value;
}
```

...and invoke it in the correct place:

```dart
for (var key in queries.keys) {
      var value = _normalizeQueryParamValue(queries[key]);
      if (value != null) {
        queryParams[key] = value;
      }
}
```

**Comment by Milad-Akarie** [comment]
@TheLiux Thank you for reporting @KernelPanic92 Thank you for debugging this, I've applied your fix and it's working.
