### ISSUE TITLE
Conditional initial route

### ISSUE THREAD

**Issue by sharpsan** [Milad-Akarie/auto_route_library#128]
In auto_route version 0.3.1 I implemented the first route shown using this:
```
              return MaterialApp(
                title: 'My App',
                onGenerateRoute: Router.onGenerateRoute,
                navigatorKey: Router.navigator.key,
                initialRoute: _isLoggedIn(_localStorage)
                    ? Router.homeRoute
                    : Router.loginRoute,
              );
```

But it appears this is no longer possible due to deprecation and `navigatorKey` no longer being exposed. 

Do you have any recommendation on the best way to determine the first route conditionally, depending on something like if the user is logged in?

**Comment by zebpay-peswani** [comment]
have you found solution to this problem i am facing the same.

**Comment by Milad-Akarie** [comment]
@sharpsan @zebpay-peswani ExtendedNavigator has an InitialRoute property

**Comment by sharpsan** [comment]
The annotation?  That defines a single route exclusively as the first route.  
Did you see my code snippet?

**Comment by Milad-Akarie** [comment]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
     builder: ExtendedNavigator<Router>(router: Router(), initialRoute: <YourInitalRoute>),
...
```

**Comment by sharpsan** [comment]
Did not see this in the docs.  Thank you!

**Comment by Milad-Akarie** [comment]
@sharpsan You should know that if for example your HomePage is named "/" and your LoginPage is named "/login" and you set initialRoute to "/login" both pages are going to be pushed because Flutter's navigator treats initial routes as deep links, meaning your stack will look like this ["/", "/login"]

**Comment by sharpsan** [comment]
For Android I've been able to handle this side effect by overriding the back button functionality.  Originally my thinking was it would be the cleanest approach to conditionally set the initial route programmatically, but as you pointed out this interferes with the expected pop behavior.

Do you think a cleaner solution is to make a dedicated route that returns either routeA widget or routeB's widget?  It seemed like overkill to me initially.

**Comment by Milad-Akarie** [comment]
maybe your very first approach would work if you don't name your home route "/" so you would have something like 
"/home"
"/login"

**Comment by Milad-Akarie** [comment]
My preferred approach would be to have one initialRoute that's always going to be pushed no matter what, then push a fullscreen login dialog from there and await for it so you act based on the results

```dart
var isLoggedIn = await ExtendedNavigator.of(ctx).pushNamed<bool>(loginPage)
if(isLoggedIn){
  updatePage()
} else{
  //assuming your App requires authentication
    exit(0);
}

```
pushing your loginPage as a fullscreenDialog will make the back arrow (the Navigation arrow) a dismiss button (X) icon, can even chose not to display it so it would look like nothing is behind it. 
Wrap your LoginPage Scaffold with a  WillPopScope so when users hit the X button or the soft back button on android you can pop with failure

```dart
 return WillPopScope(
      onWillPop: () async {
        // pop with results
        ExtendedNavigator.of(context).pop(false);
        // returning false disables original pop action
        return false;
      },
      child: Scaffold()
....
```

**Comment by maxusr** [comment]
The easiest way is to write a custom name to your routes without the leading `/` like 
```
@MaterialAutoRouter()
class $Router {
 @MaterialRoute(name: 'home-sceen') // home-screen rather than /home-screen generated automatically
  HomeScreen homeScreen;
 @MaterialRoute(name: 'second-sceen')
  SecondScreen secondScreen;
}
```

And in your MaterialApp, set the property `initialRoute` like
```
final initialRoute = condition ? Routes.homeScreen : Routes.secondScreen;
MaterialApp(
          initialRoute: initialRoute,
          builder: ExtendedNavigator<Router>(
            router: Router(),
            guards: [AuthGuard()],
            initialRoute: initialRoute,
          ),
...
```
