### ISSUE TITLE
navigator key

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [Milad-Akarie/auto_route_library#1281]
I want to show dialog without context or show dialog in which I don't have my wanted page's context. how can I?  I search, We can do it with the Navigator key in MaterialApp. in auto route how we can do this?

**Comment by Petri-Oosthuizen** [comment]
Please see the [Navigating Without Context](https://github.com/Milad-Akarie/auto_route_library#navigating-without-context) section in the [README.md](https://github.com/Milad-Akarie/auto_route_library#readme).

I prefer the get_it solution.

**Comment by Shahmirzali-Huseynov** [comment]
@Petri-Oosthuizen thank you for reply,

But I want to show dialog (showDialog function in flutter), not to navigate some of page. show dialog function require context.

**Comment by Petri-Oosthuizen** [comment]
Add a `GlobalKey<NavigatorState>` to your DI. Add this to your AppRouter: `AppRouter(getIt.get<GlobalKey<NavigatorState>>())`. 

Now you can access the context to show dialogs:
```final globalContext = getIt.get<GlobalKey<NavigatorState>>().currentContext!;```

**Comment by Shahmirzali-Huseynov** [comment]
thank you it's work.
