### ISSUE TITLE
Return value from navigate

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [Milad-Akarie/auto_route_library#1282]
### Background:
I'm injecting the AppRouter into a DI service and using `navigate` to navigate pages. The reason for injecting the AppRouter into DI is that I can unit-test the navigations this way. The reason I'm using `navigate` and not `push/pop` is because I'm using nested navigation and according to the [docs](https://github.com/Milad-Akarie/auto_route_library#navigating-without-context): "navigating without context is not recommended in nested navigation unless you use navigate instead of push".

I'm open to suggestions if there is a better way to unit test navigation with context navigation (push/pop).

### The Problem:
I need the result from the child page on the parent page. One way to get this result is using callbacks but I'm not a big fan of that. The `navigateBack` method does not accept result arguments.

**Comment by Milad-Akarie** [comment]
Hello @Petri-Oosthuizen having navigate return results is a bit hard to accomplish because navigate may not always push a new page to the stack, it may just pop until the target page. 

the reason for my comment '...unless you use navigate' is to not have multiple unnecessary entires in your stacks.
e.g if we have this stack
```
'/'
'/second/sub1'
```
and from root you **PUSH** '/second/sub2'
you'll end up with a stack that looks like this
```
'/'
'/second/sub1'
'/second/sub2'
```

but if you use navigate, your stack will look something like this
```
'/'
'/second/sub2'
```

if you want to achieve the same result using push you might manually acquire the nested router and call push on it.

`final res = await rootRouter.innerRouterOf<StackRouter>(SecondRoute.name)?.push<TypedRes>(Sub2Route());`

**Comment by Petri-Oosthuizen** [comment]
Thank you for the response. That seems like quite a bit of code to use each time to push to a page. Interesting that you can do it though!

Out of curiosity how do you test the navigations(`push/pop/navigate`) in your widget tests? This is where the need for me to use a global AppRouter started. If this is not necessary I don't really have to worry about using navigate vs push.

**Comment by Milad-Akarie** [comment]
@Petri-Oosthuizen I found the best way is to use a mocked `NavigatorObserver`, which auto_route has an extended version of `AutoRouterObserver` ( use if have tab routes )
basically you would verify event methods like this

`verify(mockObserver.didPush(any!, any));`

here's a complete example of your test case

```dart
// using mocktail to generate mocks
@GenerateNiceMocks([MockSpec<AutoRouterObserver>()])
import 'package:auto_route/auto_route.dart';

  testWidgets('test top route popping result',(WidgetTester tester) async {

    await tester.pumpWidget(MaterialApp.router(
      routeInformationParser: router.defaultRouteParser(),
      routerDelegate: router.delegate(
        // we're using a callback observers builder
        // because Navigator widget does not allow
        // the usage of the same observer for different navigators
        navigatorObservers: () => [MockAutoRouterObserver()],
      ),
    ));

    router.push(const SecondRoute(
      children: [
        SecondNested1Route(),
        SecondNested2Route(),
      ],
    ));
    await tester.pumpAndSettle();

    // Every AutoRouter widget has RouterScope parent
    // that has all inherited Observers, so finding the last observer
    // would mean the nearest to the current context
    //
    // you can make a helper method for that
    final scope = find.byType(RouterScope).last.evaluate().first;
    final observer = (scope.widget as RouterScope).firstObserverOfType<MockAutoRouterObserver>()!;

    // calling popTop will call pop on the most top router in the hierarchy
    await router.popTop('result');
    // capture the popped route passed to observer.didPop
    final verifyResult = verify(observer.didPop(captureAny, any)).captured.single;
    // now the popped result is inside of a Completer and route.popped is a returned
    // future of that completer
    final res = await (verifyResult as Route).popped.then((value) => value);
    expect(res, 'result');
  });
```

**Comment by Petri-Oosthuizen** [comment]
Thank you for your response! That is very similar to what I initially did!

My only issue is the fact that I want to be able to test pages in isolation without having to worry about mocking the view models of the pages navigated to in the widget tests. This is fine for integration tests though.

In the end, I got around this by extending the AutoRouter so that I could inject and mock it. This way the navigation never occurs during a test.

**Comment by Milad-Akarie** [comment]
@Petri-Oosthuizen let me know if there is any test-helper utils or methods I should add to AutoRouter
