### ISSUE TITLE
Chrome back button works when using `replaceAll`

### ISSUE THREAD

**Issue by erayerdin** [Milad-Akarie/auto_route_library#1286]
While `replaceAll` works on Android well, it does not work as expected in Chrome. I can still go back with back button in Chrome. Is this because how navigation works different in web?

---

# Environment

 - Flutter (Channel stable, 3.3.9, on Fedora Linux 36 (KDE Plasma) 6.0.9-200.fc36.x86_64, locale en_US.UTF-8)
 - Auto Route 5.0.2

**Comment by erayerdin** [comment]
This, unfortunately, didn't work. Still can go back. My code is:

```dart
if (kIsWeb) {
  context.router.markUrlStateForReplace();
}
context.router.replaceAll([const LoginRoute()]);
```

**Comment by AshishAcharya083** [comment]
Still facing this issue.
