### ISSUE TITLE
AutoRouteObserver not working for AutoTabsRouter.tabBar()

### ISSUE THREAD

**Issue by prembankerquicko** [Milad-Akarie/auto_route_library#1287]
Hey @Milad-Akarie, was having trouble calling a function everytime the tab was changed. Looked at #1124 for reference.

The solution using `context.tabRouter` worked but the `AutoRouteObserver` solution failed. Integrated it just as you mentioned it there. Any reason for this?

**Comment by Milad-Akarie** [comment]
@prembankerquicko I think this's already fixed, try using the git version until I push  the next release.

**Comment by prembankerquicko** [comment]
@Milad-Akarie Cool, thanks!

**Comment by Milad-Akarie** [comment]
@prembankerquicko version 5.0.3 published to pub.dev
