### ISSUE TITLE
RangeError (start): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#1288]
Hey,
With new update, the app isn't starting. throws this error:
`RangeError (start): Invalid value: Only valid value is 0: 1`
```
When the exception was thrown, this was the stack:
#0      RangeError.checkValidRange (dart:core/errors.dart:358:7)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      RouteMatcher._match (package:auto_route/src/matcher/route_matcher.dart:123:44)
#3      RouteMatcher._match (package:auto_route/src/matcher/route_matcher.dart:138:27)
#4      RouteMatcher.matchUri (package:auto_route/src/matcher/route_matcher.dart:85:12)
#5      DefaultRouteParser.parseRouteInformation (package:auto_route/src/router/parser/route_information_parser.dart:20:18)
#6      RouteInformationParser.parseRouteInformationWithDependencies (package:flutter/src/widgets/router.dart:1213:12)
#7      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:707:8)
```

**Comment by JeffTyfoom** [comment]
Same here!

**Comment by Milad-Akarie** [comment]
@JeffTyfoom can you please share your router setup before you renaming empty paths?

**Comment by Milad-Akarie** [comment]
@naamapps @JeffTyfoom  should be fixed in 5.0.4. Please confirm and close.

**Comment by naamapps** [comment]
Fixed indeed, tnx @Milad-Akarie.

**Comment by JeffTyfoom** [comment]
@Milad-Akarie 

I've found some strange behavior on router.pushNamed after renaming the path back to empty string.

If I will push a page from page2 to page3, the page that will push is page2 instead of page3. But If I will rename the path to non-empty string it will be fine.

Check this sample repo https://github.com/Jifflis/id-generator



##Page2

```dart
class SamplePage2 extends StatelessWidget {
  const SamplePage2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page 2'),
      ),
      body: Center(
        child: InkWell(
            onTap: () {
              context.router.pushNamed('SamplePage3');
            },
            child: Text('Page 2')),
      ),
    );
  }
}

```


##router.dart

```dart
@AdaptiveAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: PageInitialWrapper,
      children: [
        AutoRoute(
          path: '',
          page: PageLayout,
          initial: true,
        ),
        AutoRoute(path: 'SamplePage3', page: SamplePage3),
        AutoRoute(path: 'SamplePage', page: SamplePage, children: [
          AutoRoute(path: '', page: SamplePage2, initial: true),
        ])
      ],
    )
  ],
)
class $AppRouter {}

```

**Comment by JeffTyfoom** [comment]
Video 1 Using  context.router.pushNamed('SamplePage3');
https://user-images.githubusercontent.com/91708709/204271807-a551e2a4-d58c-4948-8506-b48547f798f2.mov


Video 2 Using context.router.push(SamplePage3Route());

https://user-images.githubusercontent.com/91708709/204271968-7105c803-6526-4f9a-beac-671d839fa0de.mov

**Comment by JeffTyfoom** [comment]
Video 1 Using   context.router.pushNamed('SamplePage3');

https://user-images.githubusercontent.com/91708709/204273152-9ec72071-3759-4144-8cda-04b78f57ae67.mov

Video 2 Using context.router.push(SamplePage3Route())


https://user-images.githubusercontent.com/91708709/204273233-ac554576-f1a6-4cd1-accd-00f4905fdeab.mov

**Comment by Milad-Akarie** [comment]
Hello @JeffTyfoom that actually makes perfect sense because,  auto_route will try to match the given path by the nearest routing controller which in your case is `SamplePage's` controller.

I added some comments to visually explains what's happening. 
```dart
@AdaptiveAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: PageInitialWrapper,
      children: [  // children here are controller by PageInitialWrapper Router
        AutoRoute(
          path: '',
          page: PageLayout,
          initial: true,
        ),
        AutoRoute(path: 'SamplePage3', page: SamplePage3),
        AutoRoute(path: 'SamplePage', page: SamplePage, children: [ // children here are controller by SamplePage Router
          AutoRoute(path: '', page: SamplePage2, initial: true),
        ])
      ],
    )
  ],
)
class $AppRouter {}
```

so from SamplePage2 if you call push on the parent you'd go to SamplePage3 with empty path
context.router.parent<StackRouter>().pushNamed('');
