### ISSUE TITLE
Redesign AutoRoute?

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#1289]
Hello everyone,

I've been trying to add new features to auto_route but every time I get blocked by the fact that I'm working in the **static** realm in which annotations operate, e.g if we have a `RoleGuard` that needs to be constructed with different arguments for each route, we could not do that in the current implementation.    

so I came up with something and I'd like to hear what you guys think about it. 
The idea is simple, separate the parts of route that require generation from that parts that don't. 

instead of assigning Type pages to `AutoRoute` we assign what `@RoutePage()`   generates. 

**Note**: you will not have to add part imports because all route pages are going to be generated inside `router.gr.dart `

```dart
@RoutePage()
class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {}
}

@RoutePage()
class BooksScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {}
}
```
Our router will extend some base router class that requires overriding of `routes` getter.
with this implementation we can simple have localized title builder, or onInit trigger and most importantly list of actual RouteGuards that can be constructed separately for each route. 

```dart
@AutoMaterialRouter()
class $AppRouter extends AutoRouterBase {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(path: '/', page: HomeRoutePage()), // HomeRoutePage() is a generated reference of [HomeScreen]
        AutoRoute(
          path: '/books',
          page: BooksRoutePage(),
          onInit:(){},
          titleBuilder: (context) => S.of(context).booksScreen,
          guards: [AutoGuard(), RolesGuard([Role.admin])],
        ),
      ];
}
```
extra pros of the new implementation
1- Reducing generation time
2- Not needing to re-generate often

cons 
adding a new route config now requires two steps
 1- Annotating the route page with @RoutePage()
 2- Adding an AutoRoute entry with the generated route-page to the routes list

I might be able to Automatically add an AutoRoute Entry with defaults to the end of routes list once a new annotation is added and of course it can be customized later on
```dart
@AutoMaterialRouter()
class $AppRouter extends AutoRouterBase {
  @override
  List<AutoRoute> get routes => [
       ///... existing auto_route entries
        AutoRoute(path: '/new', page: NewRoutePage()), 
      ];
}
```

**Comment by prasant10050** [comment]
We should definitely do it. It will be very helpful for reducing generation time.

**Comment by mohn93** [comment]
What will happen to the args generation, I can't see an example here.

**Comment by Milad-Akarie** [comment]
@mohn93 Args will still be generated the same.

**Comment by mohn93** [comment]
@Milad-Akarie , Can we inject some dependency into guards?, I mean like from riverpod or injectable

**Comment by Milad-Akarie** [comment]
@mohn93 ofcourse, you can treat AppRouter as any other class in your project.

**Comment by mohn93** [comment]
@Milad-Akarie, I can't see why you need a dedicated title builder for the title, is it used for web things or what?

**Comment by Milad-Akarie** [comment]
Localized title

**Comment by mohn93** [comment]
@Milad-Akarie What title ?

**Comment by mohn93** [comment]
@Milad-Akarie And why I can't localize it inside of the screen widget?, Don't I have access to context there?

**Comment by mohn93** [comment]
`onInit:(){},` here you're not talking about the widget init function, right? I feel that if you're not, you should make it clearer

**Comment by Milad-Akarie** [comment]
@mohn93 I'm talking about the cases when you you're displaying different titles in the same place e.g you have a tabsRouter and 4 different titles that can be displayed in the main AppBar. 

@mohn93 I'm still considering  the onInit function it supposed to be called on route initiation so you can init some dependencies for example.

**Comment by mohn93** [comment]
@Milad-Akarie, that's useful, I suggest you add these clarifications to the `AutoRoute` constructor's documentation, it's better to understand how intended for these methods work, because the name you chose may mean different things to different people.

Other than that, I believe that this redesign brings value that allows us to overlook its cons easily, and I recommend implementing it.
