### ISSUE TITLE
Nested navigation Deep links bug

### ISSUE THREAD

**Issue by SofiSheromova** [Milad-Akarie/auto_route_library#1291]
Hi! I noticed a strange bug when following a deep link to a router with nesting greater than or equal to 3.   

Package version used:  
```dart
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.3
```

### Steps to Reproduce
1. The application must have nested navigation with routes nested 3 or more.
In my example, I use the following route tree:
```dart

@AdaptiveAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: SignInPage,
      path: '/sign-in',
    ),
    AutoRoute(
      page: EmptyRouterScreen,
      path: '/',
      initial: true,
      name: 'MainRoute',
      children: [
        AutoRoute(
          page: HomePage,
          initial: true,
          path: '',
        ),
        AutoRoute(
          page: EmptyRouterScreen,
          name: 'AccountRoute',
          path: 'account',
          children: [
            AutoRoute(
              page: ProfilePage,
              path: '',
              initial: true,
            ),
            AutoRoute(
              page: CodePage,
              path: 'code',
            ),
            AutoRoute(
              page: SettingsPage,
              path: 'settings',
            ),
          ],
        ),
      ],
    ),
  ],
)
class AppRouter extends _$AppRouter {}
```
2. Launch the application. I'm launching the app on the web for simplicity, but the bug also reproduces with mobile deeplinks set up.  
3. The example contains an authorization stub. When you click "sign in", the authorization is successful, the current path changes to `/`. Then you can go to the account, settings, code. Navigation inside the application is correct.
4. We are interested in deep linking. Being on the path `/`, replace the path with `/account`, transition was successful. Now let's try being on the path `/account`, replace the path with `/account/settings`, the transition did not occur.

**Expected results:** when you change the path from `/account` to `/account/settings`, you go to the settings

**Actual results:** no transition occurs  

https://user-images.githubusercontent.com/41895601/204224230-8c31d01e-b5df-4cce-9f95-17b4ddae39e4.mov

<details>
<summary>Code sample</summary>
I tried to make a small example, which can be viewed at the 
<a href="https://github.com/SofiSheromova/nested_navigation_bug">link</a>
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.9 on channel stable at /Users/ssheromova/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ssheromova/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ssheromova/Library/Android/sdk
    • Java binary at: /Users/ssheromova/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/ssheromova/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • rkda597hcqdm7pfq                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 mini (mobile)   • 15F7F353-5C13-4FF6-89F9-503A1E8637E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
 </details>

**Comment by SofiSheromova** [comment]
Path parsing is performed correctly. The problem is with navigation, which occurs in the `_navigateAll` method. It calls the `_popUntilOrPushAll` method, which then calls `_removeTopRouterOf` (line 920) with the `AccountRoute` argument.  
https://github.com/Milad-Akarie/auto_route_library/blob/b0de3a4547e38558efa43987174e6d89dfab913a/auto_route/lib/src/router/controller/routing_controller.dart#L920  
And since the `AccountRoute` `childController` has been deleted, its update does not occur (line 1198).   
https://github.com/Milad-Akarie/auto_route_library/blob/b0de3a4547e38558efa43987174e6d89dfab913a/auto_route/lib/src/router/controller/routing_controller.dart#L1198


![image](https://user-images.githubusercontent.com/41895601/204229877-cb607414-9b80-4d64-a207-b91c8c26288e.png)  
![image](https://user-images.githubusercontent.com/41895601/204229904-535021dc-5ce2-4a77-bafb-364fc28cabd7.png)  
![image](https://user-images.githubusercontent.com/41895601/204229958-b47e03f7-655f-41a6-85d5-d9ea4d35143a.png)  
![image](https://user-images.githubusercontent.com/41895601/204230022-083f837e-513f-44c3-9dcb-14ecb21b0991.png)

**Comment by Milad-Akarie** [comment]
Hello @SofiSheromova Thank you for this detailed report but unfortunately I still can't reproduce the bug. 

This's 3 levels deep navigation, and it worked at intended every time. 
https://user-images.githubusercontent.com/55059449/204484196-2b001680-86fc-4dda-b5b3-1aeb803425c0.mp4

can you please provide more info...
are you using a guard? 
are you hard reloading at any point?

**Comment by SofiSheromova** [comment]
@Milad-Akarie have you tried to reproduce the code from the example? I have posted it on github. It does not use guards, this bug is reproduced both debug and release build.   
Perhaps declarative navigation at the root somehow affects the work.

Can I see the application code that is in the video? Then I could compare with my code

**Comment by Milad-Akarie** [comment]
@SofiSheromova in fact declarative navigation may be the cause of this.
The example is inside of the repo 
https://github.com/Milad-Akarie/auto_route_library/tree/master/auto_route/example/lib/web

**Comment by SofiSheromova** [comment]
@Milad-Akarie I rewrote my code to imperative navigation from declarative, the problem was solved. I conclude that the problem exists only for declarative navigation. 

I also found another problem with deep links relevant for declarative navigation and the iOS platform. This is due to the scenario of deep links on this platform when the application is not launched. `setNewRoutePath` method gets the correct configuration, but `navigateAll` method does not always work correctly. As a result, deep link navigation does not occur, the user remains on the route '/' (in my case, this bug appeared 1 time out of 5-10 attempts). 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/41895601/205549503-d5ba1e52-0d83-4f12-8c9a-b4f2b5c53658.png">  
<a href="https://docs.flutter.dev/development/ui/navigation/deep-linking">documentation</a>  


Thank you for your package and your hard work! It's sad that declarative navigation is unstable, I've already gotten used to it. For now, I will return to using imperative navigation.

**Comment by Milad-Akarie** [comment]
@SofiSheromova does the iso deeplink bug appear in declarative or imperative routing? 
steps to reproduce?

**Comment by SofiSheromova** [comment]
@Milad-Akarie 
In my case, the problem is observed only in declarative navigation. Rewriting to imperative navigation solved the problem. It failed to reproduce on a simple example. It seems I was not quite right in the formulation of the problem. I think my problems were related to the fact that stack changes in the routes method (`declarativeDelegate` argument) and `setNewRouthPath` method can overlap each other's actions
