### ISSUE TITLE
Question about nested routing

### ISSUE THREAD

**Issue by pongloongyeat** [Milad-Akarie/auto_route_library#1293]
I have an app whose routing is set up as below:

```dart
part 'app_router.gr.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute<void>(
      path: '/onboarding',
      page: OnboardingPage,
      initial: true,
    ),
    AutoRoute<void>(
      path: '/tabs',
      page: MainTabPage,
      children: [
        AutoRoute<void>(
          path: 'home',
          name: 'HomeRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<void>(path: '', initial: true, page: HomeTabPage),
            AutoRoute<void>(
              path: 'feature-list',
              page: FeatureListLandingPage,
              children: [
                AutoRoute<void>(path: 'feature1', page: Feature1Page),
                AutoRoute<void>(path: 'feature2, page: Feature2Page),
                ...
              ],
            ),
          ],
        ),
        ...
        AutoRoute<void>(
          path: 'account',
          name: 'AccountRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<void>(path: '', page: AccountTabPage, initial: true),
          ],
        ),
      ],
    ),
  ],
)

// extend the generated private router
class AppRouter extends _$AppRouter {}
```

I'm trying to make a route containing a list of features in the home tab. The route (under the home tab) should be as follows:
- FeatureList
  - Feature1
  - Feature2
  - ...

However, I'm struggling to setup the routing as such and I keep getting `Looks like you're trying to navigate to a nested route without adding their parent to stack first try navigating to FeatureListLandingRoute -> Feature1Route` when navigate to `Feature1` from `FeatureList`. Printing the current route before pushing to `Feature1` shows that I am indeed on the correct router so the parent is already on the stack. Am I understanding something wrongly in regards to navigation here?

**Comment by mayken** [comment]
Same issue

**Comment by Milad-Akarie** [comment]
@pongloongyeat is FeatureListLandingPage a sub-routes host? does it contain an AutoRouter() widget? 
seems to me that your feautreList route setup should look like this

```dart
AutoRoute<void>(
              path: 'feature-list',
              page: EmptyRouterPage, // this page is mearly an AutoRouter widget to host sub-routes
              children: [
                 // setting this page path to empty will have it displayed on  '.../freautre-list'
                AutoRoute(path: '', page: FeatureListLandingPage),
                AutoRoute<void>(path: 'feature1', page: Feature1Page),
                AutoRoute<void>(path: 'feature2, page: Feature2Page),
                ...
              ],
            ),
```

**Comment by mayken** [comment]
Router:
`@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: RootScreen,
      initial: true,
      children: [
        AutoRoute(
          page: ProfileScreen,
          children: [
            AutoRoute(page: EditProfileScreen),
          ],
        ),
      ],
    ),
  ],
)`

`class RootScreen extends StatelessWidget {
  const RootScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AuthCubit, AuthState>(
      listenWhen: (p, c) => p.status != c.status,
      listener: (context, state) {
        context.router.navigate(const RootRoute());
      },
      builder: (context, state) {
        return Container(child: AppTextButton(text: "press me", onPressed: () {
          print(context.router.current.router.childControllers);
        },),);
      },
    );
  }
}`

in console log empty array or
`Looks like you're trying to navigate to a nested route without adding their parent to stack first
try navigating to RootRoute -> ProfileRoute`

**Comment by pongloongyeat** [comment]
@Milad-Akarie, the landing page does contain subroutes (if I understand your question correctly). Ideally, I'd like for the path to look something like this: `<appScheme>://<appDomain>/tabs/home/feature-list/feature1`. Setting the `FeatureList` page as an `EmptyRouterPage` didn't seem to help though. It throws `Looks like you're trying to navigate to a nested route without adding their parent to stack first try navigating to EmptyRouterRoute -> FeatureLandingRoute`.

If it's of any use, this is how I push my `FeatureLanding` page from the `HomeTab` page: `context.pushRoute(FeatureLandingRoute())`.

**Comment by Milad-Akarie** [comment]
@pongloongyeat the setup I suggested will give you the path you need. 

```dart
AutoRoute<void>(
              path: 'feature-list',
              page: EmptyRouterPage, // this will generate EmptyRouterRoute
              name: 'FeatureRoute', // use custom name instead
              children: [
                 // setting this page path to empty will have it displayed on  '.../freautre-list'
                AutoRoute(path: '', page: FeatureListLandingPage),
                AutoRoute<void>(path: 'feature1', page: Feature1Page),
                AutoRoute<void>(path: 'feature2, page: Feature2Page),
                ...
              ],
            ),
```
then just push(FeatureRoute());

**Comment by mayken** [comment]
> @mayken Any page that children routes MUST have an AutoRouter() widget to render those routes.

Thanks, I thought about the navigation stack of the entire application

**Comment by pongloongyeat** [comment]
@Milad-Akarie it doesn't seem to be working :/ I'm getting the same issue as before Looks like you're trying to navigate to a nested route without adding their parent to stack first
           try navigating to EmptyRouterRoute -> FeatureLandingRoute

**Comment by JaosnHsieh** [comment]
Same here. Flutter web app, In the initial page `login.dart`, call `context.router.navigate(const UserRoute());` when clicking got error on chrome console

```
Uncaught (in promise) Error: 
Looks like you're trying to navigate to a nested route without adding their parent to stack first
try navigating to EmptyRouterRoute -> UserRoute
```

routes.dart

```dart
import 'package:auto_route/annotations.dart';
import 'package:auto_route/empty_router_widgets.dart';
import '../pages/dashboard_page.dart';
import '../pages/login.dart';
import '../pages/post.dart';
import '../pages/settings.dart';
import '../pages/user.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(path: '/dashboard', page: EmptyRouterPage, children: [
      RedirectRoute(path: '', redirectTo: 'user'),
      AutoRoute(path: 'user', page: UserPage),
      AutoRoute(path: 'posts', page: PostPage),
      AutoRoute(path: 'settings', page: SettingsPage)
    ]),
    AutoRoute(path: '/login', page: LoginPage, initial: true)
  ],
)
class $AppRouter {}

```

login.dart
```dart
import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';
import '../routes/routes.gr.dart';

class LoginPage extends StatelessWidget {
  const LoginPage({super.key});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
        onPressed: (() {
          context.router.navigate(const UserRoute());
        }),
        child: Text('go to user route'));
  }
}

```

dashboard.dart
```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter_auto_route_test/pages/post.dart';
import '../routes/routes.gr.dart';
import 'package:flutter/material.dart';

class DashboardPage extends StatelessWidget {
  const DashboardPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Column(
          children: [
            ElevatedButton(
                onPressed: () {
                  context.router.push(const PostRoute());
                },
                child: Text('Post')),
            ElevatedButton(
                onPressed: (() {
                  context.router.push(const SettingsRoute());
                }),
                child: Text('Setting')),
            ElevatedButton(
                onPressed: () {
                  context.router.push(const UserRoute());
                },
                child: Text('User'))
          ],
        ),
        const Expanded(child: AutoRouter())
      ],
    );
  }
}

```
