### ISSUE TITLE
path parser

### ISSUE THREAD

**Issue by The28AWG** [Milad-Akarie/auto_route_library#1297]
Hello.
The current path parser does not support "advanced" paths. For example, you cannot use two or more parameters in the same path segment.
I suggest using the https://pub.dev/packages/path_to_regexp package to implement a more advanced path parser.
I need a path like `/:slug.:id` where `:slug` is of type String and `:id` is of type num(int or double)
It would be nice if could add a function pathValidator
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: DashboardPage,
      initial: true,
    ),
    AutoRoute(
      page: BookPage,
      path: '/book/:bookId',
      validate: bookPathValidate,
    ),
  ],
);
class AppRouter extends _$AppRouter {}

Future<bool> bookPathValidate(RouteData data) async {
  // validate route data
  return true;
}
```

**Comment by Milad-Akarie** [comment]
@The28AWG I don't know about that, I have a lot of logic per path segment so switching to regex matching might take a some time and effort, maybe if list the advanced uses cases I'd be able to support them with minimal code changes. 

 Path provider is a nice idea, what would happen if path is not valid?

**Comment by The28AWG** [comment]
The path provider (validator) must work in the same way as AutoRouteGuard. If the validation fails, then redirect the user to the 404 page (which must first be added for the web version of the application). Perhaps in the MaterialAutoRouter annotation it is worth adding the onUnknownRoute field to where to redirect the user if he made a mistake when typing the address. Or redirect to the path "*" if it exists.

I need to convert a human-readable address like /bookSlug.bookId in such a way that only bookId remains, while the bookSlug part is not very important to me. I know I can use a path like /:bookData with a String type and extract the bookId part later in the code, but it would be nice if auto_route did the work for me.

**Comment by The28AWG** [comment]
The AutoRedirectGuard behavior is ideal for validating path data. Just as an additional parameter to the onNavigation method, you need to pass RouteData which contains all the actual path data.
That is, first we find a match for the path, then we check the parameters using AutoRouteGuard/AutoRedirectGuard, if there are no problems, then we direct it to the path specified in RouteData, otherwise RouteGuard takes over the behavior control. It can redirect the path if it is an AutoRedirectGuard, or try to find another path if it is an AutoRouteGuard.

**Comment by The28AWG** [comment]
I originally suggested passing a function as a parameter because I like the json_serializable approach, but AutoRedirectGuard seems to store some redirect behavior data in it. So I do not insist on the original version.

**Comment by The28AWG** [comment]
It turns out that I was inattentive and my thinking distorted the word "Guard" in the class name.
I hope to see better handling of path parameters one day.
