### ISSUE TITLE
How can I get back to the previous page from when hide BottomNavigationBar on a specific page?

### ISSUE THREAD

**Issue by minhnguyenandpad** [Milad-Akarie/auto_route_library#1298]
Hello I have success to hide the BottomNavigationBar on a specific page. 
https://github.com/Milad-Akarie/auto_route_library/issues/732
Now how do I get back to the previous page where the BottomNavigationBar still visible? I try to pop but it's not working.
**Note:** Each of my screen have it own app bar.

**Comment by minhnguyenandpad** [comment]
I see this in your repository. But when using it. I got this error. `AutoTabsRouter operation requested with a context that does not include an AutoTabsRouter.`
```dart
class DashboardPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final tabsRouter = AutoTabsRouter.of(context);
    return AutoTabsScaffold(
      routes: const [
        UsersRoute(),
        PostsRoute(),
        SettingsRoute(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return BottomNavigationBar(
          currentIndex: tabsRouter.activeIndex,
          onTap: tabsRouter.setActiveIndex,
          items: const [
            BottomNavigationBarItem(label: 'Users',...),
            BottomNavigationBarItem(label: 'Posts',...),
            BottomNavigationBarItem(label: 'Settings',...),
          ],
        );
      },
    );
  }
}   
```

**Comment by Milad-Akarie** [comment]
@minhnguyenandpad try using router.navigateBack() instead of pop

**Comment by minhnguyenandpad** [comment]
> @minhnguyenandpad try using router.navigateBack() instead of pop

Hello @Milad-Akarie Where should I put this function?

**Comment by Milad-Akarie** [comment]
@minhnguyenandpad is the page you're hiding a sub-page inside of a tab?

**Comment by minhnguyenandpad** [comment]
@Milad-Akarie sorry for the late reply. I manage to do it with navigateBack().
