### ISSUE TITLE
Being able to list all routes

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/auto_route_library#13]
I have a drawer and I'm navigating to the pages by index. It would be great if in the generated class there was a list of all the routes so that I can just say for example `Router.routes[index]`. I know that I could just maintain a list of all the routes myself but it would be cumbersome to maintain it over time and if I, say, add new routes and forget to add it to said list, my code would break. It would also avoid me having to create a function to get a route from the index. The list should be in the order that they are defined in the class.

**Comment by Milad-Akarie** [comment]
Hey @Reprevise 
I might add it as an optional config in the next build.

**Comment by Reprevise** [comment]
That would be great, thank you! It would make my life much easier with that.

**Comment by Milad-Akarie** [comment]
added in v0.2.2 
@AutoRouter(generateRouteList: true)
Thanks for your time.
