### ISSUE TITLE
Sharing Blocs Across Different Routes

### ISSUE THREAD

**Issue by ngoctranfire** [Milad-Akarie/auto_route_library#130]
Hey there, I wanted to try and implement the following: I have Route A and Route B. Both of them use Bloc C. With wrappedRoutes, I can just instantiate and pass in BLoC C. However, I want to make sure they share and use the same BloC. Is that possible?

Any help of trying to do this would be appreciated! This is possible when not using the generator, but since ExtendedNavigator fills in the onGenerateRoute() for us, I'm. not sure if this is possible.

As an example, In the link below, there is a specific instance where we would want something like this, as the bloc library actually has a specific pattern for this. AutoRouter, as it currently sits can't do this though as far as I know. Anyone know for sure?

https://bloclibrary.dev/#/recipesflutterblocaccess?id=app-router

**Comment by JErazo7** [comment]
I have the same problem, i don´t know how to pass the bloc state to another route using  auto_route.

**Comment by Limbou** [comment]
You can try using nested navigator and wrap it with BlocProvider

**Comment by Milad-Akarie** [comment]
@ngoctranfire isn't this the same as providing a bloc above your MaterialApp?

**Comment by NamanShergill** [comment]
Did you find any way to do this? I would like to know how to pass the bloc while pushing a route too

**Comment by Limbou** [comment]
@NamanShergill If you want to use the same bloc for multiple pages You might want to use a nested navigator and wrap it with BlocProvider. Example:

`@override
  Widget build(BuildContext context) {
    return BlocProvider<SomeBloc>(
      create: (_) => SomeBloc(),
      child: ExtendedNavigator<MainRouter>(
        key: _navigatorKey,
        router: MainRouter(),
      ),
    );
  }`

**Comment by NamanShergill** [comment]
> @NamanShergill If you want to use the same bloc for multiple pages You might want to use a nested navigator and wrap it with BlocProvider. Example:
> 
> ```@override
>   Widget build(BuildContext context) {
>     return BlocProvider<SomeBloc>(
>       create: (_) => SomeBloc(),
>       child: ExtendedNavigator<MainRouter>(
>         router: MainRouter(),
>       ),
>     );
>   }

Thank you, I will use this!
