### ISSUE TITLE
how to persist navigation state?

### ISSUE THREAD

**Issue by fnicastri** [Milad-Akarie/auto_route_library#1300]
Hi @Milad-Akarie ,
thanks for this library.

I'm facing a problem trying to implement state restoration after the app have been killed by the os.
This most happens on android during some activities like picking a picture from library or capturing a picture.
After this kind of events the app have to return to the last route to continue seamlessly.

However I cannot find a way to do it with AutoRoute nor hints in the docs.

Previously I was doing this with `Navigator 1.0 APIs`, `RestorationMixin` and `restorablePush`.

How I can do the same using AutoRoute? Right now I'm using `AutoRouterDelegate.declarative`.

Thanks,
Francesco

**Comment by uncledoc** [comment]
yes, in addition, auto_route restore last navigated screen and forget the history of navigated screens

**Comment by fnicastri** [comment]
never mind, I've changed back to go_router 6,
thanks anyway

**Comment by uncledoc** [comment]
Yes, i did the same ((:

**Comment by fnicastri** [comment]
It's a pity, I think this library have a great potential but there is not enough documentation and, at least this is my feeling, not enough comunication.

**Comment by xVemu** [comment]
Any news on this?

**Comment by AndyDavidJoyce** [comment]
Any update on this?
