### ISSUE TITLE
AutoRouteAware does not fire events after hot reload

### ISSUE THREAD

**Issue by kmrosiek** [Milad-Akarie/auto_route_library#1313]
Hi, thank you Milad for great package.
I have a trouble with AutoRouteAware after hot reload. 

I initialise `AutoRouteObserver`:
```
return Background(
      child: MaterialApp.router(
        routerDelegate: AutoRouterDelegate(
          _appRouter,
          navigatorObservers: () => [AutoRouteObserver()]),
        //....
```
I am using `AutoTabsRouter.pageView`:
``` @override
  Widget build(BuildContext context) {
    return ScreenWrapper(
      child: AutoTabsRouter.pageView(
      // ...
```
wrapped inside `ScreenWrapper` that detects pages changes:
```
class _ScreenWrapperState extends State<ScreenWrapper>
    with AutoRouteAware, TickerProviderStateMixin {
   AutoRouteObserver? _observer;
   //...
```
Everything works just fine, I get notified about all events `pop`, `popNext`, `push`, `pushNext`.
...Until is do hot reload.
During hot reload ScreenWrapper build method is called. After Hot Reload no events `pop`, `popNext`, `push`, `pushNext` are called. 

I thought it might be an issue inside `AutoRouteAware`. Any tips on that?

**Comment by kmrosiek** [comment]
I have create a [sample code](https://github.com/kmrosiek/auto_route_aware_sample)
In order to test:
1. Run app (I tested it on iOS)
2. Navigate to details screen
3. Notice in log you can see: pushed next, popped next.
4. Go back to main screen
5. Press hot reload
6. Navigate to details screen
7. You should not be able to see pushed next, popped next right now.

**Comment by kmrosiek** [comment]
In the MaterialApp I had:
```
MaterialApp.router(
      routerDelegate: AutoRouterDelegate(
        _appRouter,
        navigatorObservers: () => [AutoRouteObserver()],
      ),
```
`AutoRouteObserver` defined directly inside `navigatorObservers`.
Defining it outside:
```
final autoRouteObserver = AutoRouteObserver();
```
and passing it to `navigatorObservers` solves the issue.
```
navigatorObservers: () => [autoRouteObserver],
```

Maybe it's worth it to change it in the documentation,, because documentation presents example with direct `AutoRouteObserver()` call inside `navigatorObservers` list which fails after hot reload.

**Comment by ma-pe** [comment]
I just went into the same problem. I'll create a merge request for the docs if I find some time :)
