### ISSUE TITLE
[BUG] AutoTabsRouter "homeIndex" parameter is not working

### ISSUE THREAD

**Issue by WanderingWizard-WW** [Milad-Akarie/auto_route_library#1314]
If I set ***homeIndex***, it is still ignored and take first element of the list of routes

```
@override
  Widget build(BuildContext context) {
    return AutoTabsRouter(
      routes: const [
        AboutYouLoaderRoute(),
        FillFullNameRoute(),
        FillGenderAndBirthdayRoute(),
        FillHeightAndWeightRoute(),
        FillMaxHeartRateRoute(),
        FillRestingHeartRateRoute(),
        FillExerciseDataRoute(),
        AboutYouSummaryRoute(),
      ],
      homeIndex: 3,
      builder: (context, child, animation) {
        return BlocListener<FillAboutYouProgressCubit, FillAboutYouProgressState>(
          listener: (context, state) {
            AutoTabsRouter.of(context).setActiveIndex(state.progressStage ?? 0);
          },
          child: Scaffold(body: child),
        );
      },
    );
  }
```

**Comment by 0wzZZzz6** [comment]
I notice it too.

**Comment by 0wzZZzz6** [comment]
> If I set _**homeIndex**_, it is still ignored and take first element of the list of routes
> 
> ```
> @override
>   Widget build(BuildContext context) {
>     return AutoTabsRouter(
>       routes: const [
>         AboutYouLoaderRoute(),
>         FillFullNameRoute(),
>         FillGenderAndBirthdayRoute(),
>         FillHeightAndWeightRoute(),
>         FillMaxHeartRateRoute(),
>         FillRestingHeartRateRoute(),
>         FillExerciseDataRoute(),
>         AboutYouSummaryRoute(),
>       ],
>       homeIndex: 3,
>       builder: (context, child, animation) {
>         return BlocListener<FillAboutYouProgressCubit, FillAboutYouProgressState>(
>           listener: (context, state) {
>             AutoTabsRouter.of(context).setActiveIndex(state.progressStage ?? 0);
>           },
>           child: Scaffold(body: child),
>         );
>       },
>     );
>   }
> ```

https://github.com/Milad-Akarie/auto_route_library/issues/1024#issuecomment-1101334244

**Comment by Milad-Akarie** [comment]
@WanderingWizard-WW @0wzZZzz6 `homeIndex` doesn't mean `initial index`, homeIndex is used to pop to homeTab before popping the host route of TabsRouter. 
you need to treat your tabsRoute as routable destinations, if I provide a way to simply pass an initialIndex then deep-linking won't work properly, so this's how you do it.
setting initial route statically => AutoRoute(page: TabPage, initial: true);
if you need to set initial route dynamically you can do it like this
if your tabsHostRoute is an initial route
`router.delegate(initialRoutes:[TabsHostRoute(children:[TargetInitailRoute()])])`
if you're to navigate to the tabsHostRoute
`context.pushRoute(TabsHostRotue(children: [TargetInitailRoute()] ))`
