### ISSUE TITLE
Why is 'dart:ui' imported in router.gr.dart file

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/auto_route_library#132]
Why is the 'dart:ui' package imported in router.gr.dart file?

It's unused and the analyzer keeps throwing error.

**Comment by ganeshrvel** [comment]
I found a similar issue: https://github.com/flutter/flutter/issues/14243#issuecomment-602063460

**Comment by Milad-Akarie** [comment]
hmm That's weird. how do I reproduce this?

**Comment by theweiweiway** [comment]
Closing issue due to:
- stale issue
