### ISSUE TITLE
How to configure go back button in Browser for Flutter Web App

### ISSUE THREAD

**Issue by ugurberkecan** [Milad-Akarie/auto_route_library#1331]
Hi i want to block back button in some cases like missing parts of the form.
I found a solution with WillPopScope but It doesn't work with back button and I thought that it is related with auto_route_library so do you any suggestion about this ?

**Comment by digiborimusik** [comment]
Same problem, WillPopScope doesnt work. I had nested declarative router inside screen and i need to handle browser back button to make changes inside that screen or block back button based on state. 
Please help us.

**Comment by abigotado** [comment]
Is there any solution?
