### ISSUE TITLE
White screen for few seconds after native splash screen

### ISSUE THREAD

**Issue by DevanshMathur** [Milad-Akarie/auto_route_library#1332]
I am getting a white screen between the native splash screen and the first page. I tried to debug it and found that it is due to app localization
I have provided support for two languages. when I run my application I am facing a white screen for a few seconds and after that my first page loads.

 @override
  Widget build(BuildContext context) {
    var appRoute = AppRouter();
    return MaterialApp.router(
      title: 'Flutter Demo',
      routeInformationProvider: appRoute.routeInfoProvider(),
      routeInformationParser: appRoute.defaultRouteParser(),
      routerDelegate: appRoute.delegate(),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      locale: Locale('en'),
      localizationsDelegates:  [
        // A class which loads the translations
        AppLocalizationDelegate(),
        // Built-in localization of basic text for Material widgets
        GlobalMaterialLocalizations.delegate,
        // Built-in localization for text direction LTR/RTL
        GlobalWidgetsLocalizations.delegate,
        // Built-in localization of basic text for Cupertino widgets
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizationDelegate.supportedLocales,
    );
  }

**Comment by horlann** [comment]
https://github.com/Milad-Akarie/auto_route_library/issues/1034


I solve in that way:
1)Line 24 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/61031890/213466478-5b3dfec5-a740-48f2-859e-2659ec7641aa.png">
2)First page which will open 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/61031890/213466757-5862702a-e456-4b6d-bfe4-977cfe76a533.png">
https://pub.dev/packages/flutter_native_splash
