### ISSUE TITLE
incomptabile with flutter 3.7.0

### ISSUE THREAD

**Issue by nokia6290** [Milad-Akarie/auto_route_library#1339]
Title says it all.

The plugin is not working with 3.7.0 flutter
receiving the following error:
<img width="929" alt="Screen Shot 2023-01-29 at 7 09 18 pm" src="https://user-images.githubusercontent.com/13733620/215313709-e99cb549-3072-440f-9870-c2e823330f1d.png">

Follow all the tutorial - and its failing at initial step.

I have used other router builders, but this one seems to be bugger.

**Comment by getBoolean** [comment]
just checking, but HomeScreen is a widget right?

**Comment by redarflap** [comment]
No issues for me using Flutter 3.7.0

Also not sure what I'm looking at in your screenshot.
