### ISSUE TITLE
Set<int> type for returnType parameter in @AdaptiveRoute

### ISSUE THREAD

**Issue by knyghtryda** [Milad-Akarie/auto_route_library#134]
Currently I am using the extension methods for most of my routes, but I found that one of my routes with a `Set<int>` return type I had to use `pushNamed<Set<int>>(...)` as I cannot specify a `Set<int>` type in `@AdaptiveRoute(returnType: ...)`.  Is there a way to do this so that 1) I can use the extension method and 2) that I get a return type of `Set<int>` instead of `dynamic` or `Set<dynamic>`?

**Comment by Milad-Akarie** [comment]
hey @knyghtryda, ya that was one of the limitations I faced in the old setup..I've been working on a completely new setup that will fix this along other things. so stay tuned

**Comment by essarn** [comment]
When will this new version be released?

**Comment by Milad-Akarie** [comment]
@knyghtryda @essarn the new version is finally out
auto_route: 0.6.0
auto_route_generator: 0.6.0
This's how you can declare a generic return type using the new approach
`AdaptiveRoute<Set<int>>(page: YOURPAGE)`
please refer to the[ Migration guide]( https://github.com/Milad-Akarie/auto_route_library#migration-guide) if you get stuck

**Comment by essarn** [comment]
@Milad-Akarie It's working great, thanks!
