### ISSUE TITLE
`AutoTabsRouter` doesn't pass route arguments to `RouteData`

### ISSUE THREAD

**Issue by Zekfad** [Milad-Akarie/auto_route_library#1341]
Similar to #1226, I use `AutoTabsRouter.builder` with routes that have required custom arguments.
Generated code for `pagesMap` looks like this:
```dart
    GenreScreenTabNewRoute.name: (routeData) {
      final args = routeData.argsAs<GenreScreenTabNewRouteArgs>(); // (*1)
      return MaterialPageX<dynamic>(
        routeData: routeData,
        child: GenreScreenTab(
          genreId: args.genreId,
          sort: args.sort,
          key: args.key,
        ),
      );
    },
```
*1 - As you can see, there's no or else (because my route is designed to take arguments manually, rather than from path or query).
I construct my route and pass it to `AutoTabsRouter.builder` routes list like this:
```dart
GenreScreenTabNewRoute(
  genreId: genreId,
  key: tabKeys[0],
  sort: BooksSort.recent,
)
```
Generated code for route looks like this:
```dart
class GenreScreenTabNewRoute extends PageRouteInfo<GenreScreenTabNewRouteArgs> {
  GenreScreenTabNewRoute({
    required int genreId,
    required BooksSort sort,
    Key? key,
  }) : super(
          GenreScreenTabNewRoute.name,
          path: 'new',
          args: GenreScreenTabNewRouteArgs( // (*2)
            genreId: genreId,
            sort: sort,
            key: key,
          ),
        );

  static const String name = 'GenreScreenTabNewRoute';
}
```
*2 - as you can see, there **is** generated args.
But I still getting following error:
```
GenreScreenTabNewRouteArgs can not be null because it has a required parameter
package:kvh/app_router/app_router.gr.dart:83:29 <fn> (1 frame)
```
That's a blocking issue for our development right now.
Flutter version:
```
Flutter 3.7.0-29.0.pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1b2edb8aaf (2 hours ago) • 2023-01-29 05:49:38 -0500
Engine • revision dd3e975f31
Tools • Dart 3.0.0 (build 3.0.0-179.0.dev) • DevTools 2.20.1
```

**Comment by Zekfad** [comment]
Still an issue in 6.0.0-rc2.

**Comment by Zekfad** [comment]
@Milad-Akarie, I was able to nail down the issue:

https://github.com/Milad-Akarie/auto_route_library/blob/b0de3a4547e38558efa43987174e6d89dfab913a/auto_route/lib/src/router/controller/routing_controller.dart#L471-L480

Here, using preMatchedRoute effectively drops route args.

**Comment by wardy484** [comment]
@Zekfad doesn't seem like this is getting much attention. Did you manage to resolve this at all?

**Comment by Zekfad** [comment]
@wardy484 not really, I wasn't digging this in depth, because snippet above is not the only issue, even fixing that problem is still remains.
Also I found out that there are some issues in following scenario:
If tabsrounter is inner widget, it's arguments are entirely ignored, and if you use replace instead of push, inner pages wont receive new `@pathParam`, in fact they will be rebuild with the same config.

**Comment by LosDanieloss** [comment]
@Zekfad any luck? I'm pretty sure I just encounter same issue as you did. I'm still on v5, but given what your comment above upgrading to v6 changes nothing?

**Comment by shtreb** [comment]
any ideas? The same problem in my project
