### ISSUE TITLE
Route names generator

### ISSUE THREAD

**Issue by subzero911** [Milad-Akarie/auto_route_library#1349]
## Use case

AutoRoutes hierarchy with numerous child routes may lead to ugly constant variables names, like `Routes.loginAuthRegFinished`.
Currently we use strings for paths in favor of constants, because `router.navigate('/login/auth/reg-finished')` is much easier to read than `router.navigate(Routes.loginAuthRegFinished)`. But it leads to the common strings problem (typos, impossible to change path in many places at once)

## Proposal

Create an AutoRoute hierarchy parser which turns AutoRoutes tree into class tree, so we can use pretty route names like
`r.login.auth.regFinished`

Idea is taken from https://pub.dev/packages/slang they analyze json / yaml translation tree too and generate variables.

**Comment by ariefwijaya** [comment]
Please read the documentation.
just use your `RouterClass.path`.
