### ISSUE TITLE
[Question] Nested Navigation (AutoRoute in a LiveView) causes 'constraints.biggest.isFinite': is not true

### ISSUE THREAD

**Issue by sjoulbak** [Milad-Akarie/auto_route_library#1359]
Hi again @Milad-Akarie! 👋 

We've created a parent view with an animated header between child transitioning and a `AutoRouter()` for its nested child views. We want this parent view to be scrollable, so we used `ListView`. But now we cannot get it to work due to the error:  `"'constraints.biggest.isFinite': is not true".`

Here is the code snippet that I am using in the parent view:

```dart
return Scaffold(
  body: ListView(
    children: [
      Container(
        width: 100,
        height: 200,
        color: Colors.red,
      ),
      AutoRouter(),
    ],
  ),
);
```

Here is the code snippet that I am using in the child views:

```dart
return Container(
  width: MediaQuery.of(context).size.width,
  height: MediaQuery.of(context).size.height,
  color: Colors.green,
);
```

I would appreciate any guidance on how to properly use AutoRouter with a flexible layout, or if there is a different approach I should take to achieve the desired layout.

**Comment by JaosnHsieh** [comment]
same here.

**Comment by veronar** [comment]
Hi @Milad-Akarie 👋🏽 
Could we please get some info on this issue?
