### ISSUE TITLE
Setting active tab index manually

### ISSUE THREAD

**Issue by goldenmoon67** [Milad-Akarie/auto_route_library#1360]
Let's say I have 2 tabs (HomeScreen and FavoriteScreen). They are children of the Dashboard screen. I can switch on those tabs easily. And Also I have one more screen which is a child of homescreen. Now, I want to call the dashboard screen aga, but it should show the favourite screen, en not the homescreen.
![Screenshot_1676588633](https://user-images.githubusercontent.com/74269979/219508921-42609b3c-8476-4884-8d88-d934dc8f09d1.png)
![Screenshot_1676589156](https://user-images.githubusercontent.com/74269979/219509014-19fda5f6-7b93-4226-ac8a-6fc12361c2f0.png)

**Comment by Milad-Akarie** [comment]
@goldenmoon67 The way to go here is to look at your tabs as routable pages not widgets. 
so you just push the parent route with the target child-route as first child. 
push(DashboardRoute(children:[FaviorteRoute()]))

**Comment by goldenmoon67** [comment]
oh okay. Thanks @Milad-Akarie
