### ISSUE TITLE
Empty Page After upgrade to 3.7.3

### ISSUE THREAD

**Issue by soulonej** [Milad-Akarie/auto_route_library#1361]
After I upgrade to 3.7.3 Flutter, 
there is a issue that Empty Page will be showed in Reload Page

if I try to refresh on the page below, it will display a empty Page,

[Problem] /posts/:uid
[Problem] /support/article/:articlePath

Look further at Browser Inspect
[Error ]Refused to execute script from 'http://0.0.0.0:12367/posts/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

```
My Router Config:
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(path: '/', page: WebNavPage, initial: true, children: [
      AutoRoute(
        path: '',
        page: GridPage,
      ),
     
      AutoRoute(path: 'posts/:uid', page: PostDetailPage),
    ]),
    AutoRoute(path: '/support/article/:articlePath', page: ArticlePage),

    RedirectRoute(path: '*', redirectTo: '/'),
  ],
)
```

**Comment by soulonej** [comment]
it worked without setUrlStrategy(PathUrlStrategy());
but this is not what I want the # in my url

Before upgrade the latest version of Flutter , all good

**Comment by soulonej** [comment]
I am thinking is it a problem with PathParams in class, the flutter didn't detect the PathParams well

**Comment by The28AWG** [comment]
I also faced a similar problem. Add $FLUTTER_BASE_HREF as the beginning of the path in the index.html file
For example:
```dart
  <link href="$FLUTTER_BASE_HREFmanifest.json" rel="manifest">
  <script src="$FLUTTER_BASE_HREFflutter.js" defer=""></script>
```
```dart
  <script>
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: '$FLUTTER_BASE_HREFmain.dart.js',
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: '$FLUTTER_BASE_HREFflutter_service_worker.js?v=',
        }
      }).then(function (engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function (appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
```
And don't forget to set up url rewrite correctly.

**Comment by soulonej** [comment]
Thank you @shemhazai  and @The28AWG 
it will work after upgrade 3.7.6 without changing the html file

it will be  closed the issue, have a nice day guys
