### ISSUE TITLE
DeferredLoadException sometimes randomly after pushing update for the app

### ISSUE THREAD

**Issue by adar2378** [Milad-Akarie/auto_route_library#1367]
Hi, thank you for the library. 

We are using `deferredLoading : true`, on web randomly after pushing updates, flutter app sometimes throws `DeferredLoadException: 'Loading main.dart.js_85.part.js failed: the code with hash 'OiVkY0kz+el7z3rp2qI3dLz0JaQ=' was not loaded. ` this exception. And app stays stuck at loading. Doesn't load route. After clearing cache it works again. Could it be related to auto_route library?

**Comment by Milad-Akarie** [comment]
@adar2378 no idea, the package barely declares the imports as deferred, then load files using load library method as mention in flutter docs.

**Comment by Raviteja11122** [comment]
same issue myside as well.

**Comment by Raviteja11122** [comment]
@adar2378 try this plugin maybe works for you https://pub.dev/packages/flutter_web_optimizer

**Comment by ranulfo** [comment]
> https://pub.dev/packages/flutter_web_optimizer

I have the same problem

**Comment by ranulfo** [comment]
> Hi, thank you for the library.
> 
> We are using `deferredLoading : true`, on web randomly after pushing updates, flutter app sometimes throws `DeferredLoadException: 'Loading main.dart.js_85.part.js failed: the code with hash 'OiVkY0kz+el7z3rp2qI3dLz0JaQ=' was not loaded. ` this exception. And app stays stuck at loading. Doesn't load route. After clearing cache it works again. Could it be related to auto_route library?

i  have the same problem
