### ISSUE TITLE
How to refresh the navigation route stack

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/auto_route_library#137]
Is it possible to refresh the whole navigation route stack programatically? 

In my app the I have few APIs which sends back personalized data when authentication token is available. So when I start my app, the api gives some public data and as soon as I login I can land back to the previous route.
But at this point I need to refresh the API data of that screen and fetch the private data as well. As I keep navigating back I wish to refresh the routes down the stack. 

Is it possible?

**Comment by Milad-Akarie** [comment]
Hey @ganeshrvel I suppose that should be done with some reactive solution like flutter bloc listener or change notifier consumer?

**Comment by ganeshrvel** [comment]
Hey @Milad-Akarie , I personally use mobx for flutter. I am wondering if it's possible to refresh the whole navigation stack or refresh the screens as I pop back to the home screen.



Right now as a work around, on logon I just use replaceRouteUntil back to the home screen and let the user start fresh.

**Comment by theweiweiway** [comment]
Closing issue due to:
- propsed solution
- stale issue
