### ISSUE TITLE
Is it possible to have other language README.md? Need Chinese. 

### ISSUE THREAD

**Issue by chyiiiiiiiiiiii** [Milad-Akarie/auto_route_library#1370]

**Comment by Milad-Akarie** [comment]
@chyiiiiiiiiiiii  sure, know any one that can help with the translation?

**Comment by chyiiiiiiiiiiii** [comment]
@Milad-Akarie Me, I am willing to do a Chinese translation.

**Comment by Milad-Akarie** [comment]
@chyiiiiiiiiiiii Alright then, make sure you translate the new readme file 
https://github.com/Milad-Akarie/auto_route_library/blob/v6.0.0_redesigned/README.md
