### ISSUE TITLE
Router issues when you mix AutoTabsRouter with other routes

### ISSUE THREAD

**Issue by mirland** [Milad-Akarie/auto_route_library#1371]
Suppose that you define a router something like that: 

```dart
 AutoRoute(
  page: SectionPage,
  initial: true,
  children: [
     AutoRoute(page: 'PagerPage1'),
     AutoRoute(page: 'PagerPage2'),
     AutoRoute(page: 'OtherExternalPage'),
  ],
),
```

Suppose that you define a`AutoTabsRouter` with 2 routes: `PagerPage1Route` and `PagerPage2Route`.
If you want to navigate from `PagerPage1` to `PagerPage2` that works. However, if I want to navigate from `PagerPage1` or `PagerPage2` to `OtherExternalPage` using `context.router.navigate(OtherExternalPageRoute)` it doesn't work and autoroute doesn't throws an error either.

I checked the code, and the RoutingController's _pages don't contain `OtherExternalPageRoute` (checked in `_navigateAll`), so the navigation is not performed.

I've also checked the AutoTabsRouter documentation and I couldn't find anything to think that my example is wrong.

BTW: I could "fix it" by adding another router, but I think the library has an issue here

thanks!

**Comment by LosDanieloss** [comment]
I'm not entirely sure but it sounds like a reason why library allows to always get parent router. 
Yet I agree that even if `OtherExternalPage` could be reached using parent router then it would be nice if `auto_route` would be cleaver enough to check for it.

**Comment by mirland** [comment]
It's not resolved, I's not a critical issue but it's not resolved

**Comment by Milad-Akarie** [comment]
Hey @mirland could you make a simple repo with repreducable example?
