### ISSUE TITLE
Has anyone tried v6 yet? 

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#1374]
Hello guys, I need some feedback on v6 before I  push it to stable channel.

**Comment by papmodern** [comment]
I came here exactly to ask how much is it takes to be ready for production usage?
I have a live app which it can't tolerate any navigation glitches. On the other side, I lost hot reload with the current stable version of your lib and it really hurts during development

**Comment by jtdLab** [comment]
@Milad-Akarie thanks for delivering v6.
In single package applications it works well but because of the new approach of registering pages v6 does not support routing across multiple packages as v5 did. But i think if v6 would support something similar to `injecable`s micro package approach it would be great.

**Comment by Milad-Akarie** [comment]
@papmodern technically the runtime code has no dramatic changes, I just added some features that were impossible using the old static approach. 

what do you mean you lost hot reload on the stable version??

**Comment by Milad-Akarie** [comment]
@jtdLab please describe your use case in more details and I'll see what I can do.

**Comment by papmodern** [comment]
> @papmodern technically the runtime code has no dramatic changes, I just added some features that were impossible using the old static approach. 
> 
> 
> 
> what do you mean you lost hot reload on the stable version??
> 
> 
> 
> 

On every reload all routes resets to initial ones. 
So if I'm developing a widget inside a deep page, I should navigate there manually or temporary I should make it default route

**Comment by jtdLab** [comment]
@Milad-Akarie checkout the repo https://github.com/jtdLab/auto_route_multi_package. It contains a minimal sample.

**Comment by itisnajim** [comment]
i have this issue, i don't know if i'm doing it right !
https://github.com/Milad-Akarie/auto_route_library/issues/1376

**Comment by papmodern** [comment]
@Milad-Akarie So an update about my issue. When I shared it with you I tried to prepare reproduction steps with your example project. And it helped me to realize the problem comes from my root widget I use as the main parent for routes. It contains a future builder and it ruined everything related to hot reload. So it's not from your amazing library.

**Comment by sososdk** [comment]
@Milad-Akarie please check #1364 #1384

**Comment by pckimlong** [comment]
How to use pathParam in v6? When I tried to use it, it not generate route for me

**Comment by Zekfad** [comment]
So far made migration, old routes works as-is, no problems except for this small:
In root routes to mark named route as inital, you have to use `"/"` instead of `""`:
```dart
  @override    
  final List<AutoRoute> routes = [
    // does't work
    RedirectRoute(path: '', redirectTo: '/playground'),
    // works
    RedirectRoute(path: '/', redirectTo: '/playground'),
 ```

**Comment by Milad-Akarie** [comment]
@pckimlong  can you share some code please? it works as expected on my end.

**Comment by Milad-Akarie** [comment]
@Zekfad ya I kinda postponed this one, one idea I had was to support factories and/or named constructors? so you would create multiple  routes for the same widget but with different names and params? 

so we would have something like this

```dart
@RoutePage(name: 'BookDetailsRoute')
class BookDetailsPage extends StatefulWidget {
  final int? id;
  final Book? book;
  
  const BookDetailsPage({@pathParam this.id = -1}) : book = null;
  
  @RoutePage(name: 'FromBookDetailsRoute')
  const BookDetailsPage.fromBook({this.book}) : id = -1;
   //...
}
```
how does that look?

**Comment by pckimlong** [comment]
> @pckimlong  can you share some code please? it works as expected on my end.

Sorry, that's my bad, I've use old version of auto_router_generator, after use .rc version It's worked now thanks

**Comment by Wilson0212tw** [comment]
#1391 
I ran into an error about swiping for pop out

**Comment by Milad-Akarie** [comment]
@Zekfad I added a check for root paths must start with '/'. 
The extend widget option doesn't sound bad neither.

**Comment by itisnajim** [comment]
@Milad-Akarie 
i start getting the error after upgrading to `^6.0.0-rc-4`:
```console
flutter: r._path /
flutter: r._path about

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building PlatformProvider(dirty, state: _PlatformProviderState#3c296):
Root-paths must start with a "/" or be a wild-card
...
#1      new RouteCollection.from                                                   route_config.dart:247
```

how can i fix this?

**Comment by radvansky-tomas** [comment]
I am not sure how to use authGuards in v6

Before I was able to pass widgetRef (from Riverpod) inside guard to have access to providers.
But now when this needs to be instance member of Router, I cant:

```
   AutoRoute(
/// THIS FAILS as ref is defined as instance member of AppRouter classs
      guards: [IsNotAnonymGuard(ref: ref)],
      
      path: '/onboarding/info',
      page: OnboardingInfoPageRoute.page,
    ),
```

**Comment by radvansky-tomas** [comment]
Found this, let me try https://github.com/Milad-Akarie/auto_route_library/issues/1398

**Comment by jonaspeter** [comment]
It took me quite a while to figure out how you set the initial route with v6 since the 'initial' parameter doesn't exist anymore in AutoRoute. 

I eventually tried to set the path of my initial route to '/' and it seems to work. Is that the correct way to do it? It would be nice if the documentation mentioned that.

**Comment by Milad-Akarie** [comment]
Hey @jonaspeter It's actually step number 5 in the migration guide.  have you seen it?
Where in the documentation you think it should be mentioned?

**Comment by jonaspeter** [comment]
Hi @Milad-Akarie, the link for the migration guide doesn't work for me, so I never got that far. I tried searching the page for "initial" but I guess I wasn't thorough enough. 

I think a good place to mention it would also be the "Add the generated route to your routes list" section of "Setup And Usage"  because new users probably need an initial route too.

**Comment by Manishmg3994** [comment]
Need help =>  issue #1407 for Routing based on Query Parameters

**Comment by Milad-Akarie** [comment]
@jonaspeter fixed the link.

**Comment by Milad-Akarie** [comment]
I believe it's time to close this thread.

**Comment by petro-i** [comment]
Hot reload is broken. 
`SOMECLASSNAMEArgs can not be null because it has a required parameter`

**Comment by anandsubbu007** [comment]
instead of throwing this error 
can it be remove or add '/' ?

```
  factory RouteCollection.from(List<AutoRoute> routes, {bool root = false}) {
    final routesMap = <String, AutoRoute>{};
    for (var r in routes) {
      if (r._path != null) {
        throwIf(
          !root && r.path.startsWith('/'),
          'Sub-paths can not start with a "/"',
        );
        throwIf(
          root && !r.path.startsWith(RegExp('[/]|[*]')),
          'Root-paths must start with a "/" or be a wild-card',
        );
        routesMap[r.name] = r;
      } else {
        routesMap[r.name] = r.changePath(
          _generateRoutePath(r.name, root),
        );
      }
    }

    return RouteCollection(routesMap);
  }
```

**Comment by Milad-Akarie** [comment]
@anandsubbu007 I don't understand your usecase, aren't you the one making assigning the paths?

**Comment by anandsubbu007** [comment]
yes, i'm assigning path. 
for one particular page. 
i use it as an individual page and also inside children based on device platform.

so, when i use '/' it supports as path but not support sub-paths  & vice-versa

**Comment by Milad-Akarie** [comment]
is there a reason why you can't do something declrative as this? 
```dart
 [
   AutoRoute(path: '/', childern [if(!android) AutoRoute(path: 'sub')],)
   if(android) AutoRoute(path: '/root', ...)
 ]
```

**Comment by anandsubbu007** [comment]
yes, can do that.
if i want to use many route than i need to manually do that.


if possible can you please add this to AutoRoute?

`String? get routepath => this._path; `

if you add this. i can rewritten the path?

when i try path it is throwing null error if i didn't define path for some route
