### ISSUE TITLE
[Help] How to prevent accessing Login page/router when use is authenticated already

### ISSUE THREAD

**Issue by adar2378** [Milad-Akarie/auto_route_library#1378]
Hi, is there any good way to prevent users from accessing login page when they are already logged in on WEB? Users can navigate back using browser back button login page/route after authenticated. I would like to prevent that, without using `AutoRouter.declrative` because if we do then we will not have deep linking

**Comment by Milad-Akarie** [comment]
@adar2378  I'm working on something related to this, I'll let you know how it turns out.

**Comment by Milad-Akarie** [comment]
@adar2378 
 set keep history to false in your login page
`AutoRoute(page: LoginRoute.page, keepHistory: false);`
if you're guarding the home page you should propaply user replace(LoginRoute) instead of push to have a clean stack

**Comment by kleyos** [comment]
> @adar2378 set keep history to false in your login page `AutoRoute(page: LoginRoute.page, keepHistory: false);` if you're guarding the home page you should propaply user replace(LoginRoute) instead of push to have a clean stack

What do you mean properly replace?
