### ISSUE TITLE
Proposal for multi package support

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/auto_route_library#1380]
@Milad-Akarie  Some thoughts on multi package support for v6:

This is heavily inspired by `injectable`s  micro package/external package approach.

```dart
void main() {
  configureRouter(); // use the generated setup function here 
  runApp(App());
}

// assuing this is the root widget of your App               
class App extends StatelessWidget {                
  @override          
  Widget build(BuildContext context){          
    return MaterialApp.router(
      // use the global instance          
      routerConfig: appRouter.config(),       
    );          
  }          
}          
```

Package `router_package`:
```dart
// app_router.dart

final appRouter = AppRouter(); // global instance

@AutoRouterConfig(
  // includeMicroPackages: false // flag to wheter include sub packages
)    
class AppRouter extends $AppRouter {    
  
  @override    
  final List<AutoRoute> routes = [    
   // routes go here   
  ];
 } 
```

```dart
// app_router.gr.dart

class NotInitializedError implements Exception {}

class AlreadyInitializedError implements Exception {}

abstract class _$AppRouter extends RootStackRouter {
  _$AppRouter([GlobalKey<NavigatorState>? navigatorKey]) : super(navigatorKey);

  Map<String, PageFactory>? _pagesMap;

  @override
  Map<String, PageFactory> get pagesMap {
    if (_pagesMap != null) {
      return _pagesMap!;
    }

    throw NotInitializedError();
  }

  void initialize(Map<String, PageFactory> pagesMap) {
    if (_pagesMap != null) {
      throw AlreadyInitializedError();
    }

    _pagesMap = pagesMap;
  }
}

/// generated route for

/// [MyPage]
class MyPageRoute extends PageRouteInfo<void> {
  const MyPageRoute({List<PageRouteInfo>? children})
      : super(
          MyPageRoute.name,
          initialChildren: children,
        );

  static const String name = 'MyPageRoute';

  static const PageInfo<void> page = PageInfo<void>(name);
}
```

Package `configure_router_package`

```dart
// routing.dart

@AutoRouteInit(
  externalPackageModules: [
    SubPackageModule,
  ],
)
void configureRouter() => appRouter.initialize(pagesMap);
```

```dart
// routing.config.dart
final Map<String, PageFactory> pagesMap = {
  ...SubPackageModule().pagesMap,
};
```

Package `sub_package`:

```dart
// my_page.dart

@RoutePage()
class MyPage extends StatelessWidget { ... }
```

```dart
// routing.dart

@AutoRouteInit.microPackage()
initMicroPackage() {}
```

```dart
// routing.module.dart

class SubPackageModule extends MicroPackageModule {
  @override
  final Map<String, PageFactory> pagesMap {
    MyPageRoute.name: (routeData) {
      return AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const MyPage(),
      );
    },
  }
}
```

Why does this approach split up the routing setup into two packages?

This is because in a multi package routing scenario sub_packages want to have access to the generated `PageRouteInfo` Objects to perform navigation like `router.push()` etc. When not splitting up the setup into two packages and using single package every sub_package will have have to depend on that package to access the `PackageRouteInfo` objects mentioned earlier but this single package would have a dependency on every sub_package that is registered as a MicroPackageModule. This will lead to every sub_package that just wants the `PageRouteInfo`  Objects for navigation having a transitiv dependency on this registered sub_packages. To solve this an approach similar to the one in `injectable` is used. The generated router acts the same way as the getIt instance does in `injectable`. It will be created and stored in a global variable and before running the app it will be configured with the `pagesMap`. Doing it that way allows to solve the transitiv dependency issue.

**Comment by Milad-Akarie** [comment]
Hey @jtdLab I didn't think I understand your point but maybe easier to tell me what's wrong with the following setup that you can do right now

```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {
 // a regular router generated inside of the micro-package
 final _microRouter = MicroRouter();

  @override
  Map<String, PageFactory> get pagesMap => {
    ..._microRouter.pagesMap,
    ...super.pagesMap,
  };

  @override
   List<AutoRoute> get routes => [
    AutoRoute(page: HomeRoute.page, path: '/'),
    // ... other root package routes
    ..._microRouter.routes, 
  ];
}

```
of course if this works we will need a cleaner version but the logic will be the same

**Comment by jtdLab** [comment]
@Milad-Akarie works like a charm. My issue went away with your setup.
Given Package A and Package B with their respective micro router to navigate from a Route in A to one in B. A needs a dependency on B but i think that is fine.

**Comment by fabiocalliari** [comment]
@jtdLab can't you create an intermediate shared package (eg., navigation) containing abstract classes to navigate between the different mfes? So, mfes should depend only on these abstractions to navigate. I can post some code snippet if required!

**Comment by Milad-Akarie** [comment]
@fabiocalliari please do post some snippets and elaborate more

**Comment by fabiocalliari** [comment]
Actually I think it's more a question of handling it on project architecture itself rather than on auto_route library. Every micro-app package would have its corresponding navigation abstraction in a shared package. For example,

```dart
abstract class AuthNavigator {
  void navigateToLogin(BuildContext context);
}
```

Then, in our micro-app-auth we'll have the concrete implementation:

```dart
class AuthNavigatorImpl implements AuthNavigator {
  void navigateToLogin(BuildContext context) {
    return context.router.push(const LoginRoute());
  }
}
```

So we can inject this abstraction using a Service Locator like GetIt. Any packet that needs to navigate to any authentication route simply consumes this abstraction. We can go even further by creating a mixin in our shared navigation package:

```dart
mixin AppNavigator {
  void navigateTo(AutoRoute route) {
    return context.router.push(route);
  }
}
```

Then we can simply our AuthNavigatorImpl by implementing this mixin:

```dart
class AuthNavigatorImpl implements AuthNavigator with AppNavigator {
  void navigateToLogin(BuildContext context) {
    return navigateTo(const LoginRoute());
  }
}
```
I don't know if that's exactly what @jtdLab  needs, but I imagine that this way it is at least possible to remove the dependency between micro-apps.

**Comment by jtdLab** [comment]
@fabiocalliari great approach to get rid of the inter micro package dependencies. In general i think you are right about handling this on an architecture level and not inside auto route.

**Comment by Milad-Akarie** [comment]
@fabiocalliari I agree with @jtdLab this looks more like an App-arch scope, but let me know if I can add anything that can help ease things out.
