### ISSUE TITLE
Another "Fork" Into the Stacked Package

### ISSUE THREAD

**Issue by FilledStacks** [Milad-Akarie/auto_route_library#1381]
Hi, 

Last time I reached out to ask the same thing 😬 I know it's under the MIT license but I still feel the need to ask. 

I would like to "fork" AutoRoute where it is now with a few modifications and use it in my Stacked Package. The last version of AutoRoute that I forked was 0.6.9 🤯 but now that we're adding web support there's a few things I'd like to get from the new AutoRoute package. 

I have some additional functionality that I've added for type-safe navigation to our version which is why I would rather take a snapshot of the current state and add all of my previous custom work instead. 

I don't need any help, but I want to keep this here for visibility and to get your acknowledgment. You can close the issue if you're happy with the request. 

If you have any questions or requests please let me know. This is a great package and I don't want to take your work for granted. 

Dane

**Comment by Milad-Akarie** [comment]
Hey Dane, I don't mind at all, Thanks letting me know.
