### ISSUE TITLE
`tabsRouter.setActiveIndex` calling build multiple times.

### ISSUE THREAD

**Issue by lucasshiva** [Milad-Akarie/auto_route_library#1386]
I decided to try out `auto_route` because it maintains the pages' state when switching pages in the navigation bar, something that `GoRouter` currently lacks. At first, I was pleasantly surprised with the built-in API to control the `NavigationBar`. I followed the official examples and was able to set up the navigation very quickly. However, I also quickly noticed how I couldn't immediately switch destinations. The icon just couldn't register my click in time (I was trying to instantly switch, to get a feel of the transition animation), yet it worked fine a second later. Upon further investigation—in other words, adding a print statement inside the `bottomNavigationBuilder`—it seems like switching destinations calls the widget's `build` method almost twenty times. This is my code:

```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

import '../router/router.gr.dart';

class NavigationView extends StatelessWidget {
  const NavigationView({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      routes: const [
        ToplistRoute(),
        LatestRoute(),
        RandomRoute(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        print("Rebuilding navigation bar..");
        return NavigationBar(
          selectedIndex: tabsRouter.activeIndex,
          onDestinationSelected: (index) => tabsRouter.setActiveIndex(index),
          destinations: const [
            NavigationDestination(
              icon: Icon(Icons.favorite),
              label: "Favorites",
            ),
            NavigationDestination(
              icon: Icon(Icons.timer_sharp),
              label: "Latest",
            ),
            NavigationDestination(
              icon: Icon(Icons.question_mark),
              label: "Random",
            ),
          ],
        );
      },
    );
  }
}
```
I've tested that the views are not the problem; they are all stateless widgets. Also, I switched back to `GoRouter` and it didn't rebuild the `NavigationBar` more than once, so it seems to be a problem specifically with `auto_route`. It's not a big problem, but there IS a delay until the user can click/tap on the navigation icons, as they have to wait until the `NavigationBar` is done with the rebuilds.

I also tried with v6, but to no avail.

**Comment by Milad-Akarie** [comment]
@lucasshiva  this's because the whole scaffold is built inside of an animation builder, I didn't think this would cause a problem before but I guess I can try to separate the bottom navigation and app bar builders from the body builder.

**Comment by Milad-Akarie** [comment]
@lucasshiva the latest rc version has the refactored implementation, you can try it now.
