### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by alf3rdfoo** [Milad-Akarie/auto_route_library#1389]
I not sure is it I have miss out something... or this is just not working initially... (I cant find any documentation on this part)
If I using .push, it can navigate to '.../admin/list', but if I enter URL directly on browser, it cant go to the page, it instead just showing a blank page.

Below codes are my 2 different writing ways:...

AutoRoute(path: '/admin/list')

OR

AutoRoute(path: '/admin', children: [ AutoRoute(path: 'list') ])

**Comment by metafounder** [comment]
I have the same issue, `Flutter (Channel stable, 3.7.5)`  and `auto_route: ^5.0.4` . This used to be ok in previous versions of Flutter.

**Comment by Milad-Akarie** [comment]
are you using path strategy package?

**Comment by metafounder** [comment]
yes, `url_strategy: ^0.2.0`

**Comment by alf3rdfoo** [comment]
I am using the flutter_web_plugins package for the path strategy.

**Comment by Milad-Akarie** [comment]
@metafounder @alf3rdfoo I got some  other complains about auto_route, url_strategy compatibility, I'll see what I can do.

**Comment by metafounder** [comment]
The thing is that I did not touch auto_route nor url_strategy packages, the issue only started after I upgraded my Flutter stable from `3.3.10` to `3.7.5` (dart managed by flutter). So on `3.3.10` I had absolutely no problem. 

And of course, the worst thing about it is that this breaks the hot reload. But anyway, do what you can, awesome package by the way.

**Comment by Milad-Akarie** [comment]
@metafounder since you're here, what's the easiest way to reproduce this?

**Comment by Milad-Akarie** [comment]
@metafounder @alf3rdfoo I could not reproduce this with a simply  setting path url strategy, it just works as expected.

tested with 3 levels deep-linking

![Mar-08-2023 1-36-27 PM](https://user-images.githubusercontent.com/55059449/223690794-cb66dc1d-8288-4cdd-96f1-733dc1cfd871.gif)

can any of you make a small repo with the unexpected behavior?

**Comment by metafounder** [comment]
I think I may have something: try to put an AuthGuard on it, it does not have to do anything, just print some stuff.

**Comment by metafounder** [comment]
router:

```const List<AutoRoute> sharedRoutes = [
  AutoRoute(
    initial: true,
    path: '/',
    page: MyHomePage,
  ),
];

const List<AutoRoute> carrierHomePageRoutes = [
  AutoRoute(
    path: '/carrier',
    name: 'WidgetHomeRouter',
    guards: [AuthGuard],
    page: WidgetHomeView,
    children: [
      AutoRoute(
        path: 'positions',
        name: 'CarrierPositionsRouter',
        guards: [AuthGuard],
        page: EmptyRouterPage,
        children: [
          AutoRoute(
            path: '',
            page: WidgetHomeView,
          ),
        ],
      ),
    ],
  ),
];

@CustomAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  transitionsBuilder: TransitionsBuilders.noTransition,
  durationInMilliseconds: 0,
  routes: [
    ...sharedRoutes,
    ...carrierHomePageRoutes,
  ],
)
class $AppRouter {}
```
(dont pay attention to the routes names ,they are a mess :P )

AuthGuard: 

```class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    print('auth guard');
  }
}
```

this one does not work for me. if you remove the authGuard terminate + re-run again (not rely on hot reload) it works as expected.

**Comment by Milad-Akarie** [comment]
@metafounder I can tell you from now this won't work because, you'd need to call resolver.next() for the navigation to continue?

**Comment by metafounder** [comment]
that is correct, my mistake. 

however, I think I found the issue in my case: 

index.html js script used to be this: 

``` 
window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: "main.dart.js",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
```

after I changed it to: 

```
window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
```

the problem went away. :)

**Comment by Milad-Akarie** [comment]
@metafounder  if i'm not mistaken this is a flutter generated code right? 
do you think we can do something about it?

**Comment by metafounder** [comment]
Yes, we can. 

I will leave this one here: 

```flutter create . --platforms=web``` (ref: https://docs.flutter.dev/development/platform-integration/web/initialization)

If you have some custom code in index.html , keep a copy of that and add it afterward to the newly generated file.

This issue needs to be closed. Would you be able to do that @alf3rdfoo ? Can you confirm that this was also the problem for you?

**Comment by alf3rdfoo** [comment]
```dart
AutoRoute(
  page: LoginRoute.page,
  path: '/login',
),
AutoRoute(
  page: AuthWrapperRoute.page,
  path: '/',
  children: [
    AutoRoute(
      page: DashboardRoute.page,
      path: '',
    ),
    AutoRoute(
      page: SecurityRoute.page,
      path: 'security',
    ),
    AutoRoute(
      page: AdminWrapperRoute.page,
      path: 'admin',
      children: [
        AutoRoute(
          page: AdminAddRoute.page,
          path: 'add',
        ),
        AutoRoute(
          page: AdminAddRoute.page,
          path: 'edit',
        ),
        AutoRoute(
          page: AdminAddRoute.page,
          path: 'list',
        )
      ],
    )
  ]
)
```

Hi, this is my minimal route code...
I have my route observer too...
Here I found out... if I access different URL, what I have get from the observer...
**URL: _localhost/login_**
_'New route pushed: LoginRoute'_

**URL: _localhost/security_**
_'New route pushed: AuthWrapperRoute'_
_'New route pushed: SecurityRoute'_

**URL: _localhost/admin_**
_'New route pushed: AuthWrapperRoute'_
_'New route pushed: AdminWrapperRoute'_
since I dint have a default page for accessing ***/admin***, so I think this is still normal...

But if I access on the deep inside admin route:
**URL: _localhost/admin/list_**
There is nothing to be printed on my terminal anymore... I assume this should not be a normal behavior...

**Comment by alf3rdfoo** [comment]
Hi, I found out that my case mostly related to path url strategy issue...

`main.dart`
```dart
import 'url_strategy.dart';

void main() async {
  usePathUrlStrategy();

  runApp(const MyApp());
}
```

`url_strategy.dart`
```dart
export 'url_strategy_noob.dart' if (dart.library.html) 'url_strategy_web.dart';
```

`url_strategy_noob.dart`
```dart
void usePathUrlStrategy() {
  // noob
}
```

`url_strategy_web.dart`
```dart
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void usePathUrlStrategy() {
  setUrlStrategy(PathUrlStrategy());
}
```

Above are my current url strategy code...

If I dint use any url strategy, when I access to `http://localhost:50786/#/admin/add`, it can be navigate fine...
