### ISSUE TITLE
BUG? - Error opening dialog using showDialog

### ISSUE THREAD

**Issue by wer-mathurin** [Milad-Akarie/auto_route_library#1390]
@Milad-Akarie 
The error occurred when trying to open a dialog and passing argument to the page inside the dialog.

auto_route: ^6.0.0-rc-2

Error: NoSuchMethodError: 'toJson'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49        throw_
.....
Error: Converting object to an encodable object failed: Instance of 'ProfileEntity'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49        throw_
dart-sdk/lib/convert/json.dart 793:7                                                writeObject
dart-sdk/lib/convert/json.dart 874:7                                                writeMap
dart-sdk/lib/convert/json.dart 829:21                                               writeJsonValue
dart-sdk/lib/convert/json.dart 784:9                                                writeObject
dart-sdk/lib/convert/json.dart 874:7                                                writeMap
dart-sdk/lib/convert/json.dart 829:21                                               writeJsonValue
dart-sdk/lib/convert/json.dart 784:9                                                writeObject
dart-sdk/lib/convert/json.dart 982:16                                               printOn
dart-sdk/lib/convert/json.dart 967:5                                                stringify
dart-sdk/lib/convert/json.dart 345:30                                               convert
dart-sdk/lib/convert/json.dart 231:45                                               encode
packages/flutter/src/services/message_codecs.dart 103:51                            encodeMessage
packages/flutter/src/services/message_codecs.dart 139:37                            encodeMethodCall
packages/flutter/src/services/platform_channel.dart 304:34                          _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter/src/services/platform_channel.dart 302:30                          [_invokeMethod]
packages/flutter/src/services/platform_channel.dart 586:3                           [_invokeMethod]
packages/flutter/src/services/platform_channel.dart 585:18                          invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter/src/services/platform_channel.dart 584:29                          invokeMethod
packages/flutter/src/services/system_navigator.dart 92:38                           routeInformationUpdated
packages/auto_route/src/router/provider/auto_route_information_provider.dart 46:21  routerReportsNewRouteInformation
packages/flutter/src/widgets/router.dart 606:14                                     [_reportRouteInformation]

The problem is because the object pass in parameter does not have a toJson method....
This is thrown when calling this method inside auto_route_information_provider.dart
```
SystemNavigator.routeInformationUpdated(
      location: routeInformation.location!,
      state: routeInformation.state,
      replace: replace,
    );
```

I'm not sure if this is a Flutter bug or cause by the library.  Does anyone experience the same things?

It does **not** prevent the dialog to open !

**Comment by Milad-Akarie** [comment]
Hey @wer-mathurin by 'page inside the dialog' do you mean an AutoRoutePage?
By reading the stack I think the problem is with whatever inside routeInformation.state, it needs to be a codable object, ( primitive or an object with .toJson method)
