### ISSUE TITLE
swipe back  will leave app not just go back to previous page in v6

### ISSUE THREAD

**Issue by Wilson0212tw** [Milad-Akarie/auto_route_library#1391]
as titile ,
I tried v6 on android,
just pushed new page ,then swiping out will let app go to background
but  router‘s pop function works as normal
 what I used for pushing page as below

` getIt<AppRouter>().push<int>(BRoute()).then((res) {print(res)})`

**Comment by Milad-Akarie** [comment]
@Wilson0212tw share router setup please

**Comment by Wilson0212tw** [comment]
the route as below Thanks.

```dart
@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends $AppRouter {
  @override
  final List<AutoRoute> routes = [
    AutoRoute(
      path: '/',
      page: ARoute.page,
    ),
    AutoRoute(
      path: '/B',
      page: BRoute.page,
    ),
  ];
}
```

**Comment by Milad-Akarie** [comment]
Hey @Wilson0212tw  I just tried this out, it seems to be working fine. just to be sure you're talking about IOS back-gesture right?

**Comment by fabcall** [comment]
@Milad-Akarie , I could repro this issue using Android's back button.

```dart
@AutoRouterConfig(replaceInRouteName: 'Screen,Route')
class AppRouter extends $AppRouter {
  @override
  Map<String, PageFactory> get pagesMap => {
        ...super.pagesMap,
      };

  @override
  List<AutoRoute> get routes => [
        /// routes go here
        AutoRoute(page: HomeRoute.page, path: '/'),
        AutoRoute(
          page: DashboardRoute.page,
          path: '/dashboard',
          children: [
            AutoRoute(page: EstablishmentsRoute.page),
            AutoRoute(page: UserRoute.page),
            AutoRoute(page: PostsRoute.page),
            AutoRoute(page: SettingsRoute.page),
          ],
        ),
        CustomRoute(
          page: CheckoutRoute.page,
          path: '/checkout',
          customRouteBuilder: modalSheetBuilder,
        )
      ];
}
```

Pushing from HomeRoute to DashboardRoute would correctly render BackButton on AppBar (which also works consistently). However, native's back simply closes the app.

**Comment by Wilson0212tw** [comment]
@Milad-Akarie ,
on **Android** 
 I tested gesture navigation (swipe from the left  edge  to right)

**Comment by Milad-Akarie** [comment]
@Wilson0212tw  what android version are you testing on?

**Comment by Wilson0212tw** [comment]
android version :13
flutter  version  : current master and stable branch <both  of them  have  no difference >
I also tested v5 on all same circumstance, but  v5 works well.

**Comment by Milad-Akarie** [comment]
@Wilson0212tw never mind, I got it, before Material.router created a `BackButtonDispatcher` by default but now that we pass our own router config I must add it myself, will push fix in minutes.

**Comment by Wilson0212tw** [comment]
ok, I got it, thank you
