### ISSUE TITLE
Nested AutoRouter navigationObserver doesn't trigger didPop

### ISSUE THREAD

**Issue by cerealexx** [Milad-Akarie/auto_route_library#1395]
I have two routers. Both parent and child routers have their own `navigationObservers.`

Navigating between nested routes triggers both observers `didPush` event.
But when tapping on hardware Android back button, only the parent `didPop` event is triggered so I can't access the current nested route from it.

How can I make a `didPop` event trigger in a nested router `navigationObserver`? Or alternatively get the current nested route from the `didPop` event of the parent router?

**Comment by Milad-Akarie** [comment]
@cerealexx I double checked this and it seems to work fine on my end. 
Please share your code. Are you using a TabsRouter?

**Comment by cerealexx** [comment]
> Are you using a TabsRouter?

Nope, I'm using a regular nested router.

main router
```
final _appRouter = AppRouter(...);

MaterialApp.router(
          routerDelegate: AutoRouterDelegate(
            _appRouter,
            navigatorObservers: () => [
               MainRouteObserver()
            ],
          ),
          routeInformationParser: _appRouter.defaultRouteParser(),
          builder: (_, child) => ...
```
nested page router
```
AutoRouter(
     navigationObservers: () => [NestedRouteObserver()]
     builder: (_, child) {
      return ...
    });
```
And related router config:
```
@CustomAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    CustomRoute(
      page: DashboardPage,
      path: '/dashboard',
      children: [
        RedirectRoute(path: '', redirectTo: 'today'),
        CustomRoute(
          path: 'today',
          page: TodayPage,
          transitionsBuilder: TransitionsBuilders.noTransition,
        ),
       ...
      ]
     ...
    )
```
MainRouteObserver triggers didPush and didPop when navigating to and from a nested route.
NestedRouteObserver only triggers didPush, never didPop.

**Comment by mariomka** [comment]
Is there any update on this?
