### ISSUE TITLE
Why does the `AutoTabsRouter` require `routes`?

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/auto_route_library#1396]
Why does the `AutoTabsRouter` require `routes`? Is it not possible to infer them from the router like `AutoRouter` seems to do it? 

```dart
AutoTabsRouter.pageView(
    routes: [
        TabPageARoute(),
        TabPageBRoute(),
    ],
); 

or

AutoTabsRouter.tabBar(
    routes: [
        TabPageARoute(),
        TabPageBRoute(),
    ],
);
```

**Comment by jtdLab** [comment]
At the moment `AutoRouter` can be defined with implicit routes from the router or in a declarative way via

```dart
// implicit
AutoRouter();

// declarative
AutoRouter.declarative(
    routes: (_) => [ // routes depending on state go here],
);
```

`AutoTabsRouter`s can be defined only in a declarative way via a required `routes` option like so:

```dart
// declarative only
AutoTabsRouter(
    routes: [ /* routes depending on state go here */ ],
); 
 
// declarative only
AutoTabsRouter.pageView(
    routes: [ /* routes depending on state go here */ ],
); 

...
```

Wouldn't it be more consistent to write some thing like:

```dart
// implicit
AutoRouter();

// declarative
AutoRouter(
    routes: (_) => [ /* routes depending on state go here */],
);
```

```dart
// implicit uses routes and their order as defined in router
AutoTabsRouter();

// declarative
AutoTabsRouter(
    routes: [ /* routes depending on state go here */ ],
); 

// implicit uses routes and their order as defined in router
AutoTabsRouter.pageView();
 
// declarative
AutoTabsRouter.pageView(
    routes: [ /* routes depending on state go here */ ],
); 

...
```

**Comment by Milad-Akarie** [comment]
@jtdLab I've tried a couple times to omit pre-declaring routes for TabsRouter with no success. 
you see TabsRouter is mainly driven by indexes. one Idea I had was to provide a way to navigate to a tab and provide it's index at the same time but that would introduce alot of problems e.g setting active index for non-initialised indexes.

 until now the most practical Idea I could came out with is to CHOSE not to pass routes and use the already decelerated routes as placeholder routes until you navigate to that route  ->` tabsRouter.navigate(Tab1Route()); `
but if a user setsActiveIndex for non-initialised that has required args then we have a problem. 

I'd love to hear  any ideas or visions regarding this.
