### ISSUE TITLE
AutoRouterHelper is not compatible with android studio

### ISSUE THREAD

**Issue by arjundevlucid** [Milad-Akarie/auto_route_library#1397]
![image](https://user-images.githubusercontent.com/96035930/224232570-12e97e08-0f17-4370-8cc1-8eec7edcc0eb.png)

**Comment by park012241** [comment]
me too

IDE: JetBrains IntelliJ IDEA Ultimate 2022.3.3 (223.8836.41)
OS: macOS Ventura 13.2.1 (22D68)
AutoRoute Helper version: 0.1.2

<img width="486" alt="image" src="https://user-images.githubusercontent.com/12793256/224532511-08e68ec6-48d3-44f8-9668-ebe3384be121.png">

**Comment by Milad-Akarie** [comment]
@arjundevlucid @park012241  updated!
if you don't want to wait for the update to be approved you can download it manually  here
https://github.com/Milad-Akarie/auto_route_library/blob/v6.0.0_redesigned/tools/AutoRoute-Helper-0.1.3.jar

**Comment by park012241** [comment]
> @arjundevlucid @park012241 updated! if you don't want to wait for the update to be approved you can download it manually here https://github.com/Milad-Akarie/auto_route_library/blob/v6.0.0_redesigned/tools/AutoRoute-Helper-0.1.3.jar

Thank you! I've got migrationed to 6.0 RC by my own (It was fun to do) though, I think it's useful :D
