### ISSUE TITLE
Open nested route above the bottomNavigationBuilder in AutoTabsScaffold

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1399]
Let say we have this route structure:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute<void>(
      page: InfoPage,
    ),
    AutoRoute<void>(
      initial: true,
      page: MainPage,
      children: [
        AutoRoute<void>(
          initial: true,
          page: EmptyRouterPage,
          children: [
            AutoRoute<void>(
              initial: true,
              page: HomePage,
            ),
            AutoRoute<void>(
              page: SearchPage,
            ),
          ],
        ),
      ],
    )
  ],
)
class AppRouter1 extends _$AppRouter1 {}
```

Inside `MainPage` we have `AutoTabsScaffold` with `bottomNavigationBuilder` widget.
Is it possible to navigate to `SearchPage` in fullscreen (the `SearchPage` be above the `MainPage` and the `bottomNavigationBuilder` widget)?

We only achieved that by moving the `SearchRoute` outside the `MainRoute` and pushing it into the stack.

**Comment by Milad-Akarie** [comment]
@MartinAKovachev that's the recommended approach, you can also chose to hide the bottomNav for certain routes.

**Comment by MartinAKovachev** [comment]
@Milad-Akarie The main reason for asking is regarding this scenario:
The user opens the application from a deeplink and we navigate the user to `SearchPage` (`SearchPage` is registered into the root Navigator/ outside the `MainRoute`). Then the user should be able to press Back button from the app bar and navigate to `MainRoute` (`HomePage` as it is set as initial). But the back button is not shown because `SearchRoute` is the only Route in the Navigator stack.
Any ideas how to handle that correctly?

**Comment by MartinAKovachev** [comment]
@Milad-Akarie From a cold start (Android, iOS):

1. Open the application
2. The user is navigated to the initial `Route` which is being set in the AutoRoute routes configuration.
3. Then check for initial deep link
4. If there is initial deep link, we map the deeplink string to our `Route`s and `push/replaceAll` etc. the corresponding Route (`router.push(SomeRoute)`)

We tried and this approach:

1. Open the application
2. Then check for initial deep link
3. If there is initial deep link, we map the deeplink string to our `Route`s and set `config(initialRoutes: [SomeRoute()])`

The problem with the second approach is that if the `Route` is registered into the root Navigator, we are not able to go back to the `SomeMainRoute`

**Comment by Milad-Akarie** [comment]
@MartinAKovachev first things first,  know that if your deep-linking setup is set properly you should not need to check any initial-deep links your self, MaterialApp.router + AutoRoute should do the job for you.

secondly, auto_route includes prefixed matches when handling deep-links.
e.g 
lets say you have this router setup 
```yaml
home: '/'
products: '/products',
   details: /:id
```
          
 navigating to `/products/1 `with `includePrefixedMatches` set to true ( defaults to true in deep-links handling )
 should create this stack hierarchy
```yaml
 [ 
   home, 
   products:  [details],
  ]
```

if you have something like this 
```yaml
home: '/'
products: '/products',
productDetails: /products/:id
```
then your stack hierarchy should look something like this
```yaml
 [
    home,
    products,
    productDetails
 ]
```
