### ISSUE TITLE
How to customize route name?

### ISSUE THREAD

**Issue by rebaz94** [Milad-Akarie/auto_route_library#14]
Thanks for this awesome package. 
Is there is anyway to customize route name instead of default variable name?

**Comment by Milad-Akarie** [comment]
Hey @rebaz94. I'm not sure I understand your question. 
You can actually name your route anything you want. 
HomeScreen myWhateverHomeScreenRouteName;

**Comment by kuhnroyal** [comment]
I also think there should be an optional way to name routes via the annotations.

```
@MaterialRoute(name = `/foo/bar`)
MyFancyRoute foo;
```

**Comment by Milad-Akarie** [comment]
Hey @kuhnroyal, can you explain where is that useful? 
I'm generally aiming for less boilerplate code. 
I'm planning to add a global optional prefix/suffix, would that satisfy what you have in mind?

**Comment by kuhnroyal** [comment]
I am think about flutter web and readable URL like route names.

**Comment by rebaz94** [comment]
@Milad-Akarie Yes I know this way, but there should be an option to set custom name.
For example if I want to set route name to be ```/edit-screen``` thats not possible now because we can't do ```EditScreen edit-screen```,  and as @kuhnroyal  suggested for readability name of web routes

**Comment by Milad-Akarie** [comment]
@kuhnroyal  @rebaz94 until now I didn't consider flutter web as I haven't had the chance temper with it yet. So thanks for bringing that to my attention. 

so the idea I have in mind right now is to first make auto-generated route names URL-friendly (kabab cased) by default and also add an optional route name in all route annotations as @kuhnroyal  suggested. 
`@MaterialRoute(name: 'my-route-name')`

Thank you both for taking the time to help make auto_route better.

**Comment by Milad-Akarie** [comment]
@rebaz94 @kuhnroyal 
added in v0.2.2 
Auto-generated route names are now url-friendly
homePage => '/home-page'

you can also pass custom names as follows
`@MaterialRoute(name: 'your-custom-path-name')`
Thanks for your time.
