### ISSUE TITLE
Navigation works only once, second try returns in empty page

### ISSUE THREAD

**Issue by radvansky-tomas** [Milad-Akarie/auto_route_library#1404]
This is very weird behavior, I've checked logs and it seem to be doing exact same steps, but second time it fails.

So I have 
Home (ROOT) -> Library(Child) with tabs ->Tab1 

Path:
`/home/library/tab1`

Inside Tab1 button navigates to detail page
Path:
`/home/library/tab1/meetings/:meetingId`

When button is pressed for the first time, meeting detail page is correctly opened -> then when context.navigateBack() is called everything is back to normal and I am back at `/home/library/tab1`

However if you press the same button again, open detail page and navigate back you end up with content of
`/home`

There is no library page nor tabs loaded (just header and empty page).

I am using Autorouter tabs and this is structure:
```dart
 /// Home nested navigation
    AutoRoute(
      path: '/home',
      guards: [
        IsNotAnonymGuard(ref: ref),
        OnboardingCompleteGuard(ref: ref),
        HomeGuard(ref: ref)
      ],
      page: HomeRootPageRoute.page,
      children: [
        RedirectRoute(path: '', redirectTo: 'library'),
        AutoRoute(
          path: 'library',
          page: LibraryPageRoute.page,
          title: ((context, data) => 'Library'),
          maintainState: true,

          /// Library nested navigation
          children: [
            RedirectRoute(path: '', redirectTo: 'accessible-meetings'),
            AutoRoute(
              path: 'accessible-meetings',
              page: LibraryAccessibleMeetingsTabRoute.page,
            ),
            AutoRoute(
              path: 'my-meetings',
              page: LibraryMyMeetingsTabRoute.page,
            ),
            AutoRoute(
              path: 'shared-meetings',
              page: LibrarySharedTabRoute.page,
            ),
          ],
        ),
        AutoRoute(
            path: 'account-settings',
            page: SettingsPageRoute.page,

            /// Library nested navigation
            children: [
              RedirectRoute(path: '', redirectTo: 'calendar'),
              AutoRoute(
                path: 'calendar',
                page: SettingsCalendarTabRoute.page,
              ),
              AutoRoute(
                path: 'billing',
                page: SettingsBillingTabRoute.page,
              )
            ]),
      ],
    ),

    AutoRoute(
      path: '/home/library/:libraryType/meetings/:meetingId',
      page: MeetingDetailPageRoute.page,
      usesPathAsKey: true,
      guards: [MeetingResolver(ref: ref)],
      title: ((context, data) => 'Meeting'),
    ),
```

**Comment by radvansky-tomas** [comment]
I just converted it to V6, but same situation is with previous version

**Comment by Milad-Akarie** [comment]
@radvansky-tomas I tried to reproduce this with no success, can you share a complete minimal implementation that reproduces this?  I guarantee that I give it attention. 

also I don't think setting maintainState = false is a good idea unless you know what you're doing, because any state inside that route will not be preserved.
