### ISSUE TITLE
Implementing tab navigation with pageview but without BottomNavigationBar

### ISSUE THREAD

**Issue by davies-maina** [Milad-Akarie/auto_route_library#1405]
Is there a way I could create some sort of onboarding screen leveraging the 'Next' and 'Previous' buttons to navigate through multiple pages with nested routes? All current implementations in the docs use the  BottomNavigationBar. How can I do this while benefitting from auto_route_library capabilities like preserving page states?

**Comment by Milad-Akarie** [comment]
@davies-maina you can simply create an `AutoTabsRouter.pageView` and not use a bottom navigation bar with it.
and for your next and previous buttons you can use the PageController from the builder 

```dart
AutoTabsRouter.pageView(
  routes: [...],
  builder: (context, child, pageController) {
    // pageController.nextPage(...)
    // pageController.previousPage(...)
 )

```
