### ISSUE TITLE
[6.0.0.x] Custom TransitionBuilder Secondary Animation value is always 0

### ISSUE THREAD

**Issue by prologikus** [Milad-Akarie/auto_route_library#1406]
Custom TransitionBuilder Secondary Animation value is always 0.

`mixin CustomTransitionsBuilders implements TransitionsBuilders {
  static const RouteTransitionsBuilder customMade = _customMade;

  static Widget _customMade(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    print("anim1: ${animation.value}");
    print("anim2: ${secondaryAnimation.value}");
    return SlideTransition(
      position: Tween<Offset>(
        begin: const Offset(0.0, 1.0),
        end: Offset.zero,
      ).animate(animation),
      child: SlideTransition(
        position: Tween<Offset>(
          begin: Offset.zero,
          end: const Offset(0.0, 1.0),
        ).animate(secondaryAnimation),
        child: child,
      ),
    );
  }
}`

`@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends $AppRouter {
  AppRouter();

  @override
  RouteType get defaultRouteType => const RouteType.custom(
      transitionsBuilder: CustomTransitionsBuilders.customMade,
      durationInMilliseconds: 2000);

  @override
  final List<AutoRoute> routes = [`

**Comment by Milad-Akarie** [comment]
fixed in v6.0.0 
Thanks for reporting.
