### ISSUE TITLE
Not able to run build_runner when upgraded to auto_route_generator-6.0.0

### ISSUE THREAD

**Issue by anderscheow** [Milad-Akarie/auto_route_library#1416]
Hi,

I'm hitting this error when try to run build_runner

![CleanShot 2023-03-22 at 11 15 48](https://user-images.githubusercontent.com/11788504/226793038-46ce5435-e9af-4471-b648-a5932e56cf57.jpg)

**Comment by mxkdev** [comment]
It seems to be some issue with having the incorrect `code_builder` dependency version. I fixed the error by explicitly adding `code_builder` as a dependency to my `pubspec.yaml`.

`code_builder: ^4.4.0`
