### ISSUE TITLE
[Question] Get current route on version 6.0.0

### ISSUE THREAD

**Issue by iTEEECH** [Milad-Akarie/auto_route_library#1420]
Hi,

Firstly, very good job for the last version !

I have one question to get the current url in nested router. I currently have a router with two children. 

For that, I created my routes in the following way : 

```AutoRoute(
      page: ParentRoute.page,
      path: '/',
      children: [
        AutoRoute(
          page: ChildrenARoute.page,
          path: '',
        ),
        AutoRoute(
          page: ChildrenBRoute.page,
          path: '',
        ),
      ],
    ),
```

I called the Autorouter() like the previous version. So far everything works but I can't get the current route... It always shows me the parent route.

``` 
final router = ref.watch(router);

    print(router.current.name);
    print(router.currentPath);
    print(router.currentChild?.name);
```

Did I miss a step please ? Thanks

**Comment by Milad-Akarie** [comment]
@iTEEECH didn't see this one, did you figure something out?
