### ISSUE TITLE
CustomRoute animation not working correctly with v6

### ISSUE THREAD

**Issue by austinried** [Milad-Akarie/auto_route_library#1426]
After upgrading to v6, my CustomRoutes with fade animations are no longer working correctly. Instead of using just the animation builder I choose, they are using the "expand" animation in the background plus the animation I choose. So for example:

```dart
CustomRoute(
  path: 'album',
  page: AlbumSongsRoute.page,
  transitionsBuilder: TransitionsBuilders.slideBottom,
  durationInMilliseconds: 200,
  reverseDurationInMilliseconds: 200,
),
```

This will slide the new page up from the bottom, but the background also does the default zoom in animation and it looks broken.

**Comment by Milad-Akarie** [comment]
@austinried I'm gonna need more info, are you on mobile? is this a nested or a root page?

**Comment by Milad-Akarie** [comment]
we fixed reversed animation value before maybe that triggered the issue in your code, try setting the reverse duration for the bottom page to 0 and see what happens

**Comment by austinried** [comment]
It's a nested route, setting reverse duration to 0 doesn't seem to help. Another thing I've noticed is that when I switch back to just using the default material transitions, the background freezes during the transition, so it doesn't appear smooth, but I don't know if this is related. I'll try to get a repro going.

**Comment by austinried** [comment]
Alright sorry for the lack of details earlier, this is on Android.  I'm mainly using an emulator with Android 11 but it repros on a real device with Android 13 as well. It was working in v5 and started doing this when I upgraded to v6, so I don't know if it's a bug or something that needs to be changed for the upgrade.

Here is a minimum repro project, looks to me like the issue comes from `AutoTabsRoute.tabBar` but I'm not sure: https://github.com/austinried/auto_route_animation_bug

![auto_route_bug](https://user-images.githubusercontent.com/4966622/229256976-6f5702ac-541d-4890-b008-93a850c47443.gif)

**Comment by Milad-Akarie** [comment]
@Kuodster what route type is the underlying page using?

**Comment by austinried** [comment]
I've updated my repro-repo a bit so you can compare the behavior against the v5 branch, where the background does not zoom with a custom animation: https://github.com/austinried/auto_route_animation_bug/tree/v5 

I've also altered the color of the button a little bit to make the second problem easier to see, which is that the background freezes during transitions now too (button stays red when it should keep animating during transition). This happens both to and from transition, but it's harder to see on the way back because the animation needs to be faster to catch it. I'm unsure if this is related, but it happens with non-custom animations too. @Milad-Akarie would you like me to file a separate bug for that?

![freezing](https://user-images.githubusercontent.com/4966622/231024812-ada4597a-7b19-4937-a0d0-4c647701f342.gif)

**Comment by Kuodster** [comment]
@Milad-Akarie The zoom-in/zoom-out effect on the underlying page does not appear if we're using a custom route builder as the default one:

`@override
  RouteType get defaultRouteType => RouteType.custom(
    transitionsBuilder: (context, animation, secondaryAnimation, child) {
      return FadeTransition(
        opacity: animation,
        child: child,
      );
    },
  );`

Unfortunately this isn't a way to go, since we're using adaptive() routes to support the iOS swipe back.

**Comment by dJani97** [comment]
I have the same issue with a CustomRoute in v6:

```dart
@override
RouteType get defaultRouteType => const RouteType.adaptive();

@override
late final List<AutoRoute> routes = [
  AutoRoute(
      path: '/',
      // other routes my app uses
  CustomRoute(
      path: '/dialog',
      page: OkDialogRoute.page,
      opaque: false,
      barrierDismissible: true,
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 300,
      reverseDurationInMilliseconds: 300),
];
```

This `/dialog` route was nicely fading in before, and now it does the default material route transition.

**Comment by dJani97** [comment]
> Adding "fullscreenDialog: true" to the custom route disables the effect too @austinried

Missed this part earlier. Setting this flag works well for me.
