### ISSUE TITLE
(context.router.pushAndPopUntil) entry.currentState == _RouteLifeCycle.popping: is not true. In Debug Mode.

### ISSUE THREAD

**Issue by arv-aks** [Milad-Akarie/auto_route_library#1428]
Error occurred when using pushAndPopUntil only in debug mode, and **working in Release mode.**

`           context.router.pushAndPopUntil(
                HomeScreenRoute(comeFrom: 'registration'),
                predicate: (_) => false);
`

- 

<img width="971" alt="Screenshot 2023-03-23 at 10 03 33 AM" src="https://user-images.githubusercontent.com/84610386/227104475-98867ba4-ab78-4194-aa9e-a90e85a535dc.png">

**Comment by Milad-Akarie** [comment]
@arv-aks I could not reproduce this

**Comment by tomasweigenast** [comment]
Got the same issue!
