### ISSUE TITLE
Question on Preserving tab state with Offstage widgets

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#143]
Thanks for the amazing package Milad. I've looked at Fluro, Sailor, built-in Navigation, but this one is the most streamlined solution by far.

I have a quick question  - I'm currently using offstage widgets and multiple ExtendedNavigators in order to preserve the tab state of each tab (I'm sure you're familiar with this: https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf). 

With this method, I do not have a root navigator. 

I just wanted to ask, is it possible to preserve tab state while implementing a root navigator? Or is there a more "auto_router" kind of way to achieve this?

Thanks

**Comment by Milad-Akarie** [comment]
Hey @theweiweiway I've been getting a lot of questions about how parallel navigation can be implemented using auto_route so I made a demo app to demonstrate it [Parallel Navigation Using Auto Route](https://github.com/Milad-Akarie/parallel-navigation-demo-auto-route)

hope this helps!

**Comment by theweiweiway** [comment]
Thank you!!

**Comment by theweiweiway** [comment]
Hi Milad! 

The example is great - however i was wondering if there is a better way to handle popping from the correct navigator. 

Basically, If I click on the profile tab and then push ``Profile Details``, it goes to the yellow page as expected. Then, if I change to the posts tab and push the ``Posts Details``, it goes to the green page as expected. 

However, now if i am on the green page and i use the android back button, instead of popping the green page back to the ``Posts List`` screen, it pops the yellow page back to the ``Profile Home`` screen (this is hidden). Then if I use the android back button for the 2nd time, it will pop back properly to the ``Posts List`` home page. 

I've managed to solve this problem by doing:
```
class ProfileDetails extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        ExtendedNavigator.byName("post").pop(); // ADDED THIS EXTRA LINE HERE
      },
      child: Scaffold(
        backgroundColor: Colors.amber.shade200,
        appBar: AppBar(
          title: Text("Profile Details"),
          backgroundColor: Colors.amber.shade600,
        ),
        body: Center(
          child: RaisedButton(
            child: Text("navigate to root/settings"),
            onPressed: () {
              ExtendedNavigator.root.pushNamed(Routes.settingsPage);
              // or with context
              // ExtendedNavigator.of(context,rootNavigator: true).pushNamed(...)
            },
          ),
        ),
      ),
    );
  }
}
```

But i was wondering if there was a "nicer" way of doing this without having to add a will pop all over the place, especially for bigger apps.

thanks!

**Comment by theweiweiway** [comment]
sorry - the ``onWillPop`` works completely fine when returning either true or false. I've implemented this method in my larger app and it isn't actually so bad, so i'm closing this again.

**Comment by wiztensai** [comment]
Hi, i have question.

How to import ExtendedNavigator class? @Milad-Akarie @theweiweiway

**Comment by Milad-Akarie** [comment]
@wiztensai ExtendedNavigator is 3 years old, it no longer exists
