### ISSUE TITLE
Does 6.0.1 support having multiple hot-swappable routers?

### ISSUE THREAD

**Issue by leomorpho** [Milad-Akarie/auto_route_library#1436]
My app implements auth with the BLOC pattern by hot-swapping routers based on the authentication state. I noticed that the generated routers now contain all pages from all the different routers. Is there a method to specify routes belonging to a specific router? Or is that not supported anymore?

**Comment by Milad-Akarie** [comment]
@leomorpho the generated code didn't change much, the page map is still provided by the root router to all sub routers. 
I'm not sure what changed for you?
