### ISSUE TITLE
[FR] Customizable _placeHolderRoute

### ISSUE THREAD

**Issue by gersur** [Milad-Akarie/auto_route_library#144]
`auto_route` use placeholder route before actually display the initial route.

The code to placeholder route:
https://github.com/Milad-Akarie/auto_route_library/blob/df8be3494e48d0ccc074f345869480633025c22e/auto_route/lib/src/extended_navigator.dart#L66-L68
IMO this looks really ugly, even though only shown for split second.

These page should be customizable to match the splash screen that shown while flutter is starting.

**Comment by Milad-Akarie** [comment]
hey @gersur it should be white lol I switched tog green to better see if it flickers and forgot to switch it back.
It'll be fixed soon.

**Comment by Milad-Akarie** [comment]
@gersur Fixed in auto_route 0.6.2 
Sorry for the delay
