### ISSUE TITLE
Changing 'Select widget mode' in DevTools causes "app restart"

### ISSUE THREAD

**Issue by petro-i** [Milad-Akarie/auto_route_library#1442]
Hi after upgrade to 6.x it is not possible to to use Flutter DevTools for searching widgets with 'Select widget mode'. Now apps "restarts" == widget tree rebuilds completely on switching on/off 'Select widget mode'. 
Actually it became worth in 6.0.3, in 6.0.1 there was problem with routes with params (they were recreated without parmas with appropriate exception), but routes without params were recreated in case 'Select widget mode' without any problems, but now it looks like complete app restart.

**Comment by Milad-Akarie** [comment]
Hello @petro-i need more info on this, I tried it my self and everything works as expected. 
what platform are you using it on? 
how are you using the inspector? idea or web?

I need reproducible steps to work on this
