### ISSUE TITLE
fullPath removed in v6

### ISSUE THREAD

**Issue by krokyze** [Milad-Akarie/auto_route_library#1444]
Hey.

I was using `fullPath` on Web to know what will be the result url before navigating to it just so I can put it inside html for SEO purposes.

Like this:
```
final route = PostDetailsRoute(id: post.id);

return AppLink(
  href: route.fullPath,
  child: GestureDetector(
    onTap: () => router.push(route),
    child: ...
  ),
);
```

Is there any plan to add it back or any solutions how to retrieve it?

**Comment by Milad-Akarie** [comment]
@krokyze paths were defined in more than one place in the older version which led to a bad design,  I added a littler helper in the new version where you can do something like this 
`router.match(PostDetailsRoute(id: post.id))?.fullPath`

**Comment by krokyze** [comment]
Thanks for the quick response, just tested. It works but as for root paths it's mandatory to start with `/` the fullPath has double slash at the beginning `//posts/0`

Do you see it as an issue within fullPath implementation or should I simply replace double slash with single on my side?

![Screenshot 2023-03-30 at 02 14 57](https://user-images.githubusercontent.com/5682176/228688501-984d5e1f-3dd2-4d74-bab3-d2b2f7d6572b.png)

**Comment by Milad-Akarie** [comment]
Yup it slipped, should have used path.join
Will fix it tomorrow

**Comment by krokyze** [comment]
@Milad-Akarie thanks. Just tested and works flawlessly 👍
