### ISSUE TITLE
Allow multiple route names for same screen

### ISSUE THREAD

**Issue by ahmedshikashaker** [Milad-Akarie/auto_route_library#1445]
In my case, I'm using the same screen for two different paths. One path is for when the user is logged in, and I use it as a child for another route that includes a side menu. The other path is for when the user is not logged in, and it doesn't have a parent route or a side menu. In version 6, I am having trouble achieving this.

**Comment by Milad-Akarie** [comment]
@ahmedshikashaker This use case was a big deal for me personally as well, but I thought why not use the same name with different paths, and depending on what router you're in auto_route will push the right path.
e.g

   ```dart
 AutoRoute(
    path: 'path1',
    page: TargetRoute.page, // duplicated page 
  ),
  AutoRoute(
    path: 'path2',
    page: SomeParentRoute.page,
    children: [
      AutoRoute(
        path: 'sub-path',
        page: TargetRoute.page, // duplicated page 
      ),
    ]
  ),
```

so if you're on the root router and you pushed TargetRoute() you will get 'path1' but if you're on nested-router  you get 'sub-path'

wouldn't that work for your?

**Comment by mirland** [comment]
Hi @Milad-Akarie, I have a similar issue, I have a `SectionRouter`, a page that handles common logic for all sections in my app.

Suppose that I have 2 sections, `AuthenticatedSectionRouter` and `UnauthenticatedSectionRouter` (the routes when you are authenticated and the routes when you are not authenticated).

In the previous version of the library, I could use:
```dart
routes: <AutoRoute>[
    AutoRoute(
      name: 'UnauthenticatedRouter',
      page: SectionRouter,
      initial: true,
      guards: [UnauthenticatedGuard],
      children: [
             // routes
      ],
    ),
    AutoRoute(
      name: 'AuthenticatedRouter',
      page: SectionRouter,
      guards: [AuthenticatedGuard],
      children: [
        // Routes
      ],
    ),
  ],
``` 

However, In this version, I cannot do the same if I want to use the same page (the `SectionRouter`).
In the latest version, I have to define other pages to achieve the previous result 

```dart
@RoutePage()
class AuthenticatedSectionRouter extends SectionRouter{
  const AuthenticatedSectionRouter({super.key});
}

@RoutePage()
class UnauthenticatedSectionRouter extends SectionRouter{
  const UnauthenticatedSectionRouter({super.key});
}
```

So I could do the same, but I had to create new pages. I preferred to use the same page, with different name, it's more clear for me

You can check the full migration [here](https://github.com/xmartlabs/flutter-template/pull/167) (it's not a long PR and it may help to understand the issue)

Do you think there's another way to achieve the previous result?

Thanks!

**Comment by Milad-Akarie** [comment]
Hey @mirland I agree but still cant image a neat way to implement this, any suggestions?

**Comment by mirland** [comment]
I was thinking and I couldn't find a better solution using the current package state. However, we could allow defining multiple `@RoutePage` annotations for the same page. 

We could define something like:
```dart
@RoutePage(name: 'AuthenticatedSectionRouter')
@RoutePage(name: 'UnauthenticatedSectionRouter')
class SectionRouter extends StatelessWidget {
```

I tested and it's not working but if we add that feature, I think it's the best way to go.

What do you think?

**Comment by Milad-Akarie** [comment]
Ya that's what I have in mind and it suggests by others before but this annotation has the deferred loading flag and the return type of the route and these two can not be different so I guess we need a different annotation which is going to add a bit of complexity

**Comment by Milad-Akarie** [comment]
Im thinking @PageAlias(name: Name)
Or @RouteAlias(name: Name)
And these should be usable with factory/named constructors as well

**Comment by Milad-Akarie** [comment]
Or @RoutePage can take a lost of aliases 🤔

**Comment by mirland** [comment]
Yes I thought that option too, I think all these solutions are great, because we will support exactly what we were supporting and in a better way

**Comment by chounry** [comment]
I can only do that in v5, where there is 'name' option.

```dart
[
  CupertinoRoute(
    path: RoomListScreen.path,
    page: RoomListScreen,
    usesPathAsKey: true,
    children: [
      CupertinoRoute(
        path: DetailScreen.path,
        page: DetailScreen,
        name: 'DeviceScreenRoomDetailScreen'
        usesPathAsKey: true,
      ),
    ]
  ),

  CupertinoRoute(
    path: DeviceScreen.path,
    page: DeviceScreen,
    usesPathAsKey: true,
    children: [
      CupertinoRoute(
        path: DetailScreen.path,
        page: DetailScreen,
        name: 'DeviceScreenRoomDetailScreen'
        usesPathAsKey: true,
      ),
    ]
  ),
]
```
 I haven't test on v6.

**Comment by mirland** [comment]
Maybe we can keep it opened

**Comment by ericvalero** [comment]
Hello, I have the same issue, two paths that go to the same page, my only solution was what @mirland has done:

> However, In this version, I cannot do the same if I want to use the same page (the `SectionRouter`). In the latest version, I have to define other pages to achieve the previous result
> 
> ```dart
> @RoutePage()
> class AuthenticatedSectionRouter extends SectionRouter{
>   const AuthenticatedSectionRouter({super.key});
> }
> 
> @RoutePage()
> class UnauthenticatedSectionRouter extends SectionRouter{
>   const UnauthenticatedSectionRouter({super.key});
> }
> ```
> 
> So I could do the same, but I had to create new pages. I preferred to use the same page, with different name, it's more clear for me

In my case is like this:

```dart
@RoutePage()
class PageOne extends DetailPage {
  const PageOne({
    @pathParam required super.entityCode,
    @pathParam required super.tabName,
    @pathParam required super.tileName,
    @queryParam super.requestId = '',
    @queryParam super.title = 'N/A',
    super.key,
  });
}

@RoutePage()
class PageTwo extends DetailPage {
  const PageTwo({
    @pathParam required super.entityCode,
    @pathParam required super.tabName,
    @pathParam required super.tileName,
    @queryParam super.requestId = '',
    @queryParam super.title = 'N/A',
    super.key,
  });
}
```

I want to ask if now exists a better solution for this problem, because in my case I have params, so that means I have duplicated code, and that is not good for long term app maintenance.

**Comment by k-ane** [comment]
Can this one be re-opened or is there a new issue to track? @Milad-Akarie

**Comment by gilang-sera** [comment]
any tips for this sir?

**Comment by imhafeez** [comment]
Any update on this issue? i have the same problem? how to define routes for multiple named constructors?

**Comment by Dekhnar** [comment]
Is this still a live issue? Or has the subject been dropped, a workaround?
