### ISSUE TITLE
Migrating: how to pass a navigator key to AppRouter

### ISSUE THREAD

**Issue by arualana** [Milad-Akarie/auto_route_library#1446]
Before I could do

 `final _appRouter = AppRouter(AppServices.key);`

Is it possible to pass a key now? It seems AppRouter doesn't take any parameters. I see that I can use dependency injection to push routes without a context, but I am using the global context for other things like showing loadingOverlay from functions without having to pass the context.

**Comment by arualana** [comment]
@gbmiranda I found a way to do it

You use get_it like the documentation says

```
// This is our global ServiceLocator
GetIt getIt = GetIt.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  getIt.registerSingleton<AppRouter>(AppRouter());
}
```

Then in you app

```
class _MyAppState extends State<MyApp> {
  final _appRouter = getIt<AppRouter>();
 /// .......
}
```
And you define the context like this

```

class AppServices {
  static BuildContext get context =>
      getIt<AppRouter>().navigatorKey.currentContext!;
}
```

Let me know if this helps

**Comment by d95sld95** [comment]
```
@AutoRouterConfig(
  replaceInRouteName: 'Page,Router',
)
class AppRouter extends $AppRouter {

  // C
  AppRouter({GlobalKey<NavigatorState>? navigatorKey}) : super(navigatorKey);

...
}
```

**Comment by gbmiranda** [comment]
> @gbmiranda I found a way to do it
> 
> You use get_it like the documentation says
> 
> ```
> // This is our global ServiceLocator
> GetIt getIt = GetIt.instance;
> 
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   getIt.registerSingleton<AppRouter>(AppRouter());
> }
> ```
> 
> Then in you app
> 
> ```
> class _MyAppState extends State<MyApp> {
>   final _appRouter = getIt<AppRouter>();
>  /// .......
> 
>        return MaterialApp.router(
>             title: 'Title',
>             routerConfig: _appRouter.config(),
>             /// .......
>         ); 
> 
> }
> ```
> 
> And you define the context like this
> 
> ```
> 
> class AppServices {
>   static BuildContext get context =>
>       getIt<AppRouter>().navigatorKey.currentContext!;
> }
> ```
> 
> Let me know if this helps

Great, I haven't seen this property before!

**Comment by gbmiranda** [comment]
@arualana 

I had solved it by creating a BuildContextProvider and always updating it in the builder. Very useful to access themes without context.

<img width="506" alt="Captura de Tela 2023-03-29 às 12 18 54" src="https://user-images.githubusercontent.com/8632216/228586879-5af037b2-4297-42a8-9ecc-5c089fbe9fc5.png">

**Comment by arualana** [comment]
I think @d95sld95 is easiest

**Comment by Milad-Akarie** [comment]
You can pass it to the generated router's constructor or read the instance inside of it. 
I think it's safe to close this one.
