### ISSUE TITLE
RoutePage annotated page from different packages does not generate after updating to v6

### ISSUE THREAD

**Issue by mixin27** [Milad-Akarie/auto_route_library#1448]
How can I generate `@RoutePage()` annotated page from different featured packages after updating to v6+?

I separated project as different packages like `routes` and `features`.

`app_router.dart` in `routes` package and `@RoutePage()` annotated pages or screens are in `features` package.

**Comment by Milad-Akarie** [comment]
@mixin27 have you considered generating the pages in their packages then merge the sub-package router with the root router?

**Comment by mixin27** [comment]
@Milad-Akarie  There is no sub-package router in my project. I tried to run build_runner in every packages but it does not generate to `app_router.gr.dart`.

I think this happened because of `app_router.dart` and `@RoutePage` annotaed pages are in different package. My project structure is like

```bash
- lib/
  - some_page.dart # @RoutePage() annotated
- packages/
  - routes/
    - lib/
      - app_router.dart # AutoRoute config
  - features/
    - feature_one/
      - lib/
        - feat_one_page.dart # @RoutePage() annotated
    - feature_tow/
        - lib/
          - feat_two_page.dart # @RoutePage() annotated

```

Could you explain how to create and merge sub-package router with the root router?

Thanks

**Comment by Milad-Akarie** [comment]
@mixin27  What I meant is that every micro-package has it's own sub-router e.g FeatureOneRouter, FeatureTwoRouter then you can simple merge them 

```dart
class RootRouter extends $RootRouter{
  final feat1Router = FeatureOneRouter();
  
 @override
  Map<String, PageFactory> get pagesMap => {
 // add page builders for feat1
   ...featr1Router.pagesMap,
   ...super.pagesMap,  
  };


  late final List<AutoRouter> get routes = [
          // root routes
         
         // add route declaration for feat1
         ...feat1Router.routes,
    ]
 }
```

**Comment by mixin27** [comment]
Thank you so much @Milad-Akarie . It's worked.
