### ISSUE TITLE
Path and full path of route lacks in v6

### ISSUE THREAD

**Issue by papmodern** [Milad-Akarie/auto_route_library#1452]
I've recently migrated to the latest version but there is something prevents me to reach the same stable state.

In previous version I could access to the path of the route for navigating with navigate function. Lets say we have SomePageRoute and I could access it with this property: `SomePageRoute.path` but now its gone. Can you guide me how I can access the path of the route page?

**Comment by Milad-Akarie** [comment]
@papmodern is there reason why you navigate using the path when you have the Typed route name? why not navigate using the PageRoute()?

in the new version you'd have to match the route to get it's path, I added helper functions for that 

```dart
    context.router.match(WebLoginRoute())?.stringMatch;
    WebLoginRoute().match(context)?.path;
```

**Comment by corymartin** [comment]
I'm having the same issue.

I was using the `path` and `fullPath` properties in tests to ensure the URI structure was as desired.

**Comment by Milad-Akarie** [comment]
@corymartin shouldn't you test against the resolved path, the matched one?

**Comment by corymartin** [comment]
Many of the tests are simple functions - no `context` object is available.  I can rework those I think.

**Comment by Milad-Akarie** [comment]
You don't need context if you have the Router instance i guess
