### ISSUE TITLE
Hot Reload sets the home page 

### ISSUE THREAD

**Issue by Cavin6080** [Milad-Akarie/auto_route_library#1455]
I am facing some weird issue in Auto Route. Whenever my app is in the debug mode and I press `Command+S` for hot-reload, it automatically goes back to the home-screen. I am using latest version of Auto Route right now. 

And the `routes.dart` file is also pretty simple with few routes like this:

```
@AutoRouterConfig(replaceInRouteName: 'Page|Screen|Example,Route')
class AppRoutes extends $AppRoutes {
  @override
  RouteType get defaultRouteType => const RouteType.material();
  @override
  final List<AutoRoute> routes = [
    AutoRoute(
      page: HomeRoute.page,
      path: '/',
    ),
    AutoRoute(
      page: SliverPersistantHeaderRoute.page,
      path: '/sliver-persistant-header',
    ),
    AutoRoute(
      page: SliverListRoute.page,
      path: '/sliver-list-example',
    ),
    AutoRoute(
      page: SliverGridRoute.page,
      path: '/sliver-grid-example',
    ),
  ];
}
```

**Comment by Milad-Akarie** [comment]
@galatea21 where are you iniating the Router?

**Comment by Cavin6080** [comment]
It was inside the build method. I have changed it and now it's working fine. Thanks for helping

**Comment by arunspacek** [comment]
I have the same issue. The Router is not initialized in the build method, but it still goes back to the initial route whenever I hot reload (Ctrl+s)

**Comment by Cavin6080** [comment]
Could you share us the code for the MyApp widget ?

**Comment by arunspacek** [comment]
class App extends ConsumerWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final appRouter = AppRouter();
    final configDb = ref.watch(configDbProvider);
    final connInfo = configDb.getConnInfo();

    User? currentUser;

    String initialRoute = '/';
    if (connInfo == null) {
      initialRoute = '/';
    } else {
      final auth = ref.watch(appProvider);
      if (auth.currentUser == null) {
        initialRoute = '/login';
      } else {
        initialRoute = '/home';
      }
    }

    return MaterialApp.router(
      title: 'EZMBAPOS ${ezThemeData.entries.first.key} ',
      debugShowCheckedModeBanner: false,
      routerDelegate: appRouter.delegate(initialRoutes: [
        if (connInfo == null) const AppConfigRoute(),
        if (connInfo != null && currentUser == null) const LoginRoute(),
        if (connInfo != null && currentUser != null) const RootRoute(),
      ]),
      routeInformationParser: appRouter.defaultRouteParser(),
    );
  }
}
