### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by mayken** [Milad-Akarie/auto_route_library#1456]
Hi! I trying change locale emit the state from cubit without reload app but not working. How to work without reload app? App always use locale which first set. I see the state update success in logs but not interface.
<img width="681" alt="1" src="https://user-images.githubusercontent.com/568913/228933005-261b3493-9d00-403b-8058-85395bf38935.png">

**Comment by Milad-Akarie** [comment]
@mayken not sure if this's a navigation-related issue?
