### ISSUE TITLE
Issue with page parameters using Wiredash

### ISSUE THREAD

**Issue by hmflores95** [Milad-Akarie/auto_route_library#1461]
Hello, we're currently using [Wiredash](https://pub.dev/packages/wiredash) for user feedback, however, we're encountering an issue where, upon opening the pop-up window, the currently open page refreshes, and the generated args object with the parameters used to open it becomes null. The method refreshing the page is `pushAllGuarded` if that's of any help.

If you have any guidance or suggestions on how to address this issue, it would be greatly appreciated. Thank you

**Comment by Milad-Akarie** [comment]
@hmflores95 are you on web? what refreshes the currently open page?

**Comment by hmflores95** [comment]
Sorry it's on mobile, Android and iOS. Wiredash opens a widget as shown [here](https://user-images.githubusercontent.com/1096485/187313854-343bfe52-9444-407b-9e7e-64738187f8af.png) which makes the page shrink and move to the bottom, that's when the reload happens.

**Comment by hmflores95** [comment]
Here is the [call stack](https://github.com/Milad-Akarie/auto_route_library/files/11143075/callstack.txt)

**Comment by Milad-Akarie** [comment]
@hmflores95 where are you initialising the AppRouter?

**Comment by hmflores95** [comment]
With `MaterialApp.router` at the root of the app, we are using `routeInformationParser` for adding observers in `routerDelegate` but I tried with only `routeConfig` and got the same result.
