### ISSUE TITLE
[Discussion] Why AutoRoute not flutter favorite ?

### ISSUE THREAD

**Issue by dleurs** [Milad-Akarie/auto_route_library#1465]
Hello :) 

While go_router, beamer and routemaster are Navigator 2.0 routing packages with the Google approval "Flutter favorites", why auto_route has not been validated ?

Thank you

**Comment by Milad-Akarie** [comment]
@dleurs I need to be a verified uploader first, which's something I'm too lazy to do :D
Are you saying it's a big deal?

**Comment by dleurs** [comment]
I think yes, in my case it is difficult to promote and push auto_route to the team while it is not within "approved" navigator 2.0 routing packages.

"Flutter's favorite" make it sound robust, trustworthy and "will be maintained". They are also stars : 

- go_router, 2.6k likes pub, github included inside flutter packages 
- auto_route, 2.1k likes pub, 1.3k likes github
- beamer, 1.0k likes pub, 500 likes github
- routemaster, 526 likes pub, 300 likes github

**Comment by Milad-Akarie** [comment]
@dleurs I'll see what I can do about this, I'd need a domain for this.

**Comment by realitymolder** [comment]
> @dleurs I'll see what I can do about this, I'd need a domain for this.

let us know if you need any help, we are a community after all 🫶

**Comment by Milad-Akarie** [comment]
Thanks @realitymolder maybe some ideas on what content should go on the website?

**Comment by realitymolder** [comment]
> Thanks @realitymolder maybe some ideas on what content should go on the website?

Technically, as far as I know, there is no limitation for the domain contents. That means I would use the domain of the author for a personal site. Maybe a blog/ cv/ or just portal for the projects/packages you are involved in! :)

**Comment by Milad-Akarie** [comment]
@realitymolder turns out I only need to verify ownership of domain, I'll postpone the website for now.

**Comment by realitymolder** [comment]
BOOM ! NOW VERIFED!

**Comment by Milad-Akarie** [comment]
@realitymolder Next is written docs for public apis to max pub score then syncing github tags with releases then we wait
