### ISSUE TITLE
Push same route twice

### ISSUE THREAD

**Issue by Kuodster** [Milad-Akarie/auto_route_library#1467]
Hello.

We're facing an issue when trying to push the same route twice (or more).

Developing a product listing app and need the ability to navigate to the same Route which is already open (ex.: you open a Product page and press any similar product, which should open a new Product Single route on top).

Currently doing so will result in an error:

`The following assertion was thrown during a scheduler callback:
Multiple owners claimed child RestorationBuckets with the same IDs.

The following IDs were claimed multiple times from the parent RestorationBucket(restorationId: HomeRouter, owner: NavigatorState#d94ef(tickers: tracking 4 tickers)):
 * "p+ProductSingleRoute" was claimed by:
   * _RestorationScopeState#e464b
   * _RestorationScopeState#7eaa1 (current owner)
When the exception was thrown, this was the stack: 
#0      RestorationBucket._debugAssertIntegrity.<anonymous closure> (package:flutter/src/services/restoration.dart:873:7)
#1      RestorationBucket._debugAssertIntegrity (package:flutter/src/services/restoration.dart:874:6)
#2      RestorationBucket.finalize (package:flutter/src/services/restoration.dart:831:12)
#3      RestorationManager._doSerialization (package:flutter/src/services/restoration.dart:386:14)
#4      RestorationManager.scheduleSerializationFor.<anonymous closure> (package:flutter/src/services/restoration.dart:353:70)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#8      _invoke (dart:ui/hooks.dart:145:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)`

Is there any way to resolve the issue without adding multiple routes with different names? (as the user can navigate 20 times like this).
We're not using named navigation here since we need to pass additional objects to the route.

Thanks.

**Comment by Kuodster** [comment]
By digging the code a bit, found out that this is the source of the problem.
Adjusted it a bit to check that it does work for sure.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/8902787/230396150-82420c62-cce5-4a05-8660-0824629a263a.png">

Is it possible to implement a feature to provide a custom restorationId based on some route parameters?

**Comment by Milad-Akarie** [comment]
Hey @Kuodster  I added restorationId builder to AutoRoute so you can do something like this

```dart
 AutoRoute(
     restorationId: (route) => '${route.name}-${route.pathParams.get('id')}'
  )
```

reopen if needed.
