### ISSUE TITLE
AuthGuard with Riverpod

### ISSUE THREAD

**Issue by WillComesBack** [Milad-Akarie/auto_route_library#1469]
In the old 5.0.3 auto_route package, I was able to pass in AuthGuard with the WidgetRef param:
`_appRouter.value = AppRouter(authGuard: AuthGuard(ref: ref));`
since teh auto_route_setup allowed me to put in AuthGuard without params here
`        CustomRoute(path: 'archive', page: ArchiveRoute.page, guards: [AuthGuard], transitionsBuilder: TransitionsBuilders.noTransition),`

now that the params are needed in 6.0.5, I need to somehow get Ref into this. Is there a way to pass in that param to my AuthGuard?
```
class AuthGuard extends AutoRouteGuard {
  final WidgetRef ref;

  AuthGuard({required this.ref});
```

**Comment by Milad-Akarie** [comment]
@WillComesBack you can have your router take an authGuard as well

```dart
class AppRouter extends $AppRouter {
  final AuthGuard authGuard;
  AppRouter(this.authGuard);
}
```

**Comment by dbeulen** [comment]
Im having the same problem. If i try your solution @Milad-Akarie i end up with an error when im assigning the guard to a route:

```
The instance member 'authGuard' can't be accessed in an initializer.
```

Complete Approuter code:

```
@AutoRouterConfig(replaceInRouteName: "Screen,Route")
class AppRouter extends _$AppRouter {
  final AuthGuard authGuard;
  AppRouter(this.authGuard);

  @override
  final List<AutoRoute> routes = [
    AutoRoute(
      path: '/',
      page: FMenuBarRoute.page,
      guards: [authGuard],
      children: [
        AutoRoute(path: 'user', page: UserProfileRoute.page),
      ],
    ),
    AutoRoute(path: '/login', page: LoginRoute.page),
  ];
}
```

**Comment by Milad-Akarie** [comment]
Make routes initializer latr
Late final routes...

**Comment by WillComesBack** [comment]
I got it to work. Thanks!
`    _appRouter.value = AppRouter(authGuard: AuthGuard(ref: ref));`
```
@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends $AppRouter {
  @override
  late List<AutoRoute> routes = [];
  final AuthGuard authGuard;

  AppRouter({required this.authGuard}) {
    routes = [
      RedirectRoute(path: '/', redirectTo: '/splash'),
      CustomRoute(
        path: '/x',
        page: XRoute.page,
        children: [
          RedirectRoute(path: '', redirectTo: '/interim/0'),
          CustomRoute(path: 'archive', page: ArchiveRoute.page, guards: [authGuard], transitionsBuilder: TransitionsBuilders.noTransition),
...
```

**Comment by dJani97** [comment]
I had to look this up, the solution is not obvious, I would suggest adding this to the migration guide. Just something like:

> See instructions for Riverpod here: https://github.com/Milad-Akarie/auto_route_library/issues/1469

**Comment by yevgeniaronov** [comment]
> I had to look this up, the solution is not obvious, I would suggest adding this to the migration guide. Just something like:
> 
> > See instructions for Riverpod here: #1469

i agree, this wasn't trivial and i don't think i would find a solution if it wasn't for @WillComesBack's example

**Comment by MoyinShabi** [comment]
> Why not just pass a `WidgetRef` into the router and gaurds? That way you can read anything you need to in the guards.
> 
> ```dart
> @AutoRouterConfig()
> class AppRouter extends RootStackRouter {
>   AppRouter(this.ref);
>   final WidgetRef ref;
>   @override
>   List<AutoRoute> get routes => [
>         AutoRoute(page: OfflineRoute.page),
>         AutoRoute(page: AuthRoute.page, guards: [AuthGuard(ref)]),
>       ];
> }
> ```
> 
> ```dart
> class AuthGuard extends AutoRouteGuard {
>   final WidgetRef ref;
>   AuthGuard(this.ref);
> 
> 
> 
>   @override
>   void onNavigation(NavigationResolver resolver, StackRouter router) {
>     ref.read(authProvider);
> 
>     //...
>   }
> }
> ```

Do you have a riverpod provider for the AppRouter class in this example, because if you do, You won’t be able to assign a Ref to a WidgetRef?
