### ISSUE TITLE
AutoRouteWrapper with ChangeNotifierProvider

### ISSUE THREAD

**Issue by mester9000** [Milad-Akarie/auto_route_library#147]
Does the AutoRouteWrapper work with ChangeNotifierProvider? I tried to implement it but it says: Could not find the correct Provider above this Widget.

**Comment by Milad-Akarie** [comment]
Hey @mester9000 show me some code?

**Comment by mester9000** [comment]
@MaterialAutoRouter(routes: <AutoRoute>[
CustomRoute(
      page: ResultScreen,
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 400),
...])


class ResultScreen extends StatelessWidget implements AutoRouteWrapper {
  @override
  Widget wrappedRoute(BuildContext context) {
    return ChangeNotifierProvider(
        create: (_) => ProvResult(
              baseCoin: baseCoin,
              baseExp: baseExp,
              gameProv: gameProv,
              ran: ran,
            ),
        child: this);
  }
...

var _resProv;

@override
  Widget build(BuildContext context) {
_resProv = Provider.of<ProvResult>(context, listen: false);
...
}
}

I get this error: Error: Could not find the correct Provider<ProvResult> above this ResultScreen Widget

**Comment by Milad-Akarie** [comment]
Make sure you run the code generator after you implemented AutoRouteWapper.
Your generated route should look something like this
```dart
ResultScreen: (RouteData data) {
      return MaterialPageRoute<dynamic>(
        // make sure it's calling wrappedRoute(ctx) here
        builder: (context) => ResultScreen().wrappedRoute(context)
...
```

**Comment by devfelipereis** [comment]
@Milad-Akarie  I know it's closed but I think that it could be in the docs. Just as a note.
