### ISSUE TITLE
How to reliably navigate up?

### ISSUE THREAD

**Issue by mityax** [Milad-Akarie/auto_route_library#1470]
Hi, thanks for your great library – I have a usage question for a flutter web project:

Suppose somewhere in the route tree I have (still old style – v5.0.4):
```
AutoRoute(
  path: 'messages',
  page: EmptyRouterPage,
  children: [
    AutoRoute(
      path: ':messageId',
      page: MessageDetailsPage,
      children: MessageDetailsPage.tabs,
    ),
  ]
),
```

Then, if I directly go to `/messages/<message-id>` using the browser's address bar, it's impossible to navigate back using `context.router.pop()` – which makes sense.
However, I need to display a back button in the UI nonetheless, for the user to be able to navigate up to the `/messages` page. As of now I had an (ugly) workaround for this (attached in the end), but this stopped working after an update of `auto_route`. Is there some way to reliably accomplish this "pop or navigate up" behavior in `auto_route` 5.x?

Thanks for any help :)

<details><summary>Previous workaround that stopped working</summary>

        extension UpWorkaround on RoutingController {
          void navigateUp() async {
            final route = root.currentSegments;
            while (route.isNotEmpty && currentSegments.any((e) => e.name == route.last.name)) {
              route.removeLast();
            }
            final path = route.map((segment) {
              if (segment.path.startsWith(':')) {
                return segment.pathParams.getString(segment.path.substring(1));
              }
              return segment.path == '/' ? '' : segment.path;
            }).join('/');
        
            root.popUntilRoot();
            await root.navigateNamed(path);
          }
        
          void popOrNavigateUp() async {
            if (await pop() == false) {
              navigateUp();
            }
          }
        }
</details>

**Comment by Milad-Akarie** [comment]
Hey @mityax  try this 

```dart
extension AppRouterX on AppRouter {
 void navigateUpOrBack() {
    if(urlState.segments.length > 1){
      // keep this if you want the new
      // url to replace the current
       markUrlStateForReplace();
       navigateAll(urlState.segments..removeLast());
    }else {
      navigateBack();
    }
  }
}
```

**Comment by mityax** [comment]
Thanks – is there also a way to do this with v 5.x? Haven't yet had the time to upgrade our app to 6.x

**Comment by Milad-Akarie** [comment]
@mityax Are you sure? Navigate All has been there forever

**Comment by brotherfolnciy** [comment]
@Milad-Akarie Hi, what`s the solution?
