### ISSUE TITLE
Can't pass instance member to Guard instance

### ISSUE THREAD

**Issue by dario-digregorio** [Milad-Akarie/auto_route_library#1472]
First of all thank you for this package :) 

I have this AppRouter:
``` dart
class AppRouter extends _$AppRouter {
  final WidgetRef ref;
  AppRouter({required this.ref});

  @override
  RouteType get defaultRouteType => const RouteType.material();

  @override
  final List<AutoRoute> routes = [
    AutoRoute(page: AppPage.page, path: '/', guards: [ AuthGuard(ref) ]),
  ];
}
```
I get the error:
`The instance member 'ref' can't be accessed in an initializer.
Try replacing the reference to the instance member with a different expression`

I want to pass the instance member `ref` to AuthGuard. Bevore v6 this was possible since the Guard instance was passed with the parameter in the AppRouter constructor. Now that I have to pass the Guard instance inside AppRouter the parameter can't be passed.
What can I do?

**Comment by Milad-Akarie** [comment]
// add late
late final List<AutoRoute> routes = [
    AutoRoute(page: AppPage.page, path: '/', guards: [ AuthGuard(ref) ]),
  ];

**Comment by dario-digregorio** [comment]
oh did not know I could do that with overrides. Thanks!
