### ISSUE TITLE
Can not resolve initial route

### ISSUE THREAD

**Issue by il2be97** [Milad-Akarie/auto_route_library#1477]
In new version, i haven't seen initial parameter in auto router and when run app it product me an Error: Can not resolve initial route

<img width="555" alt="Снимок экрана 2023-04-10 в 17 57 44" src="https://user-images.githubusercontent.com/34628268/230927541-c74fe714-8ff4-44f9-8ac4-06baee036a13.png">
<img width="489" alt="Снимок экрана 2023-04-10 в 17 57 51" src="https://user-images.githubusercontent.com/34628268/230927545-1f1a3064-400c-4ee7-98a2-78c90e0a9a7a.png">

<img width="762" alt="Снимок экрана 2023-04-10 в 17 59 51" src="https://user-images.githubusercontent.com/34628268/230927611-b050efc0-93ee-49c4-8519-01739a55e0bc.png">

**Comment by il2be97** [comment]
need add initial path

**Comment by Milad-Akarie** [comment]
@il2be97 yes, you need to add it, `AutoRoute(page: Home.page, path: '/')`

**Comment by octobocto** [comment]
> AutoRoute(page: HomeRoute.page, initial: true),
> and not with this:
> 
> AutoRoute(page: HomeRoute.page, path: '/'),
> This is my `flutter doctor` and I use `auto_route: ^10.0.1` in my project:

This was not enough for me FYI. I also needed to add this to make android work:

```
// Catch-all for deep links - redirect unknown paths to start
RedirectRoute(path: '*', redirectTo: '/'),
```
