### ISSUE TITLE
Pass arguments to children of EmptyRouterPage

### ISSUE THREAD

**Issue by davies-maina** [Milad-Akarie/auto_route_library#1483]
I have the following setup:
```
AutoRoute(
          name: 'ActivityDetailsRoute',
          page: EmptyRouterPage,
          children: [
AutoRoute(
              path:'',
              page:  ActivityDetails,),
]
```
The 'ActivityDetails' page receives an argument but how do I pass it from  'ActivityDetailsRoute'?

**Comment by Milad-Akarie** [comment]
@davies-maina Is there a reason why you can't pass it directly to `ActivityDetails`?
something like this? 

`context.push(ActivityDetailsRoute(children: ActivityDetails(args)))`

although  that looks like a valid case for a new feature I've been thinking about (inherited arguments)
