### ISSUE TITLE
Can not resolve initial route

### ISSUE THREAD

**Issue by yutech23** [Milad-Akarie/auto_route_library#1484]
When I enter a random address, it throws the error 'can not resolve initial route' in new version. (auto_route 6.1.0)

for example 
![image](https://user-images.githubusercontent.com/42283661/231492577-574f01de-ff8b-4de0-9c4f-1cd7615a2b14.png)
 this address not my route.

Error: Can not resolve initial route
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/auto_route/src/router/controller/auto_router_delegate.dart 83:7                                                   setInitialRoutePath
packages/flutter/src/widgets/router.dart 716:32                                                                            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/flutter/src/widgets/router.dart 712:15                                                                            <fn>

MY CODE
![image](https://user-images.githubusercontent.com/42283661/231494084-15e97bd8-c707-4bb5-bf2c-e64e619c4e8d.png)

NOTE: 
![image](https://user-images.githubusercontent.com/42283661/231494284-fa29ddca-987d-48b1-8f55-5a061ce6aab9.png)

**Comment by Milad-Akarie** [comment]
That's the very initial path and it can not resolve it, makes total sense, if you for example want any invalid route to redirect to home you can do add a redirect route at the end of your routs list
RedirectRoute(path:'*', redirectTo: '/')
Or if you want to display a 404 page
AutoRoute(path: '*', page:MyNotFoundRoute.page)

Hope that makes sense
