### ISSUE TITLE
how to impelemnt splash page with a route other than '/' 

### ISSUE THREAD

**Issue by maxzod** [Milad-Akarie/auto_route_library#1485]
since home page takes `/` as path 
I need to make the splash page is a initial page without make her path a `/`

**Comment by Milad-Akarie** [comment]
Hey @maxzod  I always use and recommend using a native splash screens 
https://docs.flutter.dev/development/platform-integration/android/splash-screen
but if you for some reason need to use a flutter splash screen
you can do something like this

```dart
    
  AutoRoute(
      path: '/',
      page: HomeRoute.page,
      guards: [
        AutoRouteGuard.simple((resolver, _) {
         // calling resolve.next() will resume navigation to HomeRoute
          push(SplashRoute(onReady: ()=> resolver.next()));
     
        }),
      ],
    ),
 // set keep history to false so it's removed from stack when home route is pushed
 AutoRoute(page: SplashRoute.page, keepHistory: false),
```

**Comment by mirland** [comment]
In this case, cannot you use a redirect route too? Milad gave me this idea some time ago

```
    RedirectRoute(path: '/', redirectTo: '/splash'),
    AutoRoute(page: SplashRoute.page, keepHistory: false, path: '/splash',),
```

I think it's another alternative 😄

**Comment by maxzod** [comment]
i need the splash page within Flutter to initialize some modules and take a return value from them
buy using both the answers above I think this would show a splash page every time I push to home 


I am afraid we have introduced new limitation with the new version 
previously I could set the initial page in a separate parameter other than the path!

**Comment by Milad-Akarie** [comment]
@maxzod what `initial` did in previous versions is add a redirect route from `/` to the target path when provided path is not `/` so nothing actually changed

**Comment by maxzod** [comment]
@Milad-Akarie I am new to this package, but seeing the migration guide this is the first thing to come to me head
