### ISSUE TITLE
[Question] Is it still possible to generate more routes for one page in v6?

### ISSUE THREAD

**Issue by stijnie2210** [Milad-Akarie/auto_route_library#1491]
In v5 I used to generate multiple routes for one page to pass different kinds of meta information to it like this:

```dart
AutoRoute(
  page: TestPage,
  meta: {
    trackingId: 1,
  },
),
AutoRoute(
  page: TestPage,
  meta: {
    trackingId: 2,
  },
),
```

Since v6 now requires you to annotate your page I no longer see a possibility to do this. Is there something in the documentation I have missed or has this purposely been removed?

**Comment by Milad-Akarie** [comment]
Hey @stijnie2210 ya that's not possible now, but still how are you supposed to navigate to the right page if you're not using different route names?

**Comment by stijnie2210** [comment]
@Milad-Akarie I meant to add different `name` parameters in my example, sorry :D. 

Your example might work, i'll give that a shot in my migration

**Comment by AAverin** [comment]
I had a very complex screen that I was reusing in v5 in 3 different parts of the app, by using different names.
Is wrapping with another class the right way to do the same in v6?
