### ISSUE TITLE
Flutter web - The splash screen always loads when I go back to home 

### ISSUE THREAD

**Issue by ranulfo** [Milad-Akarie/auto_route_library#1494]
this package works perfectly on mobile but on flutter web i am noticing that it loads the splashscreen page every time i return to home using browser page back click. how do i solve this? I'm using the animated_splash_screen package to create the splash screen.
thanks in advance

**Comment by Milad-Akarie** [comment]
@ranulfo I'm gonna need some more info on this, how's your router setup? and how your initing your router?

**Comment by ranulfo** [comment]
> @ranulfo I'm gonna need some more info on this, how's your router setup? and how your initing your router?

The initial call looks like this:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setPathUrlStrategy();
  await initParse();
  setupLocators();
  runApp(DevicePreview(builder: (_) => SplashScreen(), enabled: false));
}
```

Inside the splashscreen I call my app normally:

```
class _SplashScreenState extends State {
  Widget? body;

  @override
  Widget build(BuildContext context) {
    return _body(context);
  }

  Widget _body(BuildContext context) {
    /* WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
      await Future.delayed(Duration(seconds: 3));
      Navigator.of(context).pop();
    });*/
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: customPrimrarySwatch,
      ),
      home: AnimatedSplashScreen(
        duration: 3000,
        splashTransition: SplashTransition.fadeTransition,
        splash: "assets/images/logo.png",
        nextScreen: MyApp(),
        //nextRoute: Routers.home,
      ),
    );
  }
...
}
```

The route is configured like this:

```
 final List routes = [
CustomRoute(
        path: "/",
        page: HomeScreen.page,
        transitionsBuilder: Routers.transitionType,
        durationInMilliseconds: Routers.transitionDelay,
        guards: [MaintenanceGuard()]),
       ...
]

```
Note: SplashScreen is not configured inside the route but I already tried to include it but the behavior was the same

**Comment by Milad-Akarie** [comment]
@ranulfo where are you passing router configuration to MaterialApp?

**Comment by ranulfo** [comment]
> @ranulfo where are you passing router configuration to MaterialApp?

this away:

`class MyAppState extends State<MyApp> {
  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return Sizer(builder: (context, orientation, deviceType) {
      return MaterialApp.router(
        routerConfig: _appRouter.config(),
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: customPrimrarySwatch,
        ),
        ...
        }
    }
}`

**Comment by ranulfo** [comment]
> @ranulfo where are you passing router configuration to MaterialApp?

this way:
```

class MyAppState extends State {
  final _appRouter = AppRouter();

  @OverRide
  Widget build(BuildContext context) {
        return Sizer(builder: (context, orientation, deviceType) {
            return MaterialApp.router(
            routerConfig: _appRouter.config(),
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
                    primarySwatch: customPrimrarySwatch,
             ),
...
       }
    }
}
```

**Comment by abasu0713** [comment]
this is still an issue.
