### ISSUE TITLE
Navigating using root router will remove the nested routes from the stack.

### ISSUE THREAD

**Issue by hasanmhallak** [Milad-Akarie/auto_route_library#1495]
This is the router configurations:

```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  RouteType get defaultRouteType => const RouteType.cupertino();

  @override
  List<AutoRoute> get routes => [
        AutoRoute(path: '/addVideo', page: AddVideoRoute.page),
        //? Main
        AutoRoute(
          path: '/main',
          page: MainRoute.page,
          maintainState: false,
          children: [
            // this is to open the home route as initial.
            RedirectRoute(path: '', redirectTo: 'home'),
            AutoRoute(
              path: 'home',
              page: HomeRoute.page,
              maintainState: false,

            AutoRoute(
              path: 'profile',
              page: ProfileRoute.page,
              maintainState: false,
            ),
          ],
        ),
      ];
}

```

Now if we use
```dart
context.router.root.push(AddVideoRoute());
```

it will lead to pop the Main Route from the routeStack. this issue appears when migrating to v6

**Comment by Milad-Akarie** [comment]
Hey @hasanmhallak Where is your  router iniailised and where are you navigating from?

**Comment by hasanmhallak** [comment]
Hey @Milad-Akarie thanks for the quick response.
The router is initialized in the initState method of the widget that contains the `MaterialApp()`
I tried to navigate from within the nested route and form outside the nested route and it's the same.

The weird thing is the `AddVideoRoute` back button will navigate back to the `MainRoute` whether I navigate using `context.popRoute` or using `Navigator.of(context).maybePop()` even though I don't see the `MainRoute` in widget inspector, but it looks like the router will re-push the `MainRoute` because the state is lost.

**Comment by Milad-Akarie** [comment]
@hasanmhallak are you sure you're not initing the router inside of a build method? Can you check whether the router is reinitiating by logging its hashcode?

**Comment by hasanmhallak** [comment]
@Milad-Akarie I've just logged the hashCode and it only logged it once, as it's in the init state.
```dart
  @override
  void initState() {
    _appRouter = AppRouter();
    isFirstTime = ref.read(onBoardingFirstRunProvider);
    initRoute = ref.read(authNotifierProvider).when(
      unAuthenticated: () {
        if (!isFirstTime) {
          return const MainRoute();
        } else {
          return const OnBoardingRoute();
        }
      },
      authenticated: (_) {
        return const MainRoute();
      },
      needVerification: (_) {
        return OtpRoute(phoneNumber: _.phoneNumber, canPop: false);
      },
    );
    print(_appRouter.hashCode);
    super.initState();
  }

```

**Comment by Milad-Akarie** [comment]
Not sure whats going on! 

Can you build a small repo that reproduces this? 

Btw you better use an AutoRouteGuard on your main route

The way you handle initial route not will conflict with deeplinks

**Comment by hasanmhallak** [comment]
@Milad-Akarie I know that I just wrote it in a rush and told myself I'll refactor it later :p but thanks for the tip.

I'll write small example and add the code here.

**Comment by Milad-Akarie** [comment]
Wait just realized something 
Try making your main route path '/'

**Comment by hasanmhallak** [comment]
still the same. I've almost finish writing the example

**Comment by hasanmhallak** [comment]
@Milad-Akarie hey, I just figure out the problem after I wrote example. 
It looks like I accidentally set `maintainState` to false on the `MainRoute` 
```dart
AutoRoute(
          path: '/Main',
          page: MyHomeRoute.page,
          maintainState: false,          // here
          children: [
            RedirectRoute(path: '', redirectTo: '1'),
            AutoRoute(
                path: '1', page: NestedOneRoute.page, maintainState: false),
            AutoRoute(
                path: '2', page: NestedTwoRoute.page, maintainState: false),
          ],
        ),
```

which resulted to the route being removed on push, and re inserted back on pop.
Sorry for that and thank you for your time.
