### ISSUE TITLE
Error "The method `pushReplacementNamed` was called on null." when using `ExtendedNavigator.root`.

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/auto_route_library#150]
I have everything setup in my `main.dart` class.

```dart
return MultiBlocProvider(
  providers: [
    BlocProvider.value(value: authBloc..add(InitializeAuthBloc())),
  ],
  child: MaterialApp(
    debugShowCheckedModeBanner: false,
    onGenerateRoute: Router(),
    builder: (context, child) {
      return ScrollConfiguration(
        behavior: NoGlowScroll(),
        child: ExtendedNavigator(router: Router()),
      );
    },
  ),
);
```

I'm trying to push a new route based on whether or not the user is authenticated but `root` in `ExtendedNavigator#root` is null for some reason. Why would this be?

I have an initial route which is just a page with a loading indicator which will push either the login screen or the home screen.

**Comment by Milad-Akarie** [comment]
@Reprevise Where are you pushing the route from?

**Comment by Reprevise** [comment]
This is from the initial route. The initial route's existence is just to decide whether or not a user should go to the home screen or the login screen.

**Comment by Milad-Akarie** [comment]
first of all @Reprevise only assign Router() to onGenerateRoute if you're not using ExtendedNavigator.
Where are you assigning the initial route in your code?

**Comment by Reprevise** [comment]
Removing the `onGenerateRoute` parameter of `MaterialApp` worked, thanks!
