### ISSUE TITLE
What is the correct approach to navigate between two inner routes.

### ISSUE THREAD

**Issue by Floul** [Milad-Akarie/auto_route_library#1501]
Here is a scheme of the behavior I expect.
<img width="885" alt="image" src="https://user-images.githubusercontent.com/43589361/232897587-cd154fa9-4576-4cd8-aaac-d702480e58a5.png">

**Expected behavior.** I have a product screen. Let's say it's one of the most important pages in my app. Normal way to get to this screen - click in a product at the ProductListPage. Also I would like to be able to get there from my user profile when I click on products I liked/viewed/bought/e.t.c. There should be other screen, that also need to get to the product page and it sub-pages (P. Details and P. Options). 

**Issues.** Unfortunately I can’t just call .push(ProductPage) anywhere I want, because it will cause an error, says "You adding a child, but not adding it's parent.". If I add all the parents with it I will get another problem - .pop() wont get me back to where I've been before I got to the ProductPage.

**Question.** So how to navigate between inner routers of different navigation branches and don’t break the .pop() behavior? Sure, I can just copy-paste ProductPage and it sub-pages, but I don't think that this approach is reliable.

**Comment by realitymolder** [comment]
did you find a solution?

**Comment by Floul** [comment]
@realitymolder no. The only "solution" I have - copy-paste an entire sub-branch.
