### ISSUE TITLE
How to remove stack until first root ?

### ISSUE THREAD

**Issue by Aina27** [Milad-Akarie/auto_route_library#1506]
I want to remove stack until root using  `router.removeUntil((routeData) => //TODO);` but there is no `routeData.isFirst`

In my case, i don't want to use popUntil because i don't want a call on didPop observer .
How can i manage to do this

**Comment by Milad-Akarie** [comment]
Try this
router.removeUntil((_)=> router.pagesCount == 1

**Comment by Aina27** [comment]
solve this using `stackData` : 
` removeUntil((routeData) => routeData == stackData.first);`
