### ISSUE TITLE
Generate arguments with private positional parameters 

### ISSUE THREAD

**Issue by essarn** [Milad-Akarie/auto_route_library#151]
The generator always generates named parameters for arguments regardless if they were named, optional or positional. If private positional parameters are present will the generated code be invalid since named parameters cannot start with an underscore.

**Comment by Milad-Akarie** [comment]
@essarn hmm it will in the next build.

**Comment by Milad-Akarie** [comment]
handled in version auto_route_generator: 0.6.3
Thanks for reporting
