### ISSUE TITLE
How to access the meta map in router observer?

### ISSUE THREAD

**Issue by Coffiie** [Milad-Akarie/auto_route_library#1510]
I have a `router.dart` file with the following setting:
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Tab',
  routes: <AutoRoute>[
    AutoRoute(path: 'splash', page: SplashPage, initial: true),
    AutoRoute(
        path: 'login', page: LoginPage, meta: {'trackingName': 'Login Page'}),
        ]
        );
```

here, I add `trackingName` param to the meta map so that whenever a route is pushed/popped, I can send tracking data for the screen change.

In `main.dart` I create a RouterObserver so that I can have callbacks to all the push/pops like so:
```
MaterialApp.router(
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        debugShowCheckedModeBanner: false,
        locale: context.locale,
        routerDelegate: AutoRouterDelegate(
          router,
          navigatorObservers: () => [
            locator<FirebaseAnalyticsService>().observer,
            locator<RouterObserver>(),
          ],
        ),
        routeInformationParser: router.defaultRouteParser(),
      ),
```
      
      
In Router Observer class Im trying to access the meta map property so I can call the relevant tracking function. However, I am unable to find it.

```
class RouterObserver extends AutoRouterObserver {
  RouterObserver();

  @override
  void didPush(Route route, Route? previousRoute) {
    log(
      'New route pushed: ${route.navigator.widget.}',
    );
//call tracking method here with route.something.meta['trackingName'];
  }

}

class $AppRouter {}
```

How do I access this? Or is there another elegant way to log the tracking names like 'Login Page Viewed' etc from the methods to the tracking function?

in Pubspec.yaml:

```
dependencies:
  auto_route: ^5.0.2

dev_dependencies:
  auto_route_generator: ^5.0.2
```

**Comment by Milad-Akarie** [comment]
Hey @Coffiie, for now you'd need to cast t AutoRoutePage to get the data, I'm thinking we could have a more elegant way to handle this, I don't know If I should work on it thu because the flutter team is looking to change the current navigation observer. 
```dart
 @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    final page = route.settings;
     if(page is AutoRoutePage){
       page.routeData.meta;
     }
  }
```
maybe such an extension is enough 

```dart
extension RouteX<T> on Route<T>{
  RouteData? get data {
    if(settings is AutoRoutePage){
      return (settings as AutoRoutePage).routeData;
    }
    return null;
  }
}
```
so now you can go `route.data?.meta`

of course this will no work on pageless routes like dialogs and bottom sheet modals or any non auto-routes.

**Comment by Coffiie** [comment]
Hi @Milad-Akarie
Thanks for your reply and the solution. So will we have to refactor again after current navigation is changed by flutter? Or this solution works irrespective of that change?
