### ISSUE TITLE
V6  work with  modules

### ISSUE THREAD

**Issue by holyboom1** [Milad-Akarie/auto_route_library#1512]
After upgrading to v6 we are  lost ability to work with modules like this
![image](https://user-images.githubusercontent.com/65105446/234003861-c13825c2-339e-486b-afef-84d2bd82589e.png)
![image](https://user-images.githubusercontent.com/65105446/234004064-c090a7fe-9044-44c9-ac75-8f8a4d91e3da.png)
![image](https://user-images.githubusercontent.com/65105446/234004104-02c9e394-a5be-4f68-a9ac-cb78189b2309.png)

How we can resolve it?

**Comment by definitelyme** [comment]
Any update on this? @Milad-Akarie
