### ISSUE TITLE
Inconsistent code generation

### ISSUE THREAD

**Issue by ookami-kb** [Milad-Akarie/auto_route_library#1513]
Hey, I've noticed that the generated code can be inconsistent in terms of the order of the classes, import aliases etc. Is it the result of some parallelization or just inconsistent order of files from analyzer?

It's pretty annoying if the generated files are kept in VCS – it can result in useless changes in the file. Is there some way to make it consistent (I would be fine to have longer build times with some flag "keep consistent order").

**Comment by Milad-Akarie** [comment]
@ookami-kb
Yup, there's not telling what files to be processed first by `build_runner`.
 maybe we can try sorting pages alphabetically, not sure if that's gonna fix the problem thu.
