### ISSUE TITLE
[Suggestion] [Question?] fallback route for initial deeplink.

### ISSUE THREAD

**Issue by hasanmhallak** [Milad-Akarie/auto_route_library#1516]
when we push a route using `router.push()` there is a callback on navigation failure.
It would be nice if there is an onFailure callback in `StackRouter.config()` on which we would fallback into if there is no callback provided on `push`.

This would be very useful especially with deeplinking as we don't have to handle all the route cases if the user try to play the with the link. in this case if the deeplink path was corrupted we navigate the user to 404 route or what ever.

The route controller already use `pushNamed` under the hood if we provide an `initialDeepLink` here:
```dart
  @override
  Future<void> setInitialRoutePath(UrlState configuration) {
    // setInitialRoutePath is re-fired on enabling
    // select widget mode from flutter inspector,
    // this check is preventing it from rebuilding the app
    if (controller.hasEntries) {
      return SynchronousFuture(null);
    }

    if (initialRoutes?.isNotEmpty == true) {
      return controller.pushAll(initialRoutes!);
    } else if (initialDeepLink != null) {
      return controller.pushNamed(initialDeepLink!, includePrefixMatches: true);    //  <----- here
    } else if (configuration.hasSegments) {
      _onNewUrlState(configuration);
      return controller.navigateAll(configuration.segments);
    } else {
      throw FlutterError("Can not resolve initial route");
    }
  }
```

so I guess it would be easy to handle this case.

**Comment by Milad-Akarie** [comment]
@hasanmhallak I think what we need here is a platform-deep link validator? 
something like this 
```dart
appRouter.config(onDeepLink:(List<PageRouteInfo> routes){
       // all good 
      return routes;
      // else return null for default behavior (as if we didn't start from deep-link)
      return null
      // or redirect
      return  [SomeOtherRoute()];
  })
```
what do you think?

**Comment by hasanmhallak** [comment]
@Milad-Akarie this looks great. But I don't think you need to return `null` for the default behavior as I noticed if the `routes` list was empty or if we pass an empty `initialRoutes` list to the config function. it will automatically pick up the initial route provided by the `/` path. I don't know if this intended or but I tested it many times and it always picked up the initial route

**Comment by Milad-Akarie** [comment]
@hasanmhallak '/' is considered the default initial deep-link.
I've been thinking about manual deep-link handling ever since deep-linking was automatically handled by `Material.router`
I think it's better to deprecate `initialDeepLink` and `InitialRoutes` and give the users one place to build their initial deep-links while being aware of the resolved links coming from the platform (routes)

I'm thinking something like this...
```dart
appRouter.config(deepLinkBuilder:(List<PageRouteInfo> routes){
       return DeepLink(routes);
       return DeepLink.fromPath('path'):
       return Deeplink.none;
  })

```

**Comment by hasanmhallak** [comment]
@Milad-Akarie I think you're right, with this ability developers can have much more freedom to handle different use-cases especially if they have `intent-filter`s that have some complex logic. I think you should take a vote before deprecation maybe other developers has more approaches regarding this matter.

**Comment by Milad-Akarie** [comment]
@hasanmhallak  in most cases uses will not need to use the `deepLinkBuilder',  I don't think  the new suggested approach can not handle any previous approach done by `initialDeepLink` or `initialRoutes`  properties,  do you?

**Comment by hasanmhallak** [comment]
@Milad-Akarie  yes of course, it's basically the same but with much more flexibility.

**Comment by Milad-Akarie** [comment]
@hasanmhallak done in the new version 6.4.0
https://pub.dev/packages/auto_route#deep-linking

```dart
  MaterialApp.router(
      routerConfig: _appRouter.config(
        deepLinkBuilder: (deepLink){
          if(deepLink.path.startsWith('/products'){
           // continute with the platfrom link
            return deepLink;
          }else{
            return DeepLink.defaultPath;
            // or DeepLink.path('/')
            // or DeepLink([HomeRoute()])
          }
        }
      ),
    )
```
consider closing this if the fix works for you

**Comment by hasanmhallak** [comment]
@Milad-Akarie it actually did. Thank you.

closing this in regards of #1522
