### ISSUE TITLE
NestedNavigator() instantiation problem

### ISSUE THREAD

**Issue by wer-mathurin** [Milad-Akarie/auto_route_library#152]
Hi,

I just found that if the parent guard list is null it will throw an exception.
To recreate the problem.
`ExtendedNavigator<Router>(
              router: Router(),
            ),`

If you attempt to instantiate NestedNavigator() in a nested route it will throw an exeption.

The workaround:
`ExtendedNavigator<Router>(
              router: Router(),
              guards: [],
            ),`

**Comment by Milad-Akarie** [comment]
@wer-mathurin  noted.. fix will be pushed soon!
Thanks for reporting!

**Comment by TheHemantKaushik** [comment]
Hi @wer-mathurin @Milad-Akarie 

Is this the error you guys are talking about?

`The following JSNoSuchMethodError was thrown building NestedNavigator(dirty, dependencies: [_ModalScopeStatus]):
TypeError: parentNav.guards is not iterable`

**Comment by wer-mathurin** [comment]
On my side I'm getting.
I/flutter ( 3060): The getter 'iterator' was called on null.
I/flutter ( 3060): Receiver: null
I/flutter ( 3060): Tried calling: iterator
I/flutter ( 3060):
I/flutter ( 3060): The relevant error-causing widget was:
I/flutter ( 3060): NestedNavigator

To resolve the issue is simple as
Adding the null check operator on the spread operator in the
extended_navigator.dart

in the build method
...?parentNav.guards,

**Comment by mrruby** [comment]
Same story here, the workaround worked

**Comment by Milad-Akarie** [comment]
Fixed in auto_route: 0.6.2 
**Note:** NestedNavigator is an ExtendedNavigator without a router now
Thanks for reporting
