### ISSUE TITLE
Generating routes inside packages/ folder

### ISSUE THREAD

**Issue by patrikbadanjak** [Milad-Akarie/auto_route_library#1520]
I have the following project structure, don't ask why, it's out of my control.

```
my-app
├── lib
│   ├── main.dart
│   ├── router.dart
│   └── login_page.dart
└── packages
    └── feature_a
        └── some_page_a.dart
```

Is it possible to generate a route for **some_page_a.dart** from **router.dart**? I thought ```@AutoRouterConfig(generateForDir: ['lib', 'packages/feature_a'])``` would do it, but it didn't. From what I read and understood in #1380, I could make a router inside each feature package and make my main router depend on it but I was hoping there was a cleaner way.

**Comment by Milad-Akarie** [comment]
@patrikbadanjak I'm still trying to figure something out regarding this.

**Comment by patrikbadanjak** [comment]
What's the use case for `generateForDir` property?

**Comment by Milad-Akarie** [comment]
@patrikbadanjak this is useful in case you want to have two root routers in same package

**Comment by jtdLab** [comment]
Is it technically possible with `build_runner`/`source_gen` to introduce like a `generateForPackage` property and generate routing code based on those other packages ?

**Comment by Milad-Akarie** [comment]
@jtdLab I'm working on something..

**Comment by Milad-Akarie** [comment]
@patrikbadanjak @jtdLab following the docs here should help you configure your micro-packages
https://pub.dev/packages/auto_route#including-micro-packages

let me know if anything goes wrong

**Comment by jtdLab** [comment]
@Milad-Akarie looks promising for cases where the are in a subdir of the package the code generator runs.

I got a setup like this, where the solution does not work. 

I get a: Invalid argument (Asset paths may not reach outside the package.)

```
router
├── lib
│   ├── router.dart
page_a
├── lib
│   ├── page_a.dart
page_b
├── lib
│   ├── page_b.dart
```

**Comment by patrikbadanjak** [comment]
> https://pub.dev/packages/auto_route#including-micro-packages
Don't know how I missed this, but it looks to be the solution to my problem. I'll let you know if it worked once I get back to it.

**Comment by jtdLab** [comment]
@Milad-Akarie The current approach does not allow non subdir micro-packages and also requires a dependency on the root package when using (TabRouter etc) in a micro package because all `PageRouteInfo` objects are generated inside the root package. This dependency on the root package makes using multiple packages obsolete because the micro-package now has implicit dependencies on all other micro-packages.

This could be solved by:

1. Generate the `PageRouteInfo` objects inside the package of the associated page.
2. Merge them in the root package similar to `injectable`.

Root package:

```yaml
root_package
├── lib
│   ├── router.dart
│   ├── router.gr.dart
│   └── cool_page.dart
    // other pages
```

```dart
// router.dart
import 'router.gr.dart';

@AutoRouterConfig(
  microRoutes: [
    MyPackageMicroRoutes,
  ],
)
class Router extends $Router {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SomeRoute.page, path: '/'),
        AutoRoute(page: CoolRoute.page, path: '/cool'),
        // other routes go here
      ];
}
```

```dart
// router.gr.dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouterGenerator
// **************************************************************************

// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:auto_route/auto_route.dart' as _i1;
import 'package:my_package/routes.gr.dart' as _i2;
import 'package:root_package/cool_page.dart' as _i3;

// export micro package page infos
export 'package:my_package/routes.gr.dart' hide MyPackageMicroRoutes;

abstract class $Router extends _i1.RootStackRouter {
  $Router({super.navigatorKey});

  @override
  Map<String, _i1.PageFactory> get pagesMap => {
        ..._i2.MyPackageMicroRoutes().pagesMap,
        CoolRoute.name: (routeData) {
          return _i1.AutoRoutePage<dynamic>(
            routeData: routeData,
            child: const _i3.CoolPage(),
          );
        },
      };
}

/// generated route for
/// [_i3.CoolPage]
class CoolRoute extends _i1.PageRouteInfo<void> {
  const CoolRoute({List<_i1.PageRouteInfo>? children})
      : super(
          CoolRoute.name,
          initialChildren: children,
        );

  static const String name = 'CoolRoute';

  static const _i1.PageInfo<void> page = _i1.PageInfo<void>(name);
}
```

Micro package: 

```yaml
my_package
├── lib
│   ├── routes.dart
│   ├── routes.gr.dart
│   └── some_page.dart
    // other pages
```

```dart
// routes.dart
@AutoRouterConfig.microRoutes()
void initMicroRoutes() {}
```

```dart
// routes.gr.dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouterGenerator
// **************************************************************************

// ignore_for_file: type=lint
// coverage:ignore-file

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auto_route/auto_route.dart' as _i2;
import 'package:my_package/some_page.dart' as _i1;

class MyPackageMicroRoutes {
  Map<String, _i2.PageFactory> get pagesMap => {
        SomeRoute.name: (routeData) {
          return _i2.AutoRoutePage<dynamic>(
            routeData: routeData,
            child: const _i1.SomePage(),
          );
        },
        // other generated pages go here
      };
}

/// generated route for
/// [_i1.SomePage]
class SomeRoute extends _i2.PageRouteInfo<void> {
  const SomeRoute({List<_i2.PageRouteInfo>? children})
      : super(
          SomeRoute.name,
          initialChildren: children,
        );

  static const String name = 'SomeRoute';

  static const _i2.PageInfo<void> page = _i2.PageInfo<void>(name);
}

// other generated route infos go here

```

Runnable sample can be found here: https://github.com/jtdLab/auto_route_micro

**Comment by Milad-Akarie** [comment]
I guess this is  resolved thanks to @jtdLab
