### ISSUE TITLE
Generating complete URLs from routes in v6 - fullPath/path properties missing

### ISSUE THREAD

**Issue by katusiky** [Milad-Akarie/auto_route_library#1521]
With version 5 of the package, I had the following code to generate complete URLs from routes and thus prevent a path from being updated and leaving the displayed URLs in some views outdated:

```
String buildUrlFromRoute(PageRouteInfo route) {
  String url = '${Env.WEB_URL}${route.fullPath}?';

  route.rawQueryParams.forEach((key, value) {
    if (value != null) {
      url += '$key=$value&';
    }
  });

  if (url[url.length - 1] == '&' || url[url.length - 1] == '?') {
    url = url.substring(0, url.length - 1);
  }

  return url;
}
```

Since version v6, the fullPath and path properties have disappeared, and now I don't know how to achieve the same thing. Does anyone know if there is a new way to do this? Or if the fullPath/path properties will return in a future update?

**Comment by Milad-Akarie** [comment]
@katusiky  I had to make route declaration the only source of truth when it comes to paths.
You need to match your route to get a path now
```
router.match(route)?.fullPath
or route.match(context)?.fullPath
```
Why do you need to build a url like that I'm curious?
