### ISSUE TITLE
Children routes also need path param even when it is passed in parent route.

### ISSUE THREAD

**Issue by dhruv-js** [Milad-Akarie/auto_route_library#1524]
I was recently trying to migrate my project on Auto route 6 after which, all the children routes are giving me an error, asking for path parameter which is already passed in the parent route.

**Comment by NachiketaVadera** [comment]
Hey @Milad-Akarie. I'm also facing the same issue. Any solutions to this?

**Comment by jhionan** [comment]
Just 1 child can exist without path, and for it, you need to set 'initial=true'

**Comment by Milad-Akarie** [comment]
@NachiketaVadera after the refactor auto_route does not know how you would create your hierarchy, so you'd have to explicitly inherit the child path param, 

`(@PathParam.inherit('paramName') this.inheritedParam)`

**Comment by NachiketaVadera** [comment]
@Milad-Akarie I now see you've also mentioned this in the docs. Sorry and thanks!
