### ISSUE TITLE
Rebuild/Refresh TabsRouter Tab

### ISSUE THREAD

**Issue by FayozbekJumabekov** [Milad-Akarie/auto_route_library#1526]
Hi, i have a problem whit nested navigation. Here is my screens structures : 

          AppRoute(
          page: MainPage,
          initial: true,
          children: [

           /// Home Page
           AppRoute(
              page: HomePage,
              name: 'HomePageRouter',
            ),
           
           /// Cart Page
              AppRoute(
              page: CartPage,
              name: 'CartPageRouter',
              children: [
                AppRoute(
                  page: OrderPage,
                ),
                AppRoute(page: OrderConfirmationPage),
                AppRoute(
                    page: OrderStatusPage,
                ),
              ],
            ),
        ),

And I use AutoTabsScaffold. Problem is that, when i reach OrderStatusPage. I have a button namely "BACK TO HOME"
and when i press this button, i have to back home page. 

When i  use context.tabsRouter.stackRouterOfIndex(context.tabsRouter.activeIndex)?.popUntilRoot();

i back CartPage but problem is that my page is not rebuild, my textControllers and my Bloc which is responsible for this page should have recreated. But it is not what I expected.

How can i rebuild or refresh parent root as like opened for the first time???

**Comment by MartinAKovachev** [comment]
@FayozbekJumabekov Can you please try `router.replaceAll[HomePageRouter()]`?

**Comment by FayozbekJumabekov** [comment]
> @FayozbekJumabekov Can you please try `router.replaceAll[<the route to which you want to navigate>]`?

router.popForced() ; this came for help
