### ISSUE TITLE
Undefined class 'Key'

### ISSUE THREAD

**Issue by obrunsmann** [Milad-Akarie/auto_route_library#1528]
Generating for the following page

```dart
@RoutePage()
class InitialSetupScreen extends HookWidget {
  final _formKey = GlobalKey<FormBuilderState>();

  InitialSetupScreen({Key? key}) : super(key: key);
...
```

Creates an error
> Undefined class 'Key'.
> Try changing the name to the name of an existing class, or creating a class with the name 'Key'.

Generated code:
```dart
class InitialSetupRoute extends PageRouteInfo<InitialSetupRouteArgs> {
  InitialSetupRoute({
    Key? key,
    List<PageRouteInfo>? children,
  }) : super(
          InitialSetupRoute.name,
          args: InitialSetupRouteArgs(key: key),
          initialChildren: children,
        );
```

**Comment by ludovicroland** [comment]
Hello,

In the file in which one you have add the line : `part 'GENERATED_FILE.gr.dart';` you can add the import 
`import 'package:flutter/material.dart';`.

It will fix the issue.

**Comment by obrunsmann** [comment]
> In the file in which one you have added the line : `part 'GENERATED_FILE.gr.dart';` you can add the import `import 'package:flutter/material.dart';`.

Awesome thank you 😍

**Comment by Meshkat-Shadik** [comment]
> > In the file in which one you have added the line : `part 'GENERATED_FILE.gr.dart';` you can add the import `import 'package:flutter/material.dart';`.
> 
> Awesome thank you 😍

Instead of imporing whole material.dart I would suggest you to only import
```dart
import 'package:flutter/foundation.dart';
```
