### ISSUE TITLE
`deepLinkBuilder` is being called only on initial route

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1529]
The new `deepLinkBuilder ` is being called only on application cold start up (initial route). It doesn't handle a deep link, if the application is in background.
In the documentation is written: `Deep link builder is an interceptor for deep-links where you can validate or override deep-links coming from the platform`. 
We understand that it is a replacement of the `initialDeepLink` and `initialRoutes`, but it will be nice if `deepLinkBuilder` handles deep links from background/foreground as well. @Milad-Akarie

**Comment by Milad-Akarie** [comment]
@MartinAKovachev fair enough, I created `deepLinkBuilder` with only initial links in mind, this should be an easy fix, I'll handle this when I get back to work .. hopefully later tonight.

**Comment by Milad-Akarie** [comment]
@MartinAKovachev should be good in auto_route: ^7.0.0

**Comment by MartinAKovachev** [comment]
@Milad-Akarie The new solution looks nice. Thank you very much for the quick response and focus on this feature ❤️

**Comment by KarinBerg** [comment]
I'm a little confused at the moment about how the `deepLinkBuilder` works. Maybe @Milad-Akarie or @MartinAKovachev can help me out here.
Let's say I have the deep link `https://share.example.com/link` which should open a special page in my app (iOS/Android).
I added the `deepLinkBuilder` as mentioned in your documentation which should intercept any deep link with the path `/link` to open this special page.
Here come now my question: Do I still need a `AutoRoute` definition in the `AutoRouterConfig` class or is that not needed?

**Comment by Milad-Akarie** [comment]
@KarinBerg you only use the deepLinkBuilder to validate the linkds coming from platform, everything thing else should be the same.

**Comment by KarinBerg** [comment]
ok, that means I have to define a Route in the `AutoRouterConfig` class otherwise deepLinkBuilder is not called. That corresponds to my observations. What I still do not understand is why the link `https://share.example.com/link` is working when I define a `RedirectRoute(path: '/link', redirectTo: '/main/map')` but not if I define a normal `AutoRoute(page: HtmlViewRoute.page, path: '/link')`. 

```
@override
  List<AutoRoute> get routes => [
        AutoRoute(
          page: SplashRoute.page,
          initial: true,
        ),
        AutoRoute(
          page: HtmlViewRoute.page,
          path: '/link',
        ), // Is not working => Page is not shown and deepLinkBuilder is not called
        RedirectRoute(
          path: '/link',
          redirectTo: '/main/map',
        ), // Is working
        AutoRoute(
          page: MainRoute.page,
          path: '/main',
          children: [
            AutoRoute(
              page: MapRouter.page,
              path: 'map',
              children: [
                AutoRoute(
                  page: MapRoute.page,
                  initial: true,
                ),
              ],
            ),
            AutoRoute(
            ...
```
Could you give me a hint?

**Comment by Milad-Akarie** [comment]
@KarinBerg that is not an expected behavior there must be something wrong, deepLinkBuilder should be called regardless

**Comment by KarinBerg** [comment]
What I can add is the following observation:

In the class `auto_router_delegate.dart` there is a method `setNewRoutePath`. This is the place where you decide to call the `deepLinkBuilder` or not. 
When using the `RedirectRoute` `configuration.hasSegments` is true and the `deepLinkBuilder` is called.
When using the `AutoRoute ` `configuration.hasSegments` is false and the `deepLinkBuilder` is not called.

What I do not understand so far is why I have no segments when using then `AutoRoute`???

I know I do something wrong but still not sure what?

**Comment by KarinBerg** [comment]
ok, now I know what I did wrong: 

What my code from above did not show was that I have a second `AutoRoute` on the page `HtmlViewRoute.page`. Like this:

```
@override
  List<AutoRoute> get routes => [
        AutoRoute(
          page: SplashRoute.page,
          initial: true,
        ),
        AutoRoute(
          page: HtmlViewRoute.page,
          path: '/link',
        ), // Is working when I comment out the second AutoRoute on page: HtmlViewRoute.page
        // AutoRoute(
        //   page: HtmlViewRoute.page,
        // ),
        AutoRoute(
          page: MainRoute.page,
          path: '/main',
          children: [
            AutoRoute(
              page: MapRouter.page,
              path: 'map',
              children: [
                AutoRoute(
                  page: MapRoute.page,
                  initial: true,
                ),
              ],
            ),
            AutoRoute(
            ...
```
If I comment out the second `AutoRoute` the `deepLinkBuilder` is passed for `https://share.example.com/link`

But I can't tell if that behaviour is expected or a bug.

**Comment by lironzemingo** [comment]
@Milad-Akarie I cannot seem to get deepLinkBuilder to be called when app is in the background, and opening from a deeplink. it is called only on app launch.
links are not universal. my scheme is `mybash://`
example links: 
- mybash:// 
- mybash://bash

what am I missing?

`@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(
          page: HomeRoute.page,
          initial: true,
          path: '/'
        ),
        AutoRoute(
          page: MockBashRoute.page,
          path: '/bash'
        ),
      ];
}`

`        return MaterialApp.router(
          routerConfig: router.config(
            deepLinkBuilder: (deepLink){
              Fimber.i("deepLink");
              return deepLink;
            }
          ),
          localizationsDelegates: context.localizationDelegates,
          supportedLocales: context.supportedLocales,
          locale: context.locale,
          title: 'MyBash',
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
            useMaterial3: false,
          ),
          debugShowCheckedModeBanner: false,
        );`
