### ISSUE TITLE
 It does not work if you pushpeeplink 2 numbers through the route of NestedRouter

### ISSUE THREAD

**Issue by qjatjr1108** [Milad-Akarie/auto_route_library#153]
hi mliad! 
I'm using your router package well :)

Below is my router
```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AdaptiveRoute(page: DevRouteHomeScreen, initial: true),
    AdaptiveRoute(
      path: '/users/:id',
      page: DevUsersScreen,
      children: [
        AdaptiveRoute(path: '/', page: DevProfileScreen),
        AdaptiveRoute(path: '/posts_one', page: DevPostsScreen1),
        AdaptiveRoute(path: '/posts_one/posts_two', page: DevPostsScreen2),
      ],
    ),
    
    AdaptiveRoute(path: '*', page: UnknownScreen),
  ],
)
```

On the DevRouteHomeScreen screen 
When called, it moves well on the first attempt.
`ExtendedNavigator.of(context).pushDeepLink('/users/2/posts_one/posts_two', queryParams: queryParams);`

However, from the second attempt, the following error occurs.

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3404 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3404:12)
#3      ExtendedNavigatorState._pushAllGuarded (package:auto_route/src/extended_navigator.dart:182:11)
<asynchronous suspension>
#4      ExtendedNavigatorState._pushDeepLink (package:auto_route/src/extended_navigator.dart:219:12)
#5      ExtendedNavigatorState._pushDeepLink (package:auto_route/src/extended_navigator.dart:214:22)
#6      ExtendedNavigatorState.pushDeepLink (package:auto_route/src/extended_navigator.dart:203:17)
#7      DevRouteHomeScreen.build.<anonymous closure> (package:bleet/view/dev/route_sample/dev_route_sample_home_screen.dart:37:22)
#8      _InkResponseState._handleTap (<…>
flutter: Pushing /users/2/
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3404 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3404:12)
#3      ExtendedNavigatorState._pushAllGuarded (package:auto_route/src/extended_navigator.dart:182:11)
<asynchronous suspension>
#4      ExtendedNavigatorState._pushDeepLink (package:auto_route/src/extended_navigator.dart:219:12)
#5      ExtendedNavigatorState._pushDeepLink (package:auto_route/src/extended_navigator.dart:214:22)
#6      ExtendedNavigatorState.pushDeepLink (package:auto_route/src/extended_navigator.dart:203:17)
#7      DevRouteHomeScreen.build.<anonymous closure> (package:bleet/view/dev/route_sample/dev_route_sample_home_screen.dart:37:22)
```

**Comment by Milad-Akarie** [comment]
Hey @qjatjr1108 ya I've been working on that. Native Navigator devs  prevented calling push and friends within push and friends for some reason!
Any ways this whole deep linking approach turned out to be a failure. I'm pushing a cleaner approach that works! tonight or tomorrow at most so stay tuned.

**Comment by Milad-Akarie** [comment]
My apologies, This took a little longer than I expected. unfortunately I've hit some limitations when it comes to pushing deep links using an ExtendedNavigator  and I had to introduce a new Widget called (AutoRouter) that works as a wrapper for the native navigator. I'm still figuring out how to deprecate the existing ExtendedNavigator and replace it with the new AutoRouter widget.

**Comment by qjatjr1108** [comment]
Thank you for confirming this problem deeply. I will be waiting for you to solve the problem at any time.

**Comment by Milad-Akarie** [comment]
Hey @qjatjr1108   check out the new version 0.6.2
be sure to replace NestedNavigator with a regular ExtendedNavigator without a router and use the regular push method the push your nested routes.

**Comment by qjatjr1108** [comment]
@Milad-Akarie 
Hello, I changed the Nested Navigation to Extended Navigator in Milad new version 0.6.2, so the deep link seems to work well!!
The page is added to the routeMap I was expecting, and it is different from moving, but in the current solution, I am satisfied!

Thanks so much for the quick fix
