### ISSUE TITLE
After handling a `deepLink` the route stack is not recreated from scratch

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1530]
Let's say we have this structure:

```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  final List<AutoRoute> routes = [
    AutoRoute(
      page: MainRoute.page,
      path: '/',
      children: [
        RedirectRoute(
          path: '',
          redirectTo: 'home',
        ),
        AutoRoute(
          page: HomeRoute.page,
          path: 'home',
         ),
      ],
    ),
    AutoRoute(
      page: InfoRoute.page,
      path: '/info',
    ),
    RedirectRoute(
      path: '*',
      redirectTo: '/',
    ),
  ];
}
``` 
We receive this deepLink: `www.test-app.com/info`
It's expected the route stack to look like this, because it's including the prefixes:
```dart
[
    MainRoute,
    HomeRoute,
    InfoRoute
]
``` 

From the [Principles of navigation](https://developer.android.com/guide/navigation/navigation-principles#deep-link) it is expected the whole stack to be removed and replaced with the deepLink stack. It means that whatever you did in HomeRoute it will be recreated as a new one.
In v6.4 after opening the deepLink the route stack is correctly created but the home page still preserves the old state (for instance text added in a TextField and scroll position).
@Milad-Akarie If this is an expected behaviour for auto route, how can we clear the old stack and open it as a new one from a deepLink?

**Comment by Milad-Akarie** [comment]
@MartinAKovachev it is in deed an invented behavior, in web this could be a url coming from browser and it only has one new segment so why build the whole thing right? I guess we can satisfy both use cases by adding a flag e.g "replaceAllOnDeepLink" or something? 
Or maybe we can do something with the passed PlatformDeepLink? like copyWith(replaceAll: true) or something.
what do you think?

**Comment by Milad-Akarie** [comment]
@MartinAKovachev you can now use the following flag for the desired behavior in auto_route 7.0.0
```dart
routerConfig: _appRouter.config(
      rebuildStackOnDeepLink: true
    )
```

**Comment by KarinBerg** [comment]
@Milad-Akarie 
First, thanks for the auto_route 7.0.0 update. Awesome that you fix this in that short time. 🥇 👍🏼 

Seems like we also need a auto_route_generator update to fix the dependencies because I get the following message when trying to use auto_route 7.0.0.

```
Because auto_route_generator 6.2.0 depends on auto_route ^6.2.0 and MyApp depends on auto_route 7.0.0, auto_route_generator 6.2.0 is forbidden.
So, because MyApp depends on auto_route_generator 6.2.0, version solving failed.

```

**Comment by Milad-Akarie** [comment]
@KieranLafferty totally missed that, auto_route_generator 7.0.0 is now live

**Comment by MartinAKovachev** [comment]
@Milad-Akarie Wow, nice job. Applause from me as well for the fix in this short period of time.
