### ISSUE TITLE
initialRoutes deprecated - How can I implement programmatic startup routes.

### ISSUE THREAD

**Issue by SherwinDeveloper** [Milad-Akarie/auto_route_library#1532]
How can I implement startup routes based on application configuration on application start?

initialRoutes on AutoRouterDelegate works/worked perfectly for that, but it is now deprecated.

Not really deeplinking from external trigger.

**Comment by Milad-Akarie** [comment]
@SherwinDeveloper
`deepLinkBuilder:(_) => DeepLink(routes[])`

**Comment by SherwinDeveloper** [comment]
Assumed that was only for deeplinks.  Thanks.

**Comment by tanhnv-avnon** [comment]
I got the same issue.

**Comment by tanhnv-avnon** [comment]
` routerConfig: router.config(
                  navigatorObservers: () => [AppNavigatorObserver()],
                  deepLinkBuilder: (_) {
                    // config deep link here
                    return DeepLink([state.isLoggedIn ? const HomeRoute() : const WelcomeRoute()]);
                  },
                )`
                
I tried to put it in  deepLinkBuilder but seem like it not call in to deepLinkBuilder to rebuild
