### ISSUE TITLE
Hero animation not working (v 7.1.0)

### ISSUE THREAD

**Issue by jamacco94** [Milad-Akarie/auto_route_library#1533]
Tried the following issues [#1168](https://github.com/Milad-Akarie/auto_route_library/issues/1168) [#418](https://github.com/Milad-Akarie/auto_route_library/issues/418) but no one helped...

Please help @Milad-Akarie

**Comment by papmodern** [comment]
I have the same issue

**Comment by papmodern** [comment]
Mine fixed with #1168
