### ISSUE TITLE
Accessibility issues with version 6 and above

### ISSUE THREAD

**Issue by psycura** [Milad-Akarie/auto_route_library#1535]
Hi, and thank you for the great work, that you do with this package.

We use this package from version 3 and everything works fine.
However, once the last major update was released (6.0.0) we found some strange issue with accessibility.
Here is the context:
For automation testing we are using `Appium` package.
This package doesnt have full support of Flutter, so we wrap our widgets with `Semantics` widget and than we can have access to the required widget.
With old versions (prior to 6.0.0)also was small issue when we use nested routes with, the the widgets inside the nested screens wasn't accessible by Appium, but its not bored us, because this part of the app can be easily tested manually.

But from the version 6.0.0 the Appium lost access to all widgets on all screens.
So we forced to revert back to version 5.0.4.

Do you have any idea why is this happen and what can be our solution?

Thanks

**Comment by Milad-Akarie** [comment]
@psycura I'm not familiar with Appium, what change exactly beak your tests?

**Comment by psycura** [comment]
The changes from version 5.0.4 to version 6.0.0
And there is 2 issues actually:
1. Issue that exists also in version 5.0.4 - Nested routes, when i use `AutoRouter()` inside my other widget, the content inside this nested router is not accessible by Appium
2. In new version, there is a new issue - Appium can find button element for example, but when he try to emulate `onClick` event for this button, nothing happens. In old version `onClick` works as expected

I dont know. what exactly the changes that you`ve did under the hood, i know only the consequences, that i described here

**Comment by LinschotenMelle** [comment]
Will this still be possible. I currently have a workaround where i wrap `Semantics` around the entire build widget but that isnt exactly what i had in mind. This feature would be great in combination with 3th party packages like Maestro to only do Black Box testing and can only see identifiers
