### ISSUE TITLE
ExtendedNavigator cant observe Route observer

### ISSUE THREAD

**Issue by yamamz** [Milad-Akarie/auto_route_library#154]

**Comment by Milad-Akarie** [comment]
Show me some code?

**Comment by yamamz** [comment]
MaterialApp(
                  builder: ExtendedNavigator<Router>(router: Router()),
                  navigatorObservers: <NavigatorObserver>[
                    biometricAuthRouteObserver,
                  ],)

**Comment by yamamz** [comment]
the class that listened

class BiometricLocker extends StatefulWidget {
  final Widget child;
  const BiometricLocker({
    Key key,
    @required this.child,
  }) : super(key: key);

  @override
  _BiometricLockerState createState() => _BiometricLockerState();
}

class _BiometricLockerState extends State<BiometricLocker> with RouteAware {
  OverlayEntry _overlayEntry;
  bool isOverlay;
  bool _isActive = false;
  final Logger logger = getLogger('_BiometricLockerState');

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    biometricAuthRouteObserver.subscribe(this, ModalRoute.of(context));
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    biometricAuthRouteObserver.unsubscribe(this);
    super.dispose();
  }

  @override
  void didPopNext() {
    //Called when the top route has been popped off, and the current route shows up.
    logger.v('didPopNext');
    _isActive = true;
    setState(() {});
  }

  @override
  void didPushNext() {
    //Called when a new route has been pushed, and the current route is no longer visible.
    logger.v('didPushNext');
    _isActive = false;
    setState(() {});
  }

  @override
  void didPush() {
    //Called when the current route has been pushed.
    logger.v('didPush');
    _isActive = true;
    setState(() {});
  }

  @override
  void didPop() {
    //Called when the current route has been popped off.
    logger.v('didPop');
    _isActive = false;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<BiometricAuthBloc, BiometricAuthState>(
      listener: (BuildContext context, BiometricAuthState state) {
        if (state is LockScreenBiometricAuthState) {
          _overlayEntry = OverlayEntry(builder: (BuildContext context) {
            return Container(
              height: MediaQuery.of(context).size.height,
              width: MediaQuery.of(context).size.width,
              child: BiometricLock(
                isBiometric: state.isBiometric,
                isEnablePin: state.isEnablePin,
              ),
            );
          });

          if (_isActive) {
            try {
              Overlay.of(context).insert(_overlayEntry);
            } catch (error, stackTrace) {
              logger.e('[build] error: error, stackTrace: stackTrace', error,
                  stackTrace);
            }
          }
        } else if (state is UnlockScreenBiometricAuthState) {
          if (_isActive) {
            try {
              _overlayEntry.remove();
            } catch (error, stackTrace) {
              logger.e('[build] error: error, stackTrace: stackTrace', error,
                  stackTrace);
            }
          }
        } else if (state is ShowPinCodeAuthState) {
          if (_isActive) {
            try {
              isOverlay = false;
              _overlayEntry.remove();
            } catch (error, stackTrace) {
              logger.e('[build] error: error, stackTrace: stackTrace', error,
                  stackTrace);
            }
          }
        } else if (state is LogoutDueToManyAttempsState) {
          if (_isActive) {
            try {
              isOverlay = false;
              _overlayEntry.remove();
              Navigator.pop(context);
              Navigator.pushNamedAndRemoveUntil(
                  context, Routes.loginPage, (Route<dynamic> route) => false);
            } catch (error, stackTrace) {
              logger.e('[build] error: error, stackTrace: stackTrace', error,
                  stackTrace);
            }
          }
        }
      },
      child: widget.child,
    );
  }
}

**Comment by yamamz** [comment]
it only listen to push

**Comment by Milad-Akarie** [comment]
@yamamz  Observers should go inside of ExtendedNavigator
```
MaterialApp(
navigatorObservers: NOT_HERE
builder: ExtendedNavigator(router: Router(),
    // HERE
    observers: [biometricAuthRouteObserver],
     ),
)
```
