### ISSUE TITLE
No pages are generated in pagesMap even though there are widgets annotated with @RoutePage

### ISSUE THREAD

**Issue by edwinnyawoli** [Milad-Akarie/auto_route_library#1541]
Even though I have pages annotated with `@RoutePage` in my sample application, running `flutter pub run build_runner build` generates an AppRouter that always has the pagesMap field empty.

Versions
````
auto_route: 6.0.5
auto_route_generator: ^6.0.0
````
````
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 135454af32 (5 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
````

![21334123123123](https://github.com/Milad-Akarie/auto_route_library/assets/10340264/38caea8d-da1d-4e05-ae86-46e541fabfb4)

![342423432121](https://github.com/Milad-Akarie/auto_route_library/assets/10340264/b976e9e8-556b-412d-9cd2-4a1764ff6e39)

**Comment by edwinnyawoli** [comment]
> Did this happen after upgrading to flutter 3.3.10?

I upgraded to 3.3.10 before trying v6 out

**Comment by AndreBlumenthal** [comment]
> > Did this happen after upgrading to flutter 3.3.10?
> 
> I upgraded to 3.3.10 before trying v6 out

@edwinnyawoli were you able to fix your problem? I am facing the same

**Comment by edwinnyawoli** [comment]
> > > Did this happen after upgrading to flutter 3.3.10?
> > 
> > 
> > I upgraded to 3.3.10 before trying v6 out
> 
> @edwinnyawoli were you able to fix your problem? I am facing the same

I reverted back to v5.0.3 unfortunately

**Comment by AndreBlumenthal** [comment]
@Milad-Akarie and @edwinnyawoli I can confirm, that my routes are not empty anymore when using `7.7.1`

**Comment by Abbasi233** [comment]
If you defined "generateForDir" attribute on AutoRouterConfig constructor, you can try to delete that. I solved problem with this way.
