### ISSUE TITLE
Deep linking stopped working after upgrading to Flutter 3.10

### ISSUE THREAD

**Issue by Hozefa04** [Milad-Akarie/auto_route_library#1546]

**Comment by yogeshButani** [comment]
yes i am facing the same issue, app is not opening even link also not generating... it always giving null in return instead of link...ive tried many solution but nothing works...also deeplinking in androidmanifest.xml is correct but not getting link....please reply this issue ..is i am the only one who is suffering from this issue?

**Comment by yogeshButani** [comment]
> _No description provided._

please reply my above question

**Comment by yogeshButani** [comment]
> +1

what are you trying to say?

**Comment by Hozefa04** [comment]
Its fixed. integration problems on my end

**Comment by yogeshButani** [comment]
> Its fixed. integration problems on my end

how did you fixed this problem please let me know? i am stucked here for few days

**Comment by Hozefa04** [comment]
> > Its fixed. integration problems on my end
> 
> how did you fixed this problem please let me know? i am stucked here for few days

sorry for replying earlier. The fix is actually mentioned in the [Changelog](https://pub.dev/packages/auto_route/changelog#:~:text=FIX%3A%20deepLinkBuilder%20is,instead%20of%20%27false%27) of auto_route 7.0.0. I set the includePrefixMatches's value to false and it was fixed. Previously it used to be false by default but now its kIsWeb.

**Comment by yogeshButani** [comment]
can you please share code?

**Comment by Hozefa04** [comment]
> can you please share code?

I don't have access to the code but the prop can be found here: 

```
return MaterialApp.router(            
      routerConfig: _appRouter.config(),         
);  
```

**Comment by Milad-Akarie** [comment]
@yogeshButani @Hozefa04 includePrefixMatches ill just match all paths with a prefix match of the deep-link, was that the problem all this time?

**Comment by Milad-Akarie** [comment]
@Hozefa04 I thought the deep-link wasn't being processed at all.

**Comment by nal-khangpt** [comment]
I tested on latest version of auto_router package, on android, and realize that the `deeplink` param in callback function always return '/' althought my app-link (which been setting up on `assetslink.json` file) is whatever. Ex: `https://mydomain.com/home` or `https://mydomain.com/home/my-item`.

I think this package do not handle deeplink as good as I wish
