### ISSUE TITLE
Where @MaterialAutoRouter after upgrade to v.7* from v.4*

### ISSUE THREAD

**Issue by forsytalnd** [Milad-Akarie/auto_route_library#1551]
Hi! Now `@MaterialAutoRouter` is not exist, but in readme you recommend use it.

**Comment by Milad-Akarie** [comment]
@forsytalnd Please read the migration guide

**Comment by forsytalnd** [comment]
Maybe one should rewrite `readme` so new syntax would be main, and deprecated one somewhere in bottom with title like "For version below 6" ))
