### ISSUE TITLE
Including Micro-Packages in different repositories in git. Unhandled Exception: Expected [RouteArgs], found [RouteArgs]

### ISSUE THREAD

**Issue by eibrat-erisov** [Milad-Akarie/auto_route_library#1552]
There is an error related to the passed arguments in Micro-Packages. The structure of the project is as follows:

## Project directory

    ├── app
		└─lib	
			└─router
			        └─app_router.dart
			 	└─app_router.gr.dart
	        └─ pubspec.yaml
    ├── packages
    		└─feature_onboarding
			└─lib	
				└─router
					└─onboarding_router.dart
					└─onboarding_router.gr.dart
			└─ pubspec.yaml

app - main application
packages - features

 in feature_onboarding the navigation is done correctly
```dart
context.router.navigate(
                    OtpConfirmationRoute(otpGenerate: state.otpGenerate),
                  );
```

But when importing into the app 

```yaml
# pubspec.yaml
dependencies:
    feature_onboarding:
        path: ../feature_modules/onboarding

```

```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {

  final _onboardingRouter = OnboardingRouter();

  @override
  Map<String, PageFactory> get pagesMap => {
        ..._onboardingRouter.pagesMap,
        ...super.pagesMap,
      };

  @override
  List<AutoRoute> get routes => [
        ..._onboardingRouter.routes,
      ];
}


```

When navigating, it gives an error 
`Unhandled Exception: Expected [OtpConfirmationRouteArgs], found [OtpConfirmationRouteArgs]`

I checked and found out that, they are conflicting because of one object on different links (in the screenshot).

![image](https://github.com/Milad-Akarie/auto_route_library/assets/101736106/e22ca596-bb76-43da-a0db-693b99969a31)

I tried taking the OtpConfirmationRouteArgs arguments from onboarding_router.gr.dart to onboarding_router.dart (or any other file in that package) and importing OtpConfirmationRouteArgs into onboarding_router.gr.dart (`import 'package:feature_onboarding_presentation/src/router/onboarding_router.dart';`). In this case, everything worked.

Creating one global `build.yaml` won't work, because the projects will be in different repositories in git.

I suggest a solution - make an optional argument that allows us to generate arguments (auto_route_generator) in another file from onboarding_router.gr.dart

**Comment by Milad-Akarie** [comment]
@eibrat-erisov  try the new micro packaging handling 
https://github.com/Milad-Akarie/auto_route_library#including-microexternal-packages
