### ISSUE TITLE
Unable to use  library after migration to 7.2.

### ISSUE THREAD

**Issue by mal33k-eden** [Milad-Akarie/auto_route_library#1560]
Unable to use the library. here are the setup and errors 
<img width="1155" alt="Screenshot 2023-05-21 at 21 30 37" src="https://github.com/Milad-Akarie/auto_route_library/assets/21183898/cfb835d9-fff0-4bd3-b8ff-d87f5229a7a3">
<img width="849" alt="Screenshot 2023-05-21 at 21 29 36" src="https://github.com/Milad-Akarie/auto_route_library/assets/21183898/cc526435-5b8a-4eb2-9cfc-87bb20f7c8c6">
<img width="963" alt="Screenshot 2023-05-21 at 21 29 24" src="https://github.com/Milad-Akarie/auto_route_library/assets/21183898/ad372b3c-68e4-43ee-b301-715f4e95c2c6">
<img width="933" alt="Screenshot 2023-05-21 at 21 35 17" src="https://github.com/Milad-Akarie/auto_route_library/assets/21183898/2610a2cb-8f63-46c7-9722-e2e15c88e483">

**Comment by mal33k-eden** [comment]
@Milad-Akarie kindly advice is i am missing any steps.

**Comment by Milad-Akarie** [comment]
@mal33k-eden did you run the build runner?

**Comment by Milad-Akarie** [comment]
Did you also update the auto_route_generator to v7?

**Comment by quissyus** [comment]
remove `class $AppRouter {}` then works

**Comment by renanboni** [comment]
I'm having this error: depends on auto_route_generator ^7.3.2 which doesn't match any versions, version solving failed.

@Milad-Akarie is the 7.3.2 a valid version for the generator?

**Comment by Milad-Akarie** [comment]
@renanboni latest auto_route_generator version is 7.1.1
