### ISSUE TITLE
Unable to use wildcard on generateForDir

### ISSUE THREAD

**Issue by DenisBogatirov** [Milad-Akarie/auto_route_library#1561]
`generateForDir: ['**/screens', '*/screens']` Has no effect and no effect and no routes are generated

Use case: 
I have two routers in my app `AppRouter` & `DrawerRouter`.  Widgets for both of them are scattered all over the project, but follow file structure and placed under `screens` and `drawers` folders respectively. If I do not provide `generateForDir` then all of the generated code is duplicated. To avoid that now I need to provide all cases of both folders manually like `generateForDir: ['lib/a/screens', 'lib/b/screens', ...]`

**Comment by Milad-Akarie** [comment]
Hey @DenisBogatirov What's the use-case for needing two routers inside the same App? 
**/screens should work, I'll check why it doesn't when I get a chance
