### ISSUE TITLE
Push route without adding to browser history

### ISSUE THREAD

**Issue by ferrarafer** [Milad-Akarie/auto_route_library#1562]
Is there a way to push a route without adding it to the browser history ?

**Comment by ferrarafer** [comment]
@Milad-Akarie that worked, thanks! But, how can I do the same without context?

**Comment by Milad-Akarie** [comment]
@ferrarafer  well if you have a specific path that you always need to neglect your do something like the following
```dart
  routerConfig: _rootRouter.config(
        neglectWhen: (path){
          return path == 'my-ignored-path';
        }
      ),
```

**Comment by ferrarafer** [comment]
Excellent, worked ! I finally used `routeInfoProvider`.

```dart
routeInfoProvider(neglectWhen: (location) {}),
```

Thanks !! ❤️
