### ISSUE TITLE
Is there a way to refresh the navigation stack using a listenable?

### ISSUE THREAD

**Issue by muezz** [Milad-Akarie/auto_route_library#1567]
Hi, 

In go_router, we can provide a listenable (which is basically a change notifier) and it would reload the navigation stack whenever the listenable/state changed. 
```dart
late final GoRouter _goRouter = GoRouter(
    debugLogDiagnostics: true,
    refreshListenable: _authProvider,
    initialLocation: IucRoutes.home.path,
    routes: <GoRoute>[
      //...routes
    ],
)
```
As you can see, the behavior of this router was that whenever the user session got expired, they would automatically be redirected to the login page (I had an auth guard which would be triggered when the nav stack was refreshed). Moreover, the user would be navigated to the relevant screen, whenever they login or logout without me having to make the programmatic call: `context.go(home or login)`. The latter is not that big of a deal but I do want the former functionality here as well.

Is there a way to achieve this? It would be great if it turns out to be as simple as providing a listenable to the auto router.

**Comment by Milad-Akarie** [comment]
@muezz There's something called AutoRedirectGuard but it requires a bit of setup comparing to just passing a listenable. 
I like the idea of just reacting a some listenable, could you tell me more about this? I might implement a samilair functionality.

does it re-push all routes on callback?

**Comment by Milad-Akarie** [comment]
@muezz  interesting... do you know if you're navigated back to latest location after redirected away by login redirect?

**Comment by muezz** [comment]
@Milad-Akarie I am not 100% sure what you mean exactly. When the route stack is refreshed, the go_router tries to go to the previous top location in the stack but is unable to do so because the route guard intercepts it and redirects it to another location. In this particular case, this would be the login page as the user was initially in the home page and the auth state chnaged automatically as their auth session expired. This change in state triggered the refresh. The route guard would then not allow the user to go back to the home page and they'd be redirected to the login page.

**Comment by Milad-Akarie** [comment]
@muezz I've added a similar functionality in the latest version 7.3.0.
https://pub.dev/packages/auto_route#route-guards 
scroll down for **Using a Reevaluate Listenable** part

please share any feedback you have

**Comment by muezz** [comment]
@Milad-Akarie That was quicker than I expected. I will try it out in a couple hours and will let you know how it goes.

**Comment by muezz** [comment]
@Milad-Akarie I tried this feature and, for me, the nav guard does not seem to be running once listeners are notified.

Here is an [example](https://github.com/muezz/auto_router_test.git) project. Give it a try. Once you log in, there is a button to log out without navigating back to login screen. Ideally, the nav guard should be triggered when that button is clicked.

**Comment by matt-hall-zory** [comment]
I'm in a very simila boat. I've got a refreshListenable set up and I can see in routing_controller->reevaluateGuards that _composeMatchesForReevaluate is returning null and not re-evaluating even though the account details have changed.

**Comment by Milad-Akarie** [comment]
@muezz @matt-hall-zory please make sure you  always call resolver.next() in your route guards.

**Comment by Milad-Akarie** [comment]
@muezz I just fixed an unhandled case when resolve.next is called with false, I probably forgot it because I rarely resolve with false in my code, and you shouldn't too unless the user cancels the login process, because if your App is launched from a deep-link and  you call reslover.next(false) after you redirect to the login page, you lost your initial-deep-link! and that's why I prefer to wait for the login result to decide whether or not I should abort the navigation. 

so your code might look something like this

```dart
if (isLoggedIn || goingToLogin) {
      resolver.next();
    } else {
     /// I use resolver.redirect instead of router.push because redirected routes will be automatically removed 
     // when resolver.next() is called.
      resolver.redirect(
        LoginRoute(onResult: resolver.next), // if result is "true" continue with original navigation event to HomeRoute else abort
      );
    }
```
inside of your  login button's onPressed

```dart
  final router = context.router;
    await authProvider.signIn('', '');
    // onResult callback will call resolver.next() which will remove the LoginRoute and resume navigation to HomeRote so we 
    // don't need to manually navigate anywhere
    if (onResult != null) {
      onResult!(true);
    } else {
      // Add fall back if onResult is not provided, probably not needed if you're building a native App not web
      router.push(const HomeRoute());
    }
```

**Comment by muezz** [comment]
@Milad-Akarie I am not really a fan of this but I understand why you want us to use `resolver.next()`. I see the benefit that if the user was on route X and tried to go to route Y, and if the user got signed out somehow, they will be redirected to login route and after logging in, they will be taken to route Y where they originally intended to go.

My confusion originates from the fact that the user can choose to perform some other action once on the login page. What if they click on the `Register` button on the login page that navigates them to a different page. What happens to the initial navigation logic that was never resolved? Would it affect the app in any way? Should I abort it using `resolver.next(false)`.

It is very unlikely that the user would try to register in this scenario but .....*murphy's law*.

**Comment by muezz** [comment]
@Milad-Akarie I have also tried the latest update to this feature. It seems to be working only if I set up an `onResult` callback which is not a big deal. I think it might be confusing for someone new to this feature. It should be made clear in the documentation that this is the only way to make this work.

**Comment by Milad-Akarie** [comment]
@muezz this should work even without the OnResult callback as long as you complete the resolver, reevaluating will not work if you have unresolved resolvers. 
They way I got this to work is by re-composing existing routes in stack  and re-pushing them again so if I allow this while a resolver is pending redirect-routes e.g LoginRoute will also be re-pushed and I don't think we want that. 
This should be enhanced overtime but for now that's all I could do

**Comment by muezz** [comment]
@Milad-Akarie I understand. For now, this seems to be working fine and would most probably fulfill the requirements I have.

Just out of curiosity, why do you have the guard mechanism set up like this? I am somewhat new to Auto-route so I am not completely sure. It does not make sense to me why there should be a need to resolve this logic outside the `onNavigation` callback. 

For example, this guard mechanism in `go_router` is as simple as this:
```dart
redirect: (BuildContext context, GoRouterState state) {
  if (AuthState.of(context).isSignedIn) {
    return '/signin';
  } else {
    return null;
  }   
}
```
This means that if you want the guard to let the route be pushed, you just need to return null. Otherwise, return the path. 

I think something like this should make this much easier to implement. For example:
```dart
@override
  void onNavigation(srcRoute, destRoute) {
    if (isLoggedOut) {
      return LoginRoute();
    }
    if (not_paid_user) {
      return SomePayWalledRoute();
    }
  return null;
  }
```
