### ISSUE TITLE
Navigating after async function

### ISSUE THREAD

**Issue by muezz** [Milad-Akarie/auto_route_library#1573]
I am not quite sure if this is a problem related to Auto Router or just my logic. I haven't encountered this with other routing libraries.

I have the following logic in the on press call back of a login button:
```dart
Provider.of<AuthProvider>(context, listen: false)
                        .signIn(emailController.text, passwordController.text)
                        .then(
                          (value) => AutoRouter.of(context)
                              .popAndPush(const HomeRoute()),
                        );
```
And I am getting the following error:
```console
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
```

I have tried using the context from a global key assigned to this page's scaffold but that did not help either. Can anyone tell me where I am making a mistake?

**Comment by Shreemanarjun** [comment]
You should check
```dart
if(context.mounted){

//then your navigation code

}

```

**Comment by muezz** [comment]
@Shreemanarjun I did that. The code in that if condition never runs because that condition comes out to be false.

**Comment by muezz** [comment]
@Shreemanarjun @Milad-Akarie I have created this sample repo that has only a login and home page. The problem is evident in both sign in and sign out. Please have a look at this.

[Sample App](https://github.com/muezz/auto_router_test.git)

**Comment by Milad-Akarie** [comment]
@muezz I haven't checked the whole App but I got something. from just looking at the router class, you shouldn't abort the on-going navigation if you need to Login first.
so you after pushing the login route inside of the onNavigation method you should call resolver.next() after the user is logged in. 

regarding the flutter error you're getting I believe it has to do with the fact that you're switch between the router widget and a circular loader  depending on auth_state, 
when circular loader is showing there is no router widget in your widgets tree.

**Comment by muezz** [comment]
@Milad-Akarie Wouldn't adding `resolver.next()` mean that the router would try to navigate again after pushing the `LoginRoute`? My assumption was that it could lead to an infinite loop where user foes to Route X, they are redirected to Login Route, then to Route X (they never get to here as the onNavigation is triggered again). I suspected that this would happen. Am I understanding it incorrectly?

As for the loading indicator, I was also playing around with it and noticed that the app was navigating correctly without the `builder` inside `MaterialApp`. I see why this is happening now but I would still like to keep the loading indicator in the app somehow. Is there any way to insert one or more widgets between the Material App and wherever the router is supposed to be? Under normal circumstances, this could easily be handled with a builder.

**Comment by Milad-Akarie** [comment]
@muezz  I meant something like this 

```dart
 @override
  void onNavigation(NavigationResolver resolver, StackRouter router) async {
    if (authProvider.isAuthenticated || resolver.route.name == LoginRoute.name) {
      resolver.next();
    } else {
       // onResult should be called when the user has completed the login process
      push(
        WebLoginRoute(onResult: (didLogin) => resolver.next(didLogin)),
      );
    }
  }
```

as for the loader you can use a Stack inside of the builder for example
 ```dart
builder: (context,routerWidget){
        return Stack(
          fit: StackFit.expand,
          children: [
            routerWidget!,
            if(loading)
              Center(child: CircularProgressIndicator(),)
          ],
        )
      }
```

**Comment by muezz** [comment]
@Milad-Akarie The stack solution is really clever and seems to be working. Thanks. The idea is that as long as the child that contains the router (routerWidget in this case) should always be in the tree for the navigation to work properly. As long as that happens, I can keep using the default builder.
