### ISSUE TITLE
_appRoute.config() not exist

### ISSUE THREAD

**Issue by quissyus** [Milad-Akarie/auto_route_library#1574]
Upgraded auto_route 7.2, but i have problems to find routerConfig: _appRoute.config()
![config_autoroute](https://github.com/Milad-Akarie/auto_route_library/assets/56977672/bf2314de-1baf-4e61-9db8-18872bcb9fa1)
![tempsnip](https://github.com/Milad-Akarie/auto_route_library/assets/56977672/97b16ba4-8072-401a-b966-680790b212fe)

**Comment by quissyus** [comment]
I found the problem.

I remove `class $AppRouter{}`

**Comment by alfaruqrizqi18** [comment]
Hi, facing the same problem. But I fixed after changed the extend class
from `$AppRouter` to `_$AppRouter`
