### ISSUE TITLE
how to close all route and push to main

### ISSUE THREAD

**Issue by rezadevelopers2** [Milad-Akarie/auto_route_library#1577]
Hello
The login page uses AutoTabsRouter.tabBar
After login, I want to go to the main page of the program and close all the routes

https://github.com/Milad-Akarie/auto_route_library/assets/78532168/599b1d09-db31-46db-987a-5ad7d6576a25

![image](https://github.com/Milad-Akarie/auto_route_library/assets/78532168/5d453537-2cf0-41a3-b80a-efd351a90a69)

To go to the main page
` context.router.replaceAll([const Main(), ]);`

But the previous router is not closed

> [√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
    • Flutter version 3.10.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (10 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

**Comment by Milad-Akarie** [comment]
@rezadevelopers2 What do you mean by close?

**Comment by rezadevelopers2** [comment]
> What do you mean by close?

I want all the previous routers to be closed and enter the new page, such as: `pushNamedAndRemoveUntil`

**Comment by rezadevelopers2** [comment]
> @rezadevelopers2 What do you mean by close?

Isn't there a solution to close all the previous routers  and enter the new page?

**Comment by Milad-Akarie** [comment]
@rezadevelopers2 removing pages from the stack will automatically "close" them as in "dispose" them so I'm not sure what you're asking?

**Comment by rezadevelopers2** [comment]
> @rezadevelopers2 removing pages from the stack will automatically "close" them as in "dispose" them so I'm not sure what you're asking?

I want like `pushNamedAndRemoveUntil ` the entire hot routers closes and enters a new page

But now if `AutoeTabsRouter.tabBar` is used and we switch between tabs and then we want to close all the previous hot pages and enter the new page, this will not happen.
You can watch it in the video I attached

**Comment by rezadevelopers2** [comment]
> @rezadevelopers2 removing pages from the stack will automatically "close" them as in "dispose" them so I'm not sure what you're asking?

 Doing a pop removes all pages from the stack, not just the last one

**Comment by jeslinjacob1995** [comment]
I have same issue , route.pushAndPopUntil(const NavHolderRoute(), predicate: (route)=> false); does not work . I am expecting it to pop all previous pages and push to new page . I dont know why this issue is closed
