### ISSUE TITLE
How to change placeholder in DeferredWidget

### ISSUE THREAD

**Issue by The28AWG** [Milad-Akarie/auto_route_library#1580]
I did not find the corresponding functionality.
I seem to get a gray screen while loading, I can't figure out why.

**Comment by Milad-Akarie** [comment]
@The28AWG just found out that by mistake we're passing a container instead of a Scaffold with centered circular loader.
fixed in 7.3.1 
also you can now provide your own placeholder to appRouter.config(placeHolder: ), FYI that's the same place holder used if the router has no entires.

**Comment by The28AWG** [comment]
Thanks!
