### ISSUE TITLE
QUESTION: How to ignore a DeepLink

### ISSUE THREAD

**Issue by KarinBerg** [Milad-Akarie/auto_route_library#1582]
Hi,
I use the Deep Linking functionality to open my app from an iOS Universal Link or Android AppLink (latest auto_route package version).
My app can run in the background (navigation app) so the following case can occur:
A user can clicks on an Universal Link while the app is already running in the background with an active car navigation. In this case I don’t want to proceed with the deep link and just bring the app to the foreground again. 

When I debug this scenario, I see the following:
- User clicks on the Link
- The app is coming to the foreground and is still in the car navigation page. 
- Now the debugger stops in the deepLinkBuilder and I have to return a DeepLink

```
deepLinkBuilder: (deepLink) {
  if (deepLink.path.startsWith('/l') || deepLink.path.startsWith('/r')) {
    if (appState == Navigating) {
      return ??? // Ignore DeepLink. Do nothing. just bring the app to the foreground
    }

    _deepLinkDataProvider.storeLinkInfo(deepLink.uri);
    return DeepLink.defaultPath;
  } else {
    return DeepLink.defaultPath;
  }
},
```

Do you have any idea how to „ignore“ a DeepLink???

**Comment by Milad-Akarie** [comment]
Hey @KarinBerg that's a valid use-case, that's why added DeepLink.none in version 7.3.2

**Comment by KarinBerg** [comment]
@Milad-Akarie You made my day 🤩 Thank you so much 🖖🏻
