### ISSUE TITLE
'builder != null': is not true.

### ISSUE THREAD

**Issue by imark00** [Milad-Akarie/auto_route_library#1585]

**Comment by mzdm** [comment]
@imark00 How did you solve? Same error.

**Comment by imark00** [comment]
have you tried setting `useInheritedMediaQuery: true` in your MaterialApp widget?

**Comment by mzdm** [comment]
> have you tried setting `useInheritedMediaQuery: true` in your MaterialApp widget?

did not help

**Comment by imark00** [comment]
sorry for that. I gave you a response to another error I had.
But when I had this particular error, I had an issue with the route name.

**Comment by mzdm** [comment]
thx, will look into that.

I am using it instead of EmptyRoutePage so I suspect there is some issue

**Comment by mzdm** [comment]
> 

ye i am on v6 and generated based on the Readme instructions. However it does not work the same as before on v5 @Milad-Akarie 

```dart
@RoutePage(name: 'PatientsListRoute')
class PatientsListScreen extends AutoRouter {}
```
