### ISSUE TITLE
replaceAll() does not work with nested routes

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1586]
Let's say we have this structure:
```dart
@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  final List<AutoRoute> routes = [
    AutoRoute(
      page: MainRoute.page,
      path: '/',
      children: [
        RedirectRoute(
          path: '',
          redirectTo: 'home',
        ),
        AutoRoute(
          page: HomeRoute.page,
          path: 'home',
         ),
        AutoRoute(
          page: SearchRoute.page,
          path: 'search',
         ),
      ],
    ),
    AutoRoute(
      page: InfoRoute.page,
      path: '/info',
    ),
    RedirectRoute(
      path: '*',
      redirectTo: '/',
    ),
  ];
}
``` 

If you try to use: `context.router.root.replaceAll([MainRoute(children: [SearchRoute()])])` it doesn't work properly and replaces the stack with `MainRoute(children: [HomeRoute()])`. @Milad-Akarie 

This does not work as well: `context.router.root.replaceAll([MainRoute(), SearchRoute(),])`

**Comment by Milad-Akarie** [comment]
@MartinAKovachev ya I think what's going on here, it's an easy fix but quick question, do you expect the MainRoute to keep it's state when you call `context.router.replaceAll([MainRoute(children: [SearchRoute()])])`?

**Comment by MartinAKovachev** [comment]
@Milad-Akarie In short no, we expect the state to be cleared when we use `replaceAll`.

**Comment by Milad-Akarie** [comment]
@MartinAKovachev should be good in version 7.4.0 
I also added a new flag for ditching old state for already existing routes
replaceAll([Routes], updateExistingRoutes: false)
