### ISSUE TITLE
Web browser back button throwing NestedStackRouter error

### ISSUE THREAD

**Issue by paramsinghvc** [Milad-Akarie/auto_route_library#1593]
Problem:
I'm using nested router for authenticated routes. The routes are like below:
- /discover : Displays a list of users
- /users/:id : Shows the detail of a given user with an id

When I use the autoroute `context.router.push(UserDetail(id: id))` in discover screen and vice-versa `context.router.pop()` inside detail screen, everything works fine and smooth.

But as soon as I use the chrome browser back button, it gives an error
```
Uncaught (in promise) Error: A NestedStackRouter was used after being disposed.
Once you have called dispose() on a NestedStackRouter, it can no longer be used.
```
Apparently, on browser back button press, the navigation behaviour behaves like a full refresh and it starts the journey from the topmost root router which causes problems like:
- The error above.
- Abrupt page transition compared to the `context.router.pop()` way.

Impact: 
It's very common to use browser back button to navigate back and froth in a web app, people use gestures as well on Mac Safari and Chrome to do that. We'll lose on the page transitions and unnecessary mounting of parent widgets causes performance impacts too.

Desired behaviour:
Given we lose all the benefits when someone presses the back button, instead of our custom button which runs pop(), is there a way to have the same UX as when we use pop? Just like how it happens in Single Page Apps like React and Angular on web? 

<img width="378" alt="Screenshot 2023-06-03 at 10 04 18" src="https://github.com/Milad-Akarie/auto_route_library/assets/4329912/a9afe127-b41e-4028-a904-ff9145b521b0">

Error:
<img width="279" alt="Screenshot 2023-06-03 at 10 13 50" src="https://github.com/Milad-Akarie/auto_route_library/assets/4329912/36e69402-abd0-4c1c-9374-da07ca706d2f">

**Comment by hazzo** [comment]
Wow, nobody? I have the same issue, how it's supposed to be fixed?
