### ISSUE TITLE
How to disable manual routing by address bar 

### ISSUE THREAD

**Issue by AliEasy** [Milad-Akarie/auto_route_library#1599]
Hi
I want to prevent users from navigating manually by address bar in browser
Like in normal way when user tries to go to a page by writing the page name in the address bar, nothing happen

**Comment by jhionan** [comment]
In my team sometimes we push pages and Pass parameter even if is a empty class, than we can have a guard that if it don't contains the parameter, than we don't navigate.

By navigating using the address bar, the app can't create the required parameters..
