### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by RahmatAliMalik5** [Milad-Akarie/auto_route_library#160]
The version shown at pub.dev is `0.6.1`. I was getting an error of

`Because myapp depends on auto_route_generator 0.6.1 which doesn't match any versions,version solving failed.`

Now, by checking the releases here on github, I have updated the versions in `pubspec.yaml` file to `0.6.0`.
Now, it is working fine for me. Please check and update the version. Thanks for such a great library

**Comment by Milad-Akarie** [comment]
@RahmatAliMalik5 should be fixed in version 0.6.2
Thanks for reporting
