### ISSUE TITLE
how i can get host name from deep link its empty

### ISSUE THREAD

**Issue by mmasood22** [Milad-Akarie/auto_route_library#1601]
i want url with hostname how i can get host inside from deep link @Milad-Akarie 

```
          deepLinkBuilder: (deepLink) {
                      print("deep link path :: ${deepLink.configuration.path}");
                      print("deep link uri :: ${deepLink.configuration.url}");
                      final newPath = deepLink.path.split('/u').last;
                      // print("deep inside :: $path");
                      // print("new path :: $newPath");
                      return DeepLink.path(newPath);
          },
```
 For the print i am getting this data
```
 
 deep link path :: /reset-password
 deep link uri :: /reset-password?ticket=12345
```
 I have two questions ;
 
 1:  **How i can get the host name of the deep link url** 
 
 
2: **And one more thing when i have  url like this `https://example.com/u/rest-password` its not opening the correct route if i do parsing it will open the default path. if i remove the u/ then its working fine.**

**Comment by Milad-Akarie** [comment]
@mmasood22 raw links are handled by platform, so you only get the path, maybe try using uni_links packages to retrieve links your self?

**Comment by mmasood22** [comment]
@Milad-Akarie i dont want to use any third party to retrieve links is there any way of doing using the latest auto route package.
