### ISSUE TITLE
Issues with Type when generate argument 

### ISSUE THREAD

**Issue by pnc022022** [Milad-Akarie/auto_route_library#1603]
This is my screen code

> @RoutePage()
class WebkitScreen extends StatefulWidget {
  final bool? hideHeader;
  final String? title;
  final Color? color;
  final String? url;
  final bool? cacheContent;

>  const WebkitScreen({
    super.key,
    this.hideHeader,
    this.title,
    this.url,
    this.color,
    this.cacheContent,
  });

> @override
  State<WebkitScreen> createState() => _WebkitScreenState();
}

And this is generated code in router.gr

> class WebkitScreenRouteArgs {
  const WebkitScreenRouteArgs({
    this.key,
    this.hideHeader,
    this.title,
    this.url,
    this.color,
    this.cacheContent,
  });
  final Key? key;
  final bool? hideHeader;
  final String? title;
  final String? url;
  final InvalidType color;
  final bool? cacheContent;
  @override
  String toString() {
    return 'WebkitScreenRouteArgs{key: $key, hideHeader: $hideHeader, title: $title, url: $url, color: $color, cacheContent: $cacheContent}';
  }
}

Color turn to InvalidType, I've try some clean and rebuild multiple times but it seem a bug

**Comment by Milad-Akarie** [comment]
@pnc022022  refer to this https://github.com/Milad-Akarie/auto_route_library/issues/1438
