### ISSUE TITLE
Any support for pushNamedAndPopUntil

### ISSUE THREAD

**Issue by natintosh** [Milad-Akarie/auto_route_library#1604]
I'm not sure if `auto_route` has any support for `pushNamedAndPopUntil` or whether there are other ways of achieving this behaviour

**Comment by natintosh** [comment]
> @natintosh not everything is supported for path navigation because a path can push one or multiple pages. explain your use-case maybe I can suggest something?

Okay so I'm working on a multi-module project with multiple teams working on a different module and each module has it own routes... then in the main app we are appending each module's routes during initialization.

```
class AppRouter extends RootStackRouter {
  final List<AppRouteInfo> routesInfo;

  AppRouter({this.routesInfo = const []}) : super();

  @override
  Map<String, PageFactory> get pagesMap =>
      routesInfo.fold(<String, PageFactory>{}, (previousValue, element) {
        return {...previousValue, ...element.pagesMap};
      });

  @override
  List<AutoRoute> get routes => routesInfo
      .fold(<AutoRoute>[], (prev, element) => [...prev, ...element.routes]);
}
```

Due to this, we are mostly using named routing to route between modules and there are some use case whereby I would need to move on to another module and pop all stack until a page and push

**Comment by Milad-Akarie** [comment]
@natintosh not of that explains the need of using paths instead of route objects?
