### ISSUE TITLE
Pass parameter List Record type support

### ISSUE THREAD

**Issue by hewcheehau** [Milad-Akarie/auto_route_library#1609]
Hi, everyone, just want to ask why I can't pass List of Record type data to a page? 

when ran finish the script;

the gr file show error
 error: 
The argument type 'List<void>' can't be assigned to the parameter type 'List<({String catName, int id})>'

Example:

```
@RoutePage()
class ExamplePage  {
const CoreDetailScreen({super.key, this.tagList = const []});
final List<({int age, String name}) tagList;
}
```

**Comment by Milad-Akarie** [comment]
@hewcheehau record support is implemented in the latest auto route versions
Thanks for reporting.
