### ISSUE TITLE
How to determine different instances of a page in AutoRouterObserver

### ISSUE THREAD

**Issue by lycstar** [Milad-Akarie/auto_route_library#1610]
I have a page like this
<img width="572" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/37872392/2728cf68-5b2a-4420-be3e-c37cb1993059">

<img width="353" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/37872392/cdc8c021-d340-4300-9fc0-b5b797134445">

<img width="756" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/37872392/fc8cfe2f-1e68-4cbb-9c97-d4049d205b66">

I need to listen to the routing to distinguish between different playlist page instances，
  but the different playlistpage's route.data?.path always playlist/:playlistId
   I hope there can get format like playlist/1, playlist/2

I have a bad way like this
```dart
    final args = route.settings.arguments as PlaylistRouteArgs;
    '${route.data?.path}/${args.playlistId}';
```
Is there a better way?

**Comment by Milad-Akarie** [comment]
@lycstar that would be `route.data?.match` => returns the string match of the route

**Comment by lycstar** [comment]
> @lycstar that would be `route.data?.match` => returns the string match of the path

Thanks, I will try.
