### ISSUE TITLE
Nested route push same page multi times but not work

### ISSUE THREAD

**Issue by lycstar** [Milad-Akarie/auto_route_library#1611]
I have a detail page, it will push multi times，but will be replaced。

for example:

home page -> detail A -> detail B

but when pop once, it will back to home, not detail A.

**Comment by lycstar** [comment]
I find a way that add path， it works ，is better way？
<img width="632" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/37872392/b03e692b-1945-451a-8a40-9ffc297d7406">

<img width="347" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/37872392/1fa63ef5-c99e-4fe7-b4ea-837d2d752392">

**Comment by Milad-Akarie** [comment]
@lycstar  can not reproduce this, it seems to work just fine, you're using router.push right?
![Jul-01-2023 1-03-42 PM](https://github.com/Milad-Akarie/auto_route_library/assets/55059449/70cbcf38-ee33-4930-b8d7-3024d960bf01)

**Comment by lycstar** [comment]
> @lycstar  can not reproduce this, it seems to work just fine, you're using router.push right?
> 
> ![Jul-01-2023 1-03-42 PM](https://github.com/Milad-Akarie/auto_route_library/assets/55059449/70cbcf38-ee33-4930-b8d7-3024d960bf01)
> 
> 

This occurs in nested router.

**Comment by Milad-Akarie** [comment]
@lycstar the example above is using a nested-router

**Comment by lycstar** [comment]
> @lycstar the example above is using a nested-router

can you give me your example main code. thanks

**Comment by jhionan** [comment]
I was trying to understand this bug, it seems that if you have a listenable to reevaluate the guard its not pushing nested pages correctly
