### ISSUE TITLE
Error split view flutter web 

### ISSUE THREAD

**Issue by arcas0803** [Milad-Akarie/auto_route_library#1616]
Hi,

I'm developing a flutter with the latest version of auto_route.

I use Adaptative Scaffold with 3 divisions (navigation, principal page, detail page)

To give an example of the routes :

1. Home
    1. BookList
        1. BookDetail
        2. No book selected 
    2. ArticlesList
        1. Article list
        2. No article selected 
    3. Profile 
    
When the app is in desktop mode, 3 columns are visible:

-------------------------------------------------------

Navigation.    ||.       Booklist  => AutoRouter()    || BookDetail => AutoRouter()

This layout works perfectly

When the app is in table mode, 2 columns are visible:

------------------------------------------------------------

Navigation || BookList=> AutoRouter() 

In this case, when I implement an onTap method in booklist to push book detail. I want to render book detail in the second column but I can't.  I can´t access the router of book list with its children and rendered in that area.

Is there any way to handle this scenario?

I can't find an example of nested navigation with multiple levels in the docs.

Thanks.

**Comment by Milad-Akarie** [comment]
Hey @arcas0803 I'm familiar with the concept, other platforms would call this named-views or named-navigator windows, right now auto_route does not support this, as I could not figure out how to handle the URL in such cases. 
e.g. Angular has its URL scheme when they define the active path for each view.  

although one thing I though about to make things simple is to mark one router as the main router in that level meaning it's the one to report sub-location. 
do you have any thoughts regarding this?

**Comment by rlee1990** [comment]
@Milad-Akarie Has there been any new thought to this?
