### ISSUE TITLE
`homeIndex` for AutoTabsRouter does not work

### ISSUE THREAD

**Issue by mhbdev** [Milad-Akarie/auto_route_library#1617]
I have no idea why this parameter really exists! Changing it will not make any change.

**Comment by Milad-Akarie** [comment]
@mhbdev Yup this is common, did you figure out how to set initial tab dynamically?

**Comment by mhbdev** [comment]
> @mhbdev Yup this is common, did you figure out how to set initial tab dynamically?

Yes, I tried to setActiveIndex after the first build, but no I have no idea how to this dynamically.

**Comment by Milad-Akarie** [comment]
@mhbdev You need to think about tab routes as nested routes, how do you set an initial nested r route?  you do it when navigating to the parent /parent/target child.
 If your tab host  page is the initial page you could do it like follows: 
 
```dart
 routerConfig: _rootRouter.config(
  deepLinkBuilder: (deepLink){
    /// You don't want to override deep-links so
    /// check if the there's no deep link first
    if(deepLink.path == DeepLink.defaultPath){
      return DeepLink(TabHostRoute(children: [TargetTab()]));
    }
    return deepLink;
  }
),
```
