### ISSUE TITLE
Pages keep on Navigating to Top Router Page

### ISSUE THREAD

**Issue by coder-Aayush** [Milad-Akarie/auto_route_library#1622]
Hello, I've been trying to achieve persistent navigation bar all across the app, but with below code, when I try to navigate to `DashboardWrapper`, it navigate to top of the page i.e `MainDashboardWrapper`.  Can you please help me on this?

## Code
```dart
 AutoRoute(
      page: MainDashboardWrapper.page,
      guards: [AuthGuard()],
      children: [
        AutoRoute(
          page: MainDashboard.page,
          path: 'main-dashboard',
          maintainState: true,
          initial: true,
          children: [
            AutoRoute(page: MasterHomeRoute.page, path: 'master-home', children: [
              AutoRoute(
                page: DashboardWrapperRoute.page,
                path: 'wallet-dashboard-wrapper',
                initial: true,
                children: [
                  AutoRoute(
                    page: DashboardRoute.page,
                    path: 'wallet-dashboard',
                    initial: true,
                    children: [
                      AutoRoute(page: HomeRoute.page, path: 'wallet-home', initial: true),
                      AutoRoute(
                        page: TransactionHistoryRoute.page,
                      ),
                    ],
                  )
                ],
              )
            ]),
          ],
        ),
      ],
    ),
```

Thanks for help!

**Comment by girija870** [comment]
This will help you 

AutoRoute(page: MainDashboardWrapper.page, path: '/', guards: [
      AuthGuard()
    ], children: [
      AutoRoute(page: MainDashboard.page, path: '', children: [
        AutoRoute(page: MasterHomeRoute.page, path: ''),
      ]),
      AutoRoute(page: SubDashboardWrapperRoute.page, path: '', children: [
        AutoRoute(page: SubDashboardRoute.page, path: '', children: [
          AutoRoute(page: SubHomeRoute.page, path: ''),
          AutoRoute(
            page: TransactionHistoryRoute.page,
          ),
        ]),
        RedirectRoute(path: '*', redirectTo: ''),
      ]),
      RedirectRoute(path: '*', redirectTo: ''),
    ]),

**Comment by coder-Aayush** [comment]
Thanks @girija870
