### ISSUE TITLE
Unable to perform widget test with AutoTabsScaffold

### ISSUE THREAD

**Issue by norman17uy** [Milad-Akarie/auto_route_library#1627]
I followed what was on the documentation on how to use AutoTabsScaffold.

![auto_route_1](https://github.com/Milad-Akarie/auto_route_library/assets/100858019/33cac400-637b-4fd1-9d70-38f908d09d2b)

But when I try to pump the widget that contains AutoTabsScaffold. It throws this error.

![auto_route_2](https://github.com/Milad-Akarie/auto_route_library/assets/100858019/68c00fb6-3d62-4197-aeae-9f32484a8514)

**Comment by Milad-Akarie** [comment]
@norman17uy are you not pumping the material App? The error implies that the tabs router can not attach to the parent router which I'm assuming it's the root router in your case.
