### ISSUE TITLE
Relative routes breaking in generated file

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/auto_route_library#163]
The imported screens are not correct:

![image](https://user-images.githubusercontent.com/25782944/87836061-e3a4db80-c85c-11ea-8274-37696479769e.png)

Also it's importing `flutter/material.dart` for some reason.

**Comment by Reprevise** [comment]
Also when you make breaking changes, it would be good to bump up the version number to say 0.7.0 so that people don't upgrade until they're ready.

**Comment by Milad-Akarie** [comment]
@Reprevise  ya I thought about doing that. but I thought I just upgraded a couple days ago ....
anyways.
Are you on windows? why do you have back slashes instead of forward slashes?

**Comment by Reprevise** [comment]
I'm on Windows. I'm not sure why it made back slashes. The issue remains when removing the first `..\`.

**Comment by Milad-Akarie** [comment]
That's weird, how does a valid relative import look like if you do it manually?

**Comment by Reprevise** [comment]
![image](https://user-images.githubusercontent.com/25782944/87838283-82810600-c864-11ea-832f-329e3c28bb81.png)

**Comment by Milad-Akarie** [comment]
@Reprevise can you check auto_route_generator: 0.6.3 and confirm if it works?

**Comment by Reprevise** [comment]
Seems to work now, for some reason `flutter/material.dart` seems to get imported though.

**Comment by Milad-Akarie** [comment]
ya actually I'm always importing it. mostly for the @required annotation. I guess I could check for that and only import it if there's at least one arguments holder class. with a required annotation.

**Comment by Reprevise** [comment]
Why don't you just use the `meta` package?

**Comment by Milad-Akarie** [comment]
@Reprevise  You mean export in auto_rout?

**Comment by Milad-Akarie** [comment]
solved by adding this export to auto_route.dart 
`export 'package:meta/meta.dart' show required;`

**Comment by Milad-Akarie** [comment]
it should all be fine in  auto_route: 0.6.4
closing this now. 
Thanks for reporting
