### ISSUE TITLE
AutoLeadingButton requires hot-reload to show its state

### ISSUE THREAD

**Issue by agonzalezpuerta** [Milad-Akarie/auto_route_library#1632]
Dear GitHub,

I have implemented an app based on AutoTabsScaffold similar to that shown in [this repos' example](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/router/router.dart).

The app has an AutoLeadingButton in the top route's AppBar, which is not shown unless I hot reload the application. I have implemented a listener to fire a `setState()` upon changes in the route stack. This gets the job done, but I'm not sure if this is the right/cleanest approach. Please see below:

```dart
class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    // Rebuilds the widget to show AutoLeadingButton upon route changes
    context.router.addListener(() {
      setState(() {});
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      appBarBuilder: (context, tabsRouter) => AppBar(
        leading: const AutoLeadingButton(
          ignorePagelessRoutes: true,
        ),
```

Thank you.

**Comment by Milad-Akarie** [comment]
Hey @agonzalezpuerta I just tested this and it seems to be working just fine,  what navigation operation are you doing that don't trigger a rebuild?

**Comment by agonzalezpuerta** [comment]
Dear @Milad-Akarie,
Thanks for the quick reply. Let me try to give you the full context. Any idea of what could be going wrong?

BTW, we reached you via Twitter. Will send you an email shortly.

The navigation is done using the push method on the nearest router, which in this example should be `ProfileRouter`. The method is triggered from a page in such router (`ProfileLandingRoute`)
```dart
context.router.push( const PersonalInfoRoute());
```
The nested routers are passed in the `routes` parameter of the `AutoTabsScaffold`:
```dart
return AutoTabsScaffold(
      appBarBuilder: (context, tabsRouter) => AppBar(
        leading: const AutoLeadingButton(
          ignorePagelessRoutes: true,
        ),
      routes: const [
        OneRouter(),
        AnotherRouter(),
        ProfileRouter(),
      ],
```
All this uses the following tree structure:

```dart
    AutoRoute(
      page: HomeRoute.page,
      children: [
        AutoRoute(
          page: OneRouter.page,
          children: [
            AutoRoute(
              page: FooRoute.page,
              initial: true,
            ),
          ],
        ),
        AutoRoute(
          page: AnotherRouter.page,
          children: [
            AutoRoute(
              page: FooFooRoute.page,
              initial: true,
            ),
          ],
        ),
        AutoRoute(
          page: ProfileRouter.page,
          maintainState: false,
          children: [
            AutoRoute(
              page: ProfileLandingRoute.page,
              initial: true,
            ),
            AutoRoute(
              page: PersonalInfoRoute.page,
            ),
          ],
        ),
      ],
    ),

    // ............

@RoutePage(name: 'OneRouter')
class OneRouterPage extends AutoRouter {
  const OneRouterPage({super.key});
}

@RoutePage(name: 'AnotherRouter')
class AnotherRouterPage extends AutoRouter {
  const AnotherRouterPage({super.key});
}

@RoutePage(name: 'ProfileRouter')
class ProfileRouterPage extends AutoRouter {
  const ProfileRouterPage({super.key});
}

**Comment by Milad-Akarie** [comment]
@agonzalezpuerta  your setup looks seems fine to me, not sure what's happening, could you try using appBar property instead of appBarBuilder?

**Comment by agonzalezpuerta** [comment]
Dear Milad,
Thanks for the reply and your time. We found it was a bug on our end while setting up the top-most routes. Our app has an "entry point" that is intended to replace all routes depending on login status. We were using `context.router.replace` instead of `context.router.replaceAll`.

By the way, as per your last answer, how do you access the `appBar` property in `AutoTabsScaffold`? We noticed it is not available. Not sure what you meant exactly.

Thanks again.

**Comment by Milad-Akarie** [comment]
@agonzalezpuerta My bad, I thought appBar was exposed, now I'm thinking it should be exposed!
