### ISSUE TITLE
'part of' in generated file 'gm.dart'

### ISSUE THREAD

**Issue by TarriestZero** [Milad-Akarie/auto_route_library#1635]
Is it possible to generate a gm.dart file with the presence `part of '<file_name>.dart'` (`@AutoRouterConfig.module()`) ?

**Comment by Milad-Akarie** [comment]
@TarriestZero there was reported bug regarding this, try the latest auto_route_generator and see if you still have an issue

**Comment by TarriestZero** [comment]
@Milad-Akarie generated correctly on version auto_route_generator: ^7.1.2. Thanks.
