### ISSUE TITLE
[Web] browser navigation buttons don't work when using AutoTabsRouter with path param containing `%20`

### ISSUE THREAD

**Issue by a-h-mzd** [Milad-Akarie/auto_route_library#1637]
**Steps to reproduce:**

1. Create a simple one-screen app with two tabs using `AutoTabsRouter`
2. The screen route should accept a path parameter
3. The parameter should contain `%20` (space character)
4. Change between tabs multiple times and then try to use browser back button

**Comment by Milad-Akarie** [comment]
@a-h-mzd Should be fixed in auto_route 7.7.0
Thanks for reporting
