### ISSUE TITLE
`flutter_bloc` does not seem to work with `Route Guards` when using `reevaluateListenable`

### ISSUE THREAD

**Issue by davidnwaneri** [Milad-Akarie/auto_route_library#1638]
I have my route guard declared as:
```dart

class AuthGuard extends AutoRouteGuard {
  const AuthGuard({
    required LoginBloc loginBloc,
  }) : _loginBloc = loginBloc;
  final LoginBloc _loginBloc;

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    var state = _loginBloc.state;
    if (state is UserLoggedInState) {
      resolver.next();
    } else {
      resolver.redirect(LoginRoute()).then((_) {
        resolver.next();
      });
    }
  }
}

```
When I use `reevaluateListenable`, I'm unable to navigate to the home screen. After a successful API request to login, the navigation to navigate to the home screen does not work. A strange thing that happens is the API requests that should happen on the home screen are called (I noticed this from the logs), but the UI does not reflect the navigation.

This only happens when using `reevaluateListenable` to listen to state changes
```dart
routerConfig: _appRouter.config(
                    reevaluateListenable: ReevaluateListenable.stream(
                      context.watch<LoginBloc>().stream,
                    ),
                  ),
```

This is what I use to navigate to the home screen from the login screen.
```dart
context.router.replaceAll([DashBoardRoute()]);
```

**Comment by Milad-Akarie** [comment]
@davidnwaneri  why are you navigating from your LoginScreen? your login screen should report back login result, the resolver.redirect should pop the login screen, and calling resolver.next should continue navigation to DashboardRoute

**Comment by davidnwaneri** [comment]
@Milad-Akarie  What your said works. To answer your question, I am not preserving the auth state, once the app is terminated and reopened, the user has to login again (This is the design). That is why I am navigating from the LoginScreen.

There is a welcome screen on the app that has a login button, which should take the user to the login screen. From what is on the docs and what you mentioned; so now the login button tries to navigate to the home screen and then redirects to the login screen. After a successful navigation, it continues to the home screen. This works. I'm just unsure if I'm doing the right thing.

**Comment by Milad-Akarie** [comment]
@davidnwaneri  This's the preferred approach in my opinion, because if a user has a deep-link to a page inside of your App they will first be asked to log in and then automatically redirected to their destination.

**Comment by davidnwaneri** [comment]
Thank you.
