### ISSUE TITLE
Cannot pop when the app is reloaded or when deep linked to a specific path (Flutter Web)

### ISSUE THREAD

**Issue by dhruv-js** [Milad-Akarie/auto_route_library#1642]
Hey, first of all thanks a lot for this package. It is really awesome and useful for my web app.

Although, there is one issue which causes a lot of problems. Whenever someone reloads the application or deep links to a specific path. The navigation history is cleared and due to which one cannot go back using the back button provided in my app on every screen. 

For example, I have,
/books/:bookID/reviews in a /parent/child/grandchild (nested) config,

If a user refreshes or deeplinks to the aforementioned state, `AutoRouter.of(context).pop()` has no effect because the ancestor routes are not in the stack. 

Steps to reproduce: 
`context.navigateTo(PageBRoute);`

//On page B reload the tab
`context.router.pop(); //This doesn't work anymore`

Is there any way this issue can be solved?

**Comment by Andrflor** [comment]
Using this delegate instead of the default one fixed that issue for me

```dart
class CustomRouterParser extends DefaultRouteParser {
  CustomRouterParser(super.matcher);

  bool _firstCall = true;

  @override
  bool get includePrefixMatches => _firstCall;

  @override
  Future<UrlState> parseRouteInformation(
      RouteInformation routeInformation) async {
    final UrlState info = await super.parseRouteInformation(routeInformation);
    _firstCall = false;
    return info;
  }
}
```

PS: Just setting includePrefixMatches to true in the default parser would also fix it but would break the back button of the browser in nested scenario...
