### ISSUE TITLE
The name 'BuildContext' is defined in the libraries 'package:auto_route/auto_route.dart' and 'package:flutter/src/widgets/framework.dart'. 

### ISSUE THREAD

**Issue by finroly** [Milad-Akarie/auto_route_library#165]
Hi I just bump the version from 0.6.1 to 0.6.4 and getting above error in all my pages.
To resolve this I have to use `import 'package:auto_route/auto_route.dart' as at;`

and  `at.ExtendedNavigator.of(context).`

is there any solution to this or I have to change all of my code?
```
@override
  Widget build(BuildContext context) {

**Comment by Milad-Akarie** [comment]
@peswanibros I'll look into it.

**Comment by Milad-Akarie** [comment]
@peswanibros I couldn't reproduce the error but I did change some things in 
```
 auto_route: 0.6.5
 auto_route_generator: 0.6.5
```
so please check it out and let me know if the issue was solved.

**Comment by peswanibros** [comment]
@Milad-Akarie Thanks for your effort!!

I tried 0.6.5

but I am getting below error 

```
E/flutter ( 6232): [ERROR:flutter/shell/common/shell.cc(209)] Dart Unhandled Exception: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 6232): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 6232): #2      HeroController.didPush (package:flutter/src/widgets/heroes.dart:715:12)
E/flutter ( 6232): #3      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:2690:14)
E/flutter ( 6232): #4      List.forEach (dart:core-patch/growable_array.dart:313:8)
E/flutter ( 6232): #5      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3306:27)
E/flutter ( 6232): #6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3269:5)
E/flutter ( 6232): #7      NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3663:5)
E/flutter ( 6232): #8      NavigatorState.pushNamedAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3513:12)
E/flutter ( 6232): #9      ExtendedNavigatorState.pushAndRemoveUntil (package:auto_route/src/extended_navigator.dart:380:22)
E/flutter ( 6232): <asynchronous suspension>

```
on this line

```
ExtendedNavigator.of(context).pushAndRemoveUntil(
            Routes.appIntro, (Route<dynamic> route) => false);

**Comment by peswanibros** [comment]
Ok so I think 0.6.5 code generator was not pushed and not reflecting in `pubspec.yaml` so I changed it to 0.6.5 after reading a closed issue where you said that you pushed 0.6.5. Now I did not get the build context error. But still getting above error. The error does not occur every time. To reproduce it just install the app using use `pushAndRemoveUntil`. after using the app for few seconds press back button, now open the app again from app drawer (click your app icon) and you will see this error.

**Comment by Manuelbaun** [comment]
Hi, 
I also got this issue, when I bumped auto_route version to 0.6.6. Basically, auto_route imports the BuildContext somehow. I can work around this by hiding 

`import 'package:auto_route/auto_route.dart' hide BuildContext;`

Should the BuildContext be included in the auto_route?

**Comment by theweiweiway** [comment]
closing due to
- stale issue
- possible solution
