### ISSUE TITLE
Breaking change in v7: `/page-name-page` became `/page-name-route`

### ISSUE THREAD

**Issue by mattermoran** [Milad-Akarie/auto_route_library#1653]
Just noticed that some buttons stopped working apparently because the automatically generated paths have changed the format that now they end with `-route` instead of `-page` as before even though the readme still mentions `-page`. 

Was that an intended change? If yes would be nice to have mentioned somewhere. And possible an option to keep the old name or better custom suffix.

**Comment by Milad-Akarie** [comment]
@mattermoran You got that right, but  I didn't think any one would use the auto-generated paths explicitly.

**Comment by mattermoran** [comment]
Yeah I guess we are technically not suppose to but it's one of those instances where client asks if we can link to some page without releasing new version and here's the result haha. 
Either way I guess I was the only one so we could just close it :)
