### ISSUE TITLE
Tabs using path param route issue

### ISSUE THREAD

**Issue by ericvalero** [Milad-Akarie/auto_route_library#1656]
Hello,

The issue happens **when I reload the page**, for example, if I am on the second tab and reload, it will navigate to the first tab, but showing the second tab content.

I am setting tab child routes with path param, this is because the same route loads different data based on path param (:name) value:
```
AutoRoute(
  path: insightsPath,
  page: FatherRoute.page,
  initial: true,
  children: [
    // Tabs
    AutoRoute(
      path: ':name',
      page: TabRoute.page,
    ),
  ],
),
```
And using **AutoTabsRouter.tabBar**:
```
AutoTabsRouter.tabBar(
  physics: const NeverScrollableScrollPhysics(),
  routes: tabPages, // List of `PageRouteInfo` generated by code
  builder: (context, child, tabController) {
    return SliverScrollPage(
      title: entityValue.title,
      tabBar: TabBar(
        controller: tabController,
        isScrollable: true,
        indicatorWeight: 3,
        indicatorPadding: const EdgeInsets.symmetric(horizontal: 8),
        tabs: tabs, // List of `Tab` generated by code
      ),
      body: child,
    );
  },
);
```
I think the problem is something related to the **child** parameter of the **AutoTabsRouter.tabBar** builder, maybe is confused by the path param route, because the tab of index 0 should load the child of index 0.

How can I solve this issue?
Thanks in advance.

**Comment by Milad-Akarie** [comment]
@ericvalero I just made AutoTabsRoute match routes by key instead of name based on your valid use-case in version 7.7.1, you still need to explicitly inform auto_route that your tab-route uses paths as key

 ```dart
 AutoRoute(
      path: ':name',
      page: TabRoute.page,
     usesPathAsKey: true, // importent
    ),
```
make sure you close this if your issue is fixed

**Comment by ericvalero** [comment]
Thanks @Milad-Akarie its working now 😄
