### ISSUE TITLE
`AutoTabsScaffold` not updating

### ISSUE THREAD

**Issue by lrsvmb** [Milad-Akarie/auto_route_library#1657]
I have a very simple setup of the `AutoTabsScaffold` with 3 tabs, all with nested routing. Somehow, the initial tab cannot be set, even though the `context.router.currentUrl` returns the correct URL. I always land on the first child of the `routes` parameter. My simple dashboard configuration can be found below. I always land on the `MapRoute` even though I want it to start on the `HomeRoute`

```
AutoRoute(
    path: '/dashboard',
    page: DashboardRoute.page,
    children: [
      AutoRoute(
        path: 'chat',
        page: ChatRouteWrapper.page,
        children: [
          AutoRoute(path: '', page: ChatOverviewRoute.page),
          AutoRoute(path: ':id', page: ChatDetailRoute.page),
          AutoRoute(path: 'user', page: UserRoute.page),
        ],
      ),
      AutoRoute(
        path: 'map',
        page: MapRouteWrapper.page,
        children: [
          AutoRoute(path: '', page: MapRoute.page),
        ],
      ),
      AutoRoute(
        initial: true,
        path: 'home',
        page: HomeRouteWrapper.page,
        children: [
          AutoRoute(path: '', page: HomeRoute.page),
          AutoRoute(path: 'logbook', page: LogbookRoute.page),
          AutoRoute(path: 'files', page: FileRoute.page),
          AutoRoute(path: 'control', page: ControlRoute.page),
          AutoRoute(
            path: 'tours',
            page: TourRouteWrapper.page,
            children: [
              AutoRoute(path: '', page: TourRoute.page),
              AutoRoute(path: ':id', page: TourDetailRoute.page),
            ],
          ),
        ],
      ),
    ],
  ),
```

**Comment by Milad-Akarie** [comment]
@lrsvmb how do you navigate? is this a web App?

**Comment by lrsvmb** [comment]
@Milad-Akarie no this is an android app. I navigate using context.router.push() or similar

**Comment by lrsvmb** [comment]
@Milad-Akarie If that helps, here is my current `AutoTabsScaffold` implementation

```
return AutoTabsScaffold(
  appBarBuilder: (context, tabsRouter) => AppBar(
    leading: const AutoLeadingButton(),
    actions: [
      IconButton(
        onPressed: () => context.router.push(const SettingsRoute()),
        icon: const FaIcon(FontAwesomeIcons.userTie),
      ),
    ],
  ),
  routes: const [
    MapRoute(),
    HomeRoute(),
    ChatOverviewRoute(),
  ],
  homeIndex: 1,
  bottomNavigationBuilder: (_, tabsRouter) {
    return BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (a) {
        tabsRouter.setActiveIndex(a);
      },
      items: const [
        BottomNavigationBarItem(icon: FaIcon(FontAwesomeIcons.map), label: "Map"),
        BottomNavigationBarItem(icon: FaIcon(FontAwesomeIcons.houseFlag), label: "Home"),
        BottomNavigationBarItem(icon: FaIcon(FontAwesomeIcons.comments), label: "Chat"),
      ],
    );
  },
);
```

**Comment by Milad-Akarie** [comment]
@lrsvmb I can't see anything wrong in your code, btw homeIndex does not set the initial index, check the comments for more info, if you could make a smell repo I'll be sure to look at it.

**Comment by lrsvmb** [comment]
@Milad-Akarie Yeah I figured that `homeIndex` might not do that. One thing to note, though: When I add an `AutoRoute` in my dashboard section, that has no wrapper page and directly links to the contents page, it works with a `RedirectRoute`! So

```
RedirectRoute(path: '', redirectTo: 'home'),
AutoRoute(path: "home", page: HomeRoute.page),
```
works, but
```
RedirectRoute(path: '', redirectTo: 'home'),
AutoRoute(path: "home", page: HomeRouteWrapper.page, children: [
  AutoRoute(path: "", page: HomeRoute.page)
]),
```
does not work. I hope that helps as clarification. 👍

**Comment by Milad-Akarie** [comment]
@lrsvmb could you try explicitly setting the target tab when navigating 
`context.pushRoute(DashboardRoute(children: [HomeRouteWrapper()]))`

**Comment by Milad-Akarie** [comment]
I'm not sure what's going on, I tried a simple demo and everything seems to work fine, could you make a repo that reproduces the error?

**Comment by lrsvmb** [comment]
@Milad-Akarie am working on it 👍

**Comment by OwlCodR** [comment]
> @Milad-Akarie I have **finally** found the solution, it was (expectedly) my bad… Seems as if the `auto_route_generator: 7.1.1` did not work (or my version of `build_runner`), as it works now! Should have thought about that from the beginning, thank you for your help anyway! Will close this issue now 👍

+1, fixed by restarting codegen one more time
