### ISSUE TITLE
Is it possible to navigate to the same route with different parameters, treating it as a separate page?

### ISSUE THREAD

**Issue by jjoelson** [Milad-Akarie/auto_route_library#1658]
Hello!

Is there a way to navigate to the same route twice, but with different parameters such that the routing system treats it as a separate page?

My hope was that I could do something like this with `key` to tell the system to treat the two pages as separate (this is how `MaterialPage`'s `key` parameter works):
```
final id1 = '1';
final id2 = '2';

await context.router.navigate(
  MyRoute(
    key: ValueKey(id1),
    id: id1,
  ),
);

await context.router.navigate(
  MyRoute(
    key: ValueKey(id2),
    id: id2,
  ),
);
```

In auto_route 6 and 7 I'm observing that the key is passed to my underlying page widget but the route itself is unchanged, meaning there is no page transition. When I check `RouteData.of(context).key`, the key is the route name rather than the key I provided.

Is there a way to achieve this?

**Comment by Milad-Akarie** [comment]
Hey @jjoelson what you can do with the current setup is define your parameter as path parameter and add usesPathAsKey flag to your route

**Comment by jjoelson** [comment]
@Milad-Akarie That worked! Thank you for speedy response!
