### ISSUE TITLE
Upgrading error: auto_route >=0.6.2 depends on path ^1.7.0,

### ISSUE THREAD

**Issue by rubgithub** [Milad-Akarie/auto_route_library#166]
I'm getting this error when trying to upgrate to ^0.6.4

```
[test_mobile] flutter pub get
Running "flutter pub get" in test_mobile...                      
Because every version of flutter_test from sdk depends on path 1.6.4 and auto_route >=0.6.2 depends on path ^1.7.0, flutter_test from sdk is incompatible with auto_route >=0.6.2.

So, because test_mobile depends on both auto_route ^0.6.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because test_mobile depends on both auto_route ^0.6.4 and flutter_test any from sdk, version solving failed.)
exit code 1
```

**Comment by FakenMaster** [comment]
when you have a conflict library version in pubspec.yaml, you can add dependency_overrides in pubspec.yaml to solve that. 
In this case , add below content in pubspec.yaml .
```
dependency_overrides:
  path: ^1.7.0
```
[https://github.com/flutter/flutter/issues/20731](https://github.com/flutter/flutter/issues/20731)

**Comment by furins** [comment]
In general using a dependency override involves some risk: using an override to specify a version outside the range that the package claims to support may break your application. But in this case it seems safe since there are not breaking changes in path 1.7.0 vs 1.6.4 [https://pub.dev/packages/path/changelog].

**Comment by Milad-Akarie** [comment]
path package was downgraded to 1.6.4 in
```
 auto_route: 0.6.5
 auto_route_generator: 0.6.5
```
Thanks for reporting

**Comment by lanmonster** [comment]
I am not seeing `auto_route_generator: 0.6.5` on pub.dev. any ETA when this will be available?

**Comment by Milad-Akarie** [comment]
@lanmonster My bad, I thought I pushed it.. it is on pub.dev now.
