### ISSUE TITLE
Provider in Guard

### ISSUE THREAD

**Issue by xVemu** [Milad-Akarie/auto_route_library#1661]
How to access provider inside AutoRouteGuard?

I've tried to pass provider to AuthGuard and then pass guard to AppRouter, but I get `The instance member 'guard' can't be accessed in an initializer.` in routes.
![image](https://github.com/Milad-Akarie/auto_route_library/assets/38427679/1d087752-726b-4aac-b0b6-fe18dad676be)

Is there any way to do it?

**Comment by Milad-Akarie** [comment]
@xVemu  make your routes list late or make it a getter
`late final List<AutoRoute> routes = ...`
