### ISSUE TITLE
`deepLinkBuilder` does not cover `initialRoutes` usecase well on web

### ISSUE THREAD

**Issue by yendacoder** [Milad-Akarie/auto_route_library#1671]
According to deprecation notes, the advised way to support `initialRoutes` is to return the desired routes from the `deepLinkBuilder`. The problem is that the same builder is being called from the `setNewRoutePath`, which on web is triggered by the history navigation. This means that returning initial routes from the builder breaks browser history navigation altogether.

**Comment by Milad-Akarie** [comment]
@yendacoder Is there a reason why you're intercepting deep-links on web? this will always cause problems, although I think it's a good idea to to `PlatformDeepLink. initial` flag.

**Comment by yendacoder** [comment]
Thanks a lot for the quick response.
I need a splash screen/initializer route that has to be shown before anything else on any platform. I do save the initially requested url and forward the user accordingly after the initial interaction is complete.

**Comment by Milad-Akarie** [comment]
@yendacoder  you might want to consider using an AutoRouteGuard for that.

**Comment by yendacoder** [comment]
@Milad-Akarie thanks for the suggestion. I considered it, but thought that the `initialRoutes` was a bit cleaner solution because there's no risk of forgetting to add the guard to a new route.

**Comment by Milad-Akarie** [comment]
Have you tried a global guard?

**Comment by yendacoder** [comment]
Oh, I was on version 5 up until recently, didn't notice global guards. Will check it out, thanks.
