### ISSUE TITLE
Add allowSnapshotting property for AutoRoute and pass it to PageRoute.allowSnappshotting 

### ISSUE THREAD

**Issue by OptimisticSean** [Milad-Akarie/auto_route_library#1672]
As seen over [here](https://github.com/flutter/flutter/issues/119897#issuecomment-1550939992) and [here](https://api.flutter.dev/flutter/widgets/PageRoute/allowSnapshotting.html) , Flutter introduced an optimization (snapshotting) for the zoom page transition some time ago, which would make animations look frozen during page transition. Currently, I'm using CustomRoute with MaterialPageRoute to disable it on specific pages. Would be great if that property is directly available in AutoRoute.

**Comment by Milad-Akarie** [comment]
@OptimisticSean Done. Will be pushed with the new release.
