### ISSUE TITLE
Support for Latest android studio

### ISSUE THREAD

**Issue by funyin** [Milad-Akarie/auto_route_library#1673]
@Milad-Akarie Thank you so much for this amazing plugin and package. Could you please add support for the latest Android studio? Just upgraded  and I am unable to use the plugin because it is incompatible.

`Not compatible with the version of your running IDE (Android Studio Giraffe | 2022.3.1)`

**Comment by behzodfaiziev** [comment]
@funyin I found that a new support version is coming, according to a version update in master.

@Milad-Akarie That would be great to release a new update 😄
