### ISSUE TITLE
How to navigate/push with rootNavigator without using pushNativeRoute

### ISSUE THREAD

**Issue by ampersanda** [Milad-Akarie/auto_route_library#1675]
I have a nested route with tabbing, but inside the tab I wanted to push new page outside of the scope of nested route.

Normally I do `Navigator.of(context, rootNavigator: true).push()` with built-in Flutter navigator, so the page I push is shown full as new screen.

At the current state, `context.router.isRoot` is returning `false`, but I tried to push using `context.router.root?.navigate()` which `context.router.root?.isRoot` is `true`, but it shows the same thing 

Is there any way to push with `rootNavigator` set to `true` using `context.router.navigate()`?

**Comment by Milad-Akarie** [comment]
@ampersanda are you using the same page as a nested page somewhere?

**Comment by ampersanda** [comment]
uhm, sorry, I'm not sure what you meant, but here's the hierarchy, hopefully it helps 

```
/dashboard
└── /patients
    ├── /consultation-tab
    │   └── /detail
    └── /vaccine-tab
```

I need to push `/detail` full page but it kept nested inside `/patients` like this

<img width="643" alt="Screenshot 2023-08-03 at 21 29 58" src="https://github.com/Milad-Akarie/auto_route_library/assets/13579812/d8b3ea1e-e3b0-4034-bd31-7a96f8e916fd">

**Comment by Milad-Akarie** [comment]
Oh, ya you can't do that, for now, hierarchies are predefined and can not be overridden, what you can do is define the same page in the root scope or whatever scope you want it to show in.

**Comment by ampersanda** [comment]
Oh noes :(...

I just tired to access `context.root` it turns out never be a `StackRouter`, it keeps returning `NestedStackRouter`. Am I missing something from the docs?

![image](https://github.com/Milad-Akarie/auto_route_library/assets/13579812/06106556-127a-4788-b88f-cb4f14b2c9ea)

**Comment by Milad-Akarie** [comment]
@ampersanda  I did not quite understand your question?

**Comment by ampersanda** [comment]
I'm sorry, nevermind
