### ISSUE TITLE
Push between tab routers with a back stack

### ISSUE THREAD

**Issue by derTuca** [Milad-Akarie/auto_route_library#1677]
Hi, I have the following navigation tree and what I'd like to do is to push from `MainRoute` to `ArtistRoute`:

- EventTabRoute (`/event`)
  - ExperiencesTabRoute(`/experiences`)
    - ArtistRoute(`/artist`)
  - TimelineTabRoute(`/timeline`)
    - MainRoute(`/main`)
    
 What I would prefer is to be able to push the pages onto the stack, rather than navigate. Right now I am doing the following from MainRoute: `context.tabsRouter.navigate(ExperiencesTabRoute(children: [ArtistRoute()]))`, but if the user presses back, the app quits since the ExperiencesTabRoute's stack is empty.

What I'd like is if the user pressed back, they should be navigated back to MainRoute, since that's the user's natural flow (with the fact that the page is on another tab being more of an afterthought).

**Comment by Milad-Akarie** [comment]
@derTuca  try using context.router.back() instead of pop();
