### ISSUE TITLE
IOS swipe back with CustomRoute

### ISSUE THREAD

**Issue by SFocus** [Milad-Akarie/auto_route_library#1683]
Hello! 

I know there have been similar open questions here before. But I still haven't figured out the solution to this problem. And I think many people have the same problem.

Swipe back is disabled only on the IOS platform when I tried to use `CustomRoute`. I'm using `transitionsBuilder` to set custom animation in CustomRoute and in this case back swipe doesn't work for me.

I've seen suggestions to use `CupertinoRoute`, but I can't specify a different transition there. 

Could you give more information or a better example for everyone how to solve this problem? 

Error no **transitionsBuilder**
```
CupertinoRoute(
      page: CountryCodeRoute.page,
      path: '/country-code',
      transitionsBuilder: TransitionsBuilders.fadeIn,
    ),
```

Here swipe back doesn't work only on IOS, Android works fine. 
```
 CustomRoute(
      page: CountryCodeRoute.page,
      path: '/country-code',
      transitionsBuilder: TransitionsBuilders.fadeIn,
    ),
```

**Comment by Milad-Akarie** [comment]
@SFocus The swipe back gesture is implemented inside of Cupertino route so I guess that not possible, you may try to override it and play with the animation.

**Comment by lwj1994** [comment]
https://pub.dev/packages/swipeable_page_route

you can build custom SwipeablePageRoute  
```dart
   @override
  RouteType get defaultRouteType => _buildRouteType();

  RouteType _buildRouteType({
    bool canOnlySwipeFromEdge = true,
    Duration transitionDuration = const Duration(milliseconds: 200),
    Duration reverseTransitionDuration = const Duration(milliseconds: 200),
  }) {
    return RouteType.custom(
        customRouteBuilder: <T>(
          BuildContext context,
          Widget child,
          AutoRoutePage<T> page,
        ) {
          return SwipeablePageRoute(
              canOnlySwipeFromEdge: canOnlySwipeFromEdge,
              transitionDuration: transitionDuration,
              reverseTransitionDuration: reverseTransitionDuration,
              settings: page,
              builder: (BuildContext context) {
                return child;
              });
        },
        durationInMilliseconds: transitionDuration.inMilliseconds,
        reverseDurationInMilliseconds: reverseTransitionDuration.inMilliseconds,
        transitionsBuilder: TransitionsBuilders.slideLeftWithFade);
  }
```

@SFocus

**Comment by fadilhim** [comment]
hi @lwj1994! , i was able to use your solution but i found it error when the route has return value. it shows SwipeablePageRoute is not subtype of AutoRoute<bool>
i already tried to change it with SwipeablePage as https://pub.dev/packages/swipeable_page_route documentation but no luck. could you help me on this?
