### ISSUE TITLE
[Question] Is it possible to use Hero animations with auto_route?

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [Milad-Akarie/auto_route_library#169]
Hello, I am new to both Flutter and auto_route, I've tried to do a Hero transition with the Hero component provided by Flutter, but the animation seems to be not working at all. Is this related to the use of the ExtendedNavigator?

Thank you in advance.

**Comment by Milad-Akarie** [comment]
@alvarezGarciaMarcos yes it is, we just had a big upgrade and the hero controller code was lost in the process lol 
anyways. it should work fine the latest build
```dart
auto_route: 0.6.6
auto_route_generator: 0.6.6
```
Thanks for reporting
