### ISSUE TITLE
Routes that are not home route doesn't work when I host the web app

### ISSUE THREAD

**Issue by Mohamed-7018** [Milad-Akarie/auto_route_library#1691]
I have built a web app using flutter, and I used auto router package to handle the routes. The app was working good on local host,but when I hosted it on the internet all the routes doesn't work except the home route.  I don't what is actually the problem.

to explain the problem:
### when I use localhost:
localhost:61400/: It returns the home route
localhost:61400/register: It returns the register route

### But when I hosted it:
domain.site/ : It returns the home route
domain.site/register: It returns 404

### "Flutter doctor -v " output:
![image](https://github.com/Milad-Akarie/auto_route_library/assets/80456446/210b0a8d-716c-4554-8fee-fcd222cb0585)

**Comment by Milad-Akarie** [comment]
@Mohamed-7018 not sure what the problem is here but you can try upgrading flutter to the latest version and auto-route to the latest version ( just published a release ) and see if you still have the problem.

does this happen when you use hash path strategy?

**Comment by Mohamed-7018** [comment]
Actually this error occurs only when I use hash path strategy.

**Comment by Mohamed-7018** [comment]
Actually, the problem occurs only when I use hash path strategy, I solved this problem by removing the hash strategy
