### ISSUE TITLE
Critical error in route_information_parser in version 7.8.1 

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1695]
@Milad-Akarie After updating to version 7.8.1 we start getting these errors in our tests

> ../../../../../../.pub-cache/hosted/pub.dev/auto_route-7.8.1/lib/src/router/parser/route_information_parser.dart:25:34: Error: The getter 'uri' isn't defined for the class 'RouteInformation'.
>  - 'RouteInformation' is from 'package:flutter/src/widgets/router.dart' ('../../../../../../fvm/versions/3.10.6/packages/flutter/lib/src/widgets/router.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'uri'.

**Comment by Milad-Akarie** [comment]
@MartinAKovachev I should've made this a major update, you're propaply getting the error because you're using flutter 3.10.6 and not the latest 3.13.0

**Comment by MartinAKovachev** [comment]
Yes, you are correct.

**Comment by renefloor** [comment]
> I should've made this a major update, you're propaply getting the error because you're using flutter 3.10.6 and not the latest 3.13.0

@Milad-Akarie it shouldn't be a major version, preferably patch or minor if it's not a breaking change (which it isn't), but minimal sdk in the pubspec should have been updated. https://github.com/Milad-Akarie/auto_route_library/blob/master/pubspec.yaml#L5
Either sdk: 3.1.0 (it's the dart version) and/or add `flutter: ">=3.13.0"`

**Comment by PollyGlot** [comment]
I am on Flutter 3.10.6 and package version 7.7.0 and I have the same error.

**Comment by Milad-Akarie** [comment]
@renefloor exactly! how did I miss that? fixed in version 7.8.2
@PollyGlot that should be impossible, maybe you declare your version as ^7.7.0

**Comment by PollyGlot** [comment]
> @renefloor exactly! how did I miss that? fixed in version 7.8.2 @PollyGlot that should be impossible, maybe you declare your version as ^7.7.0

Yes, you are right, I was using ^7.7.0, so as a temporal fix I use a fixed version and I could build for Android

**Comment by Milad-Akarie** [comment]
I guess it's safe to close this now.
