### ISSUE TITLE
The problem with deep links if there is a third-party solution for managing deep links

### ISSUE THREAD

**Issue by sergey-aliyev-m10** [Milad-Akarie/auto_route_library#1697]
There was a problem with the use of auto_route in the conditions of the already implemented functionality for managing deep links and I don't want manage deep links by this callback. Is there any way other than below to disable this functionality?

```
deepLinkBuilder: (link) {
  final isInitialPath = link.path == '/';
  final isEmptyRouter = _appRouter.pageCount == 0;

  if (isInitialPath || isEmptyRouter) {
    return link;
  }

  return DeepLink.none;
}
```

**Comment by Milad-Akarie** [comment]
@sergey-aliyev-m10  what are you trying to do exactly? 
btw this line   final isInitialPath = link.path == '/'; isn't always going to work because an initial deep-link can be anything 
try checking against link.initial property

**Comment by sergey-aliyev-m10** [comment]
My problem is that I can not refuse this functionality, there is no leverage. My project has its own deep linking feature that uses the auto_route API for navigation. If I minimize the application, go to any messenger and click a deep link from there, the application will open, show the last screen that was there before minimizing for a split second, and then the logic wired into the auto_route for processing deep links will work, which is undesirable for me. But I didn’t implement anything there, I already have my own functionality for this, but when the resumed application starts to work out some kind of deep link processing logic, which does not find a suitable route for my link and simply puts the most initial route '/' at the top. At first I thought that I could just make a deepLinkBuilder and return DeepLink.none from it. But it turns out that this generally affects the initial route and everything will break. Therefore, I described deepLinkBuilder in the way I presented it above. This works for me. The question was, is there any other way to do this?

**Comment by Milad-Akarie** [comment]
@sergey-aliyev-m10 built-in deep-linking will only work if you set it up on the native side e.g on android you would have to add 
` <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />`
so if you don't want flutter to automatically handle your deep-links don't include the above line

**Comment by sergey-aliyev-m10** [comment]
It really helped, thanks a lot
