### ISSUE TITLE
Best way to access to nav stack

### ISSUE THREAD

**Issue by muezz** [Milad-Akarie/auto_route_library#1704]
What is the best way to access the current router stack?
For example, if the user does the following
- initially at `screenA`
- push to `screenB`
- replace with `screenC`
- push to `screenD`
I would expect to get an array or something that preserves the order like: 
```dart
context.router.getStackOrSomeSimilarMethod; // => [screenA, screenC, screenD]
```

My use case is that I want to run particular pieces of logic depending on where the user came from. In particular, I would need to check the last and second last route in the stack.

I understand that there are some complex topics like web and nested routing that might make this somewhat difficult to achieve. In my case, web is not involved at all and ALL of my routes are in the top router (i.e. there is no nested navigation).

**Comment by Milad-Akarie** [comment]
@muezz I believe  context.router.stackData is what you're looking for!

```dart
 for(var route in context.router.stackData){
       print(route.name);
     }
```
