### ISSUE TITLE
Relaunch deeplink while on same page

### ISSUE THREAD

**Issue by Abdelrahman-Sherif** [Milad-Akarie/auto_route_library#1705]
Hey Milad, is there a way to relaunch the deeplink while still on the same page?

My deeplink works well, but I need that upon relaunching, it relaunches the screen again with the new parameters. As long as i am still on the same screen, this doesn't happen.

Issue only happens when using declarative delegate, using normal navigation works good when using the rebuildStackOnDeepLink=true parameter

Here is a small snippet of my routes, where "fbop" is the "deeplink" page.

AutoRoute(
    page: WrapperRoute.page,
    path: '/',
    children: [
      AutoRoute(
        page: ConfirmEmailRouteLoader.page,
        initial: true,
        path: 'confirmEmail',
        keepHistory: false,
      ),
      AutoRoute(
        page: FirebaseOpsRouteLoader.page,
        path: 'fbop',
      ),
    ],
  ),

**Comment by Abdelrahman-Sherif** [comment]
Might be useful to note that placing a button on the page that "relaunches" it does work, so the problem does not lie in the routes setup.

**Comment by Milad-Akarie** [comment]
@Abdelrahman-Sherif I'd suggest that you avoid using declaration routing in your root router, as it proved a lot of issues when implemented with deep-links, consider using route guards instead.
