### ISSUE TITLE
How to handle flutter bottom navigation bar when back button is pressed to go to the HomeScreen

### ISSUE THREAD

**Issue by Madyan786** [Milad-Akarie/auto_route_library#1706]
please help me i created bottom navigation bar in which i have five tabs but when i click on back buttion in every tab then its exit the app why?

**Comment by Milad-Akarie** [comment]
@Madyan786 what you need is assigning a home index so the host the route is only popped if the index == homeIndex `AutoTabsRouter(homeIndex: 0)`
