### ISSUE TITLE
How to use riverpod ProviderScope with push

### ISSUE THREAD

**Issue by HasanAlqaisi** [Milad-Akarie/auto_route_library#1709]
Hi,
I want to be able to pass the ProviderScope to override some providers with riverpod.
I tried to do this:
```
AutoRouter.of(context).push(
ProviderScope(overrides: [currentDoctorProvider.overrideWithValue(doctor)],
child: const ReviewsPage()),
);
```
But since push requires `PageRouteInfo`, that won't be possible.
Is there another way to do this?
I tried:
```
AutoRouter.of(context).pushWidget(
ProviderScope(overrides: [currentDoctorProvider.overrideWithValue(doctor)],
child: const ReviewsPage()),
);
```
It works but I am using bottom navigation with nested navigation, and if I use it, it will changes the desired behavior.

**Comment by HasanAlqaisi** [comment]
I didn't know about [Wrapping Routes](https://github.com/Milad-Akarie/auto_route_library#wrapping-routes).
Closing since this can fix the problem.

**Comment by tomasweigenast** [comment]
Sorry this is old, but how did you solve it? Can you paste an example?

**Comment by HasanAlqaisi** [comment]
> Sorry this is old, but how did you solve it? Can you paste an example?

As far as I remember. From my example above, the idea is to pass the **doctor** object to the **ReviewsPage**
``` dart
@RoutePage()
class ReviewsPage extends StatelessWidget implements AutoRouteWrapper {
  final Doctor doctor;

  ReviewsPage(this.doctor);
  
  @override
  Widget wrappedRoute(BuildContext context) {
    return ProviderScope(
    overrides: [currentDoctorProvider.overrideWithValue(doctor)],
    child: this,
    );
  }
  ...
}
```

**Comment by tomasweigenast** [comment]
Ah, you pass the doctor object to the widget, I was trying to fetch it in the widget itself then passing using scope.
