### ISSUE TITLE
Using helper methods without context

### ISSUE THREAD

**Issue by sharpsan** [Milad-Akarie/auto_route_library#171]
In auto_route v0.6.2 you specified in your changelog: `Remove ExtendedNavigator.ofRouter method`
However, the documentation still specifies `ExtendedNavigator.ofRouter` is the correct way to use helper methods: `ExtendedNavigator.ofRouter<Router>().pushSecondScreen(args...)`

My question is how can I still use helper methods to push routes with params without a context?

**Comment by Milad-Akarie** [comment]
Hey @sharpsan please refer to [this](https://github.com/Milad-Akarie/auto_route_library#navigation)

**Comment by bounty1342** [comment]
Should change the reference to ofRouter<Router> there : https://github.com/Milad-Akarie/auto_route_library#navigation-helper-methods-extension.

Probably give a full exemple of custom router also.

**Comment by bounty1342** [comment]
Yes with the last push 👍

**Comment by sharpsan** [comment]
Thanks for pointing me in the right direction.  

I'm not too fond of the new requirement to specify the router by name using a string.  Seems like something that should be auto-generated to prevent mis-typing or the need to separately keep track of router names in a constants file.

**Comment by Milad-Akarie** [comment]
@sharpsan I'm planning on coming up with easier ways to access nested navigators without context so stay tuned

**Comment by Milad-Akarie** [comment]
closing this for now.
