### ISSUE TITLE
Redirect to the First Route 

### ISSUE THREAD

**Issue by raaz0n** [Milad-Akarie/auto_route_library#1714]
When I refresh any of these routes its redirect to the First route which is PrivacyPolicyRoute, But the slug is dynamic  for each route 
<img width="466" alt="image" src="https://github.com/Milad-Akarie/auto_route_library/assets/36769862/2e95d395-349a-4b67-92fc-7fa19981399b">

**Comment by Milad-Akarie** [comment]
@rajan-poudel that makes sense because all of your routes have the same path, the first path satisfies the patter so it picks it. 
what you can do is add a subfix after the /page to for each path like 

/page/privacy-policy/:slug
/page/terms/:slug 
...etc

**Comment by rajan-poudel** [comment]
Ok Thank You @Milad-Akarie
