### ISSUE TITLE
How to make bottomAppBar with FAB with notchedMargin using auto_route? 

### ISSUE THREAD

**Issue by ortemmetro** [Milad-Akarie/auto_route_library#1717]
How to correctly and effectively implement this behaviour?

**Comment by ortemmetro** [comment]
I managed to create only this type of bottomAppBar:
`
@RoutePage()
class MainPage extends StatefulWidget {
  const MainPage({super.key});

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      floatingActionButton: FloatingActionButton(
        //Floating action button on Scaffold
        onPressed: () {
          //code to execute on button press
        },
        child: const Icon(Icons.add), //icon inside button
      ),

      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      //floating action button location to left
      routes: const [
        HomeRoute(),
        StatisticsRoute(),
      ],
      bottomNavigationBuilder: (context, tabsRouter) {
        return BottomNavigationBar(
          currentIndex: tabsRouter.activeIndex,
          onTap: tabsRouter.setActiveIndex,
          items: const [
            BottomNavigationBarItem(
              label: "Home",
              icon: Icon(Icons.home),
            ),
            BottomNavigationBarItem(
              label: "Stats",
              icon: Icon(Icons.bar_chart),
            ),
          ],
        );
      },
    );
  }
}
`

![изображение](https://github.com/Milad-Akarie/auto_route_library/assets/79922019/4df291b8-d6b5-4a2e-b805-95ca4b0923d6)

**Comment by Milad-Akarie** [comment]
@ortemmetro I don't quite understand the issue here.

**Comment by ortemmetro** [comment]
@Milad-Akarie How can I achieve this UI using auto_route package?
![изображение](https://github.com/Milad-Akarie/auto_route_library/assets/79922019/3ae476d1-d369-4cca-8259-3c1e805c0afb)

**Comment by Milad-Akarie** [comment]
@ortemmetro actually this's irrelevant to the auto_route package, what you can do is find a bottom-navigation-bar library that can do this and hook it up with auto_route navigation.

**Comment by ortemmetro** [comment]
Okay, thanks!
