### ISSUE TITLE
Reason to update update sdk constrains to flutter: >=3.13.0 ?

### ISSUE THREAD

**Issue by akadatsky** [Milad-Akarie/auto_route_library#1725]
Is there really a need to update the minimal version of Flutter to 3.13.0?

In my project, I use Flutter prior v3.13 and will force to stay with auto_route: 7.8.1, without further updates

**Comment by nguyenhuutukhtn** [comment]
Agree! Flutter v3.13 has some severe bug and Flutter team need release a hotfix version. Constrains with version flutter make my project have to choose option. Use old flutter version with bug in auto_route <7.8.1, or use lastest auto_route with bug of Flutter v3.13

**Comment by Milad-Akarie** [comment]
you can safely stick to auto_route 7.8.1 for now it has no major changes then constraining the flutter version.
