### ISSUE TITLE
Default global route transition

### ISSUE THREAD

**Issue by Jethro87** [Milad-Akarie/auto_route_library#1743]
In the documentation, it says `Tip: override defaultRouteType in generated router to define global custom route transitions.`

I've been using this method to define global transitions, but it's a bit annoying, as whenever I make changes to any routes the generated file gets overwritten and I have to add back my code. Is there a way (or can a way be built) to specify global route transitions in the AppRouter file instead of the generated AppRouter?

Here's my code, for reference:

```
  @override
  RouteType get defaultRouteType => isWeb || isMacOS
      ? RouteType.custom(
          transitionsBuilder: (context, animation, secondaryAnimation, child) {
            return FadeTransition(
              opacity: animation,
              child: child,
            );
          },
          durationInMilliseconds: 125,
          reverseDurationInMilliseconds: 125,
        )
      : RouteType.material();
```

**Comment by a-h-mzd** [comment]
@Jethro87 Add the override code to your AppRouter class and the generator takes care of everything else.

**Comment by Jethro87** [comment]
@a-h-mzd Thanks! I could have sworn I tried that, but apparently, I did not.
