### ISSUE TITLE
AutoRoute Helper not available with Android Studio Giraffe | 2022.3.1 Patch 2

### ISSUE THREAD

**Issue by mirabo-vuong-nt** [Milad-Akarie/auto_route_library#1748]
I can not search AutoRoute Helper from Plugins Marketplace, so i manually download it and "Install from disk".
Then I got an error message below:
![Screenshot 2023-09-29 at 15 29 58](https://github.com/Milad-Akarie/auto_route_library/assets/123710038/268a2398-9430-47dd-b8b4-bd4ef3394103)

Plz support it as soon as possible

**Comment by yeras-is** [comment]
We need support

**Comment by yeras-is** [comment]
@Milad-Akarie

**Comment by Milad-Akarie** [comment]
@yeras-is updated submitted and  pending review

**Comment by Milad-Akarie** [comment]
for disk installs 
https://github.com/Milad-Akarie/auto_route_library/blob/master/tools/AutoRoute-Helper-0.1.6.jar

**Comment by mirabo-vuong-nt** [comment]
thanks for your services! @Milad-Akarie

**Comment by Mr4Mike4** [comment]
AutoRoute Helper does not work on Android Studio Giraffe | 2022.3.1 Patch 3

https://github.com/Milad-Akarie/auto_route_library/assets/6643879/3bb21dc1-bfec-4149-8524-13abc2a7d268

**Comment by dJani97** [comment]
> Plugin 'AutoRoute Helper' (version '0.1.6') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is AI-241.15989.150

**Comment by Milad-Akarie** [comment]
@dJani97 I'm sorry but the plugin is no longer supported. feel free to clone and edit your self.
