### ISSUE TITLE
system "back" button close app in nested navigation

### ISSUE THREAD

**Issue by prostreet1212** [Milad-Akarie/auto_route_library#1749]
Hellow. When you run the flutter run --release command or --profile, the system "back" button closes the application, instead of returning to the previous page, according to the route. How to fix it?

**Comment by itxtoledo** [comment]
just wrap your first screen with WillPopScope and do your verification

**Comment by Milad-Akarie** [comment]
@prostreet1212 show some code

**Comment by prostreet1212** [comment]
strange, but the problem turned out to be in this event of my imagebloc, which is called in the build method of one of the nested views

Future _checkAndDownloadImageEvent(
      CheckAndDownloadImageEvent event, Emitter<ImageState> emit) async {
    if (state.image == null) {
      if (event.url.isNotEmpty) {
        emit(state.copyWith(avatarStatus: AvatarStatus.loading));
        /*authBloc.add(
            const ChangeAvatarStatusEvent(avatarStatus: AuthStatus.loading));*/
        Dio dio = Dio();
        Response response = await dio.get(event.url,
            options: Options(responseType: ResponseType.bytes));

        final Directory appDirectory = await getTemporaryDirectory();
        Reference storageReference = FirebaseStorage.instance
            .ref()
            .child('users')
            .child(event.uid)
            .child('avatar')
            .child(event.uid);
        FullMetadata uploadTask1 = await storageReference.getMetadata();
        String typeFile = uploadTask1.contentType!;
        typeFile =
            typeFile.substring(typeFile.indexOf('/') + 1, typeFile.length);
         String filePath = '${appDirectory.path}/${event.uid}.$typeFile';
        File file = File(filePath);
        String newFilePath = '${appDirectory.path}/${event.uid}_new.$typeFile';
        File newFile = File(newFilePath);


        if(await file.exists()){
          await file.delete().whenComplete(() async{

            newFile = await newFile.writeAsBytes(response.data);
            emit(state.copyWith(image: newFile,avatarStatus: AvatarStatus.success,avatarUrl: event.url));
          });
        }else if(await newFile.exists()){
         await newFile.delete().whenComplete(()async {
           file = await file.writeAsBytes(response.data);
           emit(state.copyWith(image: file,avatarStatus: AvatarStatus.success,avatarUrl: event.url));
         });
        }else{
          file = await file.writeAsBytes(response.data);
          emit(state.copyWith(image: file,avatarStatus: AvatarStatus.success,avatarUrl: event.url));
        }



        /*authBloc.add(
            const ChangeAvatarStatusEvent(avatarStatus: AuthStatus.success));*/
      }
    }
  }
namely in the lines:
authBloc.add(
            const ChangeAvatarStatusEvent(avatarStatus: AuthStatus.loading));
authBloc.add(
            const ChangeAvatarStatusEvent(avatarStatus: AuthStatus.success));

I removed these lines in profile and release modes, everything worked correctly.

The question is closed.

**Comment by Milad-Akarie** [comment]
That is strange! Guess it's safe to close this now
