### ISSUE TITLE
[Question] Shouldn't usesPathAsKey work in this case ?

### ISSUE THREAD

**Issue by bounty1342** [Milad-Akarie/auto_route_library#1752]
Hi,

I have declare the following routes:
```
    MaterialRoute(path: 'regions/*', guards: [CatalogGuard()], page: CatalogPageScreenRoute.page, usesPathAsKey: true),
    RedirectRoute(path: 'regions', redirectTo: 'regions/*'),
    MaterialRoute(path: 'networks/*', guards: [CatalogGuard()], page: CatalogPageScreenRoute.page, usesPathAsKey: true),
    RedirectRoute(path: 'networks', redirectTo: 'networks/*'),
```

When I try to access the below path, the first one succeed but not the other one.
`      final path = ["/app/catalogue/networks/bretagne", "/app/catalogue/regions/bretagne"];
`
Seems it keeps only the last route for the same page. 
I thought usesPathAsKey could help, but I think I miss something. Any idea ?

Thank you :)

edit:     

```
MaterialRoute(path: 'regions/bretagne', page: CatalogPageScreenRoute.page, usesPathAsKey: true),
MaterialRoute(path: 'networks/bretagne', page: CatalogPageScreenRoute.page, usesPathAsKey: true),
```

produce the same result :(

**Comment by Milad-Akarie** [comment]
Hey @bounty1342 I can't seem the understand your question, can you start by explaining the use-case? what are you trying to achieve?

**Comment by bounty1342** [comment]
Ki @Milad-Akarie, I'm migrating from 5.x.x to the last version.

The "region" and "network" where two routes on the same page, setup with différents names.

In the last version, the name being on the annotation rather than the declaration, they end up declared with the same page but different path, as shown in the previous post.

Those paths are use for deeplink for example and could not be changed.

**Comment by Milad-Akarie** [comment]
@bounty1342  yes, you can have different paths point to the same page with no problem, and setting usesPathAsKey will have the pages stack manager treat them as two different pages. 

do you have a problem with this setup?

**Comment by bounty1342** [comment]
Yes, only the last declared page will match. 😔

**Comment by Milad-Akarie** [comment]
@bounty1342 you mean when you navigate by PageRouteInfo?

**Comment by bounty1342** [comment]
When a use a deeplink,

`MaterialRoute(path: 'regions/bretagne', page: CatalogPageScreenRoute.page, usesPathAsKey: true),
MaterialRoute(path: 'networks/bretagne', page: CatalogPageScreenRoute.page, usesPathAsKey: true),`

/app/catalog/networks/bretagne will match
But /app/catalog/regions/bretagne will not.

**Comment by Milad-Akarie** [comment]
@bounty1342 Yup that should happen, it just hit me, what you need to do is something like this 

```dart
@RoutePage()
class NetworksPageScreen extends CatalogPageScreen{
  const NetworksPageScreen({Key key}) : super(key: key);
}

```
then use each page for one path.

There's a pending task of creating what I call "Page Aliases" which is gonna make things easiter

**Comment by bounty1342** [comment]
Thanks you, it worked.  Sorry if my question wasn't very clear at the beggining.

I presume you understand now why I wonder about 'usesPathAsKey'. 
It seem, there is some places that still rely on the name of the page rather than the 'key'.

Also thank you for all the work you do. 🙏
