### ISSUE TITLE
Navigation doesn't work properly, if `AutoRouteGuard.onNavigation` method is overridden as async method

### ISSUE THREAD

**Issue by MartinAKovachev** [Milad-Akarie/auto_route_library#1764]
@Milad-Akarie We have a custom `AutoRouteGuard` in which we override `onNavigation` as async method.

```dart
class CustomRouteGuard extends AutoRouteGuard {
  CustomRouteGuard({
    required SomeUseCase someUseCase,
  })  : _someUseCase = someUseCase;

  final SomeUseCase _someUseCase;

  @override
  Future<void> onNavigation(NavigationResolver resolver, StackRouter router) async {
    final someResult = await _someUseCase();
 
    if (someResult.isTrue) {
        resolver.next();
    } else {
        resolver.next(false);
    }
  }
``` 

Is that correct, because `onNavigation` is sync by default. We noticed a strange behaviour in some cases, if we await something before calling `resolver.next()`?

This might be related to another issue with the deep links handling https://github.com/Milad-Akarie/auto_route_library/issues/1668.

**Comment by Milad-Akarie** [comment]
Hey @MartinAKovachev marking navigation as async should not have any effect because the method is not being awaited, the NavigatorResolver is.
what kind of strange behavior are you getting?
