### ISSUE TITLE
auto_route_generator import error

### ISSUE THREAD

**Issue by FakenMaster** [Milad-Akarie/auto_route_library#177]
In generated file route.gr.dart , sometime will import below line. 

> import '../../flutter/material.dart';

 That's because of import_resolver.dart line 24 check, the path 'package:flutter/material.dart' will be replaced with the relative path.

**Comment by FakenMaster** [comment]
Don't know why author need replace the import path with relative path. I just remove auto_route_generator library code in import_resolver line 24 - 28, then everything is ok.

**Comment by Milad-Akarie** [comment]
Hey @FakenMaster using relative imports is guided by effective dart.
 I'll take a look!

**Comment by Milad-Akarie** [comment]
@FakenMaster is your package name 'flutter'?

**Comment by FakenMaster** [comment]
No, my package name isn't 'flutter'. It's weired.

**Comment by Milad-Akarie** [comment]
@FakenMaster I still don't understand why your package import was imported as a relative path, but I did some changes in 
```yaml
auto_route: 0.6.7
auto_route_generator: 0.6.7
```
could you check if you're still getting the error? 
also, I added an option to not prefer relative imports just in case!
`MaterialAutoRouter(preferRelativeImports: false,...)`

**Comment by cgalvar** [comment]
I have the same issue in the lastest version 0.6.7, preferRelativeImports is not available yet, and indeed my package name has the word flutter on it

**Comment by cgalvar** [comment]
I can confirm that changing the name of my package fixed the issue, Greetings.

**Comment by FakenMaster** [comment]
> @FakenMaster I still don't understand why your package import was imported as a relative path, but I did some changes in
> 
> ```yaml
> auto_route: 0.6.7
> auto_route_generator: 0.6.7
> ```
> 
> could you check if you're still getting the error?
> also, I added an option to not prefer relative imports just in case!
> `MaterialAutoRouter(preferRelativeImports: false,...)`

Sorry for the late response. Yes, after upgrading 0.6.7, the problem is gone! Congratulations! Thx man.
@Milad-Akarie . 
By the way , as @cgalvar mentioned, under 0.6.6 version, if the package name contains "flutter", it will cause the problem. So it's the source of problem. Thanks @cgalvar .
So the fix solutions ,it's either upgrade to 0.6.7 or avoid using "flutter" in the package name.
👏👏👏
