### ISSUE TITLE
pushNamed with object(s)

### ISSUE THREAD

**Issue by abdallah-odeh** [Milad-Akarie/auto_route_library#1777]
Is there any plans to support passing an object or list of objects with **pushNamed** function?
I am currently using the `onGenerateRoute` function that goes to screen by it's name and parse the passed `arguments` according to the current screen name as follow:
```
case MyScreen.routeName:
  return SplitExpenseScreen.route(settings.arguments as MyScreenArgsObject);
```
so my whole app is built on this logic 
```
Navigator.of(context).pushNamed(MyScreen.routeName,
              arguments: MyScreenArgsObject(object.id, groupId: object.groupId, type: object.type));
```

so is there a way to convert the returned `Route` instance from `onGenerateRoute` to your `PageRouteInfo` object

**Comment by Milad-Akarie** [comment]
@abdallah-odeh I'm afraid not
