### ISSUE TITLE
Question how to open a page(NestedRouter) from notification 

### ISSUE THREAD

**Issue by charm-cloud** [Milad-Akarie/auto_route_library#178]
Hi,thanks for the great library.

how to  maintain backstack i.e. preserve navigation ,as i open page from a pending intent i.e notification similar to android TaskStackBuilder

**Comment by Milad-Akarie** [comment]
How does the path you get from your notification looks like?

**Comment by charm-cloud** [comment]
It tend to open a page which is  inside bottom nav ->detailpage-> detailpage1 ->detailpage2

**Comment by Milad-Akarie** [comment]
@charm-cloud What's your navigators setup? do you have a root navigator that has parallel navigators?

**Comment by Milad-Akarie** [comment]
In a straightforward nested setup that looks like the following
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: HomeScreen, initial: true),
    MaterialRoute<void>(
      path: '/users/:id',
      page: UsersScreen,
      name: 'usersScreen',
      children: [
        MaterialRoute(path: '/', page: ProfileScreen),
        MaterialRoute(
          path: '/posts',
          page: PostsScreen,
          children: [
            MaterialRoute(path: '/', page: PostsHome),
            MaterialRoute(path: '/details', page: PostDetails),
          ],
        ),
      ],
    ),
  ],
)
```

simply setting your initial route to `/users/1/posts/details` will take you to your destination and maintain the back stack

**Comment by charm-cloud** [comment]
Thank you so much for your help , i think i need to upgrade from 0.5.0 ,and the same  approach will work for  this https://github.com/Milad-Akarie/parallel-navigation-demo-auto-route ,i just found the sample

**Comment by Milad-Akarie** [comment]
It should be simple to migrate but, in case you get lost 
https://github.com/Milad-Akarie/auto_route_library#migration-guide

**Comment by charm-cloud** [comment]
will this approach work for parallel navigators also ?

**Comment by Milad-Akarie** [comment]
It's not that simple, you need to assign the initial route (the nested path) to the targeted navigator not the root navigator.

**Comment by charm-cloud** [comment]
Thank you for your help
