### ISSUE TITLE
Navigation history lost when resizing in responsive design

### ISSUE THREAD

**Issue by touficzayed** [Milad-Akarie/auto_route_library#1780]
Hi,

I really like autoroute over any other routing frameworks, and I really want to use it in my projects.

It's almost perfect for my use cases, except for one thing: I do not succeed to make it work with responsive design, when I resize the app window.

I have set up a repository with an example:

https://github.com/touficzayed/autoroute_test

When you run the app, simply navigate to screen one or two to fill the navigation stack on one or both tabs or navigation rails.

Then resize the app window. The responsive design apply but all the navigation history is lost. Like the app has been reset.

I could achieve easily a working behaviour with go router or beamer but I don't want to use these frameworks.

Is it a bug or am i doing something wrong?

**Comment by touficzayed** [comment]
no ideas?

**Comment by touficzayed** [comment]
I've investigated the issue a little bit.

In the test repository I have a main frame that hold the AutoTabsRouter.

In the child of this AutoTabsRouter I have a AppFrame class that monitor the width of the app through MediaQuery.

Each time a breakpoint is passed (desktop->laptop->tablet->mobile) a new Scaffold is injected.

It seems that whenever a new Scaffold is rebuilt a new tabsRouter is recreated (I don't know why).

If I change the AppFrame to display a single giant Scaffold with NavigationRails or BottomNavigationBar the problem is mitigated. In the repository it is located in the "better" branch.

I can resize the app and I retain the same tabsRouter with all history stack when I scale from desktop to laptop to tablet, each displaying a different navigation rail.

But when I reach the mobile size, the navigation rail is not displayed and instead I display a bottom nav bar. Only in this case now the tabsRouter is recreated and navigation history is lost.

It's not perfect, I would like to retain the same tabsRouter in all cases but at least the experience is better.

Do you know why the tabsRouter is recreated?

Obviously the experience is better now, but it would be perfect if I could scale from mobile to desktop without losing my navigation history.

**Comment by moshOntong-IT** [comment]
If you want to make your app , better responsiveness, you can use this package [Responsive Framework](https://pub.dev/packages/responsive_framework). I tried to edit your sample repo

Fork Repo:
https://github.com/moshOntong-IT/autoroute_test/tree/testhttps://github.com/moshOntong-IT/autoroute_test/tree/test

In your main.dart

``` dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  var router = AppRouter();
  runApp(MaterialApp.router(
    builder: (context, child) => ResponsiveBreakpoints.builder(
      child: child!,
      breakpoints: [
        const Breakpoint(start: 0, end: 450, name: MOBILE),
        const Breakpoint(start: 451, end: 800, name: TABLET),
        const Breakpoint(start: 801, end: 1920, name: DESKTOP),
        const Breakpoint(start: 1921, end: double.infinity, name: '4K'),
      ],
    ),
    routerConfig: router.config(),
  ));
}

```

Then in app_frame.dart, you can see here that I used the Responsive Framework

``` dart
import 'package:auto_route/auto_route.dart';
import 'package:autoroute_test/frames/avatar_drawer.dart';
import 'package:flutter/material.dart';
import 'package:responsive_framework/responsive_breakpoints.dart';

class AppFrame extends StatelessWidget {
  final Widget child;
  final TabsRouter tabsRouter;
  const AppFrame({super.key, required this.child, required this.tabsRouter});

  @override
  Widget build(BuildContext context) {
    final breakpoints = ResponsiveBreakpoints.of(context);
    return Scaffold(
      // appBar: AppBar(title: Text(tabsRouter.current.title(context))),
      // endDrawer: const AvatarDrawer(),
      body: Row(
        children: [
          NavigationRail(
            extended: breakpoints.isDesktop,
            destinations: const [
              NavigationRailDestination(
                  icon: Icon(Icons.home), label: Text("A")),
              NavigationRailDestination(
                  label: Text("B"), icon: Icon(Icons.search)),
            ],
            selectedIndex: tabsRouter.activeIndex,
            onDestinationSelected: tabsRouter.setActiveIndex,
          ),
          Expanded(child: child),
          if (breakpoints.largerOrEqualTo(DESKTOP))
            const Row(
              children: [
                VerticalDivider(width: 1),
                SizedBox(
                  width: 250,
                  child: AvatarDrawer(),
                )
              ],
            )
        ],
      ),
    );
  }
}

```

> You can change the breakpoint in the main file

**Comment by touficzayed** [comment]
Wow great!

It even works with the bottom navigation bar, I don't lose my state. I can resize from mobile to desktop seamlessly.

Thank you very much for your help!

I close this issue.

**Comment by tomasweigenast** [comment]
> If you want to make your app , better responsiveness, you can use this package [Responsive Framework](https://pub.dev/packages/responsive_framework). I tried to edit your sample repo
> 
> Fork Repo: https://github.com/moshOntong-IT/autoroute_test/tree/testhttps://github.com/moshOntong-IT/autoroute_test/tree/test
> 
> In your main.dart
> 
> ```dart
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   var router = AppRouter();
>   runApp(MaterialApp.router(
>     builder: (context, child) => ResponsiveBreakpoints.builder(
>       child: child!,
>       breakpoints: [
>         const Breakpoint(start: 0, end: 450, name: MOBILE),
>         const Breakpoint(start: 451, end: 800, name: TABLET),
>         const Breakpoint(start: 801, end: 1920, name: DESKTOP),
>         const Breakpoint(start: 1921, end: double.infinity, name: '4K'),
>       ],
>     ),
>     routerConfig: router.config(),
>   ));
> }
> ```
> 
> Then in app_frame.dart, you can see here that I used the Responsive Framework
> 
> ```dart
> import 'package:auto_route/auto_route.dart';
> import 'package:autoroute_test/frames/avatar_drawer.dart';
> import 'package:flutter/material.dart';
> import 'package:responsive_framework/responsive_breakpoints.dart';
> 
> class AppFrame extends StatelessWidget {
>   final Widget child;
>   final TabsRouter tabsRouter;
>   const AppFrame({super.key, required this.child, required this.tabsRouter});
> 
>   @override
>   Widget build(BuildContext context) {
>     final breakpoints = ResponsiveBreakpoints.of(context);
>     return Scaffold(
>       // appBar: AppBar(title: Text(tabsRouter.current.title(context))),
>       // endDrawer: const AvatarDrawer(),
>       body: Row(
>         children: [
>           NavigationRail(
>             extended: breakpoints.isDesktop,
>             destinations: const [
>               NavigationRailDestination(
>                   icon: Icon(Icons.home), label: Text("A")),
>               NavigationRailDestination(
>                   label: Text("B"), icon: Icon(Icons.search)),
>             ],
>             selectedIndex: tabsRouter.activeIndex,
>             onDestinationSelected: tabsRouter.setActiveIndex,
>           ),
>           Expanded(child: child),
>           if (breakpoints.largerOrEqualTo(DESKTOP))
>             const Row(
>               children: [
>                 VerticalDivider(width: 1),
>                 SizedBox(
>                   width: 250,
>                   child: AvatarDrawer(),
>                 )
>               ],
>             )
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> > You can change the breakpoint in the main file

I'm sorry for writing here, but this solution only applies if you have a TabsRouter, what about if you have nested routers and want to modify the UI of only one route based on constraints? The state continues losing
