### ISSUE TITLE
How to Pass the BuildContext with Route Change?

### ISSUE THREAD

**Issue by kg551915** [Milad-Akarie/auto_route_library#179]
_I'm unsure if I am missing a conceptual understanding._

## Question: 
Why isn't the BuildContext being passed with the route change?

## Setup
I have a Bloc Provider at a top widget that then calls a child widget that builds the actual page. Then I have more widgets on-top of those that build the contents of the page. Then one item needs to open up a new page that still uses the same BlocProvider state. When I use `ExtendedNavigator.of(context).pushNamed(Routes)` the following error occurs:

```
flutter:         CubitProvider.of() called with a context that does not contain a Cubit of type
flutter:         BlocName.
flutter:         No ancestor could be found starting from the context that was passed to
flutter:         CubitProvider.of<BlocName>().
```

All files contain BlocBuilders.

### MAIN WIDGET:
```
return MultiBlocProvider(
      providers: [
        BlocProvider(
            create: (BuildContext context) => getIt<BlocName>()),
      ],
      child: WidgetOne(),
    );
```
### WIDGET ONE:
```
return BlocConsumer<BlocName, BlocNameState>(
        listener: (context, state) {}, 
        builder: (context, state) {
           return WidgetTwo();
```
### WIDGET TWO:
```
return BlocConsumer<BlocName, BlocNameState>(
        listener: (context, state) {}, 
        builder: (context, state) {
           return InkWell(
                    onTap: () {
                      ExtendedNavigator.of(context)
                          .pushNamed(Routes.WidgetThree);
                    },
```
### WIDGET THREE:
Returns the above error.
```
return BlocBuilder<BlocName, BlocNameState>(
```

**Comment by Milad-Akarie** [comment]
@kg551915 please refer to [this](https://github.com/Milad-Akarie/auto_route_library/issues/138#issuecomment-655914532)
