### ISSUE TITLE
[BUG] Dialog in AutoRoute by using CustomRoute is not working

### ISSUE THREAD

**Issue by moshOntong-IT** [Milad-Akarie/auto_route_library#1793]
This is how I utilize the `CustomRoute`

``` dart
 CustomRoute(
      page: OrganizationNewRoute.page,
      path: '/organization/new',
      customRouteBuilder: <OrganizationNewRoute>(BuildContext context,
          Widget child, AutoRoutePage<OrganizationNewRoute> page) {
        return PageRouteBuilder(
          fullscreenDialog: page.fullscreenDialog,
          settings: page,
          pageBuilder: (_, __, ___) {
            return SizedBox(height: 200, width: 200, child: child);
          },
        );
      },
    ),
```

I am trying here to make the screen as Dialog as you can in the code here:

``` dart
     pageBuilder: (_, __, ___) {
            return SizedBox(height: 200, width: 200, child: child);
          },
```
   
   But not working even if I set the fullScreenDialog as false, but this parameter is already set on false as default in the constructor.

**Comment by radomir9720** [comment]
Hi, @moshOntong-IT. If you're trying to make a dialog, why don't you use the `DialogRoute`? [Here is an example](https://github.com/Milad-Akarie/auto_route_library/issues/670#issuecomment-913435578).
