### ISSUE TITLE
Divide Navigation by modules (same project)

### ISSUE THREAD

**Issue by rubgithub** [Milad-Akarie/auto_route_library#180]
For example I have this folder hierarchy in my single project
-core
  -coreRouter
-auth
 -authRouter
-sales
  -salesRouter
....

And I want to each one has it own navigation control, is is possible? Or is there  a better way to organize it?

**Comment by Milad-Akarie** [comment]
To answer you question, it is possible to have as many navigators as you want, it's just another flutter widget. but things can get a little messy. 
If you're going for a nested approach auto_route will automatically generate separate routers for each parent route.

```dart
routes:[
MaterialRoute(path:'/': ,page: HomePage)
// a nested router called CorePageRouter will be generated
// for this route
MaterialRoute(path:'/core': ,page: CorePage,
    children: [
             // core related routes here
          ]
     )
]

```

**Comment by rubgithub** [comment]
Can I have a core control and `MaterialRoutes` for each module? For example:
```
routes:[
MyMaterialRouteHomePage(),
MyMaterialRouteCorePage()
]
```
If it possible, could you please give a short example?

**Comment by Milad-Akarie** [comment]
If I understood your requirement correctly, this this is what you need to do
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: HomeScreen, initial: true),
    coreRouteModule,
    MaterialRoute(path: '*', page: UnknownRouteScreen)
  ],
)
class $RootRouter {}
```

this can be in a separate file
```dart
const coreRouteModule = MaterialRoute<void>(
  path: '/core',
  page: CorePage,
  children: [
    MaterialRoute(path: '/core-first', page: CoreFirst),
    MaterialRoute(path: '/core-second', page: CoreSecond),
  ],
);

```

**Comment by rubgithub** [comment]
Exactly!
Thank you very much!
