### ISSUE TITLE
how to deeplink with lazy guard

### ISSUE THREAD

**Issue by kirya355** [Milad-Akarie/auto_route_library#1805]
Hello, I have 2 pages: 
1) WithGuardPage - can't open without login
2) WithoutGuardPage - can open without login

Can I deeplink to WithGuardPage->WithoutGuardPage, so that I see WithoutGuardPage(without login), and when pop, AuthGuard will work and I will see LoginPage?

Now when navigating 
```
[
WithGuardRoute(),
WithoutGuardRoute()
]
```
I see LoginPage, Although I don't need login to see WithoutGuardPage

I am attaching screenshots of an example.

![image](https://github.com/Milad-Akarie/auto_route_library/assets/41366638/4ab91ab4-55bd-443d-b4f4-2a0189de8ca5)
![image](https://github.com/Milad-Akarie/auto_route_library/assets/41366638/1d36b156-5d62-4bc4-840e-b897e61e9e83)

**Comment by Milad-Akarie** [comment]
Hey @kirya355 I'm afraid that's not possible because you need the first route to pass the guard to show the second guard, but what you can do is add some logic inside of your second route's pop invocation to redirect to the guarded route.
