### ISSUE TITLE
Support for GetX

### ISSUE THREAD

**Issue by Prn-Ice** [Milad-Akarie/auto_route_library#181]
[GetX](https://pub.dev/packages/get) is a package that is gaining a lot of popularity fast and it does simplify navigation.
I'm wondering if you would consider adding support for auto-generating get routes like you do with the basic flutter navigator.

**Comment by Milad-Akarie** [comment]
Hey @Prn-Ice  looks cool, but I honestly have no plans on doing that anytime soon.

**Comment by Prn-Ice** [comment]
No problem, my aim was to plant the seed XD.

**Comment by Milad-Akarie** [comment]
@Prn-Ice does it expose an onGenerateRouteMethod?

**Comment by Prn-Ice** [comment]
Yeah, it does.
The recommended approach however is 
```dart
void main() {
  runApp(
    GetMaterialApp(
      initialRoute: '/',
      getPages: [
        GetPage(name: '/', page: () => MyHomePage()),
        GetPage(name: '/second', page: () => Second()),
        GetPage(
          name: '/third',
          page: () => Third(),
          transition: Transition.zoom  
        ),
      ],
    )
  );
}
```
