### ISSUE TITLE
Redirect is not working in `AutoRouteGuard`

### ISSUE THREAD

**Issue by mattermoran** [Milad-Akarie/auto_route_library#1815]
I'm trying to add a global guard but something is off and I can't get it to work. 
Here's the example code:
```dart
@override
void onNavigation(NavigationResolver resolver, StackRouter router) {
  if (router.current.name == RedirectedRoute.name) {
    resolver.next();
  } else {
    print('Redirecting to ${RedirectedRoute.name}');
    resolver.redirect(RedirectedRoute());
  }
}
```

I get a blank screen and in the console I get a message printed 464 times. 
```bash
464 flutter: Redirecting to RedirectedRoute
```

My code is practically no different than the example provided in the readme so I don't think this is expected. 

<details>
<summary>Reproducible code</summary>

```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

part 'main.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen,Route')
class AppRouter extends _$AppRouter implements AutoRouteGuard {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: HomeRoute.page, initial: true),
        AutoRoute(page: RedirectedRoute.page),
      ];

@override
void onNavigation(NavigationResolver resolver, StackRouter router) {
  if (router.current.name == RedirectedRoute.name) {
    resolver.next();
  } else {
    print('Redirecting to ${RedirectedRoute.name}');
    resolver.redirect(RedirectedRoute());
  }
}
}

void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  MainApp({super.key});

  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _appRouter.config(),
    );
  }
}

@RoutePage()
class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blue[100],
      body: Center(
        child: Text('Home'),
      ),
    );
  }
}

@RoutePage()
class RedirectedScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red[100],
      body: Center(
        child: Text('Redirected'),
      ),
    );
  }
}

```
</details>

flutter version 3.16.3
auto_route version 7.3.2

**Comment by lcardosol** [comment]
Have you solved this? I got the same problem, for me it causes blank screen and an exception on the console, here is my issue #1818

**Comment by mattermoran** [comment]
nope. I had to add a guard on specific routes rather than global one

**Comment by lcardosol** [comment]
> nope. I had to add a guard on specific routes rather than global one

Would you mind sharing your temporary solution? I did try to assign them manually by separating the guard in its own class like tis:

```
class AuthGuard extends AutoRouteGuard {
  AuthGuard({
    required this.authState,
  }) : super();

  final AuthStateNotifer authState;

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final isLoginRoute = router.current.name == SignInRoute.name;
    final isSignUpRoute = router.current.name == SignUpRoute.name;
    final isAuthPage = isLoginRoute || isSignUpRoute;

    if (authState.isLogged && isAuthPage) {
      resolver.redirect(const HomeRoute());
    } else if (authState.isLogged && !isAuthPage) {
      resolver.next(true);
    } else if (!authState.isLogged && isAuthPage) {
      resolver.next(true);
    } else if (router.current.name == 'Root') {
      resolver.next(true);
    } else {
      resolver.redirect(const SignInRoute());
    }
  }
}
```

Like this it works, but it concerns me that I have to check on that specific route `Root` otherwise it causes the onNavigation to be triggered infinitly.

**Comment by mattermoran** [comment]
Oh as I was typing out my solution I realized the difference between my global guard that's not working and local. In my local one I'm using `router.replaceAll([RouteToShow()])` instead of `resolver.redirect(RouteToShow())`. 
Just tried to use `router.replaceAll` in my global and it seems to be working fine. 

The only issue is having to also check for root but honestly that's not a big deal.

**Comment by Milad-Akarie** [comment]
router.current is not the route being intercepted by guard, resolver.route is.

**Comment by mattermoran** [comment]
well it's official now, I can't read it seems

**Comment by Milad-Akarie** [comment]
Or maybe whoever wrote the docs made a mistake...

**Comment by mattermoran** [comment]
No the docs seems to be ok. Just tested with `resolver.route.name` and it works like charm. 
my bad :)

and thanks!
