### ISSUE TITLE
Setting initial route based on state

### ISSUE THREAD

**Issue by KieranLafferty** [Milad-Akarie/auto_route_library#182]
I'm trying to configure an initial route that changes based on the user's auth status provided via a Bloc state

```
  Widget _materialApp(String initialRoute) {
    return MaterialApp(
      builder: ExtendedNavigator.builder(
        router: _router,
        initialRoute: initialRoute,
        guards: [
          AuthGuard(
            authBloc: BlocProvider.of<AuthenticationBloc>(context),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AuthenticationBloc, AuthenticationState>(
      listener: (context, state) {
        if (state is AuthenticationStateAuthenticated) {
          _exNavigatorKey.currentState.push(Routes.inboxScreen);
        } else if (state is AuthenticationStateUnauthenticated) {
          _exNavigatorKey.currentState.popUntil((route) => route.isFirst);
        }
      },
      builder: (context, state) {
        final route = state is AuthenticationStateAuthenticated
            ? Routes.inboxScreen
            : Routes.onboardingScreen;
        return _materialApp(route);
      },
    );
  }
```

This was working in version `"0.6.0"` but stopped working after upgrading to `"0.6.6"`

Is there a recommended way to set the initial route from outside of the generated files? I'm aware that there's an `initial` property on the MaterialRoute and have configured it as follows: 

```
    MaterialRoute(
      page: OnboardingScreen,
      initial: true,
    ),
    MaterialRoute(
      page: InboxScreen,
      guards: [AuthGuard],
    ),
```
 
When I launch my app it always goes to `OnboardingScreen`. Thanks for any help you can provide!

**Comment by KieranLafferty** [comment]
It looks like this method is swapping out the initial route I provide with the base route 

<img width="378" alt="Screen Shot 2020-07-27 at 7 52 14 AM" src="https://user-images.githubusercontent.com/778142/88556714-2e052580-cfde-11ea-928d-e076fdde5194.png">

<img width="563" alt="Screen Shot 2020-07-27 at 7 52 21 AM" src="https://user-images.githubusercontent.com/778142/88556706-2c3b6200-cfde-11ea-877b-2fad9e1a6e3f.png">

**Comment by KieranLafferty** [comment]
Seems to be related to a race condition with the Guard that I have set up for the inbox screen. Removing the guard allowed it to set the initialRoute correctly

**Comment by Milad-Akarie** [comment]
@KieranLafferty How's your router setup?

**Comment by KieranLafferty** [comment]
The initial route that was failing to be set has a guard on it I just noticed that a PR that addresses this issue was fixed via #189  so I'll wait for a release that includes that :) 

As a short term fix I just removed the guard from the initial route and it works properly

**Comment by KieranLafferty** [comment]
The only difference between my set up and the one described in #189  is that my routes are defined as 

```
    MaterialRoute(
      page: OnboardingScreen,
      initial: true,
    ),
    MaterialRoute(
      page: InboxScreen,
      guards: [AuthGuard],
    ),
```

and my MaterialApp is set up as:

```
return MaterialApp(
      builder: ExtendedNavigator.builder(
        navigatorKey: _exNavigatorKey,
        router: _router,
        initialRoute: initialRoute,
        guards: [
          AuthGuard(
            authBloc: BlocProvider.of<AuthenticationBloc>(context),
          )
        ],
      ),
    );
```

Then based on whether the user is signed in or not at launch I set the `initialRoute` to be either `InboxScreen` (when signed in) or `OnboardingScreen` (when not signedin)

**Comment by Janaka-Steph** [comment]
Hello @KieranLafferty, did you solve it? 
I am also trying to set the initial route based on state. But I am confused, what AuthGuard is actually doing? Can you show what you put in there please? 

I would like to this but the guard function is running before the Unauthenticated state is emitted. 
(the Navigator that I receive as argument is not the one I want).
```
class AuthGuard extends RouteGuard {
  @override
  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName, Object arguments) async {
    if (getIt<AuthBloc>().state is Unauthenticated) {
      ExtendedNavigator.root.push(Routes.getStartedPage);
      return false;
    } else{
      return true;
    }
  }
}
``` 
@Milad-Akarie  
Thanks for any help

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
