### ISSUE TITLE
Route back to initial splash page every time I save.

### ISSUE THREAD

**Issue by BrillianceOsprey** [Milad-Akarie/auto_route_library#1829]
1. Here is my app_router.dart

@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SplashRoute.page, initial: true),
        AutoRoute(
          page: WrapperRoute.page,
          path: '/start',
          children: [
            AutoRoute(page: HomeRoute.page, path: 'home'),

            // Settings
            AutoRoute(page: SettingRoute.page, path: 'settings'),
            AutoRoute(page: PostRoute.page, path: 'post'),
          ],
        ),
        AutoRoute(page: SigninRoute.page, path: '/signin'),
        AutoRoute(page: SignupRoute.page, path: '/signup'),
        AutoRoute(page: OnBoardingRoute.page, path: '/onboarding'),
      ];
}

2. Here is my Material.router
    return MaterialApp.router(
      title: 'Libra',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.light,
      routerConfig: appRouter.config(),
    );

3. Here is my splash page
 import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

@RoutePage()
class SplashPage extends StatefulWidget {
  const SplashPage({super.key});

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {

 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: Text('Splash Page'),
      ),
    );
  }
}

**Comment by BrillianceOsprey** [comment]
I got it , I need to declare appRoute under build method of app widget page or material.router page

**Comment by Milad-Akarie** [comment]
@BrillianceOsprey avoid declaring it in any build method, you could declare it as a final field inside of your material App

**Comment by BrillianceOsprey** [comment]
> @BrillianceOsprey avoid declaring it in any build method, you could declare it as a final field inside of your material App

@Milad-Akarie Thank you.
