### ISSUE TITLE
Annotation for transition in CustomAutoRouter is ignored

### ISSUE THREAD

**Issue by igoriuz** [Milad-Akarie/auto_route_library#183]
Annotations for custom transitions are only working when the animation is defined for **CustomRoute** but not for **CustomAutoRouter**. Other fields, like durationInMilliseconds are also not passed.

My code:
```
@CustomAutoRouter(
    transitionsBuilder: TransitionsBuilders.fadeIn,
    durationInMilliseconds: 800,
    routesClassName: 'ContentRoutes',
    routes: [
      CustomRoute(page: GroupsScreen, initial: true),
      CustomRoute(page: GroupDetailsScreen),
    ])
class $ContentRouter {}
```

Generated code:
```
  ...
  final _pagesMap = <Type, AutoRouteFactory>{
    GroupsScreen: (data) {
      return PageRouteBuilder<dynamic>(
        pageBuilder: (context, animation, secondaryAnimation) => GroupsScreen(),
        settings: data,
      );
    },
...
```

But it works, if the transition is defined in the CustomRoute object
```
@CustomAutoRouter(
    transitionsBuilder: TransitionsBuilders.fadeIn,
    durationInMilliseconds: 800,
    routesClassName: 'ContentRoutes',
    routes: [
      CustomRoute(page: GroupsScreen, initial: true),
      CustomRoute(page: GroupDetailsScreen, 
                             transitionsBuilder: TransitionsBuilders.fadeIn,),
    ])
class $ContentRouter {}
```

```
  ...
  final _pagesMap = <Type, AutoRouteFactory>{
    GroupsScreen: (data) {
      return PageRouteBuilder<dynamic>(
        pageBuilder: (context, animation, secondaryAnimation) => GroupsScreen(),
        settings: data,
        transitionsBuilder: TransitionsBuilders.fadeIn,
      );
    },
...
```

**Comment by Milad-Akarie** [comment]
@igoriuz actually the logic here is a little weird, it made more sense when @CustomRoute annotation was used lol 
When you use MaterialRoute, CupertinoRoute or  CustomRoute in whatever AutoRouter it overrides the global configurations. so if you want your routes to adapt to always match the AutoRouter Config use `AutoRoute`

@CustomAutoRouter(
    transitionsBuilder: TransitionsBuilders.fadeIn,
    durationInMilliseconds: 800,
    routesClassName: 'ContentRoutes',
    routes: [
      CustomRoute(page: GroupsScreen, initial: true),
      CustomRoute(page: GroupDetailsScreen, 
                             transitionsBuilder: TransitionsBuilders.fadeIn,),
    ])
class $ContentRouter {}

**Comment by igoriuz** [comment]
Thanks for the fast reply! Yeah it's indeed a little bit confusing. I thought that by default the global configuration is used and can be overriden by the the (Cupertino/Material/Custom)Route. I will use AutoRoute from now on.

I have another short question, and i'm not completly sure if it's relevant bc i'm upgrading from 0.4.4 to the newest version.
For our tests we wrote a custom MockRouter and overriden onGenerateRoute to "fake" next screen interaction which we aren't interested in:
```
  @override
  Route<dynamic> onGenerateRoute(RouteSettings settings, [String basePath]) {
    if (settings.name == kInitialTestingRoute) {
      return MaterialPageRoute<dynamic>(
        builder: (_) => widget,
        settings: settings,
      );
    } else {
      return MaterialPageRoute<dynamic>(
        builder: (_) => Text("route:${settings.name}"),
        settings: settings,
      );
    }
  }
```

But with the newset version it fails due to:
```
The following _CastError was thrown building ExtendedNavigator<MockRouter>(state:
ExtendedNavigatorState<MockRouter>#25b73):
type 'RouteSettings' is not a subtype of type 'RouteData' in type cast
```

Have you maybe an idea why? If not, it's not urgent and this issue could be closed otherwise.

**Comment by Milad-Akarie** [comment]
I'm not sure. but RouteData is a sub class of RouteSettings. I'm not sure if you can mock it!

**Comment by igoriuz** [comment]
I've debugged it and the only difference is, that the real app receives RouteSettings with way more attributes than in my mocked app. Anyways, i will probably delay my upgrade to 0.6.6. Thank you for your help!
