### ISSUE TITLE
How to Directly jump to the page Using Dynamic Routing 

### ISSUE THREAD

**Issue by charmy1** [Milad-Akarie/auto_route_library#184]
In the example app ,cant navigate to PostDetails page  or PostHome Page

**Comment by Milad-Akarie** [comment]
are you using the root navigator?

**Comment by charmy1** [comment]
ExtendedNavigator.root.pushNamed("/users/1/posts/details");

**Comment by Milad-Akarie** [comment]
ya that should work, are you getting an error or something?

**Comment by charmy1** [comment]
no errors

**Comment by Milad-Akarie** [comment]
@charmy1 router setup please?

**Comment by charmy1** [comment]
i use the same setup as sample app https://github.com/Milad-Akarie/auto_route_library/tree/master/example

**Comment by Milad-Akarie** [comment]
@charmy1 can I see the generated file?

**Comment by charmy1** [comment]
https://github.com/charmy1/test_routes/blob/master/lib/router/profile_router.gr.dart
