### ISSUE TITLE
Nested navigation don't open new page, restart opened pages

### ISSUE THREAD

**Issue by RNOVOSELOV** [Milad-Akarie/auto_route_library#1843]
I have this router config 

`@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends _$AppRouter {
  @override
  RouteType get defaultRouteType => const RouteType.adaptive();

  @override
  List<AutoRoute> get routes => [
        AutoRoute(
          page: MainRoute.page,
          initial: true,
          path: '/main',
          children: [
            AutoRoute(page: HomeRoute.page, path: 'home', children: []),
            AutoRoute(page: CatalogRoute.page, path: 'catalog', children: [
              AutoRoute(path: 'subcategory', page: SubCatalogRoute.page),
            ]),
            AutoRoute(page: BagRoute.page, path: 'bag'),
            AutoRoute(page: FavoritesRoute.page, path: 'favorites'),
            AutoRoute(page: ProfileRoute.page, path: 'profile', children: []),
            AutoRoute(path: 'user', page: UserInfoRoute.page),
          ],
        ),
      ];
}`

and create Main page using AutoTabsScaffold
`  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    return AutoTabsScaffold(
      routes: const [
        HomeRoute(),
        CatalogRoute(),
        BagRoute(),
        FavoritesRoute(),
        ProfileRoute(),
      ],
      bottomNavigationBuilder: (context, tabsRouter) {
        return BottomNavigationBar(
          currentIndex: tabsRouter.activeIndex,
          onTap: (index) {
            if (!inProgress) tabsRouter.setActiveIndex(index);
          },
          items: <BottomNavigationBarItem>[
            _createBottomNavBarItem(BottomTab.home, 0, context),
            _createBottomNavBarItem(BottomTab.catalog, 0, context),
            _createBottomNavBarItem(BottomTab.bag, bagItemsCount, context),
            _createBottomNavBarItem(
                BottomTab.favorite, favoritesItemsCount, context),
            _createBottomNavBarItem(BottomTab.profile, 0, context),
          ],
        );
      },
    );
  }`
  
  How can I open UserInfoRoute inside of ProfileRoute? Should Itbe inside ProfileRoute description (in children) as SubCatalogRoute inside CatalogRoute?
  
  I try to use various methods but all opened page stack reboors and do nothing:
  
  context.pushRoute(const UserInfoRoute()), 
  context.pushRoute(const ProfileRoute(children: [UserInfoRoute()])),
  
Thks a lot in advance

**Comment by RNOVOSELOV** [comment]
![2024-01-23_00-24-14](https://github.com/Milad-Akarie/auto_route_library/assets/3972982/b033f189-b383-4344-93dd-88d536a993b2)
![2024-01-23_00-24-43](https://github.com/Milad-Akarie/auto_route_library/assets/3972982/18ff059c-631a-41c1-9417-7d7395b45358)

**Comment by ismailcaakir** [comment]
Can you explain how you solved the problem?
