### ISSUE TITLE
Override Android back button and iOS Swipe back gesture

### ISSUE THREAD

**Issue by fabienbranchel** [Milad-Akarie/auto_route_library#1845]
Is there any way to override Android back button and iOS Swipe back gesture ?

Searching in previous issues, I find this one pretty close : 
https://github.com/Milad-Akarie/auto_route_library/issues/976

You suggest to use `AutoRouteGuards` for conditional redirecting. 
I try it but I can't make it work. It's seems that `onNavigation` function of guard is only call when navigate, not when we use back button (which is the logical behavior in my opinion). 

Am I missing something ?

**Comment by gleberemeev** [comment]
You can use WillPopScope or PopScope to override these inputs

**Comment by samleecampspot** [comment]
I used `PopScope(canPop: false...)` to prevent back gestures.  

For some reason, my nested route in a tab needed to be refactored from an `AutoRoute` -> `MaterialRoute` on iOS because I was still able to navigate backwards w/ the gesture.  Android was fine with just the `PopScope.canPop == false`.
