### ISSUE TITLE
I have to manually import pages after the routes.gr.dart has been generated

### ISSUE THREAD

**Issue by ANTONINEUTRON** [Milad-Akarie/auto_route_library#1852]
After I am done with the set up of autoroute as specified in the documentation, the generated routes.gr.dart still has red lines with a message that the page has not been imported.
sample message `The name 'BooksPage' isn't a class.
Try correcting the name to match an existing class.`
In order to resolve this I will have to manually import the page.
A fix that'll ensure the generation process handles the import would be nice.

**Comment by Spariok** [comment]
I got the same error after setting up. I don't find how to fix it

**Comment by ANTONINEUTRON** [comment]
For now, you will just need to open the generated file and place your cursor on the highlighted line of code. This action will enable you to see an option in your IDE (such as VS Code or Android Studio) to import the reference.

**Comment by ImanGhasemiArani** [comment]
in this case, yes this is a bug. but you can ignore it by using `import` instead of `part`. like this:
...
~~part 'auto_route_config.gr.dart';~~
import 'auto_route_config.gr.dart';
...

**Comment by ANTONINEUTRON** [comment]
The solution mentioned above works
