### ISSUE TITLE
Generator fails with routes or guards in the same file

### ISSUE THREAD

**Issue by frank06** [Milad-Akarie/auto_route_library#186]
I used to place guards in `router.dart`

This no longer works because the generator is broken, including a:

```
import '.';
```

For classes in the same file, do not add any imports.

**Comment by Milad-Akarie** [comment]
@frank06 The fix will be included in the next build.

**Comment by Milad-Akarie** [comment]
@frank06 fixed in 
```yaml
auto_route: 0.6.7
auto_route_generator: 0.6.7
```
Thanks for reporting
