### ISSUE TITLE
Incorrect meta value returned when navigating with navigateNamed for Nested Routes

### ISSUE THREAD

**Issue by carlosfiori** [Milad-Akarie/auto_route_library#1882]
When navigating using `navigateNamed` for nested routes in AutoRoute, the `meta` value is being returned incorrectly. Instead of retrieving the `meta` value from the destination route, it is returning the `meta` value of the parent route.

### Use Case
We use information from the `meta` to decide whether or not to show the BottomNavigationBar depending on the screen, but due to the incorrect `meta` being provided, the BottomNavigationBar is being displayed erroneously.

### Reproduce
You can reproduce this issue by cloning this [repository](https://github.com/carlosfiori/auto_route_deep_link_problem). When clicking the "go to profile" button on the home page, it should navigate to the profile screen without displaying the BottomNavigationBar.

It has been noticed that by adding a delay of 100 milliseconds, the `meta` value is returned correctly:
```dart
Future.delayed(const Duration(milliseconds: 100)).then((value) {
    // Now the value is correct
    print(context.topRouteMatch.meta['showBottomNav']);
});
```

### Expected Behavior:
The returned `meta` value should correspond to the destination route, providing relevant information associated with that specific route.

### Current Behavior:
The returned `meta` value corresponds to the parent route when retrieved immediately after navigation, which is incorrect. However, introducing a 100-millisecond delay before retrieving the `meta` value results in the correct `meta` value being returned.

### Additional Information:
This issue affects the functionality of applications that rely on accurate `meta` information for nested routes. This can lead to incorrect rendering or behavior based on incorrect `meta` data.

**Comment by Milad-Akarie** [comment]
Hey @carlosfiori I just tried your example and everything seems to be working fine? 

https://github.com/Milad-Akarie/auto_route_library/assets/55059449/6cb1757d-b579-4d00-85ca-bcbff49dc7c6

note: I've removed the delayed code in the above example

**Comment by carlosfiori** [comment]
Hi @Milad-Akarie, thank you for your response.

The problem arises when navigating from the home page to the profile page for the first time.

I tested it in version 9.4 with Flutter 3.19.3, and the issue persists.


https://github.com/Milad-Akarie/auto_route_library/assets/20682772/f5a8a2d5-8233-4c19-9865-9708e0f0d232

**Comment by carlosfiori** [comment]
Hi @Milad-Akarie just test in 7.9.1 and work just great, thank you very much

**Comment by Milad-Akarie** [comment]
@carlosfiori 7.9.2 has a hot fix related to this issue

**Comment by carlosfiori** [comment]
Great, I tested it on 7.9.2 and everything still works, thanks
