### ISSUE TITLE
Issue in nested navigation back method

### ISSUE THREAD

**Issue by Shreemanarjun** [Milad-Akarie/auto_route_library#1883]
This one the code i am using that causing problem.

Defined routes like this
```dart
  CustomRoute(
        page: AddressBottomSheetRoute.page,
        path: '/addressBottomSheet',
        guards: [
          TokenGuard(userDbService: userDbService),
        ],
        customRouteBuilder:
            <T>(BuildContext context, Widget child, AutoRoutePage<T> page) {
          return ModalBottomSheetRoute(
            isScrollControlled: true,
            clipBehavior: Clip.none,
            // this is important
            settings: page,
            builder: (_) => child,
            isDismissible: true,
            enableDrag: true,
            useSafeArea: true,
            showDragHandle: true,
          );
        },
        children: [
          RedirectRoute(
            path: '*',
            redirectTo: 'selectAddress',
          ),
          AutoRoute(
              page: SelectAddressRoute.page,
              path: 'selectAddress',
              initial: true),
          AutoRoute(
            page: AddNewAddressRoute.page,
            path: 'addNew',
          ),
          AutoRoute(
            page: UpdateAddressRoute.page,
            path: 'updateAddress',
          ),
        ]),

```

```dart 
  final selectedAddressId = _formKey.currentState
          ?.fields[SelectAddressFormKeys.selectedAddress]?.value as String?;
      if (selectedAddressId != null) {
        final addressList = await ref.read(addressNotfierPod.future);
        widget.onSelectAddressData(addressList.data
            .where((element) => element.id == selectedAddressId)
            .first);
        ref.read(autorouterProvider).back();
      }


```

```dart


E/flutter ( 5946): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'NestedStackRouter' has no instance getter 'identifier'.
E/flutter ( 5946): Receiver: Instance of 'NestedStackRouter'
E/flutter ( 5946): Tried calling: identifier
E/flutter ( 5946): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter ( 5946): #1      RoutingController._removeTopRouterOf (package:auto_route/src/router/controller/routing_controller.dart:90:15)
E/flutter ( 5946): #2      StackRouter._popUntilOrPushAll (package:auto_route/src/router/controller/routing_controller.dart:1213:11)
E/flutter ( 5946): #3      StackRouter._navigateAll (package:auto_route/src/router/controller/routing_controller.dart:1633:9)
E/flutter ( 5946): #4      StackRouter.navigateAll (package:auto_route/src/router/controller/routing_controller.dart:1623:12)
E/flutter ( 5946): #5      NavigationHistoryImpl.back (package:auto_route/src/router/controller/navigation_history/native_navigation_history.dart:51:14)
E/flutter ( 5946): #6      RoutingController.back (package:auto_route/src/router/controller/routing_controller.dart:430:36)
E/flutter ( 5946): #7      _SelectAddressPageState.onSelectAddress (features/select_address/view/select_address_page.dart:47:38)
E/flutter ( 5946): <asynchronous suspension>



```

Flutter version:- 3.19.1
AutoRoute Version :- 7.8.5

**Comment by Yusuf007R** [comment]
I have the same problem, downgrading to 7.8.4 fixes the issue

**Comment by slgobinath** [comment]
Same problem here. Downgrading to 7.8.4 works. I compared the problematic source code between 7.8.4 and 7.8.5 the difference is `identifier` in the latest code.

routing_controller.dart v7.8.4:
```
void _removeTopRouterOf(Key? key) {
  for (final ctr in List.unmodifiable(_childControllers).reversed) {
    if (ctr.key == key) {
      _childControllers.remove(ctr);
      break;
    }
  }
}
```

routing_controller.dart v7.8.5:
```
void _removeTopRouterOf(Key? key) {
  for (final ctr in List.unmodifiable(_childControllers).reversed) {
    if (ctr.identifier == key) {
      _childControllers.remove(ctr);
      break;
    }
  }
}
```

The master branch is using `key` not sure from where the release got `identifier` https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/router/controller/routing_controller.dart#L91

**Comment by Yusuf007R** [comment]
I cannot even find the release v7.8.5 here in github this is strange

**Comment by hechengloong** [comment]
I have the same problem

**Comment by Shreemanarjun** [comment]
> I am getting similar error as well, but its happening on both `7.8.4` and `7.8.5`. I wonder if it was due to flutter version as well?
> 
> ```
> I/flutter ( 8943): ----------------FIREBASE CRASHLYTICS----------------
> I/flutter ( 8943): NoSuchMethodError: Class 'TabsRouter' has no instance getter 'identifier'.
> I/flutter ( 8943): Receiver: Instance of 'TabsRouter'
> I/flutter ( 8943): Tried calling: identifier
> I/flutter ( 8943): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
> I/flutter ( 8943): #1      RoutingController._removeTopRouterOf (package:auto_route/src/router/controller/routing_controller.dart:90:15)
> I/flutter ( 8943): #2      StackRouter._removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1152:5)
> I/flutter ( 8943): #3      StackRouter.removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1136:5)
> I/flutter ( 8943): #4      AutoRouteNavigatorState.build.<anonymous closure> (package:auto_route/src/router/widgets/auto_route_navigator.dart:103:31)
> I/flutter ( 8943): #5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284:28)
> I/flutter ( 8943): #6      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5243:9)
> I/flutter ( 8943): <asynchronous suspension>
> ```

Please use 7.8.4 for now.

**Comment by maxchu92** [comment]
> > I am getting similar error as well, but its happening on both `7.8.4` and `7.8.5`. I wonder if it was due to flutter version as well?
> > ```
> > I/flutter ( 8943): ----------------FIREBASE CRASHLYTICS----------------
> > I/flutter ( 8943): NoSuchMethodError: Class 'TabsRouter' has no instance getter 'identifier'.
> > I/flutter ( 8943): Receiver: Instance of 'TabsRouter'
> > I/flutter ( 8943): Tried calling: identifier
> > I/flutter ( 8943): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
> > I/flutter ( 8943): #1      RoutingController._removeTopRouterOf (package:auto_route/src/router/controller/routing_controller.dart:90:15)
> > I/flutter ( 8943): #2      StackRouter._removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1152:5)
> > I/flutter ( 8943): #3      StackRouter.removeRoute (package:auto_route/src/router/controller/routing_controller.dart:1136:5)
> > I/flutter ( 8943): #4      AutoRouteNavigatorState.build.<anonymous closure> (package:auto_route/src/router/widgets/auto_route_navigator.dart:103:31)
> > I/flutter ( 8943): #5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284:28)
> > I/flutter ( 8943): #6      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5243:9)
> > I/flutter ( 8943): <asynchronous suspension>
> > ```
> 
> Please use 7.8.4 for now.

I am getting this error on auto_route `7.8.4`, I'm guessing its caused by the recent update of Flutter `3.19.3`?

**Comment by dzsonni** [comment]
`7.8.4` works fine. Make sure you omit the `^` in your pubspec otherwise on ugprade it will resolve to `7.8.5`
`auto_route: 7.8.4`

**Comment by maxchu92** [comment]
> `7.8.4` works fine. Make sure you omit the `^` in your pubspec otherwise on ugprade it will resolve to `7.8.5` `auto_route: 7.8.4` You can check in pubspec.lock what the resolved version is.

Wow. This really solved my issue. I was not familiar with pubspec. Thank you.

**Comment by Jethro87** [comment]
This is fixed for me on the latest version (`7.9.0`). 🙏

**Comment by Shreemanarjun** [comment]
Fixed in 7.9.0

**Comment by Shreemanarjun** [comment]
popAndPush throws error in the latest version @Milad-Akarie

**Comment by uemirhanselim** [comment]
Why you don't fix this problem, I've been trying to find a solution since last week and right now in the github issues I found the solution. My whole week just trashed.

**Comment by Milad-Akarie** [comment]
@uemirhanselim this issue was fixed a week ago?

**Comment by oscarshaitan** [comment]
version 8.0.0 fix this for me
