### ISSUE TITLE
Error: Superclass has no getter named 'popDisposition' | The method 'PopScope' isn't defined for the class 'AutoRouteNavigatorState'

### ISSUE THREAD

**Issue by jaderdev** [Milad-Akarie/auto_route_library#1892]
Hello, I'm  getting this error suddenly and after trying and searching didn't found a solution.

../../.pub-cache/hosted/pub.dev/auto_route-7.8.5/lib/src/router/widgets/custom_cupertino_transitions_builder.dart:201:18: Error: Superclass has no getter named 'popDisposition'.
    return super.popDisposition;
                 ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/auto_route-7.8.5/lib/src/router/widgets/auto_route_navigator.dart:116:14: Error: The method 'PopScope' isn't defined for the class 'AutoRouteNavigatorState'.
 - 'AutoRouteNavigatorState' is from 'package:auto_route/src/router/widgets/auto_route_navigator.dart' ('../../.pub-cache/hosted/pub.dev/auto_route-7.8.5/lib/src/router/widgets/auto_route_navigator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PopScope'.
      return PopScope(
             ^^^^^^^^

I'm using 
  auto_route: ^7.8.1

and 
  auto_route_generator: ^7.3.1

My Flutter info.

Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (7 months ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

**Comment by thecarry98** [comment]
I dont know what the hell is going on, yesterday i would be too

**Comment by Milad-Akarie** [comment]
Foes this happen in the latest version?

**Comment by brandonguigo** [comment]
Hey!

I've gotten the same problem on 3.13.6.
Fixed it by updating to the latest stable version (3.16.0)

**Comment by MayroTejada** [comment]
> I've gotten the same problem on 3.13.6. Fixed it by updating to the latest stable version (3.16.0)

I upgrade to 3.16.0 but I keep facing the same problem. I use auto_route 7.8.5

**Comment by MayroTejada** [comment]
I fix it using auto_route: 7.8.4 instead ^7.8.5

**Comment by bensonarafat** [comment]
+1

**Comment by SamsonMokaya** [comment]
+1

**Comment by Lankesh007** [comment]
I Have solved this error modified the route cache page 
if you need any help from this to build IOS please contact me

**Comment by Shreenidhi-Technomers** [comment]
It is due to the versions of auto_route and auto_route_generator packages.
i tried     auto_route: ^7.8.4  and  auto_route_generator: ^7.3.2 It worked

**Comment by shri1211** [comment]
It is due to the versions of auto_route and auto_route_generator packages.
i tried auto_route: ^7.8.4 and auto_route_generator: ^7.3.2 It worked.

**Comment by Davut-Atajanov** [comment]
This issue still persists, auto_route ^8.0.0 is not working for me, I had to downgrade it, but they say that 8.0.0 is a big upgrade, I don't really want to miss out on them

**Comment by Milad-Akarie** [comment]
@Davut-Atajanov what flutter version are you on?

**Comment by Lankesh007** [comment]
stable, 3.19.6,

**Comment by Davut-Atajanov** [comment]
> @Davut-Atajanov what flutter version are you on?

I am currently in 3.19.4  
If I upgrade to 3.20.0, 3.22.3 or anything above linter library starts having problems ("intl" library)

**Comment by Milad-Akarie** [comment]
maybe it's better if you try to fix the linter error, you'll need to upgrade to the latest flutter version eventually

**Comment by jaderdev** [comment]
Thankyou everyone.

**Comment by RihabJdaida** [comment]
Hello everyone, I was using Flutter 3.0.13 and encountered a bug, but it has been fixed for me after upgrading to Flutter 3.0.19.
