### ISSUE TITLE
When I navigate back I get ERROR!

### ISSUE THREAD

**Issue by uemirhanselim** [Milad-Akarie/auto_route_library#1895]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'TabsRouter' has no instance getter 'identifier'.
E/flutter ( 5578): Receiver: Instance of 'TabsRouter'

**Comment by Milad-Akarie** [comment]
@uemirhanselim use the latest versions
