### ISSUE TITLE
PopScope and WillPopScope doesn't work in Flutter Web when I want to back by  browser's back button

### ISSUE THREAD

**Issue by pitcairn1987** [Milad-Akarie/auto_route_library#1898]
PopScope and WillPopScope doesn't work in Flutter Web when I want to back by  **browser's** back button.

**Comment by Milad-Akarie** [comment]
@pitcairn1987 PopScope does not support intercepting the browser's back button. Unfortunately, currently there's no direct way to achieve this using auto_route.
