### ISSUE TITLE
Custom callback(function) as parameter to the route failed to generate

### ISSUE THREAD

**Issue by rebaz94** [Milad-Akarie/auto_route_library#19]
Hi,
There is a problem when using callback to generated route. for example if we have a class like this
```dart
class MyPage extends StatelessWidget {
  const MyPage({
    Key key,
    @required this.id,
    @required this.name,
    @required this.callback,
  }) : super(key: key);

  final int id;
  final String name;
  final void Function(int id) callback;
}
```

the builder can not generate proper class for arguments, it failed immediately. and shows error
```dart
// Error: NoSuchMethodError: The getter 'source' was called on null.
//        Receiver: null
//        Tried calling: source
```

but using a typedef for the callback function fix the problem
```
typedef CustomCallback = void Function(int id);
```

**Comment by Milad-Akarie** [comment]
Hey @rebaz94, What happened is that it didn't see it as a Type..I will investigate this more. 
but as a preferable practice, you should use the navigator's returned value as your call back function

`final result = await Navigator.of(ctx).pushNamed('your_route_name');`
and from MyPage screen in your case
`Navigator.of(ctx).pop(id) // id will be stored in the returned result object`
you can even type the return result 
`final result = await Navigator.of(ctx).pushNamed<int>('your_route_name');
then
 Navigator.of(ctx).pop<int>(result)
`
read more about it here
https://flutter.dev/docs/cookbook/navigation/returning-data

**Comment by rebaz94** [comment]
@Milad-Akarie My use case is different I don't want to pop the screen, I have a nested navigator and a screen which I want to reuse it in different route so using a callback let me use proper route. here is an example
```dart
typedef OnCategorySelected = void Function(Category item);
class SelectCategoryScreen extends StatelessWidget {
  final OnCategorySelected onCategorySelected;
  const SelectCategoryScreen({Key key, this.onCategorySelected}) : super(key: key);
  
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        FlatButton(
          child: Text('Cate 1'),
          onPressed: () => onCategorySelected(item),
        ),
        FlatButton(
          child: Text('Cate 2'),
          onPressed: () => onCategorySelected(item),
        )
      ],
    );
  }
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SelectCategoryScreen(
      onCategorySelected: (Category item){
        MainRoute.of(context).pushNamed('/product', arguments: item);
      },
    );
  }
}

class AnotherScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SelectCategoryScreen(
      onCategorySelected: (Category item){
        MyOtherRoute.of(context).pushNamed('/other', arguments: item);
      },
    );
  }
}
```

**Comment by Milad-Akarie** [comment]
AutoRoute can handle dynamic params now in v0.3.0
