### ISSUE TITLE
Args are generated as var - Linter warning

### ISSUE THREAD

**Issue by Chojecki** [Milad-Akarie/auto_route_library#190]
Is it possible to generate args as `final` ?

Right now linter warnings: "Prefer final for variable declarations if they are not reassigned." at _pagesMap

For eg:

`MapSearcherPage: (data) {
      var args = data.getArgs<MapSearcherPageArguments>(nullOk: false); // <-- Here
      return MaterialPageRoute<dynamic>(
        builder: (context) => MapSearcherPage(
          key: args.key,
          keyWords: args.keyWords,
        ),
        settings: data,
      );
    },`

**Comment by Milad-Akarie** [comment]
you mean this 
` var args = data.getArgs<MapSearcherPageArguments>(nullOk: false)`
to this?
` final args = data.getArgs<MapSearcherPageArguments>(nullOk: false)`
if yes, it would be changed in the next build

**Comment by Milad-Akarie** [comment]
@Chojecki  done in
```yaml
auto_route: 0.6.7
auto_route_generator: 0.6.7
```
Thanks for reporting.
