### ISSUE TITLE
[Help] Setting default route parameters? Error: RouteArgs can not be null because the corresponding page has a required parameter 

### ISSUE THREAD

**Issue by JonasJW** [Milad-Akarie/auto_route_library#1900]
Thanks for this awesome package! I have a question that I couldn't find answers to and would appreciate getting some help on this.

I have a page that requires some parameters, something like this:

```
@RoutePage()
class ProfilePage extends StatelessWidget {
  final Function() loadData;

  const ProfilePage({
    Key? key,
    requried this.loadData
  }) : super(key: key);
}
```

It's not an initial route however, on web, when I reload this page it still gives me the error: `ProfileRouteArgs can not be null because the corresponding page has a required parameter`. I guess it's the same when I make it an initial route.

I have previously used GoRouter where in my route definitions I would create an Instance of the page and could just pass parameters. Is there some way I could achieve this with auto_route?

How do I deal with this? I found [this issue](https://github.com/Milad-Akarie/auto_route_library/issues/802) that suggests something like `delegate(initialRoutes: ...);` but I have no idea what that means and how to use this. I couldn't find any documentation on this.

**Comment by Milad-Akarie** [comment]
Hey @JonasJW have you tried using AutoRouteGuard?
