### ISSUE TITLE
How to scope a Same and Specific Bloc to some of the Routes using Auto Route?

### ISSUE THREAD

**Issue by cavin-7span** [Milad-Akarie/auto_route_library#1905]
I've been using `AutoRouteWrapper` for quite some time, but I needed the functionality to scope the same Bloc to 2 to 3 screens. I've tried Custom Route, but I'm not able to achieve the functionality.

**Comment by Milad-Akarie** [comment]
Hey @cavin-7span what you need is to wrap all those shared screens inside a sub router and provide your shared block above it.

**Comment by Cavin6080** [comment]
Thanks @Milad-Akarie for the help 😄 It is working as intended now with the tweaks you suggested.

**Comment by dwikyhardi** [comment]
hi @Milad-Akarie, can you paste the example?

**Comment by Milad-Akarie** [comment]
![image](https://github.com/user-attachments/assets/bc6adc8b-0cfd-44e9-8ac7-514739f400ee)
