### ISSUE TITLE
Bloc Provider Duplicating issue using Sub router

### ISSUE THREAD

**Issue by Cavin6080** [Milad-Akarie/auto_route_library#1906]
Scenario:

I've one Bottom Navigation Bar with 4 items in it. In the first 2 screens of the Bottom Navigation Bar, I want to share the same BLoC to it.

Here's my implementation for it:

```dart
...
AutoRoute(
        /// This is my bottom navbar route
          page: BottomNavigationBarRoute.page,
          children: [
            AutoRoute(
             /// This is my sub route that includes the Bloc Provider
              page: HomeCategoryProviderRoute.page,
              children: [
                /// These are my first 2 screen of the Bottom Navbar 
                AutoRoute(page: CategoriesRoute.page),
                AutoRoute(page: HomeRoute.page),
              ],
            ),
            AutoRoute(page: CartRoute.page),
            AutoRoute(page: AccountRoute.page),
          ],
        )
...
```

Here's the implementation of `HomeCategoryProviderRoute`:

```dart
@RoutePage()
class HomeCategoryProviderPage extends AutoRouter {
  HomeCategoryProviderPage({super.key})
      : super(
          builder: (context, child) {
            return BlocProvider(
              create: (context) => CategoriesCubit(
                categoriesRepository: const CategoriesRepository(),
              )..getCategoriesList(),
              child: child,
            );
          },
        );
}

```

But the problem I'm facing is that the `getCategoriesList()` function is getting called 2 times, which means for the 2 screens, a new BloC is created for both of them.

**Comment by cavin-7span** [comment]
I'm also getting another issue with this, whenever I use `context.pushRoute(const HomeRoute())` The `CategoriesCubit` calling `getCategoriesList()` function

**Comment by Milad-Akarie** [comment]
@cavin-7span First of all can you wrap AutoRouter inside of the widget instead of extending it? 

```dart
  @override
  Widget build(BuildContext context) {
    return BlockProvider(
      create: ...,
      child: AutoRouter(),
    );
  }
```

**Comment by cavin-7span** [comment]
I did the changes as you suggested:

```dart
@RoutePage()
class HomeCategoryProviderPage extends StatelessWidget {
  const HomeCategoryProviderPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => CategoriesCubit(
        categoriesRepository: const CategoriesRepository(),
      )..getCategoriesList(),
      child: const AutoRouter(),
    );
  }
```

But still the `getCategoriesList()` is calling 2 times. First when it loads the Home Screen, and the second time is when I click on second tab in the Bottom Navigation Bar

**Comment by Milad-Akarie** [comment]
@cavin-7span  not sure what the issue is, it looks like HomeCategoryProviderPage is losing state for some reason, could you create a simple repo that repreduces the issue?

**Comment by Cavin6080** [comment]
Sure

**Comment by Cavin6080** [comment]
Here's the link of the Repository with the reproducible code for the same: https://github.com/Cavin6080/auto-route-issue-with-global-bloc

**Comment by Cavin6080** [comment]
> @Milad-Akarie Here's the link of the Repository with the reproducible code for the same: https://github.com/Cavin6080/auto-route-issue-with-global-bloc

Hey @Milad-Akarie,
Is there any update on it?

**Comment by Milad-Akarie** [comment]
Hey @cavin-7span your setup loads two different stacks, it's normal your bloc gets initiated twice.
this is how your graph looks like 

```yaml
- BottomNavigationbarRoute
       - HomeCategoryProviderRoute / HomeRoute 
       - HomeCategoryProviderRoute / ProfileRoute
       - ExploreRoute
```
              
 as you can see `HomeCategoryProviderRoute` exists in two different locations in the graph, and it's being created in each location.
 
 the only valid setup for your use case is to have `BottomNavigationbarRoute` provide the bloc so it's accessed in all tabs and remove `HomeCategoryProviderRoute`

**Comment by Milad-Akarie** [comment]
first make `BottomNavigationBarScreen` stateFull,
create your block inside the BottomNavigationBarScreen.state normally like `myBlock = MyBlock()..runSomething();`
pass the instance you created to any route 
`HomeRoute(myBlock: myBlock);` 
 insdie `HomeScreen` you need to define a parameter that accepts `MyBlock` ofcourse.
lastly provide the bloc instance as a value inside HomeScreen 
`BlockProvider.value(value: myBlock, child: ....)`
