### ISSUE TITLE
[support] How to you pass arguments when not on web

### ISSUE THREAD

**Issue by long1eu** [Milad-Akarie/auto_route_library#1907]
I understand on web that you can specify this dynamic segments like this
```dart
AutoRoute(path: '/books/:id', page: BookDetailsPage),  
```

But on mobile `id`  will be parsed as `:id` and not sure how I can give it a value so it's consistent.

**Comment by Milad-Akarie** [comment]
@long1eu if you're not navigating by path then inside BookDetailsPage have a constructor param named id and annotate it with @PathParam() so it's automatically parsed for you

**Comment by long1eu** [comment]
Indeed I have something like this:
```dart
  const BookDetailsPage({@PathParam('id') required this.bookId, super.key});

  final String bookId;
```

my issue here is that the parsing result in this case is `:id`.

**Comment by Milad-Akarie** [comment]
@long1eu how do you navigate to this page?

**Comment by long1eu** [comment]
It's the initial page.

**Comment by Milad-Akarie** [comment]
where are you supposed to get value of 'id' from? deeplink?

**Comment by Milad-Akarie** [comment]
can you share the code inside AutoRouteGuard?

**Comment by long1eu** [comment]
```dart
class BookSelectedGuard implements AutoRouteGuard {
  BookSelectedGuard(this.store);

  final Store<AppState> store;

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final String? bookId = store.state.bookId;
    if (bookId != null) {
      resolver.redirect(BookDetailsPage(bookId: bookId));
    } else {
      resolver.redirect(SelectProjectRoute(onResult: resolver.next));
    }
  }
}

```

**Comment by Milad-Akarie** [comment]
this `BookDetailsPage` should be `BookDetailsRoute` right? 
in the below line you are resuming the initial destination with id=null when calling resolver.next;
`  resolver.redirect(SelectBookRoute(onResult: resolver.next));`
you need to always abort with resolver.next(false); inside on result obtain the book id then re-push BookDetailsRoute with the it

**Comment by long1eu** [comment]
Something like this?
```dart
class BookSelectedGuard implements AutoRouteGuard {
  BookSelectedGuard(this.store);

  final Store<AppState> store;

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final String? bookId = store.state.books.selectedBookId;
    if (bookId != null) {
      resolver.redirect(BookDetailsRoute(bookId: bookId));
    } else {
      resolver.redirect(
        SelectBookRoute(
          onResult: (String? bookId) {
            resolver.next(false);
            if (bookId != null) {
              resolver.redirect(BookDetailsRoute(bookId: bookId));
            }
          },
        ),
      );
    }
  }
}

```

**Comment by Milad-Akarie** [comment]
@long1eu yes, fyi resolver. redirect is meant to be used for temp-redirects, I think it's better if you use router.push or router.replace instead, also you should always call resolver.next, in your case it should always be called with resolver.next(false)

**Comment by long1eu** [comment]
I've send you an email at info@vertex.ly

**Comment by Milad-Akarie** [comment]
@long1eu resend on milad.akarie@gmail.com please
