### ISSUE TITLE
Allow empty paths without making them initial?

### ISSUE THREAD

**Issue by JonasJW** [Milad-Akarie/auto_route_library#1915]
Take this route as an example

    AutoRoute(
      path: "/",
      page: TabbarAutoRoute.page,
      children: [
        AutoRoute(
          path: 'home',
          page: HomeRoute.page,
          initial: true,
        ),
        AutoRoute(
          path: '',
          page: ContentRoute.page,
          initial: false,
          children: [
            AutoRoute(
              path: 'routines',
              page: RoutineListRoute.page,
              initial: false,
            ),
            AutoRoute(
              path: "programs",
              page: ProgramListRoute.page,
              initial: false,
            ),
          ],
        ),

      ],
    ),

The `ContentRoute` has an `AutoTabsRouter` that renders the routes `RoutineListRoute` and `ProgramListRoute`.

I would like to set the path of `ContentRoute` to empty, so the paths `/routines` and `/programs` lead to the related tabs. However, I want to have the `HomeRoute` as the initial route.

It seems, leaving a path empty means it's automatically the initial route, even when having other routes marked as initial.

I would like that the path `/` leads to `HomeRoute` but it always leads to `RoutineListRoute`. Only `/routines` should lead to `RoutineListRoute`, not `/`.

**Comment by JonasJW** [comment]
Maybe this is a better example:

    AutoRoute(
      path: "/login", 
      page: LoginRoute.page,
      initial: user == null, // Initial if user is not logged in
    ),
    AutoRoute(
      path: "/",
      page: TabbarAutoRoute.page,
      initial: user != null, // Initial if user is logged in
      children: [
        AutoRoute(
          path: 'home',
          page: HomeRoute.page,
          initial: AuthState().currentUid != null,
        ),
        AutoRoute(
          path: 'profile',
          page: ProfileRoute.page,
        ),
      ],
    ),

Due to the fact that the `TabbarAutoRoute` has an empty route, it is always initial. Even though the `LoginRoute` should be initialed if no user is logged in. I think this is a common use case, of course it would be solvable by giving TabbarAutoRoute a not empty path but then the paths for `HomeRoute` and `ProfileRoute` have a prefix, which I would like to avoid.

**Comment by JonasJW** [comment]
@Milad-Akarie sorry for tagging you but I really was wondering if there is a solution to this so the empty path is not automatically the initial path?

**Comment by Milad-Akarie** [comment]
Hey @JonasJW I just wanted to take a look at the possibilities before I reply, they way RouteMatcher works this might need some work, it's not a bug it's just meant to work this way, so changing the implementation might take some work, besides, it might introduce breaking changes. 

from your usecase above I think what you need is active redirection based on user  status, if that's the case what you need is to use `AutoRouteGuard`, you can implement and pass your guards to `AutoRoute(guards:...)` or use the shorthand AutoRute.guarded if you don't intent to have multiple guards.

```dart
AutoRoute.guarded(
      page: HomeRoute.page,
      path: '/home',
      initial: true,
      onNavigation: (resolver,_){
         if(user != null){
           resolver.next();
         }else{
           resolver.redirect(LoginRoute(noResult: resolver.next));
         }
       },
)
```
