### ISSUE TITLE
Missing Back Button after refresh on web

### ISSUE THREAD

**Issue by JonasJW** [Milad-Akarie/auto_route_library#1916]
Example routes:

    AutoRoute(
      path: "/home",
      page: HomeRoute.page,
      initial: true,
      children: [
        AutoRoute(
          path: "child",
          page: ChildRoute.page,
        ),
      ]
    )

Example pages:

    @RoutePage()
    class HomePage extends StatelessWidget {
      const HomePage({Key? key}) : super(key: key);

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('Test Page'),
          ),
          body: Column(
            children: [
              FilledButton(
                onPressed: () {
                  AutoRouter.of(context).push(ChildRoute());
                },
                child: Text("Go"),
              ),
            ],
          ),
        );
      }
    }

    @RoutePage()
    class ChildPage extends StatelessWidget {
    const ChildPage({ Key? key }) : super(key: key);

      @override
      Widget build(BuildContext context){
        return Scaffold(
          appBar: AppBar(
            title: const Text('Child Page'),
          ),
          body: Column(
            children: [
              Text("Child Page")
            ],
          ),
        );
      }
    }

When opening the app at path `home/child`, the page does not have a back button. I would expect AutoRoute to understand that it's a child route of `/home` and show a back button.

**Comment by Milad-Akarie** [comment]
@JonasJW where do you expect/home/child to pop to?

**Comment by JonasJW** [comment]
@Milad-Akarie I would expect it to pop to `/home` as the ChildRoute is a child of the HomeRoute. This is how GoRouter handles it and routers of other frameworks.

Btw, I very much appreciate your work! AutoRoute is a great package and I would really like to use it in my app, I just have a few minor issues like this one but overall it's already much easier to use as GoRouter.

**Comment by Milad-Akarie** [comment]
@JonasJW does HomeRoute has an AutoRouter widget inside of it? your setup doesn't make sense

**Comment by Milad-Akarie** [comment]
You need an AutoRouter widget to render child routes

**Comment by JonasJW** [comment]
@Milad-Akarie Thanks for clarifying, I must have miss understood this.

However, the issue still persists. I don't want to use nested routers by having an `AutoRouter` on my HomePage. I want to use the same route for the ChildRoute and HomeRoute.

Am I correct that the routes should then look like this:

    AutoRoute(
      path: "/home",
      page: HomeRoute.page,
      initial: true,
    ),
    AutoRoute(
      path: "/home/child",
      page: ChildRoute.page,
      initial: false,
    ),

If I do this and open the app at `/home/child/` the app starts at the HomePage. I would expect it to show the ChildPage and include a back button that pops to `/home`, i.e. the HomePage.

**Comment by Milad-Akarie** [comment]
@JonasJW with the current setup you only have to set includePrefixMatches to true inside router.config()

**Comment by JonasJW** [comment]
@Milad-Akarie that's perfect! Thank you very much!

Just letting you know, in the docs it says "This of course requires includePrefixMatches to be true in the root config (default is true)", while the default value is actually `!kIsWeb`.

**Comment by Milad-Akarie** [comment]
Ya must've forgotten to change that
