### ISSUE TITLE
"only "package" and "asset" schemes supported" Error

### ISSUE THREAD

**Issue by Tejasvp25** [Milad-Akarie/auto_route_library#192]
[INFO] Generating build script...
[INFO] Generating build script completed, took 450ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 105ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.0s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 17ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 90ms

[SEVERE] auto_route_generator:autoRouteGenerator on test/widget_test.dart (cached):

Unsupported operation: Cannot resolve file:///E:/Misc_Stuff/Android-Apps/torrentsearch/lib/core/pages/splash_screen.dart; only "package" and "asset" schemes supported
package:build                                                                                 new AssetId.resolve
package:build_resolvers/src/build_asset_uri_resolver.dart 173:29                              _parseDirectives.<fn>
dart:collection                                                                               new HashSet.of
package:build_resolvers/src/build_asset_uri_resolver.dart 166:13                              _parseDirectives
package:build_resolvers/src/build_asset_uri_resolver.dart 84:44                               BuildAssetUriResolver.performResolve.<fn>
package:build_resolvers/src/build_asset_uri_resolver.dart                                     BuildAssetUriResolver.performResolve.<fn>
package:graphs/src/crawl_async.dart 64:31                                                     _CrawlAsync._crawlFrom
package:graphs/src/crawl_async.dart 81:12                                                     _CrawlAsync._visit
dart:async                                                                                    Future.wait
package:graphs/src/crawl_async.dart 69:18                                                     _CrawlAsync._crawlFrom
package:graphs/src/crawl_async.dart 81:12                                                     _CrawlAsync._visit
dart:async                                                                                    Future.wait
package:graphs/src/crawl_async.dart 53:20                                                     _CrawlAsync.run
package:graphs/src/crawl_async.dart 34:54                                                     crawlAsync
package:build_resolvers/src/build_asset_uri_resolver.dart 57:32                               BuildAssetUriResolver.performResolve
package:build_resolvers/src/resolver.dart 234:24                                              AnalyzerResolvers.get
package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart 19:58  PerformanceTrackingResolvers.get.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15                        _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart 19:16  PerformanceTrackingResolvers.get
package:build                                                                                 BuildStepImpl.resolver
package:source_gen/src/builder.dart 68:32                                                     _Builder.build
package:build                                                                                 runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19                                 _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15                        _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23                                 _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                                        _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                                         NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22                                 _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                                 Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17                                 _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38                                 _SingleBuild._runBuilder.<fn>
dart:async                                                                                    Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36                                 _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20                                 _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                                        _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 184:15                        _NoOpBuildPerformanceTracker.trackBuildPhase
package:build_runner_core/src/generate/build_impl.dart 316:47                                 _SingleBuild._runPhases.<fn>
package:timing/src/timing.dart 222:44                                                         NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 310:32                                 _SingleBuild._runPhases
package:build_runner_core/src/logging/logging.dart 25:30                                      logTimedAsync
package:build_runner_core/src/generate/build_impl.dart 267:26                                 _SingleBuild._safeBuild.<fn>
dart:async                                                                                    runZoned
package:build_runner_core/src/generate/build_impl.dart 262:5                                  _SingleBuild._safeBuild
package:build_runner_core/src/generate/build_impl.dart 209:24                                 _SingleBuild.run
package:build_runner_core/src/generate/build_impl.dart 94:56                                  BuildImpl.run
package:build_runner_core/src/generate/build_runner.dart 25:14                                BuildRunner.run
package:build_runner                                                                          BuildCommand.run
package:args/command_runner.dart 197:27                                                       CommandRunner.runCommand
package:args/command_runner.dart 112:25                                                       CommandRunner.run.<fn>
dart:async                                                                                    new Future.sync
package:args/command_runner.dart 112:14                                                       CommandRunner.run
package:build_runner                                                                          run
.dart_tool\build\entrypoint\build.dart 22:22                                                  main

[SEVERE] auto_route_generator:autoRouteGenerator on lib/core/pages/settings.dart (cached):

Unsupported operation: Cannot resolve file:///E:/Misc_Stuff/Android-Apps/torrentsearch/lib/core/pages/splash_screen.dart; only "package" and "asset" schemes supported
package:build                                                     new AssetId.resolve
package:build_resolvers/src/build_asset_uri_resolver.dart 173:29  _parseDirectives.<fn>
dart:collection                                                   new HashSet.of
package:build_resolvers/src/build_asset_uri_resolver.dart 166:13  _parseDirectives
package:build_resolvers/src/build_asset_uri_resolver.dart 84:44   BuildAssetUriResolver.performResolve.<fn>
package:build_resolvers/src/build_asset_uri_resolver.dart         BuildAssetUriResolver.performResolve.<fn>
package:graphs/src/crawl_async.dart 64:31                         _CrawlAsync._crawlFrom
package:graphs/src/crawl_async.dart 81:12                         _CrawlAsync._visit
dart:async                                                        Future.wait
package:graphs/src/crawl_async.dart 69:18                         _CrawlAsync._crawlFrom

[SEVERE] auto_route_generator:autoRouteGenerator on lib/core/routes/routes.dart (cached):

Unsupported operation: Cannot resolve file:///E:/Misc_Stuff/Android-Apps/torrentsearch/lib/core/pages/splash_screen.dart; only "package" and "asset" schemes supported
package:build                                                     new AssetId.resolve
package:build_resolvers/src/build_asset_uri_resolver.dart 173:29  _parseDirectives.<fn>
dart:collection                                                   new HashSet.of
package:build_resolvers/src/build_asset_uri_resolver.dart 166:13  _parseDirectives
package:build_resolvers/src/build_asset_uri_resolver.dart 84:44   BuildAssetUriResolver.performResolve.<fn>
package:build_resolvers/src/build_asset_uri_resolver.dart         BuildAssetUriResolver.performResolve.<fn>
package:graphs/src/crawl_async.dart 64:31                         _CrawlAsync._crawlFrom
package:graphs/src/crawl_async.dart 81:12                         _CrawlAsync._visit
dart:async                                                        Future.wait
package:graphs/src/crawl_async.dart 69:18                         _CrawlAsync._crawlFrom

[SEVERE] auto_route_generator:autoRouteGenerator on lib/main.dart (cached):

NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (AssetId) => bool)
dart:core                                                                                     Object.noSuchMethod
package:build_resolvers/src/build_asset_uri_resolver.dart 93:40                               BuildAssetUriResolver.performResolve.<fn>
package:graphs/src/crawl_async.dart 68:27                                                     _CrawlAsync._crawlFrom
package:graphs/src/crawl_async.dart 81:12                                                     _CrawlAsync._visit
dart:async                                                                                    Future.wait
package:graphs/src/crawl_async.dart 53:20                                                     _CrawlAsync.run
package:graphs/src/crawl_async.dart 34:54                                                     crawlAsync
package:build_resolvers/src/build_asset_uri_resolver.dart 57:32                               BuildAssetUriResolver.performResolve
package:build_resolvers/src/resolver.dart 234:24                                              AnalyzerResolvers.get
package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart 19:58  PerformanceTrackingResolvers.get.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15                        _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart 19:16  PerformanceTrackingResolvers.get
package:build                                                                                 BuildStepImpl.resolver
package:source_gen/src/builder.dart 68:32                                                     _Builder.build
package:build                                                                                 runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19                                 _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15                        _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23                                 _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                                        _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                                         NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22                                 _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                                 Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17                                 _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38                                 _SingleBuild._runBuilder.<fn>
dart:async                                                                                    Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36                                 _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20                                 _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                                                    _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                                        _SingleBuild._matchingPrimaryInputs

[SEVERE] Build:
Failed after 212ms
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:338:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#11     _rootRun (dart:async/zone.dart:1184:13)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by Tejasvp25** [comment]
`import 'package:auto_route/auto_route.dart';
import 'package:auto_route/auto_route_annotations.dart';
import 'package:torrentsearch/core/pages/about.dart';
import 'package:torrentsearch/core/pages/settings.dart';
import 'package:torrentsearch/core/pages/splash_screen.dart';
import 'package:torrentsearch/core/pages/terms_and_conditions.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/all_recents.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/favourite.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/home.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/recent_info.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/search_history.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/torrent_result.dart';

@MaterialAutoRouter(
  routes: <AutoRoute>[
    // initial route is named "/"
    CustomRoute(
      page: SplashScreen,
      initial: true,
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute<Home>(
      page: Home,
      path: "/home",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: TorrentResult,
      path: "/result",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: RecentInfo,
      path: "/recent",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: Settings,
      path: "/settings",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: AllRecents,
      path: "/allrecent",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: Favourite,
      path: "/favourite",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: SearchHistory,
      path: "/history",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: TermsandConditions,
      path: "/tac",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
    CustomRoute(
      page: About,
      path: "/about",
      transitionsBuilder: TransitionsBuilders.fadeIn,
      durationInMilliseconds: 500,
    ),
  ],
)
class $Router {}
`

**Comment by Milad-Akarie** [comment]
@Tejasvp25  This showed after the new update? 
could you set preferRelativeImports to false and see if you still get the error? 

btw you can use a global CustomAutoRouter with plain AutoRoutes instead of passing your custom settings to each route. 
```dart
@CustomAutoRouter(
preferRelativeImports: false,
transitionsBuilder: TransitionsBuilders.fadeIn,
durationInMilliseconds: 500,
routes: [
AutoRoute(page: SplashScreen, initial: true),
AutoRoute(page: Settings),
AutoRoute(page: ...),
...)
```

**Comment by Tejasvp25** [comment]
yes , this issue showed after new update.
I've set preferRelativeImports to false still the issue persists

`import 'package:auto_route/auto_route.dart';
import 'package:auto_route/auto_route_annotations.dart';
import 'package:torrentsearch/core/pages/about.dart';
import 'package:torrentsearch/core/pages/settings.dart';
import 'package:torrentsearch/core/pages/splash_screen.dart';
import 'package:torrentsearch/core/pages/terms_and_conditions.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/all_recents.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/favourite.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/home.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/recent_info.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/search_history.dart';
import 'package:torrentsearch/features/torrent/presentation/pages/torrent_result.dart';

@CustomAutoRouter(
  preferRelativeImports: false,
  transitionsBuilder: TransitionsBuilders.fadeIn,
  durationInMilliseconds: 500,
  routes: <AutoRoute>[
    // initial route is named "/"
    AutoRoute<SplashScreen>(
      page: SplashScreen,
      initial: true,
    ),
    AutoRoute<Home>(
      page: Home,
      path: "/home",
    ),
    AutoRoute(
      page: TorrentResult,
      path: "/result",
    ),
    AutoRoute(
      page: RecentInfo,
      path: "/recent",
    ),
    AutoRoute(
      page: Settings,
      path: "/settings",
    ),
    AutoRoute(
      page: AllRecents,
      path: "/allrecent",
    ),
    AutoRoute(
      page: Favourite,
      path: "/favourite",
    ),
    AutoRoute(
      page: SearchHistory,
      path: "/history",
    ),
    AutoRoute(
      page: TermsandConditions,
      path: "/tac",
    ),
    AutoRoute(
      page: About,
      path: "/about",
    ),
  ],
)
class $Router {}

`

**Comment by Mallikarjun7657** [comment]
@Tejasvp25 I have also faced same issue while working with auto_route package, Just go to the import statements of the error file in your case (file:///E:/Misc_Stuff/Android-Apps/torrentsearch/lib/core/pages/splash_screen.dart; ) go to the splash screen and remove the import statement with "file:///E:/Misc_Stuff/Android-Apps/torrentsearch/lib/core/pages/splash_screen.dart;"  and then replace the proper import statement which contains package in import statement (ex: import 'package:your_app_name:splash_screen') then your generator will run successfully.
