### ISSUE TITLE
A nested navigator is not able to obtain its router on its own.

### ISSUE THREAD

**Issue by Braj65** [Milad-Akarie/auto_route_library#193]
I am trying to use the 'nested navigator' 0.6.0 example. But it is giving me a runtime error.
I have a home page containing a bottomnavbar. It shows the landing page(which has nested navigators)
Router class nested config section-
MaterialRoute<void>(
    path: '/landing',
    page: LandingPage,
    children: <AutoRoute>[
      MaterialRoute<void>(path: '/', page: FirstLandingPage),
      MaterialRoute<void>(path: '/jam', page: SecondNested),
    ],
  ),
The landing page has following body-
class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Jam')),
      body: ExtendedNavigator(
        initialRoute: LandingPageRoutes.firstLandingPage,
      ),
    );
  }
}
I tried with only 'ExtendedNavigator()' as well. I am getting following error- 
'package:auto_route/src/extended_navigator.dart': Failed assertion: line 248 pos 12: 'router !=
I/flutter ( 8369): null': is not true.
I/flutter ( 8369): 
I/flutter ( 8369): The relevant error-causing widget was:
I/flutter ( 8369):   ExtendedNavigator<RouterBase>
I/flutter ( 8369):   file:///C:/........................../lib/home_nested.dart:12:13

**Comment by edmbn** [comment]
@Braj65 Did you solved this? I'm facing the same problem. Thanks!
