### ISSUE TITLE
Question: Access BuildContext from within AutoRouteGuard

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/auto_route_library#1933]
Is it technically possible to change AutoRouteGuard and give it access to the `BuildContext` above the route being guarded?

So something like this is possible:

```dart
void onNavigation(BuildContext context, NavigationResolver resolver, StackRouter router) {
  final data = context.read<SomeBloc>().data
 
  // allow navigation depending on state
}
```

**Comment by Milad-Akarie** [comment]
@jtdLab  you can access context using   `router.navigatorKey.currentContext?`, but understand that this context is above the whole navigator

**Comment by jtdLab** [comment]
This returns  only `null`s
