### ISSUE TITLE
@MaterialAutoRouter doesnt have named  parameter 'routes' for v0.6.7

### ISSUE THREAD

**Issue by vinoopks** [Milad-Akarie/auto_route_library#194]
auto_route v0.6.7 doesn't seem to have routes List as  a named parameter inside MaterialAutoRouter class.
`class MaterialAutoRouter extends AutoRouter {
  const MaterialAutoRouter(
      {bool generateNavigationHelperExtension,
      bool generateArgsHolderForSingleParameterRoutes,
      String routesClassName,
      String routePrefix})
      : super._(
            generateNavigationHelperExtension,
            generateArgsHolderForSingleParameterRoutes,
            routesClassName,
            routePrefix);
}`

Could you please check and fix this?

**Comment by zhllm** [comment]
You can use ^0.6.0 to get latest version,and it's work.
