### ISSUE TITLE
Deeplink getting called multiple times

### ISSUE THREAD

**Issue by devmuaz** [Milad-Akarie/auto_route_library#1946]
Hello,

I've recently integrated the `deeplink` feature into my app, but then I found out that the link that's being pressed is calling the specific page to be shown multiple times, so when I press the link the first time it will show the page correctly, but when pressing the link again it will show the page twice, and it keeps going with how many times I press the link.

This happens on both `Android` and `iOS` platforms

here's my router config:
```dart
routerConfig: appRouter.config(
  deepLinkBuilder: (deepLink) {
    logD('App', 'deepLink', deepLink.path);
    if (deepLink.path.startsWith('/business')) return deepLink;
    return DeepLink.defaultPath;
  },
  rebuildStackOnDeepLink: true,
),
```

here's my router:
```dart
@AutoRouterConfig(
  replaceInRouteName: 'View,Route',
)
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SplashRoute.page, path: '/business/:id', initial: true),
        AutoRoute(page: BusinessRoute.page),
        AutoRoute(page: MainRoute.page),
      ];
}

final appRouter = AppRouter();
```
`Note`: The `SplashRoute` is getting the `id` correctly each time, and this `id` is being passed to the `BusinessRoute` programmatically using `appRouter.push` method, and this `BusinessRoute` is the one that's being called multiple times.

Am I doing something wrong? Any solution?

**Comment by devmuaz** [comment]
The issue has been resolved, it turned out that there's a property that keeps the history alive (called `keepHistory`, and this defaults to `true`), and disabling it solves the whole thing!

here's the updated `AppRouter` class:
```dart
@AutoRouterConfig(
  replaceInRouteName: 'View,Route',
)
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SplashRoute.page, path: '/business/:id', initial: true),
        AutoRoute(page: BusinessRoute.page, keepHistory: false),
        AutoRoute(page: MainRoute.page),
      ];
}

final appRouter = AppRouter();
```

@Milad-Akarie It would be beneficial if this is documented in the README.md file 🔥

Thanks!

**Comment by Milad-Akarie** [comment]
@devmuaz hold on, what page are trying to deep-link to? the SplashRoute? is there a mistake here?

**Comment by devmuaz** [comment]
@Milad-Akarie Trying to deep-link the `BusinessRoute`, but need the `id` in the `SplashRoute`

**Comment by Milad-Akarie** [comment]
Business route has no path so how are you supposed to deep-link to it?

**Comment by devmuaz** [comment]
Yes, that's why I'm using the `SplashRoute` as a deep-link destination because I need the `id` in the splash first, then I'm doing it programmatically pushing the `BusinessRoute` with that `id` came from the splash

**Comment by Milad-Akarie** [comment]
@devmuaz  so you're the one pushing the page again and again into the stack, maybe try navigate instead of push, or just keep in your mind that setting keepHistory to false the business route will never stay in stack if you push a another page above it.

**Comment by devmuaz** [comment]
Yeah, I tried calling this from the `SplashRoute`:
```dart
appRouter.navigate(BusinessRoute(id: id));
```

but still, the route is getting called multiple times

**Comment by Milad-Akarie** [comment]
have you tried with rebuildStackOnDeepLink: false? 
in general if you're not doing in thing inside of your splash screen, ( just branding and then redirecting ) you should consider using a native splash screen

**Comment by devmuaz** [comment]
Hmm lemme try setting it to `false`.

Actually, the splash route has many functionalities inside and the whole app depends on this route before the app gets started and the deep-link `id` is one of them.

**Comment by devmuaz** [comment]
@Milad-Akarie Nah, still the same! I even tried to write a `Guard` to that route to prevent the duplication, but never worked tho!

**Comment by devmuaz** [comment]
Yes, unfortunately, the `keepHistory` indeed removes the route once a new route gets pushed above it!

**Comment by devmuaz** [comment]
@Milad-Akarie issue has been fixed, it was as you mentioned above my mistake somewhere in the code and after digging deeper, found out that the page is getting rebuilt causing it to push the page multiple times.

My mistake is that I was doing it in the UI, the solution was to move the logic somewhere safe in business logic where UI builds has no effect in there!

Thanks for bringing that in mind!

**Comment by guillaumeboussion** [comment]
@devmuaz hey, did you manage to build your deep link on iOS with your app terminated and your stack needing the splash initialization ?
