### ISSUE TITLE
Install/setup. Annotator not recognized. Won't build.

### ISSUE THREAD

**Issue by willhaslett** [Milad-Akarie/auto_route_library#195]
Following the docs for install and setup, the annotator isn't recognized and my project won't build. The latter may (?) be a collision between `auto_route` and `moor`, but I have no way of knowing. The blue line under the import indicates that the package is being imported but not used. What am I missing? If it's a typo, my apologies. Have stared at it...

<img width="1231" alt="Screen Shot 2020-08-03 at 4 33 41 PM" src="https://user-images.githubusercontent.com/2914495/89226282-b6b92e00-d5a9-11ea-86a5-131a24165b9a.png">

```
[SEVERE] moor_generator:moor_generator on lib/main.dart (cached):
Error running MoorGenerator
line 1, column 2434 of package:MoodTriggers2/main.dart: Could not resolve annotation for class $Router
  ╷
1 │ ┌ @MaterialAutoRouter(
2 │ │   routes: <AutoRoute>[
3 │ │     MaterialRoute(page: HomeScreen, initial: true),
4 │ │     MaterialRoute(page: LoginScreen),
5 │ │     MaterialRoute(page: DbViewerScreen),
6 │ │     MaterialRoute(page: AssessmentStartScreen),
7 │ │   ]
8 │ └ )
```

**Comment by willhaslett** [comment]
btw, the ask is not to have my code debugged. My suspicion is that the docs could use some clarifying editing.

**Comment by theweiweiway** [comment]
Is this still a problem in 1.0.1?

**Comment by theweiweiway** [comment]
Closing due to stale issue
