### ISSUE TITLE
Codegen can't find widgets, they need to be imported into the app_router file

### ISSUE THREAD

**Issue by callum-mudbath** [Milad-Akarie/auto_route_library#1951]
When running codegen, the generated file errors, stating that the child of the AutoRoutePage isn't a class. To fix this, I need to import the widget into the page where app_router is defined.

Is this expected? If so that's fine, but it could be clearer in the docs that this is required. I don't really see the point of the codegen though in this case, why not just let me import the widget and defined a route?

**Comment by xeinebiu** [comment]
extend "$AppRouter" instead of "_$AppRouter" and remove the "part ..." declaration.

Should be fine after.

**Comment by Milad-Akarie** [comment]
@xeinebiu  exactly

**Comment by pvaibhav** [comment]
In V9 we have to 'extend RootStackRouter', and the problem comes back. What's the recommended solution now?

**Comment by ortemmetro** [comment]
Yes, with RootStackRouter there is a same problem. The error says : "Error: Couldn't find constructor 'SomeWidget'"
