### ISSUE TITLE
IOS swipe back make TextField not focus when tab on TextField when app build with flutter 3.22 

### ISSUE THREAD

**Issue by RubyRook** [Milad-Akarie/auto_route_library#1955]
auto_route: ^8.1.3
flutter 3.22
plateform: IOS

https://github.com/Milad-Akarie/auto_route_library/assets/36258256/7c663d50-afa9-49fe-ba61-8914ae11fcd9

**Comment by guplem** [comment]
We are facing the same issue

**Comment by RubyRook** [comment]
It seem like the problem not come from auto_route. I found the same issue here: https://github.com/flutter/flutter/issues/148867. The main problem come from flutter 3.22 itself. I will close this issue.
