### ISSUE TITLE
New Xcode error out of the blue

### ISSUE THREAD

**Issue by arualana** [Milad-Akarie/auto_route_library#1959]
All of a sudden I am getting this error on bitrise build

`Error (Xcode): ../.pub-cache/hosted/pub.dev/auto_route-7.8.5/lib/src/router/widgets/auto_route_navigator.dart:116:14: Error: The method 'PopScope' isn't defined for the class 'AutoRouteNavigatorState'`

Using auto_route: ^7.8.4

The flutter version being installed is https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.13.7-stable.zip

Note: previous builds that had passed before now too get this error too on trying to rebuild them, so it is nothing in the new code causing this. So, for the same code there were no issues 2 months ago

**Comment by Milad-Akarie** [comment]
@arualana  it seems like a flutter upgrade or caching issue.
