### ISSUE TITLE
AutoTabsRouter.pageView sibling views defaults to path ''

### ISSUE THREAD

**Issue by zachbrown-unosquare** [Milad-Akarie/auto_route_library#1962]
I'm using AutoTabsRouter.pageView with a bottom nav bar. The bottom nav bar has 4 icons that all represent a parent resource of some sort with a detail view. The list and detail views are defined as siblings.

If I first navigate to the list view, then try to navigate to the detail view everything works as expected. If I then, after the list view has been loaded at least once, navigate to one of the details of that list from somewhere else in the app, it works fine. BUT... if I restart the app, then try to navigate directly to the detail view before the list view has loaded at least once it just navigates to the list, then re-navigating works correctly. Basically the detail views sibling list view has to have loaded at least once in order for the detail routes to work. This was working in the past.

I was using an older version of flutter 3.16.0. Last week I upgraded flutter version to latest as well as all the packages to the latest. After some research it looks like flutter 3.16.3 made some changes that may have broken things. However, for the life of me I can't figure out how to get back to my original behaviour. I had to roll back the flutter version i'm using, downgrade some of the packages for now, but really want to upgrade everything so I can take advantage of some of the new stuff in dart.

Anyone have any idea's as to what is obvious that I might be missing?

**Comment by zachbrown-unosquare** [comment]
AutoRoute(
          path: 'colors',
          page: ColorsRoute.page,
          children: [
            AutoRoute(
              path: '',
              page: ColorsListRoute.page,
            ),
            AutoRoute(
              path: 'detail/:id',
              page: ColorsDetailsRoute.page,
              usesPathAsKey: true,
            )
          ],
        ),

**Comment by Milad-Akarie** [comment]
@zachbrown-unosquare  are you still having an issue?
