### ISSUE TITLE
Cannot navigate to child route with @PathParam.inherit("param").

### ISSUE THREAD

**Issue by dipak-pd** [Milad-Akarie/auto_route_library#1963]
**Getting error when trying to navigate to a nested route:**

I/flutter ( 6896): Missing or invalid required parameter
I/flutter ( 6896): Failed to parse [int] quotationId value from null
I/flutter ( 6896): #0      Parameters.getInt (package:auto_route/src/common/parameters.dart:85:7)
I/flutter ( 6896): #1      new $AppRouter.<anonymous closure>.<anonymous closure> (package:shilpkar/router/router.gr.dart:279:39)
I/flutter ( 6896): #2      RouteData.argsAs (package:auto_route/src/route/route_data.dart:101:22)
I/flutter ( 6896): #3      new $AppRouter.<anonymous closure> (package:shilpkar/router/router.gr.dart:277:30)
I/flutter ( 6896): #4      RootStackRouter._pageBuilder (package:auto_route/src/router/controller/root_stack_router.dart:161:20)
I/flutter ( 6896): #5      StackRouter._addEntry (package:auto_route/src/router/controller/routing_controller.dart:1570:29)
I/flutter ( 6896): #6      StackRouter._push (package:auto_route/src/router/controller/routing_controller.dart:1275:14)
I/flutter ( 6896): <asynchronous suspension>

**This is route config**
```
AutoRoute(
     page: DashboardQGRoute.page,
     path: "project-services/quotation-new/:quotationId",
     children: [
         AutoRoute(
         page: RoomSelectionRoute.page,
         path: "room-selection",
             ),
        ]),
```

**DashboardQG screen**

```
@RoutePage()
class DashboardQGScreen extends ConsumerWidget {
  const DashboardQGScreen({
    @PathParam('quotationId') required this.quotationId,
    super.key,
  });
  final int quotationId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: const CommonAppBar(title: Text("data")),
      body: Center(
        child: IconButton(
          onPressed: () {
            context.router.push(RoomSelectionRoute());
          },
          icon: Icon(Icons.add),
        ),
      ),
    );
  }
}
```

**RoomSelection Screen**

```
@RoutePage()
class RoomSelectionScreen extends StatelessWidget {
  const RoomSelectionScreen(
      {super.key, @PathParam.inherit('quotationId') required int id});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CommonAppBar(title: Text("Room selection")),
      body: Container(),
    );
  }
}
```

**Comment by abhi259** [comment]
Facing this same issue

**Comment by ghanasyam-n** [comment]
I am also facing similar issue with AutoRoute.before it was working fine.

**Comment by dipak-pd** [comment]
I don't understand what's wrong with this package, I can't even navigate to any nested route.

**Configuration**

```

@AutoRouterConfig(replaceInRouteName: 'Screen,Route')
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => <AutoRoute>[
        AutoRoute(
            page: Dashboard.page,
            path: '/dashboard',
            initial: true,
            children: [AutoRoute(page: ProjectRoute.page, path: 'project')])
      ];
}

```

**Not able to navigate either push or pushNamed**

`
 context.router.push(ProjectRoute());
`

`context.router.pushNamed('/dashboard/project');`

Every time it's navigating to dashboard.

**Comment by dipak-pd** [comment]
#1958 is similar issue

**Comment by uvais-codes** [comment]
Same issue here.

**Comment by Mik77o** [comment]
Nested navigation seems to be broken to some extent. When I use the tabbar and try to push further, it just doesn't work (latest Flutter, latest version of auto_route, Flutter web).

**Comment by Mik77o** [comment]
@dipak-pd I fixed issues with nested navigation when I used AutoRouter(). You can read about this in docs for this package (nested navigation section).

**Comment by dipak-pd** [comment]
> @dipak-pd I fixed issues with nested navigation when I used AutoRouter(). You can read about this in docs for this package (nested navigation section).

@Mik77o Thanks, I'll try again

**Comment by Milad-Akarie** [comment]
@dipak-pd  is there an AutoRouter widget inside DashboardQGRoute.page ?

**Comment by dipak-pd** [comment]
> @dipak-pd is there an AutoRouter widget inside DashboardQGRoute.page ?

No, only flutter widgets are there inside DashboardQGRoute.page.

I also tried out with a new project, it doesn't even work there

You can check this : https://github.com/dipak-pd/auto-router-test

**Comment by pfcstyle** [comment]
Facing same problem.  
v.7.9.2

**Comment by bughoho** [comment]
same problem

**Comment by jakelaws1** [comment]
same problem as well

**Comment by Milad-Akarie** [comment]
To render child routes you need a nested AutoRouter Widget ( an outlet ) 
please read the docs more carefully https://pub.dev/packages/auto_route#nested-navigation
