### ISSUE TITLE
deepLinkBuilder && doubling element's tree

### ISSUE THREAD

**Issue by tremp-m** [Milad-Akarie/auto_route_library#1965]
hi. I encountered either a problem, or a bug, or I don’t understand something. let's take it as an example - https://github.com/Milad-Akarie/auto_route_library/tree/master/auto_route/example/lib/web_demo

let's make some small changes:
```
@override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      theme: ThemeData.dark(),
      debugShowCheckedModeBanner: false,
      routerConfig: _appRouter.config(
        reevaluateListenable: authService,
        deepLinkBuilder: (deepLink) {
          return DeepLink.defaultPath;
        },
      ),
    );
  }
```
now let's launch (in chrome browser) and go to user profile page. Run Flutter inspector and see one UserProfilePage in tree
![Снимок экрана 2024-05-31 в 00 14 25](https://github.com/Milad-Akarie/auto_route_library/assets/48671789/519e2b4e-fac9-4197-a9d9-ac53356ab7ef)

then push chrome system back button, then refresh flutter inspector and see two UserProfilePage in tree
![Снимок экрана 2024-05-31 в 00 18 04](https://github.com/Milad-Akarie/auto_route_library/assets/48671789/8c9211a0-ef25-4b9a-b472-6f1fe890a911)

Why this behavior? Why do we go to deepLinkBuilder during such transitions? How can I filter only a specific deep link, but leave all paths inside the application unchanged?

**Comment by Milad-Akarie** [comment]
is there a reason why you're returning the default window path instead of the platform link inside deepLinkBuilder?

**Comment by tremp-m** [comment]
it's only simple example. There is can be some rules for routes replacement.

**Comment by Milad-Akarie** [comment]
@tremp-m show your navigation code please
