### ISSUE TITLE
Rebuilt full material page after selecting a textfield

### ISSUE THREAD

**Issue by bounty1342** [Milad-Akarie/auto_route_library#197]
Hi,

I have a textfield, and accessing after rooting cause rebuild.

Not sure why and how to correct this. Do you have the same behaviour ?

Regards

 PS : could it be related to https://github.com/flutter/flutter/issues/37878 ?

**Comment by nateshmbhat** [comment]
any updates on this ?

**Comment by bounty1342** [comment]
Actually, not sure this id a bug as several other factor could be the culprit of the rebuild.
Shoukd check textfield is in statfull widget with a global key, and that in the parent tree thzt rebuilt tgere is no unique key that prevent to retrieve in from cache.

**Comment by bounty1342** [comment]
I close the issue.
