### ISSUE TITLE
Automatically back when use CustomRoute with swipe for back

### ISSUE THREAD

**Issue by tientt1304** [Milad-Akarie/auto_route_library#1970]
I have 3 screen called A, B and C (A and C defined with AutoRoute, B defined with CustomRoute).
My follow is A -> B -> C. 
However, a bug occurs when I swipe back from screen C to B continuously for about 2, 3 times or more. The UI automatically navigates back to screen A. 
How can I resolve this issue?

**Comment by Milad-Akarie** [comment]
@tientt1304  is this still an issue with the latest release?
