### ISSUE TITLE
Unable to Set Custom Transition Duration While Maintaining iOS Swipe Back Gesture

### ISSUE THREAD

**Issue by snackva** [Milad-Akarie/auto_route_library#1971]
I am using AutoRoute in my Flutter project and encountering an issue when trying to set a custom transition duration for routes. I would like to maintain the default iOS swipe back gesture while having a custom transition duration.

**Problem:**

When I use `CustomRoute` to set the transition duration, the swipe back gesture on iOS is lost:

```dart
CustomRoute(
  page: ProfileRoute.page,
  path: "/profile/:userId",
  guards: [AuthGuard()],
  durationInMilliseconds: 500,
  transitionsBuilder: TransitionsBuilders.slideLeft
)
```

On the other hand, using `AutoRoute` maintains the swipe back gesture but does not allow me to set a custom transition duration:

```dart
AutoRoute(
  page: ProfileRoute.page,
  path: "/profile/:userId",
  guards: [AuthGuard()]
)
```

**Request:**

Is there a way to achieve both a custom transition duration and maintain the iOS swipe back gesture? Any guidance or suggestions on how to resolve this issue would be greatly appreciated.

**Additional Information:**

- Flutter version: 3.19.6
- AutoRoute version: 8.1.3
- AutoRoute generator version: 8.0.0

Thank you for your help!

**Comment by Milad-Akarie** [comment]
Hey @snackva unfortunately this is not a bug, this is an intended behaviour, it doesn't make sense to swipe-back on a page that  transitions from bottom up or from top down for example.

**Comment by snackva** [comment]
Thanks @Milad-Akarie but the desired behavior is to have the same transition animation and swipe back gesture in iOS while changing the transition duration. Isn't there a way to archieve that?

**Comment by snackva** [comment]
Any update? @Milad-Akarie

**Comment by Milad-Akarie** [comment]
@snackva not going to be able to help with this as I have no plans on customising a platform's default transition 
maybe try to extend the cupertino page route your self and use it as a custom route.

**Comment by leo596566** [comment]
> 有更新嗎？[@Milad-Akarie](https://github.com/Milad-Akarie)

@snackva I also encountered this problem. May I ask how to solve it?
