### ISSUE TITLE
Got an error when navigation back web button with nested route

### ISSUE THREAD

**Issue by duymanhit** [Milad-Akarie/auto_route_library#1973]
My flutter version is 3.22.2. From route A, I navigate to nested route nested-A, then continue to navigate to route B. When I go back from B by the web back button, I get an Error:

```
Assertion failed: file:///C:/flutter/packages/flutter/lib/src/widgets/navigator.dart:3315:14
!popResult
is not true
```

**Comment by rsegecin** [comment]
same here. The browser navigator back button throws me this same error `!popResult is not true`, but it works if I haven't visited other tabs from AutoTabsScaffold. Navigating with `Navigator.pop(context)` or `context.router.maybePop()` it pops the stack without a problem.

**Comment by rsegecin** [comment]
I'm working with `auto_route: ^8.1.3`

**Comment by Milad-Akarie** [comment]
@duymanhit  should be fixed in the latest version, Thanks for reporting.

**Comment by duymanhit** [comment]
@Milad-Akarie Thank you so much. I really appreciate your effort
