### ISSUE TITLE
Route get reset after keyboard appears

### ISSUE THREAD

**Issue by Hamlet626** [Milad-Akarie/auto_route_library#1975]
The route always fallbacks to the initial route after the keyboard appears like when tapping into a text field. 

It appearss like this

https://github.com/Milad-Akarie/auto_route_library/assets/26908521/328283d0-e7f7-4f22-adab-e2f2186421ff

My MaterialApp is something like this
```

  @override
  Widget build(BuildContext context,WidgetRef ref) {

    return MaterialApp.router(
      builder: (context,child)=>ResponsiveBreakpoints.builder(
        child: child!,
        breakpoints: [
          const Breakpoint(start: 0, end: 600, name: MOBILE),
          const Breakpoint(start: 601, end: 900, name: TABLET),
          const Breakpoint(start: 901, end: 1536, name: DESKTOP),
          const Breakpoint(start: 1536, end: double.infinity, name: '4K'),
        ],
      ),
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
      routerConfig: AppRouter().config(
          reevaluateListenable: ReevaluateListenable.stream(FirebaseAuth.instance.userChanges()))
    );
  }
```
I'm using 
```
context.navigateTo(EmailPasswordRoute());
```
to navigate from first screen to second screen.

I put nothing inside the textField, and it shows no error when it resets back to the first screen.

PS: Now it's only on android&iOS emulators, I haven't tried on real devices. And if I changed to default Navigator, it won't fall to initial route after keyboard appears, so I'm pretty sure it's some problem with auto_route. 
Plus, I also found that on web, it appears the same problem if I drag and change window size.

**Comment by Milad-Akarie** [comment]
@Hamlet626  just initialize the router outside the build function
