### ISSUE TITLE
Blank screen when first opening the app

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#1978]
Hi, 
I noticed that the initialization of the router is somewhat slower than other solutions out there (I tried GoRouter just to see what I'm missing - turned out to be nothing but bugs, This package is miles ahead!).

There is a small delay between the app splash screen and the actual first page showing app, there is a blank screen showing for a couple of milliseconds, while with GoRouter there is no delay at all!

I investigated a little and noticed the placeholder parameter in the appRouter.config() function, why is this needed? can't the package show the first page without a delay?

Thanks

**Comment by Milad-Akarie** [comment]
Hey @naamapps normally there isn't any delay, nothing that I know of at least, are you guarding the main route or using a global guard maybe?

**Comment by naamapps** [comment]
Hi @Milad-Akarie !
I do have a guard, but this happens also when deleting the guard temporarily.
It is also very noticeable on debug mode, where the blank page appears for multiple seconds.

I think these lines are the culprit.
https://github.com/Milad-Akarie/auto_route_library/blob/31657c7e575d2da6af3b015b27fc7c9da58ee45b/auto_route/lib/src/router/widgets/auto_route_navigator.dart#L112C1-L115C15

**Comment by Milad-Akarie** [comment]
@naamapps the place holder is there because you can't render a navigator with empty pages list. can you create a simple repo repreducing the issue?
