### ISSUE TITLE
feat: Static functions for routes on screens

### ISSUE THREAD

**Issue by dickermoshe** [Milad-Akarie/auto_route_library#1979]
There is a pain point IMHO when working with auto route that extensions could solve

Now every `Screen` has a `Route` accosiated with it.
This ruins the DevX INMO, because
1. You're referencing a class you've never written. Generated Code should be under the hood only (IMHO)
2. Needless complexity
3. You MUST name a Screen, `Screen`.
4. When `Ctrl+Click` to a widget, you have to make 2 stops.

https://github.com/Milad-Akarie/auto_route_library/assets/75931499/e6abaaca-34e5-41ff-b44f-e7500643f683

It would really nice if instead of dealing with 2 classes for each route:

* `UserScreen`
* `UserRoute`

we had this:
* `UserScreen`
* `UserScreen.route`
* `UserScreen.page`

This could be easily added via an extension:
```dart
extension UserScreenRouteX on UserScreen {
  static UserScreenRoute route({
    Key? key,
    List<PageRouteInfo>? children,
  }) => UserRoute(
    key:key,
    children:children
  );
  static PageInfo get page => UserRoute.page;
}
```

This would solve all of the above issues. This feature is backwards compatible. All of this could be disabled with a flag.

@Milad-Akarie I've got time to work on this. Let me know if you're interested.

**Comment by Milad-Akarie** [comment]
Hey @dickermoshe correct me if I'm wrong but I don't think static extension methods are yet supported in dart.

**Comment by dickermoshe** [comment]
How would you feel about making it a function `page()`

**Comment by dickermoshe** [comment]
It would not look as nice. It would look like a named constructor for the widget.
IMHO, it's still the smarter way to go.

**Comment by Milad-Akarie** [comment]
Hey @dickermoshe how about we delay this until macros are all figured out? your first suggestion might be possible with macros.
