### ISSUE TITLE
[web] initial route not in path on deeplink

### ISSUE THREAD

**Issue by archie-sh** [Milad-Akarie/auto_route_library#198]
With flutter router the behaviour is the initscreen is loaded then the homescreen using the deeplink http://localhost:7357/#/home:
```
MaterialApp(
        navigatorKey: navigatorKey,
        initialRoute: '/',
        routes: {
          '/': (context) => InitScreen(),
          '/home': (context) => HomeScreenBuilder(),
        },
      ),
```
With auto_route and the deeplink http://localhost:7357/#/home only the homescreen is in the stack the initial route is skipped
```
@MaterialAutoRouter(routes: [
  MaterialRoute(page: InitScreen, initial: true,),
  MaterialRoute(
    page: HomeScreenBuilder, path: "/home", guards: [AuthGuard],
  ),
])
class $Router {}
```
```
MaterialApp(
        builder: ExtendedNavigator.builder(
            router: Router(),
            initialRoute: '/',
            navigatorKey: navigatorKey,
            guards: [AuthGuard()],
            builder: (ctx, extendedNav) => Theme(
              data: ThemeData(
                pageTransitionsTheme: NoTransitionsOnWeb(),
                brightness: Brightness.light,
                primarySwatch: Colors.blue,
                visualDensity: VisualDensity.adaptivePlatformDensity,
              ),
              child: extendedNav,
            )),
      ),
```

**Comment by Milad-Akarie** [comment]
@archie-sh  Yes, this's the intended behavior for web. opening "/home" should only push the home page.

**Comment by archie-sh** [comment]
But it does not match the flutter behaviour

https://api.flutter.dev/flutter/widgets/Navigator/defaultGenerateInitialRoutes.html

> For example, if the route /stocks/HOOLI was used as the initialRoute, then the Navigator would push the following routes on startup: /, /stocks, /stocks/HOOLI. This enables deep linking while allowing the application to maintain a predictable route history.

If the inteded behaviour is different from flutter's  then I would suggest documenting it in the README.

**Comment by Milad-Akarie** [comment]
@archie-sh  Yes, This's how it works on native, on web it pushes flat pages as the stack is managed by the browser.
I believe when flutter team is finished with their new navigation solution it's gonna behave something like this on web. 

and I know that some docs are missing, I've been really busy lately so I apologize about that.

**Comment by archie-sh** [comment]
Hey, no worries, thanks for the greaat library. I have had a really good experience with it on mobile. 

I will use the native router for now and see what the flutter team comes up with 
https://github.com/flutter/flutter/issues/45938
I think it will be a while until the new navigation is there and ill refactor accordingly when it happens.

**Comment by Milad-Akarie** [comment]
@archie-sh it's cool, are you saying you'd like a similar mobile experience on the web?

**Comment by archie-sh** [comment]
I did not understand the quesiton. 

Bu I think web its different than mobile because users can bookmark a route and then navigate themselves to a specific route, its the issue im having right now.

**Comment by Milad-Akarie** [comment]
I mean when you navigate to "/second" on web you'd like your stack to be ["/", "/second"]?

**Comment by archie-sh** [comment]
Yes, just like the native flutter router works.

**Comment by passsy** [comment]
I was very confused when I noticed `auto_route` doesn't behave as the normal Router.

Could it be changed to also use `defaultGenerateInitialRoutes`? Maybe make it optional to not be a breaking change. Although I suggest making it the default

**Comment by theweiweiway** [comment]
`includePrefixMatches: true` solves this in the most recent Autoroute Version 2.x
