### ISSUE TITLE
auto_route fragment support

### ISSUE THREAD

**Issue by TekExplorer** [Milad-Akarie/auto_route_library#1980]
I want to have certain routes use fragments to represent the current location, such as the current file being edited

I also use it for filters in some places, though I recognize that those could be query parameters.

Its also used for my login route, where a url needs to be inputted and then an api key on the next page. That Uri needs to be in the path, but urlEncoding it looks honestly terrible. Plus, its not a great api for the sake of deep links.

I dont really see fragments used at all, so i'm a little concerned.

If its _*not*_ supported, what would it take to support it?

**Comment by TekExplorer** [comment]
It really doesn't look like it does support fragments...
This is despite `PageRouteInfo` having the field already, so... I'm confused. Why is the field there if it isn't being used?

**Comment by Milad-Akarie** [comment]
@TekExplorer  are you you saying you can't read #fragment from a url?

**Comment by TekExplorer** [comment]
> @TekExplorer  are you you saying you can't read #fragment from a url?

I'm saying I can't use it as a parameter In my route. This is important to me as the fragment is sometimes required, or otherwise has important semanting meaning.

Go router builder has the same issue if just not addressing the fragment at all, despite being otherwise trivial to implement.

**Comment by TekExplorer** [comment]
@Milad-Akarie What are your thoughts on the matter? Do you intend to properly support fragments for routes?

**Comment by Milad-Akarie** [comment]
@TekExplorer fragment support is added in the latest version of auto_route, make sure you update the generator as well.

use the @urlFragment annotation the same way you'd use @QueryParam.
