### ISSUE TITLE
Function pushAll won't work on WEB

### ISSUE THREAD

**Issue by prologikus** [Milad-Akarie/auto_route_library#1981]
The pushAll function in auto_route does not work correctly on the web. When navigating through multiple routes using pushAll and then going back, the user is taken to the initial route instead of the previous one in the list.

**Steps to Reproduce**

1. Use the pushAll function as shown:

```
void example() async {
  appRouter?.pushAll([
    PlaceRoute(),
    ProductRoute(),
  ]);
}
```
2. Navigate back using the native browser buttons
3. Observe the stacking don't work

**Workaround**

 ```
 void example() async {
    if (kIsWeb) {

      appRouter?.push(PlaceRoute());
      await Future.delayed(Constants.defAnimDur);
      appRouter?.push(ProductRoute());
    } else {

      appRouter?.pushAll([
        PlaceRoute(),
        ProductRoute(),
      ]);
    }
  }
```

**Comment by Milad-Akarie** [comment]
Hey @prologikus actually this makes sense, browser's history does not care about the applications's stack it just keeps track of the visited locations, so technically you never visited PlaceRoute(), it was not shown to user,  you could argue that it doesn't make sense to go back to a location you've never visited. 

I'm closing this for now, but feel free to explain your use-case further.
