### ISSUE TITLE
Error when using 8.14

### ISSUE THREAD

**Issue by jovet-github-acn** [Milad-Akarie/auto_route_library#1983]
../../.pub-cache/hosted/pub.dev/auto_route-8.1.4/lib/src/router/auto_route_page.dart:126:15: Error: Superclass has no getter named 'popGestureEnabled'.
    if (super.popGestureEnabled) {
              ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by jovet-github-acn** [comment]
Additional issue when using 8.2.0.

Because auto_route >=8.2.0 depends on meta ^1.12.0 and every version of integration_test from sdk depends on meta 1.11.0, auto_route >=8.2.0 is incompatible with integration_test from sdk.
So, because cristy_pos depends on both integration_test from sdk and auto_route ^8.2.0, version solving failed.

**Comment by ain-py** [comment]
same issue, please let me know if you've found any solution.

**Comment by Milad-Akarie** [comment]
what flutter version are you using?

**Comment by ain-py** [comment]
@Milad-Akarie im using version 3.19.6

**Comment by tomkad99** [comment]
I tried on Flutter 3.22.2 and the problem currently disappeared

**Comment by Mir1001** [comment]
Same problem on Flutter 3.19.5. Tmp. fix   auto_route: ^8.0.3 ->  auto_route: 8.0.3

**Comment by Guang-B** [comment]
I tried on Flutter 3.22.2 the problem still exist.

**Comment by devBamidele** [comment]
I upgraded to Flutter 3.22.2, bumped auto route to 8.2.0 and everything worked fine

**Comment by agonzalezpuerta** [comment]
I'm facing the incompatibility issue due to meta ^1.12.0 as well. Using auto_route 8.3.0 and Flutter 3.24.0.

**Comment by cecepasinechka** [comment]
> Same problem on Flutter 3.19.5. Tmp. fix auto_route: ^8.0.3 -> auto_route: 8.0.3

Fixed the problem for me.
