### ISSUE TITLE
Creating feature flow using auto_route

### ISSUE THREAD

**Issue by SAGARSURI** [Milad-Akarie/auto_route_library#1985]
Hey @Milad-Akarie 
Thank you for the library. I am planning to create feature flows in my flutter app. E.g payment flow, accounts flow etc. Each flow will encapsulate the navigation logic. I am trying to achieve something similar with auto_route:
[flow_builder](https://pub.dev/packages/flow_builder)

**Comment by Milad-Akarie** [comment]
@SAGARSURI what state management solution are you using? this properly can be achieved using AutoRouter.declerative builder

**Comment by SAGARSURI** [comment]
I am using BLoC. Can you share a basic example which shows a simple feature flow?

**Comment by SAGARSURI** [comment]
I am struggling to figure out how to connect `AutoRouter.declarative` with the main `AppRouter`.

**Comment by naveenr-egov** [comment]
`routerDelegate: AutoRouterDelegate.declarative(
                              widget.appRouter,
                              navigatorObservers: () => [AppRouterObserver()],
                              routes: (handler) => state.maybeWhen(
                                orElse: () => [
                                  const UnauthenticatedRouteWrapper(),
                                ],
                                authenticated: (_, __, ___, ____, _____) => [
                                  AuthenticatedRouteWrapper(),
                                ],
                              ),
                            ),`
                            
@SAGARSURI check if this works

**Comment by Milad-Akarie** [comment]
@SAGARSURI onNavigate is only called when you use router.navigate or navigate by browser's address bar

**Comment by iamnabink** [comment]
I think we can build a flow builder or achieve something similar with `AutoRouter.declarative`, does anyone has any idea on the limitation of `AutoRouter.declarative` over [FlowBuilder](https://pub.dev/packages/flow_builder) ?
