### ISSUE TITLE
When I navigate to the same route a second time, the page doesn't refresh.

### ISSUE THREAD

**Issue by lushan1314** [Milad-Akarie/auto_route_library#1986]
When I navigate to the same route a second time, if the rawQueryParams doesn't change, the page doesn't refresh.

I know the design is good, the normal situation is correct, thank you for your efforts. But I just wanted to ask if it is possible to set up to always refresh the route each time navigate.

I noticed that every time the PageRouteInfo object's operator and the associated parameters of the hashCode method changed, the route was refreshed. I don't want to give each route a random number, is there a more convenient way to handle this situation?

**Comment by Thomas-Lilley** [comment]
I had this issue, you can turn state preservation off in the route declaration, hope this helps! 🙂 

```
AutoRoute(
    path: "",
    page: ExampleRoute.page,
    maintainState: false,
),
```

**Comment by lushan1314** [comment]
> 我遇到了这个问题，你可以在路线声明中关闭状态保存，希望这会有所帮助！🙂
> 
> ```
> AutoRoute(
>     path: "",
>     page: ExampleRoute.page,
>     maintainState: false,
> ),
> ```

Thank you for your reply. 
I had considered trying your solution before, but I was a bit concerned that it might cause other issues, such as the page state mysteriously being lost. 
So, after careful consideration, I decided to add a random `@QueryParam` to the `route` and pass a `Uuid` each time. This ensures that the page is refreshed every time the route is entered.

**Comment by lushan1314** [comment]
I found that the solution I used is only suitable for navigating to a nested route. Normal navigate operations still cannot refresh the page. For example:
`pageA -> pageB -> pageC -> pageD -> navigate pageA`
The widget is recreated, but the State does not change and does not rebuild, so the page does not refresh. Did I misunderstand the usage of `navigate`?
