### ISSUE TITLE
Replacing go_router with auto_route in widget tests

### ISSUE THREAD

**Issue by vukan-markovic** [Milad-Akarie/auto_route_library#1987]
Hi,

I previously used go_router for navigation on the project, and now I am replacing it with aout_route. Everything works fine except tests, I have the following ones:

```
extension PumpApp on WidgetTester {
  Future<void> pumpRealRouterApp(String location) async {
    return pumpWidget(
      TranslationProvider(
        child: MaterialApp.router(
          routerConfig: AppRouter.router(location),
        ),
      ),
    );
  }
}
```

Here the AppRouter was configured with go_router, but now when I use auto_route, I am unsure how to make this work.

**Comment by Milad-Akarie** [comment]
@vukan-markovic just constructor a router instance then use it like this 
router.config(deepLocationBuilder: (_)=> DeepLink.path(location))

**Comment by Vukan-Levi9** [comment]
@Milad-Akarie You probably meant deepLinkBuilder? I tried that but it's not working for me, an example of my router test is looking like this, and I get the following error:
<img width="386" alt="Screenshot 2024-07-15 at 09 25 17" src="https://github.com/user-attachments/assets/fed24492-cc83-4221-827c-43f005be03a2">
<img width="529" alt="Screenshot 2024-07-15 at 09 25 08" src="https://github.com/user-attachments/assets/ea520746-7a28-477c-9a14-6ee87d226895">

**Comment by Milad-Akarie** [comment]
This snippet is from auto_route test folder and it actually work
Future<void> pumpRouterApp(
  WidgetTester tester,
  RootStackRouter router, {
  String? initialLink
}) {
  return tester
      .pumpWidget(
        MaterialApp.router(
          routeInformationParser: router.defaultRouteParser(),
          routerDelegate: router.delegate(
            deepLinkBuilder: (link) =>
                initialLink == null ? link : DeepLink.path(initialLink),
          ),
        ),
      )
      .then((_) => tester.pumpAndSettle());
}

**Comment by Vukan-Levi9** [comment]
Yes, it works, tnx.
