### ISSUE TITLE
Overide a route 

### ISSUE THREAD

**Issue by naveenr-egov** [Milad-Akarie/auto_route_library#1988]
I have a requirement where there is a Page B in PackageZ i'm overriding the page B in my main app.
In PackageZ there are screens PageA, PageB, PageC

In main app
custompage extends Page B. 

When in the PackageZ there is navigation happening from PageA to PageB

i want to navigate to custompage instead of PageB

**Comment by naveen-egov** [comment]
```
     } else if (!route.hasChildren) {
      // INFO : Added this code to support Nested Auto Rotue
        if(config is RedirectRoute){
              final defaultMatches = _match(Uri(path: config.changePath(config.redirectTo).path),routes );
        if (defaultMatches != null) {
          return defaultMatches.first;
        }
    }
```


auto_route/lib/src/matcher/route_matcher.dart

**Comment by Milad-Akarie** [comment]
try overriding the page builder inside router.pagesMap to build your custom page
