### ISSUE TITLE
Manage System back button with Auto route with alternative way

### ISSUE THREAD

**Issue by Zokirjon-Ashiraliyev** [Milad-Akarie/auto_route_library#1989]
I can not manage system back button with auto route in android and IOS. For example I have A and B screens . A screen has  back button  which stay leading in the appbar and a button stay in center. If you click a button in center of A screen, you can move int b screen.   B screen does not have back button , user only back to A screen by using System back button. My first stype is that i move B screen by A screen , after that i back into A screen by using system back button .  Then I click a button  which stay leading in Appbar, but   auto route open B screen.  I see some solution to this situation , sucha popScope. But i can not find alternative way for this situation. Please help me.

**Comment by SAGARSURI** [comment]
Use `AutoLeadingButton()` in your `AppBar()`. The back navigation will work. It's also mentioned in the documentation.

**Comment by Zokirjon-Ashiraliyev** [comment]
Ok thanks
