### ISSUE TITLE
Can’t generate routes

### ISSUE THREAD

**Issue by zhllm** [Milad-Akarie/auto_route_library#199]
![image](https://user-images.githubusercontent.com/65887926/89436213-807dd900-d778-11ea-83f7-268b06e14aa2.png)

**Comment by zhllm** [comment]
forever stay action 1，and don't known what meaning that warnings.

**Comment by Dhruv-Garg79** [comment]
I am also getting the same error.

auto_route version 0.6.7
flutter 1.20.0-7.2.pre

**Comment by frank06** [comment]
Just curious: is this library tested somehow?

**Comment by zhllm** [comment]
just now, i upgrade fluuter to Channel master, 1.21.0-6.0.pre.226, and set auto_route: ^0.6.0, run 
`
flutter packages pub run build_runner clean;
flutter packages pub run build_runner build;
`

it's work!!!!!!!

**Comment by Dhruv-Garg79** [comment]
I had tried the beta branch and stable branch wasn't working on them. Moving to master branch will not be possible. I have done changes in the generated file manually for now.

**Comment by zhllm** [comment]
emm......beacuse my project is  a demo，it's doesn't matter.

**Comment by Milad-Akarie** [comment]
@zhllm @Dhruv-Garg79 try bumping your build_runner version to ^1.10.1

**Comment by Dhruv-Garg79** [comment]
Hi, I was able to generate successfully after upgrading to flutter 1.20.1 and changing build_runner to ^1.10.1 as suggested by @Milad-Akarie
