### ISSUE TITLE
how to use outer route (parent) inside the inner the route in nested routing

### ISSUE THREAD

**Issue by Anas-Qasem** [Milad-Akarie/auto_route_library#1991]
I'm developing an e-commerce app with a screen called the "View Address Screen." Users can access this screen in two ways: through the edit profile screen or during the checkout process (nested route).

so I created two routes for the "View Address Screen" in `List<AutoRoute> get routes`

``` dart
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => [
        //This route to access the screen from the edit profile screen
        AutoRoute(page: ViewAddressRoute.page),
        //This is the nested route where
        //The user can select his address before checkout
        AutoRoute(
         //This screen is where I use the AutoRouter();
          page: CheckoutPaymentContainerRoute.page,
          children: [
            AutoRoute(page: ViewAddressRoute.page, initial: true),
            AutoRoute(page: PreferredPaymentMethodRoute.page, path: 'PaymentMethod'),
            AutoRoute(page: CheckOutSummaryRoute.page, path: 'CheckOutSummaryRoute'),
          ],
        ),
      ];
}
```
now in the last screen CheckOut Summary Screen, the user can change his address again, so I am trying to navigate to "View Address Screen" using the outer route, not the inner route using `context.router.root`, 
I know this is a bit complex 😅  , so this is a video for a demonstration.

**Expected results**: 

https://github.com/Milad-Akarie/auto_route_library/assets/81823248/a8cc93c4-6c13-4852-a3ed-8da69396b0b8

**Actual results**:

https://github.com/Milad-Akarie/auto_route_library/assets/81823248/c07bcc7e-cf47-49d2-9d87-859a0b74db2e

I managed to create the Expected results by creating another route and returning the same "View Address Screen" widget

``` dart
@RoutePage()
class OuterViewAddressScreen extends StatelessWidget {
  const OuterViewAddressScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const ViewAddressScreen(isInsideCheckoutProcess: false);
  }
}

@RoutePage()
class ViewAddressScreen extends StatelessWidget {
  const ViewAddressScreen({super.key, this.isInsideCheckoutProcess = true});
  final bool isInsideCheckoutProcess;
  @override
  Widget build(BuildContext context) {
    return Scaffold()
  }
}
```
but is there a way to access it as it already exists?

**Comment by Milad-Akarie** [comment]
Hey @Anas-Qasem why don't just push the route? just go context.pushRoute(ViewAddressRoute);
are you getting any errors?

**Comment by Anas-Qasem** [comment]
Hey @Milad-Akarie thanks for replying, actually, there are no errors. Still, if I try to push ViewAddressRoute while I'm in the CheckoutPaymentContainerRoute specifically in step 3 and when I click the change address button ( as the Actual results video shows), In that case, it will navigate to the first screen again (which is the ViewAddressRoute), I think this is happening because the ViewAddressRoute is inside the children of CheckoutPaymentContainerRoute and I'm currently using the context of inner AutoRoute().

the behavior I want is to show ViewAddressRoute as a separate route when the user clicks (change address button), like if I navigate to it directly without going through the CheckoutPaymentContainerRoute, as the Actual results video shows.

I managed to create the Expected results by creating another route and returning the same "View Address Screen" widget
but I think if there is a way to get the outer AutoRoute() I will manage to create the same behavior without the necessary to create another route and return the"View Address Screen" widget, I know this is a bit complex, but hope you get it 😅

**Comment by Milad-Akarie** [comment]
@Anas-Qasem right now this is the only way you can active such setup, I might add 'aliases' to the same route so multiple PageRouteInfo classes are generated.

I'm closing this for now.
