### ISSUE TITLE
How to get result in navigation observer

### ISSUE THREAD

**Issue by alejandrogiubel** [Milad-Akarie/auto_route_library#1994]
How can I get result in navigation observer in didPop method? I can see _result param in debug, but can't access to it.

**Comment by Milad-Akarie** [comment]
Hey @alejandrogiubel not sure if this is possible, do you need the result for logging purposes?

**Comment by alejandrogiubel** [comment]
Hi @Milad-Akarie, in my case I need the result of a "poped" page in the navigation  observer to do some logic. Is tedious to make this logic in a call back in every push to this route. What do you think about it?

**Comment by Milad-Akarie** [comment]
@alejandrogiubel have you tried doing the following? 
 
```dart
  @override
  void didPop(Route route, Route? previousRoute) async {
   final result = await route.popped;
  }
```

**Comment by alejandrogiubel** [comment]
Yes, it's exactly what I was looking for. Thank you very much for the quick response. I'm going to close this issue.
