### ISSUE TITLE
Route Page does not get generated for a few pages

### ISSUE THREAD

**Issue by dhruv-sirodaria** [Milad-Akarie/auto_route_library#1995]
First of all, thank you for this amazing package, I have been using it for quite sometime now and it is really helpful.
I am working on flutter web app, with nested routes and currently running on `auto_route: ^8.2.0` and `auto_route_generator: ^8.0.0`. 
There is a situation where the routes are not getting generated for a particular directory.
Can this be due to the reason that I have a deeply nested folder structure and the path name is too long for the build_runner?

Would really appreciate some help here.
Thank you.

**Comment by Milad-Akarie** [comment]
Hey @dhruv-sirodaria where is your directory located? is there any thing special about this dir?
