### ISSUE TITLE
Cold start app by deep link cause white screen

### ISSUE THREAD

**Issue by lambaosk8** [Milad-Akarie/auto_route_library#1996]
Hello,

I'm facing the issue that when I open app by a URL (cold start - app is not open yet), the app will show the white screen. If the app is open already, no issue. Even I have tried to just open LoginRoute when `initial = true` => still the same white screen. Below is my implementation:

**Router**
```class AppRouter extends _$AppRouter {
  @override
  RouteType get defaultRouteType => const RouteType.material();
  @override
  final List<AutoRoute> routes = [
    AutoRoute(page: IntroRoute.page, fullscreenDialog: true, meta: const {
      'hideBottomNav': true,
    }),
    AutoRoute(path: "/login", page: LoginRoute.page),
    AutoRoute(
        page: MainTabbarRoute.page,
        children: [communityTab, groupTab, messagingTab, notificationTab]),
    AutoRoute(
        path: '/message/detail/:id',
        page: ThreadDetailRoute.page,
        fullscreenDialog: true,
        meta: const {
          'hideBottomNav': true,
        }),
  ];
}
```

**MaterialApp**
```
MaterialApp.router(
            theme: ThemeData(
              useMaterial3: false,
              textSelectionTheme: const TextSelectionThemeData(cursorColor: UIColors.s_black),
            ),
            debugShowCheckedModeBanner: false,
            builder: EasyLoading.init(),
            routerConfig: _appRouter.config(
              includePrefixMatches: true,
              deepLinkBuilder: (deepLink) {
                if (deepLink.path.startsWith('/message/detail')) {
                  if (deepLink.initial) {
                    return const DeepLink([IntroRoute()]);
                  }

                  final threadId = deepLink.path.split('/').last;
                  return DeepLink([
                    ThreadDetailRoute(
                      thread: ThreadModel(threadId: int.parse(threadId)),
                      threadCategory: ThreadCategory.community,
                    )
                  ]);
                } else {
                  return const DeepLink([IntroRoute()]);
                }
              },
            ),
          ),
```

Please note that I'm able to interact with UI elements on the screen even they're white.
![image](https://github.com/user-attachments/assets/44c8498d-d471-4272-8522-b512a0a71269)

Thank you in advance!

**Comment by Milad-Akarie** [comment]
@lambaosk8 does it happen when you open your App normally? without a deep-link  Imean

**Comment by baolamvalidus** [comment]
> @lambaosk8 does it happen when you open your App normally? without a deep-link  Imean

Hi @Milad-Akarie, without deep-link the app works fine. However, begin from the time white screen issue occurred, open app normally will show the white screen. I have inspect the UI => elements still there, they just on white.

**Comment by Milad-Akarie** [comment]
@baolamvalidus what platform are you on? also I'm suspecting it has to do with this line `builder: EasyLoading.init(),`

**Comment by lambaosk8** [comment]
Sorry for lately response. I found out testing on Emulator cause this issue. It not occur on real device. Thanks!

**Comment by AzarouAmine** [comment]
@Milad-Akarie I have the same issue described here but happens in real devices as well!
