### ISSUE TITLE
Default argument value

### ISSUE THREAD

**Issue by BenevidesLecontes** [Milad-Akarie/auto_route_library#20]
Hi thanks for your amazing work and lib. it is possible to have default value on routes?
My use case is, I have a wrapper class that I use for all my routes, this class has `pageType` parameter, on each route definition, I want to pass the default value for this parameter. Thanks

**Comment by BenevidesLecontes** [comment]
@Milad-Akarie I solved using `wrappedRoute`. And it's working fine, but is bit verbose,  because I need to implement the abstract class in every route that I want to use my Wrapper.
I was doing something like this:

```
@autoRouter
class $Router {
  @initial
  PageContainer landPage;
  PageContainer loginUser;
  PageContainer loginPassWord;
  PageContainer home;
  PageContainer loginBiometric;
  PageContainer loginSuccessFeedback;
  PageContainer investLand;
}
```

In each route I need to pass as argument the `PageType`, pageType is a enum that i created.

**Comment by Milad-Akarie** [comment]
I see!
can you share the constructor of your page container

**Comment by BenevidesLecontes** [comment]
```
PageContainer({
    Key key,
    @required this.pageType,
  });
```

**Comment by Milad-Akarie** [comment]
How would you pass args to your child pages?

**Comment by Milad-Akarie** [comment]
You could make your child widgets implement AutoRouterWrapper then wrap them in your PageContainer() of course then you need to pass your child widget to your wrapper widget

```
class LoginPage extends StatelessWidget implements AutoRouteWrapper {
  @override
  Widget get wrappedRoute => PageContainer((type), this (as your child widget);
```

but looking at this I think you might need to use a NestedRouter Implementation where your PageContainer is a root widget.

**Comment by BenevidesLecontes** [comment]
> You could make your child widgets implement AutoRouterWrapper then wrap them in your PageContainer() of course then you need to pass your child widget to your wrapper widget
> 
> ```
> class LoginPage extends StatelessWidget implements AutoRouteWrapper {
>   @override
>   Widget get wrappedRoute => PageContainer((type), this (as your child widget);
> ```
> 
> but looking at this I think you might need to use a NestedRouter Implementation where your PageContainer is a root widget.

I did this.

**Comment by BenevidesLecontes** [comment]
> How would you pass args to your child pages?

No, I'm taking some decisions with this parameter.

**Comment by BenevidesLecontes** [comment]
@Milad-Akarie can I close this, since I already solved using another way?

**Comment by Milad-Akarie** [comment]
@BenevidesLecontes sure man.
Thanks for the insights.
Might think of something to pass in static valuess
