### ISSUE TITLE
Integration Testing using `Patrol`

### ISSUE THREAD

**Issue by OmarYehiaDev** [Milad-Akarie/auto_route_library#2000]
Hello folks!

### Problem

I'm using `AutoRoute` in all of my projects as the best routing solution. Nowadays, I'm trying to write some **E2E Tests** with `Patrol` for one of my apps which heavily depend on a lot of features in the package. The problem now is when I try to use `router.navigate(SomeRoute());`, it doesn't work. However, when I tried to replace one of the navigation methods into `Flutter Navigator V2` way like:
```dart
Navigator.of(context).push(
  MaterialPageRoute(
    builder: (_) => const SomePage(),
  ),
);
```
It worked normally without any problems, so this is really frustrating to me as I've already tried to analyze a lot of under the hood code of how `AutoRouter` works and navigates pages in comparison with `Navigator V2`'s way of work, but I reached a dead end too.

### Sys & Env Info
- Flutter v3.22.2 with Dart v3.4.3
- `auto_route: ^8.1.4`
- `auto_route_generator: ^8.0.0`
- `build_runner: ^2.4.8`
- `patrol: ^3.9.0`
- `mocktail: ^1.0.4` => I've tried to mock the `StackRouter` by it as [this comment](https://github.com/Milad-Akarie/auto_route_library/issues/745#issuecomment-1832559938) but failed in doing that for some reason.

**Comment by Milad-Akarie** [comment]
Hey @OmarYehiaDev  could you share a complete test snippet?
