### ISSUE TITLE
await router.push not working

### ISSUE THREAD

**Issue by tovidd** [Milad-Akarie/auto_route_library#2002]
The `AddressRouterWrapper` is an empty stateless class, that has children `CreateAddressRouter` & `EditAddressRouter`. But await not work if push to `AddressRouterWrapper` to designed children.

This line not await
```flutter
final result1 = await AutoRouter.of(context).push<bool?>(AddressRouterWrapper(
  children: const [CreateAddressRouter()],
));
```

This awaited
```flutter
final result2 = await AutoRouter.of(context).push<bool?>(const CreateAddressRouter());
```

**Comment by tomasweigenast** [comment]
Same here!

**Comment by Milad-Akarie** [comment]
await applies to the parent route you're pushing not the children.

**Comment by tomasweigenast** [comment]
> await applies to the parent route you're pushing not the children.

So what is the way to await the last children? Sometimes you have to push with the parent because:
You are on /profile/address and I want to push to /foo/bar, I can't push just bar because that would not work

**Comment by Milad-Akarie** [comment]
@tomasweigenast Try using callback arguments instead of awaiting results.
