### ISSUE TITLE
Android's Back Button closes App in Sub Route

### ISSUE THREAD

**Issue by MomenMuhammad01** [Milad-Akarie/auto_route_library#2009]
## The Issue 

The Android back button & back gesture are causing the app to close despite being in a sub route
tested on both emulator and real device

My app_router file
[app_router.zip](https://github.com/user-attachments/files/16390403/app_router.zip)

## Flutter doctor : 
```
[✓] Flutter (Channel stable, 3.22.3, on macOS 13.6.6 22G630 darwin-x64, locale en-US)
    • Flutter version 3.22.3 on channel stable at /usr/local/Caskroom/flutter/3.19.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (9 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/momen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.6.6 22G630 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.185

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

Android Version : 13 
auto_route: ^8.3.0
auto_route_generator: ^8.1.0

 
https://github.com/user-attachments/assets/6370af36-b6c6-4aa2-8a55-b92d82e514af

**Comment by Erkam246** [comment]
I’m experiencing the same problem. Sometimes it works, but other times it doesn’t. I’m not sure what’s causing the issue.

**Comment by MomenMuhammad01** [comment]
> I’m experiencing the same problem. Sometimes it works, but other times it doesn’t. I’m not sure what’s causing the issue.

For me it was working fine before but after the latest updates it just start doing this weird behavior

**Comment by huzeyfetascsi** [comment]
greetings, I was looking at issues while examining goroute and autoroute packages. coincidentally, I encountered this problem for the android back button in a project yesterday. as a solution to the AndroidManifest.xml file I solved it by writing `android:enableOnBackInvokedCallback=“false”`  in the application. maybe it will help you. maybe it may not be related to the route package. just wanted to share.

**Comment by MomenMuhammad01** [comment]
> greetings, I was looking at issues while examining goroute and autoroute packages. coincidentally, I encountered this problem for the android back button in a project yesterday. as a solution to the AndroidManifest.xml file I solved it by writing `android:enableOnBackInvokedCallback=“false”` in the application. maybe it will help you. maybe it may not be related to the route package. just wanted to share.

Thanks for sharing, but unfortunately it didn't solve the problem.

**Comment by Milad-Akarie** [comment]
Hey @MomenMuhammad01 could you create a simple repo reproducing this issue so I can work on it?

**Comment by gilang-sera** [comment]
me too. i have this problem too. especially when i'm using CustomRoute. any solution for this issue?

**Comment by MomenMuhammad01** [comment]
Hey @Milad-Akarie i tried to make a simple repo to reproduce this but surprisingly it didn't have the same issue, so i will keep investigating the issue farther

**Comment by Milad-Akarie** [comment]
@MomenMuhammad01 I can help you debug this if you send me a stripped version of your actual App

**Comment by MomenMuhammad01** [comment]
After debugging it turns out that there was a mistake made by one of my fellow developers in the project which was causing this issue, it's now fixed and it has nothing to do with the package.

Thank you @Milad-Akarie  for trying to help out and for your great effort to provide us such an amazing package.

**Comment by xVemu** [comment]
@MomenMuhammad01 how did you manage to fix this? I have the same problem
