### ISSUE TITLE
Can EmptyShellRoute be const?

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/auto_route_library#2016]
Current:

```dart 
final BooksTab = EmptyShellRoute('BooksTab');
   context.push(BooksTab());
```

Could this be changed to:

```dart 
const BooksTab = EmptyShellRoute('BooksTab');
   context.push(BooksTab());
```

by making `EmptyShellRoute` constructor const or is it not const for a reason ?

**Comment by Milad-Akarie** [comment]
@jtdLab at first I couldn't but then I used my full dart knowledge to make it work lol, it's const in 9.0.1

**Comment by jtdLab** [comment]
Thanks :)
