### ISSUE TITLE
Is there no pushReplacement alternative?

### ISSUE THREAD

**Issue by NamanShergill** [Milad-Akarie/auto_route_library#202]
Is there anyway to achieve this through the plugin? I seem to be unable to find it.

**Comment by Milad-Akarie** [comment]
Just "replace"

**Comment by NamanShergill** [comment]
Thank you! Sorry for creating an issue for this, I was having a lot of trouble.

**Comment by adrianjagielak** [comment]
`replace` and `pushReplacement` are not the same.

If im correct the methods in auto_route closely resembles those in native Flutter Navigator so [`replace`](https://api.flutter.dev/flutter/widgets/NavigatorState/replace.html) ("_Replaces a route on the navigator with a new route._") is not the same as [`pushReplacement`](https://api.flutter.dev/flutter/widgets/NavigatorState/pueplacement.html) ("_Replace the current route of the navigator by pushing the given route and then disposing the previous route once the new route has finished animating in._") ergo the issue should be reopened.
