### ISSUE TITLE
Guards still not working on NestedRoutes?

### ISSUE THREAD

**Issue by waadsulaiman** [Milad-Akarie/auto_route_library#2021]
Hi @Milad-Akarie, thank you very much for this wonderful package. There is only one small issue that many of us have been facing for a long time. There does not seem to be an easy way to guard nested routes. Do you have an example of an alternative approach? Meanwhile, this issue is a properly solved?

Sincerely,
Waad Sulaiman

**Comment by Milad-Akarie** [comment]
Hey @waadsulaiman  If you mean tab-routes, they're still not supported, implementing tab-guards is not a straightforward process, there are a lot of use-cases to cover, I'll try to make them my next priority
