### ISSUE TITLE
Proposal: Web package regression in 9.2.0 back to web: ^1.0.0

### ISSUE THREAD

**Issue by l1qu1d** [Milad-Akarie/auto_route_library#2026]
The **major release** of `AutoRoute 9.0.0`, I believe, shouldn't regress to `web ^0.5.1` as it's already a *major breaking release*.

We only had one package that was affected that needed to be upgraded to be able to migrate to `AutoRoute 9.0.0`. I made the PR to the package and has been merged with `web: ^1.0.0`, https://github.com/Baseflow/flutter-geolocator/pull/1547. In fact, `GeoLocator` already has another major release on top of the PR. 

**Dart 3.5** has also been released and says, "*We’d like to encourage all web package authors to [migrate to package:web](https://dart.dev/interop/js-interop/package-web).*" and has replaced the older `dart:html`. Those migrating from `dart:html` will likely go direclty to `web: ^1.0.0` as well.

For packages that are making the migration to `web: ^1.0.0`, it's going to *desync* `AutoRoute ^9.0.0`. A couple of solutions that might be better than the regression.

1. Keep the `web` package `^1.0.0` and revert the `AutoRoute 9.2.0` release. As I've said before, the `9.0.0` release is a major breaking change and users are already impacted.
2. OR Handle both cases for `web: ^0.5.1` and `web: ^1.0.0` by constraining it to `web: >=0.5.1 <2.0.0` --with appropriate code to handle the different versions.

---------------

AutoRoute Release: 9.2.0:
FIX: revert web package back to version ^0.5.1 because it's pinned in a lot of other packages. 

Commits:
https://github.com/Milad-Akarie/auto_route_library/commit/961283c09d4e23f00ead5e34005bc960f4b0ac5f
https://github.com/Milad-Akarie/auto_route_library/commit/9be4dcd6edaae4dd36ff474090eb91b2977219e7
https://github.com/Milad-Akarie/auto_route_library/commit/9405d321c45924a33000558b746ace3f4185866c

**Comment by l1qu1d** [comment]
@Milad-Akarie More and more mainstream packages either have already or are in the process of migrating to `web: ^1.0.0` and should be addressed sooner than later. Most of Firebase's web versions even have PR's ready to go to migrate.

**Comment by Milad-Akarie** [comment]
done
