### ISSUE TITLE
How to pass animation values to page 

### ISSUE THREAD

**Issue by furins** [Milad-Akarie/auto_route_library#204]
I have some difficulties to understand how to pass an animation value to a page, in order to custom animate some widgets during transition.

Let suppose we have a custom route... 

    // This is the routes list
    @MaterialAutoRouter(routes: <AutoRoute>[
      CustomRoute(page: Step1),
    ])

for a particular page:

    // this is the page containing a widget I'd like to animate during transition
    class Step1 extends StatelessWidget {
        final Animation<double> transitionAnimation;

        const Step1({
            Key key,
            this.transitionAnimation,
        }) : super(key: key);

        @override
        Widget build(BuildContext context) {
            return AnimatedBuilder(
                animation: transitionAnimation,
                builder: (context, child) {
                    return SlideTransition(position: Tween<Offset>(begin: Offset(1, 0), end: Offset(0, 0))).animate(transitionAnimation); // just an example
                }
            );
        }
    }

Your library generates the following code:

    InvoiceContestStep1: (data) {
        return PageRouteBuilder<dynamic>(
            pageBuilder: (context, animation, secondaryAnimation) =>
                Step1(),
            settings: data,
        );
    }

whereas I'd like something like this:

    InvoiceContestStep1: (data) {
        return PageRouteBuilder<dynamic>(
            pageBuilder: (context, animation, secondaryAnimation) =>
                Step1(animation),  // <-- animation is passed to the page
            settings: data,
        );
    }

Is there a way to pass animation to the page, like trough a custom PageBuilder? 

 (libraries versions in use: `auto_route: ^0.6.7, auto_route_generator: ^0.6.7, build_runner: ^1.8.0`)

thanks in advance!

**Comment by theweiweiway** [comment]
closing due to
- auto_route 1.0.x has a way to specify fine grain details for animations via `transitionsBuilders` field
