### ISSUE TITLE
NoSuchMethodError: The getter 'name' was called on null.

### ISSUE THREAD

**Issue by himanshu64** [Milad-Akarie/auto_route_library#205]
this is the example I tried can somebody help me to sort it out
`class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }
}

class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }
}

@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: HomeScreen, initial: true),
    MaterialRoute(page: LoginScreen, fullscreenDialog: true),
  ],
)
class $Router {}

[INFO] Generating build script...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _findBuilderApplications.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:63:24)
#2      _CustomHashMap.[]= (dart:collection-patch/collection_patch.dart:281:31)
#3      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:49:12)    
#4      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)    
#5      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)    
#6      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)    
#7      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:76:50)
#8      _findBuilderApplications (package:build_runner/src/build_script_generate/build_script_generate.dart:59:27) 
<asynchronous suspension>
#9      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:28:26)     
#10     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
#11     generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:25:5)       
#12     generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:49:31)
<asynchronous suspension>
#13     main (file:///C:/Users/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:87:30)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255

flutter doctor -v
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (3 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK
    • Platform android-29, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at 
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by DazzaH0** [comment]
Take a look at this
https://github.com/Milad-Akarie/auto_route_library/issues/200#issuecomment-670344315
