### ISSUE TITLE
Resolver.next() must be called once

### ISSUE THREAD

**Issue by alisabry22** [Milad-Akarie/auto_route_library#2051]
i have an issue on my app with AuthGaurd with Bloc state management i don't know how to overcome.
issue is very simple but i don't know how to solve it.

Scenario:
1)login to the app so the authguard works perfectly and resolver.next(true) is working.
2)logout from the app, the resolver.redirect() will work and redirects the users to login page.
3)user tries to login again and the problem happens .

**Error:**  Failed assertion: line 182 pos 12: '!isResolved': Make sure `resolver.next()` is only called once.) 

how can i overcome this situation how i can let the users to login and logout and login again seamlessly without any issue.

This my AuthGuard code 👍 
`class AuthGaurd extends AutoRouteGuard {
  final AuthBloc authBloc;
  AuthGaurd({required this.authBloc});
  
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    authBloc.stream.listen((state) {
      logger.d("authBloc.stream $state");
      if (state is AuthenticationSuccess) {
     
          resolver.next(true);
      
      } else if (state is AuthenticationFailure) {
        logger.d("failed to login");
        
        resolver.redirect(const AuthRouterRoute());
      }
    });
  }
}`
and this build method inside MyApp Widget which is the first widget inside runApp(MyApp) 
`
  Widget build(BuildContext context) {
 
    final appRouter = getIt<AppRouter>();
    return BlocBuilder<ThemeCubit, ThemeState>(
      buildWhen: (previous, current) => previous != current,
      builder: (context, themeState) {
        return ScreenUtilInit(
          designSize: const Size(430, 970),
          minTextAdapt: true,
          splitScreenMode: true,
          builder: (context, child) {
            return BlocBuilder<LanguageCubit, LanguageState>(
              builder: (context, state) {
                return MaterialApp.router(
                  localizationsDelegates:
                      AppLocalizations.localizationsDelegates,
                  supportedLocales: AppLocalizations.supportedLocales,
                  locale: Locale(state.lang),
                  debugShowCheckedModeBanner: false,
                  routerConfig: appRouter.config(
                    reevaluateListenable:ReevaluateListenable.stream(context.watch<AuthBloc>().stream),
                  ),
                  theme: themeState is ThemeDark
                      ? AppTheme.darkTheme
                      : AppTheme.lightTheme,
                );
              },
            );
          },
        );
      },
    );
  }`

**Comment by alisabry22** [comment]
solved it.

**Comment by fikretsengul** [comment]
Can you share the solution with an example code?

**Comment by EArminjon** [comment]
Up, how did you solve that ?
