### ISSUE TITLE
The app unfortunately closes on Android when using Predictive Back or the hardware back button

### ISSUE THREAD

**Issue by Jasco07122021** [Milad-Akarie/auto_route_library#2059]
The app unfortunately closes on Android when using Predictive Back or the hardware back button
- Flutter 3.24.2 
- auto_route 9.2.2

I have 5 tabs and I use AutoTabsScaffold to manage them. Whenever I tap on the second or other tab, the hardware back button takes me back to the first tab. But, after pressing the back button, the app exits. Need fix!

This issue started after I upgraded my Flutter version to 3.24

**Comment by cdobrovolny** [comment]
having the same issue.

**Comment by AlexDochioiu** [comment]
Same issue here

**Comment by cdobrovolny** [comment]
a valid workaround is to downgrade the Flutter-Sdk to 3.22.0

**Comment by xVemu** [comment]
Current workaround is to change from `frameworkHandlesBack` to `true` in local flutter's source code here
https://github.com/flutter/flutter/blob/0167f02e90c14ea5f476398d2fe7f1d3bbaedd8e/packages/flutter/lib/src/services/system_navigator.dart#L41

**Comment by ddfreiling** [comment]
Seems related to https://github.com/flutter/flutter/issues/156517

**Comment by GregUAs** [comment]
With Flutter 3.24.3, all versions above 8.1.3 are defective for the back gesture in Android.

**Comment by TiesPol** [comment]
Same issue here, only when using FlutterFragmentActivity

**Comment by GregUAs** [comment]
Should I go through something else? @TiesPol

**Comment by LiamMarega** [comment]
Any solution?

**Comment by AlexDochioiu** [comment]
> Any solution?

This one seems to work:
https://github.com/Milad-Akarie/auto_route_library/issues/2059#issuecomment-2434908775

**Comment by LiamMarega** [comment]
I have another problem with this...
Now i have a endDrawer in my app like this:

 return AutoTabsScaffold(
      key: const Key('home_page_router_key'),
      animationCurve: Curves.ease,
      animationDuration: const Duration(milliseconds: 150),
      lazyLoad: true,
      primary: true,
      homeIndex: 1,
      routes: const [
        NewsHomeRoute(),
        FeedDiscoverHomeRoute(),
        GamificationRankingRoute(),
        ProfileRoute(),
      ],
      endDrawer: FeroxLoggedProfileDrawer(),
      endDrawerEnableOpenDragGesture: draggableEndDrawer,
      
      
      But when i use Android back button this 
      
      The drawer does not close until it reaches the initial route, regardless of whether it was opened on another route.

**Comment by xVemu** [comment]
Why closed?

**Comment by GregUAs** [comment]
> > Any solution?
> 
> This one seems to work: [#2059 (comment)](https://github.com/Milad-Akarie/auto_route_library/issues/2059#issuecomment-2434908775)

It's not a good practice to manage manually all states of lifecycle. It's work but not recommended at all.
Take care when you will update your project or dependencies.

**Comment by AlexDochioiu** [comment]
> > > Any solution?
> > 
> > 
> > This one seems to work: [#2059 (comment)](https://github.com/Milad-Akarie/auto_route_library/issues/2059#issuecomment-2434908775)
> 
> It's not a good practice to manage manually all states of lifecycle. It's work but not recommended at all. Take care when you will update your project or dependencies.

There's no management of states though, just an action performed on given lifecycle notifications (in this case to override the buggy "preferred" back button handling). While overriding the back button handling delegation may not be great, it's much better than having a buggy app navigation.

P.s. by all means, when the flutter team adds predictive back support for FlutterFragmentActivity, this workaround should be removed.

**Comment by mse-JoNa** [comment]
> > Any solution?
> 
> This one seems to work: [#2059 (comment)](https://github.com/Milad-Akarie/auto_route_library/issues/2059#issuecomment-2434908775)

In flutter 3.24.0 FlutterFragment removed override onBackPressed method in below comment. Use onBackPressedCallback instead. But onBackPressedCallback wasn't register by default.
 (https://github.com/flutter/engine/pull/52302)
If you want  navigator to handle the back key for example using PopScope ,need make sure onBackPressedCallback was enabled with calling setFrameworkHandlesBack true , usually navigator class do the work automatically in setFrameworkHandlesBack(notification.canHandlePop),  we dont need to handle canHandlePop, but in some case, for example, after showModal/dialog (useRootNavigator= true) ,then  navigator not work as expect, the canHandlePop can be false when it need to be true, I am not sure if it is go_router or navigator' bug.   
Problems begins from 3.24.0 ,just because override onBackPressed method is removed and also onBackPressedCallback is not working.
