### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'push' was called on null

### ISSUE THREAD

**Issue by mester9000** [Milad-Akarie/auto_route_library#206]
I updated my auto_route version to 0.6.7 so I had to make the builder changes around MaterialApp.
After the changes when I try to navigate somewhere I get this error: Unhandled Exception: NoSuchMethodError: The method 'push' was called on null
If I try to stick with older versions of auto route it still requires builder on ExtendedNavigator. I do not understand why.

**Comment by Infucio** [comment]
Can you provide your material app code.
