### ISSUE TITLE
How do I pass the context of a certain ExtendedNavigator to a widget to be displayed across the entire app?

### ISSUE THREAD

**Issue by NamanShergill** [Milad-Akarie/auto_route_library#207]
In a previous version of this plugin I was able to show error/success popups by passing ```Router.navigatorKey.currentState.overlay.context``` to the widgets. But if I try passing ```ExtendedNavigator.named(<My Navigator's name>).context``` or ```ExtendedNavigator.root.context```, it throws ``` Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.``` whenever that widget is to be displayed. Is there any way to pass the context? As I am using streams to display the pop ups and I already need to pass a String to them, can't pass context alongwith it.

**Comment by NamanShergill** [comment]
Never mind, I just had to use a NavigatorKey to get the context.

**Comment by mirkancal** [comment]
@NamanShergill how did you give the navigatorKey to MaterialApp.router widget?
