### ISSUE TITLE
Guards seem to be ignored (using stacked arch)

### ISSUE THREAD

**Issue by FickleLife** [Milad-Akarie/auto_route_library#209]
I am attempting to use the latest version of `auto_route: ^0.6.7` with [`stacked_services`](https://github.com/FilledStacks/stacked/tree/master/packages/stacked_services) and its nav library.

The issue I have is guards are ignored - the code for the guard is not fired. The stacked_services nav library basically uses `Get` under the hood. 

main.dart:
```
return MaterialApp(
      builder: ExtendedNavigator.builder<Router>(
        router: Router(),
        observers: [FirebaseAnalyticsObserver(analytics: FirebaseAnalytics())],
        guards: [AuthGuard()],
        navigatorKey: locator<NavigationService>().navigatorKey,
        builder: (context, extendedNav) => Theme(
          data: _themeChooserService.dark,
          child: extendedNav,
        ),
      ),
    );
```
`locator<NavigationService>().navigatorKey` encapsulates 

```
get navigatorKey {
    return Get.key;
  }
```
which in itself returns: 
```
GlobalKey<NavigatorState> key = GlobalKey<NavigatorState>();
```

router.dart:
```
    MaterialRoute(page: ProductAddEditForm, guards: [AuthGuard], name: "productAddEditFormRoute"),
```

router.gr.dart:
```
...
RouteDef(Routes.productAddEditFormRoute,
        page: ProductAddEditForm, guards: [AuthGuard]),
...

```

route_guards.dart:
```
class AuthGuard extends RouteGuard {
  final AuthenticationService _authenticationService = locator<AuthenticationService>();
  final NavigationService _navigationService = locator<NavigationService>();

  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName, Object arguments) async {
    print('running guards');
    final signedIn = await _authenticationService.checkSignIn();
    if (signedIn) {
      return true;
    }

    _navigationService.replaceWith(Routes.loginViewRoute);
    return true;
  }
}

```

code to nav to the route: 
```
await _navigationService.navigateTo(Routes.productAddEditFormRoute);
```

This navigates successfully but, without firing any code in `route_guards.dart` for routes that are marked with the guard.  `_navigationService.navigateTo` simply wraps a Get call: 
```
Future<dynamic> navigateTo(String routeName, {dynamic arguments, int id}) {
    return Get.toNamed(routeName, arguments: arguments, id: id);
  }
```

Any ideas where I am going wrong here?

<details>
<summary>
FLutter doctor:
</summary>
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Applications/flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alexblack/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 5360F0EC-F786-4B67-8ADC-E5A9F2702329 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

</details>

**Comment by Milad-Akarie** [comment]
Guards logic is inside the ExtendedNavigator which is a wrapper for the native navigator, so you using the native navigator directly won't run the guards logic.

**Comment by FickleLife** [comment]
Thanks, I have moved to ExtendedNavigator
