### ISSUE TITLE
Waiting for too long while generating the auto router

### ISSUE THREAD

**Issue by shreyash-jain** [Milad-Akarie/auto_route_library#210]
[INFO] 17.2s elapsed, 1/17 actions completed.
[INFO] 18.3s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - auto_route_generator:autoRouteGenerator on lib/core/authentication/bloc/authentication_bloc.dart

This is an unending task, waited for half an hour

**Comment by felixagbavor** [comment]
This is an issue with the new flutter upgrade. Having the same problems as well.

**Comment by yingwei1025** [comment]
having this issues with the flutter version 1.20.1, waiting for 1 hour

**Comment by ConnorMcGill** [comment]
I'm not sure if this is helpful but I was having the same issue until I ran flutter clean, updated the package versions to latest and then ran the command again to generate the routes.  It seemed to complete in ~20 seconds this time around.

This is my flutter doctor output"

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F96, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.3)
[!] Connected device

**Comment by shreyash-jain** [comment]
I think I found what the actual issue was

--_Analyzer 0.39.15 seems to break build_runner_

**Solution :**
For anyone searching here, you can set the override for now inside your pubspec.yaml:

```
dependency_overrides:
  analyzer: '0.39.14'
```

Additionally, I had to clear all of the caches:

flutter clean
flutter pub cache repair
flutter pub run build_runner clean
