### ISSUE TITLE
ability to inject params through both ArgumentHolder class and also through query params

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#214]
@Milad-Akarie 
Its a common use case to have deeplinks in applications where we may need to open a particular screen using a deeplink.

Right now , the library only allows to use either argument holder class or through a QueryParam or PathParam paramter. 

But there should be a way to support both of them. 
+ ArgumentHolder class will be used to open screens through the native navigator or extended navigator.
+ query params sent through something like a deeplink will still be able to inject all the parameters the screen or would be able to add data to a argument holder class directly.

**Comment by Milad-Akarie** [comment]
Hey @nateshmbhat, elaborate using some code?

**Comment by nateshmbhat** [comment]
Sure give me 10 mins

**Comment by nateshmbhat** [comment]
One way to push screen, this will be used by users who push the screen directly instead of parsing something like a deeplink :

NavigationService.pushNamed( 'path' , arguments : ArgumentHolder( name : 'name' , age : 'age' )




Another way to open a screen should be through query params :


NavigationService.openDeeplink("path?name=milad&age=25")

So this would internally make sure that the query parameter map would be mapped to the corresponding argument holder object and would pass the argument holder object normally to the screen.

**Comment by nateshmbhat** [comment]
Right now, both the options of pushing the screen is not possible. Since using the query param means that the argument holder class is not created.

**Comment by nateshmbhat** [comment]
@Milad-Akarie any updates on this ?

**Comment by KieranLafferty** [comment]
@nateshmbhat  curious if you found a workaround here. Also @Milad-Akarie  an update to this would be greatly appreciated!

**Comment by theweiweiway** [comment]
Is this still an issue in AutoRoute 2.x? I think this should work now - please double check and close if that's the case

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
