### ISSUE TITLE
Stuck on generating the auto router

### ISSUE THREAD

**Issue by thienhaole92** [Milad-Akarie/auto_route_library#215]
When I run the command to generating route it takes too long
[INFO] 42.7s elapsed, 1/17 actions completed.
[INFO] 43.8s elapsed, 1/17 actions completed.
[INFO] 44.9s elapsed, 1/17 actions completed.

**Comment by alvinvin00** [comment]
for now, we must add 
```dart
dependency_overrides:
  analyzer: '0.39.14'
```
into pubspec.yaml

Source : https://stackoverflow.com/questions/63428704/not-able-to-generate-the-mobx-using-build-runner-in-flutter

**Comment by Milad-Akarie** [comment]
This should be fixed in the new releases.
