### ISSUE TITLE
Allow underscore or camelCaes in dynamic route path parameter

### ISSUE THREAD

**Issue by azihsoyn** [Milad-Akarie/auto_route_library#216]
Hi, this was the router I am looking for!.

In the current implementation, if set `/users/:user_id` or `/users/:userID` to a path, generated code treat it `userid`.
I want you to keep original variable names.

Thanks.

**Comment by theweiweiway** [comment]
actually, i was wondering about this too since I need underscores_ in my path parameter

 @Milad-Akarie , is this easy to do?
