### ISSUE TITLE
Error shown after updating Flutter

### ISSUE THREAD

**Issue by shakirkasmani** [Milad-Akarie/auto_route_library#219]
error 1 : Couldn't infer type parameter 'T'.

Tried to infer 'dynamic' for 'T' which doesn't work:
  Type parameter 'T' declared to extend 'RouterBase'.
The type 'dynamic' was inferred from:
  Parameter 'router' declared as     'T'
                     but argument is 'dynamic'.

Consider passing explicit type argument(s) to the generic.

error 2: 'dynamic' doesn't extend 'RouterBase'.
Try using a type that is or is a subclass of 'RouterBase'.

error 3: 'Router' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Router'.

error 4: The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:heed/presentation/routes/router.gr.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

`MaterialApp(
        title: 'Notes',
        debugShowCheckedModeBanner: false,
        theme: ThemeData.light().copyWith(
          primaryColor: const Color(0xFF013300),
          accentColor: Colors.amberAccent.shade200,
          floatingActionButtonTheme: FloatingActionButtonThemeData(
              backgroundColor: Colors.blue.shade900),
          inputDecorationTheme: InputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8), ), ),),
        builder: ExtendedNavigator(router: Router()),
      )`

router.dart
`@MaterialAutoRouter(
  generateNavigationHelperExtension: true,
  routes: <AutoRoute>[
    MaterialRoute(page: SplashPage, initial: true),
    MaterialRoute(page: SignInPage),
    MaterialRoute(page: NotesOverviewPage),
    MaterialRoute(page: NoteFormPage, fullscreenDialog: true),
  ],
)
class $Router {}`

router.gr.dart
`class Routes {
  static const String splashPage = '/';
  static const String signInPage = '/sign-in-page';
  static const String notesOverviewPage = '/notes-overview-page';
  static const String noteFormPage = '/note-form-page';
  static const all = <String>{
    splashPage,
    signInPage,
    notesOverviewPage,
    noteFormPage,
  };
}
class Router extends RouterBase {
  @override
  List<RouteDef> get routes => _routes;
  final _routes = <RouteDef>[
    RouteDef(Routes.splashPage, page: SplashPage),
    RouteDef(Routes.signInPage, page: SignInPage),
    RouteDef(Routes.notesOverviewPage, page: NotesOverviewPage),
    RouteDef(Routes.noteFormPage, page: NoteFormPage),
  ];
  @override
  Map<Type, AutoRouteFactory> get pagesMap => _pagesMap;
  final _pagesMap = <Type, AutoRouteFactory>{
    SplashPage: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => SplashPage(),
        settings: data,
      );
    },
    SignInPage: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => SignInPage(),
        settings: data,
      );
    },
    NotesOverviewPage: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => NotesOverviewPage(),
        settings: data,
      );
    },
    NoteFormPage: (data) {
      final args = data.getArgs<NoteFormPageArguments>(nullOk: false);
      return MaterialPageRoute<dynamic>(
        builder: (context) => NoteFormPage(
          key: args.key,
          editNote: args.editNote,
        ),
        settings: data,
        fullscreenDialog: true,
      );
    },
  };
}
/// ************************************************************************
/// Navigation helper methods extension
/// *************************************************************************

extension RouterExtendedNavigatorStateX on ExtendedNavigatorState {
  Future<dynamic> pushSplashPage() => push<dynamic>(Routes.splashPage);

  Future<dynamic> pushSignInPage() => push<dynamic>(Routes.signInPage);

  Future<dynamic> pushNotesOverviewPage() =>
      push<dynamic>(Routes.notesOverviewPage);

  Future<dynamic> pushNoteFormPage({
    Key key,
    @required Note editNote,
  }) =>
      push<dynamic>(
        Routes.noteFormPage,
        arguments: NoteFormPageArguments(key: key, editNote: editNote),
      );
}
/// ************************************************************************
/// Arguments holder classes
/// *************************************************************************

/// NoteFormPage arguments holder class
class NoteFormPageArguments {
  final Key key;
  final Note editNote;
  NoteFormPageArguments({this.key, @required this.editNote});
}`

**Comment by Janaka-Steph** [comment]
Using:
```
auto_route: ^0.6.7  
auto_route_generator: ^0.6.8  
```

Hello,

I am facing the same errors on this call `builder: ExtendedNavigator.builder<Router>(router: Router()),`

```
'dynamic' doesn't extend 'RouterBase'.
Try using a type that is or is a subclass of 'RouterBase'.
```

```
The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:x/presentation/routes/router.gr.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

```
'Router' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Router'.
```

Any ideas? Thank you for your help!

**Comment by bounty1342** [comment]
You can also rename your routeur in the router.dart class. 'class $AutoRouter {}' for exemple.
This would avoid other conflict.

**Comment by theweiweiway** [comment]
Closing issue due to:
- possible solution
- stale issue

**Comment by shakirkasmani** [comment]
I used import 'package:flutter/material.dart' hide Router;

 solved
