### ISSUE TITLE
一个问题：多次重复构建时，会存在问题吗？

### ISSUE THREAD

**Issue by dudumuta** [Milad-Akarie/auto_route_library#222]
1.标准注解后执行build，生成输出文件；
2.修改之前标注的注解，然后再次执行build；
3.这时会生成正确的路由文件么？
4.多次执行会有输入的文件只是有改动的文件问题，build过程是个增量的过程。

**Comment by theweiweiway** [comment]
Sorry, could you post this question in English? Thanks
