### ISSUE TITLE
Replacement of ExtendedNavigator.root.overlay.context

### ISSUE THREAD

**Issue by cruzelx** [Milad-Akarie/auto_route_library#224]
What is the alternative to **ExtendedNavigator.root.overlay.context** in the new version?

**Comment by SashaFarkas** [comment]
Is there any solution to this?

**Comment by Milad-Akarie** [comment]
@SashaFarkas if you're trying to access the context you can use` appRouter.navigatorKey.currentContext`.

**Comment by SashaFarkas** [comment]
@Milad Akarie <milad.akarie@gmail.com> How to acces navigator key in
auto_route 0.6.9? I mean GlobalKey<ExtendedNavigatorState>, not
GlobalKey<NavigatorState>

**Comment by theweiweiway** [comment]
what I did in 0.69 was:

```
final navKeys = <ENav, GlobalKey<ExtendedNavigatorState>>{
  ENav.auth: GlobalKey<ExtendedNavigatorState>(),     
};

...
          key: navKeys[ENav.search], // to access.   
```

**Comment by theweiweiway** [comment]
closing due to stale issue
