### ISSUE TITLE
how to add a NavigatorObserver to the setting of the route

### ISSUE THREAD

**Issue by bero93** [Milad-Akarie/auto_route_library#226]
before this package i was adding an observer to some route to control the orientation of the route by a NavigatorObserver:

  case GeneralRouting.MainWizardViewRouteName:
          return MaterialPageRoute(
              settings: RouteSettings(
                  arguments:  ScreenOrientation.portraitOnly
                 ),
            builder: (context)=> MainWizardView(
                userProfile: args,
              ));

can u please give me a way to integrate this functionality with your package

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
