### ISSUE TITLE
[web] Url bar not updating in newest Flutter SDK Beta (1.21.0-9.1.pre)

### ISSUE THREAD

**Issue by dannnnthemannnn** [Milad-Akarie/auto_route_library#229]
Upgrading flutter to this version and auto route is no longer updating the url bar when you navigate to routes.

**Comment by dannnnthemannnn** [comment]
Still not updating in the newest flutter beta

**Comment by orrios** [comment]
This is fixed #225

**Comment by Milad-Akarie** [comment]
This should be fixed in 

```yaml
auto_route: 0.6.9
auto_route_generator: 0.6.9
```
