### ISSUE TITLE
Make generated class linter-compatible

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/auto_route_library#23]
Hi! I'm using the linting rules specified by Flutter themselves in their [repository](https://github.com/flutter/flutter/blob/master/analysis_options.yaml) and every time I go to debug my app, I have to click "Debug Anyways" because the generated router file throws an error. I ignored the file in my `analysis_options.yaml` file but the Dart linter currently has a bug where when you open ignored files, the errors and/or warnings stay. The error I'm getting is when you define a route (`MaterialPageRoute`, `PageRoute`, `CupertinoPageRoute`), it doesn't have a type argument such as `MaterialPageRoute<dynamic>`.

There's other things like not defining type annotations for the route strings (couldn't you just make them all of type `String`?) and the variable `args` not being used at the top of `onGenerateRoute()` but it doesn't bother me as much as the red errors. It would be great if you could just define the `PageRoute`s type arguments to `dynamic`.

**Comment by Milad-Akarie** [comment]
@Reprevise PageRoute return types are gonna be in the next build.
so you're gonna be able to do something like
@MaterialRoute(returnType: String)
and default it to dynamic

Thanks for reporting.

**Comment by Milad-Akarie** [comment]
@Reprevise  You can now specify route return type in
` @MaterialRoute(returnType:String)`
and it defaults to dynamic if you don't pass anything so the linter is happy.
check out v0.3.0
