### ISSUE TITLE
Elaborate example/ document for all the features

### ISSUE THREAD

**Issue by sanni-aubergine** [Milad-Akarie/auto_route_library#231]
Can we have an elaborate example for using auto_route.
Are there any elaborate articles or videos or oss projects which take advantage and show us how one can make most out of this package.

Thanks for building auto_route.

**Comment by gat786** [comment]
Can we build something around this?

**Comment by theweiweiway** [comment]
I spoke with Milad, more comprehensive documentation will be coming soon
