### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by rahulnakre** [Milad-Akarie/auto_route_library#232]
Hey, I have a route defined with a path parameter like so:
```dart
MaterialRoute(
  page: StudyScreen,
  name: "studyScreen",
  path: "/study-screen/:studyId?"
),
```

But when I navigate to this route without any parameters, I get this:
![image](https://user-images.githubusercontent.com/28615350/92138011-dc6d6900-eddb-11ea-8561-bc0fdbbb51df.png)

Edit: If I explicitly set the argument to ```null```, it seems to work:
```dart
ExtendedNavigator.of(context).push(
  SearchRoutes.studyScreen(studyId: null),
);
```

**Comment by Milad-Akarie** [comment]
I don't know, I can't reproduce this.

**Comment by theweiweiway** [comment]
Closing issue due to:
- unproducible
- AutoRoute 1.x has dynamic path support
- stale issue
