### ISSUE TITLE
I can't seem to find the nested router

### ISSUE THREAD

**Issue by beomjo** [Milad-Akarie/auto_route_library#234]
Hello Milad!
It seems that the following error occurs because the overlapping router is not found.
```
Unhandled Exception: NoSuchMethodError: The method 'push' was called on null
```

I have a nested router named nestedRouterName in the root

```
ExtendedNavigator.named(nestedRouterName).push(
      path,
      arguments: arguments,
    );
```

`ExtendedNavigator.named(nestedRouterName)` is null

Thank you for always quick support.
Thanks Millard

**Comment by Milad-Akarie** [comment]
@qjatjr1108  did you provide the name to the Nested ExtendedNavigator?

**Comment by BeomJobs** [comment]
@Milad-Akarie 
of course.
I have a name as a static constant, and I am serving it

**Comment by Milad-Akarie** [comment]
@BeomJobs ok where are you pushing from? outside the nested nav?

**Comment by matthewfx** [comment]
I've had the same problem and found a solution to it. The documentation mentions that: "if you don't provide a name the navigator will be named after it's router class's type name". And indeed if you don't provide it and then look for its router class type name it works.

**Comment by gwennguihal** [comment]
Hi @Milad-Akarie,

I'have a similary bug.
I have 4 nested routers in a bottomNavigationBar, they are named:
```
ExtendedNavigator(
              name: model.navigatorName,
              router: AppRouter(),
              observers: [
                widget._service.createRouteObserver(),
                //...model.observers,
              ],
              initialRoute: model.initialRoute,
              initialRouteArgs: model.initialRouteArgs,
            )
````

When I quit the app on android (via the back button) and restart it, I got the same error if I use `ExtendedNavigator.named('name')` (returns null) but it's ok if I use `ExtendedNavigator.of(context)`. 

`_NavigatorsContainer_routers` only contains the root navigator, but not nested routers.

**Comment by theweiweiway** [comment]
Closing issue due to:
- possible solution
- stale issue
