### ISSUE TITLE
Can't generate auto route after update to flutter 1.20

### ISSUE THREAD

**Issue by YasserOJ** [Milad-Akarie/auto_route_library#235]
Recently with flutter 1.17 I was able to build the genrated classes with the build runner command; But after the update to 1.20 
I couldn't build my auto route using the command "flutter pub run build_runner build --delete-conflicting-outputs"

![Screenshot 2020-09-08 at 09 15 05](https://user-images.githubusercontent.com/26030291/92450847-d698ce80-f1b3-11ea-8de2-807dcf277b85.png)

and the same problem keep repeating as in the screenshot taken

**Comment by dharmesh099** [comment]
I have faced the same issue
![image](https://user-images.githubusercontent.com/19344961/92466817-4fb51780-f1ee-11ea-9513-1a008804664d.png)

**Comment by trauts2** [comment]
Any updates here?  I see the same with 1.22.

**Comment by SNPBharadwaj** [comment]
i guess the package needs an update to support analyzer's new update

**Comment by Milad-Akarie** [comment]
This should be fixed in 

```yaml
auto_route: 0.6.9
auto_route_generator: 0.6.9
```
