### ISSUE TITLE
Hot Reload causes the app to go back to its initial view instead of refreshing the state of the page I'm on.

### ISSUE THREAD

**Issue by jdaev** [Milad-Akarie/auto_route_library#237]
ExtendedNavigator is configured exactly as in the readme.

```
return MaterialApp(
              builder: ExtendedNavigator.builder<Router>(
                router: Router(),
                navigatorKey: locator<NavigationService>().navigatorKey,
                initialRoute: Routes.startUpViewRoute,
                builder: (context, extendedNav) => Theme(
                  data: ThemeData(brightness: Brightness.dark),
                  child: extendedNav,
                ),
              ),
              
            );
          }
```

**Comment by bounty1342** [comment]
@jdaev Most probably linked to your navigatorKey :
https://api.flutter.dev/flutter/material/MaterialApp/navigatorKey.html

If think, removing it, will solve your issue.

**Comment by andrzejchm** [comment]
I don't think that's it @bounty1342 . I have my navigator without the key specified and suffer the same problem

**Comment by jdaev** [comment]
I actually solved this issue. My problem was that I had a future builder as a parent of my material app, which for some reason doesn't work with this. So is suggest moving anything you have above material app to inside it.
