### ISSUE TITLE
How to handle Login Authentication in Flutter Web

### ISSUE THREAD

**Issue by boscux** [Milad-Akarie/auto_route_library#238]
Hello, I'm implementing a Flutter Web app.
I'm having hard time to find a proper solution on how to handle not logged in users in my web app. 

Let's assume I have two screens: Login and ScreenA. 

My aim is that if the user is not logged in, if he types the url of the ScreenA in the browser he is redirected to the login. 
Instead, if the user is already logged in and he types the login url in the browser he is redirected to ScreenA. 

I can define an AuthGuard and GuestGuard in my app, but how to handle the redirect to the other screen? 

Thank you

**Comment by theweiweiway** [comment]
If I'm understanding your question correctly,

To handle the redirection from login to ScreenA, you can push ScreenA as soon as the user gets logged in
