### ISSUE TITLE
Transition curve

### ISSUE THREAD

**Issue by MotiBartov** [Milad-Akarie/auto_route_library#239]
Hi, 

I have a question about transition curve.
Is it possible to set the animation curve of a transition ?

I am using the CustomRoute with transitionBuilder as following:

      `
       CustomRoute(page: CustomerPage, transitionsBuilder: slideRightTransition, durationInMilliseconds: 300 )
 
       Widget slideRightTransition(BuildContext context, Animation<double> animation,
               Animation<double> secondaryAnimation, Widget child) {
                 return new SlideTransition(
                        position: new Tween<Offset>(
                        begin: const Offset(1.0, 0.0),
                        end: Offset.zero,
                        ).animate(animation),
                   child: child,
              );
      }`

How can I modify the animation curve?

Thanks for your support.
Moti.

**Comment by Milad-Akarie** [comment]
Hey Moti, Sorry for the delay. 
Have you tried this? 
```dart
Widget slideRightTransition(BuildContext context, Animation<double> animation,
    Animation<double> secondaryAnimation, Widget child) {
  var curvedAnim = CurvedAnimation(parent: animation, curve: Curves.easeInOut);
  return new SlideTransition(
    position: new Tween<Offset>(
      begin: const Offset(1.0, 0.0),
      end: Offset.zero,
    ).animate(curvedAnim),
    child: child,
  );
}
```

**Comment by MotiBartov** [comment]
Hi Milad, 

Thanks for your answer, 
Well i've tried something very similar, and it worked: 

        
       final customAnimation = CurvedAnimation(curve: Curves.ease, parent: (animation as ProxyAnimation).parent);


I guess your answer is better, ill give it a try.

Take care,
Moti.
