### ISSUE TITLE
Could the generated class not use static members?

### ISSUE THREAD

**Issue by saschaernst** [Milad-Akarie/auto_route_library#24]
Hey Milad,

after enjoying your injectable package, it would be really nice to also use the generated auto_route class with DI (i.e. for mocking, etc.). What about generating a non-static class? If anybody really, really wants the static variant, there is always a possibility of a singleton.

Cheers, Sascha

**Comment by Milad-Akarie** [comment]
Hey @saschaernst  sorry for the delay, I was working on injectable lately.
and Yes that's been on my mind for a while now. I started working on expending the router class and the fact that it's static is becoming a limitation. 

Maybe by default I can generate a singleton version and provide an option to generate a non singleton version for those who wanna manage it's life span using a some injector or something.
how does that sound?

**Comment by saschaernst** [comment]
I would argue that it is easier to create an instantiatable version and  offer a singleton on top

**Comment by Milad-Akarie** [comment]
@saschaernst  Hey again, 
I haven't come up with a complete idea on how that's gonna work yet.
I'm not so good when it comes creating mocks and tests in general, could you show me some code on what you have in mind?

**Comment by saschaernst** [comment]
Just get rid of all the static in the generated class. If somebody needs simple access from everywhere without bothering with dependency injection, there is always the possibility to instantiate a singleton directly in the main file. That way you have high testability, you can mock the routes and you can choose how to use it

**Comment by Milad-Akarie** [comment]
> there is always the possibility to instantiate a singleton directly in the main file.
you mean as a global variable?

**Comment by saschaernst** [comment]
yes, I wouldn't do it, but it is still better than a hardcoded static class

**Comment by Milad-Akarie** [comment]
not a big fan of global vars neither, how about making the router class a singleton?

**Comment by saschaernst** [comment]
Everybody not using it would carry this Router.instance baggage around. And people using it like that limit the testability of their code. It's like handing a gun to a child ;-)

**Comment by Milad-Akarie** [comment]
That's a valid point, I'll see what I can do.

**Comment by saschaernst** [comment]
I'll post my idea later

**Comment by saschaernst** [comment]
This would be my approach:

Pros:
- completely mockable, even the page names

```
class Routes {
  static const _initialPage = '/';
  String get initialPage => _initialPage;

  static const _otherPage = '/other-page';
  String get otherPage => _otherPage;

  GlobalKey<NavigatorState> get navigatorKey => getNavigatorKey<Routes>();
  NavigatorState get navigator => navigatorKey.currentState;

  Route<dynamic> onGenerateRoute(RouteSettings settings) {
    final args = settings.arguments;
    switch (settings.name) {
      case _initialPage:
        return MaterialPageRoute(
          builder: (_) => IntroPage(),
          settings: settings,
        );
      case _otherPage:
        return MaterialPageRoute(
          builder: (_) => OtherPage(),
          settings: settings,
        );
      default:
        return unknownRoutePage(settings.name);
    }
  }
}
```

**Comment by Milad-Akarie** [comment]
Hey @saschaernst  check out v0.4.0 and share your thoughts please. 
Thanks for your efforts.
