### ISSUE TITLE
Scroll to top on page transition

### ISSUE THREAD

**Issue by Janaka-Steph** [Milad-Akarie/auto_route_library#240]
Hello, 

When I navigate to a new page and come back, the screen is at the same scroll position where I left it. I would like to always display a new screen at top position. Do I have to write custom code for scroll to top or I am missing an option or something? Any recommendation what I should use?

Thank you

**Comment by Milad-Akarie** [comment]
@Janaka-Steph are you saying that you don't want to maintain the state of your page?

**Comment by Janaka-Steph** [comment]
Not sure about the "state of the page", simply the scroll position state. It is just weird to scroll a screen, go to an other, and when coming back the scroll position is at where I left. On a website any page you open will always be displayed at scroll position zero.

**Comment by Milad-Akarie** [comment]
@Janaka-Steph well if you don't have any other state to maintain inside of your scrolling page you could try setting maintainState to false

  `MaterialRoute( page: HomeScreen, maintainState: false )`

other than that I guess you could try to use a ScrollController and rest the scroll offset manually.

**Comment by Janaka-Steph** [comment]
I tried playing with ScrollController but without success. I didn't know about `maintainState` property, thanks I can try that. 
I will close the issue, thank you for your help and this great library!
