### ISSUE TITLE
How to add swipe back gesture to custom route?

### ISSUE THREAD

**Issue by DFelten** [Milad-Akarie/auto_route_library#241]
I've defined my own custom route that works too. However, the iOS swipe back gesture is no longer available.

How can I activate this gesture for custom routes with auto_route?

**Comment by Milad-Akarie** [comment]
Hey @DFelten, This is irrelevant to auto_route package but you can check the implementation of the back gesture in CupertinoPageRoute and mimic it.

**Comment by Milad-Akarie** [comment]
closing this as for now custom route builders are not supported by auto_route

**Comment by rmargolinross** [comment]
I still would like this feature for the CustomRoute option or somehow allow the MaterialRoute to allow custom transition builders.

**Comment by vnext-quangnh** [comment]
I switched to using go_router when this feature wasn’t supported 🥱

**Comment by 0x01001** [comment]
I switched to using go_router when this feature wasn’t supported 🥱

**Comment by maxence-futures** [comment]
@0x01001 Transition builders don't allow you to use swipe-back gestures with GoRouter.
