### ISSUE TITLE
Which Custom Route Transition for Hero animation?

### ISSUE THREAD

**Issue by sceee** [Milad-Akarie/auto_route_library#242]
Hi,

I'm trying to add a hero animation to a custom route transition. It does unfortunately not really work, when navigating to the route the hero animation is not shown, only when popping that route, the hero animation works. That's why I'm wondering what transition is the correct to function with hero animations?

**Comment by doppio** [comment]
Does the Hero component exist on the first frame when your route builds? It has to be there on the first frame so Flutter can link between them and start the animation as soon as the route is pushed.

**Comment by sceee** [comment]
@doppio actually, that was it as the component was wrapped in a FutureBuilder in the second screen. Thank you very much for your help!
