### ISSUE TITLE
Unable to assign RouteronGenerateRoute method to onGenerateRoute:

### ISSUE THREAD

**Issue by lazarvgd** [Milad-Akarie/auto_route_library#243]
Hi, I am newbie with this library so please sorry in advance if I am asking stupid question.

I have generated routes for my app, but I am not able to assign Router.onGenerateRoute method to onGenerateRoute: method in MaterialApp. The issue that is present is that I cannot access Routes.initalRoute nor Router().onGenerateRoute method.

Can you please help me to resolve this issue? 
Thanks

**Comment by Milad-Akarie** [comment]
@lazarvgd Sorry for the late response. Did you successfully generate the router file?

**Comment by alexolivier** [comment]
I had this also. I had to alias the import of the `.gr.dart` file due to a conflict

**Comment by akshaybhange** [comment]
> I had this also. I had to alias the import of the `.gr.dart` file due to a conflict
Thanks, @alexolivier, works perfectly. I think this issue can be closed now @Milad-Akarie

Just for beginners :
change your
`import 'package:your/app/path/router.gr.dart'`
to 
`import 'package:your/app/path/router.gr.dart' as myRouter`

and 
`onGenerateRoute: Router(),`
to 
`onGenerateRoute: myRouter.Router(),`
