### ISSUE TITLE
FutureBuilder connection state is "waiting" even when the future is already complete and the snapshot has data already.

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#244]
In my stateful widget , i have a future builder and the result of the future i am saving it in a state variable so that when the rebuild happens, it uses the completed future without doing the computation again.

But the problem here is that, when i am on a screen which has a text field and when the keyboard opens, the whole screen gets rebuilt again (as expected) but the future builder renders one frame with connectionState as "waiting" even when the future is already a resolved future and even when the snapshot already has error.

As mentioned in the docs, there is a limitation in future builder : 

> A side-effect of this is that providing a new but already-completed future to a FutureBuilder will result in a single frame in the ConnectionState.waiting state. This is because there is no way to synchronously determine that a Future has already completed.

The above limitation is causing my whole screen to remount causing it to lose its state, since i have a future builder that returns a loader when the connection state goes to a `waiting` state which "unmounts" the stateful widget and when the `connectionState` goes back to `done` state. the whole stateful widget is remounted.

how do i solve this issue ?

**Comment by theweiweiway** [comment]
closing due to:
- stale issue
- doesn't seem to be related to auto_route
