### ISSUE TITLE
Nested routes and back button behavior

### ISSUE THREAD

**Issue by MotiBartov** [Milad-Akarie/auto_route_library#246]
Hi Milad,

I have a question about working with nested routes and their behaviour when click Android back button.

I have 5 tabs, each tab page is a nested router created like this: 
 ` ExtendedNavigator<HomeNestedRouter>(router: HomeNestedRouter(), name: $HomeNestedRouter.name)` 

All routers works well!

When navigating within the nested routes and click the back button they pops out properly but consider the following pattern:

1. TabA_NestedRoute.initialPage -> push TabA_NestedRoute.someNamedPage 
2. User navigates to other TabB, TabA state remains as it is. 
3. User clicks the back button. 

The system will pop out TabA nested router but the user doesn't see this (so back button has no visual effect), the user then click back button again and this time it will effect (leave the app or other action).

The question is, how can i set the current router priority (as a function of tab selection for instance)?

Thanks for your support,
Moti.

**Comment by Milad-Akarie** [comment]
Hey @MotiBartov, ya this's kind of a big deal, honestly it's hard to manage using the current setup of the Native navigator. Things are looking good with the new Navigator 2.0 though, which I'm hoping I'll be able to switch to real soon.

**Comment by MotiBartov** [comment]
Hi Milad,

Thanks again for your answer, I've thought this one will be tough. 

However, just for knowledge and for others that encounter such issue, i tell how I've managed this, it's not so pretty but it worked.. 

In the TabPageWidget, i've wrapped it with WillPopScope widget to intercept the back button.

When the user taps the back button, I check which tab it is now, and if its not the first tab, I then check if the current tab navigator can pop (which means, user navigated to some route in this nested router), if true, then do pop on that navigator, then also return false for WillPopScope.  If it can't pop (it means that this is the initial route of the router), then set the tab to the previews tab. On the first tab, then it will exit the app.

This makes it to behave much more like Android users expected.

Take care,
Moti.

**Comment by theweiweiway** [comment]
Closing issue due to:
- propsed solution
- stale issue
- AutoRoute 1.x has better support for back button behaviour
