### ISSUE TITLE
Navigate without context

### ISSUE THREAD

**Issue by iconappmaster** [Milad-Akarie/auto_route_library#248]
Is it possible to navigate without context?

I'm trying to navigate from a handle click on a notification and there's no context there.

I tried to use GlobalKey for navigation and the currentContext is returned null.

Thanks

**Comment by moti0375** [comment]
Have you tried to use the `ExtendedNavigator.named("navigatorName").push() ` ?

**Comment by Milad-Akarie** [comment]
yes
https://pub.dev/packages/auto_route#navigation

**Comment by nicks101** [comment]
Is there any similar solution in the `1.0.0-beta.7` version also?

**Comment by jiggum** [comment]
After v1, you can use the root router without context by using that instance of AppRouter(`final appRouter = AppRouter()`) directly.
