### ISSUE TITLE
Wrong import resolution on generated router

### ISSUE THREAD

**Issue by alhafoudh** [Milad-Akarie/auto_route_library#249]
Hi,
I have a moor data class called `ContentType` which is passed as agument to some pages.
auto_route_generator is generating router.gr.dart file with `import 'dart:io';`, not with `import 'package:data/moor_database.dart';` because `dart:io` includes some `ContentType` class for http.

Is there a way to force `auto_route_generator` to do custom import? It fixes for a while when I remove the `import 'dart:io';` and add `import 'package:data/moor_database.dart';` manually to `router.gr.dart` file, but the file (of course) gets regenerated in few saves.

**Comment by KieranLafferty** [comment]
Same issue here it will occasionally import the correct package but for some it never does.

**Comment by theweiweiway** [comment]
Is this still a problem in 1.0.1?

**Comment by Milad-Akarie** [comment]
@theweiweiway That was fixed too.
