### ISSUE TITLE
Nested ExtendedNavigator does not remember state on hot reload

### ISSUE THREAD

**Issue by alhafoudh** [Milad-Akarie/auto_route_library#251]
Hi, I my root ExtendedNavigator does remember on which route I am currently on, but when I hot reload when I am in some nested route handled by nested ExtendedNavigator, I get routed to last root route, not the nested route. I did not find any specific solution how can I achieve this, I tried tweaking the `key` parameter, but with no luck.

**Comment by cacianokroth** [comment]
Hello, try this: https://github.com/Milad-Akarie/auto_route_library/pull/225!

**Comment by Milad-Akarie** [comment]
Hey @alhafoudh, I honestly can't reproduce the error, everything is restored as intended when I hot reload. 
are you using the nav builder with Material App?
```dart
 MaterialApp(
      // builder uses the native nav key to keep
      // the state of ExtendedNavigator so it won't reload
      // when using Flutter tools-> select widget mode
      builder: ExtendedNavigator.builder<AppRouter>(router:AppRouter,..);
```

**Comment by alhafoudh** [comment]
@Milad-Akarie i have the root navigator exactly like that in my code. How should I have the nested one? Inside the root nav...

**Comment by Milad-Akarie** [comment]
Nested one should look like this
```dart
ExtendedNavigator(
       // optional initial route
        initialRoute: UsersScreenRoutes.profileScreen,
       // optional name/key
        name: 'usersRouter',
      ),
```

**Comment by theweiweiway** [comment]
closing due to:
- stale issue
