### ISSUE TITLE
Error: The non-abstract class '_CustomNavigatorState' is missing implementations for these members:

### ISSUE THREAD

**Issue by Vildnex** [Milad-Akarie/auto_route_library#252]
I'm using the `auto_route` package in order to route my app and until 2 days ago everything worked just fine, until now.
For some reason, I'm getting the following error.

**SYSTEM:**

- **flutter**: 1.22
- **dart**: 2.10.0
- **auto_route**: ^0.6.7

**ERROR:**

    ../../.pub-cache/hosted/pub.dartlang.org/custom_navigator-0.3.0/lib/custom_navigator.dart:60:7: Error: The non-abstract class '_CustomNavigatorState' is missing implementations for these members:
     - WidgetsBindingObserver.didPushRouteInformation
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
    
    class _CustomNavigatorState extends State<CustomNavigator>
          ^^^^^^^^^^^^^^^^^^^^^
    /opt/flutter/packages/flutter/lib/src/widgets/binding.dart:122:16: Context: 'WidgetsBindingObserver.didPushRouteInformation' is defined here.
      Future<bool> didPushRouteInformation(RouteInformation routeInformation) {

**main.dart**

    import 'package:device_simulator/device_simulator.dart';
    import 'package:flutter/material.dart';
    import 'package:auto_route/auto_route.dart';
    import 'Test.gr.dart' as r;
    void main() => runApp(MyApp());
    
    const bool debugEnableDeviceSimulator = true;
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
        builder: ExtendedNavigator.builder<r.Router>(
          router: r.Router(),
          builder: (context, extendedNav) => DeviceSimulator(
            enable: debugEnableDeviceSimulator,
            child:
                Scaffold(body: extendedNav, backgroundColor: Colors.red ),
          ),
        ),
        );
      }
    }

Also, I should mention, because of some update of flutter I guess, now I need to use `r.Router` instead of just `Router`.

**Test.dart**

    import 'package:auto_route/auto_route_annotations.dart';
    
    @MaterialAutoRouter(
      routes: <AutoRoute>[],
    )
    class $Router {}

And also if has any importance here it's the generated file

**Test.gr.dart**

    // GENERATED CODE - DO NOT MODIFY BY HAND
    
    // **************************************************************************
    // AutoRouteGenerator
    // **************************************************************************
    
    // ignore_for_file: public_member_api_docs
    
    import 'package:auto_route/auto_route.dart';
    
    class Routes {
      static const all = <String>{};
    }
    
    class Router extends RouterBase {
      @override
      List<RouteDef> get routes => _routes;
      final _routes = <RouteDef>[];
      @override
      Map<Type, AutoRouteFactory> get pagesMap => _pagesMap;
      final _pagesMap = <Type, AutoRouteFactory>{};
    }

Do you have any idea what's going one here or how can I fix this? Or if I can't fix this, what can I use instead of the `auto_route` package which will offer me the same benefice?

**Comment by Milad-Akarie** [comment]
Hey, This should be fixed in the latest versions ..check it out
