### ISSUE TITLE
error-404-page-not-found-profilescreen-in-flutter

### ISSUE THREAD

**Issue by MuazamAli69** [Milad-Akarie/auto_route_library#256]
I am using the flutter auto_route package for navigation. This error occurs when I navigate the screen on the context. e.g: If I write

` ExtendedNavigator.named('BuyRouter').push(HomeRoutes.profileScreen);`
This works and pushes on the BuyRouter screen but the problem I am having that I want to push the screen on context. As I apply this to the context.

`  ExtendedNavigator.root.push(HomeRoutes.profileScreen);`
Error 404 page not found /profile screen occurs.

I also uploaded the question on StackOverflow [Url](https://stackoverflow.com/questions/64301069/error-404-page-not-found-profilescreen-in-flutter)

**Comment by Milad-Akarie** [comment]
calling ExtendedNav.root doesn't use context to locate your nav, if you want to use context
`ExtendedNavigator.of(context).push(HomeRoutes.profileScreen)`

**Comment by MuazamAli69** [comment]
Thanks issued resolved
