### ISSUE TITLE
invalid member on null: 'key'

### ISSUE THREAD

**Issue by rlee1990** [Milad-Akarie/auto_route_library#257]
I am receiving an error `invalid member on null: 'key'` when trying to build the app.

```
`class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  
  @override
  Widget build(BuildContext context) {
    final themeData = Provider.of<ThemeState>(context);
    final connectionStatus = Provider.of<ConnectionStatus>(context);
    return OverlaySupport(
      child: MultiProvider(
        providers: [
          StreamProvider<UserPublic>(
            create: (context) => FirestoreService().streamPublicUser(Provider.of<User>(context, listen: false).uid),
          ),
        ],
          child: MaterialApp(
            builder: ExtendedNavigator.builder(
              router: SnabRouter(),
              guards: [AuthGuard()],
            ),
          title: 'SNAB',
          theme: themeData.getTheme(),
          debugShowCheckedModeBanner: false,
        ),
      ),
    );
  }
}`
```
[√] Flutter (Channel master, 1.23.0-14.0.pre.84, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.0)
[√] Connected device (3 available)

• No issues found!

**Comment by hauketoenjes** [comment]
Same problem here, the issue seems to occur on all platforms (i tested android and web).

The `invalid member on null: 'key'` occurs in line 37 in the `ExtendedNavigator` : 
https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/extended_navigator.dart#L37

I tested with the provided example code of this package.

**Comment by rlee1990** [comment]
@hauketoenjes I think that the application is not generating the key

**Comment by rlee1990** [comment]
@Milad-Akarie any idea on this?

**Comment by hauketoenjes** [comment]
I just tested on another channel of flutter than master and the problem is gone. Probably a temporary problem on the flutter side. Seems to be no problem with this package imo.

**Comment by rlee1990** [comment]
Okay cool good to now Sucks because the master has the fix for the URL hash for Flutter web. @hauketoenjes I wonder if there was a breaking change for the newest version of master that is not yet compatible with this. I will close this for now.

**Comment by rlee1990** [comment]
I have to reopen it as I can only use the master channel and the hash URL fix will come to beta but I think the problem might come also for this package down then line.

**Comment by rlee1990** [comment]
@hauketoenjes I found the issue it is with the package. the issue is with line `      (context, nav) {
        var extendedNav = ExtendedNavigator<T>(
          // key: GlobalObjectKey(nav.key),
          navigatorKey: navigatorKey,
          observers: observers,
          onUnknownRoute: onUnknownRoute,
          initialRoute: initialRoute,
          initialRouteArgs: initialRouteArgs,
          router: router,
          guards: guards,
          name: name,
        );`
Commenting out the key works. It looks like the key is never being supplied from the builder.

**Comment by mx1up** [comment]
having the same problem on beta
```
Flutter 1.22.0-12.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8b3760638a (4 weeks ago) • 2020-09-15 17:47:13 -0700
Engine • revision 4654fc6cf6
Tools • Dart 2.10.0 (build 2.10.0-110.3.beta)
```

**Comment by rlee1990** [comment]
@mx1up did you try what I did above?

**Comment by mx1up** [comment]
@rlee1990  yes, commenting out that line does make it work again..

**Comment by BaR488** [comment]
Hi, something change in flutter WidgetApp.
Look at [this getter](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/app.dart#L1177)

[This way](http://www.smlll.com/packages/auto_route#using-the-native-navigator) should work.

Or just set not **null value**  in `home` or `onGenerateRoute` or `onUnknownRoute` or set not empty `routes`

**Comment by afermin** [comment]
HI @rlee1990. Do you mean we have to comment the line in the library? I don't have it in my local

**Comment by rlee1990** [comment]
@afermin yes that was how I got it to work. We have to wait until @Milad-Akarie fixes the issue.

**Comment by eggnstone** [comment]
Is there a better workaround?
Me commenting out the line in your library does not seem like a good solution.
How about changing
`key: GlobalObjectKey(nav.key),`
to
`key: nav == null ? null : GlobalObjectKey(nav.key),`

**Comment by mars3142** [comment]
That's why I created a pull request, which seems to be ignored. 🤔

**Comment by Milad-Akarie** [comment]
Hello all,
sorry for the late replay. The purpose of using the builder is using the nav.key to maintain navigator state when Flutter inspector reloads the App, in other words, without the key we don't need the builder! so for now you can just build your ExtendedNavigator using the default constructor.

**Comment by SamuelMTDavies** [comment]
Hi @Milad-Akarie,

Can you please elaborate on what the purpose of the builder is and the difference between the two code samples in the docs?

**Everyone else** who doesn't want to comment out the key in the package.


### This is what the documentation shows for the examples.
`MaterialApp(
     builder: ExtendedNavigator.builder<Router>(router: Router(),
     // pass anything navigation related to ExtendedNav instead of MaterialApp
         initialRoute: ...
         observers:...
         navigatorKey:...
         onUnknownRoute:...
     ),

    MaterialApp(
      builder: ExtendedNavigator.builder(
        router: Router(),
        builder: (context, extendedNav) => Theme(
          data: ThemeData(brightness: Brightness.dark),
          child: extendedNav,
        ),
      ),`




Milad is saying unless you need specific functionality your code should be more like this

`MaterialApp(
      builder: ExtendedNavigator<AppRouter>(
        router: AppRouter(),
        guards: [AuthGuard()],
        initialRoute: '/',
      ),
    );`

@Milad-Akarie I'm happy to write a pull request to update the docs to make them clearer - I just need to understand the main differences and functionality of the builder.

**Comment by Milad-Akarie** [comment]
@SamuelMTDavies When Flutter inspector is launched (widget select mode) specifically, MaterialApp reloads and the navigator loses state, as a work around I'm using the native nav's key whiches maintained by the MaterialApp to create a global object key to restore ExtendedNavigator state on App reloads

**Comment by Milad-Akarie** [comment]
@SamuelMTDavies I'm really close to launching auto_route 1.0-beta which is based on navigator 2.0.
Extended Navigator has alot of work  a rounds due to its limited Api flexibility. So it will probably be merely maintained as legacy

**Comment by mars3142** [comment]
@Milad-Akarie How can I use the default ExtendedNavigator constructor with something like a custom transition builder function. I need that, because I want always to wrap my screens with a stack, so I can dynamic add widgets. That's why I currently need the builder factory constructor.

**Comment by Flow2dot0** [comment]
@mars3142 @Milad-Akarie 

Hello, actually that you can perform to wait for auto_route 1.0 on navigator 2.0 and if you still got the issue is this trick : 

        home: Navigator(
          pages: [MaterialPage(child: **YOUR_START_PAGE()**)],
          onPopPage: (route, result) {
            if (!route.didPop(result)) return false;
            return true;
          },
        ),
        builder: ExtendedNavigator.builder<router.Router>(
          guards: [AuthGuard()],
          router: router.Router(),
          builder: (context, extendedNav) => Theme(
              data: ThemeData(
                scaffoldBackgroundColor: cWhite,
                fontFamily: primaryFontFamily,
              ),
              child: extendedNav),
        ),

This solve my invalid member on null:key issue. It is temporary. Commenting the navigator.key on the library didn't change anything to the issue only this does.

Hope it helps.

**Comment by wer-mathurin** [comment]
Thanks @Flow2dot0  just adding Container() solve the issue !

**Comment by 2shrestha22** [comment]
Same problem after updating to Flutter 2.0 today.

**Comment by sath26** [comment]
the problem occured in mine as well

**Comment by thenifemi** [comment]
Same here @2shrestha22 @sath26 .. I fixed it by removing the `.builder` from ` builder: ExtendedNavigator.builder(
        navigatorKey: navigatorKey,
        router: AppRouter(),
      ),` and change it to ` builder: ExtendedNavigator(
        navigatorKey: navigatorKey,
        router: AppRouter(),
      ),`

**Comment by sath26** [comment]
where does the navigatorKey come from to get assigned to.? @thenifemi

**Comment by thenifemi** [comment]
@sath26 Ignore it, don't include it.

**Comment by sath26** [comment]
i get undefined name 'navigatorKey' error @thenifemi

**Comment by thenifemi** [comment]
Interesting!
Add:
```
 GlobalKey<NavigatorState> navigatorKey;
```
and then in your MaterialApp widget:
```
builder: ExtendedNavigator(
       navigatorKey: navigatorKey,
       router: AppRouter(),
     ),
```

**Comment by sath26** [comment]
@thenifemi 
`The following assertion was thrown building HeroControllerScope:
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [GlobalObjectKey _MaterialAppState#8c8b7]
The parent of the widgets with that key was: HeroControllerScope
The first child to get instantiated with that key became: WidgetsApp-[GlobalObjectKey _MaterialAppState#8c8b7]
    state: _WidgetsAppState#d0aa5
The second child that was to be instantiated with that key was: HeroControllerScope
A GlobalKey can only be specified on one widget at a time in the widget tree.
`
i got the above error. unable figure out the reason behind the error. i have added
` GlobalKey<NavigatorState> navigatorKey;` in following way
`
class AppWidget extends StatelessWidget {
  GlobalKey<NavigatorState> navigatorKey;
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (context) =>
              getIt<AuthBloc>()..add(const AuthEvent.authCheckRequested()),
        )
      ],
      child: MaterialApp(
        title: 'Shamagri - bill sharing app',
        debugShowCheckedModeBanner: false,
        builder: ExtendedNavigator(
          navigatorKey: navigatorKey,
          router: app_router.Router(),
          //initialRoute: app_router.Routes.splashScreen
        ),
        theme: ThemeData.light().copyWith(
          primaryColor: Colors.green[800],
          accentColor: Colors.blueAccent,
          floatingActionButtonTheme: FloatingActionButtonThemeData(
            backgroundColor: Colors.blue[900],
          ),
          inputDecorationTheme: InputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by thenifemi** [comment]
@sath26 I like the way you code.

Please put the `GlobalKey<NavigatorState> navigatorKey;` in your build function.

**Comment by pvaibhav** [comment]
Just adding a data point for anyone using `WidgetsApp` on flutter 2. The following worked for me:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WidgetsApp(
        color: Colors.blue, builder: ExtendedNavigator(router: MyRouter()));
  }
}
```
