### ISSUE TITLE
Are you planning to support the Navigator 2.0 (declarative) API

### ISSUE THREAD

**Issue by dgaedcke** [Milad-Akarie/auto_route_library#258]
https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#heading=h.l6kdsrb6j9id

It feels like this is the way Flutter is going and I'd prefer to invest in the future.

Do you plan to support this pattern??

**Comment by Milad-Akarie** [comment]
@dgaedcke Of course I'm planning to, I've been following Nav 2.0 for a while now, it might take me some time to implement it though.

**Comment by theweiweiway** [comment]
Autoroute 1.x now supports Navigation 2.0
