### ISSUE TITLE
NoSuchMethodError The getter "Key" was called on null

### ISSUE THREAD

**Issue by KaushickSArgekar** [Milad-Akarie/auto_route_library#259]
MaterialApp(
          debugShowCheckedModeBanner: false,
          builder: ExtendedNavigator.builder<AppRouter>(router: AppRouter()),
        ));

@MaterialAutoRouter(routes: <AutoRoute>[
  MaterialRoute(page: SplashPage, initial: true),
  MaterialRoute(page: LoginPage),
  MaterialRoute(page: DashboardPage)
])
class $AppRouter {}

**Comment by rlee1990** [comment]
@KaushickSArgekar look at #257

**Comment by theweiweiway** [comment]
Closing due to:
- stale issue
- possible solution in #257
