### ISSUE TITLE
Conditional initial route causes push animation at boot

### ISSUE THREAD

**Issue by softronaut** [Milad-Akarie/auto_route_library#263]
I have two initial routes depends on the condition like:
```
initialRoute: isNewUser ? WelcomeScreen : HomeScreen;
```
So, in `MaterialAutoRouter` I defined the `HomeScreen` as the initial because most of the time it will take that responsibility. The problem is, if `isNewUser` returns true, I have a push animation for `WelcomeScreen` which is absolutely unwanted. I don't want any navigation animation at boot.

I read the documentation but couldn't find any related example or solution.

This is the `NavigationObserver`:
```
flutter: NavObserver.push: null
flutter: NavObserver.push: null => welcome
```

There is a workaround by creating a custom transition that does nothing. But it's unwanted of course...

**Comment by KieranLafferty** [comment]
Also experiencing this one. @softronaut  could you please describe the workaround you implemented in more detail?

**Comment by softronaut** [comment]
@KieranLafferty here the code I use for workaround:
```dart
...
@MaterialAutoRouter(
  routes: <AutoRoute>[
    CustomRoute(page: WelcomePage, transitionsBuilder: CustomTransitions.noTransition),
...

class CustomTransitions {
  static const noTransition = _noTransition;

  static Widget _noTransition(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return child;
  }
...
```
