### ISSUE TITLE
BuildContext conflict

### ISSUE THREAD

**Issue by matthewfx** [Milad-Akarie/auto_route_library#264]
Hi,

I just had to upgrade the auto_route in my existing libraries from 0.6.0 to the current one because the generator wasn't working with the latest flutter. I don't know why but I'm getting errors in all files with auto_route library imported.

_The name 'BuildContext' is defined in the libraries 'package:auto_route/src/extended_navigator.dart (via package:auto_route/auto_route.dart)' and 'package:flutter/src/widgets/framework.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports._

That is really weird because I haven't had those errors with 0.6.0... Any idea what might be a reason for it?

Thanks,

mat

**Comment by chrisoftech** [comment]
Hi @matthewfx am currently experiencing the same issue. What i did as a fix was to hide auto-route BuildContext from imports.
Like so 
`import 'package:auto_route/auto_route.dart' hide BuildContext;`
