### ISSUE TITLE
V.60 removed ofRouter

### ISSUE THREAD

**Issue by brasizza** [Milad-Akarie/auto_route_library#266]
Hi!.
I have in my app on main.dart a deeplink to move to some page in my app  and i used like this (ExtendedNavigator.ofRouter<Router>().popAndPushNamed(Routes.qrcode..........) , but now this version remove the "ofRouter".. how can i use the same thing ?

**Comment by theweiweiway** [comment]
may i suggest you upgrade to version 2.x? Previous version are no longer supported

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
