### ISSUE TITLE
path: '*' to known page

### ISSUE THREAD

**Issue by zs-dima** [Milad-Akarie/auto_route_library#270]
path: ```'*'``` to known page
it could be nice to be able to have same page in common route and ```'*'``` path:

```dart
@CustomAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      page: LoadingPage,
      initial: true,
    ),
    AutoRoute(
      page: HomePage,
      children: <AutoRoute>[
        AutoRoute(initial: true, page: Page1),
        AutoRoute(page: Page2),
        AutoRoute(page: Page3),
      ],
    ),
    AutoRoute(path: '*', page: HomePage),
  ],
)
class $Router {}
```

**Comment by Milad-Akarie** [comment]
@zs-dima I'm not sure I get your point. doesn't the above code work as expected?

**Comment by zs-dima** [comment]
@Milad-Akarie 
Code above lead to generated code error as it will be duplicated Route 'homePage'
Hope navigator 2.0 auto_route version will not have this issue

**Comment by theweiweiway** [comment]
Closing in favour of #318
