### ISSUE TITLE
Expose reverseTransitionDuration property for CustomRoute

### ISSUE THREAD

**Issue by alexagat** [Milad-Akarie/auto_route_library#276]
The `CustomRoute` type does not expose a `reverseTransitionDuration` property, which could be set on the generated `PageRouteBuilder`. 

Without this exposure, one cannot control this property on a `CustomRoute` and change it from the default of `300ms`.

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
