### ISSUE TITLE
Can't use anymore push for dynamic routes

### ISSUE THREAD

**Issue by BenevidesLecontes** [Milad-Akarie/auto_route_library#28]
Hi @Milad-Akarie on the newer version I can't push anymore `MaterialPageRoute` for dynamic routes.
I'm using it extensively with nested navigators. Why you introduced this breaking change? thanks.

**Comment by Milad-Akarie** [comment]
Hey @BenevidesLecontes, what do you mean you can't push? What kinda error do you get?

**Comment by BenevidesLecontes** [comment]
I was using `navigatorKey CurrentState`to do things like that on nested navigators 
```
navigatorKey.currentState.push(
      MaterialPageRoute(
        fullscreenDialog: true,
        builder: (BuildContext context) => page,
      ),
    );
```
With the newer version i can't  do this anymore, because extended navigator doesn't have the `push` method, only `pushNamed`.

**Comment by Milad-Akarie** [comment]
Hey @BenevidesLecontes, is there a good reason why you're pushing Routes directly instead of by name? This's not how autoRoute supposed to work.
