### ISSUE TITLE
Build runner should import custom transition class

### ISSUE THREAD

**Issue by ImDeZz** [Milad-Akarie/auto_route_library#281]
I have made a custom transitionBuilder class, but the buildrunner is not importing the class in the generated file. I can import it manually, but it should do it automatically.
![image](https://user-images.githubusercontent.com/18382875/101617033-6565f300-3a10-11eb-8501-6f86ee262a2c.png)

**Comment by theweiweiway** [comment]
@ImDeZz What verison? It works for me on latest 1.0.0 version

**Comment by theweiweiway** [comment]
Closing due to stale issue
