### ISSUE TITLE
Bugs with nested routing and AutoTabsRouter

### ISSUE THREAD

**Issue by maxiundtesa** [Milad-Akarie/auto_route_library#287]
Hi,

I am facing problems/experiencing a bug with nested routing and the AutoTabsRouter.
For this I used a slightly modified version of the example project.
My intention is to have the ProfilePage at the url "profile" instead of profile/me and have the MyBooksPage as a "child" Page with the url profile/books.
With that I'm experiencing two bugs:
1. The url doesnt change to profile if you select the profile tab. This only happens if a Route is specified in the children array in the profileTab element. If the children array is empty, the url change works fine.
2. App cant navigate to the MyBooksPage, the error message says "Router can not navigate to profile/books". And i did change the router call in the Profile Page to `context.router.push(ProfileTab(children: [MyBooksRoute(filter: 'FromRoute')]))`

Otherwise it's working great:)

Flutter Version: 1.25.0-8.1.pre
Auto_route Version: 1.0.0-beta.1 

Changed files from Example Project:
```import 'package:auto_route/annotations.dart';
import 'package:auto_route/auto_route.dart';
import 'package:example/mobile/screens/profile/profile_page.dart';

import 'my_books_page.dart';

const profileTab = AutoRoute(
  path: 'profile',
  name: 'ProfileTab',
  page: ProfilePage,
  children: [
    AutoRoute(path: 'books', page: MyBooksPage),
  ],
);
```

```import 'package:auto_route/auto_route.dart';
import 'package:example/mobile/router/router.dart';
import 'package:example/mobile/screens/user-data/data_collector.dart';
import 'package:flutter/material.dart';

class ProfilePage extends StatefulWidget {
  @override
  _ProfilePageState createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  UserData userData;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'Profile page',
              style: Theme.of(context).textTheme.headline5,
            ),
            const SizedBox(height: 32),
            RaisedButton(
                child: Text('My Books'),
                onPressed: () {
                  context.router.push(ProfileTab(children: [MyBooksRoute(filter: 'FromRoute')]));
                }),
            const SizedBox(height: 32),
            userData == null
                ? RaisedButton(
                    child: Text('Collect user data'),
                    onPressed: () {
                      context.router.root.push(UserDataCollectorRoute(onResult: (data) {
                        setState(() {
                          userData = data;
                        });
                      }));
                    })
                : Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text('Your Data is complete'),
                      const SizedBox(height: 24),
                      Text('Name: ${userData.name}'),
                      const SizedBox(height: 24),
                      Text('Favorite book: ${userData.favoriteBook}'),
                    ],
                  )
          ],
        ),
      ),
    );
  }
}
```

**Comment by Milad-Akarie** [comment]
Hello.
When a router has children it means that it has it's own "inner controller/router"
for the following example to work you'll need to define an outlet (AutoRouter Widget) for child routes inside of the ProfilePage

```dart
const profileTab = AutoRoute(
  path: 'profile',
  name: 'ProfileTab',
  page: ProfilePage,
  children: [ // this is considered an inner router
    AutoRoute(path: 'books', page: MyBooksPage),
  ],
);
```

This setup will show your profile page at 'profile' and myBooks at 'profile/books'
EmptyRouterPage is as the name suggests an empty  page that has nothing but an AutoRouter outlet to render child routes.
```dart
const profileTab = AutoRoute(
  path: 'profile',
  name: 'ProfileTab',
  page: EmptyRouterPage, // the outlet of the child routes
  children: [ 
     AutoRoute(path: '', page: ProfilePage),
    AutoRoute(path: 'books', page: MyBooksPage),
  ],
);

let me know if this doesn't work for you. 
```

**Comment by maxiundtesa** [comment]
Ah ok, so i have to modify the profile page aswell...
Normally i would have used the second version with the EmptyRouterPage, but i tried that before and got an error message: `"NoSuchMethodError: invalid member on null: '+'"`
This error message only appears, when there is an AutoRoute with an empty path '' inside the children array.

This error apparently has something to do with line 25 in the route_match.dart file: `params = pathParams + queryParams`
Both pathParams and queryParams should be empty objects, but instead in that case they are null

**Comment by maxiundtesa** [comment]
The "NoSuchMethodError: invalid member on null: '+'" bug still persists with the second beta.
In order to replicate it, you can use the example project and just replace the profileTab-route with your provided solution. After that the error message appears
```
const profileTab = AutoRoute(
  path: 'profile',
  name: 'ProfileTab',
  page: EmptyRouterPage, // the outlet of the child routes
  children: [ 
     AutoRoute(path: '', page: ProfilePage),
    AutoRoute(path: 'books', page: MyBooksPage),
  ],
);
```

**Comment by Milad-Akarie** [comment]
@maxiundtesa  That's an easy one.. will be pushed real soon.

**Comment by Milad-Akarie** [comment]
@maxiundtesa should be fixed
https://pub.dev/packages/auto_route/versions/1.0.0-beta.3+1

**Comment by maxiundtesa** [comment]
Yes, it works great now:)
Thanks a lot for the quick fix and for the amazing library!
Btw another thing i noticed: When you reload the page in the example app / press enter on the url, it always switches to the default page and not the currently chosen url. Is that behavior expected?

**Comment by Milad-Akarie** [comment]
@maxiundtesa When you refresh the browser you're actually rebuilding the App with the url as an initial destination, but that can be overridden by 'initialDeepLink' or 'initialRoutes' property inside of the RootRouteDelegate (which are only meant for mobile), so make sure you don't have an initial destination set by your App.

**Comment by maxiundtesa** [comment]
@Milad-Akarie That definitely makes sense. Thanks:)
I had a initial route of „/„ set, thats why it didn’t work. After removing that it works fine.

Another thing i noticed: It is currently not possible to have two different routes for the same page. Although it does make sense in some usecases.
For example to have a page with all items ever created by all users at the url `/items` and then have the same page/widget at the url `account/items`, where it only shows the items created by the current user.
If i create those two routes with different routeNames and then to call them, one works, the other one only shows an error message:  `Error: Expected [ItemWidgetRoute2],  found [ItemWidgetRoute1]`
Is that functionality generally possible or is router 2.0/auto_route strictly limited to only one route per page?

**Comment by Milad-Akarie** [comment]
This used to validate route args when they were separated from the RoutePageInfo, it shouldn't be necessary now, I'll see what I can do.

**Comment by Milad-Akarie** [comment]
@maxiundtesa The new version using route names to map pages inside of the Page types, so duplicate page names shouldn't be a problem any more. 
check it out
https://pub.dev/packages/auto_route/versions/1.0.0-beta.4
https://pub.dev/packages/auto_route_generator/versions/1.0.0-beta.4

**Comment by maxiundtesa** [comment]
@Milad-Akarie It works absolutely fine, thanks:)
I also noticed that pressing the browser back button apparently doesn't call something like `Navigator.of(context).pop()`, but instead navigates to the url before (like .pop() would do) and also reloads the whole application. 
So every stateful widget is rebuild (`initState()` is getting called) and even worse: Also my provider/AppState is getting recreated, which is done in the HomeRouterPage-Class. I understand that this is probably intended if the user reloads the browser page, but on a press of the back button?

```
class HomeRouterPage extends AutoRouter with AutoRouteWrapper {
  const HomeRouterPage({Key key}) : super(key: key);

  @override
  Widget wrappedRoute(BuildContext context) {
    return ChangeNotifierProvider<FrontPageState>(
        create: (c) => FrontPageState(),
        child: this
    );
  }
}
```

```
const homeTabRoutes = AutoRoute(
  path: 'h',
  page: HomeRouterPage,
  name: 'HomeTab',
  children: [
    AutoRoute(path: '', page: HomeScreen),
    AutoRoute(path: 'map', page: ChooseLocationWidget, fullscreenDialog: true),
  ],
);
```
