### ISSUE TITLE
The getter 'rootDelegate' isn't defined for the type 'AppRouter'.

### ISSUE THREAD

**Issue by tmxdyf** [Milad-Akarie/auto_route_library#289]
Hello, I met the following problem, please help, thank you.
![image](https://user-images.githubusercontent.com/6415080/102750530-f1790280-43a0-11eb-9da8-5d7bab8faba2.png)

**Comment by Milad-Akarie** [comment]
What version are you using?

**Comment by Milad-Akarie** [comment]
Make sure you also upgrade the generator and re-run it

**Comment by tmxdyf** [comment]
auto_route: ^0.6.9
Has been upgraded ^1.0.0-beta.2 to solve this problem. Thank you.
