### ISSUE TITLE
Access context inside Guard 1.0.0

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#290]
Hi Milad!

Is there a way to access context inside of the AuthGuard? All of the examples I have found in both the old and new documentation use shared preferences or a variable to control whether the user is authenticated. 

I want to use Bloc to control whether the user is authenticated, and need to access context to do that. 

For reference:

```
bool isAuthenticated = false;

class AuthGuard extends AutoRouteGuard {
  @override
  Future<bool> canNavigate(   
      List<PageRouteInfo> pendingRoutes, StackRouter router) async {
    // rely on Bloc state here instead of isAuthenticated variable
    if (!isAuthenticated) {
      router.root.push(AuthRouter());
      return false;
    }
    return true;
  }
}
```

On a side note, 1.0.0 is amazing. Much easier to write code and understand what is happening. Plus the TabsRouter Feature with lazy loading is a godsend as I was handling all of that manually before

thanks Milad!

**Comment by Milad-Akarie** [comment]
@theweiweiway Glad to hear my package is making other developer's life easier. 
You could use the navigatorKey's context as long as you provide your bloc above the MaterialApp or at least above the router widget inside of the MaterialApp builder. 


**Note:** make sure you read or call Provider.of() with listen set to false 
```dart
 final context = router.navigatorKey.currentContext;
 context.read<T>()...
```

**Comment by theweiweiway** [comment]
Amazing, got it - thnx!

**Comment by theweiweiway** [comment]
Hi @Milad-Akarie Milad,

sorry - I actually can't use the solution provided above because `router.navigatorKey.currentContext` returns null. Here's the code snippet:

```
class AuthGuard extends AutoRouteGuard {
  @override
  Future<bool> canNavigate(
      List<PageRouteInfo> pendingRoutes, StackRouter router) async {
    print(router.navigatorKey.currentContext); // returns null
    return true;
  }
}
```

The full repo is here: https://github.com/theweiweiway/auto_route_example

**Comment by Milad-Akarie** [comment]
Using it on initial routes?

**Comment by theweiweiway** [comment]
No initial routes and also no deep link

**Comment by Milad-Akarie** [comment]
@theweiweiway pushing `/groups/root/details` will push home page first `/` then groups tab `groups` then `root` then `root/details`  so you're guarding an initial route.
The guard is activated before the navigator key got mounted, so I guess it makes sense that the context is still null. I'll take a closer look as soon as possible.

**Comment by theweiweiway** [comment]
@Milad-Akarie 

oh, sorry - i commented out the initialDeepLink when I was testing this. So whatever the repo shows is not 100% accurate with respect to that initialDeepLink parameter

But yeah, that makes sense , something to do with race conditions and the Guard being mounted before navigator key

Thanks!

**Comment by pxsanghyo** [comment]
I'm having the same problem where context is null.
@theweiweiway Did you find a workaround?
@Milad-Akarie Any update on this issue?

Thanks!

**Comment by theweiweiway** [comment]
@pxsanghyo  The way I currently get around this is by specifying 2 routers, one is an `AppRouter` and one is an `AuthRouter` . I use it like so:

```dart
  final _appRouter = AppRouter();
  final _authRouter = AuthRouter();

  RootStackRouter _getRouter(AuthState state) {
    return state.maybeMap(
      signedIn: (_) => _appRouter,
      orElse: () => _authRouter,
    );
  }


...
MaterialApp.router(
    routerDelegate: _getRouter(state).delegate(),
    routeInformationParser:
        _getRouter(state).defaultRouteParser(),
)
```

However, this only works if you want to protect your whole app when logged out, and not specific parts of the app

**Comment by DeD1rk** [comment]
> @pxsanghyo The way I currently get around this is by specifying 2 routers, one is an `AppRouter` and one is an `AuthRouter` . I use it like so:

This is exactly my use case (I have an AuthBloc providing the AuthState, that now surrounds the MaterialApp.router, though I could move it op or down the tree as required), but I'm not entirely sure which router should do what, could you elaborate on how the AuthRouter should look with respect to the AppRouter?

**Comment by DeD1rk** [comment]
I just did another approach. I have an `AuthBloc` with a `Stream<AuthState>` that is provided around my app. I now have a stateful widget with the `AppRouter` created in its `initState()` method. The AuthGuard parameter of the AppRouter get's the Stream<AuthState>, and listens to it: 

```dart 
class AuthGuard implements AutoRouteGuard {
  bool _authenticated = false;

  AuthGuard(Stream<AuthState> authStream) {
    authStream.listen((authState) {
      _authenticated = (authState is LoggedInAuthState);
    });
  }
  ...
}

class _ThaliAppState extends State<ThaliApp> {
  late final _appRouter;

  @override
  void initState() {
    final authBloc = BlocProvider.of<AuthBloc>(context, listen: false);
    _appRouter = AppRouter(authGuard: AuthGuard(authBloc.stream));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'App',
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
    );
  }
}
```

My implementation might be a bit unpolished, but I think something similar could work for various use cases, including with ChangeNotifiers and such instead of BLoC, and with intricate AuthGuard code.

**Comment by Milad-Akarie** [comment]
@DeD1rk That look a decent approach to me.

**Comment by theweiweiway** [comment]
@DeD1rk that is the best solution i love it!

**Comment by alexgrusu** [comment]
Hi, I have a similar approach with that shown by @DeD1rk, but I'm struggling with some point.

I use a SplashPage with a BlocListener like this:
`class SplashPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        state.map(
          initial: (_) {},
          authenticated: (_) => context.router.replace(const HomePageRoute()),
          unauthenticated: (_) =>
              context.router.replace(const SignInPageRoute()),
        );
      },
      child: const Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}
`
Then, runApp(MyApp()); 

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    loadImages(context);
    return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (context) =>
              getIt<AuthBloc>()..add(const AuthEvent.authCheckRequested()),
        ),
      ],
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,
        theme: ThemeData.light().copyWith(
          inputDecorationTheme: InputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8.0),
            ),
          ),
          textSelectionTheme: const TextSelectionThemeData(
            cursorColor: Colors.white,
            selectionColor: Colors.white,
          ),
        ),
        routeInformationParser: MyAppRouter().defaultRouteParser(),
        routerDelegate: MyAppRouter().delegate(
          initialRoutes: [const SplashPageRoute()],
        ),
      ),
    );
  }
}

Somehow, if I trigger the logOut and then going to ResetPasswordPage, when calling pop() it throws the app in the HomePage.
Also, I saw that if I try to hot reload the app, a white screen is shown.

Before null-safety I used a builder with ExtendedNavigator like so:
` child: MaterialApp(
        debugShowCheckedModeBanner: false,
        builder: ExtendedNavigator(
          router: MyAppRouter(),
        ),
`
Am I missing something?

Now, my MaterialAppRouter looks as below

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: SplashPage, initial: true),
    AutoRoute(page: SignInPage),
    AutoRoute(page: RegisterPage),
    AutoRoute(page: ResetPasswordPage),
    AutoRoute(page: HomePage),
],
generateNavigationHelperExtension: true,
)
class $MyAppRouter {
  late SplashPage splashPage;
  late SignInPage signInPage;
  late RegisterPage registerPage;
  late ResetPasswordPage resetPasswordPage;
  late HomePage homePage;
}

```

**Comment by zsoerenm** [comment]
@DeD1rk 
I expanded your idea a bit further and came up with following clever solution:

```dart
class AuthGuard extends AutoRouteGuard {
  final AuthenticationBloc authBloc;
  StreamSubscription<AuthenticationState> authBlocStateSubscription;

  AuthGuard({this.authBloc});

  @override
  Future<bool> canNavigate(
      List<PageRouteInfo> pendingRoutes, StackRouter router) async {
    if (authBloc.state is Unauthenticated) {
      router.root.push(LoginRoute());
    } else if (authBloc.state is Authenticated) return true;

    authBlocStateSubscription?.cancel();
    authBlocStateSubscription = authBloc.stream.listen((state) {
      if (authBloc.state is Uninitialized && state is Unauthenticated) {
        router.root.push(LoginRoute());
      }
      if (state is Authenticated) {
        router.replaceAll(pendingRoutes);
        authBlocStateSubscription.cancel();
      }
    });
    return false;
  }
}
```
Doing it this way you do not need to pass a callback to the Login page. Simply login the user in and the subscription will lead you to the correct pending route. This should even work when you log in the user in a different tap in the browser!

**Comment by herman-the-worm** [comment]
@zsoerenm any clever way to convert the current solution for the new AuthGuard?

https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/router/auth_guard.dart

**Comment by alexgrusu** [comment]
> @zsoerenm any clever way to convert the current solution for the new AuthGuard?
> 
> https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/router/auth_guard.dart

Check the one listed above by me, https://github.com/Milad-Akarie/auto_route_library/issues/290#issuecomment-815936718.

It uses a BlocProvider that registers an event when the app starts. Based on the state that results, the splash page routes the login page or the home page accordingly.

**Comment by herman-the-worm** [comment]
@alexgrusu Thanks

  I was able to figure out the new AuthGuard. Thanks for the reference

**Comment by theweiweiway** [comment]
Closing due to: 
- pretty good workarounds proposed
- and also, I just tried accessing context with `router.navigatorKey.currentContext` in version 2.2.0 and it works like a charm 🍡 !

**Comment by JankoLancer** [comment]
@herman-the-worm can u share your solution for new auth guard?

**Comment by herman-the-worm** [comment]
@JankoLancer 

Suggestions to improve this are welcome

We are planning to replace passing authbloc by adding a getIt statement instead

have not migrated this part yet

class AuthGuard extends AutoRouteGuard {
  late final AuthenticationBloc authBloc;
  StreamSubscription<AuthenticationState>? authBlocStateSubscription;
  static final String tokenKey = "name of the token key";

  AuthGuard({required this.authBloc});

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) async {
    authBlocStateSubscription = authBloc.stream.listen((state) async {
      if (authBloc.state.status == AuthenticationStatus.unknown ||
          state.status == AuthenticationStatus.unauthenticated) {
        SharedPreferences prefs = await SharedPreferences.getInstance();
        String token = '';
        if (kIsWeb) {
          var box = Hive.box('token');
          if (box.get(0) != null) {
            token = box.get(0);
          }
        } else {
          if (await FlutterSecureStorage().read(key: tokenKey) != null) {
            token = (await FlutterSecureStorage().read(key: tokenKey))!;
          }
        }
        if (token == '') {
          if (prefs.getString('intro') == null) {
            authBlocStateSubscription?.cancel();
            router.root.pushNamed('/intro');
          } else {
            authBlocStateSubscription?.cancel();
            router.root.pushNamed('/onboard');
          }
          authBlocStateSubscription?.cancel();
        }
      }

      if (state.status == AuthenticationStatus.authenticated) {
        print('going through to verifyGuard');
        authBlocStateSubscription?.cancel();
        resolver.next(true);
      }
    });
    resolver.next(true);
  }
}

**Comment by JankoLancer** [comment]
Thanks!
I share my solution because it might be useful to someone:
```
import 'dart:async';

import 'package:auto_route/auto_route.dart';
import 'package:landover/BLoCs/user_bloc.dart';
import 'package:landover/app_router.gr.dart';

class AuthGuard extends AutoRouteGuard {
  final UserBloc authBloc;
  StreamSubscription<AuthenticationStatus> authBlocStateSubscription;
  Completer comp;
  AuthenticationStatus lastStatus;

  AuthGuard({this.authBloc});

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    if (authBloc.user != null) {
      // If there is user already in auth bloc, resolve immediately
      resolver.next(true);
    } else {
      authBlocStateSubscription?.cancel();
      authBlocStateSubscription = authBloc.authStatus.listen((status) async {
        // Listen for user auth status changes
        // Purpose of completer is to prevent multiple pushes to router
        if (status == lastStatus) return;
        lastStatus = status;
        if (status != AuthenticationStatus.loggedIn) {
          // If user is not logged in, replace route with LoadingRoute
          comp = Completer();
          await router.replace(const LoadingRoute());
          comp.complete();
        } else {
          // When user is logged in, push HomeRoute and resolve navigation
          await comp?.future;
          await router.replaceAll(
            [const HomeRoute(), resolver.route.toPageRouteInfo()],
          );
          await authBlocStateSubscription?.cancel();
        }
      });
    }
  }
}
```
