### ISSUE TITLE
How to wrap specific pages with Bloc

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#296]
Hi Milad!

Is there a way a specific subset of pages with Bloc so that I don't have to provide the Bloc above all routes? For example, I only want to wrap `/sign_up` routes with the SignUpBloc like so: 

```
const authRouter = AutoRoute(
  path: 'auth',
  name: 'AuthFeature',
  page: EmptyRouterPage,
  children: [
    AutoRoute(path: '', page: AuthPage),
    AutoRoute(path: 'login', page: AuthLoginPage),
    AutoRoute(path: 'sign_up', page: AuthSignUpPage), // wrapped with SignUpBloc
    AutoRoute(path: 'sign_up/email', page: AuthSignUpEmailPage),  // wrapped with SignUpBloc
    AutoRoute(path: 'sign_up/password', page: AuthSignPasswordUpPage),  // wrapped with SignUpBloc
  ],
);
```

Thanks!

**Comment by Milad-Akarie** [comment]
@theweiweiway I've been giving this matter some though lately but I still can't figure out a proper way to do so.
You could at least wrap the auth section with your signup bloc, it's lazily created so it shouldn't be a problem I suppose.
Instead of using EmptyRouterPage create your own and have it implement AutoRouteWrapper.

```dart
class AuthRouterPage extends AutoRouter with AutoRouteWrapper {
  const AuthRouterPage({Key key}) : super(key: key);

  @override
  Widget wrappedRoute(BuildContext context) {
      // provide sign-up bloc here
     return BlocProvider(create: (_) => SignupBloc(), child: this);           
  }
}
```
use it 

```dart
const authRouter = AutoRoute(
  path: 'auth',
  name: 'AuthFeature',
  page: AuthRouterPage,
  children: [ // now all children are wrapped with signupBloc
    AutoRoute(path: '', page: AuthPage),
    AutoRoute(path: 'login', page: AuthLoginPage),
    AutoRoute(path: 'sign_up', page: AuthSignUpPage),
    AutoRoute(path: 'sign_up/email', page: AuthSignUpEmailPage), 
    AutoRoute(path: 'sign_up/password', page: AuthSignPasswordUpPage),
  ],
);
```

**Comment by theweiweiway** [comment]
Hey Milad, 

Actually, this solution works great. If I wanted to, I could make a a `signUpRouter` and use the wrapper like you described to provide the Bloc only to sign up routes.

But I think that's overkill. This method is sufficient for all my use-cases, thanks!
