### ISSUE TITLE
Conditionally rendering bottom navbar based on current route

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#298]
Hi Milad!

Sorry, another issue -

I'm trying to render bottom navbar based on the current route path (or name). 

```
bottomNavigationBar:  context.route.path == '/groups' ? buildBottomNavigationBar(tabsRouter) : null,
```

But printing `context.route.path` gives me nothing. printing `context.route.name` gives me `HomeRoute` no matter what tab I go to. I've tried `context.router.currentRoute?.path` as well but that returns nothing. 

`context.tabsRouter.currentRoute?.name` returns the correct tab, but it doesn't return the actual route path like I need. 

Thanks!

**Comment by Milad-Akarie** [comment]
Please share your router setup

**Comment by theweiweiway** [comment]
Hi Milad, here's my setup:
https://github.com/theweiweiway/auto_route_example

`/lib/pages/home_page.dart` has where I'm trying to conditionally render the bottom navbar

Thanks!

**Comment by Milad-Akarie** [comment]
@theweiweiway actually the builder will only be called when the active tab is changed, when you're pushing group/details you're actually using the inner router of the group feature so that's the one that rebuilds, i'm not sure if I should rebuild the parent when a child router rebuilds....

you could add your group/details route to the root so it covers the entire screen when it' pushed?
BTW root routes should always start with a forward slash '/'. 

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      usesTabsRouter: true,
      children: [
        // groupsRouter,
        AutoRoute(path: 'group', page: GroupsPage),
        accountRouter,
      ],
    ),
    AutoRoute(path: '/group/details', page: GroupsDetailsPage)
  ],
)
class $MainRouter {}
```

**Comment by theweiweiway** [comment]
Thanks for the reply and solution Milad

I understand what you are saying, but I don't really like that approach because all of my `groups` routes will need to be defined in the `MainRouter`. In larger projects, this file could potentially become overwhelming since other tabs would need to define each page as well. In order to remedy this, I tried doing:
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      usesTabsRouter: true,
      children: [
        // groupsRouter,
        AutoRoute(path: 'group', page: GroupsPage),
        accountRouter,
      ],
    ),
    groupsRouter, // do this instead of defining all groups pages in this one file
  ],
)
class $MainRouter {}
```

and my groups_router.dart is:
```
const groupsRouter = AutoRoute(
  path: 'groups',
  name: 'GroupsFeature',
  page: EmptyRouterPage,
  children: [
    AutoRoute(path: 'details', page: GroupsDetailsPage)
  ],
);

```

and home_page.dart is
```
// before
// routes: [GroupsFeature(), AccountFeature()],
// after
routes: [GroupsRoute(), AccountFeature()],
```

but I get 

```
VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [Root] Router can not navigate to details
#0      TreeEntry._resolveConfigOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:589:9)
#1      TreeEntry._push (package:auto_route/src/router/controller/routing_controller.dart:436:18)
#2      TreeEntry.push (package:auto_route/src/router/controller/routing_controller.dart:419:12)
#3      GroupsPage.build.<anonymous closure> (package:auto_route_example/pages/groups/groups_page.dart:15:32)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#9      BaseTapGestureRecog<…>
```

More importantly though,  I noticed that the console always prints the correct path  in the terminal, which looks like:`CurrentLocation: <correct path here>`
This **always** prints the correct path, and works even when i switch tabs or push new routes. Is there a way I can access that? Not only would it solve my problem with the bottom navigation bar, it would allow me to listen to the current page for Analytics purposes

Thanks Milad!

**Comment by theweiweiway** [comment]
Hey Milad, another things is that with the approach of moving all `groups` routes into the main router like so:
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      usesTabsRouter: true,
      children: [
        // groupsRouter,
        AutoRoute(path: 'group', page: GroupsPage),
        accountRouter,
      ],
    ),
    AutoRoute(path: '/group/details', page: GroupsDetailsPage)
    // all other AutoRoute group paths here
  ],
)
class $MainRouter {}
```

is that I can no longer use a `GroupsRouterWrapper` to wrap all `/groups` routes with a Bloc. I think it's a fairly common use case to wrap one whole tab like `/groups` tab with a Bloc (#296)

**Comment by Milad-Akarie** [comment]
The reason for the exception is probably using the wrong scooped router.
Try `router.root.push`

The forgotten print statement is called by root delegate, that's the path it should report back to the browser.

I haven't tried this yet but you could do something like

` var rootDelegate = RootRouterDelegate.of(context);
rootDelegate.addListener((){
     print(rootDelegate.currentConfigration)

})`
Excuse the mess, I'm on my phone.

**Comment by theweiweiway** [comment]
Thanks Milad, I finally got it working!

I kept my previous setup, and in `home_page.dart` i used your code snippet to listen to the current path. 

```
  String path = "";

  @override
  void didChangeDependencies() {
    var rootDelegate = RootRouterDelegate.of(context);
    rootDelegate.addListener(() {
      final newPath = rootDelegate.currentConfiguration.map((a) {
        if (a.path.isNotEmpty && !a.path.contains("/")) {
          return '/' + a.path;
        }
        return "";
      }).join("");
      setState(() {
        path = newPath;
      });
    });
    super.didChangeDependencies();
  }

...

   bottomNavigationBar: path == '/groups' || path == '/account'
              ? buildBottomNavigationBar(tabsRouter)
              : null,
```

This also allowed me to keep my router setup so that i can keep my `groups` and `account` tabs wrapped with a `BlocProvider` if I wanted to.

I still think that there should be an easier way to get the current path in a parallel navigator setup, since I can definitely see other use cases that rely on the current path - but this works great for now

Thanks again!
