### ISSUE TITLE
[Help wanted] Beta 1.0.0 - RemoveUntil / RemoveUntilRoot behavior

### ISSUE THREAD

**Issue by KhatibFX** [Milad-Akarie/auto_route_library#303]
Hi,

Before beta version 1.0.0, if I call showDialog() from a page, I can pop the dialog using 
```dart
ExtendedNavigator.root.popUntilPath(Routes.page);
```

With the new update, if I call showDialog() from a page, I can't find a similar functionality. calling 
```dart
AutoRouter.of(context).removeUntil((route) =>route.name == PageRoute.name);
```

Simply does nothing.

Could you help me understand how to do it properly?

Thanks!

**Comment by Milad-Akarie** [comment]
Hello @KhatibFX, 
if you just want to pop the dialog why don't you just call `AutoRouter.of(context).pop()`?
also make sure you're on the latest beta versions
https://pub.dev/packages/auto_route/versions/1.0.0-beta.5+1
https://pub.dev/packages/auto_route_generator/versions/1.0.0-beta.5

**Comment by KhatibFX** [comment]
Hi, @Milad-Akarie 
For my use case, the dialog may have been already popped by the user, and in that case, I don't want to pop him further into a previous page.

Moreover, I am on the latest auto_route: ^1.0.0-beta.5+1 version.

Thanks!

**Comment by Milad-Akarie** [comment]
@KhatibFX oh I see. 
The problem here is that AutoRouter only maintenance the stack of pages, a dialog is a pageless route,

You can use this method until I add an official method in next build. 

` Navigator.of(context).popUntil((route) => route.settings is AutoRoutePage);`

**Comment by BartusZak** [comment]
Hey @Milad-Akarie 

Any update on featue to close `showDialog` with `AutoRouter.of(context).pop()`?

It still does nothing on the latest `auto_route: ^1.0.0-beta.7` .

Example:
```dart
  void _onClick() {
    showDialog(
        context: context,
        builder: (BuildContext context) {
          return WillPopScope(
            onWillPop: () async => false,
            child: Center(
              child: CircularProgressIndicator(),
            ),
          );
        });
    Navigator.of(context).popUntil((route) => route.settings is AutoRoutePage); // works
    AutoRouter.of(context).pop(); // exception
  }
```

![image](https://user-images.githubusercontent.com/16143176/106583607-91e84800-6545-11eb-9229-9b90fa20600c.png)

**Comment by Milad-Akarie** [comment]
@BartusZak  is this still an issue in beta.9?

**Comment by BartusZak** [comment]
@Milad-Akarie Sorry, I won't be able to confirm that.

**Comment by theweiweiway** [comment]
closing due to
- possible solution provided

**Comment by mpiparo** [comment]
I'd like to re-open since the possible solution doesn't work for me because I am need to pass back data from the pop. 

Using:
Navigator.of(context).popUntil((route) => route.settings is AutoRoutePage)

pops and dismisses the dialog ok, but popUntil doesn't allow me to pass back any results from my alert dialog as I was doing with:
Navigator.of(context).pop(result);

unless anyone has thought of a work-around?

thanks.
