### ISSUE TITLE
Eta on a nullsafe version?

### ISSUE THREAD

**Issue by oliverfunk** [Milad-Akarie/auto_route_library#306]
I can't use `auto_route: 1.0.0-beta` in a nullsafe project of mine because one of the other packages uses `equatable: ^2.0.0-nullsafety` and this is using `equatable: ^1.0.0`.

When could we expect a nullsafe version of auto_route?

PS: Great package, thank you for your hard work!

**Comment by Milad-Akarie** [comment]
Hey @oliverfunk I can't really give an Eta but it's planned after docs, testing and the release version of 1.0.0

**Comment by theweiweiway** [comment]
Closing in favour of #340
