### ISSUE TITLE
Can't push separate router route that is not part of the parallel navigation setup

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#307]
Hi Milad!

I'm trying to push a `TestRoute()` and i noticed it only works if the `TestPage` is defined in the main_router as `AutoRoute(path: '/test', page: TestPage)` and not as it's own router. More code below:

```
@AdaptiveAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: HomePage,
      usesTabsRouter: true,
      children: [groupsRouter, accountRouter],
    ),
    // testRouter // this does NOT work
    AutoRoute(path: '/test', page: TestPage) // this works!
  ],
)
class $MainRouter {}
```

My testRouter:
```
const testRouter = AutoRoute(
  path: '/test', // also tried 'test'
  page: EmptyRouterPage,
  children: [
    AutoRoute(path: '', page: TestPage),
  ],
);
```

And i am navigating to it with:
`context.router.push(TestRoute());` 

I also tried `router.root`

The error I keep getting is:
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [GroupsFeature] Router can not navigate to
#0      BranchEntry._resolveConfigOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:563:9)
#1      BranchEntry._push (package:auto_route/src/router/controller/routing_controller.dart:410:18)
#2      BranchEntry.push (package:auto_route/src/router/controller/routing_controller.dart:393:12)
#3      _GroupsPageState.build.<anonymous closure> (package:auto_route_example/pages/groups/groups_page.dart:30:32)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#9      BaseTa<…>
```

I know I can just define each route by itself and not use a `testRouter`, but I like how this keeps things clean, especially in larger projects.

Thanks!

**Comment by Milad-Akarie** [comment]
Hey @theweiweiway you're trying to push the test router's child route to the root router that's why you're getting that error
Try. Try give the test router a name and push it instead... right now it's name is EmptyRouterRoute so if you push that it will work

**Comment by Milad-Akarie** [comment]
If your test router has only one child why have it create a separate router?
Const testRoute = AutoRoute(path: /test, page: TestPage);

**Comment by theweiweiway** [comment]
Thanks Milad,

My example is actually a simplified setup of my larger flutter app. I have several routes inside my "test" router, which is why I want to move the "test" routes into it's own router. 


I've given my route a name, `TestFeature`. My router is now:
```
const testRouter = AutoRoute(
  path: '/test',
  name: 'TestFeature',
  page: EmptyRouterPage,
  children: [
    AutoRoute(path: '', page: TestPage),
  ],
);
```

How exactly would I push it now? I just tried `context.router.push(TestRoute());` as well as `context.router.root.push(TestRoute())` but I still get an error: `Router can not navigate to /test`
```
Unhandled Exception: [GroupsFeature] Router can not navigate to /test
#0      BranchEntry._resolveConfigOrReportFailure (package:auto_route/src/router/controller/routing_controller.dart:563:9)
#1      BranchEntry._push (package:auto_route/src/router/controller/routing_controller.dart:410:18)
#2      BranchEntry.push (package:auto_route/src/router/controller/routing_controller.dart:393:12)
#3      _GroupsPageState.build.<anonymous closure> (package:auto_route_example/pages/groups/groups_page.dart:30:32)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#9      <…>
```
Thanks!

**Comment by theweiweiway** [comment]
Sorry - please ignore my last stupid comment. This works now:
`context.router.root.push(TestFeature());`

My question is now, how do I push a specific route within the `testRouter`? Because it seems like I'm pushing the router itself - not a specific page. If I have a setup like so: 

```
const testRouter = AutoRoute(
  path: '/test',
  name: 'TestFeature',
  page: EmptyRouterPage,
  children: [
    AutoRoute(path: '', page: TestPage),
    AutoRoute(path: 'details', page: TestDetailsPage),
  ],
);
```

How can i push the `TestDetailsRoute`? Do I have to push the `TestFeature` route **first**, and then push the `TestDetailsRoute` after? 

Thanks!

**Comment by Milad-Akarie** [comment]
If you're to navigate using paths you'd navigate to `/tes/details` not just details.. route objects have a similar behavior.
You'll notice that Test feature has a children property and that's how you use it.

`router.root.push(TestFeature(
           children: [TestDetailsRoute()]
      ))`

What do you think of this approach?

**Comment by theweiweiway** [comment]
Thanks for the explanation @Milad-Akarie, that all makes a lot of sense! Your solution works great, and I love how it's so easy to change routers and decide exactly which route want to push onto the router with the `children` parameter



> In the above example if we call AutoRouter.of(context) in the build method inside of UserPage it will get us the root controller but calling AutoRouter.of(context) inside of UserProfilePage for example, will get us the inner/nested controller of UserPage.

Everything is much clearer to me now. Thanks !!

**Comment by AscentionOne** [comment]
Hi, @Milad-Akarie and @theweiweiway this issue and answer help me a lot. I have the same issue currently and try to understand how the new Navigator 2.0 auto_rout work and a good way of managing large projects using the auto_rout package! I use the auto_route package since the Navigator 1.0 version and I like it a lot! Thanks a lot, @Milad-Akarie and keep up the good work! 😘👍 Hope to see more documentation of how the new auto_rout works!

**Comment by jesussangomez** [comment]
Hello I'm facing a similar issue, this is my AppRouter.

```dart
@MaterialAutoRouter(replaceInRouteName: 'Page,Route', routes: <AutoRoute>[
  AutoRoute(path: '/', page: LandingPage, initial: true),
  AutoRoute(path: '/dashboard', page: HomePage, children: [
    RedirectRoute(path: '', redirectTo: 'overview'),
    AutoRoute(path: 'overview', page: DashboardPage),
    AutoRoute(path: 'company', page: CompanyPage)
  ]),
])
class $AppRouter {}
```
The thing is that in my HomePage I have a drawer that is always visible and I just try to update the body according to the route. And it's working if I change the route on the URL, manually. But when I try to navigate is not working.

@Milad-Akarie, I used the method that you suggested. 

`router.root.push(TestFeature(children: [TestDetailsRoute()]))`

It works, but reloads all the HomePage and not only my body on that HomePage. Here is a gif of what is going on, at the end, I'm changing the route manually on the URL, and this is what I want to achieve by tapping my menus.

![20210409_010405](https://user-images.githubusercontent.com/913584/114140253-a6461980-98d5-11eb-92fa-dcb19d6d248c.gif)

Am I missing something?

**Comment by ricpar11** [comment]
> Hello I'm facing a similar issue, this is my AppRouter.
> 
> ```dart
> @MaterialAutoRouter(replaceInRouteName: 'Page,Route', routes: <AutoRoute>[
>   AutoRoute(path: '/', page: LandingPage, initial: true),
>   AutoRoute(path: '/dashboard', page: HomePage, children: [
>     RedirectRoute(path: '', redirectTo: 'overview'),
>     AutoRoute(path: 'overview', page: DashboardPage),
>     AutoRoute(path: 'company', page: CompanyPage)
>   ]),
> ])
> class $AppRouter {}
> ```
> 
> The thing is that in my HomePage I have a drawer that is always visible and I just try to update the body according to the route. And it's working if I change the route on the URL, manually. But when I try to navigate is not working.
> 
> @Milad-Akarie, I used the method that you suggested.
> 
> `router.root.push(TestFeature(children: [TestDetailsRoute()]))`
> 
> It works, but reloads all the HomePage and not only my body on that HomePage. Here is a gif of what is going on, at the end, I'm changing the route manually on the URL, and this is what I want to achieve by tapping my menus.
> 
> ![20210409_010405](https://user-images.githubusercontent.com/913584/114140253-a6461980-98d5-11eb-92fa-dcb19d6d248c.gif)
> 
> Am I missing something?

did you get any updates on this?

**Comment by Milad-Akarie** [comment]
Try navigate instead of pushing, because push will add a new route to your stack everytime, which can be bad for performance as well, navigate will ensure that a route can only exist once in the stack
Also, no need to navigate from root anymore, autoroute will find the right router wcop automatically router.navigate(TestFeatureRoute(childern..));
