### ISSUE TITLE
Application reloads after pressing browser back button

### ISSUE THREAD

**Issue by maxiundtesa** [Milad-Akarie/auto_route_library#309]
Hi,
I'm currently dealing with the issue that the application handles a press of the browser back completely differently than a press of the (automatically created) in-app back button.
Apparently the browser back button doesn't call something like Navigator.of(context).pop(), but instead navigates to the url before (like .pop() would do) and also reloads the whole application.
So every stateful widget is rebuild (initState() is getting called) and even worse: Also every provider/AppState is getting recreated. I understand that this is probably intended if the user reloads the browser page, but on a press of the back button?

This issue can be seen in these two videos, which demonstrate how the back button presses are handled by the app:

https://user-images.githubusercontent.com/17526240/103425595-8e167e00-4bb3-11eb-8cb5-5166a0d334aa.mp4

https://user-images.githubusercontent.com/17526240/103425709-86a3a480-4bb4-11eb-883b-886ce6ad007b.mp4

The example project to reproduce the issue: https://github.com/maxiundtesa/auto_route_example
In this example, the page with the list of books is a stateful widget, which gets recreated after the browser back button is pressed

**Comment by Milad-Akarie** [comment]
@maxiundtesa there's an issue indeed but still pressing the browser's back button is not supposed to mimic android's back button, it rebuilds the entire App with the new url, that's how the creator of router intended for it to work.
AutoRouter tries to update subtrees if possible else it re-pushes new routes

**Comment by maxiundtesa** [comment]
@Milad-Akarie Ok, so that is the intended functionality of the back button
I tried it with the new version and with that the back button doesnt work at all. The url changes, but the page doesnt.
Probably due to this error message: 
```
======== Exception caught by scheduler library =====================================================
The following IndexError was thrown during a scheduler callback:
RangeError (index): Index out of range: no indices are valid: 0

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7             _get]
packages/auto_route/src/router/controller/routing_controller.dart 222:42      get [_activePage]
packages/auto_route/src/router/controller/routing_controller.dart 226:22      get topMost
packages/auto_route/src/router/controller/routing_controller.dart 363:24      get topMost
...
====================================================================================================
```

**Comment by Milad-Akarie** [comment]
Could you share your router setup please?
Also I noticed that you're using a tabs router in a web App, I don't think tab routers are ideal in web Apps because it preserves all children state.

I've added a web example, please check.

**Comment by maxiundtesa** [comment]
@Milad-Akarie The router setup/whole app is identical with the example app, i only converted one widget to a stateful one for testing.
But you can find it here: https://github.com/maxiundtesa/auto_route_example
I know it's not ideal, but since I'm going to use it in the ios/android version of the app, it's easier to just have one navigation method for now. If everything works with it, I can focus on a more browser specific way for the navigation


Video of the bug:

https://user-images.githubusercontent.com/17526240/103564582-0d12fb80-4ebf-11eb-94df-e3d76f445a00.mp4

**Comment by Milad-Akarie** [comment]
@maxiundtesa Looks like a problem with the TabsRouter, I'll take a look.

**Comment by maxiundtesa** [comment]
@Milad-Akarie Thanks:) And the new web example is a much better way of handling navigation for the web, so definitely thanks for that. It's phenomenal that we can have a permanent base widget and still use routes with this package, so even something like a top navigation bar is possible

**Comment by maxiundtesa** [comment]
Fixed in newest version
