### ISSUE TITLE
MaterialRoute behaviour is wrong?

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/auto_route_library#314]
I just noticed that the animation for `MaterialRoute` is different on android and ios devices during `replace`.

on Android - the new screed appears from the bottom.
on ios - it appears from the right.

is it correct?
how can I force both platforms looks like android?

thank you.

**Comment by Milad-Akarie** [comment]
Hey @pro100svitlo AutoRoute uses the built-in material route as is, and that's actually how it's intended to work ( kind of adaptive).
try to play with these in your Material App theme 

```dart
ThemeData(
    pageTransitionsTheme: PageTransitionsTheme(builders: {
      TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
      TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
      TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
      TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
    }),
);

```

**Comment by pro100svitlo** [comment]
@Milad-Akarie thank you 🙏 

followed your advice: replaced 
```
      TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
```
with 
```
      TargetPlatform.iOS: FadeUpwardsPageTransitionsBuilder(),
```

works fine 👌 

p.s. thank you for an awesome library 🚀
