### ISSUE TITLE
AutoRoute context in dialog

### ISSUE THREAD

**Issue by oyvindsam** [Milad-Akarie/auto_route_library#317]
Hi, I am trying to use AutoRoute from a dialog, however get `AutoRouter operation requested with a context that does not include an AutoRouter.` error when calling any method on context.router. 

```
showDialog(
    context: context,
    builder: (context) {
      return AlertDialog(
        actions: [
          FlatButton(
            child: Text('Log in / register'),
            onPressed: () {
              context.router // <-- error
                  .push(SignUpViewRoute());
            },
          )
        ],
      );
    },
  );
```

Calling on context.router before showDialog() works fine. Any idea? Thanks

**Comment by ronymesquita** [comment]
I have get this error when used this library with [provider](https://pub.dev/packages/provider).
To fix this problem, was needed to use the `context` of `MaterialApp` as the child of `Provider`.

Example:
```dart
MaterialApp.router(
  routerDelegate: _applicationRouter.delegate(),
  routeInformationParser: _applicationRouter.defaultRouteParser(),
  builder: (_, routerWidget) => MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => Provider1()),
      Provider(create: (_) => Provider2()),
    ],
    child: routerWidget, // The context of the MaterialApp is used here
  )
```

The [example](https://github.com/Milad-Akarie/auto_route_library/tree/master/example) project also shows how to use the `context` of `MaterialApp` in [web_main.dart](https://github.com/Milad-Akarie/auto_route_library/blob/master/example/lib/web/web_main.dart):
```dart
MaterialApp.router(
  theme: ThemeData.dark(),
  routerDelegate: appRouter.delegate(),
  routeInformationParser: appRouter.defaultRouteParser(),
  builder: (_, router) {
    return Provider(
      create: (_) => BooksDB(),
      child: router,
    );
  },
);
```

**Comment by oyvindsam** [comment]
Hi @ronymesquita, I just found the reason for the error. showDilaog has a parameter `useRootNavigator` defaulting to true. From the docs: `TheuseRootNavigator argument is used to determine whether to push the dialog to the [Navigator] furthest from or nearest to the given context. By default, useRootNavigator is true and the dialog route created by this method is pushed to the root navigator. It can not benull`.` 

Setting it to false seems to work fine!
