### ISSUE TITLE
Push same page into different nested navigators (auto_route 2.0)

### ISSUE THREAD

**Issue by wwwdata** [Milad-Akarie/auto_route_library#318]
Thanks for your work on version 2.0  of this library! I am currently testing it out and wondering how I would achieve the following:

I am using the `usesTabsRouter` property and some `children` for my tabs. Which is (like in the example) `EmptyRouterPage`.

so for example:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  preferRelativeImports: false,
  routes: <AutoRoute>[
    AutoRoute<dynamic>(
      path: '/',
      page: DashboardPage,
      initial: true,
      usesTabsRouter: true,
      children: [
        homeTab,
        accountTab,
      ],
    ),
    AutoRoute<dynamic>(page: ProductPage),
  ],
)
class $AppRouter {}


const homeTab = AutoRoute<dynamic>(
  path: '',
  page: EmptyRouterPage,
  name: 'HomeTab',
  children: [
    RedirectRoute(path: '', redirectTo: 'home'),
    AutoRoute<dynamic>(path: 'home', page: HomePage),
  ],
);
```

I am now wondering: Is it only possible to now push `children` of the `HomeTab`? I would like to be able to push the same page (`ProductPage`) inside multiple different children routers. When I register the `AutoRoute` on the top navigator and try to push it from inside a tab, I just get an exception that the router cannot navigate to my page. Putting it into multiple `children` arrays throws an error when running `build_runner` that the same name was used twice.

**Comment by theweiweiway** [comment]
Hi @wwwdata,

I think it should work if you do `context.router.root.push(ProductRoute)` - the key is the **root** because you've defined that route in the main root navigator

Simply calling `context.router.push` will select the navigator you are currently in, which is probably the `homeTab` and the `ProductPage` does not exist in that navigator

**Comment by wwwdata** [comment]
But then it is pushed on top of the tab. I want to be able to push it inside multiple different tab routers. I think this is a common use case for apps.

**Comment by Milad-Akarie** [comment]
Try assiging a custom name to your duplicated route.

**Comment by wwwdata** [comment]
> Try assiging a custom name to your duplicated route.

Hi, yes that would "work". But the problem here is that I then have the same page with 2 different Route names. So depending on which tab I am currently in, I need to use a different Route class to push it.

Is it going to be a planned feature that it is possible to push the same generated `PageRouteInfo` inside different nested routers? In a typical e-commerce app it is for example quite common to for example have a home screen where products are teased, and you can open them within the tab of the home screen. And then you will also have the product page linked from a search tab for example and you can open the product page within that tab after pressing on a search result. It would be quite complicated to always be aware of in which tab you are pushing something from.

**Comment by Milad-Akarie** [comment]
@wwwdata Deep-linking would be rather hard without scoped children, I also find this annoying and  I'm trying to think of ways to separate linking from other navigation logic.

**Comment by theweiweiway** [comment]
Hey @wwwdata 

```
In a typical e-commerce app it is for example quite common to for example have a home screen where products are teased, and you can open them within the tab of the home screen. And then you will also have the product page linked from a search tab for example and you can open the product page within that tab after pressing on a search result. It would be quite complicated to always be aware of in which tab you are pushing something from.
```

I have this kind of use case and i agree that it is a very common use case to have shared pages between stacks - not just in e-commerce but many kinds of app with tabs. 

But everything I need is achievable by pushing the the page from root. In your example you have a `Home` and `Search` tab. These tabs cover their own domains. Now, the `ProductPage` covers it's own domain as well - it handles everything to do with a single product. 

Wouldn't it make sense to have this `ProductPage` or group of product pages as it's own router, and push them ontop of the tabs when you need it from the `root`? This intuitively makes sense to me. What specific advantages are you trying to get by having this product page in each tab?

**Comment by wwwdata** [comment]
Hi. The advantage would be that the user can then still switch the tabs while keeping the navigation stack inside a tab alive. This allows for "multi tasking"

**Comment by akago-dev** [comment]
Any updates on this issue ? We have the same problem, multiple shared pages across tabs, and duplicate every route is not really clean.

**Comment by theweiweiway** [comment]
Is this still a problem in 2.2.x?

**Comment by 0ttik** [comment]
> Is this still a problem in 2.2.x?

I think so as I'm getting: `Duplicate route names must have the same path!` when trying to push same page to different routes and, when I change names of the duplicate routes, there is no error.

**Comment by The-Redhat** [comment]
Is there an update to this issue? Or this there a recommended solution?

**Comment by IBugraGezer** [comment]
I have the same problem

**Comment by tstarasinic** [comment]
Any solution for this ? I also have 4 tabs, and every page in the app can be opened in every tab. So having different names for routes in every  tab is basically  impossible, because pages are link all the way and since I can go from "club page" to "group of that club"  on main tab and same in groups page and ... So knowing for every page on what tab you are and then redirect to proper path name means every time a navigate would  have to use some os if() or switch() or even method() where I check tabs in than redirect to proper page. This is frankly totally stupid to do.

**Comment by Milad-Akarie** [comment]
@tstarasinic do you pages share the same path everywhere?

**Comment by tstarasinic** [comment]
Yes, that was the idea. I created a list of routes and added it to every tab route list, so in that way it should be the same. But then a had a problem that if I navigated to a specific page "mygroups/group/3/post/10" the back button only navigated back to "mygroups/group/3". It never navigated all the way back to tab page - includePrefixMatches: true. But this only happens  when opening push notifications and navigating to that path and not visiting the "/mygroups" tab before
```
AutoRoute(path: 'mygroups', name: 'MyGroupsTabRoute', page: EmptyRouterPage, children: [...routerChildren, AutoRoute(path: '', page: MyGroupsPage)]),

const List<AutoRoute<dynamic>> routerChildren = [
  AutoRoute(path: 'group/:groupId', page: GroupPage),
  AutoRoute(path: 'group/:groupId/posts/:postId', page: post.PostGroupPage),
  AutoRoute(path: 'group/:groupId/join-request', page: PendingRequestsPage),
]
```
But if I tried to it like that:
```
const List<AutoRoute<dynamic>> routerGroupChildren = [
  AutoRoute(path: 'mygroups/group/:groupId', page: GroupPage),
  AutoRoute(path: 'mygroups/group/:groupId/posts/:postId', page: post.PostGroupPage),
  AutoRoute(path: 'mygroups/group/:groupId/join-request', page: PendingRequestsPage),
]
```
and add this list to mygroups tab. Then back button worked ok for that tab, but when doing the same for every other tab. _Duplicate route names must have the same path!_ message is displayed.

**Comment by ariefwijaya** [comment]
@tstarasinic You must custom route name to avoid duplicate route class name
