### ISSUE TITLE
Don't generate empty _guardedRoutes because it causes "isn't used" warning.

### ISSUE THREAD

**Issue by slavap** [Milad-Akarie/auto_route_library#32]
static const _guardedRoutes = const {};

![image](https://user-images.githubusercontent.com/4129763/75217812-fce1aa00-574c-11ea-818a-5792ce18f843.png)

**Comment by Milad-Akarie** [comment]
Hey @slavap noted.

**Comment by Milad-Akarie** [comment]
Fixed in v0.3.1
Thanks for reporting.
