### ISSUE TITLE
[Feature] Extension methods

### ISSUE THREAD

**Issue by arcas0803** [Milad-Akarie/auto_route_library#320]
In the extension part of the library, only generate push methods.
Is it possible to add popandpush method  and the ability to pass a result to previous route?

**Comment by Milad-Akarie** [comment]
@arcas0803 Using the new Approach pushing a route looks like this

`router.push(HomeScreenRoute)`
meaning there's no need for extension methods anymore. 
did I get your question right?

**Comment by theweiweiway** [comment]
Closing due to:
- stale issue
