### ISSUE TITLE
Page return value proposal

### ISSUE THREAD

**Issue by DevNico** [Milad-Akarie/auto_route_library#322]
It would be great to have the ability to specify Page return values. Let's say I have a page to scan QR-Codes and I want to use that page all across my application. I would like to specify this page to have e.g. a String as the return type of this page for the QR-Code content. So in my scanning page I would have something like `context.router.pop(qrCode);` and when opening the page I would like to do: `final qrCode = await router.context.push(QrCodeRoute());`.

This is just a proposal for either a replacement for the current approach in the doc with the Function that's called before the page pop but I think this would be much cleaner and would align more with how most people are used to do it with the old Flutter Navigator v1.

Please let me know what you think!

**Comment by Milad-Akarie** [comment]
@DevNico We replaced awaiting return values for callback functions to move closer to the new declarative approach

try this 
```dart
router.context.push(QrCodeRoute(
  onScanComplete(value){
 // do stuff with the result    
  }
));
where `onScaneComplete` is parameter callback function inside of your QrCodePage

```

**Comment by DevNico** [comment]
Alright if that's your design decision fair enough. I was just more used to awaiting return values but sure this works too. Thanks!
