### ISSUE TITLE
Migrate to Null Safety 

### ISSUE THREAD

**Issue by jamesblasco** [Milad-Akarie/auto_route_library#323]
I would like to know if there are plans to migrate to null safety in the short future. 

Currently,  null safety is available in flutter only for beta, dev, and master channels and has not been released to stable yet. But It would be interesting to start planning the migration.

The Flutter team is encouraging package's owners to do the migration so they are available for when they release the version with null safety in the upcoming months :)

https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

**Comment by DevNico** [comment]
Any timeline on this? A pre-release version with null safety would be great.

**Comment by arsamme** [comment]
Now null safety is stable and would you please say when auto-route will move to null-safety version?

**Comment by theweiweiway** [comment]
Closing in favour of #340
