### ISSUE TITLE
Easing on page transitions

### ISSUE THREAD

**Issue by FickleLife** [Milad-Akarie/auto_route_library#324]
I have a page successfully transitioning with `CustomRoute(page: LoginSignupView, name: "loginSignupViewRoute", transitionsBuilder: TransitionsBuilders.slideBottom),`, however the transition is linear. Is it possible to apply some sort of easing, like the standard back/forward left/right transitions have?

**Comment by Milad-Akarie** [comment]
@FickleLife  it's possible to use your own transitions builder function and do what you please with the animation.
