### ISSUE TITLE
bug in default arguments for pages

### ISSUE THREAD

**Issue by HosseinYousefi** [Milad-Akarie/auto_route_library#325]
When I have something like 

```dart
class A {
  Parameter p;
  const A({
    @required this.p,
  });
}
```
auto_routes correctly generates the code to handle this.

However if I add a default argument to p like:

```dart
class A {
  Parameter p;
  const A({
    this.p = const DefaultValue(),
  });
}
```

it imports the DefaultValue from a package as some _ix like `import 'default_value.dart' as _i5`.
but then when using the default argument, it doesn't use the _i5 prefix.

so instead of `route.initialHabitType ?? const _i5.DefaultValue()` it generates: `route.initialHabitType ?? const DefaultValue()`.

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
