### ISSUE TITLE
pushAndRemoveUntil doesn't work as expected.

### ISSUE THREAD

**Issue by subinsv** [Milad-Akarie/auto_route_library#326]
AutoRoute: beta 7

Requirement:
* Remove all pages from backstack and push a new page

I pushed page1 into stack. 

Now I tried 

Flow 1:
```
            router.pushAndRemoveUntil(
              Page2Route(),
              predicate: (val) => false,
            );
```
* Page1 was still in backstack.

Flow 2:
```
  router.pushAndRemoveUntil(
              Page2Route(),
              predicate: (val) => true,
            );
```
* Page1 was still in backstack.

This seems to work with default navigator

```
            Navigator.popUntil(context, (route) {
              return false;
            });
```
* Page1 was removed.

**Comment by aytunch** [comment]
@subinsv Did you find a solution yet? I am having trouble making `popUntil()` work

**Comment by subinsv** [comment]
@aytunch as of now I am using the default navigator for popuntil operation alone as an workaround.

**Comment by Milad-Akarie** [comment]
@subinsv I'll look into it..
try `replaceAll([])`

**Comment by subinsv** [comment]
Thanks @Milad-Akarie .
This issue seems to be resolved in latest beta version.

**Comment by BartusZak** [comment]
Confirmed. 
It works as expected in `auto_route: ^1.0.0-beta.9`

```dart
AutoRouter.of(context).pushAndRemoveUntil(RoomRoute(roomId: 'main'),
        predicate: (val) => false);
```
