### ISSUE TITLE
Customize Unknown Route Page

### ISSUE THREAD

**Issue by skybur** [Milad-Akarie/auto_route_library#33]
Hi there, thanks for this awesome package ❤️ 

Is it possible to customize the page when an unknown route is pushed? Or maybe provide the unknown page ourselves? The current unknown page is kinda scary IMHO haha.

**Comment by Milad-Akarie** [comment]
@skybur lol, That's a good idea, I'll see what I can do.

**Comment by Milad-Akarie** [comment]
Added in v0.3.1.
just annotate your customUnknownRoute with @unknownRoute and make sure your customUnknownRoute has a default constructor that takes in a positional String.
Thanks for your efforts.
