### ISSUE TITLE
Does this package support middleware?

### ISSUE THREAD

**Issue by eliezerp3** [Milad-Akarie/auto_route_library#330]
Just wanted to start with a massive thank you to Milad Akarie for this package. Really makes things much easier.

Is there an easy way to create custom middleware that will be called before attempting to access specific routes [make sure is authenticated/is admin]? Thank you.

**Comment by Milad-Akarie** [comment]
Hey @eliezerp3 Thanks for the support. 
you could use an `AutoRouteGuard`, extend your own and implement your login, check this example for reference. 
https://github.com/Milad-Akarie/auto_route_library/blob/master/example/lib/mobile/router/auth_guard.dart
then use it on routes
`AutoRoute(page: MyPage, guards: [MyGuard],)`

**Comment by eliezerp3** [comment]
Thanks man! And just is there an eta on a stable version 1.0? (You can close this after answer).

**Comment by theweiweiway** [comment]
Closing issue due to:
- possible solution
- stale issue
