### ISSUE TITLE
pop() doesn't work

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/auto_route_library#331]
For some reason, when I run `AutoRouter.of(context).pop()` on a certain screen, it doesn't work. However, when I run `Navigator.of(context).pop()` it works. What is something that auto_route does differently from Navigator that would make it not work? I'm not sure how to make this bug reproducable. I'm using `AutoRouter.of(context).push()` to add the route to the stack, but only the native `Navigator#pop` can remove it.

**Comment by Milad-Akarie** [comment]
@Reprevise The only difference is that AutoRouter().pop() calls mayPop on the navigator, but this shouldn't be a problem unless you're trying to pop the last route in the stack?

**Comment by Reprevise** [comment]
Nope, there is one more route "behind" that one.

**Comment by Milad-Akarie** [comment]
@Reprevise could try calling mayPop on the navigator see if it has the same behavior?

**Comment by Reprevise** [comment]
@Milad-Akarie Ah, so `maybePop` doesn't pop it either. I figured out that the parent widget has a `WillPopScope` widget built-in but I set the `onWillPop` callback to always return true. Why would `maybePop` block it?

**Comment by mohammadne** [comment]
same for me by having `WillPopScope`:

```
        final navigatorState = AutoRouter.of(context).navigatorKey;
        await navigatorState.currentState?.maybePop();

        return Future.value(false);
```

**Comment by theweiweiway** [comment]
Is this still a problem in AutoRotue 2.x?

**Comment by wiztensai** [comment]
> same for me by having `WillPopScope`:
> 
> ```
>         final navigatorState = AutoRouter.of(context).navigatorKey;
>         await navigatorState.currentState?.maybePop();
> 
>         return Future.value(false);
> ```

i think you can use router.popForced();
