### ISSUE TITLE
Using auto_route with get

### ISSUE THREAD

**Issue by FilledStacks** [Milad-Akarie/auto_route_library#334]
I've been using auto_route together with get and a services setup to make navigation available in the my ViewModels which house my business logic. With the new pre-release I can't add a navigation key to the Material app. Is there any way that we can still supply a navigation key when using your package. I was only using it to generate the onGenerateRoute function along with the page parameters and the route names. 

Does that functionality still exist? If not I'll most likely clone at 0.6.6 and recommend using that through my channel given the setup is so effortless and works pretty well.

**Comment by Milad-Akarie** [comment]
Hey Dane, I can add a navigator key to the delegate constructor but you'll still need to push route objects instead of string paths, Couldn't you use the Generated router as a service? it's meant to be injectable.

**Comment by FilledStacks** [comment]
@Milad-Akarie The router can't be used like the navigation service. My package stacked_services provides navigation service, dialog service, snackbar service and a bottom sheet service. They use Get, which requires the key to be set. So it won't work using only your router. 

I get that you want to add functionality which is why I would rather make my own fork to keep it at the current version / functionality because of how much easier it made my code for me. I just wanted to check with you in case I might have missed anything from the generated code. 

Thanks for your response. I'll probably get your old generator code and make a package with that if you're fine with that? I could write my own but I would prefer not to.

**Comment by Milad-Akarie** [comment]
@FilledStacks I don't mind at all, The old generator does not use the CodeBuilder library so it's a little messy, maybe try to switch to that?

**Comment by FilledStacks** [comment]
@Milad-Akarie I'll check the code when I get there. I really appreciate you allowing me to build off it. I'm going to move it into the [stacked](https://pub.dev/packages/stacked) packages as the stacked_router and will build it into the initial version of the stacked_application package that will wrap all this setup for the user neatly.

Much appreciated again. Good luck with the new direction of the package.
