### ISSUE TITLE
Nest declarative routers not working

### ISSUE THREAD

**Issue by Nolence** [Milad-Akarie/auto_route_library#337]
Hi!

I'm trying to have declarative routing in my app that looks like this:

```dart
@AdaptiveAutoRouter(
  replaceInRouteName: 'Page',
  routes: <AutoRoute>[
    AutoRoute(
      page: AppWrapper,
      path: '/',
      children: [
        AutoRoute(
          path: 'auth',
          page: AuthPage,
        ),
        AutoRoute(
          page: SubscriptionWrapper,
          initial: false,
          path: 'app',
          children: [
            AutoRoute(
              path: 'home',
              page: HomePage,
            ),
            AutoRoute(
              path: 'subscribe',
              page: SubscribePage,
            ),
          ],
        ),
      ],
    ),
  ],
)
class $Router {}
```

If they're not authed I'll send them to `AuthPage`. If they are they'll go to the SubscriptionWrapper which either sends them to `home` or `subscribe` depending on whether they are subscribed or not.

Both `Wrapper` routes implement `AutoRouterWrapper`. Here is my `AppRouter` for example:

```dart
class AppWrapper extends HookWidget implements AutoRouteWrapper {
  @override
  Widget wrappedRoute(BuildContext context) {
    return this;
  }

  @override
  Widget build(BuildContext context) {
    final asyncUser = useProvider(userProvider);

    return AutoRouter.declarative(
      onGenerateRoutes: (BuildContext context, List<PageRouteInfo> routes) {
        return [
          asyncUser.when(
            data: (user) {
              if (user == null) return AuthPageRoute();

              return SubscriptionWrapperRoute();
            },
            error: (error, stackTrace) => SplashPageRoute(
              error: error,
              stackTrace: stackTrace,
            ),
            loading: () => SplashPageRoute(),
          ),
        ];
      },
    );
  }
}
```

This all works and the user is guided through the stages of loading, auth and subscription. However, it doesn't look like the context is being updated with the current router. Once I'm at `HomePage` if I try to push a route to anywhere I get this:

```
Unhandled Exception: [Root] Router can not navigate to profile
```

And I checked and I really still am on the root router instead of the `SubscriptionWrapper` Router that I'd expect. Is there anything special I have to do in order to update the current routers?

Thanks!

**Comment by Milad-Akarie** [comment]
Hey @Nolence  to make this simple, every time you open an array you're creating a branch (router/controller).
@AdaptiveAutoRouter(
  replaceInRouteName: 'Page',
  routes: <AutoRoute>[ // this is root router
    AutoRoute(
      page: AppWrapper,
      path: '/',
      children: [ // this's a nested router 
        AutoRoute(
          path: 'auth',
          page: AuthPage,
        ),
        AutoRoute(
          page: SubscriptionWrapper,
          initial: false,
          path: 'app',
          children: [ // this's a nested router
            AutoRoute(
              path: 'home',
              page: HomePage,
            ),
            AutoRoute(
              path: 'subscribe',
              page: SubscribePage,
            ),
          ],
        ),
      ],
    ),
  ],
)
class $Router {}

**Comment by Nolence** [comment]
Sorry my thought process was that by using `AutoRouter.declarative` that would also pass along which `router`/`controller` it belonged to. Is this not correct?

For example, if I returned `SubscriptionWrapperRoute ` from `AppWrapper`  then those children routes would all have the context and router of the `SubscriptionWrapper` and not the root router still.

I guess my question is really how is the `router`/`controller` supposed to be updated then when using `declarative` router to return other nested Routers? Or am I just thinking about this in the wrong way?

Thank you for the help

**Comment by theweiweiway** [comment]
Hey @Nolence ,

It really sounds like your use-case is best served through a Guard. You can use an AuthGuard and a SubscriptionGuard. In both Guards, you could push a new router to the root controller if the user isn't logged in or subscribed.

As an aside, I typically only use declarative routers if they are part of a flow. Like a sign up flow or subscribe flow. Here, I hook up the declarative router to a state management solution and take care of my routes via state.

 In other use-cases, it usually feels right to use a regular router/controller.

**Comment by Milad-Akarie** [comment]
@Nolence Declarative routers don't expose their controller meaning you can not obtain the controller using AutoRouter.of(context) witch should make sense because you can not be adding routes to the stack declaratively then push some routes in an  imperative way.

I find What @theweiweiway suggested a more neat approach to this.

**Comment by Nolence** [comment]
Although I can imagine Guards would work, it would be nice if the declarative router was smart enough to push the necessary routes/breadcrumbs in my place as well as expose and delegate routing responsibility to the child's controller. Fully imperative doesn't make sense to me. I only want the auth to be declarative and the internal routes should be guided by user's clicking on buttons to navigate.

Having a fully declarative approach for a real app would be ugly wouldn't it? It would need things like `isOnSettingsPage`, `isOnProfilePage` rather than just pushing the individual routes which is intuitive

**Comment by Milad-Akarie** [comment]
@Nolence Nested routers are handled separately meaning you could have a declarative router inside of an imperative router and vice versa.
Parent routers  pass prematched routes to their children, and they're handled internally inside of imperative routers, declarative routers get their prematched routes inside of the onGenerateRoutes callback where yiu can include them in your declared stack.

**Comment by Nolence** [comment]
Oh ! took me a while. But it finally sank in haha. My mistake was not clearly separating the roles of the two routers in my head. As I understand now, declarative routers should just return imperative routers if you want to move manually. I always seemed to miss this step.

**Comment by AcodeWang** [comment]
I add a question maybe relevant. How could I get the child router from another branch of routes. For Example I got PageA and PageB and 2 child page for each. From Page A, I know we could navigate to Page B by `context.router.parent().root.navigate(PageBRoute())`. My question : Is it possible navigate directly to PageBChild2Route from PageA?

**Comment by AcodeWang** [comment]
Ok I just found the solution in another issue. #307 . The right way to navigate nested router should be `.navigate(PageBRouter(children: [PageBChild2Route()]))`. Wait for more the documentation for v1. Thanks again for the package.
