### ISSUE TITLE
Better error reporting for routes not found

### ISSUE THREAD

**Issue by Nolence** [Milad-Akarie/auto_route_library#338]
Hi!

I've found one of the main pain points in trying to understand what I was doing wrong was the error reporting. I'd think it would be great if the current

```dart
throw FlutterError("[${toString()}] Router can not navigate to ${route.fullPath}");
```
was also accompanied with a representation of the router tree and from which point the user was trying to navigate from. I quickly ported `treeify` to dart and published it [here](https://pub.dev/packages/treeify) but I could image this library could have a very similar thing that even adds colors or other configuration such as what routes are guarded, where the user is pushing from or anything else.

```
├─ AuthPage
│  ├─ LoadingPage
│  └─ HomePage
│     └─ TabsRouter
│        ├─ CoursePage
│        ├─ StatsPage
│        └─ ProfilePage
└─ *
   └─ NotFoundPage
```

I could maybe offer a PR but I'm very skeptical I'll get it done right away.

Thanks for library!

**Comment by Milad-Akarie** [comment]
@Nolence  Sweeet! I love this.
