### ISSUE TITLE
Help for AutoWrappedRoutes with flutter_bloc

### ISSUE THREAD

**Issue by charm-cloud** [Milad-Akarie/auto_route_library#339]
Hi , 
I am using version .6.9

I want to pass flutter_bloc ,between two pages(BlocProvider.value).The Two pages are not in same navigator (so https://github.com/Milad-Akarie/auto_route_library/issues/296  approach cannot be used).Also i cannot make it a top level bloc ,i.e above the Material App.Also need to access the bloc's value in init state , so cant directly pass the bloc's value in the next page's argument and access via constructor 

Thank You

**Comment by Milad-Akarie** [comment]
Hey @charm-cloud  how about passing the bloc via constructor then providing it as a value inside of wrappedRoute getter?

**Comment by charm-cloud** [comment]
Thank you so much !!!, it worked well
