### ISSUE TITLE
Migrating auto_route_library to null safety?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/auto_route_library#340]
I use auto_route_library in my app and it is one of the major null safety migration blocker. We had appreciate if you could migrate the package to null safety.

**Comment by Milad-Akarie** [comment]
@ganeshrvel  the next build will generate a null safety aware code and soon the whole package will be migrated.

**Comment by DevNico** [comment]
This is the third issue about null safety as far as I can tell (see #323 and #306). Can you give a more specific timeline on when  a null safe version will be ready or give info about potential blockers so we (the users of this awesome library 😄) know what to expect?

**Comment by essarn** [comment]
@Milad-Akarie 

Not to rush anything but is there an eta on when the package is migrated?
Auto route is the only package left to be migrated off my dependencies.

**Comment by maxzod** [comment]
@essarn  same as you !
after yesterday event  flutter && dart null safety is stable and we need to migrate ASAP

**Comment by jordyvandomselaar** [comment]
If you could provide us with some pointers, I'd love to help with the migration!

**Comment by Milad-Akarie** [comment]
@maxzod @jordyvandomselaar  I'm on it. please have some patience.

**Comment by jordyvandomselaar** [comment]
@Milad-Akarie It's alright =), I did not intend to rush you or anything, just offering my help!

**Comment by Milad-Akarie** [comment]
@jordyvandomselaar  I appreciate it. it's honestly taking longer than I thought with legacy generator support and everything.

**Comment by Milad-Akarie** [comment]
auto_route: 1.0.0 is finally out, I apologize for the delay but there were a lot of issues to be resolved and some required refactoring.

**Comment by CassiusPacheco** [comment]
@Milad-Akarie No apologies needed! You've dedicated so much time to this, we're the ones thanking you! Great work, will try it straight away 👏

**Comment by masseelch** [comment]
Dayum! I love this man! Great Work, very much appreciated. Can one buy you a coffee somewhere? This awesome work has to be appreciated.

**Comment by ganeshrvel** [comment]
I use at least 3 packages, that you have authored.

Please add your BuyMeACoffee url in the ReadMe. I am sure that many like me would like to buy you some coffees. Please update the donation link here as well once you set it up. Looking forward to it.

Thanks a lot for your packages.

**Comment by Milad-Akarie** [comment]
@masseelch @ganeshrvel  @CassiusPacheco  That makes me really happy you guys. I've always used open source libs/tools and it feels really good to give back. 

I'm having trouble connecting ByMeCoffee or any similar service to a payment gateway as neither PayPal or Stripe are support my country (Libya), the same thing goes for Github sponsors. 

for now the only service that seems like it might work for me is Patreon but I'm not sure if developers like that one?

**Comment by CassiusPacheco** [comment]
Whatever works for you. I’m happy to contribute a bit back to you for your amazing work!

**Comment by nguyenxndaidev** [comment]
> I'm having trouble connecting ByMeCoffee or any similar service to a payment gateway as neither PayPal or Stripe are support my country (Libya), the same thing goes for Github sponsors.

Sure that we can by you a coffee if Patreon works.
But I think it's not a long term solution because many developers don't have it.
Nearly everyone has PayPal account I guess. Other services are very rarely use.
