### ISSUE TITLE
Routes for optional path parameters

### ISSUE THREAD

**Issue by Grooviz** [Milad-Akarie/auto_route_library#341]
When I define a route with an optional path parameter:

```
@CustomAutoRouter(
  generateNavigationHelperExtension: true,
  routes: <AutoRoute>[
    [...]
    AutoRoute(path: '/data-page/:dataUid?', page: DataPage),
    [...]
  ],
)
class $AppRouter {}
```

The generated `Routes` class is:
```
class Routes {
  [...]
  static String dataPage({dynamic dataUid = ''}) => '/data-page/$dataUid';
  [...]
  static const all = <String>{
    [...]
    _dataPage,
    [...]
  };
}
```
### Issue 1

If I call `Routes.dataPage()`, I get the route `/data-page/` instead of `/data-page`.
This results in a `Route-name /data-page/? is not found!` error.

### Issue 2

Shouldn't a helper method be generated for the routes with optional parameters?

```
Future<dynamic> pushDataPage({String dataUid = ''}) => push<dynamic>(Routes.dataPage(dataUid));
```

**Comment by Milad-Akarie** [comment]
@Grooviz The new auto_route does not support optional path parameters as it turned out to be a bad practice, if you're dealing with an optional parameters use query params instead of path params.

**Comment by theweiweiway** [comment]
closing due to solution provided and stale issue
