### ISSUE TITLE
Reset Tab State

### ISSUE THREAD

**Issue by jacobia21** [Milad-Akarie/auto_route_library#343]
Hi, I have set up my tabs router and it works properly with a bottom navigation bar. Now I would like to add the ability to reset an individual tab's state to the first page if the user clicks on the bottom nav item of the page they are already in. For example I have the HomeTab which has the Home Page and a  few children routes. Would it be possible to pop back to the Home Page when the Home button is clicked?

**Comment by Milad-Akarie** [comment]
Hey @jacobia21 Did you try doing that inside of a willPopScope?

**Comment by jacobia21** [comment]
Hi @Milad-Akarie not exactly sure how I would implement it with a WillPopScope. Currently I have this AutoTabsRouter ```
```dart
AutoTabsRouter(
      routes: const [
        HomeTab(),
        LeadershipTab(),
        ProjectTab(),
        CalendarTab(),
      ],
      builder: (context, child, animation) {
        final tabsRouter = context.tabsRouter;
        return Scaffold(
          body: FadeTransition(
            opacity: animation,
            child: child,
          ),
          bottomNavigationBar: buildBottomNav(context, tabsRouter),
        );
      },
    );
  }
```

with the following BottomNav being built:

```dart
BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (index) {
        tabsRouter.setActiveIndex(index);
      },
      items: [...],
)
```

I tried implementing something in the onTap function of the BottomNavBar to handle resetting the tab like this, but I wasn't sure of how the logic should be implemented.

```dart
BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (index) {
        if (tabsRouter.activeIndex == index) {
          // pop to first page in current tab
        }
        tabsRouter.setActiveIndex(index);
      },
      items: [...],
)
```

**Comment by Milad-Akarie** [comment]
@jacobia21 I misunderstood your question at first, I thought you needed to go back to the home tab when back button is pressed. 
any ways

in general you can access inner routers by calling `innerRouterOf<T>(Route.name)` on the current router so your code should look something like this
` tabsRouter.innerRouterOf<StackRouter>(BooksTab.name).popUntilRoot();`
but as I was testing it just now I found a bug where innerRouterOf returns null at times and I fixed it 
in  `auto_route: 1.0.0-beta.9`
https://pub.dev/packages/auto_route/versions/1.0.0-beta.9 
so make sure you update to that
also seeing your use case I had to add a helper function to get inner stack routers by index to make things easier. 

```dart
  onTap: (index) {
        if (tabsRouter.activeIndex == index) {
         // stackRouterOfIndex will return null if entry at index is not a StackRouter
          tabsRouter.stackRouterOfIndex(index)?.popUntilRoot();
        } else {
          tabsRouter.setActiveIndex(index);
        }
      },
```

**Comment by jacobia21** [comment]
This works perfectly! Thanks so much @Milad-Akarie

**Comment by RicardoRB** [comment]
I tried as you described here @Milad-Akarie, but it didn't work. This is the workaround that I found out:

```dart
 List<AutoRoutePage> stack =
    AutoRouter.of(context).topMost.stack;
if (stack.length > 1 &&
    AutoTabsRouter.of(context).activeIndex == 0) {
  while (stack.length > 1) {
    await AutoTabsRouter.of(context).topMost.pop();
    stack = AutoRouter.of(context).topMost.stack;
  }
} else {
  AutoTabsRouter.of(context).setActiveIndex(0);
}
```
