### ISSUE TITLE
CustomRoute - unable to define two different animations for the same screen

### ISSUE THREAD

**Issue by vasilich6107** [Milad-Akarie/auto_route_library#344]
Hi. Thanks for the library.

I'm trying to make two different custom routes on the same page that differs with transition.

Currently page map consists of types as keys. 
`final _pagesMap = <Type, AutoRouteFactory>`

This is why two different custom routes on the same screen overrides each other...

**Comment by Milad-Akarie** [comment]
@vasilich6107 What version are you on?

**Comment by vasilich6107** [comment]
`auto_route: 0.6.9`
