### ISSUE TITLE
Incompatibility with named routes and dynamic arguments (onGeneratedRoute)

### ISSUE THREAD

**Issue by yurianxdev** [Milad-Akarie/auto_route_library#345]
I'll try to explain with a (not very rare) example. With `Navigator` you can build something like this:
```dart
final List<Map<String, dynamic>> items  = [
  { 'route': '/route-to-path', 'args': 12 },
  { 'route': '/route-another-path', 'args': 'different type of arguments' },
  { 'route': '/home', 'args': SomeObject() },
];

final buttonsToPaths = items.map((item) => FlatButton(
    onPressed: () {
      Navigator.of(context).pushNamed(item['route'], arguments: item['args']);
    },
    child: Text(
      'Flat Button',
    ),
  ),
);
```
I know the case below breaks the spirit of AutoRoute, but in some cases (like one I'm facing right now) is just inevitable. This kind of job worked for AutoRoute `^0.6`, with a set up like:
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: ViewHome, path: '/home'),
    MaterialRoute(page: ViewNeededPath, path: '/route-to-path'),
    MaterialRoute(page: ViewAnother, path: '/route-to-another-path'),
  ],
)
```
And then use `Navigator` as before.

Right now, that setup does not work anymore, apparently because AutoRoute is no longer registering the routes with `onGenereatedRoute`, or something like that.
```
Navigator.onGenerateRoute was null, but the route named "/route-to-path" was referenced.
```

I think AutoRoute should have that the flexibility of still using named routes and dynamically typed arguments.

**Comment by Milad-Akarie** [comment]
@yurianxdev  Are you using auto_route 1.0.0?

**Comment by yurianxdev** [comment]
Yes sir. Version 1.0.0-beta.7 to be exact.

**Comment by Milad-Akarie** [comment]
@yurianxdev I'm not sure I understand your goal but you can achieve the above in a neat way using auto_route 1.0.0,

```dart
final List<PageRouteInfo> items  = [
  FirstGeneratedRoute(args),
  dSecondGeneratedRoute(args),
  ThiredGeneratedRoute(args),
];

final buttonsToPaths = items.map((item) => FlatButton(
    onPressed: () {
      AutoRouter.of(context).push(items[index]);
    },
    child: Text(
      'Flat Button',
    ),
  ),
);
```
am I missing something?

**Comment by yurianxdev** [comment]
@Milad-Akarie close, but imagine the routes and the arguments coming from the backend (I know it is a bad design, but it is what I have right now).

**Comment by Milad-Akarie** [comment]
@yurianxdev How about mapping them?

```dart
final Map<String,PageRouteInfo> items  = [
  FirstGeneratedRoute.name: FirstGeneratedRoute(args),
  SecondGeneratedRoute.name: SecondGeneratedRoute(args),
  ThiredGeneratedRoute.name: ThiredGeneratedRoute(args),
];
```
