### ISSUE TITLE
Add support to a widget builder in routes definition

### ISSUE THREAD

**Issue by CassiusPacheco** [Milad-Akarie/auto_route_library#349]
Hi Milad, first of all I'd like to thank you for all your work in this lib, it's amazing!

While experimenting with it I noticed that it's not possible, AFAIK, to have custom widget builder for the routes, which makes Dependency Injection trickier.

For example, I have this route:
```
AutoRoute(
  path: 'settings',
  page: EmptyRouterPage,
  name: 'SettingsTabRoute',
  children: [
    AutoRoute(
      path: '',
      page: SettingsTabPage,
      name: 'settingstab',
    )
  ],
)
```

It'd be very useful if I could do instead:

```
AutoRoute(
  path: 'settings',
  page: EmptyRouterPage,
  name: 'SettingsTabRoute',
  children: [
    AutoRoute(
      path: '',
      page: SettingsTabPage,
      pageBuilder: (context) => SettingsTabPage(someDependency),
      name: 'settingstab',
    )
  ],
)
```

So I can inject `someDependency`, from the example above, into my widget.

I can see that might break the auto generated routes, so perhaps we'd need a different type of routes? Maybe part of the `CustomRoute`?

What do you think?

**Comment by Milad-Akarie** [comment]
Hey @CassiusPacheco Glad you like the Lib. 
unfortunately we can not pass instances or functions to static consts, code generators only consume static code. how ever I've been thinking of ways to handle dependency injection in AutoRoute and the best idea I've came up with is to provide a way to pass a dependencies provider function to the router and hook it up with your di handler, then annotate the injected params with @InjectParam or something 

so we would have something like this

```dart
T resolveDependency<T>(BuildContext context){
 // assuming you're using getIt
  return getIt<T>();
}
```
I'm still not sure if this's the best way to handle this, thoughts?

**Comment by CassiusPacheco** [comment]
I'm not entirely sure I get it right, but it seems to be a possible solution. I'm using my own DI container but it's fairly similar to GetIt.

I was wondering still if it'd be possible to have a ManualRoute where it doesn't get automatically generated by the code gen and give us more flexibility to create our own builders and such, for example. Do you think that could also be a possibility?

**Comment by jbt-cii** [comment]
Humm I have to change completly the way I declare the "router" I think when I read this:
[https://autoroute.vercel.app/introduction/installation_and_usage](https://autoroute.vercel.app/introduction/installation_and_usage)

Is it correct?
