### ISSUE TITLE
Best practices and some questions about Bottom Navigation Bar apps

### ISSUE THREAD

**Issue by aytunch** [Milad-Akarie/auto_route_library#350]
Hi @Milad-Akarie :)
I have fairly common requirements for an app with a bottom navigation bar. And I have questions:D 

1. `Bottom navigation Bar` with 5 tabs. (`HomePage`, `MessagesPage`, `CameraPage`, `BasketPage`, `ProfilePage`)
2. State restoration is a must. If I scroll at a random place in `HomePage` and go to `ProfilePage` and then again to `HomePage`, I expect to see where user was scrolled to and which `TextField`s were filled in etc.
3. Middle tab is `CameraPage`. It should open like a modal view without the `bottom nav bar` (full screen camera view)
4. When `CameraPage` is dismissed/popped, we always show `HomePage` (index=0)
5. `ProfilePage` has a list of user posts. When a post is pressed, `PostPage` will be pushed. `Bottom nav bar` needs to be **visible** in `PostPage`.
6. `MessagesPage` has a list of user friends. When a friend is pressed, `ChatPage` will be pushed. `Bottom nav bar` needs to be **hidden** (because we have a `TextField` at the bottom)
7. Lastly, if user presses a push notification like "Milad sent you a message", we need to show user the `MessagesPage` tab and `ChatPage` of Milad. (path something like `/messages/id:milad/chat/`)

I have looked at the [example codes, especially the one with bottom nav bar about the books ](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/screens/home_page.dart)and here are my questions;

Inside our main router.dart, in `MaterialAutoRouter`:`routes`:`AutoRoute`:`children` we supply Books, Profile and Settings.
But we also supply them in the stateless widget in our Ui code as follows:
```
AutoTabsRouter(
        routes: [BooksTab(), ProfileTab(), SettingsTab()],
```
Is this the right method? Should we always keep these in parallel? For my requirements, the middle tab is not really a part of the TabsRouter but it keeps space in the nav bar. So Should I do as follows? (4 items in `AutoTabsRouter`, but all 5 items in router.dart?
```
AutoTabsRouter(
        routes: [HomeTab(), MessagesTab(), BasketTab(), ProfileTab()],
```
Or is it the opposite? Should I give `AutoRoute` of 4 tabs in router.dart and all 5 in `AutoTabsRouter`? Is there a way to set a parameter for `AutoRoute` or `CustomRoute` which allows us to push a modal page for the middle tab? I hope there is something like that. Otherwise I can only think of a solution like below:

```
if(index!=2) //if it is not the middle tab
    tabsRouter.setActiveIndex(index);
else
    AutoRoute.of(context).push(CameraPage);
```

What is `children` exactly for in `AutoRoute` class? I did not find a documentation on it. Also what is `usesTabsRouter` for? Are they important for this case?

For steps 5 and 6, I want to be able to show detail pages with or without the bottom navigation bar. How can I do this programmatically with AutoRoute?

I see `RedirectRoute` a lot but what is it used for? Will I need it? Is it just for web? Or does it have a purpose for Mobile?

What is the use of `name` and `path`? When should we use both?
```
AutoRoute(
          path: 'settings',
          page: SettingsPage,
          name: 'SettingsTab',
        ),
```

Lastly, are the below 2 lines equivalent? 
```
context.router.push(BookDetailsRoute(id: book.id));
BookDetailsRoute(id: book.id).show(context);
```

**Comment by Milad-Akarie** [comment]
Hey @aytunch 
- AutoTabsRouter is supposed to maintain the state of its children. 
- tab routes can only be pushed in the body scope meaning you can't go full screen if you have a bottombar or an Appbar, so you probably have to add your camera route as a root route then have 4 real tabs and handle the fake tab like follows 

```dart
     onTap: (index) {
          if (index == 2) {
            // reset tab to home
            tabsRouter.setActiveIndex(0);
           // push camera route
            context.router.push(CameraRoute())
          } else if (index > 2) {
            // if index greater than 2 add one to make for the missing tab
            tabsRouter.setActiveIndex(index + 1);
          } else {
            tabsRouter.setActiveIndex(index);
          }
}
```

- children are the nested routes inside of AutoRoute e.g tabs are children/nested routes that are pushed in parallel. 
- usesTabsRouter flag is how auto_route picks the right controller for the nested children  (Stack Controller or Parallel Routes Controller) 
- you probably don't need to use RedirectRoute for mobile 
- The name is used to name the generated route class, if you don't assign a name to AutoRoute the generated Route name will be the Widget's name HomePage -> HomePageRoute..
- paths are used in web as you'd expect and in mobile they're used in deep linking, e.g you can use it to handle your path '/messages/id:milad/chat/'

and lastly the the lines are equivalent.
let me know if I missed any of your questions.

**Comment by aytunch** [comment]
Thank you very much for the nice explanation. 

One quick extra question: What is the best way to set a custom transition for `AutoTabsRouter`? Where should I put my custom transition code in?

I want to use a [Shared_Axis animation from the animations package](https://pub.dev/packages/animations#shared-axis) for transitions between Tabs. Is it possible? 

Take care Milad.

**Comment by Milad-Akarie** [comment]
I haven't played with that animation lib yet but AutoTabsRouter has a builder that provides an animation object and a child you should be able to implement any animation you want.

**Comment by ntminhdn** [comment]
@Milad-Akarie 
How I can do this?. Sorry for I can't find any example about this issue.
5. ProfilePage has a list of user posts. When a post is pressed, PostPage will be pushed. Bottom nav bar needs to be visible in PostPage.

**Comment by feriyalsusanto** [comment]
Hey @ntminhdn ,

Have you found the solution for your screen needs?

**Comment by ntminhdn** [comment]
@feriyalsusanto yes. I have found the solution. Check my example.
https://github.com/ntminhdn/CleanBlocFlutter/blob/master/lib/presentation/router/app_router.dart

**Comment by hschk** [comment]
Hey,

I’m encountering the same issue: I want to push a detail page from my ListPage, which is one of the pages in the Bottom Navigation Bar. The Bottom Navigation Bar should remain visible when navigating to the detail page, so I can’t declare the detail route at the root level.

Unfortunately, the link to your repository is no longer available. Could you please share how you solved this?

Thanks in advance!
