### ISSUE TITLE
TabsRouter not updating route

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#352]
Hi @Milad-Akarie,

I tested the 1.0.0-beta.9 for a bit and it really looks great.
One thing I noticed is that calling `TabsRouter.setActiveIndex()` does not seem to update the global route. The index is updated correctly but `context.route.route.fullPath` still returns the old path.

Am I missing something here?

**Comment by Milad-Akarie** [comment]
@kuhnroyal `context.route` gets you the scoped route, try `context.topMost.current` topMost will always get you the top most router in the hierarchy.

**Comment by kuhnroyal** [comment]
Thanks that works and is updated correctly. How can I get the full path from there?

**Comment by theweiweiway** [comment]
This is what I've been doing to listen to full path:

```
  String path = ""; 

  @override
  void didChangeDependencies() {
    var rootDelegate = RootRouterDelegate.of(context);
    rootDelegate.addListener(() {
      if (rootDelegate?.currentConfiguration != null) {
        final newPath = rootDelegate.currentConfiguration.map((a) {
          if (a.path.isNotEmpty && !a.path.contains("/")) {
            return '/' + a.path;
          }
          return "";
        }).join("");
        setState(() {
          path = newPath;
        });
      }
    });

    super.didChangeDependencies();
  }
```

**Comment by theweiweiway** [comment]
closing due to:
- stale issue
