### ISSUE TITLE
Nested navigator on bottom sheet

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#355]
On `auto_route: ^0.6.9` I used this widget to open a nested navigator on a bottom sheet:
```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';

class SheetWidget extends StatelessWidget {
  final RouterBase router;
  final String initialRoute;
  final Object arguments;

  SheetWidget({@required this.router, @required this.initialRoute, this.arguments});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      height: MediaQuery.of(context).size.height * .93 - MediaQuery.of(context).viewInsets.bottom,
      color: theme.canvasColor,
      child: ExtendedNavigator(
        router: router,
        initialRoute: initialRoute,
        initialRouteArgs: arguments,
      ),
    );
  }
}
```

I'm looking to update this to the new `auto_route: ^1.00-beta.9`, how can I achieve this?

**Comment by theweiweiway** [comment]
You can use `AutoRouter.declarative` to create an independent flow with it's own nested navigator. 
Please see #305, #337 for examples on how to set up the declarative router

The idea is that you can use an `AutoRouteWrapper` to put everything in the modal, and then have declarative routing inside the modal

You can also achieve this without declarative routing. Just make a nested router and put all of your routes in the modal in that nested router. Then, use an `AutoRouteWrapper` to wrap all of your modal routes in and have the modal logic in `AutoRouteWrapper`

**Comment by Limbou** [comment]
@theweiweiway could you please provide some code example? I don't follow your explanation
