### ISSUE TITLE
There is no way to provide a navigatorKey in the latest beta

### ISSUE THREAD

**Issue by doppio** [Milad-Akarie/auto_route_library#356]
In the latest beta release, RootRouterDelegate internally creates a GlobalKey to use as the Navigator's key. auto_route users should optionally be able to pass in their own key.

My use case is that I'm using the [Wiredash](https://pub.dev/packages/wiredash) package for sending user feedback. This package requires you to pass it the key of the primary navigator.

**Comment by kuhnroyal** [comment]
You can access the navigator key via `appRouter.navigatorKey` and pass it on.

**Comment by doppio** [comment]
Oh, perfect! Thank you @kuhnroyal.

**Comment by SashaFarkas** [comment]
What is appRouter.navigatorKey?
