### ISSUE TITLE
[1.0.0] White flash before first page is rendered

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#360]
This occurs due to https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/router/widgets/auto_router_delegate.dart#L116 - for me the `scaffoldBackgroundColor` is determined by the page that is shown first and not by the `MaterialApp.theme`.

The apps scaffold background is white but the first page might be dark, this leads to the white flash and I can not change the theme for the router widget. The placeholder page probably needs to be configurable in the router delegate config.

**Comment by Milad-Akarie** [comment]
@kuhnroyal will include this in the next build

**Comment by aytunch** [comment]
Hi @Milad-Akarie Do you have a timeline for the next build? and will it be on nnbd branch or both?

**Comment by theweiweiway** [comment]
@kuhnroyal @Milad-Akarie   Can i close this? This has been merged into 1.0.1 right

**Comment by Milad-Akarie** [comment]
@theweiweiway  Correct. closing this.

**Comment by aytunch** [comment]
Hi @Milad-Akarie we are still experiencing the white screen issue. 
Our flow is as follows. We use a PNG image for our native splash image.
After native splash page is displayed, auto router takes us to our initial page which has the exact same PNG image as the native splash.
However during the transition, we see a white screen or a different color which is set by `scaffoldBackgroundColor`.
We thought you added `placeholder` inside the `autorouterDelegate` just for this purpose which overrides the scaffold color with a custom widget but white screen is still being showed even after placeholder.
Thanks.

**Comment by Prn-Ice** [comment]
> Hey @aytunch, @Milad-Akarie, did you ever work out what was going on here? I am having a similar issue when loading an AutoRouter / AutoTabsScaffold for the first time. Any pointers would be very much appreciated as I am going round in circles with this one...as it stands I will have to write my own routing as I cannot push this to production glitchy like this.
> 
> Do you have any idea what / where the white color could be coming from? My scaffold background is black (coming via CupertinoThemeData). or any workarounds to stop the flash from happening?
> 
> Thanks!

This issue for me was because of some async initialisation between when the splash screen goes off and when the initial route is built.

Using flutter_native_splash to delay popping the splash screen fixed this for me.
