### ISSUE TITLE
Auto Route generate doesnt add import statement to generated file

### ISSUE THREAD

**Issue by emem365** [Milad-Akarie/auto_route_library#363]
So a weird thing is happening when I was trying to add a Custom Route to the routes file. 
```
@MaterialAutoRouter(
  generateNavigationHelperExtension: true,
  routes: <AutoRoute>[
    CustomRoute(
      page: Calendar,
      transitionsBuilder: createRippleLeftDown,
    ),
  ],
)

class $Router {}
```
This thing works great. I have the function createRippleLeftDown stored in another file and the import statement gets added to the generated file perfectly fine. But since I have multiple of such createRipple functions, I decided to wrap them in a class, something like:
```
class TransitionHelper {
  static Widget createRippleLeftDown(
      BuildContext context,
      Animation<double> animation,
      Animation<double> secondaryAnimation,
      Widget child) {
    return TransitionEffect.createRipple(origin: 'LeftDown')(
        Curves.linear, animation, secondaryAnimation, child);
  }
}

```
so when I change the line in the router file from :
`       transitionsBuilder: createRippleLeftDown, `
to 
`      transitionsBuilder: TransitionHelper.createRippleLeftDown,`

and now when I try to generate the .gr.dart file, it doesnt have this import statement, which results in the compiler throwing an error. What am I missing here? 
I tried to look through the API ref, but I couldn't really find why this is happening.

PS: The version I have for auto_route_generator is 0.6.10 and auto_route is 0.6.9. Flutter: 1.24.0-10.2pre

**Comment by Milad-Akarie** [comment]
@emem365 This's handled in the new auto_route I'll try to fix it in the legacy version as soon as possible.

**Comment by emem365** [comment]
@Milad-Akarie cool, would be waiting for that update :)

**Comment by theweiweiway** [comment]
@emem365 is this still an issue in version 2.2.0?

**Comment by emem365** [comment]
@theweiweiway Not if you use the null-safety version. haven't tried legacy again.  I am closing the issue since it works perfectly now, in the new updates.
