### ISSUE TITLE
Bottom Tabs + Stacks, how to hide doble AppBars

### ISSUE THREAD

**Issue by ricbermo** [Milad-Akarie/auto_route_library#364]
![image](https://user-images.githubusercontent.com/2601363/108414700-8b6ef700-71fa-11eb-8bd2-29a3e425e279.png)

Hello there,
First that all for all of the time you've spent in putting together this package.

I'm a noob Flutter developer and I've been playing with your example app, the books one.

I was just wondering if it is possible (probably yes) and how (probably with a simple param) to hide or reuse the app bar so the user doesn't see 2 of them. In the image I uploaded, the 1st tab belongs to the [tab](https://github.com/Milad-Akarie/auto_route_library/blob/a83e917554156bec3b7585b6a2018968faa1529b/auto_route/example/lib/mobile/screens/home_page.dart#L15) and the one below is defined in the [book details page](https://github.com/Milad-Akarie/auto_route_library/blob/a83e917554156bec3b7585b6a2018968faa1529b/auto_route/example/lib/mobile/screens/books/book_details_page.dart#L26)

How can I hide one of them and print the book title?
Thanks in advance.

**Comment by Milad-Akarie** [comment]
@ricbermo The current setup shares one Appbar across tabs, maybe what you need to do is provide a dedicated AppBar for each tab.

**Comment by ricbermo** [comment]
@Milad-Akarie thank you very much. BTW, Do u have some kind of Discord (or similar) channel where I could go a post this kind of questions? I shouldn't have created an issue for such dummy question 😬
