### ISSUE TITLE
Question /help about bottom navigation router

### ISSUE THREAD

**Issue by charm-cloud** [Milad-Akarie/auto_route_library#365]
I get some error, i am using  0.6.7

` dependOnInheritedWidgetOfExactType              ExtendedNavigatorState.routerName (package:auto_route/src/extended_navigator.dart:473:53)
I/flutter (11899): #6      ExtendedNavigatorState.dispose (package:auto_route/src/extended_navigator.dart:463:9)
I/flutter (11899): #7      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
I/flutter (11899): #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13) ...`

Not sure about how to debug it 
I am using bottom navigation bar with router for each bottomtab page , and other nested router  ,

Router set up is below link 

https://pastebin.com/8m8UY5uv

Thank you

**Comment by theweiweiway** [comment]
Usually we put child routes as relative paths, not absolute paths. Are you sure you want to put those routes as child routes of `MyDetailsPage`? If you are, can you try using relative paths

```
      AdaptiveRoute(
          page: MyDetailsPage,
          path: "/myDetails",
          name: 'DetailsPage',
          children: [
            AdaptiveRoute(
              page: MyDetails,
              path: '/', // try "" so that this path is now /myDetails
            ),
            AdaptiveRoute(
              page: ChatScreenFromNotification,
              path: '/chatScreen:foodProviderId?', // do you mean chatScreen/:foodProviderId?
            ),
           // AdaptiveRoute(page: MenuMainPage)
          ]),
         ])
```

**Comment by charm-cloud** [comment]
Thanks for the explanantion , i now understand that child routes should not start with /, have to be relative path only
