### ISSUE TITLE
Question about deep link 

### ISSUE THREAD

**Issue by charm-cloud** [Milad-Akarie/auto_route_library#368]
Hi , i am using 0.6.9, version , with below setup , deep link path is not found 

DetailsRoute is a part of bottomNavtab

`@MaterialAutoRouter(
    generateNavigationHelperExtension: true,
    routesClassName: 'DetailsRoute',
    routes: [

      AdaptiveRoute(page: Profile),
      AdaptiveRoute(page: AppDetails),
      AdaptiveRoute(
          page: MyDetailsPage,
          path: "/myDetails",
          name: 'DetailsPage',
          initial: true,

          children: [
            AdaptiveRoute(
              page: ChatListPage,
              path: '/det',
            ),
            AdaptiveRoute(
              page: ChatScreen,
              path: '/chatScreen:Id?',
            ),
           // AdaptiveRoute(page: MenuMainPage)
          ]),
      AdaptiveRoute(
        page: HelpPage,
      ),
`

`class MyDetailsPage extends StatelessWidget {
 

  const MyDetailsPage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ExtendedNavigator(
        initialRoute: "/det",
      ),
    );
  }
}

class MyDetails extends StatelessWidget {

  const MyDetails({
    Key key,
  
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: MyDetailsWidget(),
    );
  }
}
`

This path is not found ExtendedNavigator.named(Strings.detailNav)
          .push('/myDetails/det/chatScreen${payload}');

**Comment by theweiweiway** [comment]
Is this still a problem in 1.0.1? 

Also, your route 
```
       AdaptiveRoute(
          page: ChatListPage,
          path: '/det',
        ),
```

is defined as a child of /myDetails.

If you don't nest it as a child, does it work properly?

**Comment by charm-cloud** [comment]
Thanks  i  upgraded the version
