### ISSUE TITLE
Hero widget support for tabRouters

### ISSUE THREAD

**Issue by ricksondpenha** [Milad-Akarie/auto_route_library#372]
How do we achieve this.. currently hero widgets don't transition across tabrouters

**Comment by Milad-Akarie** [comment]
@ricksondpenha Usually hero controllers are managed inside of the Navigator widget.  I'll see what I can do.

**Comment by WasserEsser** [comment]
@Milad-Akarie I've tried wrapping my Scaffold AppBar widget with a Hero and use the default page transition provided by AutoRoute. The Hero transition doesn't seem to work.

**Comment by carlosfiori** [comment]
up
