### ISSUE TITLE
ExtendedNavigator.initialRoute not working as I expect it to...

### ISSUE THREAD

**Issue by RemeJuan** [Milad-Akarie/auto_route_library#373]
This may not be an issue, but an actual design decision, but it is somewhat confusing, to me at least.

In my `MainRouter` I have a List of routes, one of which being 

```dart
      CustomRoute(
        page: AppBootstrap,
        initial: true,
      ),
```

I am busy implementing the `integration_test` package and within the tests needed to pump the ExtendedNavigator so that in the test I can start at a specific point as for our auth flow, you head in 1 of 2 directions based on an http.Response status.

So what is being pumped in is

```dart
            ExtendedNavigator(
              router: MainRouter(),
              name: mainRouterName,
              initialRoute: Routes.loginView,
            );
```

However, I noticed that the auth was being all screwy and when adding logs in specific places I found that even though I defined the `initialRoute`, the app was still first going to `AppBootstrap` and then ending at `LoginView`, so that was the first screen I saw, but not the first screen that was routed to.

Is that how it is meant to work, as my assumption would have been that the `initialRoute` would have been an override for whichever was defined as the initial, not a `pop`, I guess it how it's working now?

Removing that `initial: true`, resulted in the same destination without the initial hops.

**Comment by theweiweiway** [comment]
```dart
              AutoRoute<dynamic>(
                path: 'overview',
                page: EmptyPage2,
               initial: true, // will auto_generate  RedirectRoute(path: '', redirectTo: 'overview'),
              ),
```

AutoRoute 2.x should fix your issue
