### ISSUE TITLE
Accessing parameters of class extended by AutoRouter with AutoRouteWrapper

### ISSUE THREAD

**Issue by michcio53** [Milad-Akarie/auto_route_library#375]
Let assume, that I want to have a bloc that can be access by specific screens. I have read that I can use a class that looks like this:

```dart
class SomeRoute extends AutoRouter with AutoRouteWrapper {
  const SomeRoute({
    Key key,
    this.onResult,
  }) : super(key: key);

  final Function() onResult;

  @override
  Widget wrappedRoute(BuildContext context) {
    return BlocProvider(
      create: (context) => SomeBloc(),
      child: this,
    );
  }
}
```

and router looks like this:

```dart
AutoRoute(
      page: FirstPage,
      name: 'FirstPage',
    ),
    AutoRoute(
      path: 'some_route',
      name: 'SomeRouteName',
      page: SomeRoute,
      children: [
        AutoRoute(
          initial: true,
          page: FirstSubRoute,
          name: 'FirstSubRoute',
        ),
        AutoRoute(
          page: SecondSubRoute,
          name: 'SecondSubRoute',
        ),
        AutoRoute(
          page: ThirdSubRoute,
          name: 'ThirdSubRoute',
        ),
      ],
    ),
```

So any child that parent is `SomeRoute`, will have an access to bloc `SomeBloc` . But what if, I want to use `onResult` callback to inform `FirstPage` (that called `SomeRoute`), about change that have been made on one of children screens. I want to use onResult in childrens of SomeRoute. Is this possible?

**Comment by theweiweiway** [comment]
Hi @michcio53,

I believe you would need to use a declarative routing approach to complete this. Milad has an example here: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/screens/user-data/data_collector.dart

Basically, the `onResult` callback is triggered by a child route's `onResult` callback. In the example link I've sent you, check out line 47. It's calling the `onResult` in line 7. So We are propogating the onResult callback from the `ThirdSubRoute`, which then calls `SomeRoute`'s onResult, which then pops in the `FirstPage`

**Comment by theweiweiway** [comment]
The key really is `AutoRouter.declarative`

**Comment by Milad-Akarie** [comment]
@michcio53 Another approach would be accessing the parent route inside the sub routes like follows
```dart
  var parent = context.route.parent;
 (parent.route as SomeRouteName).onResult();
```

**Comment by theweiweiway** [comment]
@Milad-Akarie  Wow - I didn't know you could do that. Awesome!

**Comment by michcio53** [comment]
@Milad-Akarie @theweiweiway thanks for fast responding! I will definitely try both of this approaches! :)
