### ISSUE TITLE
typedef Route parameter breaks generator

### ISSUE THREAD

**Issue by alkebuware** [Milad-Akarie/auto_route_library#376]
Hi,

It looks like there's a regression in the beta auto_route_generator package where if a route has a typedef parameter it breaks the build. I saw that this was referenced in issue https://github.com/Milad-Akarie/auto_route_library/issues/35, but was fixed in the stable branch.

When I try to build the below widget 
```
typedef SaveCallback = Future<void> Function(User user);

class EditContactScreen extends StatefulWidget {
  final User user;
  final SaveCallback onSave;

  const EditContactScreen({Key key, @required this.user, @required this.onSave})
      : super(key: key);

  @override
  _EditContactScreenState createState() => _EditContactScreenState();
}
```

I get the below error from build_runner
```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/src/routes.dart:

NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
```

**Comment by theweiweiway** [comment]
hey @alkebuware do u. still get this error in version 2.2.x?
