### ISSUE TITLE
How add observer in tabsRouters?

### ISSUE THREAD

**Issue by wwwhttpru** [Milad-Akarie/auto_route_library#377]
Sorry for my English :)
How to add Observer in tabsRouter? 
Interested in Firebase Analytics

**Comment by brizaldi** [comment]
any update about this?

**Comment by jlnrrg** [comment]
with #486 I assume this should work. Please try on your side.
`Add AutoRouteObserver to add tabs observing to the native observer.`

**Comment by Milad-Akarie** [comment]
@brizaldi you could implement AutoRouterObserver which extends the native NavigatorObserver
then pass to the delegate using the navigatorObservers creator callback

make sure the callback always creates  new instances.
` navigatorObservers: () => [MyAutoRouterObserver()]`

**Comment by theweiweiway** [comment]
Closing due to solution provided
