### ISSUE TITLE
ExtendedNavigator.builder crashes with Flutter 2.0

### ISSUE THREAD

**Issue by klisiewicz** [Milad-Akarie/auto_route_library#378]
The current stable version (0.6.9) of the Auto Route packages seems to be not compatible with Flutter 2.0. I've followed the example from the [documentation](https://pub.dev/packages/auto_route#setup-and-usage) and ended up with an error:
```
The following NoSuchMethodError was thrown building Builder(dirty):
The getter 'key' was called on null.
Receiver: null
Tried calling: key

The relevant error-causing widget was: 
  MaterialApp file:///sample_app/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ExtendedNavigator.builder.<anonymous closure> (package:auto_route/src/extended_navigator.dart:37:36)
#2      _MaterialAppState._materialBuilder.<anonymous closure> (package:flutter/src/material/app.dart:756:39)
#3      Builder.build (package:flutter/src/widgets/basic.dart:7555:48)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
...
====================================================================================================
```

```yaml
dependencies:
  auto_route: ^0.6.9
dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner:
```

```
Flutter version 2.0.0 
Framework revision 60bd88df91 (25 hours ago), 2021-03-03 09:13:17 -0800
Engine revision 40441def69
Dart version 2.12.0
```

```dart
class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: ExtendedNavigator.builder<SampleRouter>(
        router: SampleRouter(),
        builder: (context, extendedNav) => Theme(
          data: ThemeData(brightness: Brightness.dark),
          child: extendedNav,
        ),
      ),
    );
  }
}

class SampleScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Hello World'),
    );
  }
}

@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: SampleScreen, initial: true),
  ],
)
class $SampleRouter {}
```

**Comment by 20156284** [comment]
I have the same issues

**Comment by sonofGod225** [comment]
I have the same issues

**Comment by klisiewicz** [comment]
The [documentation](https://api.flutter.dev/flutter/material/MaterialApp/builder.html) of the `MaterialApp` describes the `builder` property as follows:

**If no routes are provided** to the regular WidgetsApp constructor using home, routes, onGenerateRoute, or onUnknownRoute, **the child will be null**, and it is the responsibility of the builder to provide the application's routing machinery.

If routes are provided to the regular WidgetsApp constructor using one or more of those properties or if the WidgetsApp.router constructor is used, **then child is not null**, and the returned value should include the child in the widget subtree; if it does not, then the application will have no Navigator or Router

That's the reason why `extended._navigator.dart` receives a `null` child:
```dart
  static TransitionBuilder builder<T extends RouterBase>({
    GlobalKey<NavigatorState> navigatorKey,
    List<NavigatorObserver> observers = const [],
    RouteFactory onUnknownRoute,
    String initialRoute,
    Object initialRouteArgs,
    @required T router,
    List<RouteGuard> guards = const [],
    String name,
    TransitionBuilder builder,
  }) =>
      (context, nav) {
        var extendedNav = ExtendedNavigator<T>(
          key: GlobalObjectKey(nav.key),
          ...
        );
        return extendedNav;
      };
```

A quick fix for that could be:

```dart
class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final router = SampleRouter();
    return MaterialApp(
      onGenerateRoute: router,
      builder: ExtendedNavigator.builder<SampleRouter>(
        router: router,
        builder: (context, extendedNav) => Theme(
          data: ThemeData(brightness: Brightness.dark),
          child: extendedNav,
        ),
      ),
    );
  }
}
```
But I'm not sure what implications it may have on the navigator's behavior.

**Comment by cherlow** [comment]
facing the same problem....any available work around?

**Comment by woelmer** [comment]
This came up before in a closed issue. The workaround that worked for me was @Flow2dot0 suggestion to add a dummy Container() or SizedBox() on the home parameter of MaterialApp.  see https://github.com/Milad-Akarie/auto_route_library/issues/257#issuecomment-740259400

**Comment by theweiweiway** [comment]
closing due to proposed workaround, and Legacy autoroute with Navigator 1.0 will no longer be supported going forward #412

**Comment by bhaveshstackapp** [comment]
> The current stable version (0.6.9) of the Auto Route packages seems to be not compatible with Flutter 2.0. I've followed the example from the [documentation](https://pub.dev/packages/auto_route#setup-and-usage) and ended up with an error:
> 
> ```
> The following NoSuchMethodError was thrown building Builder(dirty):
> The getter 'key' was called on null.
> Receiver: null
> Tried calling: key
> 
> The relevant error-causing widget was: 
>   MaterialApp file:///sample_app/lib/main.dart:14:12
> When the exception was thrown, this was the stack: 
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
> #1      ExtendedNavigator.builder.<anonymous closure> (package:auto_route/src/extended_navigator.dart:37:36)
> #2      _MaterialAppState._materialBuilder.<anonymous closure> (package:flutter/src/material/app.dart:756:39)
> #3      Builder.build (package:flutter/src/widgets/basic.dart:7555:48)
> #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
> ...
> ====================================================================================================
> ```
> 
> ```yaml
> dependencies:
>   auto_route: ^0.6.9
> dev_dependencies:
>   auto_route_generator: ^0.6.10
>   build_runner:
> ```
> 
> ```
> Flutter version 2.0.0 
> Framework revision 60bd88df91 (25 hours ago), 2021-03-03 09:13:17 -0800
> Engine revision 40441def69
> Dart version 2.12.0
> ```
> 
> ```dart
> class SampleApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       builder: ExtendedNavigator.builder<SampleRouter>(
>         router: SampleRouter(),
>         builder: (context, extendedNav) => Theme(
>           data: ThemeData(brightness: Brightness.dark),
>           child: extendedNav,
>         ),
>       ),
>     );
>   }
> }
> 
> class SampleScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Center(
>       child: Text('Hello World'),
>     );
>   }
> }
> 
> @MaterialAutoRouter(
>   routes: <AutoRoute>[
>     MaterialRoute(page: SampleScreen, initial: true),
>   ],
> )
> class $SampleRouter {}
> ```

thank you @klisiewicz.
my issue solved.

i am uses of auto_route_generator: ^0.6.9 and change to
auto_route_generator: ^0.6.10
