### ISSUE TITLE
Provide option of removing hash (#) from the URL path?

### ISSUE THREAD

**Issue by AscentionOne** [Milad-Akarie/auto_route_library#379]
After yesterday the release of Flutter 2 and Flutter web came into the stable channel. Base on the Q&A section, Mariam Hasnany
product manager of Flutter web, mention that now the url can be customized and hash (#) sign now can be removed. [Here](https://flutter.dev/docs/development/ui/navigation/url-strategies) provide a  method of changing URL Strategy. She also mentioned that we can use [url_strategy](https://pub.dev/packages/url_strategy) a package that managed all that for you. 

However, I tried the url_strategy package it did remove the hash (#) symbole, but when changing the route it becomes very slow when you typed in the children's path ex: /books/1. Have anyone try this? Or we can change the URL Strategy through auto_rout? Thanks!

**Comment by theweiweiway** [comment]
Hey @AscentionOne is it still slow?

I just tried the url_strategy package in AutoRoute 2.x and it's the same speed as if there are hashes. can you confirm and close if that's the case? thnx.

**Comment by AscentionOne** [comment]
@theweiweiway Sorry for the late reply. I think I can close this for now. I will give it a try and let you know if there is still an issue. Since I am back on the mobile project lately~ Thank you!

**Comment by AscentionOne** [comment]
@theweiweiway Also does the `auto_route` package provide the option of removing (#) sign for now? Haven't seen it in the recent update. Will it be in the future or just use `url_strategy` package. Thanks!

**Comment by aytunch** [comment]
what is the recommended way to remove the hash symbol from url using auto route?

**Comment by pbozzay** [comment]
I have the same question

**Comment by DanielCardonaRojas** [comment]
I'm looking for the same feature. How difficult would it be to implement a custom URL parser. I took a look at the docs 
and seems to be possible  https://api.flutter.dev/flutter/widgets/RouteInformationParser-class.html.

Any hints on how to implement this strategy ?

**Comment by fedser** [comment]
For me helped suggestions from https://github.com/Milad-Akarie/auto_route_library/issues/1389:
1/ recreate base index.html via command: `flutter create . --platforms=web`
2/ use flutter_web_plugins:
 a/ add to pubspec.yaml:
```
flutter_web_plugins:
    sdk: flutter
```
 b/ in main() add `setUrlStrategy(PathUrlStrategy());`
