### ISSUE TITLE
Because auto_route_generator >=0.6.9 <1.0.0-beta depends on auto_route ^0.6.9 and multipie(project name) depends on auto_route ^0.2.1, auto_route_generator >=0.6.9 <1.0.0-beta is forbidden.

### ISSUE THREAD

**Issue by pythonsst** [Milad-Akarie/auto_route_library#381]
Because auto_route_generator >=0.6.9 <1.0.0-beta depends on auto_route ^0.6.9 and multipie depends on auto_route ^0.2.1, auto_route_generator >=0.6.9 <1.0.0-beta is forbidden.
So, because multipie depends on auto_route_generator ^0.6.10, version solving failed.
Running "flutter pub get" in multipie...                                
pub get failed (1; So, because multipie depends on auto_route_generator ^0.6.10, version solving failed.)

**Comment by theweiweiway** [comment]
Can you update to the latest versions of auto route and auto route generator

**Comment by klisiewicz** [comment]
It's not an issue with the `auto route` package, but with external packages that internally depend on an outdated `auto route` package version: "_and multiple depends on auto_route ^0.2.1_".

**Comment by theweiweiway** [comment]
Closing due to
- not a problem with AutoRoute
