### ISSUE TITLE
Using tabsRouter with nested children

### ISSUE THREAD

**Issue by FDJethroLising** [Milad-Akarie/auto_route_library#382]
Version:
```
 auto_route: ^1.0.0-beta.10
 auto_route_generator: ^1.0.0-beta.11
```
I use the tabsRouter feature of AutoRoute.

I need to resolve/catch this url pattern

/users
/users/123

My routes look like this
```dart
<AutoRoute>[
    AutoRoute(
      page: HomeScreen,
      initial: true,
      usesTabsRouter: true,
      children: [
        AutoRoute(
          path: "users/",
          page: UsersListScreen,
          children: [
            AutoRoute(
              path: "users/:id",
              page: UserDetailsScren
            )
          ],
        ),
      ],
    ),
  ],
```

Is this the right way to catch/resolve those URL/paths?
How do I programmatically navigate to a specified user in this path: users/123?

**Comment by theweiweiway** [comment]
Try `router.pushNamed('/users/123')` when you are inside the users tab - please let me know if that works

**Comment by Milad-Akarie** [comment]
@theweiweiway  I think he needs both '/users' and '/users/:id' on the same level. 
@FDJethroLising  try the following setup. 

```dart
<AutoRoute>[
    AutoRoute(
      page: HomeScreen,
      path: '/',
      usesTabsRouter: true,
      children: [
        AutoRoute(
          path: "users",
          page: EmptyRouterPage,
          children: [
              AutoRoute(
              path: '',
              page: UserDetailsScren
            ),
            AutoRoute(
              path: ":id",
              page: UserDetailsScren
            )
          ],
        ),
      ],
    ),
  ]
```

**Comment by FDJethroLising** [comment]
@Milad-Akarie 
Tried  your recommendation
```dart
<AutoRoute>[
    AutoRoute(
      page: HomeScreen,
      path: '/',
      usesTabsRouter: true,
      children: [
        AutoRoute(
          path: "users",
          page: EmptyRouterPage,
          children: [
              AutoRoute(
              path: '',
              page: UserListScreen
            ),
            AutoRoute(
              path: ":id",
              page: UserDetailsScreen
            )
          ],
        ),
      ],
    ),
  ]
```

and got:
>The following assertion was thrown building HomeScreen:
HomeScreenRoute can not navigate to UsersListScreen

**Comment by Milad-Akarie** [comment]
Where are you pushing it from?

**Comment by FDJethroLising** [comment]
@Milad-Akarie 

Sorry that was my error.

I tried your recommendation and I don't see the `UserListScreen` on "members/", only the EmptyRouterPage (which is just a Container).

When I put "/members/1" url  on my browser, it doesn't route to `UserDetailsScreen`

**Comment by FDJethroLising** [comment]
I have found a work around but its a bit of a hack, for now it works for me.

Instead of having the '/users/' route have children I just do this

```dart
<AutoRoute>[
    AutoRoute(
      page: HomeScreen,
      path: '/',
      usesTabsRouter: true,
      children: [
        AutoRoute(
          path: "users/:id",
          page: UserListsScreen,
        ),
      ],
    ),
  ]

```

and just do a check on the `UsersListScreen`

```dart
class UserListScreen extends StatelessWidget {
  final String id;
  const UserListScreen({
    Key key,
    @PathParam('id') this.id,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print(id);
    return id == null || id == ":id" ? _listView() : _userDetailsScreen(id: id);
  }
}
```

I can then programmatically navigate to the details screen by doing

```dart
  AutoRouter.of(context).push(
      HomeScreenRoute(children: [UserListScreenRoute(id: userID)]));
```

Navigation syncs, as well as the URL.

However, its hack and can get tedious if I decide to have more than 1 route under '/users'.

Another note: I did see this in your repo, i was wondering if this would work? 
https://github.com/Milad-Akarie/parallel-navigation-demo-auto-route

**Comment by theweiweiway** [comment]
I'll take a look at this when I have a bit more time on the weekend - it seems like what Milad suggested should work without problem

**Comment by Milad-Akarie** [comment]
@FDJethroLising  I'm not sure I understand correctly but, if you have two different routes '/users' and 'users/:id' why render them both in same screen? 
why can't you have something like this 

```dart
<AutoRoute>[
    AutoRoute(
      page: HomeScreen,
      path: '/',
      usesTabsRouter: true,
      children: [
        AutoRoute(
          path: "users/:id",
          page: UserDetailsScreen,
        ),
         AutoRoute(
          path: "users",
          page: UserListsScreen,
        ),
      ],
    ),
  ]

```

**Comment by FDJethroLising** [comment]
@Milad-Akarie  the issue is UserDetailsScreen is nested inside UserListScreen. But What you suggested can be made to work so Im gonna use it. 

The only thing now is I cant seem to navigate to different tabs/routes. I always get 'cant route to /path' errors.

**Comment by theweiweiway** [comment]
@FDJethroLising  Oh, is this a problem of pushing the route? If so, did you try this: https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing

The very bottom of the page, it tells you how to navigate between tabs/routes. This is only for the case of bottom navigation bar tabs

**Comment by FDJethroLising** [comment]
@theweiweiway Wow didn't know this page existed. I'll dig in, it seems to have what I'm Looking for. Thanks!

**Comment by RicardoRB** [comment]
> @FDJethroLising Oh, is this a problem of pushing the route? If so, did you try this: https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing
> 
> The very bottom of the page, it tells you how to navigate between tabs/routes. This is only for the case of bottom navigation bar tabs

Am I the only one who it doesn't work? :(
