### ISSUE TITLE
Add a "buy me a coffee" link

### ISSUE THREAD

**Issue by CassiusPacheco** [Milad-Akarie/auto_route_library#383]
I have to say that auto_route is the best Navigator 2.0 library out there (I've tried so many), and your massive effort is helping me and others tons!

Maybe you should consider adding one of those "buy me a coffee" kind of paypal (or something else) links to the readme file. I'd love to contribute with a couple of coffees ☺️

**Comment by AscentionOne** [comment]
Agreed! auto_route package had also helped me a lot in Navigator 2.0. Especially I am developing a web application, where routing mechanics is really important! ♥

**Comment by Milad-Akarie** [comment]
@CassiusPacheco @AscentionOne I really appreciate the gesture and I'm really glad you guys find auto_route helpful. Unfortunately neither PayPal nor Stripe support my country. :(

**Comment by AscentionOne** [comment]
Hi @Milad-Akarie Will this kind of method work? I saw some creators of the package( flutter_form_builder) use this. https://www.buymeacoffee.com/

**Comment by CassiusPacheco** [comment]
What about GitHub sponsor?

**Comment by Milad-Akarie** [comment]
@CassiusPacheco not even on the wishlist lol

**Comment by theweiweiway** [comment]
There's always... Bitcoin?? Lol

**Comment by theweiweiway** [comment]
noooooooo idea. I guess we can ask everyone here

@CassiusPacheco @AscentionOne, please like Milad's post if you would considering sending Milad bitcoin! 

I used Kraken to buy and sell bitcoin back in the day. You are in Lebanon right? You can create an account (https://support.kraken.com/hc/en-us/articles/360001368823-Geographic-Restrictions-Can-I-use-Kraken-if-I-m-from-) but you might not be able to deposit funds.

That's oK if you only want to use it for receiving funds... I think?

**Comment by AscentionOne** [comment]
I check the buymecoffe they can also use the bank account directly. I am not sure if it will work in Libya. Check here in “How do I get payed” section.

https://help.buymeacoffee.com/en/articles/4539170-frequently-asked-questions

I also check Patreon, I didn’t saw the restriction in Libya. Check here for more information. 

https://support.patreon.com/hc/en-us/articles/360038061371-Sanctions-Policy

**Comment by CassiusPacheco** [comment]
I just saw that you've managed to create a [buy me a coffee link](https://www.buymeacoffee.com/miladakarie)! Nice one. I've made a contribution, thanks for your work

**Comment by Milad-Akarie** [comment]
@CassiusPacheco  yup I managed some how, Thank you so much for your support.

**Comment by AscentionOne** [comment]
Yeah, coffee break! Thank you, for the great packagege Milad! Cheers ☕
