### ISSUE TITLE
Web Support Please.

### ISSUE THREAD

**Issue by valehasadli** [Milad-Akarie/auto_route_library#384]
Hello there! 

It's a very useful library and unfortunately, it doesn't support the web. After the **Flutter 2** version, **navigator 2.0** _has arrived with a new feature_. 

Do you think to support new features?

**Comment by jonasbark** [comment]
auto_route: ^1.0.0-beta.10 already uses Navigator 2.0 and I'm using it on a web app :)

**Comment by valehasadli** [comment]
> auto_route: ^1.0.0-beta.10 already uses Navigator 2.0 and I'm using it on a web app :)

Thanks for the comment, I just checked the package already has been released 1.0.1 version but still, I didn't see WEB support on the supported devices list.
