### ISSUE TITLE
Please provide usable documentation

### ISSUE THREAD

**Issue by pueffl** [Milad-Akarie/auto_route_library#385]
For the latest beta, there is the following documentation section:

Finalize the setup

after you run the generator your router class will be generated, hook it up with MaterialApp.

   final _appRouter = AppRouter()
   ...
  Widget build(BuildContext context){
      return MaterialApp.router(
             routerDelegate: _appRouter.delegate(...initialConfig),
             routeInformationParser: _appRouter.defaultRouteParser(),
         ),
  }
...this is not so easy to understand. Even after I got it, 'initialConfig' is still mysterious and not defined. What does that mean? Where do I have that config???

**Comment by amrnt** [comment]
I see that the docs are up now https://autoroute.vercel.app

**Comment by pueffl** [comment]
Ok, I try to read through this and see if it helps. routerDelegate: _appRouter.delegate(...**initialConfig**), is still mysterious, at least in the setup + install section :-)

**Comment by pueffl** [comment]
Thx, think I understand and can work on with that so far. Still have to prove in my app if I really do :-)
