### ISSUE TITLE
Extend replaceInRouteName to allow more than one replacement.

### ISSUE THREAD

**Issue by slavap** [Milad-Akarie/auto_route_library#387]
For example:
```dart
replaceInRouteName: 'Page,Route;View,Route;Deferred,'
```
means I want to:
1. Replace Page to Route
2. Replace View to Route
3. Remove Deferred

**Comment by nguyenxndaidev** [comment]
I would suggest to use callback function to give developers full control of changing the route name.
Maybe, deprecated `replaceInRouteName` and change to smt like 'generateRouteName'.

```
generateRouteName: (name) => name.replaceAll('Page', 'Route')
```
