### ISSUE TITLE
CustomRouteBuilder should be changed or extended to allow lazy instantiation.

### ISSUE THREAD

**Issue by slavap** [Milad-Akarie/auto_route_library#388]
```dart
typedef CustomRouteBuilder = Route Function(BuildContext context, Widget child, CustomPage page);
```
So currently child is instantiated when CustomRouteBuilder called, which is not always desired.
IMO it should be:
```dart
typedef ChildBuilder = Widget Function(BuildContext context);
typedef CustomRouteBuilder = Route Function(BuildContext context, ChildBuilder childBuilder, CustomPage page);
```
That way it will be possible to lazy instantiate child, the same way as PageRouteBuilder does.

**Comment by Milad-Akarie** [comment]
@slavap I two was worried about this at first then I realized constructing the child is not the same as initializing it, even the MaterialPage shipped in with flutter accepts a child not a builder  `MaterialPage(child: )` 
what do you think?

**Comment by slavap** [comment]
@Milad-Akarie Not sure what exactly you are saying, but constructing StatefulWidget will call init for its state, and there could be quite expensive code in init method. So I personally think my request for changes is the right thing.

**Comment by Milad-Akarie** [comment]
Actually createState will call initState not the widget's constructor.

**Comment by slavap** [comment]
@Milad-Akarie I need to check it with debugger, my memory is telling me that state init will be called, but may be I’m mistaken

**Comment by slavap** [comment]
@Milad-Akarie Checked under debugger - and yes, you are right, creating StatefulWidget does not immediately creates its state (it will be created and init later on mount), so it is quite cheap operation.
