### ISSUE TITLE
use const and final variables when it is possible to

### ISSUE THREAD

**Issue by z-dmitri** [Milad-Akarie/auto_route_library#39]
it could be nice to use const and final variables in the generated files when it is possible
- for the better performance + reduce warnings
so generated file will looks like:
```dart
transitionDuration: const Duration(milliseconds: n),
```
instead of:
```dart
transitionDuration: Duration(milliseconds: n),
```

**Comment by Milad-Akarie** [comment]
@z-dmitri noted. Thanks for reporting

**Comment by Milad-Akarie** [comment]
@z-dmitri  done in v0.4.0 
BTW There are some breaking changes!
