### ISSUE TITLE
Deeplinking on web not behaving as expected when using nested routes

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#392]
In the following case:  

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: GroupsPage,
      initial: true,
      children: [
        AutoRoute(path: 'list', page: GroupsListPage),
        AutoRoute(path: 'details', page: GroupDetailsPage)
      ],
    ),
  ],
)
class $AppRouter {}.
```

On the web browser, if I go to `/#/details` or `/#/list`, it shows me `GroupsPage` but it should be showing me `GroupDetailsPage` or `GroupsListPage`. 

Now, if I change `GroupsPage` (the initial route page) to `EmptyRouterPage`, the deeplinking behaviour works as intended.
 `/#/details`  brings me to `GroupDetailsPage` and
`/#/list` brings me to `GroupsListPage`

**Comment by nguyenxndaidev** [comment]
Same happens to me. I must use EmptyRouterPage and create a child with `path: ''` to make it work.

**Comment by theweiweiway** [comment]
Yeah, that's definitely the best way at the moment to get around this. It's a good enough solution that this isn't a critical bug or anything

**Comment by Milad-Akarie** [comment]
@theweiweiway @nguyenxndaidev  Your groups page needs an 'Outlet' to render child routes ( That's a simple AutoRouter() widget) 
`EmptyRouterPage` is an empty page with an `AutoRouter()` widget

**Comment by theweiweiway** [comment]
Oh, i missed that - thanks!
