### ISSUE TITLE
Support path generation

### ISSUE THREAD

**Issue by nguyenxndaidev** [Milad-Akarie/auto_route_library#394]
Currently, if I have `AutoRoute(page: AuthPage)`, generated code for the route will have `path: '/auth-page'`.

I would suggest to support function callback `generatePath` to give developers full control how to generate path globally.
If `generatePath` is not provided, use kebab case as default.
If `path is provided`, don't call `generatePath`.

```
@MaterialAutoRouter(
  generatePath: (page) => ...,
  routes: <AutoRoute>[
    AutoRoute(page: AuthPage), // generatePath is used
    AutoRoute(page: PublicPage, path: '/public') // generatePath is not called
  ]
)
```

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: AuthPage), // default generatePath is to convert to kebab case: /auth-page
    AutoRoute(page: PublicPage, path: '/public') // generatePath is not called
  ]
)
```

**Comment by Milad-Akarie** [comment]
@nguyenxndaidev That's a good idea. I'm now trying to release the auto_route 1.0.0, once that's done I'll start working on all the new suggestions.
