### ISSUE TITLE
How to navigate from a router context to another router context?

### ISSUE THREAD

**Issue by nguyenxndaidev** [Milad-Akarie/auto_route_library#395]
If I am on `/public/a`, how can I navigate to `/a` or `/protected/a`?

See example https://github.com/nguyenxndaidev/auto_route_example/tree/bug/router-switching/lib

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      name: 'HomeRouter',
      page: HomeRouterPage,
      children: [
        AutoRoute(path: '', page: HomePage),
        AutoRoute(path: 'a', page: HomeAPage),
        AutoRoute(path: 'b', page: HomeBPage),
      ],
    ),
    AutoRoute(
      path: '/public',
      name: 'PublicRouter',
      page: PublicRouterPage,
      children: [
        AutoRoute(path: '', page: PublicPage),
        AutoRoute(path: 'a', page: PublicAPage),
        AutoRoute(path: 'b', page: PublicBPage),
      ],
    ),
    AutoRoute(
      path: '/protected',
      name: 'ProtectedRouter',
      page: ProtectedRouterPage,
      children: [
        AutoRoute(path: '', page: ProtectedPage),
        AutoRoute(path: 'a', page: ProtectedAPage),
        AutoRoute(path: 'b', page: ProtectedBPage),
      ],
    ),
    AutoRoute(path: '/*', page: NotFoundPage),
  ],
)
class $AppRouter {}

class HomeRouterPage extends AutoRouter with AutoRouteWrapper {
  const HomeRouterPage({Key key}) : super(key: key);

  @override
  Widget wrappedRoute(BuildContext context) {
    return this;
  }
}

class PublicRouterPage extends AutoRouter with AutoRouteWrapper {
  const PublicRouterPage({Key key}) : super(key: key);

  @override
  Widget wrappedRoute(BuildContext context) {
    return this;
  }
}

class ProtectedRouterPage extends AutoRouter with AutoRouteWrapper {
  const ProtectedRouterPage({Key key}) : super(key: key);

  @override
  Widget wrappedRoute(BuildContext context) {
    return this;
  }
}
```

**Comment by nguyenxndaidev** [comment]
It seems, `context.router.root.push(ProtectedRoute())` works.
So what are the differences betwwen `context.router.root` and `context.router`?

**Comment by Milad-Akarie** [comment]
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[ // routes inside this are managed using the root router
    AutoRoute(
      initial: true,
      name: 'HomeRouter',
      page: HomeRouterPage,
      children: [ // routes inside this are using the HomeRouterPage
        AutoRoute(path: '', page: HomePage),
        AutoRoute(path: 'a', page: PublicAPage),
      ],
    ),
    AutoRoute(path: '/auth', page: AuthPage),
    AutoRoute(path: '/protected', guards: [AuthGuard], page: ProtectedPage),
    AutoRoute(path: '/*', page: NotFoundPage),
  ],
)
class $AppRouter {}

This's a diagram from the docs I'm working on.. it might help you visualize what's going on. 
![Untitled Diagram](https://user-images.githubusercontent.com/55059449/111072730-7e38e580-84e4-11eb-9d03-c2eeab0645d5.png)

**Comment by nguyenxndaidev** [comment]
@Milad-Akarie I found the root problem and updated the description with new example.

**Comment by Milad-Akarie** [comment]
@nguyenxndaidev  Where are you navigating from and where do you want to navigate to?

**Comment by nguyenxndaidev** [comment]
> @nguyenxndaidev Where are you navigating from and where do you want to navigate to?

If I am on `/public/a`, how can I navigate to `/a` or `protected/a`?

**Comment by Milad-Akarie** [comment]
'/public/a' is inside of the public router but you need to go one level up, which you can do by calling
 `context.router.root `or` context.router.parent` then you go push the parent route and the initial child or children.
` context.router.parent.push(ProtectedRouter(children: [ProtectedARoute()]));`

**Comment by nguyenxndaidev** [comment]
Thanks @Milad-Akarie! It works!

I still have some questions:
* If I have multiple levels of router, how can I get it without the need to know the hierarchy? For example, get router by name/key or by type?
* How can I understand the `children` when I push to a new router? Could you give me an example whenI need multiple items in `children`?

**Comment by nguyenxndaidev** [comment]
As far as I see now, the AppBar Up button doesn't work if I use `context.router.root.push(ProtectedRouter(children: [ProtectedARoute()]));`

**Comment by nguyenxndaidev** [comment]
I think I understand the usage of `children` now. It is the hierarchy stack to make the AppBar Up button works.
But, hmm, it means I need to manage the hierarchy every time I push.
