### ISSUE TITLE
Navigate to a new route smarter

### ISSUE THREAD

**Issue by nguyenxndaidev** [Milad-Akarie/auto_route_library#397]
It would be nice if we can find a way to automatically find the correct router context and the hierarchy when navigate.

If the current url is `/a` in `HomeRouter`, we want to navigate to `/public/a` in `PublicRouter`.
* Instead of `context.router.root.push(PublicRouter(children: [PublicRoute(), PublicARoute()]))`.
    It could be `context.router.push(PublicARoute())` to create a hierarchy stack `[PublicPage, PublicAPage]`.
    So the router should be smarter to know that, `PublicARoute` is belong to `PublicRouter` automatically.
    Developers should be allowed to build a logic somehow to create the hierarchy stack, so `push(PublicARoute())` will know that, the hierarchy is `[PublicPage, PublicAPage]`.
* Another problem is to support building a hierarchy stack, which contains pages from multiple routers.
    For example, instead of `[PublicPage, PublicAPage]`, we may want `[HomePage, PublicPage, PublicAPage]`

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      name: 'HomeRouter',
      page: HomeRouterPage,
      children: [
        AutoRoute(path: '', page: HomePage),
        AutoRoute(path: 'a', page: HomeAPage),
      ],
    ),
    AutoRoute(
      path: '/public',
      name: 'PublicRouter',
      page: PublicRouterPage,
      children: [
        AutoRoute(path: '', page: PublicPage),
        AutoRoute(path: 'a', page: PublicAPage),
      ],
    ),
  ],
)
```

**Comment by theweiweiway** [comment]
`router.root` is deprecated now and you can just `context.pushRoute`

If you want to push to a tabsRouter child, you can do `context.pushToChild` 

So it's a lot simpler now. Can you try with AutoRoute 2.x and close this issue if this is resolved?

**Comment by Milad-Akarie** [comment]
I think I know what's going on,do you still get the error of you set lazyLoad to false?
