### ISSUE TITLE
How to implement a Nested Navigation?

### ISSUE THREAD

**Issue by AndrewSheetMetal** [Milad-Akarie/auto_route_library#4]
Hi there!

Very cool packages, can save a lot of time!
I have one question: Is it already possible or planned to integrate Nested Navigation with your Package?
So that we have a NestedRouter Class or so.

Best regards
Andy

**Comment by Milad-Akarie** [comment]
Hey Andy, it is actually work in progress so stay tuned.

**Comment by kuhnroyal** [comment]
Was wondering about the same thing. Really love the simplicity of this library.

**Comment by Milad-Akarie** [comment]
@kuhnroyal Thanks, nested navigation handling will be included in the next build.

**Comment by Milad-Akarie** [comment]
done in version 0.2.0
