### ISSUE TITLE
Can't run the `/example` : auto_route_generator from path is forbidden

### ISSUE THREAD

**Issue by jerryzhoujw** [Milad-Akarie/auto_route_library#40]
` flutter packages pub run build_runner build `

> No .dart_tool/package_config.json file found, please run "pub get" first.  Starting with Dart 2.7 this file configures the resolution of package import URIs. Running "pub get" will generate this file.

`pub get`
> Resolving dependencies...
Because every version of auto_route_generator from path depends on auto_route from hosted and
  example depends on auto_route from path, auto_route_generator from path is forbidden.
So, because example depends on auto_route_generator from path, version solving failed.

**Comment by Milad-Akarie** [comment]
Hey, @jerryzhoujw can you please show me your pubspec file?

**Comment by jerryzhoujw** [comment]
hi @Milad-Akarie , I just run it in your `example/` folder.

**Comment by TshineZheng** [comment]
same here

**Comment by vasilich6107** [comment]
This is true the example is not working.
For the first time I have the same error as @jerryzhoujw 
When I update pubspeck to use versions instead of path it throws

```
Failed to precompile build_runner:build_runner:r pub run build_runner build                             
../../../.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:97:8: Error: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
../../../.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:129:8: Error: The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
pub finished with exit code 1

```

**Comment by JRamos29** [comment]
I tried to run the example and got the same error, that was solved with:

```
flutter clean
flutter pub upgrade
flutter pub get
```

But then during the build it couldn't find the target on ios build, due the project configuration, that has different environments. The solution was create a new flutter project and copy the content from the example's lib folder to the lib of the new project, and the dependencies of pubspec.yaml as well. Now it's working.

**Comment by raymondctc** [comment]
Not sure why, but this works for for me, using `dependency_overrides` to specify the path:
```
diff --git a/example/pubspec.yaml b/example/pubspec.yaml
index c0ac5c0..d706630 100644
--- a/example/pubspec.yaml
+++ b/example/pubspec.yaml
@@ -8,8 +8,8 @@ environment:
 dependencies:
   flutter:
     sdk: flutter
-  auto_route:
-    path: ../auto_route
+    #auto_route:
+    #path: ./auto_route/

 dev_dependencies:
   build_runner:
@@ -17,11 +17,19 @@ dev_dependencies:
   flutter_test:
     sdk: flutter
   auto_route_generator:
-    path: ../auto_route_generator
+    path: ../auto_route_generator/
   effective_dart: ^1.2.0
   hive_generator: ^0.8.1
   pedantic:

+dependency_overrides:
+  auto_route:
+    path: ../auto_route/
+
+
 flutter:
   uses-material-design: true
```

**Comment by theweiweiway** [comment]
Closing due to:
- stale issue
- seems to be a solution
