### ISSUE TITLE
Do not require optional fields in args

### ISSUE THREAD

**Issue by Nolence** [Milad-Akarie/auto_route_library#400]
Hello ! This is concerning null safe auto_route

Right now, when we generate code for a page like this:

```dart
class CoursePage extends StatelessWidget {
  final String? courseID;

  const CoursePage(
    Key? key,
    @PathParam('courseID') this.courseID,
  ) : super(key: key);
// ...
```

we get this

```dart
class CoursePageRoute extends _i1.PageRouteInfo<CoursePageRouteArgs> {
  CoursePageRoute({required this.key, required this.courseID})
      : super(name,
            path: ':courseID',
            args: CoursePageRouteArgs(key: key, courseID: courseID),
            params: {'courseID': courseID});
// ...
```

where the before optional `key` is now required in both the `CoursePageRoute` constructor and the in the `CoursePageRouteArgs`. I'd think it'd be more expected if stayed optional no?

So far awesome work on the null migration though :)

**Comment by nguyenxndaidev** [comment]
I confirm that I can reproduce the issue.

**Comment by Milad-Akarie** [comment]
Hey @Nolence @Nolence  in the above example key is a required positional parameter, you can not construct CourserPage without it.
am I missing something?

**Comment by Nolence** [comment]
Ah! You're totally right. Thought I had mistyped something but no, that is a positional required parameter and it makes sense it'd be required. Not sure how I overlooked that

Closing

**Comment by nguyenxndaidev** [comment]
> key is a required positional parameter, you can not construct CourserPage without it.

@Milad-Akarie Normally, I will put key inside `{}`. But why must I do it to construct `CourserPage`? The same question for `courseID`.

If I don't use auto_route, the widget in the example still works without using `{}`, right?

**Comment by nguyenxndaidev** [comment]
This is the code generation:
```
class CourseRoute extends _i1.PageRouteInfo<CourseRouteArgs> {
  CourseRoute({required this.key, required this.courseID})
      : super(name,
            path: '/course-page',
            args: CourseRouteArgs(key: key, courseID: courseID));

  final _i5.Key? key;

  final String? courseID;

  static const String name = 'CourseRoute';
}
```

Why don't we just remove required for nullable variables?
```
CourseRoute({this.key, this.courseID})
```

**Comment by Milad-Akarie** [comment]
@nguyenxndaidev I get your point of view but, I believe most dart programmers consider positional parameters required by convention besides, developers can simply put the key inside of curly brackets to make it optional,

**Comment by nguyenxndaidev** [comment]
> @nguyenxndaidev I get your point of view but, I believe most dart programmers consider positional parameters required by convention besides, developers can simply put the key inside of curly brackets to make it optional,

For `key`, it's ok. But I think we should cover general cases because of 2 reasons:
* If the widget is from external package, they cannot do it.
* They don't need to refactor there code

IMO, this issue could be in low priority because `CourseRoute` still works. But it should still need to be fixed.
