### ISSUE TITLE
Proposal: Change AutoRouter.declarative to match flutter naming scheme

### ISSUE THREAD

**Issue by essarn** [Milad-Akarie/auto_route_library#403]
I think the `AutoRouter.declarative` constructor should be renamed to `AuthRouter.builder` since that is the naming scheme that flutter uses for "builder" like widgets. Also in that case would the property `children` make more sense than the current `onGenerateRoutes`.

So in short, my proposal is. Change `AutoRouter.declarative` to `AuthRouter.builder` and `onGenerateRoutes` to `children`.

**Comment by Milad-Akarie** [comment]
@essarn interesting thought, but I don't think usual factory builders in flutter and declarative version of StackRouter are the same, beside AutoRouter widget has a builder property, don't you think that might be misleading? 

I'll leave this open, we may be able to gather more opinions.

**Comment by theweiweiway** [comment]
I kinda like it the way it is right now :octocat: 🐙 🌊

**Comment by essarn** [comment]
Yeah the current naming works just fine having worked with it a bit.
