### ISSUE TITLE
default argument

### ISSUE THREAD

**Issue by masseelch** [Milad-Akarie/auto_route_library#404]
Hi,

i am testing your current release of auto_route: 1.0.0.

The [docs](https://autoroute.vercel.app/basics/passing_arguments) say: 

> **Note**: Default values are respected. Required fields are also respected and handled properly.

However this:
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(path: '/login', page: LoginPage),
    AutoRoute(
      path: '/',
      guards: [AuthGuard],
      page: HomePage,
    ),
  ],
)
class $AppRouter {}

class LoginPage extends StatefulWidget {
  LoginPage({this.onLogin = defaultLoginHandler});

  final VoidCallback onLogin;

  @override
  _LoginPageState createState() => _LoginPageState();
}
defaultLoginHandler() {
  print('I am the defaultLoginHandler');
}
```
generates this:
```dart
class LoginRoute extends _i1.PageRouteInfo<LoginRouteArgs> {
  LoginRoute({this.onLogin})
      : super(name, path: '/login', args: LoginRouteArgs(onLogin: onLogin));

  final void Function() onLogin;

  static const String name = 'LoginRoute';
}
```

This will not compile. 
```
lib/router/router.gr.dart:51:20: Error: The parameter 'onLogin' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  LoginRoute({this.onLogin})
```

Am I doing something wrong?

I know I can workaround this by making the `onLogin` callback nullable and checking for it to be non-null before calling it, but the above one feels cleaner.

**Comment by Milad-Akarie** [comment]
@masseelch The route object shouldn't have arg fields after the new refactor, I'm working on the fix.

**Comment by Milad-Akarie** [comment]
@masseelch
onLogin is not proceeded with a required keyword nor it's  positional.

 I think the real problem here is that default importable elements are not handled and I don't think there's an easy way to handle them. 
 the way I see it a decent workaround would be 
 
 
```dart
class LoginPage extends StatelessWidget {
  final VoidCallback _onLogin;

  LoginPage({
    Key? key,
    required VoidCallback onLogin,
  })
      : _onLogin = onLogin ?? defaultLoginHandler,
        super(key: key);
}
 
```

**Comment by masseelch** [comment]
I have onLogin nullable with a check if it's null an call the default if so. Works like a charm.

Should I leave this open? It still is a bug since it behaves different from what the docs say. If there is no solution to this, the docs should be changed and maybe we could add a FAQ for this kind of questions?

**Comment by kthecoder** [comment]
Is this the same issue as using a required parameter?

```
Class MyClass1 extends HookWidget {
  final Object objectData;
  final Object2? object2Data;
  final Object3 object3Data;

  const MyClass1({
    @PathParam('objectData') required this.objectData,
    @PathParam('object2Data') this.object2Data,
    @PathParam('object3Data') this.object3Data = 0,
  });
```

Where the above code returns an error during build_runner build:

```
Path/Query parameters must be nullable or have a default value
   ╷
20 │     @PathParam('objectData') required this.objectData,
   │                                            ^^^^^^^^^^
   ╵
```

**Comment by rmargolinross** [comment]
I have just recently hit his issue while on version 2.2.0. I fee like this was working before, so I wonder if an update to build_runner or something has broken this? I would love a work around that doesn't involve manually editing the generated file or something.

**Comment by theweiweiway** [comment]
@rmargolinross same here, I'm almost certain it's build_runner 2.0.4 that is causing the issue. I downgrade to 2.0.3 and everything is good to go~

**Comment by rmargolinross** [comment]
I have tried downgrading build runner to 2.0.3 and 2.0.2 to no avail, so I do not think that is the issue.

**Comment by rmargolinross** [comment]
I have also tried making a fork and version locking all of the things I could in the pubspec of auto_route_generator (removed all of the ^) and the issue still stands. I am not sure what changed a few days ago that started this. It was fine on the 26th and then stopped working on the 27th.

**Comment by rmargolinross** [comment]
Okay, I think I found a clue as to the issue. I was able to get my build working by overriding the dependency for analyzer to version 1.5.0. build_runner references analyzer ^1.4.0 and it was updated to 1.7.1 a few days ago.

Again, so for a temporary work around add in your pubspec.yaml

```
dependency_overrides:
  analyzer: 1.5.0
```

**Comment by dfdgsdfg** [comment]
https://github.com/Milad-Akarie/auto_route_library/issues/590

**Comment by rmargolinross** [comment]
I do wonder if this will ever be fixed. I now have to override source_gen as well to prevent other issues, as that now requires analyzer 2.0.0

**Comment by semsturgut** [comment]
same here 😕

**Comment by SettiNitesh** [comment]
@RoutePage()
class LoginPage extends StatefulWidget {
  final Function(bool) onResult;

  LoginPage({
    Key? key,
    void Function(bool)? onResult,
  }) : this.onResult = onResult ?? ((bool isLoggedIn) => isLoggedIn);

  @override
  State<LoginPage> createState() => _LoginPageState();
}


   LoginPage({
    Key? key,
    void Function(bool)? onResult,
  }) : this.onResult = onResult ?? ((bool isLoggedIn) => isLoggedIn);
  
  //  you can try this it will work
