### ISSUE TITLE
Required argument with PathParam Annotation

### ISSUE THREAD

**Issue by masseelch** [Milad-Akarie/auto_route_library#405]
How can i map a required non-nullable parameter in a widget constructor with `@PathPatam`-Annotation?

```dart
class DisplayDetailPage extends StatefulWidget {
  DisplayDetailPage({required this.displayId});
  
  final String displayId;

  @override
  _DisplayDetailPageState createState() => _DisplayDetailPageState();
}

AutoRoute(
      path: '/displays',
      guards: [AuthGuard],
      page: DisplayListPage,
      children: [
        AutoRoute(
          path: ':id',
          page: DisplayDetailPage,
        ),
      ]
    ),
```

The generator will tell me to use a `@PathPatam` Annotation but adding it to the constructor does not work since i need to remove the required keyword, but then dart won't compile.

```dart
DisplayDetailPage({@PathParam('id')  required this.displayId}); // <- This wont compile.
```

**Comment by Milad-Akarie** [comment]
@masseelch you're gonna have to give it a default value -1 for example.

**Comment by Milad-Akarie** [comment]
@masseelch  try giving it a default value. -1 for example.

**Comment by masseelch** [comment]
That works as workaround yes. Are the plans to change this? I don't know it dart has some limits which made you do it this way.

**Comment by Milad-Akarie** [comment]
Yes there are some limitations when leaving that required. I might be able to come up with better ways to handle this in future builds but right now path Parameters must be nullable or have a default value.

I think the nullable approach is good enough?

**Comment by masseelch** [comment]
It is yes. Thank you!
