### ISSUE TITLE
'AppRouter' doesn't extend 'RouterBase'

### ISSUE THREAD

**Issue by alphamanorg** [Milad-Akarie/auto_route_library#407]
Hi, I'm having some problems with the latest version. 
ExtendedNavigator.builder<r.AppRouter> giving 'AppRouter' doesn't extend 'RouterBase' error. Please help.

**Comment by ramzed** [comment]
I have the same problem.

**Comment by Milad-Akarie** [comment]
If you're still using the legay version ( ExtendedNavigator) set usesLegacyGenerator to true inside of MaterialAutoRouter

**Comment by PieterHartzer** [comment]
> If you're still using the legay version ( ExtendedNavigator) set usesLegacyGenerator to true inside of MaterialAutoRouter

What is the process to upgrade?  The `Finalize the setup` step on the website isn't clear on how to set it up if you have anything else in MaterialApp.
