### ISSUE TITLE
The parameter type 'dynamic' is incompatible with the field type 'AuthGuard'.

### ISSUE THREAD

**Issue by dirkhe1051931999** [Milad-Akarie/auto_route_library#411]
after **flutter packages pub run build_runner build**  
index.gr.dart have a error  
![image](https://user-images.githubusercontent.com/22389976/111614661-cb85c180-881a-11eb-91dd-a3ea50135405.png)
auth_guard.dart
![image](https://user-images.githubusercontent.com/22389976/111614687-d2143900-881a-11eb-98cf-33129ee4caf3.png)
router.dart
![image](https://user-images.githubusercontent.com/22389976/111614706-d9d3dd80-881a-11eb-8c8e-85988ffb80bb.png)

environment:
  sdk: ">=2.7.0 <3.0.0"
# auto_route
  auto_route: ^1.0.1

 auto_route_generator: ^1.0.1
  build_runner:

i dont update sdk version because it will happen others lot of error

**Comment by Milad-Akarie** [comment]
@dirkhe1051931999 you need to downgrade to version 0.6.9 then.
