### ISSUE TITLE
Drop legacy generator support?

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#412]
Hello @all,
I'm just wondering if there's still some users stuck with legacy generator? and by 'legacy' I mean the old generator that's based on Navigator v1 and is using `ExtendedNavigator`.

Maintaining the package is a-lot of work as is, besides, backward compatibility is holding auto_route back in some areas.

so, do you guys think we should drop it?

**Comment by theweiweiway** [comment]
Yes - It's an incredible amount of work to keep going forward with this package while making sure legacy works and everything. This will definitely let you work faster going forward.

Actually, I'm currently using version 0.6.9 in production at our start-up. It works great, and we haven't found a need to update to 1.0.x. I just use flutter version manager to switch between projects and everything works great.

Except cocoapods sometimes. i fookin hate cocoapods.

**Comment by AscentionOne** [comment]
Yes, I agree with @theweiweiway. Eventually, we have to migrate to Navigation 2.0. I am already using 2.0. If it takes a lot of effort to maintain backward compatibility, I think for the long run of the auto_route package we have to drop the legacy one. Thanks for the great work @Milad-Akarie 👍

**Comment by masseelch** [comment]
Yes, i think you should just freeze the legacy generators and accept PRs which fix crucial bugs (if any occur in the future). And like @theweiweiway I have several versions of flutter for older projects.

**Comment by theweiweiway** [comment]
I think a decision was made on this - so gonna close it
