### ISSUE TITLE
Async operations in a declarative router

### ISSUE THREAD

**Issue by WasserEsser** [Milad-Akarie/auto_route_library#413]
Hi, 

this is not an issue per-se, but I've run into this and was wondering if you have any thoughts on a clean implementation of my flow.

I want to use a declarative router for one of my flows. 
The flow goes as follows:

Check Permissions

if (permissions are not granted)
   Missing Permissions Page -> Exit flow/re-initiate flow after AppLifecycle changes (might show a button to the permission settings)

if (permissions are granted)
  Check if data exists in sqlite db

if (data doesnt exist)
  Data Creation Page

if (data exists)
  Data Overview Page (user can go from here and edit/create more data)

if (submit)
  Network request with data

if (request done)
  Success

if (request failed)
  Error

Now, because checking if permissions are granted and checking if data exists in the db are two async operations, I would need a page that just checks these things. I have not implemented this yet, but wouldn't that initiate page transitions? Is there a way to disable these page transitions? These pages would only really show a loading indicator for a fraction of a second. Initiating a page transition would most likely result in a bad user experience because the user can't really follow whats happening. 

Additionally, are these two pages even necessary? An if (await) statement would be enough for my use case, but onGenerateRoutes does not support an async function.

Whats the best way to implement such a flow cleanly?

**Comment by Milad-Akarie** [comment]
@WasserEsser onGenerteRoutes is called inside of a build method so there's no way it can be async, 
If you don't have a specific reason to use a flow I believe what you need is an AutoRouteGuard, You can redirect your user to any page after you've done your async work. 
p.s CustomRoute have no transition animation by default.

**Comment by WasserEsser** [comment]
@Milad-Akarie Thanks for the response. 

Route guards seem to be the best solution. 
I also didn't know that CustomRoutes don't contain a transition animation by default, that's pretty useful. 
Thanks!
