### ISSUE TITLE
compatibility issue with build_runner: ^1.12.2

### ISSUE THREAD

**Issue by mbmshafraz** [Milad-Akarie/auto_route_library#415]
Because build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0 and auto_route_generator 1.0.1 depends on build ^1.5.0, build_runner >=1.12.0 is incompatible with auto_route_generator 1.0.1.
And because no versions of auto_route_generator match >1.0.1 <2.0.0, build_runner >=1.12.0 is incompatible with auto_route_generator ^1.0.1.
So, because wreckfinder depends on both auto_route_generator ^1.0.1 and build_runner ^1.12.2, version solving failed.
pub get failed (1; So, because wreckfinder depends on both auto_route_generator ^1.0.1 and build_runner ^1.12.2, version solving failed.)

**Comment by Milad-Akarie** [comment]
@mbmshafraz  I just pushed a fix a second ago, can you confirm? 
auto_route 1.0.2

**Comment by mbmshafraz** [comment]
@Milad-Akarie now error massage is gone. Thanks
