### ISSUE TITLE
[Bug] Can not use `customRouteBuilder` on `CustomRoute`

### ISSUE THREAD

**Issue by hffmnn** [Milad-Akarie/auto_route_library#416]
I am trying to use `modal_bottom_sheet` as a dependency. So I wanted to add a `customRouteBuilder` on `CustomRoute`.

Given I have the following annotation:

```dart
@CustomAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      usesTabsRouter: true,
      children: [
        RedirectRoute(path: '', redirectTo: 'profile'),
        AutoRoute(
          path: 'books',
          page: EmptyRouterPage,
          name: 'BooksTab',
          children: [
            AutoRoute(path: '', page: BookListPage),
            CustomRoute(page: BookDetailsPage, path: ':id', customRouteBuilder: (constext, page) {}),
... rest of the code from `example`
```

This gives the following errors:
```
Arguments of a constant creation must be constant expressions.
Try making the argument a valid constant, or use 'new' to call the constructor.
```
```
The values in a const list literal must be constants.
Try removing the keyword 'const' from the list literal.
```
```
Invalid constant value.
```

<img width="1252" alt="Screenshot 2021-03-20 at 23 40 03" src="https://user-images.githubusercontent.com/352753/111887476-9a9dbc00-89d5-11eb-8d3c-b28ce4244c5e.png">

Any ideas? And: Is this the typical way to integrate a custom route?

**Comment by Milad-Akarie** [comment]
@hffmnn  You can only pass static code to an annotation in dart. 
try doing it like this

```dart
// define your builder as a global function or a static member
Route myCustomRouteBuilder (context, page) {
 // construct and return your route
}

// pass myCustomRouteBuilder function as a reference
CustomRoute(page: BookDetailsPage, path: ':id', customRouteBuilder: myCustomRouteBuilder}),
...

```

**Comment by hffmnn** [comment]
Thanks, @Milad-Akarie, that did the trick.

But this produces a follow up:

```
class CustomRoutes {
  static const modal = _modal;

  static Route _modal(BuildContext context, Widget child, CustomPage page) {
    return MaterialWithModalsPageRoute(builder: (BuildContext context) {
      return page;
    });
  }
}
...
CustomRoute(
                page: BookDetailsPage,
                path: ':id',
                customRouteBuilder: CustomRoutes.modal),
```
This gives the following error:

<img width="730" alt="Screenshot 2021-03-23 at 09 58 39" src="https://user-images.githubusercontent.com/352753/112120364-6f29f580-8bbe-11eb-9c26-a7bcc1b9ac93.png">


Sorry for the noise, but is there any example on how to achive that?

**Comment by Milad-Akarie** [comment]
@hffmnn Does materialWIthModealPageRoute take a settings arg?

**Comment by hffmnn** [comment]
Yes, it does:

```
MaterialWithModalsPageRoute({
    required WidgetBuilder builder,
    RouteSettings? settings,
    bool maintainState = true,
    bool fullscreenDialog = false,
  })  
```

**Comment by Milad-Akarie** [comment]
try this
```dart
static Route _modal(BuildContext context, Widget child, CustomPage page) {
    return MaterialWithModalsPageRoute(builder: (BuildContext context) {
         // you want to return the widget not the page here
      return child;
    },
// this is required
    settings: page, 
    );
  }
```

**Comment by hffmnn** [comment]
This works (aka. does not throw an error) and also calls the builder. Still, the transition looks like a typical push. But I guess this is a fault on my side and not this library. Guess we can close the issue?

**Comment by Milad-Akarie** [comment]
ya, you're the one building the route now.

**Comment by badsmuggler** [comment]
Hi guys @hffmnn & @Milad-Akarie, 
I've still an issue with this. I follow exactly what you did before, so : 

I create a CustomRoute : 

```
CustomRoute(. 
  opaque: true,  
  fullscreenDialog: true,  
  path: '/gallery',  
  name: 'GalleryRoute',  
  page: GalleryPage,  
  customRouteBuilder: myCustomRouteBuilder,  
  transitionsBuilder: TransitionsBuilders.slideLeft,  
)
```
And then my method for the customRouteBuilder : 


```
Route myCustomRouteBuilder(BuildContext context, Widget child, CustomPage page) {
  return MaterialWithModalsPageRoute(
    builder: (BuildContext context) {
      return child;
    },
    settings: page,
  );
}
```

Unfortunately, when the `router.gr.dart` file is generated, it's throwing an error : 

`Error: The argument type 'Route<dynamic> Function(BuildContext, Widget, CustomPage<dynamic>)' can't be assigned to the parameter type 'Route<T> Function<T>(BuildContext, Widget, CustomPage<dynamic>)?'.`

Do you know how I can solve this? 

Thx for your time and reply!

**Comment by YasserOJ** [comment]
@Milad-Akarie  hello the solution you provided is not valid after adding null safety to flutter 
can you check it please
![Screen Shot 2021-07-06 at 16 11 02](https://user-images.githubusercontent.com/26030291/124624635-f56bfe00-de74-11eb-9ccc-03295134d070.png)

**Comment by zvikarp** [comment]
Hey @Milad-Akarie  just hit the issue, here is how I solved it:

```
class CustomRoutes {
  static const Route<T> Function<T>(BuildContext, Widget, CustomPage<dynamic>) modal = _modal;

  static Route<T> _modal<T>(
      BuildContext context, Widget child, CustomPage<dynamic> page) {
    return MaterialWithModalsPageRoute<T>(
      builder: (BuildContext context) {
        return child;
      },
      settings: page,
    );
  }
}
```
