### ISSUE TITLE
appRouter.pop() pops too far

### ISSUE THREAD

**Issue by WasserEsser** [Milad-Akarie/auto_route_library#420]
Hi!

This is my router setup:

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      page: Home,
      path: "/",
      initial: true,
    ),
    AutoRoute(
      path: "/scans",
      name: 'ScanRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(
          path: 'users',
          name: 'ScanUserRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: Users,
            ),
            AutoRoute(
              path: 'create',
              page: Create,
            ),
          ],
        ),
      ],
    ),
  ],
)
class $AppRouter {}
```

From my Home page, I navigate to the Users page like this:

```
AutoRouter.of(context).push(
  ScanRouter(
    children: [
      ScanUserRouter(
        children: [
          UsersRoute(),
        ],
      ),
    ],
  ),
)
```

Inside my Users page, when a certain condition is true, I navigate to the Create page like this:

`AutoRouter.of(context).push(CreateRoute());`

Now, inside the Create page, calling pop() results in the navigator going all the way back to the Home page.
Is this intentional? How should I navigate instead to have a 'normal' navigation flow?

**Comment by WasserEsser** [comment]
I forgot to mention the version I'm using. 
I'm using version 1.0.2.

**Comment by WasserEsser** [comment]
After a few more tries, I found out this is caused whenever I try to pop through a global AppRouter instance.
Calling pop on a contextual router object (AppRouter.of(context) for example), it navigates back just fine.

I'm calling this through a chain of callbacks, so it would be cleaner if I could pop without passing down the context through multiple callback functions.

**Comment by WasserEsser** [comment]
I believe this is because the `current` RouteData on the global AppRouter instance is the ScanRouter.
So with multiple nested routers registered and navigating to sub-pages of the nested routers, the global AppRouter instance pops the routers instead of individual pages.

Seeing this, it's most likely intended behavior. However, it would be nice if we could pop individual pages from the nested routers through a global AppRouter instance (if possible).

**Comment by Milad-Akarie** [comment]
@WasserEsser I'm gonna start with some irrelevant tips
```dart
AutoRouter.of(context).push(
  ScanRouter(
    children: [
      ScanUserRouter(
        children: [
          // usersRoute has an Empty path '' so unless you want to pass some args to it 
          // you don't need  to pass it here as it's pushed automatically
          UsersRoute(),
        ],
      ),
    ],
  ),
)
```

```dart
 AutoRoute(
      page: Home,
      path: "/", 
       // setting initial to true here is redundant as it only sets the path to '/'
       // which you already specified
      initial: true,
    ),
```
and yes Nested Routers are also stack entries so if you pop that entry the whole branched-stack goes with it. 

luckily there's a way to access child routers from their parents using the `innerRouterOf` method

` _appRouter.innerRouterOf(ScanRouter.name).pop();`

**Comment by WasserEsser** [comment]
@Milad-Akarie thanks for the tips. 

`innerRouterOf` and `topMost` are definitely useful, as they fix a number of issues such as trying to replace the current route from the root router not working. With `(appRouter.topMost as StackRouter).replace()`, this works nicely.

**Comment by theweiweiway** [comment]
I can take a crack at the documentation
