### ISSUE TITLE
setState after dispose

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#421]
I'm getting `setState() called after dispose()` exception after calling:

```dart
tabsRouter.stackRouterOfIndex(0).replace(ConversationsRoute(folder: 'archived'));
```

 from `ConversationsRoute(folder: 'active')`

Here is the router:

```dart
AdaptiveRoute(
      initial: true,
      guards: [AuthGuard],
      path: '/',
      page: DashboardView,
      usesTabsRouter: true,
      children: [
        RedirectRoute(path: '', redirectTo: 'folder'),
        AdaptiveRoute(
          path: 'folder',
          page: EmptyRouterPage,
          name: 'FolderRoute',
          children: [
            RedirectRoute(path: '', redirectTo: 'active'),
            AdaptiveRoute(path: ':folder', page: ConversationsView),
          ],
        ),
      ],
    ),
```

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for BranchEntry:
setState() called after dispose(): AutoRouterState#424f1(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1231:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1266:6)
#2      AutoRouterState.didChangeDependencies.<anonymous closure> (package:auto_route/src/router/widgets/auto_router.dart:71:9)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
#4      BranchEntry._addEntry (package:auto_route/src/router/controller/routing_controller.dart:672:7)
...
The BranchEntry sending notification was: FolderRoute
====================================================================================================
```

Am I doing something wrong ?

**Comment by Milad-Akarie** [comment]
@Herrera93 you don't seem to be anything wrong.
does this happen all the time or as a result of other events? How do I reproduce it? 
also are you using the latest versions of auto_route and auto_route_generator?

**Comment by ayushin** [comment]
I get the same after I rebuild the layout as a result for example of web browser window resize

>>> setState() called after dispose(): AutoRouterState#ba1b3(lifecycle state: defunct, not mounted)

**Comment by ayushin** [comment]
adding if(mounted) seem to fix the problem without any side effects..

But same story with autoTabsRouter

>>> A ParallelBranchEntry was used after being disposed.
packages/auto_route/src/router/widgets/auto_tabs_router.dart 104:18           dispose

**Comment by ayushin** [comment]
competing this out  in packages/auto_route/src/router/widgets/auto_tabs_router.dart:104
    // _controller?.dispose();

also seem to solve the problem for the tabsRouter

What can be the route cause @Milad-Akarie ?

**Comment by ayushin** [comment]
Actually another similar problem auto_tabs_router.dart:92 : 

```
        if(mounted) {
          setState(() {
            _index = _controller!.activeIndex;
          });
        }
```

**Comment by ayushin** [comment]
OK the problem is not removing listener in dispose, PR coming

**Comment by ayushin** [comment]
https://github.com/Milad-Akarie/auto_route_library/pull/469

The problem with auto_tabs_router seems to be different - to start with dispose is called multiple times...

**Comment by ayushin** [comment]
@Herrera93  can you please check if the below works for you:

```
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/apexlabs-ai/auto_route_library
      path: auto_route
      ref: orhpaned-listeners-fix
```

**Comment by ayushin** [comment]
Hi @Milad-Akarie 

This is still broken. While I no longer get the error messages the rebuilding of the routes does not work after flutter web resize - i end up with a blank page and no errors.

**Comment by Milad-Akarie** [comment]
@ayushin please share your router setup and where you're making the call from.

**Comment by ArintonAkos** [comment]
I have this problem too. The problem happens when i long click the container, the popup appears the when i click on the button which pops the context, it throws the error

My router app:
`
MaterialApp.router(
                locale: language.appLocal,
                supportedLocales: const [
                  Locale('en', ''),
                  Locale('ro', ''),
                  Locale('hu', '')
                ],
                localizationsDelegates: const [
                  AppLocalizations.delegate,
                  GlobalMaterialLocalizations.delegate,
                  GlobalWidgetsLocalizations.delegate
                ],
                title: 'MyInstrument',
                theme: theme.getTheme()?.materialTheme,
                routerDelegate: AutoRouterDelegate.declarative(
                  _appRouter,
                  routes: (_) => [
                    /*if (initialize.initialized)
                      if (isSignedIn)
                        const BaseRouter(children: [MainRoute()])
                      else if (initialize.boardingCompleted)
                        const AuthRouter(children: [LoginRoute()])
                      else
                        OnBoardRoute()
                    else
                      SplashRoute()*/
                    BaseRouter(children: [MainRoute()])
                  ]
                ),
                routeInformationParser: _appRouter.defaultRouteParser(includePrefixMatches: true),
              )
            )`


This is my main_page.dart file, it opens HomeRoute default.

`
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: SizedBox(
          width: 150,
          height: 150,
          child: CupertinoContextMenu(
            actions: [
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text('asdsd'),
              )
            ],
            child: Container(
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  color: Colors.red
              ),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
`

**Comment by ArintonAkos** [comment]
I am using auto_route: ^3.2.0

**Comment by Adam-Langley** [comment]
I'm having this exact same issue. I can reproduce it 100% of the time.
I've tracked it down to this piece of code:

<img width="942" alt="image" src="https://github.com/user-attachments/assets/7c369cce-5251-44e7-ac2e-56543b47e7e5">

I can see that on line 672, this._debugDisposed == false, then on line 676 (within post-frame callback) this._debugDisposed == true - hence the notifyAll (line 668) throws the exception.
