### ISSUE TITLE
Tab routes can not have guards

### ISSUE THREAD

**Issue by AlexanderFarkas** [Milad-Akarie/auto_route_library#422]
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: "/login",
      page: LoginWrapperPage,
      children: [
        AutoRoute(page: EmailPage),
        AutoRoute(page: PasswordPage),
      ]
    ),
    AutoRoute(
      path: "/",    
      page: HomePage,
      usesTabsRouter: true,
      children: [    
        AutoRoute(
          path: "books",
          name: "BooksRouter",
          page: BooksWrapperPage,
          children: [
            AutoRoute(path: "", page: BooksPage),
            AutoRoute(path: "details", page: BookDetailsPage),
            RedirectRoute(path: "*", redirectTo: ""),
          ], 
        ),
        AutoRoute(
          path: "account",
          name: "AccountRouter",
          guards: [AuthGuard], // Adding AuthGuard here will 
          // guard all account routes, ensuring that the user
          // must be logged in to access them
          page: EmptyRouterPage,
          children: [
            AutoRoute(path: "", page: AccountPage),
            AutoRoute(path: "details", page: AccountDetailsPage),
            RedirectRoute(path: "*", redirectTo: ""),
          ],
        ),
      ],
    ),
  ],
)
class $AppRouter {}
```

This doesn't work and says "Tab routes can not have guards"

**Comment by SashaFarkas** [comment]
It would be good, if we couldn't switch to account tab (every click on bottom nav item would push AuthRoute)

**Comment by theweiweiway** [comment]
In the meantime in your `AccountRouter` you can make an `AccountWrapperPage` that replaces `EmptyRouterPage` and check if the user is logged in inside of that wrapper page. 

if logged in, continue. If not, push to login page

**Comment by KholmatovS** [comment]
> In the meantime in your `AccountRouter` you can make an `AccountWrapperPage` that replaces `EmptyRouterPage` and check if the user is logged in inside of that wrapper page.

Hello. I'm also faced with this situation right now. If it is possible, can you give more detailed explaination, please? I couldn't find any documentation about routers' customization in order to implement this kind of wrapper. Thank you advance.

**Comment by shadowBoss12-sta** [comment]
Hello. Also facing same issue . Any help will be appreciated. Thanks in Advance

**Comment by miaosun009** [comment]
你好。也面临着同样的问题。任何帮助将不胜感激。提前致谢

**Comment by oyont** [comment]
> In the meantime in your `AccountRouter` you can make an `AccountWrapperPage` that replaces `EmptyRouterPage` and check if the user is logged in inside of that wrapper page.
> 
> if logged in, continue. If not, push to login page

Logic works but when back button pressed on login page, router navigates to empty screen
