### ISSUE TITLE
Firebase Analytics navigatorObservers on auto_route >= 1.0.0

### ISSUE THREAD

**Issue by brizaldi** [Milad-Akarie/auto_route_library#424]
Hi,
From the firebase analytics [documentation](https://pub.dev/packages/firebase_analytics#track-pageroute-transitions), to allow Tracking PageRoute Transitions we need to add a `FirebaseAnalyticsObserver` to the list of `NavigatorObservers` like this:

```dart
FirebaseAnalytics analytics = FirebaseAnalytics();

MaterialApp(
  home: MyAppHome(),
  navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics),
  ],
);
```

Is there a way to add this `navigatorObservers` because last time I check the current version of auto_route doesn't support it

**Comment by SashaFarkas** [comment]
```
return MaterialApp.router(
      title: "My app",
      builder: (context, child) {
        return child;
      },
      theme: _getTheme(context),
      routerDelegate: _appRouter.delegate(
        navigatorObservers: []
      ),
      routeInformationParser: _appRouter.defaultRouteParser(),
    );
```

**Comment by brizaldi** [comment]
Thank you @SashaFarkas
