### ISSUE TITLE
Future is resolved too soon

### ISSUE THREAD

**Issue by P1-Ro** [Milad-Akarie/auto_route_library#425]
When using `context.router.push(...).then` it doesn't behave exaclty as `Navigator.push(...).then`.
Navigators future is resolved when pushed route is popped, current implementation resolves future as soon as it is pushed.

Is there currently any way i can achieve same result with auto_route?

**Comment by finroly** [comment]
have you found any solution to this issue?

**Comment by P1-Ro** [comment]
Not yet, I am hoping to get help here. I know something like this could be done, but i really don't like it.
```
context.router.push(
      BookDetailsRoute(
          book: book,
          onRateBook: (rating) {
           // handle result
          }),
    );
```

**Comment by Milad-Akarie** [comment]
@P1-Ro please refer to #432
