### ISSUE TITLE
Initial index for AutoTabsRouter

### ISSUE THREAD

**Issue by nkokhan** [Milad-Akarie/auto_route_library#426]
How to set initial index to AutoTabsRouter widget? In my case, the initial index is 1 non 0.

**Comment by Milad-Akarie** [comment]
@nkokhan If you don't need to set the initial index dynamically you could use  a RedirectRoute() to set your initial destination. 
`RedirectRoute(path: '', redirectTo: 'myHomeTap');`

**Comment by nkokhan** [comment]
> @nkokhan If you don't need to set the initial index dynamically you could use a RedirectRoute() to set your initial destination.
> `RedirectRoute(path: '', redirectTo: 'myHomeTap');`

Where I should use this?

**Comment by nkokhan** [comment]
I figured it out! 'redirectTo' it's a path, not name, for another page. I tried with name first. A bit confusing implementation, but it works. Thanks! U make amazing work!
