### ISSUE TITLE
pushAndRemoveUntil pushes page more then 8 times

### ISSUE THREAD

**Issue by NarHakobyan** [Milad-Akarie/auto_route_library#435]
I tried to push DashbardPage but noticed that the initState function gets called more than 8 times

```
    await router.pushAndRemoveUntil(const DashboardPage(),
        predicate: (r) => false);
```

Tried to replace it with `router.push(const DashboardPage())` to check if it calls only once or not and that's worked, so problem comes from `pushAndRemoveUntil`.

Note: It happens only on **production**, on debug mode it's working as expected.

**Comment by Milad-Akarie** [comment]
@NarHakobyan The pop until part is implemented by the Navigator. 
This's the implementation of pushAndRemoveUntil
```dart
  @override
  Future<void> pushAndRemoveUntil(
    PageRouteInfo route, {
    required RoutePredicate predicate,
    OnNavigationFailure? onFailure,
  }) {
    popUntil(predicate);
    return push(route, onFailure: onFailure);
  }
```
maybe try to use popUntil without the push part see if you still get the error? 
also you could try
`replaceAll([DashboardPage()]);`

**Comment by NarHakobyan** [comment]
@Milad-Akarie `replaceAll([DashboardPage()]);` have the same behavior as `router.pushAndRemoveUntil(const DashboardPage(), predicate: (r) => false);`

Code below works as expected but I think it's a little bit not elegant.

```
router.push(const DashboardPage());
router.removeUntil((route) => route.name == DashboardPage.name);
```
