### ISSUE TITLE
Generated code cause compilation error when using implicit-dynamic analyzer rule

### ISSUE THREAD

**Issue by edwardaux** [Milad-Akarie/auto_route_library#438]
I use `implicit-dynamic: false` in my `analysis_options.yaml`  file, but have noticed with the 1.0.2 generator that it generates the following for a simple `SplashScreen` class with no arguments:

```
class SplashScreenRoute extends _i1.PageRouteInfo {
  const SplashScreenRoute() : super(name, path: '/splash-screen');

  static const String name = 'SplashScreenRoute';
}
```
The compiler complains because it wants the generated route to inherit from `_i1.PageRouteInfo<void>` instead of just `_i1.PageRouteInfo`. 

Note that if I add a parameter to my `SplashScreen` class, it generates the following:
```
class SplashScreenRoute extends _i1.PageRouteInfo<SplashScreenRouteArgs> {
  ...
}
```
Is there any reason why the generator couldn't use `<void>` as the type for `PageRouteInfo`

**Comment by Milad-Akarie** [comment]
Hey @edwardaux, PageRouteInfo is annotated with `@optionalTypeArgs ` you would think the analyzer will respect this, lol
```dart
@optionalTypeArgs
class PageRouteInfo<T> {}
```
I guess I could have it implement 'dynamic' when there are no args.

**Comment by edwardaux** [comment]
Looks like there's a (long-standing) defect open for this already: https://github.com/dart-lang/sdk/issues/32538. I don't think that it is going to be fixed soon.

FWIW, though, I reckon the generated code should be `_i1.PageRouteInfo<void>`, rather than `_i1.PageRouteInfo<dynamic>`.  Using `<dynamic>` implies that there could actually be a type for the args... whereas using `<void>` is a signal that there definitely won't (can't) be any params.
