### ISSUE TITLE
Are there other ways to initialize the navigator?

### ISSUE THREAD

**Issue by matthewfx** [Milad-Akarie/auto_route_library#441]
Hey,

Before the Navigator 2.0 changes, it was possible to initialize the navigator like: 
```
child: ExtendedNavigator<FormRouter>(
            router: MainRouter(),
            initialRoute: '/',
            initialRouteArgs: LoadingPageArguments(
                configBloc: widget.configBloc),
          )),
```
Now it seems it has to use the MaterialApp like:

```
child: MaterialApp.router(
              routeInformationParser: _appRouter.defaultRouteParser(),
              routerDelegate: _appRouter.delegate(initialRoutes: [
                LoadingRoute(
                    configBloc: widget.configBloc),
              ]),
              theme: Theme.of(context),
              debugShowCheckedModeBanner: false,),
```

Is there any other way? I'd rather avoid nesting Material apps.
Thank you for your work Milad!

**Comment by Milad-Akarie** [comment]
Hey @matthewfx  What do you mean by nesting MaterialApps? 
you could always provide a Router widget in the builder function or as a home widget.

**Comment by matthewfx** [comment]
Hey, @Milad-Akarie By nesting, I meant that I initialize the router deeper within the app not in the main.dart so I would have 2 MaterialApps in the end. This is probably fine but I wanted to know if there is another way. How can I use a Router widget to pass initial params etc. I haven't seen it in the docs I believe.

**Comment by Milad-Akarie** [comment]
@matthewfx oh! nested routers are initialized differently. their controllers are automatically injected in the context so you won't have to worry about that, The only thing you need to do is use an AutoRouter() widget to render the nested children.

**Comment by matthewfx** [comment]
No, I don't have nested routers. Just one but I have an overlay on top of all pages and because of that I initialize the router deeper in the widget tree.

**Comment by Milad-Akarie** [comment]
@matthewfx I don't completely understand your setup yet but whenever I need to wrap all the pages with a widget I use MaterialApp builder

```dart
            MaterialApp.router(
                routerDelegate: _appRouter.delegate(),
                routeInformationParser: _appRouter.defaultRouteParser(),
                builder: (context, router) {
                 // router is Router widget constructed inside of MaterialApp with our delegate
                   return MyWrapperWidget(child: router);
                }),
```

**Comment by matthewfx** [comment]
OK - I thought there might be another way. Thank you very much for your help and your work! Have a great day!

**Comment by alexgrusu** [comment]
@Milad-Akarie could you please detail a little bit your approach or take a look on mine?

In my example I tried to integrate the builder of the MaterialApp.router like so
```dart
MaterialApp.router(
        routeInformationParser: MyBuddyRouter().defaultRouteParser(),
        routerDelegate: MyBuddyRouter().delegate(
          initialRoutes: [const SplashPageRoute()],
        ),
        builder: (context, widget) => SplashPage(),
      ),
```

My SplashPage integrates a consumer and routes the proper page
```dart
class SplashPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        state.map(
          initial: (_) {},
          authenticated: (_) => context.router.replace(const HomePageRoute()),
          unauthenticated: (_) =>
              context.router.replace(const SignInPageRoute()),
        );
      },
      child: const Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}
```

And this is how I implemented the router
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: SplashPage, initial: true),
    AutoRoute(page: SignInPage),
    AutoRoute(page: HomePage),
  ],
  generateNavigationHelperExtension: true,
)
class $MyBuddyRouter {
  late SplashPage splashPage;
  late SignInPage signInPage;
  late HomePage homePage;
}
```
Following this approach, the exception that occur is:
```
E/flutter (22062): [ERROR:flutter/shell/common/shell.cc(242)] Dart Unhandled Exception: AutoRouter operation requested with a context that does not include an AutoRouter.
E/flutter (22062): The context used to retrieve the Router must be that of a widget that is a descendant of an AutoRouter widget., stack trace: #0      AutoRouter.of.<anonymous closure>
```

**Comment by alexgrusu** [comment]
Hei @Milad-Akarie, any thoughts on the above question? Kind regards.

**Comment by mpiparo** [comment]
I have a follow up question about this topic. I have a similar setup where the MaterialApp needs to be higher up in the tree with my autoRoute routing further down the tree. I am trying to avoid nesting a second MaterialApp since it's causing me some UI issues. I've tried replacing the MaterialApp.router(...) and use the base Router(...), but when I do that it doesn't appear to route to the initial page, and gets stuck. My tree looks like so:

```
MaterialApp
-> SomeWidget
    -> Scaffold(bottomNavigationBar: ...)
        -> Router
```

I'm calling the Router as follows:

```
Router(
  	routerDelegate: router.delegate(
		navigatorObservers: () => [getIt<NavigatorStackObserver>()],
	),
        routeInformationParser: router.defaultRouteParser(),
),
```

It runs fine if I use MaterialApp.router(....), but like I said then I'm nesting MaterialApp's and it's causing me some UI issues.

@matthewfx, were you able to come up with a solution or approach to this?

thanks.

**Comment by matthewfx** [comment]
@mpiparo Unfortunately no.
