### ISSUE TITLE
Default enum argument value in generated file is not using import prefix

### ISSUE THREAD

**Issue by skybur** [Milad-Akarie/auto_route_library#443]
Hello, I encountered this bug after updating to latest version of `auto_route`

I have this screen widget which I used a named parameter with default enum value.

![image](https://user-images.githubusercontent.com/11155424/113252725-64720d80-92ee-11eb-96d8-004cecf6f64b.png)

When I run build to generate the files, this is the result.

![image](https://user-images.githubusercontent.com/11155424/113253923-22e26200-92f0-11eb-839d-70c857ee7d6a.png)

![image](https://user-images.githubusercontent.com/11155424/113252846-94b9ac00-92ee-11eb-964d-6d6c8d02da3b.png)

As you can see the field is correctly using import prefix, but the default value in the constructor is not using it.

It seems this is duplicate of  #325, if this can't be fixed, are there any workarounds? Thanks

Version info:
`auto_route: ^1.0.2`
`auto_route_generator: ^1.0.2`

Flutter doctor:
```
flutter] flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at D:\Dev\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Redmi Note 7 (mobile) • 192.168.18.61:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome             • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)            • edge               • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

**Comment by Milad-Akarie** [comment]
Hey @skybur  ya this's actually a known hard to fix issue as the default code is presented to const reader as literal code ("String").
 I came up with an idea on how it might be fixed the other day and I'll try to include it in the next build.
 for now a simple work around would be

```dart
class MyScreen extends StatelessWidget{
  final AuthScreenStateEnum _screenState;
   MyScreen({
     AuthScreenStateEnum? screenState,  
    }) : _screenState = screenState ?? AuthScreenStateEnum.Login;
}
```
