### ISSUE TITLE
Pass GlobalKey

### ISSUE THREAD

**Issue by stepanzalis** [Milad-Akarie/auto_route_library#445]
👋
I need to pass `GlobalKey<NavigatorState>` to a MaterialApp, but now with `.router` it seems that it's not possible. Is there any workaround for this? Thanks 🙏

**Comment by jiggum** [comment]
How about using `appRouter.navigatorKey`?

**Comment by Milad-Akarie** [comment]
@stepanzalis if you need to pass your own key you could use the delegate
```dart
 routerDelegate: _appRouter.delegate(
        navigatorKey: 
      )
```
if you just want to access the key user `appRouter.navigatorKey` as @jiggum  suggested.

**Comment by stepanzalis** [comment]
@Milad-Akarie @jiggum Thanks 🙏
