### ISSUE TITLE
Severe error when running build

### ISSUE THREAD

**Issue by ivatar39** [Milad-Akarie/auto_route_library#447]
Hi, after I ran `flutter pub run watch --delete-conflicting-outputs` this error has appeared:
`[INFO] Running build...
[SEVERE] auto_route_generator:autoRouteGenerator on lib/presentation/routes/app_router.dart:

type 'PrefixElementImpl' is not a subtype of type 'LibraryElement?' in type cast
[SEVERE] injectable_generator:injectable_config_builder on lib/presentation/injection.dart:

type 'PrefixElementImpl' is not a subtype of type 'LibraryElement?' in type cast
[INFO] Running build completed, took 433ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 19ms

[SEVERE] Failed after 453ms
`

**Comment by gcostaapps** [comment]
I'm also getting this error many times, every time that it occurs I need to do flutter clean, pub get and pub run again. It's a bit frustrating.

**Comment by theweiweiway** [comment]
Does the issue persist on AutoRoute 2.1.x?

**Comment by theweiweiway** [comment]
Is this an autoroute issue? It looks like there's some conflicts involving prefixes and injectable. It might help to share more of your code, like the routing setup, wherever `PrefixElementImpl` is located, etc.

**Comment by ivatar39** [comment]
Probably it's my fault. After clearing injection related errors, I don't see this issue any more.
