### ISSUE TITLE
Nested route not pushed initially

### ISSUE THREAD

**Issue by Zacherl** [Milad-Akarie/auto_route_library#448]
Hi,

I'm trying to use nested routing to ensure that Firebase is loaded before going to any child page. The routing worked fine before, however, at the moment the app is getting stuck at the "FirebasePageRoute" and does not load the "UserListPage". I tried setting "initial: true" on UserListPage (and FirebasePage), but I did not see any effect.

Is there something I'm fundamentally misunderstanding? Another question: If I would be on the user list page and would press the back button, would it only pop the user list page and return to the firebase page or would it close the app?

I'm fairly new to both flutter and auto_route, so sorry if this does not belong here.

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      path: '/',
      page: FirebasePage,
      children: [
        AutoRoute(path: '', page: UserListPage),
      ],
    ),
    AutoRoute(path: '/*', page: NotFoundPage),
  ],
)
class $AppRouter {}
```

```
class FirebasePage extends StatelessWidget {
  final _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) => FutureBuilder(
        future: _initialization,
        builder: (context, snapshot) => snapshot.hasError
              ? ErrorPage.forError(snapshot.error)
              : (snapshot.connectionState == ConnectionState.done)
                  ? const AutoRouter()
                  : CircularProgressIndicator(semanticsLabel: S(context).global_loading);
        };
}
```

**Comment by Zacherl** [comment]
The problem solved itself: I had a bug in the nested widget I did not recognize. The routing works perfectly fine, the back button also behaves as expected.

**Comment by ariefwijaya** [comment]
@Zacherl so, what is the solution?

**Comment by Zacherl** [comment]
@ariefwijaya I'm sorry, I checked the commits around that time but I could not find anymore what the bug was. :/
