### ISSUE TITLE
Pop modal bottom sheet

### ISSUE THREAD

**Issue by essarn** [Milad-Akarie/auto_route_library#451]
How can a bottom sheet that was opened with `showModalBottomSheet` be popped without also popping the underlying route? Only the bottom sheet should be popped and not the route that opened it.

**Comment by theweiweiway** [comment]
Hey @essarn , can you show me ur routing setup and version u are using

I was able to pop properly for the app I'm creating - are u opening and popping the sheet within a nested router or from root?

**Comment by essarn** [comment]
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      initial: true,
      usesTabsRouter: true,
      page: AppWrapperPage,
      children: [
        AutoRoute(page: HomePage),
        AutoRoute(page: StatisticsPage),
        AutoRoute(page: MarketplacePage),
      ],
    ),
    AutoRoute(
      page: AuthWrapperPage,
      children: [
        AutoRoute(page: SignInPage),
        AutoRoute(page: EmailLinkPage),
      ],
    ),
    AutoRoute(page: AccountPage),
  ],
)
class $AppRouter {}
```

The route pop happens in the `SignInPage` but the whole route is removed wheter you're using the nested or root router.

Also is it possible to push a wrapper route like `AuthWrapperPage` declarative in `AppWrapperPage`, how would router setup to make that possible look like?

Thanks for the help!

**Comment by essarn** [comment]
Hi again @theweiweiway,
Is this the correct way to achieve what I described in the previous post?

Thanks

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      initial: true,
      page: BootstrapWrapperPage,
      children: [
        AutoRoute(
          usesTabsRouter: true,
          page: AppWrapperPage,
          children: [
            AutoRoute(page: HomePage),
            AutoRoute(page: StatisticsPage),
            AutoRoute(page: MarketplacePage),
          ],
        ),
        AutoRoute(
          page: AuthWrapperPage,
          children: [
            AutoRoute(page: SignInPage),
            AutoRoute(page: EmailLinkPage),
          ],
        ),
        AutoRoute(page: LoadingPage),
        AutoRoute(page: ErrorPage),
      ],
    ),
    AutoRoute(page: AccountPage),
  ],
)
class $AppRouter {}
```

```dart
class BootstrapWrapperPage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final loading = useProvider(_loadingProvider);
    final authenticated = useProvider(authenticatedProvider);

    return AutoRouter.declarative(
      onGenerateRoutes: (_, __) => [
        loading.when(
          data: (_) => authenticated ? AppWrapperRoute() : AuthWrapperRoute(),
          loading: () => LoadingRoute(),
          error: (_, __) => ErrorRoute(),
        ),
      ],
    );
  }
}
```

**Comment by theweiweiway** [comment]
I haven't tried it but that looks pretty good to me - actually it's quite nice. I was using an AuthGuard to achieve something like that, but I think I like your way better . I think I might have to try it out

For your modalBottomSheet, how are you pushing the modal and popping the modal? I'm doing something similar with a `showBasicDialog` and it seems to work well

**Comment by theweiweiway** [comment]
I am curious though if the URLs will work as intended. Because last time I used `AutoRouter.declarative`, i realized that the URL no longer syncs up with your routes

**Comment by essarn** [comment]
I'm not sure about the URLs but I would guess that they would work as expected. 

The bottom sheet is pushed with `showModalBottomSheet` in `SignInPage` and removed with `context.router.pop` in the same route but it doesn't work. It works fine to pop a dialog showed with `showAlertDialog` in the route.

**Comment by essarn** [comment]
There is no error and nothing happens. But as I said it works to pop a dialog but not a bottom sheet. Also, is the `showBasicDialog` a custom method of yours because I can't find in the framework?

**Comment by theweiweiway** [comment]
Sorry, `showGeneralDialog`

I see, i guess it has something to do with the modal.

Did you try `context.router.root.pop` as well?

**Comment by essarn** [comment]
Yes still not working using the root router. Could you maybe try and see if you are successful in showing a bottom sheet and removing it using the methods I described?

**Comment by theweiweiway** [comment]
@essarn OK so i tried it and this seteup worked for me:

```dart
     onPressed: () =>
                // _authCubit.selectFlow(AuthFlow.signUp()
                showModalBottomSheet(
                    context: context,
                    useRootNavigator: true, // if this is false, nothing happens when i click the 'pop' button in the modal
                    builder: (context) {
                      return Container(
                          height: 500,
                          child: ElevatedButton(
                            child: Text('pop'),
                            onPressed: () {
                              context.router.root.pop();
                            },
                          ));
                    }),
```

**Comment by essarn** [comment]
> @essarn OK so i tried it and this seteup worked for me:
> 
> ```dart
>      onPressed: () =>
>                 // _authCubit.selectFlow(AuthFlow.signUp()
>                 showModalBottomSheet(
>                     context: context,
>                     useRootNavigator: true, // if this is false, nothing happens when i click the 'pop' button in the modal
>                     builder: (context) {
>                       return Container(
>                           height: 500,
>                           child: ElevatedButton(
>                             child: Text('pop'),
>                             onPressed: () {
>                               context.router.root.pop();
>                             },
>                           ));
>                     }),
> ```

Yeah that makes sense to use the root navigator.  Gonna give it a try when I get home tonight. 

Thanks for testing, appreciate it!

**Comment by essarn** [comment]
@theweiweiway thanks for the help, your solution worked for me as well 😄
