### ISSUE TITLE
auto_router_generator failing on functions with Future<void> return type

### ISSUE THREAD

**Issue by allen-9count** [Milad-Akarie/auto_route_library#458]
When running `auto_route_generator` on a file that has a function of type `Future<void>` as a constructor argument, router file generation fails with the following error:

```[SEVERE] auto_route_generator:autoRouteGenerator on lib/router/router.dart:

NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name`
```
Here is the code that fails it:

```
typedef SomeFunction = Future<void> Function(
  BuildContext context,
);

class ScreenA extends StatelessWidget {
  final String someString;
  final SomeFunction onFunc;

  const ScreenA({
    @required this.someString,
    this.onFunc,
  });

  @override
  Widget build(BuildContext context) => Container();
}
```

When changing `Future<void>` to anything else, like `Future<bool>`, it generates correctly:

`typedef SomeFunction = Future<bool> Function(
  BuildContext context,
);`

**Comment by Milad-Akarie** [comment]
@allen-9count  I'll look into it. 
could you give a case where async callbacks is needed?

**Comment by allen-9count** [comment]
@Milad-Akarie Sorry for the late reply! Use case would be where a Widget needs to wait on a callback to complete so it can refresh after a callback has been completed and not before.
