### ISSUE TITLE
QUESTION: comprehensive flutter routing guidance

### ISSUE THREAD

**Issue by mohammadne** [Milad-Akarie/auto_route_library#459]
I'm familiar with basic flutter routing.

what I need is to get deeper into flutter routing mechanism and strategy and after that understtod behind the scene of this awesome library.
I would appreciate if anyone can help me and others like me that how we can get deeper into flutter and auto_route route system.

Thanks

**Comment by Milad-Akarie** [comment]
Hey @mohammadne I'm glad to hear that, do you have any specific questions?

**Comment by theweiweiway** [comment]
Closing due to stale issue
