### ISSUE TITLE
How do Deep Links and Universal Links work with Auto_Route?

### ISSUE THREAD

**Issue by DFelten** [Milad-Akarie/auto_route_library#461]
Thanks for your great package! I really love to use Auto Route.

I'm currently trying to implement [Deep Links](https://flutter.dev/docs/development/ui/navigation/deep-linking) and Universal Links into our app. 

## Deep links with uni_link2 and auto_route
First I tried it with the package [uni_links2](https://pub.dev/packages/uni_links2), which seems to work great. The stream listener and the push is working. 

A cold start (app is not launched) is not working on Android, since the initialRoute contains the deeplink within the route. An empty view is visible after the cold start. 

So I've added `RedirectRoute(path: '*', redirectTo: '/')` to the router and the cold start is working great. But now the deep links  are not working anymore when the App is already launched. The redirect route is also called here for these deep links. The listener is working, but the push is doing nothing. It seems that the _pageBuilder in the root_stack_router is called twice. First with the desired `PostDetailsRoute`, and after this with the `HomeRoute`.

What am I doing wrong here?

```dart
Future<StreamSubscription?> init() async {
  final String? _initialLink = await getInitialLink();

  if (_initialLink != null && _initialLink != '/') {
    context.router.push(PostDetailsRoute(postUrl: _initialLink));
  }

  // Attach a listener to the stream
  return linkStream.listen((String? link) {
    if (link != null) {
      context.router.push(PostDetailsRoute(postUrl: _initialLink));
    }
  }, onError: (err) {
    // Do nothing on error
  });
}
```

Later I saw that Auto Route also supports deep links. So I also tried this.

## Deep links with auto_route
Unfortunately, I am not sure how to implement these only with auto_route. I have searched in the documentation, but without finding a working solution.

I have reached the point where I can read out the URL from the route settings entry. For testing I created a page for DeepLinks and push the route to the details page only if the article exists. Otherwise I stay on the page. I would like to use this logic later on the start page of the app.

The problem I have is that I can currently only use the logic on a separate page. Here also unfortunately only once. As soon as I am on the page, I cannot trigger this route again. When I've implemented the logic on the initial route it's no longer working  since no navigation change is detected. It's the same when I'm already in the deep link page.

Is there a better way to detect deep links here? It is important that articles can be opened via the browser. initState is of course only triggered the first time. But I don't know any other place to do the forwarding. A central observer for such deep links would be helpful.

What would be the right way here with auto route? Maybe I'm going about this all wrong. Thanks in advance for the help!

My current router
```dart
@MaterialAutoRouter(
  generateNavigationHelperExtension: true,
  preferRelativeImports: true,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AdaptiveRoute(page: HomePage, initial: true),
    AdaptiveRoute(page: PostDetailsPage),
    AdaptiveRoute(page: ProfilePage),
    AutoRoute(path: '*', page: DeepLinkPage)
  ],
)
class $AppRouter {}
```
I also tried here `RedirectRoute(path: '*', redirectTo: '/')`, but then nothing happens when trigger a deep link.

This is the deep link page. On the details page, I can get the information I want from our backend based on the URL.
```dart
class DeepLinkPage extends StatefulWidget {
  @override
  _DeepLinkPageState createState() => _DeepLinkPageState();
}

class _DeepLinkPageState extends State<DeepLinkPage> {
  String routeUrl = '';

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance?.addPostFrameCallback((_) {
      final ModalRoute? modalRoute = ModalRoute.of(context);

      if (modalRoute != null) {
        final StackEntryItem leafEntry = (modalRoute.settings as AutoRoutePage).entry;
        routeUrl = 'https://www.mypage.de${leafEntry.key.value}';
        if (PageService.checkIfArticleExists(routeUrl)) {
          context.router.push(PostDetailsRoute(postUrl: routeUrl));
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Text(routeUrl),
    );
  }
}
```

The command for the emulator to simulate the deep link
```sh
adb shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "https://www.mypage.de/article-title/"
```

**Comment by Milad-Akarie** [comment]
Hello @DFelten You'll still need to obtain your deep-link using `uni-link`, `FirebaseDyanamicLinks` or any other package.
auto_route will make sure your App opens the desired page according to the provided link. 

both `uni-links` and `FirebaseDynamicLinks` have two methods to get links 

**First- getting the initial link when the App launches**
  
 uni_links
`await getInitialUri();`
firebase 
`await FirebaseDynamicLinks.instance.getInitialLink()`

**Second- Using deep-link listener which is triggered when the user opened a deep-link and the App is already running.**
uni_links
```dart
   getUriLinksStream().listen((Uri uri) {
      // push deep link here
    }, onError: (err) {
      // handle error
    });
```
firebase
```dart
FirebaseDynamicLinks.instance.onLink(
      onSuccess: (PendingDynamicLinkData dynamicLink) async {
        final Uri deepLink = dynamicLink?.link;
        if (deepLink != null) {
         // push deep link here
        }
      },
      onError: (OnLinkErrorException e) async {
         // handle error
      }
    );
```
with that being said you'd want to give your pages/locations proper paths so you can navigate to them easily 

```dart
@MaterialAutoRouter(
  generateNavigationHelperExtension: true, // this is no longer a thing
  preferRelativeImports: true, // this is true by default
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    // initial = true will just set path to '/', ignored if path is set manually
    AdaptiveRoute(path: '/', page: HomePage),
    AdaptiveRoute(path: '/post-details/:id', page: PostDetailsPage),
    AdaptiveRoute(path: '/profile', page: ProfilePage),
   //  AutoRoute(path: '*', page: DeepLinkPage) no need
  ],
)
class $AppRouter {}
```
with the above setup if you set the initialDeepLink to '/post-details/1' auto_route will open the PostDetailsPage and parse your path parameter 'id'. more on that here https://pub.dev/packages/auto_route#working-with-paths

How I use deep-links and deep-locations in my personal Apps

```dart
// before I run my App I check if App started from a deep-link
// then pass the link to my App widget
final deepLink = await FirebaseDynamicLinks.instance.getInitialLink();
  runApp(App(
    initialDeepLink: deepLink?.link?.toString(),
  ));
```
App widget
```dart
class _AppState extends State<App> {
  final _appRouter = AppRouter();

  @override
  void didChangeDependencies() async {
    super.didChangeDependencies();
    // internal this using FirebaseDynamicLinks.instance.onLink()
    dynamicLinkManager.initDynamicLinks(onDLinkSuccessCallback: (Uri deepLink) {
      // pushing a deep-link when App is running
      _appRouter.pushPath(deepLink.toString());
      // you can also push using route objects if you decide to do
      // the matching your self you can do something like this
        if(deepLink.path.startsWith('/post-details')){
           _appRouter.push(PostDetailsRoute(id:deepLink.pathSegments[1]));
        }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
     
      routerDelegate: _appRouter.delegate(
        // here I'm passing my initial deep-link to the delegate
        initialDeepLink: widget.initialDeepLink,
      ),
      routeInformationParser: _appRouter.defaultRouteParser(),
    );
  }


```

**Comment by DFelten** [comment]
Thanks for your great help! I used the initial link incorrectly. The deep links are working now :)

**Comment by DFelten** [comment]
@Milad-Akarie Is it possible to get the whole deep link including the slashes as a path param? 

Our route could look like this: `https://www.domainname.de/ratgeber/fitness-tracker-smartwatches-bestenliste/`

And there we need everything after `https://www.domainname.de/`. We need `/ratgeber/fitness-tracker-smartwatches-bestenliste/` or the whole link for the backend call.

**Comment by Milad-Akarie** [comment]
Looks like what you need to do is
context.routeData.match

**Comment by DFelten** [comment]
> Looks like what you need to do is
> context.routeData.match

Great, thanks! This is definitely a nicer solution.

**Comment by DFelten** [comment]
> Looks like what you need to do is
> context.routeData.match

Great, thanks! This is definitely a better solution.

We have a [big problem on Android and deep links](https://stackoverflow.com/questions/67216018/infinite-loop-with-android-app-links-deep-links-in-flutter) now, unfortunately, but it has nothing to do with Auto Route.

**Comment by Milad-Akarie** [comment]
What is it?

**Comment by DFelten** [comment]
The app can be opened via deep links and we can display content based on these links (We're using the package uni_links2). On iOS everything is working, but on Android we've get an infinite loop on certain links.  

Our app has a details page and links with the same domain appear here, but they should be opened in the browser and not in the app. The links go to content that we can't handle in the app.

These links should be opened within the app from the deep link:

- https://www.ourdomain.com/article-name
- https://www.ourdomain.com/category/article-name

An url like this should be opened within the browser:

- https://www.ourdomain.com/page/whatever
- https://www.ourdomain.com/goto/whatever

With the url_launcher package I can open urls, but they are directly seen as deep links and opened again in their own app. I also tried android_intent, and it's working when define Chrome as the default intent. But I can't guarantee that the user has Chrome installed.

Currently I have no idea how to solve this issue. All I know is that I can specify whole domains or paths as the schema. Unfortunately, I cannot exclude specific paths. Also, I don't know how to specify that links should open in the browser and not in their own app.

**Comment by NamanShergill** [comment]
> The app can be opened via deep links and we can display content based on these links (We're using the package uni_links2). On iOS everything is working, but on Android we've get an infinite loop on certain links.
> 
> Our app has a details page and links with the same domain appear here, but they should be opened in the browser and not in the app. The links go to content that we can't handle in the app.
> 
> These links should be opened within the app from the deep link:
> 
> * https://www.ourdomain.com/article-name
> * https://www.ourdomain.com/category/article-name
> 
> An url like this should be opened within the browser:
> 
> * https://www.ourdomain.com/page/whatever
> * https://www.ourdomain.com/goto/whatever
> 
> With the url_launcher package I can open urls, but they are directly seen as deep links and opened again in our own app. I also tried android_intent, and it's working when define Chrome as the default intent. But I can't guarantee that the user has Chrome installed.
> 
> Currently I have no idea how to solve this issue. All I know is that I can specify whole domains or paths as the schema. Unfortunately, I cannot exclude specific paths. Also, I don't know how to specify that links should open in the browser and not in our app.

Maybe this package would help for cases like this? https://pub.dev/packages/flutter_web_browser#-readme-tab-

**Comment by DFelten** [comment]
Thanks, we had this idea too :) Our current solution is a platform call for opening the link in the app browser. In the next step we will probably create an inapp browser.

```kt
private fun openUrl(call: MethodCall, result: MethodChannel.Result) {
    // Use default browser instead of triggering chooser so that we don't get into
    // a loop where the current app will forever try to open the URL because it
    // was once set as the preferred app for URLs
    val defaultBrowser = Intent.makeMainSelectorActivity(
            Intent.ACTION_MAIN,
            Intent.CATEGORY_APP_BROWSER
    )

    val url = (call.arguments as? String)

    url?.let {
        defaultBrowser.data = Uri.parse(it)
        activity.startActivity(defaultBrowser)
    }
}
```

**Comment by AAverin** [comment]
What if website and app have different URL structures? Is there a way to still handle web links and map them to some app route instead?
