### ISSUE TITLE
How to pop current screen?

### ISSUE THREAD

**Issue by finroly** [Milad-Akarie/auto_route_library#463]
Screen A :
```
AutoRouter.of(context).push(DoneScreenRoute(onResult: (result) {
        if (result) {
          widget.onResult!(transaction);
          AutoRouter.of(context).pop();
        }
      }));
```

The Done screen play animation and pop itself. 

Screen Done: 

```
if (status == AnimationStatus.completed) {
          widget.onResult!(true);
          AutoRouter.of(context).pop();
        }
```

Here the done screen does pop up but the the current screen does not pop. However the code does run on Screen A but `AutoRouter.of(context).pop();` does not have any effect.

**Comment by alexgrusu** [comment]
Simply use `context.router.pop();`

**Comment by Milad-Akarie** [comment]
@finroly Probably you end up doing is calling `router.pop()` twice, so before the first screen is finished popping you're calling pop again. 
What you can do is use other popping options like
 only call this in once either when the animation completes or inside of `onResult` callback
 _assuming the page you want to finally pop to is your `HomePage_`
  `router.popUntilRouteWithName(HomeRoute.name)`
or 
`router.popUntil((route) => logic to decide when to stop popping);`


@alexgrusu `context.router` is just a shortcut for `AutoRouter.of(context)`

**Comment by finroly** [comment]
How do I pass parameters in case of `router.popUntilRouteWithName(HomeRoute.name)` Actually this was working fine before when  push does not get resolved as soon as it called `with await`.

**Comment by finroly** [comment]
@Milad-Akarie Thanks the below code works without deplay


```
int count = 0;

 AutoRouter.of(context).popUntil((route) {
            return count++ == 2;
 });
```

**Comment by finroly** [comment]
@Milad-Akarie How can I refresh previous page after popping the current page as there is no await now?

**Comment by theweiweiway** [comment]
I believe you will be able to await in the next build of AutoRoute. Gonna close this since it seems like your initial question was answered
