### ISSUE TITLE
Nested navigation in scope of tab navigation bar

### ISSUE THREAD

**Issue by Chojecki** [Milad-Akarie/auto_route_library#464]
Hi,

Is it possible to navigate between tabs nested routes?

Let say I have navigation like this:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AdaptiveRoute<dynamic>(
      path: '/app',
      page: TabNavigation,
      usesTabsRouter: true,
      fullscreenDialog: true,
      children: [
        AutoRoute<dynamic>(
          path: 'home',
          name: 'HomeRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(
              path: '',
              page: HomeScreen,
            ),
            AutoRoute<dynamic>(path: 'user_profile', page: ProfileScreen),
            AutoRoute<dynamic>(
              path: 'post_details',
              page: PostDetailsScreen, // <--- So here is post details screen
            ),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        AutoRoute<dynamic>(
          path: 'profile',
          name: 'ProfileRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: MyProfileScreen),
            AutoRoute<dynamic>(
              path: 'edit_personal_data',
              page: ProfilePersionalDataEditForm,
            ),
             AutoRoute<dynamic>(
              path: 'post_details',
              page: PostDetailsScreen, // <--- And here is the same screen (I can change it name like name: "some") 
            ),
            AutoRoute<dynamic>(
              path: 'edit_profile',
              page: ProfileEditScreen,
            ),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
      ],
    ),
  ],
)
class $Router {}
```

So the idea is to have for eg. `HomeScreen` (one tab) with list of `Posts` and by taping on post I can go to `PostDetails` and when I in `PostDetails` I can tap on `Avatar of post owner` and go to profile of this Owner.

From the other hand,  in `ProfileScreen` (another tab) I see a `List of Post of this user of Profile` and I want to go to `PostDetails` wich is nested in `HomeRouter` and duplicated in `ProfileRouter`.

Because of this screen duplication I have to create really hacky logic to know when to navigate where with a lot of `if's` to get Router know where am I right now and to context.router.push or context.router.root... etc.

I can move Routes outside of tab bar navigation, but I lost bottom navigation bar.

Is it possible to navigate between nested tab routes ? For eg: Im in scope on tabNavitation, I'm on at `ProfileScreen` tap something and go `HomeScreen -> PostDetails` and land on `PostDetailsScreen, but on pop I go to `ProfileScreen` not to Home

**Comment by theweiweiway** [comment]
Check out the bottom of the page here: https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing


I think what you will need to end up doing is:

```dart
context.tabsRouter
  ..innerRouterOf<StackRouter>(ProfileRouter.name)
  .push(ProfileDetailsRoute()); 
```  

Let me know if that works

**Comment by Chojecki** [comment]
Ye, but I don't want to change the tab. We ended with Navigator.of(context).push(MaterialPagerRoute(builder: (ctx) => Screen()... inside TabNavigator

**Comment by mohammadne** [comment]
same issue for me:
https://github.com/Milad-Akarie/auto_route_library/issues/460

**Comment by theweiweiway** [comment]
seems like #460 was fixed in newest versions of auto-route - is this still a problem ?

**Comment by magician20** [comment]
> Check out the bottom of the page here: https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing
> 
> I think what you will need to end up doing is:
> 
> ```dart
> context.tabsRouter
>   ..setActiveIndex(1)
>   ..innerRouterOf<StackRouter>(ProfileRouter.name)
>   .push(ProfileDetailsRoute()); 
> ```
> 
> Let me know if that works

First:  I tried this code and worked. But in my case I had to add the name of the inner page because it was not generated automatically .
Second:
 (if this page >> context.tabsRouter.setActiveIndex(1) already open, why code below not working ??  )
 AutoRouter.of(context).innerRouterOf<StackRouter>(ProfileRouter.name)!.navigate(ProfileDetailsRoute());
