### ISSUE TITLE
Please Improve README.md

### ISSUE THREAD

**Issue by ICoderMe** [Milad-Akarie/auto_route_library#466]
Can you write the documentation in detail? List the meaning and purpose of the attributes and methods, otherwise you have to guess one by one?

**Comment by theweiweiway** [comment]
There's also https://autoroute.vercel.app/introduction 

But I guess what you are looking for is an API reference.. 

If you would like to contribute and help out with this it would be much appreciated!

**Comment by ICoderMe** [comment]
I’m sorry, I’ve been reading the README before and ignored this new link. After reading this document, the introduction is okay, but I still suggest to improve the document and demo

**Comment by theweiweiway** [comment]
Hey ICoder and anyone else with an opinion on this, can you give any specific suggestions for improvements in the docs ? 

Maybe concrete examples on things that are unclear, so that we can make the docs as clear as possible

**Comment by theweiweiway** [comment]
Closing for now - but please re-open if you have any feedback/inputs
