### ISSUE TITLE
Empty white page when i hot reload/restart

### ISSUE THREAD

**Issue by fremfi** [Milad-Akarie/auto_route_library#467]
When I run the app for the first time it renders correctly, but soon as I hot restart/reload it renders for a brief second and quickly replaces it with an empty screen.

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: SplashScreen, initial: true),
    AutoRoute(path: '/welcome', page: IntroScreen),
    AutoRoute(path: '/login', page: SignInScreen),
    AutoRoute(path: '/routine', page: RoutineScreen),
  ],
)
class $AppRouter {}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final _appRouter = AppRouter();

    return MaterialApp.router(
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
      builder: (_, router) {
        return ProviderScope(
          child: router!);
      },
    );
  }
}
```

What am I doing wrong? thanks

**Comment by theweiweiway** [comment]
It looks fine, but I think something weird is happening with the rest of your code. What does ProviderScope look like? 

It might be best to share the whole repository

**Comment by fremfi** [comment]
> It looks fine, but I think something weird is happening with the rest of your code. What does ProviderScope look like?
> 
> It might be best to share the whole repository

The same thing happens even if I remove the Provider Scope, and I put simple stateless widgets on my autoroutes, instead of my screens.
I'm not able to share my whole repository, but I can share certain files, like my pubspec.yaml, if it helps?

**Comment by theweiweiway** [comment]
Can I see the splash screen? Are you doing some sort of redirect in that file?

**Comment by fremfi** [comment]
Yes am doing a redirect in that file, and plan on changing the logic to use the auth guard, but I don't think that's my problem, as even  this code has the same behaviour

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: RandomScreen, initial: true),
    // AutoRoute(path: '/welcome', page: IntroScreen),
    // AutoRoute(path: '/login', page: SignInScreen),
    // AutoRoute(path: '/routine', page: RoutineScreen),
    // AutoRoute(path: '/routine-info', page: RoutineInfoScreen),
  ],
)
class $AppRouter {}

class RandomScreen extends StatelessWidget {
  const RandomScreen({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Text('Hello World'),
    );
  }
}
```
I also removed provider scope, so it's really a barebones application at this point.

Here's my splash screen if it helps

```
class SplashScreen extends HookWidget {
  const SplashScreen({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    Future<void> checkAuthStateAndNavigate() async {
      if (await context.read(authNotifierProvider.notifier).getCurrentUser() !=
          null) {
        await context
            .read(userNotifierProvider.notifier)
            .getCurrentUser()
            .whenComplete(() {
          final user = context.read(userNotifierProvider).user;

          if (user != null &&
              user.settings.notificationSettings.routineNotificationsEnabled &&
              user.settings.notificationSettings.routineNotificationTime !=
                  null) {
            final List<Event> events = user.routines.fold(
                [],
                (prev, Routine routine) =>
                    prev +
                    routine.events
                        .where((event) => event.date!.isAfter(
                            DateTime.now().subtract(const Duration(days: 1))))
                        .toList());
            ScheduleRoutineNotifications().execute(
                events,
                user.settings.notificationSettings
                    .routineNotificationTime!); // This function clears and schedules the notifications
          }
          AutoRouter.of(context).navigate(const RoutineRoute());
        });
      } else {
        AutoRouter.of(context).navigate(const IntroRoute());
      }
    }

    useEffect(() {
      checkAuthStateAndNavigate();
      return () => null;
    }, []);
    return Scaffold(
      body: Stack(
        alignment: Alignment.center,
        children: <Widget>[
          Positioned(
            top: MediaQuery.of(context).size.height / 3,
            child: Column(
              children: [
                SizedBox(
                  height: 110,
                  child: Image.asset(
                    'assets/logos/3.0x/xxx.png',
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by uzuki-P** [comment]
I'm also got stuck on white screen
I think it stuck on trackRepaintWidgets
I try to reproduce the error using bare flutter project, but it seem just working fine

this is the log

```
[   +2 ms] Synced 0.0MB.
[   +2 ms] <- accept
[  +17 ms] Connected to _flutterView/0x7fb9b102c620.
[{"event":"app.started","params":{"appId":"7aa9168b-fcb7-46d0-95a3-af1054548828"}}]
[{"id":0,"result":{"value":"iOS","type":"_extensionType","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1.0","type":"_extensionType","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[{"id":6,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugAllowBanner"}}]
[{"id":7,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":8,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.show"}}]
[{"id":9,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":12,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
```

Any ideas?

**Comment by theweiweiway** [comment]
Are both of you on web or mobile?

Also, @fremfi what does your initialization logic look like? Not really sure what is going here to be honest..

**Comment by fremfi** [comment]
I didn't try running on the web, just on mobile so far. I started trying out Beam router, and I don't have the issue anymore, so I'm not sure if it's the library or something about my setup that is causing the issue.
`
Future<void> main() async {
  I18n.defaultLocale = const Locale("en", "");
  WidgetsFlutterBinding.ensureInitialized();

  if (!kIsWeb) {
    await Firebase.initializeApp();
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
  }
  runApp(
    MyApp(),
  );
}
`

**Comment by uzuki-P** [comment]
I'm using [ResoCoder ddd](https://github.com/ResoCoder/finished-flutter-firebase-ddd-course) that upgraded to flutter 2 and I add some LanguageBloc.

This is the main app widget

```
class AppWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _dismissKeyboardOnLostFocus(context),
      child: MultiBlocProvider(
        providers: [
          BlocProvider(
            create: (_) =>
                getIt<AuthBloc>()..add(const AuthEvent.authCheckRequested()),
          ),
          BlocProvider(create: (_) => getIt<LanguageBloc>()),
        ],
        child: BlocBuilder<LanguageBloc, LanguageState>(
          builder: (context, state) {
            return MaterialApp.router(
              debugShowCheckedModeBanner: false,
              title: 'My App',
              locale: Locale(state.current),
              localizationsDelegates: AppLocalizations.localizationsDelegates,
              supportedLocales: AppLocalizations.supportedLocales,
              routerDelegate: app_router.Router().delegate(),
              routeInformationParser: app_router.Router().defaultRouteParser(),
              theme: themeData,
            );
          },
        ),
      ),
    );
  }

  void _dismissKeyboardOnLostFocus(BuildContext ctx) {
    final FocusScopeNode currentFocus = FocusScope.of(ctx);
    if (!currentFocus.hasPrimaryFocus) {
      FocusManager.instance.primaryFocus?.unfocus();
    }
  }
}
```

**Comment by PatrickBTUD** [comment]
Same problem here, when hot restart or reload for a short time the correct screen is displayed and when only empty screen with primary color of AppTheme.

Workaround for the web is changing the URL to a different path and back again.

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: MainScreen, initial: true),
    AutoRoute(path: '/login', page: LoginScreen, maintainState: false),
    AutoRoute(path: '/register', page: RegisterScreen, maintainState: false),
    AutoRoute(path: '/overview', page: OverviewScreen),
    AutoRoute(path: '/start/activate/:activation_token', page: ActivateAccountScreen),
    AutoRoute(path: '*', page: UnknownScreen),
  ],
)
class $AppRouter {}
```

```
class Absolut extends StatelessWidget {
  final Configuration configuration;

  const Absolut(this.configuration);

  @override
  Widget build(BuildContext context) {
    final _appRouter = AppRouter();

    return MultiProvider(
      providers: [
        Provider<Configuration>(
          create: (context) => configuration,
        ),
        Provider<Client>(
          create: (context) => Client(configuration),
        ),
        FutureProvider<SharedPreferencesService?>(
          create: (context) async => SharedPreferencesService.getInstance(),
          initialData: null,
          lazy: false,
        ),
        ProxyProvider<Client, SessionService>(
          update: (context, client, _) => SessionService(client),
          dispose: (context, sessionService) => sessionService.dispose(),
        ),
        ProxyProvider2<Client, SessionService, UserService>(
          update: (context, client, sessionService, _) => UserService(client, sessionService),
          dispose: (context, loginService) => loginService.dispose(),
        ),
      ],
      child: MaterialApp.router(
        routerDelegate: _appRouter.delegate(),
        routeInformationParser: _appRouter.defaultRouteParser(),
        title: "TEST",
        theme: CustomTheme.lightTheme,
      ),
    );
  }
}
```


```
class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final sessionService = Provider.of<SessionService>(context);
    return StreamBuilder<bool>(
      stream: sessionService.userLoading,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting || (snapshot.hasData && snapshot.data!)) {
          return SplashScreen();
        } else {
          return StreamBuilder(
            stream: sessionService.user,
            builder: (context, userSnapshot) {
              if(userSnapshot.connectionState == ConnectionState.active) {
                if(userSnapshot.data == null) {
                  return LoginScreen();
                } else {
                  return OverviewScreen();
                }
              }
              return SplashScreen();
            },
          );
        }
      },
    );
  }
}
```

**Comment by Milad-Akarie** [comment]
@fremfi  @uzuki-P @PatrickBTUD all of you are initiating your AppRouter() inside of the build function and that's what's causing the flickering also your pages state is probably lost on hot reload. 
all you gotta do is initiate your root router outside of the build function,



```dart
class AppWidget extends StatelessWidget {
final _appRouter = AppRouter(); // initiate your Router here
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
             // use the instance here
              routerDelegate: _appRouter.delegate(),
              routeInformationParser: _appRouter.defaultRouteParser(),
            );
  }
```

**Comment by uzuki-P** [comment]
> @fremfi @uzuki-P @PatrickBTUD all of you are initiating your AppRouter() inside of the build function and that's what's causing the flickering also your pages state is probably lost on hot reload.
> all you gotta do is initiate your root router outside of the build function,
> 
> ```dart
> class AppWidget extends StatelessWidget {
> final _appRouter = AppRouter(); // initiate your Router here
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp.router(
>              // use the instance here
>               routerDelegate: _appRouter.delegate(),
>               routeInformationParser: _appRouter.defaultRouteParser(),
>             );
>   }
> ```

welp
this fixed it
kinda dumb mistake from me LOL

**Comment by Milad-Akarie** [comment]
@uzuki-P How do you think I instantly recognized the issue? I did the same mistake a couple times building up the library lol
closing this for now.

**Comment by fremfi** [comment]
> @fremfi @uzuki-P @PatrickBTUD all of you are initiating your AppRouter() inside of the build function and that's what's causing the flickering also your pages state is probably lost on hot reload.
> all you gotta do is initiate your root router outside of the build function,
> 
> ```dart
> class AppWidget extends StatelessWidget {
> final _appRouter = AppRouter(); // initiate your Router here
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp.router(
>              // use the instance here
>               routerDelegate: _appRouter.delegate(),
>               routeInformationParser: _appRouter.defaultRouteParser(),
>             );
>   }
> ```

smh, my two hours gone just like that because of a one linear 😆 . thanks!

**Comment by Mad-Kat** [comment]
@Milad-Akarie 
Hmm I upgraded our Setup with auto_route today and somehow I have the same issue and I have the initialization of the AppRouter outside of the `build` method.

```dart
class App extends StatelessWidget with WidgetsBindingObserver {
  App({Key? key}) : super(key: key);

  final _appRouter = auto_route.AppRouter();

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: const SystemUiOverlayStyle(
        // For Android.
        // Use [light] for white status bar and [dark] for black status bar.
        statusBarIconBrightness: Brightness.light,
        // For iOS.
        // Use [dark] for white status bar and [light] for black status bar.
        statusBarBrightness: Brightness.dark,
      ),
      child: MaterialApp.router(
        routerDelegate: _appRouter.delegate(
          initialRoutes: [const auto_route.AuthenticationSwitchRoute()],
        ),
        routeInformationParser: _appRouter.defaultRouteParser(),
        theme: appTheme(),
        locale: context.select((AppSettingsProvider appSettings) => appSettings.locale),
        supportedLocales: AppLocalizations.supportedLocales,
        localizationsDelegates: AppLocalizations.localizationsDelegates,
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}
```

and in my AuthenticationSwitch

```dart
class AuthenticationSwitch extends StatelessWidget {
  const AuthenticationSwitch({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AutoRouter.declarative(routes: (context) {
      final auth = context.watch<AuthenticationProvider>();
      return [
        auth.currentState.maybeMap(
            signedIn: (_) => const auto_route.AuthenicatedAreaRouter(),
            permissionDenied: (_) => const auto_route.PermissionDeniedScreenRoute(),
            orElse: () => const auto_route.UnauthenicatedAreaRouter())
      ];
    });
  }
}
```

Any ideas here?

Thank you in advance :)

**Comment by Mad-Kat** [comment]
Nevermind I fixed it :smiley: 

For the folks, who read this:
I changed my App Widget to be a `StatefulWidget` and initialized the `AppRouter` in the State -> Hot-Reload works again

**Comment by MassimoTambu** [comment]
> Nevermind I fixed it 😃
> 
> For the folks, who read this:
> I changed my App Widget to be a `StatefulWidget` and initialized the `AppRouter` in the State -> Hot-Reload works again

This fixed my problem

**Comment by frantovar** [comment]
Hi Everyone, I'm having the same issue and I tried your solutions but I can't fix it.

This is my AppView (Also I've tried making it StatefullWidget):

`class AppView extends StatelessWidget {
  AppView({Key? key}) : super(key: key);

  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      theme: Theme22.lightTheme,
      themeMode: ThemeMode.light,
    );
  }
}`

And the place where I use the AutoTabScaffold:

`class HomeView extends StatelessWidget {
  const HomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      routes: const [
        ProgramRoute(),
        FilterRoute(),
        MapRoute(),
        InfoRoute(),
        FavsRoute(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return BottomAppBar(
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 4),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                for (var i = 0; i < _tabIcons.length; i++)
                  HomeTabButton(
                    index: i,
                    icons: _tabIcons[i],
                    activeIndex: tabsRouter.activeIndex,
                    onPressed: () => tabsRouter.setActiveIndex(i),
                  ),
              ],
            ),
          ),
        );
      },
    );
  }
}`

Any suggestions?
