### ISSUE TITLE
Android system back button closes whole app

### ISSUE THREAD

**Issue by dannnoon** [Milad-Akarie/auto_route_library#47]
Hello,

After upgrading library version from 0.2.2 to the newest one (0.4.1) I encountered an issue with Android system back button. Whenever I press it, even if I am not on initial route, application is being closed. If I call pop() method on my router, then it works in expected way. When I swipe back on iPhone, it also works.

I tried to go around it and add WillPopScope widget to my main page, but onWillPop was never called.

My MaterialApp:
```
MaterialApp(
        title: translate(Keys.Common_App_Name),
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          localizationDelegate
        ],
        supportedLocales: localizationDelegate.supportedLocales,
        locale: localizationDelegate.currentLocale,
        theme: Themes.mainTheme(context),
        builder: ExtendedNavigator<Router>(router: Router()),
      )
```

**Comment by Milad-Akarie** [comment]
Hey, @dannnoon  
Fixed in auto_route: 0.4.2
Thanks for reporting.
