### ISSUE TITLE
pushPath nor working for tab navigation nested routes

### ISSUE THREAD

**Issue by hazzo** [Milad-Akarie/auto_route_library#475]
Hi I'm trying to replicate the example from this repo and when I try to push to the books detail page by using `AutoRouter.of(context).pushPath('/books/$id')` nothing happens. In the contrary if I push the page with the other method, `AutoRouter.of(context).push(BookDetailsRoute(id: id))` works just fine.

I realised that if instead of doing simply `router.pushPath('/books/$id')` I do `router.root.pushPath('/books/$id')` it works but obviously it is wrong and the back arrow is not showing.

Don't know if is something on my config or what, but any children route is working with `pushPath`

Thanks and great package!

**Comment by wisnuwiry** [comment]
Any updates on this issue? 

cc: @Milad-Akarie

**Comment by theweiweiway** [comment]
@hazzo can you try on version 2.1.x and see if it works now? thnx

**Comment by hazzo** [comment]
Sorry for the delay It seems that now is working. Thanks
