### ISSUE TITLE
auto_route_generator 1.0.2 depends on build_runner ^1.12.2

### ISSUE THREAD

**Issue by zs-dima** [Milad-Akarie/auto_route_library#477]
Could be nice to update auto_route to use build_runner: ^2.0.0
however it is not high priority

**Comment by alexolivier** [comment]
This is blocking me migrating to NS. Any suggested workaround?

**Comment by Milad-Akarie** [comment]
You could overid the build runner dependency until the next build is released

**Comment by masseelch** [comment]
> This is blocking me migrating to NS. Any suggested workaround?

```yaml
dependency_overrides:
  build_runner: ^1.12.2
```
Remove when @Milad-Akarie publishes updated version.

**Comment by theweiweiway** [comment]
New version is compatible with build rubber 2.0.2
