### ISSUE TITLE
root route setting

### ISSUE THREAD

**Issue by ICoderMe** [Milad-Akarie/auto_route_library#478]
Ask a question. Applications usually have a splash page. If you want to pop after the start page ends and enter the homepage, how do you set the root route (initial: true)

**Comment by theweiweiway** [comment]
Honestly, I try to avoid this by having a splash page route, and instead have a SplashPage widget that I render when i am initializaing the app.

```dart
class InitApp extends HookWidget {
  @override
  Widget build(BuildContext context) {
    // Listen for auth state changes
    useEffect(() {
      authStateListener(context);
    }, []);

    return BlocBuilder<AuthCubit, AuthState>(
      builder: (context, state) {
        return state.maybeMap(
          initial: (s) => SplashScreen(),
          orElse: () => MainApp(),
        );
      },
    );
  }
```


In this case, I initialize everythign, then I wait for my auth state to be initialized. When the auth state is finally obtained, I render the main app. Otehrwise I render teh splashscreen. No routing required

**Comment by theweiweiway** [comment]
@ICoderMe did this solve your problem? Could you please close if it did
