### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by MartinaColucci** [Milad-Akarie/auto_route_library#479]
Hi, I have used Umap to make a map for my website. the map in the background is OSM-fr and I am not able to change it in English, I mean that whether I change the background map and I copy and paste the code on my website, the map still be in French. 

Thanks

**Comment by theweiweiway** [comment]
Hey, are you talking about a sitemap?

**Comment by MartinaColucci** [comment]
> Hey, are you talking about a sitemap?

Hi, yes! Thanks

**Comment by jlnrrg** [comment]
@MartinaColucci if this resolved your issue, please close it :smile:.

**Comment by theweiweiway** [comment]
closing due to duplicate issue: #329
