### ISSUE TITLE
Unable to set `transitionsBuilder` for `CustomRoute`

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/auto_route_library#482]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/12133914/115963505-e1745980-a51f-11eb-987f-be2c8cb44ad5.png">

Can't figure out how to define a constant function...

Can you please provide an example?

Thanks 🙏

**Comment by Milad-Akarie** [comment]
@pro100svitlo just define your function anywhere then pass the reference to it

```dart
 Widget fadeIn(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return FadeTransition(opacity: animation, child: child);
  }
```
then inside of custom route
`CustomRoute(transationsBuilder: fadeIn)`

**Comment by pro100svitlo** [comment]
Thanks 🙏
