### ISSUE TITLE
Passing rich object while using :param

### ISSUE THREAD

**Issue by wiradikusuma** [Milad-Akarie/auto_route_library#483]
I want my URL to represent the content ("You're in book detail 1"):

    AutoRoute(page: BookDetailsPage, path: '/books/:id'),

So that when user `F5` the page, it loads the same page. But I also want, when opened from another page (say by clicking an item in a list), to pass a rich object, which can be useful for hero animation (same image URL) and pre-loading the data.

What is the best approach to achieve that?

**Comment by theweiweiway** [comment]
Hey @wiradikusuma

You could do something like this: https://autoroute.vercel.app/basics/passing_arguments

But in addition to the rich object, you would also annotate a field with @PathParam. So it could look like:
```dart
class BookDetailsPage extends StatelessWidget {
    const BookDetailsRoute({@PathParam("id") this.id, this.book, this.onRateBook}); 
 
    final id;
    final Book book; 
    final void Function(int) onRateBook;
```

Is that what you mean?

**Comment by Milad-Akarie** [comment]
@theweiweiway  I was just replying the same lol

**Comment by Milad-Akarie** [comment]
can I add, id and book should booth be nullable and you got to do the checking.

**Comment by wiradikusuma** [comment]
Thanks @theweiweiway and @Milad-Akarie , good to hear that `PathParam` and rich object can be combined!
