### ISSUE TITLE
Rebuild/update TabsRouter state

### ISSUE THREAD

**Issue by KholmatovS** [Milad-Akarie/auto_route_library#484]
Thank you for this great library! 
I am using it for BottomNavigationBar with tabs router and wanted to know is there any method to explicitly rebuild or update routes state? Or at least ignore the stacking and recreate the pages every time the certain active index is selected. For example, I have the CartPage where all items added in my cart are listed, so when I switch to this page (select by index from bottom nav) I could just rebuild the entire page to update the list of data.

**Comment by Milad-Akarie** [comment]
@KholmatovS  how about setting a listener in your CartPage's did change deps
```dart
final tebsRouter = context.tabsRouter
tabsRouter.addListener((){
      if(tabsRouter.activeIndex == cartPageIndex){
      // update page  
      }
});
```
although I prefer passing an event to bloc holding the list state to refresh rather then refreshing the list everytime you open the page.

**Comment by KholmatovS** [comment]
Thank you! I've added the listener in CartPage when build is called for the first time, so whenever I change the active index to the cart, the list update is triggered. Everything works fine. 
Surely I agree about the bloc pattern, and definitely going to change it, but a bit later. Nevertheless, sometimes in different use-cases rebuilding the state is more convenient. 
Are you planning to make optional state preservation for tabs in the future? For example in TabsRouter's children make a field with `preserveState: true/false`, whenever the active index is selected with explicitly defined preservation state, the page is recreated

**Comment by KholmatovS** [comment]
By the way, thank you a lot, my problem is resolved for now and I'm going to close the issue
