### ISSUE TITLE
 '!keyReservation.contains(key)': is not true error when trying to push the same page a second time.

### ISSUE THREAD

**Issue by JimTacobs** [Milad-Akarie/auto_route_library#489]
I might be doing something crazy or something that's just not-done, but I just can't figure out a way to reach what I want to do. Keep in mind that I had this flow working with regular Flutter routing, but I want to migrate to auto_route to reduce boilerplate and create ease-of-use.

I have this application where users will visit the same screen multiple times, but the data that they see inside the screen is different every time. Imagine something like this, where each letter represents a screen.

A -> B -> C -> D -> E -> C -> F -> E -> .....

The application in question is an onboarding app, and it's necessary for the user to be able to use native back functionality (swiping on iOS/back button on Android) to navigate back to previous screens. Thus, solutions where I pop and then push don't seem suitable. I have all the logic in place to show the correct state on each screen, depending on where the user started going back, but I just can't push the same screen onto the Navigation stack for a second time. 

Before I share a minimal code example, I wondered if this is intended behavior? Or is there some property that I'm missing that lets me create a unique ID for each screen every time I want to push it onto the stack anew?

**Comment by JimTacobs** [comment]
After spending 2 hours on it, typing this out gave me an epiphany, it seems. Should just use Path Parameters here, works perfectly.  In case anyone else walks into this issue and struggles with it.

**Comment by Milad-Akarie** [comment]
Hey @JimTacobs  it is instead intended behavior by the native Navigator 2.0, I worked around it in older versions.
 I don't know your work flow but you should try navigate () instead of push
navigate  pops until the given route if it's already in stack otherwise it pushes a new one.

**Comment by JimTacobs** [comment]
Thank you Milad. Problem with using navigate seems to be that it manipulates the navigation stack, thus not allowing the user to go back through the flow the exact way they went forward. The above solution, using push with Path Parameters, does seem to work, though it does feel a tiny bit hacky.

**Comment by NamanShergill** [comment]
> 
> 
> Hey @JimTacobs it is indeed intended behavior by the native Navigator 2.0, I worked around it in older versions.
> I don't know your work flow but you should try navigate () instead of push
> navigate pops until the given route if it's already in stack otherwise it pushes a new one.

The assert still fails when using `navigateAll` instead of `pushAll`, making pushing similar routes over similar current ones impossible,

**Comment by JimTacobs** [comment]
I've found an alternative way to go about this. Instead of using Path Parameters, which would very easily cause unintended behaviour, I've created subscreens of my generic screens which are used at one and only one point in the application flow. I don't know if this would pass best-practice scrutiny, but it works for my usecase.

FooScreen is the generic screen, which contains all the logic to show the screen the correct way depending on the current state values (I use Riverpod).

```
class FooScreen extends StatelessWidget {
  @override Widget build() {
    return .....
  }
```

Because of the generic setup of FooScreen, I can create copies of this screen and not pass any logic to them (you could set up your generic screen to take arguments, of course). AutoRoute doesn't know about FooScreen, but does know about BarScreen and BazScreen. I set up my app in such a way that the correct concrete implementation of my generic screen is pushed at the right point in the flow. Thus, I don't need to worry about ids or possible duplication in the stack.

```
class BarScreen extends FooScreen {
  @override Widget build() {
    return FooScreen()
  }
}
```

```
class BazScreen extends FooScreen {
  @override Widget build() {
    return FooScreen()
  }
}
```
