### ISSUE TITLE
ExtendedNavigator.of(context) do not allows to call pushSecondScreen method

### ISSUE THREAD

**Issue by fedotxxl** [Milad-Akarie/auto_route_library#49]
Hello. I'm checking description:

```
ExtendedNavigator.of(context).pushSecondScreen(args...);
//or
ExtendedNavigator.ofRouter<Router>().pushSecondScreen(args...)
```

`ExtendedNavigator.ofRouter<Router>()` works as expected - I can call `pushSecondScreen` method. `ExtendedNavigator.of(context)` doesn't have any page-specific methods. Is the description correct?

**Comment by Milad-Akarie** [comment]
@fedotxxl both methods obtain the same class state, so ya they both should have page-specific push methods if you set the generation flag to true 
`@MaterialAutoRouter(generateNavigationHelperExtension: true)`

**Comment by fedotxxl** [comment]
Yes, you are right... it works now...
