### ISSUE TITLE
This requires the 'non-nullable' language feature to be enabled

### ISSUE THREAD

**Issue by aarajput** [Milad-Akarie/auto_route_library#490]
I am using flutter version 2.0.5 with dart version 2.7.0. 

When i run auto generate code command, it created  **app_router.gr.dart**  which have null safety code in it, so its giving me error because i am on dart version 2.7.0

What should i do?

<img width="560" alt="Screen Shot 2021-04-27 at 11 57 50 AM" src="https://user-images.githubusercontent.com/16102514/116198786-d273ee00-a74f-11eb-8f63-a833934f05ac.png">

**Comment by jlnrrg** [comment]
With version [1.0.0](https://pub.dev/packages/auto_route/changelog#100) auto_route migrated to null safety.
If it is a deliberate decision on your side to work without null safety enabled I'd like you to reconsider as more and more packages now have made the cut to nnbd.

If you decide for it anyway, you can always choose a version before 1.0.0 of auto_route. It should work then.

**Comment by aarajput** [comment]
I found that in **_auto_route_generator/lib/src/code_builder/library_builder.dart_** file, **_useNullSafetySyntax_** is set to **_true_.**

Is there a way to detect if supported dart version is greater or equal to 2.12, then set _useNullSafetySyntax_ to true, otherwise false ?

**Comment by jlnrrg** [comment]
Even if it would be possible, which I am not sure it is. There is a great reason to not do such a thing.
The code of auto_route is now on nnbd (which is awesome), which would mean, that for your convenience the maintainer would have to go the extra mile of maintaining two code bases.

The options you have concerning null safety is either to make the switch (highly recommended) or stay on a lower version of auto_route (and other packages for that matter)

**Comment by aarajput** [comment]
Thanks for your help. I am closing this ticket.
