### ISSUE TITLE
Force query parameters to be optional

### ISSUE THREAD

**Issue by ResoDev** [Milad-Akarie/auto_route_library#491]
Hello!
I can currently write this inside a page's constructor
```dart
@QueryParam('myParam') required this.myField
```
which successfully generates the code. However, this code fails when a query parameter is left out from the URL because the generated code requires the query parameter to be present in the parameters map.
```dart
queryParams.getString('myParam')
```

Then this generated code obviously fails if a query parameter is not provided in the URL.

I propose that non-optional query parameters must be provided a default value. After all, query parameters are not part of the path and are by definition optional. Leaving them out from the URL should not result in an error.

Another option would be to fail the code generation if you find a `required` field annotated with `@QueryParam`.

**Comment by Milad-Akarie** [comment]
Hello @ResoDev, I totally agree, I had it work like that before, path/query params must be nullable or have a default value but some users had issues with it so I removed assertion.
 I guess having the assertion work for just query parameters can work and won't make some users unhappy. 
 I'll include this in the next build. Thank you.

**Comment by Milad-Akarie** [comment]
@ResoDev  done in version 2.0.1
