### ISSUE TITLE
auto_route 2.0 Hot reload issue

### ISSUE THREAD

**Issue by zs-dima** [Milad-Akarie/auto_route_library#493]
auto_route 2.0 introduced Hot reload issue for nested navigation.

Ctrl + \ while app running and nested page open lead to error:

```
[ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: Failed to parse [String] bookId value from null, stack trace: #0      Parameters.getString (package:auto_route/src/common/parameters.dart:41:7)
#1      new AppAutoRouter.<anonymous closure>.<anonymous closure> (package:workshop/app/router.gr.dart:53:37)
#2      RouteData.argsAs (package:auto_route/src/route/route_data.dart:44:22)
#3      new AppAutoRouter.<anonymous closure> (package:workshop/app/router.gr.dart:51:30)
#4      RootStackRouter._pageBuilder (package:auto_route/src/router/widgets/root_stack_router.dart:56:20)
#5      StackRouter._addEntry (package:auto_route/src/router/controller/routing_controller.dart:784:29)
#6      StackRouter._pushAllGuarded (package:auto_route/src/router/controller/routing_controller.dart:748:18)
<asynchronous suspension>
```

**Comment by Milad-Akarie** [comment]
@zs-dima  please share Router setup

**Comment by zs-dima** [comment]
@Milad-Akarie 

```
@CustomAutoRouter(
  transitionsBuilder: TransitionsBuilders.fadeIn,
  durationInMilliseconds: 200,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomePage, initial: true),
    AutoRoute(
      path: '/book:bookId',
      page: BookRootPage,
      children: [
        AutoRoute(path: '', page: BookPage),
***
```

**Comment by AgarwalsRahul** [comment]
Hot Reload is not working with auto_route 2.0.1
main.dart file:
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  configureInjection(Environment.prod);
  HydratedBloc.storage = await HydratedStorage.build(
      storageDirectory: await getApplicationDocumentsDirectory());
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // status bar color
  ));

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final router = r.Router();
    return Sizer(
      builder: (context, orientation, deviceType) => MultiBlocProvider(
        providers: [
          BlocProvider(
            create: (context) => getIt<ThemeBloc>(),
          ),
          BlocProvider(
            create: (context) =>
                getIt<AuthBloc>()..add(const AuthEvent.checkedAuthStatus()),
          ),
        ],
        child: BlocBuilder<ThemeBloc, ThemeState>(
          builder: (context, state) {
            return MaterialApp.router(
              routerDelegate: router.delegate(),
              routeInformationParser: router.defaultRouteParser(),
              title: 'SineTee',
              debugShowCheckedModeBanner: false,
              themeMode: state.isDarkMode ? ThemeMode.dark : ThemeMode.light,
              theme: state.appTheme,
              // builder: ExtendedNavigator(
              //   router: r.Router(),
              // ),
            );
          },
        ),
      ),
    );
  }
}
Router:
@MaterialAutoRouter(routes: <AutoRoute>[
  AutoRoute(page: SplashScreen, initial: true),
  AutoRoute(page: Home),
  AutoRoute(page: InterestScreen),
  AutoRoute(page: AccountScreen),
  AutoRoute(page: AssignmentScreen),
  AutoRoute(page: OAuthScreen),
  AutoRoute(
    page: AuthSplashScreen,
  ),
  AutoRoute(
    page: OTPVerificationScreen,
  ),
  // AutoRoute(page: LoginPage),
  AutoRoute(page: LoginScreen),
  AutoRoute(page: CourseScreen),
  AutoRoute(page: DrillDetailPage),
  AutoRoute(page: NotificationScreen),
  AutoRoute(page: ForgotPasswordScreen),
  AutoRoute(page: ForgotPasswordSecondScreen),
  AutoRoute(page: SignUpScreen),
  AutoRoute(page: SecondSignUpScreen),
  AutoRoute(
    page: ChangePasswordScreen,
    // initial: true,
  ),
])
class $Router {}

**Comment by AgarwalsRahul** [comment]
> Hot Reload is not working with auto_route 2.0.1
> main.dart file:
> void main() async {
> WidgetsFlutterBinding.ensureInitialized();
> configureInjection(Environment.prod);
> HydratedBloc.storage = await HydratedStorage.build(
> storageDirectory: await getApplicationDocumentsDirectory());
> SystemChrome.setPreferredOrientations([
> DeviceOrientation.portraitUp,
> DeviceOrientation.portraitDown,
> ]);
> SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
> statusBarColor: Colors.transparent, // status bar color
> ));
> 
> runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
> @override
> Widget build(BuildContext context) {
> final router = r.Router();
> return Sizer(
> builder: (context, orientation, deviceType) => MultiBlocProvider(
> providers: [
> BlocProvider(
> create: (context) => getIt(),
> ),
> BlocProvider(
> create: (context) =>
> getIt()..add(const AuthEvent.checkedAuthStatus()),
> ),
> ],
> child: BlocBuilder<ThemeBloc, ThemeState>(
> builder: (context, state) {
> return MaterialApp.router(
> routerDelegate: router.delegate(),
> routeInformationParser: router.defaultRouteParser(),
> title: 'SineTee',
> debugShowCheckedModeBanner: false,
> themeMode: state.isDarkMode ? ThemeMode.dark : ThemeMode.light,
> theme: state.appTheme,
> // builder: ExtendedNavigator(
> // router: r.Router(),
> // ),
> );
> },
> ),
> ),
> );
> }
> }
> Router:
> @MaterialAutoRouter(routes: [
> AutoRoute(page: SplashScreen, initial: true),
> AutoRoute(page: Home),
> AutoRoute(page: InterestScreen),
> AutoRoute(page: AccountScreen),
> AutoRoute(page: AssignmentScreen),
> AutoRoute(page: OAuthScreen),
> AutoRoute(
> page: AuthSplashScreen,
> ),
> AutoRoute(
> page: OTPVerificationScreen,
> ),
> // AutoRoute(page: LoginPage),
> AutoRoute(page: LoginScreen),
> AutoRoute(page: CourseScreen),
> AutoRoute(page: DrillDetailPage),
> AutoRoute(page: NotificationScreen),
> AutoRoute(page: ForgotPasswordScreen),
> AutoRoute(page: ForgotPasswordSecondScreen),
> AutoRoute(page: SignUpScreen),
> AutoRoute(page: SecondSignUpScreen),
> AutoRoute(
> page: ChangePasswordScreen,
> // initial: true,
> ),
> ])
> class $Router {}

Also 
On Changing theme globally, It shows blank screen

**Comment by Milad-Akarie** [comment]
@AgarwalsRahul  your issue is simple just remove the router initiating from the build function
`final router = r.Router();`

**Comment by zs-dima** [comment]
@Milad-Akarie thanks for replying
I could not use Material.router with current project, but I could try with some test project.

This issue appear with auto_route 2.0.0 version and still exist

**Comment by zs-dima** [comment]
>  I can't reproduce this,

I could see exception I provided in logs, but app reloading and continue running on the same page (however maybe some re-navigation missing)

**Comment by zs-dima** [comment]
@Milad-Akarie reproduced with Material.router as well:

to reproduce press 'PRESS ME' button and 'Ctrl + \' for hot reload then.
based on your example:

main.dart
```dart
void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _rootRouter = RootRouter();

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        theme: ThemeData.dark(),
        routeInformationProvider: PlatformRouteInformationProvider(
          initialRouteInformation: RouteInformation(
            location: _rootRouter.current.path,
          ),
        ),
        routerDelegate: _rootRouter.delegate(
          initialDeepLink: Navigator.defaultRouteName,
        ),
        routeInformationParser: _rootRouter.defaultRouteParser(),
      );
}
```

Router
```dart
@CustomAutoRouter(
  transitionsBuilder: TransitionsBuilders.fadeIn,
  durationInMilliseconds: 200,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomePage, initial: true),
    AutoRoute(
      path: '/book:bookId',
      page: BooksRootPage,
      children: [
        AutoRoute(path: '', page: BookListPage),
      ],
    ),
    RedirectRoute(path: '*', redirectTo: '/'),
  ],
)
class $RootRouter {}
```


HomePage
```dart
class HomePage extends StatelessWidget {
  const HomePage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () => context.router.push(BooksRootRoute(bookId: 'test bookId')),
          child: Text('PRESS ME'),
        ),
      ),
    );
  }
}
```


BooksRootPage 
```dart
class BooksRootPage extends StatelessWidget {
  final String bookId;

  const BooksRootPage({
    Key? key,
    @PathParam('bookId') required this.bookId,
  }) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return AutoRouter(
      builder: (_, child) => child,
    );
  }
}
```

**Comment by zs-dima** [comment]
@Milad-Akarie looks routeInformationProvider lead to this error, however it worked fine with prev auto_router versions and it is required for the Router() widget I mention in the issue description.

**Comment by givip** [comment]
Yeah, I think I have the same issue #515

**Comment by Milad-Akarie** [comment]
@zs-dima What are you trying to do with line?
```dart
 routeInformationProvider: PlatformRouteInformationProvider(
          initialRouteInformation: RouteInformation(
            location: _rootRouter.current.path,
          ),
        ),
```

**Comment by zs-dima** [comment]
@Milad-Akarie 
routeInformationProvider required for the Flutter Router widget as I mention above.
and I have to use Router widget instead of MaterialApp.router.
It worked well with previous auto_route versions.

**Comment by Milad-Akarie** [comment]
@zs-dima I honestly have no idea how it worked before because it shouldn't, the current behavior is the expected one because every-time the App rebuilds you're providing a different RouteInformationProvider,

just do the following and you're golden

```dart
class _MyAppState extends State<MyApp> {
  final _rootRouter = RootRouter();
  final _routeProvider = PlatformRouteInformationProvider(
    initialRouteInformation: RouteInformation(
      location: Navigator.defaultRouteName,
      // on web you need to do this
      // location: WidgetsBinding.instance?.window.defaultRouteName ?? Navigator.defaultRouteName,
    ),
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: Router(
        routeInformationProvider: _routeProvider,
        routerDelegate: _rootRouter.delegate(),
        routeInformationParser: _rootRouter.defaultRouteParser(),
        backButtonDispatcher: RootBackButtonDispatcher(),
      ),
    );
  }
}
```

**Comment by zs-dima** [comment]
@Milad-Akarie thanks a lot, I missed it providing a different RouteInformationProvider on rebuilds.
