### ISSUE TITLE
auto_route: ^0.6.9 How to transfer auto_route: ^2.0.1 ExtendedNavigator

### ISSUE THREAD

**Issue by purgeyao** [Milad-Akarie/auto_route_library#498]
The extendedNavigator is no longer found at auto_route.
How should the following code be migrated
```
    return Consumer2<AppTheme, LocaleModel>(
        builder: (context, appTheme, localeModel, _) {
      return ScreenUtilInit(
          designSize: Size(828, 1792),
          builder: () => MaterialApp(
                title: 'abc',
                theme: ThemeData(
                  primarySwatch: appTheme.themeColor,
                  buttonColor: appTheme.themeColor,
                ),
                builder: ExtendedNavigator<RouterMap>(
                  navigatorKey: navigatorKey,
                  router: RouterMap(),
                  guards: [AuthGuard()],
                ),
```
ExtendedNavigator prompt does not exist
```
                builder: ExtendedNavigator<RouterMap>(
                  navigatorKey: navigatorKey,
                  router: RouterMap(),
                  guards: [AuthGuard()],
                ),
```

**Comment by theweiweiway** [comment]
Hey @purgeyao , AutoRoute 2.x deprecated the legacy AutoRoute. You should keep using version 1.x if you want to keep using ExtendedNavigator

Please see the example folder here: https://github.com/Milad-Akarie/auto_route_library/tree/master/auto_route/example 
to see how to use the new AutoRoute 2.x

Unfortunately, the documentation here https://autoroute.vercel.app/introduction is not even up to date with AutoRoute 2.x yet. Please give us some more time and those docs will be updated.

Sorry about this

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
