### ISSUE TITLE
User-configurable routes

### ISSUE THREAD

**Issue by wiradikusuma** [Milad-Akarie/auto_route_library#500]
I'm building an app like this:

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      usesTabsRouter: true,
      children: [
        AutoRoute(page: Page1),
        AutoRoute(page: Page3),
        AutoRoute(page: PageSettings),
      ],
    ),
    AutoRoute(page: Page2),
    AutoRoute(page: Page4),
    AutoRoute(page: Page5),
  ],
)
```

As you can see, `Page1` and `Page3` are "tab-able" using the bottom bar while the rest are standalone screens. This is **configurable** in `PageSettings`:

```
=Settings=
Select up to 3 pages to be put at the bottom menu.
[x] Page 1
[ ] Page 2
[x] Page 3
[ ] Page 4
[ ] Page 5
```

My questions: Does this library support my use case? If yes, how to achieve that? If no, do you know other libraries that do? Or do I need to use Navigator 2.0 directly?

**Comment by jlnrrg** [comment]
Yes it does, but probably not in the way you indent it to work, but feel free to try.
What you can do is have hard defined tabs, that load different widgets based on the selection.
And concerning the text or icons on the tabs you can just listen to changes in a provider like riverpod.

**Comment by Milad-Akarie** [comment]
yes, you just need to defined them both as tabRoutes and root routes for  linking to work
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      children: [
        AutoRoute(page: PageSettings),
       ..._configurableRoutes
      ],
    ),
     ..._configurableRoutes
  ],
)

const _configurableRoutes = [ 
 AutoRoute(page: Page1),
     AutoRoute(page: Page3),
    AutoRoute(page: Page2),
    AutoRoute(page: Page4),
    AutoRoute(page: Page5),
]
```
then in your AutoTabsRouter decide what routes to show

```dart
AutoTabsRouter(
routes: [
    Page1Route(),
    Page2Route(),
   if(userWantsPage3) Page3Route() 
  else Page4Route()
]
);
```

**Comment by wiradikusuma** [comment]
Thanks, I'll give it a try, didn't know you can put the route more than once!
