### ISSUE TITLE
Navigating to another tab doesn't take arguments

### ISSUE THREAD

**Issue by steve-cahn** [Milad-Akarie/auto_route_library#502]
I'm using the bottom navigation tabs. When I'm in tab 3 and try to navigate to tab 2 with arguments, the new page opens up without computing the arguments.

So for example, if I have this:

```dart
context.tabsRouter
  ..setActiveIndex(1)
  ..innerRouterOf<StackRouter>(ProfileRouter.name)
  .push(ProfileRoute(name: 'Sam')); 
```
The profile page will get null for "name". What am I doing wrong and how can I fix it?

**Comment by theweiweiway** [comment]
Sorry - documentation not updated for this - but I believe the new way to navigate to another page in a tab is just to simply

`context.tabsRouter.pushToChild(...`

Can you try that and let me know if it works?

**Comment by steve-cahn** [comment]
Tried this: `context.tabsRouter.pushToChild(ChildOfAnotherRoute());`
but got this error:

Can not find a child controller to handle OrdersRoute

```
When the exception was thrown, this was the stack
#0      TabsRouter._findStackRouterIndexFor
```

**Comment by Milad-Akarie** [comment]
@steve-cahn please post your router setup.

**Comment by Milad-Akarie** [comment]
@steve-cahn you can now use context.navigateTo(MyTabe(chidlern:[])); or context.navigateNamedTo('myTab/child');
closing this for now.
