### ISSUE TITLE
AutoBackButton issue

### ISSUE THREAD

**Issue by scarnett** [Milad-Akarie/auto_route_library#504]
The recent 2.0.2 update seems to have introduced a breaking change where the `AutoRouteButton` never displays even though the route can be popped.

![image](https://user-images.githubusercontent.com/798305/116758576-fcd6dd00-a9d5-11eb-9dad-eebdcd758823.png)

The condition on line 19 always evaluates to false. It seems to work as expected when I downgrade to 2.0.1.

**Comment by Milad-Akarie** [comment]
should be fixed in auto_route 2.1.0 
please confirm and close.

**Comment by scarnett** [comment]
Hi, after upgrading and running the build_runner I get quite a few errors now in the generated router file.

![image](https://user-images.githubusercontent.com/798305/117302655-7c830280-ae41-11eb-8b78-f9e3ddcf7a53.png)
![image](https://user-images.githubusercontent.com/798305/117302707-8d337880-ae41-11eb-9314-8535cdff713d.png)
![image](https://user-images.githubusercontent.com/798305/117302816-ab00dd80-ae41-11eb-9084-1857481838db.png)

**Comment by theweiweiway** [comment]
still a problem in 2.2.x?

**Comment by scarnett** [comment]
@theweiweiway yes, I get these errors in 2.2.0

Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
Flutter version 2.0.6
Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
Engine revision 05e680e202
Dart version 2.12.3
