### ISSUE TITLE
Android system back button closes whole app

### ISSUE THREAD

**Issue by Ae-Mc** [Milad-Akarie/auto_route_library#507]
Breaked in `auto_route 2.0.2` with `auto_route_generator 2.0.1`. Version `2.0.1` with `auto_route_generator 2.0.1` works normally.

**Comment by Milad-Akarie** [comment]
@Ae-Mc is this still an issue with 2.1.0 update?

**Comment by Ae-Mc** [comment]
No, issue fixed.
