### ISSUE TITLE
Please, update new documentation on autoroute.vercel.app

### ISSUE THREAD

**Issue by Ae-Mc** [Milad-Akarie/auto_route_library#508]
[autoroute.vercel.app/introduction](https://autoroute.vercel.app/introduction)

**Comment by theweiweiway** [comment]
Sorry, I've been quite busy - but this is on my TODO list asap!

**Comment by Ae-Mc** [comment]
At least add information about documentation's auto_route version. It's confusing that examples from documentation are not working.

**Comment by theweiweiway** [comment]
OK - docs are updated! 

I still need to add some more material, but they should be relevant for 2.1.0 now!
