### ISSUE TITLE
AutoTabsScaffold and WillPopScope

### ISSUE THREAD

**Issue by bogdanmarinescu** [Milad-Akarie/auto_route_library#509]
AutoTabsScaffold should expose an `onWillPop` method in order to override the back button functionality.

example:
```
AutoTabsScaffold(
  onWillPop: (TabsRouter tabs) async {
    if (tabs.activeIndex == 0) {
      return true;
    }
    tabs.setActiveIndex(tabs.activeIndex - 1);
    return false;
  },
)
```

**Comment by Milad-Akarie** [comment]
@bogdanmarinescu  why not just wrap it above it?

**Comment by carlosfiori** [comment]
> @bogdanmarinescu why not just wrap it above it?

I think it's because of the access on the TabsRouter variable, if you wrap above that, you need to store TabsRouter somewhere else to access its methods on WillPopScope

**Comment by bogdanmarinescu** [comment]
sorry for not answering. @carlosfiori is right.

**Comment by ruclip** [comment]
I'm using `WillPopScope` Widget in the `bottomNavigationBuilder`.  It works like a charm 💪 

```
[...]
bottomNavigationBuilder: (context, tabsRouter) {
        return WillPopScope(
          onWillPop: () => onBackPressed(tabsRouter),
          child: [...]
```
