### ISSUE TITLE
Is there a way to render a common widget across the App?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/auto_route_library#51]
Hi,

With respect to your latest changes to auto_route, I am looking for a way to render a widget that can be accessible across the app. Earlier I used to something like this:

```dart
MaterialApp(
  builder: (BuildContext context, Widget widget) {
    setErrorBuilder();

    return Column(
      children: <Widget>[
        Expanded(
          child: widget,
        ),
        AlertsScreen(),
      ],
    );
  },
  title: 'App name',
  onGenerateRoute: Router.onGenerateRoute,
  initialRoute: Router.splashScreen,
  navigatorKey: Router.navigator.key,
),
```

1) But now since the builder is used for Navigation I am unable to mount `AlertsScreen` widget into the app. Is there a way to mount a common widget which can be accessible across the app?

2) Is it possible to get the right context for such common widgets as the below code used to throw the error:

code: 
```dart
//AlertsScreen.dart

Flushbar(
      title: 'title',
      message: 'body',
      duration: const Duration(seconds: 5),
    ).show(context);
```

error:
> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Navigator operation requested with a context that does not include a Navigator. The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.

[AlertsScreen.dart source](https://github.com/ganeshrvel/open_cloud_encryptor/blob/login-alerts-screens/lib/features/alerts/ui/pages/alerts.dart)

Thanks

**Comment by Milad-Akarie** [comment]
Hey @ganeshrvel for some reason I didn't get notified of this issue..I stumbled upon it just now
the widget in this line is actually a native navigator widget 
` builder: (BuildContext context, Widget widget) {`
so instead of returning it return an ExtendedNavgiator widget

```dart
 return Column(
      children: <Widget>[
        Expanded(
          child: ExtendedNavigator<Router>(router: Router()),
        ),
        AlertsScreen(),
      ],
    );
```
