### ISSUE TITLE
 Unhandled exception when push with argument

### ISSUE THREAD

**Issue by dafinoer** [Milad-Akarie/auto_route_library#510]
hi, i try to push some page with argument
```
await context.router.push(CameraPreviewPageRoute(
          path: path,
          isSubmit: (isSubmit) {
            if (isSubmit == true) {
              pickedData =
                  PickedData(path: path, takenDateTime: DateTime.now());
            }
          }));
```
and i'm get some exception ` Unhandled Exception: Expected [CameraPreviewPageRouteArgs],  found [CameraPreviewPageRouteArgs]`

```
T argsAs<T>({T Function()? orElse}) {
    final args = route.args;
    if (args == null) {
      if (orElse == null) {
        throw FlutterError(
            '${T.toString()} can not be null because it has a required parameter');
      } else {
        return orElse();
      }
    } else if (args is! T) {
      throw FlutterError(
          'Expected [${T.toString()}],  found [${args.runtimeType}]');
    } else {
      return args;
    }
  }
```
above the code, i think, args it's must be true with generic type, but why i get throw exception?

**Comment by Milad-Akarie** [comment]
@dafinoer are you using duplicate route names or anything? 
could you check if this is still in issue in version 2.1.0?

**Comment by dafinoer** [comment]
ok, i will check this issue.

**Comment by carlosfiori** [comment]
Hi @Milad-Akarie, I’m also facing this problem, but in my case I use microapps, and generate all routes twice, one for navigation between microapps (the root navigator) and another for internal microapp navigation

Do you have any sugestion how to handle this?

**Comment by carlosfiori** [comment]
@joshuadeguzman I'm also in the same situation, using two app routers.
I made a PR #865 adding an option to generate or not the argument, this way only one argument is generated, and the error does not happen
