### ISSUE TITLE
Propagate parent path parameters

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#511]
I have the following route structure:

```dart
AutoRoute(path: ':conversationId', page: ChatEmptyView, children: [
    AutoRoute(path: '', page: ChatView),
    AutoRoute(path: 'info', page: ChatInfoView),
]),
```

and my `ChatView` requires `conversationId`:
```dart
ChatView({
    @PathParam() required this.conversationId,
 });
 ```
 
 But generator throws an error since the `conversationId` path parameter is from the parent:
 
 ```dart
 ChatRoute.name: (routeData) {
      var pathParams = routeData.pathParams;
      final args = routeData.argsAs<ChatRouteArgs>(
          orElse: () => ChatRouteArgs(
              conversationId: pathParams.getString('conversationId')); // <-- Throws an exception here since conversationId is null
      return _i1.CustomPage<dynamic>(
          routeData: routeData,
          child: _i19.ChatView(
              conversationId: args.conversationId),
          opaque: true,
          barrierDismissible: false);
    },
 ```
 
 Is there a way to propagate parent path parameters ? I was using `router.parent()` before to access the parameters but I recently updated to null safety so this isn't working like before. Do I need to set `conversationId` to optional

**Comment by Milad-Akarie** [comment]
@Herrera93 in the current setup you can't access inherited params using @pathParam, if you're using the latest version you can go `conetxt.routeData.inheritedPathParams`
