### ISSUE TITLE
Prefer final for variable declarations if they are not reassigned.

### ISSUE THREAD

**Issue by andrewsleeman24** [Milad-Akarie/auto_route_library#513]
Having recently upgrade the flutter with nullable types I have started get lint errors like the fiolllow:
`Prefer final for variable declarations if they are not reassigned`

The generated code is 
`...`
`    },`
`    OrganizationPageRoute.name: (entry) {`
`      var args = entry.routeData.argsAs<OrganizationPageRouteArgs>();`
`      return _i1.MaterialPageX(`
`         entry: entry,`
`          child: _i5.OrganizationPage(key: args.key, orgLo: args.orgLo));`
`    },`
`...`

Add I belive should be:
`...`
`    },`
`    OrganizationPageRoute.name: (entry) {`
`      final args = entry.routeData.argsAs<OrganizationPageRouteArgs>();`
`      return _i1.MaterialPageX(`
`          entry: entry,`
`          child: _i5.OrganizationPage(key: args.key, orgLo: args.orgLo));`
`    },`
`...`

that is the work 'var' should be 'final'

**Comment by Milad-Akarie** [comment]
You're not using the latest version, that has already been fixed.
