### ISSUE TITLE
Is there a way to navigate without context? 

### ISSUE THREAD

**Issue by incrypto32** [Milad-Akarie/auto_route_library#514]
Is there a way in which i can navigate without context earlier when not using i used a navigatorKey to do that is there any way i can do it with this with auto_route?

**Comment by steve-cahn** [comment]
Were you able to figure out how to do that?

**Comment by Milad-Akarie** [comment]
Are you guys using any dependency injection package like get_it in your Apps?

**Comment by jlnrrg** [comment]
duplicate issue #495

**Comment by incrypto32** [comment]
> Are you guys using any dependency injection package like get_it in your Apps?

@Milad-Akarie Iam using get_it ?what about it?

**Comment by 838** [comment]
@Milad-Akarie

How can we inject the generated `AppRouter` via `Injectable` plugin? 

I tried to inject it as a third party module 

```dart
/// injection.dart

final inject = GetIt.I;

@module
abstract class RegisterCoreDependencies {
  AppRouter get appRouter => AppRouter();
}


/// main.dart

final  _router => inject<AppRouter>();

Widget build(BuildContext context) => MaterialApp.router(
  routerDelegate: _appRouter.delegate(),
  routeInformationParser: _appRouter.defaultRouteParser(),
);


/// widget.dart 

final _router => inject<AppRouter>();

onPressed() => _router.push(const HomeRoute());
```

But when I trie to call `push` I get this error: 
```log 
Unhandled Exception: [Root Router] Router can not navigate to home-page
```

**Comment by Milad-Akarie** [comment]
@838 your injection looks fine, you're getting the router instance.
can I see your router setup?

**Comment by Milad-Akarie** [comment]
@incrypto32 What @838  did is exactly what I was talking about. alternately you can assign your generated router as a global variable which I personally don't recommend but it works.

**Comment by 838** [comment]
@Milad-Akarie 

Sorry I tried to simplify the code, so I just mistyped the variable name. otherwise, it looks correct in the project :).

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: LoginPage, initial: true),
    AutoRoute(page: HomePage),
  ],
)
class $AppRouter {}

**Comment by 838** [comment]
I'm not sure if it's because the current context of the navigationKey is null.

<img width="702" alt="Screenshot 2021-05-06 at 10 52 57 PM" src="https://user-images.githubusercontent.com/3314171/117364126-d0cbc800-aebd-11eb-8198-4a8b1832966f.png">

**Comment by 838** [comment]
Actually the issue was in how I registered the `AppRouter`:

```dart
/// Won't work!
@module
abstract class RegisterCoreDependencies {
  AppRouter get appRouter => AppRouter();
}


/// This works!
@module
abstract class RegisterCoreDependencies {
    final AppRouter appRouter = AppRouter();
}

**Comment by 838** [comment]
@Milad-Akarie 

Thank you :) 

Why wouldn't you recommend ? what problems could we encounter ?

**Comment by Milad-Akarie** [comment]
@838 because each nested router has it's own routing controller that's created by the widgets `AutoRouter` or `AutoTabsRouter`, if you try to access one of these controllers before they're created you might end up with a null controller so maybe just be aware of that.
