### ISSUE TITLE
EmptyRouterPage doesn't render children after Hot restart/reload

### ISSUE THREAD

**Issue by givip** [Milad-Akarie/auto_route_library#515]
Before update to versions ^2.0.0 (current version is 2.0.2) everything worked as expected.
After update I noticed that Hot restart/reload provides blank screen under `EmptyRouterPage`, the interesting fact is, that `ConversationsView` is stateful widget and loads some data from network. 
So it shows spinner for a moment and then, after changing state, blank screen.

I checked issues 
https://github.com/Milad-Akarie/auto_route_library/issues/467 
https://github.com/Milad-Akarie/auto_route_library/issues/285
and this doesn't help.

Interesting fact, that in Cold start `builder` function in AutoTabsRouter called twice, but after Hot restart called four times. 

Here is Router definition:
```dart
@AdaptiveAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: <AutoRoute>[
    // Onboarding routes were there
    
    // App
    AdaptiveRoute(
      initial: true,
      guards: [AuthGuard],
      path: '/',
      page: DashboardView, //This is wrapper around AutoTabsRouter, which includes following routes 'FolderRoute', 'ConnectionsRoute', 'ChannelsRoute, 'DiscoverRoute'
      children: [
        RedirectRoute(path: '', redirectTo: 'folder'),
        AdaptiveRoute(
          path: 'folder',
          page: EmptyRouterPage,
          name: 'FolderRouteName',
          children: [
            RedirectRoute(path: '', redirectTo: 'active'),
            AdaptiveRoute(path: ':folder', page: ConversationsView),
          ],
        ),
        AdaptiveRoute(path: 'connections', page: ConnectionsView, name: 'ConnectionsRouteName'),
        AdaptiveRoute(path: 'channels', page: WorkInProgress, name: 'ChannelsRouteName'),
        AdaptiveRoute(path: 'discover', page: WorkInProgress, name: 'DiscoverRouteName'),
      ],
    ),

    //Other routes were there

    RedirectRoute(path: '*', redirectTo: '/'),
  ],
)
class $MobileRouter {}
```

Flutter doctor output:
```
➜  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by Milad-Akarie** [comment]
@givip you're on mobile right?

**Comment by givip** [comment]
Yes

**Comment by Milad-Akarie** [comment]
I have almost the same exact setup buy my hot reloads works just fine?
![May-05-2021 15-54-35](https://user-images.githubusercontent.com/55059449/117152368-3df63500-adba-11eb-963e-d4d23d740947.gif)

**Comment by Milad-Akarie** [comment]
@givip  I'm preparing release 2.1.0 right now, I might've changed something during my refactoring ( I do alot of refactoring lol) maybe wait until you test your code on 2.1.0?

**Comment by theweiweiway** [comment]
they call him... the REFRACTOR-MASTER 😎😎😎

**Comment by Milad-Akarie** [comment]
@theweiweiway I hear he refactors with no tests!!
![Family Guy Peter Griffin  Telling A Scary Story At Fat Camp](https://user-images.githubusercontent.com/55059449/117156441-fa9dc580-adbd-11eb-878c-b8bb3cfbcf03.jpeg)

**Comment by theweiweiway** [comment]
![n](https://user-images.githubusercontent.com/49566929/117157596-b514d480-ad8c-11eb-921a-55855dfa4742.png)

**Comment by givip** [comment]
I think, I'm doing something wrong. Updated on version 2.1.0 and now I always see blank screen. May be we can debug deeply my case?

**Comment by givip** [comment]
main.dart:

```
void main() async {
  final router = isWeb
      ? WebRouter(
          authGuard: AuthGuard(),
          noAuthGuard: NoAuthGuard(),
        )
      : MobileRouter(
          authGuard: AuthGuard(),
          noAuthGuard: NoAuthGuard(),
        );
  runApp(
    MyApp(router, false),
  );
}

class MyApp extends StatefulWidget {
  final RootStackRouter router;
  final bool isLoggedIn;

  MyApp(this.router, this.isLoggedIn);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  _MyAppState();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'TestApp',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightThemeData,
      darkTheme: AppTheme.darkThemeData,
      routerDelegate: widget.router.delegate(),
      routeInformationParser: widget.router.defaultRouteParser(),
      localizationsDelegates: [
        DefaultMaterialLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      builder: (_, child) => child!,
    );
  }
}
```

<img width="985" alt="Screenshot 2021-05-06 at 12 21 47" src="https://user-images.githubusercontent.com/14872445/117265774-a2ba9980-ae65-11eb-9a58-70c0cf5435b8.png">

**Comment by Milad-Akarie** [comment]
@givip are you doing some in the builder?
`builder: (_, child) => child!,` 
cause child here is the actual router widget.

**Comment by givip** [comment]
> @givip are you doing some in the builder?
> 
> `builder: (_, child) => child!,` 
> 
> cause child here is the actual router widget.

What I should do?

**Comment by Milad-Akarie** [comment]
@givip is there a reason why you're passing an empty builder?

**Comment by givip** [comment]
> @givip is there a reason why you're passing an empty builder?
> 
I'm not sure, it worked before, what is the "right" way to do? Is there any guide for that?

**Comment by givip** [comment]
It seems problem in in AutoGuardRouter:

Event if I even use Guard with `return true` it doesn't work

Finally I removed guards at all and it worked.

**Comment by givip** [comment]
So removing guards fix the totally blank screen, but initial issue described in first message is still there.

**Comment by theweiweiway** [comment]
if you're on 2.1.0, the guard works a bit different. You can't do `return true`, instead you need to do 

```dart
 void onNavigation(NavigationResolver resolver, StackRouter router) {
    // do stuff, then proceed
    resolver.next(true);
```
sorry will add to documentation soon

**Comment by givip** [comment]
> if you're on 2.1.x, the guard works a bit different. You can't do `return true`, instead you need to do
> 
> ```dart
> // in 2.1.0, onNavigation is canNavigate
>  void onNavigation(NavigationResolver resolver, StackRouter router) {
>     // do stuff, then proceed
>     resolver.next(true);
> ```
> 
> sorry will add to documentation soon

Will try

**Comment by givip** [comment]
Yes, blank screen gone. The initial problem is still there. What additional information I can provide for solving?

**Comment by givip** [comment]
I feel, that something wrong with Guard setup
```

class AuthGuard extends AutoRouteGuard {
  final _auth = locator<AuthenticationService>();

  @override
  void canNavigate(NavigationResolver resolver, StackRouter router) async {
    if (!_auth.isLoggedIn) {
      if (isWeb && resolver.pendingRoutes.last.path != '/') {
        await router.root.push(LoginRoute(
          showBackButton: resolver.pendingRoutes.first is! WelcomeRoute,
          onLoginResult: (success) {
            if (success) {
              router.replaceAll(
                  resolver.pendingRoutes.map((e) => PageRouteInfo.fromMatch(e)).toList());
            }
          },
        ));
      } else {
        await router.root.push(const WelcomeRoute());
      }
      return resolver.next(false);
    }
    return resolver.next(true);
  }
}

class NoAuthGuard extends AutoRouteGuard {
  final _auth = locator<AuthenticationService>();

  @override
  void canNavigate(NavigationResolver resolver, StackRouter router) async {
    if (_auth.isLoggedIn) {
      await router.root.push(const DashboardRoute());
      return resolver.next(false);
    }
    return resolver.next(true);
  }
}
```

**Comment by givip** [comment]
@theweiweiway @Milad-Akarie Solved by removing GlobalKey from DashboardView
