### ISSUE TITLE
context.navigateTo (AutoRouter.of(context) also) makes popUntilRoot.

### ISSUE THREAD

**Issue by AlexandrFarkas** [Milad-Akarie/auto_route_library#516]
Call to 'navigate' clears Navigator's history.  But it should push instead (cause pushed route doesn't exist when "navigate" is  called).

**Comment by Milad-Akarie** [comment]
Test with new version?

**Comment by AlexandrFarkas** [comment]
Yes, 2.0.2

**Comment by AlexandrFarkas** [comment]
Fixed in 2.1.0
