### ISSUE TITLE
Is it possible to use the same screen in 2 nested screens?

### ISSUE THREAD

**Issue by AlexandrFarkas** [Milad-Akarie/auto_route_library#519]
I have 2 tabs, which can navigate to the same screen. I don't need to differentiate them. Also, I don't want to push that route over tabs (hide bottom nav bar). What could I do?

**Comment by AlexandrFarkas** [comment]
Yes, it's possible with 2.1.0. No workarounds needed

**Comment by jlnrrg** [comment]
It is great to hear that you were able to do it. But please provide a solution or link for those coming after you.
Thanks

**Comment by Shahmirzali-Huseynov** [comment]
@AlexanderFarkas how ? can you give example

**Comment by AlexanderFarkas** [comment]
Just define it in 2 places, as usual.

I've not been using auto route for more than a year, so no code example at my disposal.
