### ISSUE TITLE
ExtendedNavigator error

### ISSUE THREAD

**Issue by matthewfx** [Milad-Akarie/auto_route_library#52]
Hi,

When I try to use
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
    // Tell MaterialApp to use our ExtendedNavigator instead of
    // the native one by assigning it to it's builder
    // instead of return the nativeNavigator we're returning our ExtendedNavigator
     builder: ExtendedNavigator<Router>(router: Router()),
    );
  }
}
```

I'm getting errors:
`The argument type 'ExtendedNavigator' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget)'.dart(argument_type_not_assignable)
The type 'ExtendedNavigator' is declared with 0 type parameters, but 1 type arguments were given.
Try adjusting the number of type arguments.dart(new_with_invalid_type_parameters)`

on the other hand this is working fine:

```
return MaterialApp(
      title: 'Covid Checker',
      debugShowCheckedModeBanner: false,
      initialRoute: Router.formPageView,
      onGenerateRoute: Router.onGenerateRoute,
      navigatorKey: Router.navigator.key,
      theme: covidTheme(),
    );
```

What am I doing wrong?

And the other question is how to add a nested navigator? Should it also be passed at the top level of the widget tree (MaterialApp)?

**Comment by edwardaux** [comment]
The compiler error message isn't very helpful here. The fix should be just adding this at the top of your file:
```
import 'package:auto_route/auto_route.dart';
```

**Comment by matthewfx** [comment]
The import has been there...

**Comment by Milad-Akarie** [comment]
Hey @matthewfx it looks like your'e using an old version of auto_route
latest versions are
auto_route: 0.4.2
auto_route_generator: 0.4.0

**Comment by matthewfx** [comment]
That's probably it. I added it to my app last week though. Pretty impressive pace of upgrades! Thanks! Please tell me where I should add the nested navigator?  Should it also be passed at the top level of the widget tree (MaterialApp)?

**Comment by Milad-Akarie** [comment]
A navigator is just another widget. 

```dart
class NestedHomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ExtendedNavigator<NestedRouter>(
                router: NestedRouter(),
              );
  }
```
You're gonna need a Nested Router of course

**Comment by matthewfx** [comment]
Awesome man! Thank you! I have one more question though. ;)  Considering the code above how one passes arguments to the initial route?
