### ISSUE TITLE
Route title 

### ISSUE THREAD

**Issue by paweldziennik** [Milad-Akarie/auto_route_library#521]
Hi!

Is there option to provide something like title for route? 
What I would like to achieve is display configurable route title in toolbar/appbar. While I could do it using `AutoRouteObserver` and switch over route type, I think it would be nice to have it as optional parameter in `Route`

**Comment by Milad-Akarie** [comment]
@paweldziennik that would be easy to add but what about localization?

**Comment by Milad-Akarie** [comment]
What I usually do is have a map of all my routes and their translations like so

```dart
final _routeTitles = {
 HomeRoute.name : 'localized home page title',
 ProfileRoute.name : 'localized route page title',
 // ... rest of the routes
};
```
then use the titles from the map
`AppBar(title: Text(_routeTitles[context.routeData.name]));`

**Comment by paweldziennik** [comment]
Yeah I was thinking about similar solution with using `route.name` but started to wonder if adding parameter `title` to `AutoRoute` wouldn't be more effective/declarative. But then I don't know if transition this parameter to `Route` is easy/possible.
```dart
CustomRoute(path: "/path", name:"name", title:"localized page title" ... )
```
Idea is to have such listener and being able to get title of pushed page: 
```dart
class RouteListner extends AutoRouterObserver {
  Function(Route route)? routePushed;
  @override
  void didPush(Route route, Route? previousRoute) {
    routePushed?.call(route);
    super.didPush(route, previousRoute);
  }
}
```

Of course this

> final _routeTitles = {
 HomeRoute.name : 'localized home page title',
 ProfileRoute.name : 'localized route page title',
 // ... rest of the routes
};

will also do a trick, but I think additional parameter is more scalable :)

**Comment by Milad-Akarie** [comment]
@paweldziennik that's the thing, you can only pass const values toe AutoRoute
```dart
CustomRoute(path: "/path", name:"name", title:"this string can't be localized here" ... )
```
The `CupertionRoute` already has a title property that will be passed to PageRoute builder, give it a look to get my point.

**Comment by paweldziennik** [comment]
I see, then indeed map solution looks as quickest and best solution there.
Thanks!
