### ISSUE TITLE
auto_route 2.+ docs?

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#524]
Hello everyone, 
With the latest release 2.2.0 out I think we've fixed and enhanced most of  the important navigation concepts and we are now ready to focus on writing some good docs because what we have now doesn't seem to help much. 

What do you guys think are most concepts or areas that new/existing auto_route users struggle to get familiar with? 
Would you prefer working examples are explained snippets?

**Comment by mikepyts** [comment]
@Milad-Akarie hello, once I have started to work with auto-route 2.0 after 1.0 seems like the biggest gap in understanding was for using the right router, especially once we are going deeper with a real mix of stack router  + tabs + nested navigators inside tabs and navigations between nested tabs pages. The second thing is missing docs for helpers like pushNamed(), pushAll() which sometimes are very useful but require time to get into the source a bit. Thanks for the topic!

**Comment by theweiweiway** [comment]
For the navigation methods - I've updated them a bit here: https://autoroute.vercel.app/basics/navigation

Open to suggestions tho

**Comment by SalahAdDin** [comment]
What happened with tabs navigation?

**Comment by Milad-Akarie** [comment]
@SalahAdin no need to use it, using the AutoTabsRouter widget is enough.

**Comment by SalahAdDin** [comment]
> @salahadin no need to use it, using the AutoTabsRouter widget is enough.

could you address us to the correct documentation about that widget?

**Comment by Milad-Akarie** [comment]
@SalahAdDin We're still working on the docs, it's pretty straight forward you should be able to implement it following this example 
https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/screens/home_page.dart
in this example we're using an AutoTabsScaffold to simplify the implementation.

**Comment by SalahAdDin** [comment]
It should be good to have an example for independent sections, and also, combining with drawer navigation, if it is possible.

**Comment by Milad-Akarie** [comment]
@SalahAdDin what do you mean by independent sections?

**Comment by SalahAdDin** [comment]
For example, one **Dashboard** screen with four tabs and one **Home** screen with two tabs.

**Comment by Milad-Akarie** [comment]
@SalahAdDin  ya that's simple, we're talking mobile here?

**Comment by SalahAdDin** [comment]
yeah, for doing responsive dashboards(tablet/mobile).

**Comment by AcodeWang** [comment]
I have 3 question : 

1. for the version of auto_route & auto_route_generator, is it a good way to keep 2 package same version name. For now the auto_route [latest_version] = 2.2.0, but auto_route_generator [latest_version] = 2.1.0. It could be a little confusing.

2. I found in the doc for Cross-tab Navigation : I could use `context.navigateTo(AccountRouter(children: AccountDetailsRoute()))` or `context.tabsRouter.navigate(AccountRouter(children: AccountDetailsRoute()))` 
What's the diffrence between `navigateTo()` and `router.navigate()`

3. With navigation we can navigate without pushing to the stack (for example on web no history in back button), how could I achive this with auto_route ?

**Comment by jlnrrg** [comment]
Ok, it should be no secret that I am a pretty big fan of https://autoroute.vercel.app/ . (the readme has to reflect the website. It is confusing to have different documentation states)
I like the concept of having a website to research certain use cases and see snippets for that. 
On the otherhand I also like to get inspired looking at an example which implements **everything** that is possible with the library.

For new users these concept seem to be problematic:
1. getting the right router
2. setting up children of a route (+ how to implement the additional router that is needed for that)
3. different ways of passing arguments

For advanced users these might seem useful:
4. implementing AuthGuard
5. implementation of RouteAware and RouteObservers in general (and maybe what to do with it)
6. an overview of usefull autoRoute classes and how to access them

**Comment by jlnrrg** [comment]
Is there any news on the state of a documentation? :pray:

**Comment by SalahAdDin** [comment]
> Is there any news on the state of a documentation? 🙏 also @theweiweiway please include a version number in https://autoroute.vercel.app/ (I think it's yours if I remember correctly). It becomes very confusing searching for information and then figuring out that it has become outdated. (same for the readme, I guess)

I think it was not done.

**Comment by SalahAdDin** [comment]
> Is there any news on the state of the documentation? 🙏 also @theweiweiway please include a version number in https://autoroute.vercel.app/ (I think it's yours if I remember correctly). It becomes very confusing searching for information and then figuring out that it has become outdated. (same for the readme, I guess)

@Milad-Akarie I think it was not done.

**Comment by SalahAdDin** [comment]
> Is there any news on the state of the documentation? 🙏 also @theweiweiway please include a version number in https://autoroute.vercel.app/ (I think it's yours if I remember correctly). It becomes very confusing searching for information and then figuring out that it has become outdated. (same for the readme, I guess)

@Milad-Akarie I think it was not done.

**Comment by SalahAdDin** [comment]
> Is there any news on the state of the documentation? pray also @theweiweiway please include a version number in https://autoroute.vercel.app/ (I think it's yours if I remember correctly). It becomes very confusing searching for information and then figuring out that it has become outdated. (same for the readme, I guess)

It seems this repository is not actively maintained, isn't it @Milad-Akarie ?

**Comment by SalahAdDin** [comment]
> Is there any news on the state of a documentation? pray also @theweiweiway please include a version number in https://autoroute.vercel.app/ (I think it's yours if I remember correctly). It becomes very confusing searching for information and then figuring out that it has become outdated. (same for the readme, I guess)

It seems this repository is not actively maintained, isn't it @Milad-Akarie ?
