### ISSUE TITLE
work with functional_widget 0.9.0+1?

### ISSUE THREAD

**Issue by ktae13-npnf** [Milad-Akarie/auto_route_library#525]
Hello everyone,

Does anybody use auto_route with functional_widget (https://pub.dev/packages/functional_widget)?

I just started new project trying to use both auto_route and functional_widget, and the build_runner keeps complaining 
```
Route must have either a page or a redirect destination
```
for the widget generated by functional_widget.

It seems auto_route doesn't recognize `part` and `part of` of generated files by functional_widget, but I cannot find a fix for it.

Any help would be great.

Thank you.

**Comment by Milad-Akarie** [comment]
Hello @ktae13-npnf, the issue has nothing to do with file parts, it's just that functional_widget generate is ran after auto_route generator so when auto_route is tying to read the generated widget it's not even created yet. 
the fix is simple, we just force auto_route to run after any .g.dart files 
it will be included in the next build. 
Thanks for reporting.

**Comment by ktae13-npnf** [comment]
Thank you @Milad-Akarie. running functional_widget build after auto_route build were another theory of failure I had, but I didn't know how to test the order of build at the time. Thanks for taking a look and committing the fix.

**Comment by ktae13-npnf** [comment]
@Milad-Akarie, So I tried to use `dev` branch to test your fix, but I am still getting `Route must have either a page or a redirect destination` error. Did I miss anything? My override
```
auto_route:
    git:
      url: git://github.com/Milad-Akarie/auto_route_library.git
      ref: dev
      path: auto_route
```
and `pub get`
```
! auto_route 2.2.0 from git git://github.com/Milad-Akarie/auto_route_library.git at 5e6b29 in auto_route
```

**Comment by Milad-Akarie** [comment]
That code is in the auto_route_generator

**Comment by dt-chris** [comment]
i cloned the repo locally in order to try using the `dev` branch and am getting an error with build_runner.

```[INFO] Generating build script...
[INFO] Generating build script completed, took 637ms

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 17ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 199ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 88ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 705ms

[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 12ms

[INFO] Terminating. No further builds will be scheduled



You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Null check operator used on a null value
package:build_runner/src/generate/watch_impl.dart 189:40  WatchImpl.reader
package:build_runner/src/server/server.dart 50:55         createServeHandler.<fn>
package:build_runner/src/server/server.dart 49:20         createServeHandler.<fn>
```

it works fine if i have master checked out (behaves the same as when pointing at the remote package), but when i switch it to dev i get the above error. in my pubspec i have:
```
  auto_route:
    path: ../auto_route_library/auto_route
```
and
```
  auto_route_generator:
      path: ../auto_route_library/auto_route_generator
```
