### ISSUE TITLE
How to use auto route with changeNotifierProvider.value

### ISSUE THREAD

**Issue by alihabbash** [Milad-Akarie/auto_route_library#528]
I have created and linked the `AppRouter` to navigate between screen but then i need to pass the provider create in the `LoginScreen` to `RegisterScreen` and I can't figured out how
This is my code for the `AppRouter`:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: [
    AutoRoute(page: LoginScreen, initial: true),
    AutoRoute(page: HomeScreen),
    AutoRoute(page: NewMissionScreen),
    AutoRoute(page: RegisterScreen)
  ],
)
class $AppRouter {}
```
and I navigate to the register screen using this method

`_appRouter.push(RegisterRoute());`

**Comment by alihabbash** [comment]
Thank you so much, it works
I'm closing this issue now

**Comment by theweiweiway** [comment]
the widget parameter (which is `router` in this case) is the router - your main App Router. the router determines which routes are currently being shown
