### ISSUE TITLE
AutoRedirect widget

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#529]
React's routing packages usually have some sort of a `<Redirect />` component to redirect a user to another route when it gets rendered.

Could it be possible to have a `AutoRedirect` widget or something like that to redirect the user as soon as the widget gets rendered?

**Comment by dt-chris** [comment]
there is `RedirectRoute`, maybe that is what you're looking for? i dont think it renders anything though, just if you navigate to that path then it sends you elsewhere.

**Comment by theweiweiway** [comment]
Actually, super easy just to make your own widget by having an `initState` and redirecting when that widget is mounted
