### ISSUE TITLE
Question: best approach to protect screens behind auth

### ISSUE THREAD

**Issue by edwardaux** [Milad-Akarie/auto_route_library#53]
[This is more of a question than an issue]

Like a lot of apps, I've got a situation where a user can use a lot of the app without being logged in, but it gets to a point where they need to be logged in to continue to the next screen.

Imagine the user is on screen `/a` and tries to navigate to screen `/b`. If they're already logged in, pushing to `/b` should go straight there, otherwise, they get taken via `/login` which, after successful authentication, then sends them on to `b`.

I guess it is sort of like the concept of the route guard, but with a bit more logic that allows a passthrough transition.

Any thoughts on whether there's some existing behaviour in auto_route that might help achieve this? Or any other pointers/suggestions? Thanks.

**Comment by Milad-Akarie** [comment]
Hey @edwardaux You can go about achieving that using route guards. 
Here are two approaches you could use
1- Let your loginScreen route return true if users successfully login.
then inside of your AuthGuard check if user is already logged in, continue to route /b otherwise navigate to the login page, your login page should return true if the auth process is a success. 
```dart
class AuthGuard extends RouteGuard {
  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName,
      Object arguments) async {
    if (isLoggedin) {
      return true;
    }
    return await navigator.pushNamed<bool>(Routes.loginScreen);
  }
}

```
inside of your login page you can pop with a result using
```dart 
ExtendedNavigator.of(context).pop(true|false)
```
2- Pass your guarded route name and args to the loginScreen so you can later redirect to the desired destination in case of a successful login. 

```dart
class AuthGuard extends RouteGuard {
  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName,
      Object arguments) async {
    if (isLoggedin) {
      return true;
    }else{
     navigator.pushNamed<bool>(Routes.loginScreen, arguments:
        LoginScreenArguments(
           redirectRouteName: routeName,
           redirectRouteArgs : arguments),
        );
    return false;
  }
}
```
Then inside your loginScreen you can redirect users to any guarded route after a successful login process 
```dart 
ExtendedNavigator.of(context).pushNamed(redirectRouteName, arguments: redirectRouteArgs);
```
Let me know if you have more questions.

**Comment by edwardaux** [comment]
Ah, thank you so much. I didn't realise I could also change the destination of the route inside the guard... perfect 💯

**Comment by edwardaux** [comment]
In case anyone is playing along at home, I tried both approaches above. 

I initially used the second one because my LoginScreen already had some logic in to do the redirect. However, there are two downsides to this approach:

1. It relies on LoginScreen to call navigator.pushNamed() - which is problematic if the original caller wanted to use pushReplacementNamed() to transition
2. It pushes redirection logic and state into the LoginScreen

Going with the first option works better (in my opinion) because now the caller’s preference for pushing is maintained, and the redirection logic is purely contained in the guard.

Note that the last check in the guard needs to be null-aware (because the LoginScreen returns with a null if it was presented modally and dismissed with by tapping in the X button)

**Comment by rahulnakre** [comment]
`class AuthGuard extends RouteGuard {
  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName,
      Object arguments) async {
    if (isLoggedin) {
      return true;
    }
    return await navigator.pushNamed<bool>(Routes.loginScreen);
  }
}`

Where does `isLoggedIn` came from? How do I pass that variable from my widget to my `AuthGuard` ? Thanks!

**Comment by Milad-Akarie** [comment]
Hey, @rahulnakre well you could directly check your SharedPreferences for a token or if you're using an auth service or something you could inject it in the AuthGuard constructor

class AuthGuard extends RouteGuard {
  Future<bool> canNavigate(ExtendedNavigatorState navigator, String routeName,
      Object arguments) async {
    if (isLoggedin) {
      return true;
    }
    return await navigator.pushNamed<bool>(Routes.loginScreen);
  }
}

**Comment by rahulnakre** [comment]
Thanks for the help!

**Comment by akshaybhange** [comment]
how can I set a splash screen while I check for authentication in AuthGuard?
