### ISSUE TITLE
Page widget recreated on back navigation

### ISSUE THREAD

**Issue by vksee** [Milad-Akarie/auto_route_library#534]
Unexpected behavior after update from version ^1.0.2 to ^2.1.0.
On back navigation: page widget recreated (**constructor** called).

Problem also reproduced in [example](https://github.com/Milad-Akarie/auto_route_library/tree/master/auto_route/example).

Flutter (Channel stable, 2.0.6, on Linux)
• Flutter version 2.0.6 
• Framework revision 1d9032c7e1, 2021-04-29 17:37:58 -0700
• Engine revision 05e680e202
• Dart version 2.12.3

**Comment by Milad-Akarie** [comment]
@vksee That was actually an intended enhancement, pages need to update after App location changes. constructing widgets in flutter is very cheap.

**Comment by vksee** [comment]
There are "heavy" objects and actions that are constructed and executed at the time the modal Page is opened, and destroyed when the Page is closed (ex. Page Model). 

For example, use case: when open a Page with a list, the data from the cache is displayed first, then a request is sent to the server, then the list is updated.

In the first version, this was easy to implement, dependent objects were created when the Page was opened, and removed automatically (Riverpod).

In the new version, this simple life cycle has become invalid.
When exit the Page, it is also re-created (new object).
But Page Model may already be destroyed.

How can know that a Page has been opened and not re-created?

**Comment by Milad-Akarie** [comment]
@vksee are you working with stateless or stateful widgets?

**Comment by Milad-Akarie** [comment]
Models/cubits shouldn't be recreated on page rebuild

**Comment by vksee** [comment]
This is not an AutoRoute issue.



States via Riverpod.
App has Screens(Pages) that have Riverpod autoDisposed Screen Model and these screens work fine with the new AutoRoute v2.

Riverpod handles re-creation of Screens and Widgets correctly.
Except for one case in my application.
