### ISSUE TITLE
pop() method with query parameters

### ISSUE THREAD

**Issue by AcodeWang** [Milad-Akarie/auto_route_library#536]
I found that if I call the router.pop() there is no more query param memorised for the stack.

For example :
From `/home?queryHome='home'` if I call router.navigate() to `/book?queryBook='book'`, then I tried to call router.pop() at book page,  I got url `'/home?queryBook='book'`.

I thought the desired result should be `/home?queryHome='home'` which is already in the route stack.

Am I wrong about the understanding of queryParam ? How could I get the desired reslut ?

**Comment by Milad-Akarie** [comment]
@AcodeWang hmmmm yes I guess that makes sense, the current setup updates all queryParams according to the top route's queryParams. I'll see what I can do about it.

**Comment by markbulingit** [comment]
Here's the sample of the bug
![queryparam pop issue](https://user-images.githubusercontent.com/91706339/140605348-302c7c2f-1fdb-446b-9004-e0ae192ee08b.gif)

**Comment by nishit-dixit** [comment]
facing the same issue on version 3.2.4. did anyone find the solution to this?

**Comment by jturak-rbi** [comment]
Still facing issues with this, any updates? Is there anything that can be done to fix this?

**Comment by jordanadamstn** [comment]
+1 any update to fix this?

**Comment by Milad-Akarie** [comment]
@jordanadamstn you should use navigateBack for web Apps ...navigate back calls history.back() this will also guarantee you won't have extra entries in your browser history
