### ISSUE TITLE
AuthGuard for token expiration DIO

### ISSUE THREAD

**Issue by herman-the-worm** [Milad-Akarie/auto_route_library#538]
Hello,

I clearly understand how AuthGuard works when the users loads their page initially and it either let's you in to the main route of the app, or will keep you in whitelisted authenticated routes like Registration or Login.

What would be the easiest way to "reset" the user to the beginning state when they are no longer authenticated and pop the pages up until SignIn Route?

I have tried many different solutions but none of them work well.

The setup is BLoC, AuthGuard, Signing Page and HomeRoute page (tabs router).

Latest version of auto_route

Thanks

**Comment by Milad-Akarie** [comment]
Easiest way replaceAll([SigninRoute()])

**Comment by herman-the-worm** [comment]
@Milad-Akarie I will try this

Thanks

**Comment by herman-the-worm** [comment]
@Milad-Akarie one other trouble is I have with this library is that I am not able to push the users navigator to the initial state (SignInRoute) if the JWT token is expired. Since JWT expiration error is caught in the Provider layer, DIO client.

Is there any method or way that I can trigger the 401 auth error to change navigation?

**Comment by Milad-Akarie** [comment]
@herman-the-worm  one way to do it is to inject the root router into your Dio interceptor, or use an evenBus to notify your app widget that user is logged out and then change router state from there.

**Comment by herman-the-worm** [comment]
I will try this @Milad-Akarie
