### ISSUE TITLE
Flutter Web - appropriate page stack after URL refresh

### ISSUE THREAD

**Issue by kamilraczka** [Milad-Akarie/auto_route_library#540]
Hi,

Firstly, I would classify this post as a question, not a bug (I guess 😅 ).
I'm fighting with a quite common scenario related to Web apps - maybe the solution is straightforward but I can't find it neither on pub doc nor autoroute.vercel.app.

**Little bit of context:**
I got a MainPage in my app (responsible for showing drawer, page content with the help of AutoRouter() ofc), DevicesPage (module chose from drawer) with list of some items and DevicesDetailsPage which is being shown after a click on item from DevicesPage. 
Basically, stack looks like this: MainPage -> DevicesWrapperPage -> DevicesPage -> DevicesDetailsPage and its url is: localHost:0000/#/devices/{deviceId}. Devices module is rendered under DevicesWrapperPage with again, AutoRouter().
Normally during app's exploration everything works as intended. The problem starts when I'm on localHost:0000/#/devices/{deviceId} url and I hit a browser's refresh button or "reenter" my url in browser's url bar - then my apps is being rebuild of course but with page stack MainPage -> DevicesWrapperPage -> DevicesDetailsPage which makes impossible to get back from DevicesDetailsPage to DevicesPage by context.router.pop() because there's no DevicesPage in stack.

**My question:** 
Is there a way to ensure/force creating List page before creation of Details page with such "dynamic loading"? I've seen a Route guard in docs but I wonder if there's other solution.

I'm posting my router declaration below:

```
@AdaptiveAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      page: MainPage,
      initial: true,
      children: [
        AutoRoute(
          initial: true,
          path: 'overview',
          page: OverviewPage,
        ),
        AutoRoute(
          path: 'devices',
          page: DevicesWrapperPage,
          children: [
            AutoRoute(path: '', page: DevicesPage, initial: true),
            AutoRoute(path: ':deviceId', page: DevicesDetailsPage),
            RedirectRoute(path: "*", redirectTo: ''),
          ],
        ),
        AutoRoute(path: 'analytics', page: AnalyticsPage),
        AutoRoute(path: 'gallery', page: GalleryPage),
        AutoRoute(path: 'settings', page: SettingsPage),
      ],
    ),
  ],
)
```

**Comment by Milad-Akarie** [comment]
Hello @kamilraczka, first of all you need to understand that when you hit the refresh button flutter rebuilds everything from scratch even the main function is recalled, so what actually happens is that your App is being rebuilt with the url in the browser as the initial location (no state is restored), so there isn't much we can do here. 

now if you don't have a more complicated scenario than the  scenario above auto_route has a little feature that can help you. 
to simplify things let's say we have two routes at the same level

```
/devices
/devices/:id
```
by default if you navigate to `/devices/1` the matcher will return the second route with the full match (/devices/:id) but if you set this simple flag `includePrefixMatches` to true inside of the `DefaultRouteParser` prefix matches will be included. 
now if we again navigate `/devices/1` `/devices` will be matched as a prefix and `/devices/:id` will matched as a full match and the two routes will be pushed to the stack.

```dart
   MaterialApp.router(
      routerDelegate: AutoRouterDelegate(
        _rootRouter,
      ),
      routeInformationParser: _rootRouter.defaultRouteParser(
        includePrefixMatches: true, // set this to true
      ),
```

alternatively you could use declarative routing and shape the stack how ever you want. 


```dart
class _DevicesWrapperPageState extends State<DevicesWrapperPage> {
  String? _deviceId;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AutoRouter.declarative(
        // called whenever  navigation happens
          onNavigate: (matches, initial) {
          // here we get a list of matches instead of just one match
         // because as I said auto_route supports prefix matching. 
         // the last match will always be the one with full match. 
            if (matches.isNotEmpty){
	       if(matches.last.routeName == DevicesDetailsRoute.name) {
            _deviceId = matches.last.pathParams.getString('deviceId');
            }
            if (!initial) {
              setState(() {});
            }
          },
          routes: (_) => [
               // always include the devices list page
                DevicesRoute(),
                if (_deviceId != null) DevicesDetailsRoute(deviceId: _deviceId)
              ],
          onPopRoute: (route, _) {
            if(route.name == UserPostsRoute.name){
               _deviceId = null;
            }
          }
          ),
    );
  }
```

**Comment by kamilraczka** [comment]
@Milad-Akarie thank you for clarification. 💯 
In any complicated case I'm going to use declarative routing. However, for my current simple scenario "includePrefixMatches" does the job!

Many thanks! 👍

**Comment by AscentionOne** [comment]
@kamilraczka @Milad-Akarie Hi, I have a similar question, but I am passing the data as parameters from for example `BooksPage` to `BookDetailsPage ` along with id. 

Here are my two page.
 ```dart
/books
/books/:id
```

Now after I refresh the page when I am on the device detail page. Which as Milad mentioned the data will be lost and indeed I get an error of "the data passed into the detail page cannot be null". 

How can I re-fetch the data from API and pass it into the page after I refresh on the `books/1` page? I also have an API for individual data with id.

I have two kinds of API. One is for getting a list of books and one is getting the individual book information from `id`.
```dart
/books
/books/id
```

I am quite new to flutter web applications and want to know how did the web work after being refreshed in detail page. It seems like they will re-fetch the data from API.

Thanks!

**Comment by Milad-Akarie** [comment]
Hey @AscentionOne I'm not sure I understand the issue, 
if as I'm assuming you're fetching your data inside of initState or didChangesDeps then you don't actually have to do anything, the data should be fetched the same way it would if you're navigating to details page.

**Comment by AscentionOne** [comment]
@Milad-Akarie Sorry for not describing the question well enough. I have list of books data. Let's say 4 books. I will fetch the data in books overview page (the api will give me a list of books data) and then passing the 4 books data to the list view builder and also to the book detail page route as parameter. So there will be 4 book list view in the book overview page. After I click the book list it will navigate to (books/1) book detail page. 

When I refresh the page in book detail page. Since I am passing the book data from the book overview page through routing. Since it's not fetched yet. So the auto rout will show the parameter passed in (book data) is null. Which make sense, because I am in the book detail page not in the overview page. I don't re-fetch data in the book detail page.

Since you mention fetching data in the init state. Does it mean I have to fetch each of the book detail from API that return individual book data? Or is there a way that I can fetch all the book data and pass it in the detail page?

I have two api one is for fetching all the books and one is for fetching individual book data through id.

Thank you!
