### ISSUE TITLE
current page rebuild every route

### ISSUE THREAD

**Issue by yarmat** [Milad-Akarie/auto_route_library#541]
When I navigate another page, the current one is rebuilt and then another one opens. Why does it happen?  On version 2.0.0 this did not happen

**Comment by Milad-Akarie** [comment]
@yarmat it's an intended behavior, some pages depend on info from path/query parameters and need to rebuild whenever they're changed, rebuilding widgets in a flutter is a very cheap procedure and  not a big deal, it could happen tens of it times in animation for example. 
if you have to initiate something or have a one time process ( http call for example) you should always do it inside of init state or did change deps if you need to access context.

**Comment by yarmat** [comment]
@Milad-Akarie thanks for clarification
