### ISSUE TITLE
Add pathName as a static variable to the generated Route classes

### ISSUE THREAD

**Issue by harsh2338** [Milad-Akarie/auto_route_library#542]
When we use pushNamed() we need to pass the path as a parameter. Adding pathName as a static variable to the Route class which is generated using auto_route_generator will be useful so that the paths can be accessed without hardcoding the string

current generated class:
`class RouteA extends _i1.PageRouteInfo {`
`     const RouteA() : super(name, path: '/page_a');`
`     static const String name = 'RouteA';`
`}`

current usage:
`context.router.pushNamed('/page_a');`

to 

modified generated class:
`class RouteA extends _i1.PageRouteInfo {`
`     const RouteA() : super(name, path: '/page_a');`
`     static const String pathName='/page_a';`
`     static const String name = 'RouteA';`
`}`

modified usage:
`context.router.pushNamed(RouteA.pathName);`

**Comment by Milad-Akarie** [comment]
Why not push route instead of path? What if the path has dynamic segments? /path/:id

**Comment by harsh2338** [comment]
@Milad-Akarie 
In that case, can the dynamic segment be derived by the arguments passed.

**Comment by Milad-Akarie** [comment]
@harsh2338 that's why we're using an object instead, if your route doesn't need an arguments you could pass your route as a const object if you're worried about performance. 
`router.push(const MyRoute());`

**Comment by harsh2338** [comment]
@Milad-Akarie I understood now. Ya i was worried about the performance. Thanks a lot!!!
