### ISSUE TITLE
Ability to have a different route based on platform

### ISSUE THREAD

**Issue by rmargolinross** [Milad-Akarie/auto_route_library#543]
I love the app but I am trying to get a CustomRoute to have the swipe to navigate back feature on ios only. I am using the CustomRoute because I want to use a fadeIn transition. I would like to either have the option to use a CupertinoRoute on ios (which I cant because the routes ore defined in a const annotation), or have the CustomRoute have the option to allow the swipe back gesture for ios.

Im at an impasse here, because my only real solution right now is to handle these pages individually and not really use Auto Route

**Comment by Milad-Akarie** [comment]
@rmargolinross I think using a custom route builder can help you achieve what you need. 
this's from the unpublished docs i'm still working on 
https://github.com/Milad-Akarie/auto_route_library/blob/dev/README.md#custom-route-builder

**Comment by rmargolinross** [comment]
Hmm this might actually work. I will try it out and give you feedback.

**Comment by rmargolinross** [comment]
That worked great thanks for the help!
