### ISSUE TITLE
hot reload doesn't work.

### ISSUE THREAD

**Issue by stha-ums** [Milad-Akarie/auto_route_library#544]
when I hot reload the screen returns blank. What am I doing wrong?

this is how I am using auto_route.

  @MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomePage, initial: true),
    AutoRoute(page: ThemeChangeDropDownWidget),
  ],
)
class $AppRouter {}

...

  final _appRouter = AppRouter()

            return MaterialApp.router(
              localizationsDelegates: [
                AppLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              supportedLocales: [
                const Locale('en', 'US'), 
                const Locale('ne', 'NP'),
              ],
              locale: localeState.locale,
              themeMode: themeState,
              darkTheme: DarkTheme()(),
              theme: LightTheme()(),
              title: "App",
              routerDelegate: _appRouter.delegate(),
              routeInformationParser: _appRouter.defaultRouteParser(),
              debugShowCheckedModeBanner: false,
            );

**Comment by theweiweiway** [comment]
Is your final _appRouter = AppRouter() 
In the build method?

If it is, it needs to go outside of the build method

**Comment by Sameerkash** [comment]
@theweiweiway my `final _appRouter = AppRouter()` is outside the build method and I can confirm this issue. The screen becomes blank after hot reoload.

**Comment by stha-ums** [comment]
> Is your final _appRouter = AppRouter()
> In the build method?
> 
> If it is, it needs to go outside of the build method

thank you this seems to work for me

**Comment by mregandla** [comment]
> @theweiweiway my `final _appRouter = AppRouter()` is outside the build method and I can confirm this issue. The screen becomes blank after hot reoload.
> 
> Moving it outside a class and making it global to the scope of the file seems to fix this issue.

AppRouter() object WAS outside built method and inside Class. Moving this object outside the class and making it global, fixed the issue for me.
