### ISSUE TITLE
Accessing the navigator stack

### ISSUE THREAD

**Issue by matthewfx** [Milad-Akarie/auto_route_library#55]
Your library generates classes encapsulating arguments for a page which is great. My question is how could I access a stack so that when I do ```pop``` I can get what arguments have been passed to a previous page. In my case, all pages are of the same type and the only difference is something like a view model which one of argument injected into them.

**Comment by Milad-Akarie** [comment]
ExtendedNavigator is just an extension to the native Navigator and as far as I know it doesn't expose a public stack so that would be a little hard to pull.
but let me get this straight.. you need to access the args of  /b when you pop to /a?

**Comment by matthewfx** [comment]
It's a nested navigator and the context in which it is nested needs to be updated based on what page it displays. Anyways I just thought it would be possible but if not I will implement a stack data structure and add it to my bloc. Thanks! Could you please look at my previous question re passing parameters to the initial route?

**Comment by Milad-Akarie** [comment]
@matthewfx I'm still not sure what you're trying achieve but I think using a NavigatorObserver can help

```dart
class MyObserver extends NavigatorObserver {
  @override
  void didPush(Route route, Route previousRoute) {
    super.didPush(route, previousRoute);
     
    print(route.settings.arguments);
    print(previousRoute.settings.arguments);
  }
}
```
You could even create your own stack and add/remove routes using didPush/didPop callbacks

**Comment by Milad-Akarie** [comment]
@matthewfx Regarding initial route args, that's a missing feature and I will be working on that.

**Comment by matthewfx** [comment]
OK, that might be helpful! Sorry for bothering you. My day job is an iOS developer. Flutter is my hobby but I need to build a pro bono app quickly in it (covid-19 related) related and don't have time to study docs properly... :( Thank you very much!
