### ISSUE TITLE
Issues with AutoTabsScaffold

### ISSUE THREAD

**Issue by akashvibhute** [Milad-Akarie/auto_route_library#554]
1. The routes list doesn't update at runtime when the widget rebuilds.
I have 4 routes in total 2 of which are dependent on whether the user is logged in or not. 

I have used the autotabsscaffold for syncing those with bottom navigation bar which also has 4 buttons with 2 having their visibility dependent on logged in status.

When I login or logout, the bottom navigation bar updates but the route associated with the now hidden button stays associated with the new button unless I reload the app. 

Below is my implementation - 
```dart
Widget build(BuildContext context) {
    
    final isLoggedIn = useProvider(isLoggedInProvider);
    final baseRoutes = [
          HomeRouter(),
          DataRouter(),
        ];
    final loggedInRoutes = baseRoutes + [
      UserRouter(),
    ];
    final loggedOutRoutes = baseRoutes + [
      AuthRouter(),
    ];
    return AutoTabsScaffold(
        routes: isLoggedIn ? loggedInRoutes : loggedOutRoutes,
        bottomNavigationBuilder: (_, tabsRouter) {
          return  BottomNavigationBar(
              backgroundColor: Theme.of(context).backgroundColor,
              currentIndex: tabsRouter.activeIndex,
              onTap: tabsRouter.setActiveIndex,
              items: [
                BottomNavigationBarItem(
                  label: 'Home',
                  icon: Icon(Icons.home),
                ),
                BottomNavigationBarItem(
                  label: 'Data',
                  icon: Icon(Icons.group_rounded),
                ),
                if (!isLoggedIn)
                  BottomNavigationBarItem(
                    label: 'Login',
                    icon: Icon(Icons.account_box),
                  ),
                if (isLoggedIn)
                  BottomNavigationBarItem(
                    icon: Icon(Icons.person),
                    label: 'Account',
                  ),
              ],
            ),
    );
}
```

All 4 routes are children of the root "/" route and above code is the build method of the root page. I'm not entirely sure what I have missed from the documentation [here](https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing).

2. All pages rebuild on switching between tabs. When switching between pages from the bottom navigation bar, all 3 of the above pages get rebuild. I don't think home page or login page needs rebuilding when I'm switching from home page to data page or navigating to a child route with the data page and there is no change on the other pages.

**Comment by ozz-rjq** [comment]
having a similar issue

**Comment by AymBch** [comment]
having the same problem too, when click on the button it doesn't navigate until I hot reload the app or press the back button.
