### ISSUE TITLE
A little sluggish compared to native flutter Navigator

### ISSUE THREAD

**Issue by ericel** [Milad-Akarie/auto_route_library#556]
I am not sure if this is just for me, or my particular setup is what causes it.
But I see a little hesitation(sluggishness) in navigation using auto-route.

Auto-route is injected using get_it.

https://user-images.githubusercontent.com/16863721/118993299-5c664e00-b9c0-11eb-894f-14abbbe2af51.mp4

The first(group chat link) in the video uses flutter material Navigator.push(context,PageRouteBuilder(....

While the slow, second(single chat link) uses the auto route. As you see from the video above it takes time for the auto route to navigate to the chat room.
` context.router.push(ChatsRouter(children: [ChatRoute(chatroomid:widget.contactsList[index].chatroomid! , chatter: chatter)]))`

And here is my routes script:
```
const chatroutes = AutoRoute(
  path: "/chats",
  name: "ChatsRouter",
  page: EmptyRouterScreen,
   guards: [AuthGuard],
  children: [
    AutoRoute(path: '', page: AppChatsScreen),
    AutoRoute(path: 'chatroom/single/:chatroomid/:chatter/:extras', page: ChatScreen),
    RedirectRoute(path: '*', redirectTo: ''),
  ],
);
```
My question, how do I fix this lagging?

**Comment by jlnrrg** [comment]
Please check the performance tab in the devtools. There you can see which widget needs the most time.
It looks to me as if your build depends on data loaded and this slows down the app.

**Comment by ericel** [comment]
@jlnrrg Not it doesn't depend on the data loaded. With the Navigator.push.... it's just okay.

**Comment by jlnrrg** [comment]
It might be that you are using the `AutoTabsScaffold` and every page in your buttomnavigation is rebuild on a `AutoRouter.push` action

**Comment by Ali-Almezead** [comment]
I am facing this problem , how to fix it please
