### ISSUE TITLE
auto_route doesn't work with state restoration

### ISSUE THREAD

**Issue by TammiLion** [Milad-Akarie/auto_route_library#557]
Please see sample project: https://github.com/TammiLion/State-Restoration-Sample-Auto-Route

It seems either I misunderstand how to configure State Restoration in auto_route or there is a bug with auto_route that causes State Restoration using RestorationMixin and RestorationScopeId not to work.

Testing on an Android Emulator with the setting 'Do not keep Activities', pressing the counter a few times, going to background and re-opening the app again:

1 A simple MaterialApp with a home: -> preserves the state of the counter 
2 A MaterialApp using a Declarative Navigator from Navigation 2.0 -> preserves the state of the counter 
3 A MaterialApp.router using a Router from auto_route -> does not preserve the state of the counter

Question: Is this a bug with auto_route or is there a way to configure auto_route to work with restorationScopeId?

**Comment by Milad-Akarie** [comment]
@TammiLion before I clone and test your snippet please remove the route initiating from the build method and let me know if you still have the issue. 

```dart
class _MyAppState extends State<MyApp> {
// initiate your router here
final _router = AppRouter();
  @override
  Widget build(BuildContext context) {
// remove this    
// final _router = AppRouter();
....
}
```

**Comment by TammiLion** [comment]
Hey, thanks for commenting. I did and comitted what you said. 
Good news: no blank screen after restarting from background.
Bad news: doesn't restore the counter state.
I will change the title and description to remove the stuff about onDispose.

**Comment by Milad-Akarie** [comment]
@TammiLion  turns out we need to pass a restoration id to restorable pages, I'll include it in the next build.

**Comment by TammiLion** [comment]
Awesome, thanks for your time and effort!

**Comment by nguyenhoanglam** [comment]
I faced `Multiple owners claimed child RestorationBuckets with the same IDs.` error after push to another stack route in Android.  However, it's works in iOS.

**Comment by kirya355** [comment]
> @TammiLion turns out we need to pass a restoration id to restorable pages, I'll include it in the next build.

Still not included?

**Comment by MartiSilvio** [comment]
> @TammiLion turns out we need to pass a restoration id to restorable pages, I'll include it in the next build.

@Milad-Akarie  Have you included this yet?

**Comment by fnicastri** [comment]
> I faced `Multiple owners claimed child RestorationBuckets with the same IDs.` error after push to another stack route in Android. However, it's works in iOS.

@nguyenhoanglam  facing the same issue, did you find a solution?
