### ISSUE TITLE
How to use Authentication in a page but not in root route?

### ISSUE THREAD

**Issue by 2shrestha22** [Milad-Akarie/auto_route_library#558]
I read the tutorial where it is said that "`Authentication` is a staple of many apps, requiring users create an account and sign in before accessing `specific pages`." In example `Authentication` is used in root of the route. Using code from example does not respect root route and initial route is what is declared in `routes` list. How to use `authentication` before accessing other page than initial route?
```
routerDelegate: AutoRouterDelegate.declarative(   
                _appRouter,
                routes: (_) => [
                  // if the user is logged in, they may proceed to the main App
                  if (authService().isLoggedIn)
                    HomeRoute()
                  // if they are not logged in, bring them to the Login page 
                  else
                    LoginWrapperRoute(onLogin: () => authService().logIn),
                ],
            ),
```

**Comment by Milad-Akarie** [comment]
@2shrestha22 if your App has public pages and you only need to protect SOME pages you should use an `AutoRouteGuard` instead. https://github.com/Milad-Akarie/auto_route_library/tree/dev#route-guards

**Comment by 2shrestha22** [comment]
> @2shrestha22 if your App has public pages and you only need to protect SOME pages you should use an `AutoRouteGuard` instead. https://github.com/Milad-Akarie/auto_route_library/tree/dev#route-guards

Thank you. I was using AuthGuard before but after reading new documentation I thought Authentication can be used in pages also. I think that part of documentation is bit confusing. Thank you for giving time to reply and awesome library.

**Comment by Milad-Akarie** [comment]
@2shrestha22 My apologies, I can't find the time to provide proper docs but we're almost there.

**Comment by 2shrestha22** [comment]
You don't need to apologize. And you can close this issue.

**Comment by michasng** [comment]
@Milad-Akarie How do I access the `context` within `onNavigation()` in the `AutoAuthGuard`?
It just says `if(authenitcated)` in the docs, but I need to access a provider to figure out the value of `authenticated`.

**Comment by wizawuza** [comment]
@michasng 
[Check it](https://github.com/Milad-Akarie/auto_route_library/issues/290#issuecomment-749110594)
