### ISSUE TITLE
Wrapping Routes not working

### ISSUE THREAD

**Issue by steve-cahn** [Milad-Akarie/auto_route_library#561]
I'm trying to wrap a route so that I have the following outcome:

<img width="359" alt="Screenshot at May 23 18-52-19" src="https://user-images.githubusercontent.com/44787181/119285933-0f6cbc80-bbf8-11eb-8cf7-da127808abe2.png">

But It doesn't seem to work... Here's my code:
```dart
const coolTab = AutoRoute(
  path: '',
  name: 'MyTab',
  page: EmptyRouterPage,
  children: [
    AutoRoute(
        path: 'myPath',
        page: MyPage,
        initial: true,
        children: [AutoRoute(path: '', page: NestedRoute, initial: true)]),
  ],
);

return AutoRouter(builder: (context, content) {
      return Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          _TopSectionBuilder(),
          Expanded(
            child: Stack(
              children: [
                MyFirstWidget(),
                MySecondWidget(),
              ],
            ),
          ),
          content,
        ],
      );
    });
```

Here's the error I'm getting:
> RenderBox was not laid out: RenderFlex#bd7cd relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE 'package:flutter/src/rendering/box.dart':  Failed assertion: line 1940 pos 12: 'hasSize'

**Comment by steve-cahn** [comment]
Anyone?

**Comment by ayushin** [comment]
I'm hitting the same issue, just by putting AutoRouter inside a Column when the route widget is just a Text()

Wrapping it with Container with fixed height fixes the problem. 

flutter: >>> 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 720 pos 12: 'constraints.biggest.isFinite': is not true., #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)


flutter: >>> BoxConstraints forces an infinite height.
flutter: These invalid constraints were provided to RenderIgnorePointer's layout() function by the following function, which probably computed the invalid constraints in question:
flutter:   _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
flutter: The offending constraints were:
flutter:   BoxConstraints(w=366.0, h=Infinity), #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)

and finally

flutter: >>> 'package:flutter/src/rendering/box.dart': Failed assertion: line 1930 pos 12: 'hasSize': RenderBox was not laid out: _RenderTheatre#a74b3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE, #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
flutter: #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)

**Comment by OscarHenry** [comment]
I am having the same problem, and it is necessary for my ui to nest the router in a column, and that the content behavior is flexible, any solution here?

**Comment by martinralfreindl** [comment]
Running into the same problem. Any solutions?
