### ISSUE TITLE
Add args in PageRouteInfo to the equal and hashCode

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/auto_route_library#565]
I propose to add `args` to the `equal` and `hashCode` functions.
Without that functionality, two routes with different params will still be equal, which is not true and wrong.

**Comment by pro100svitlo** [comment]
Is this package alive?

**Comment by pro100svitlo** [comment]
@Milad-Akarie is this package still supported?

**Comment by Milad-Akarie** [comment]
Yes, but unfortunately I've been super busy for a while now.
I'm planning on spending some time maintaining it starting this week
