### ISSUE TITLE
Library started ignoring default values for non nullable types, causing the generated code to be invalid.

### ISSUE THREAD

**Issue by NamanShergill** [Milad-Akarie/auto_route_library#569]
![image](https://user-images.githubusercontent.com/33877135/120061678-f347a000-c07b-11eb-9bba-eaedb8f44bca.png)
Here, the initialIndex is a non nullable value.

Not sure what started causing this. I have been on the latest version since it came out.

**Comment by rmargolinross** [comment]
Possible dupe of #404

**Comment by NamanShergill** [comment]
> > Okay, I think I found a clue as to the issue. I was able to get my build working by overriding the dependency for analyzer to version 1.5.0. build_runner references analyzer ^1.4.0 and it was updated to 1.7.1 a few days ago.
> 
> Again, so for a temporary work around add in your pubspec.yaml
> 
> ```
> dependency_overrides:
>   analyzer: 1.5.0
> ```

Posting the workaround by @rmargolinross here in case someone stumbles upon this looking for a solution.
