### ISSUE TITLE
Pushnamed with dynamic path argument

### ISSUE THREAD

**Issue by RicardoRB** [Milad-Akarie/auto_route_library#574]
Basically, I have this route:

```dart
/supermarkets/:supermarketId/search?query="banana"
```

And I want to do like this:

```dart
AutoRouter.of(context).pushNamed('/supermarkets/${widget.supermarketId}/search?query="banana"');
```

But I get this:

```dart
Failed to parse [String] supermarketId value from null
```

Am I doing something wrong?

**Comment by RicardoRB** [comment]
I'll answer myself:

The problem was that SearchPage(@pathparam("supermarketId") requrired this.supermarketId) was a child of a SupermarketPage(@pathparam("supermarketId") requrired this.supermarketId), so it won't take the dynamic value since it is just in SupermarketPage.

**Comment by RicardoRB** [comment]
Ok... Unfortunately, I'm not able to make it work as I want since the page is in the bottom bar.

And it makes to throw the exception since the library doesn't take both path params that I do need....

@Milad-Akarie Can you please help?

**Comment by Milad-Akarie** [comment]
@RicardoRB you need @pathParam to read path params from parent paths right? I've tried implementing that but got stopped by something, don't recall what it was right now.
until I give it another shot you can read parent's path info manually using `context.routeData.parent.pathParams` or `context.router.routeData`

**Comment by RicardoRB** [comment]
Thanks, @Milad-Akarie !
