### ISSUE TITLE
Pressing back button pop nested navigator

### ISSUE THREAD

**Issue by Thioby** [Milad-Akarie/auto_route_library#58]
Hi,

Pressing system back button inside nested navigator cause navigate to main navigator instead of  returning ot prevoius page in nested navigator. 

**Main Navigator -> Main Page -> Nested Navigator -> Page A -> Page B**

Pressing back button on Page B should return to Page A

**Comment by Milad-Akarie** [comment]
Hey, @Thioby 
Fixed in 
auto_route 0.4.4
auto_route_generator 0.4.4
Thanks for reporting.

**Comment by Thioby** [comment]
@Milad-Akarie 
Thank you! 👍
