### ISSUE TITLE
The Nested Route disappears when switching between responsive layout (desktop to mobile) in AutoTabsScaffold.

### ISSUE THREAD

**Issue by ricksondpenha** [Milad-Akarie/auto_route_library#589]
Hi, I've made a repo to reproduce this issue here: [auto_route_bug](https://github.com/ricksondpenha/auto_route_bug)

Here's the video of this issue:

https://user-images.githubusercontent.com/13574945/122421648-2493fb80-cfaa-11eb-85af-4ada74415ffc.mp4

So basically I've used your bottom navigation bar example from docs to build a sidebar, but sidebar builds only if its in desktop mode, when switched to mobile resolution a drawer is used instead. but when I'm inside a deep nested route, ie: /orders/active only /orders route is shown. Looks like the route gets stuck at EmptyPageRouter, but if i switch back to another deep nested route and resize my app window, the nested route which was previously not shown is rendered.

 Here's my AutoRouter code:
```
@CustomAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      name: 'HomeRoute',
      initial: true,
      page: Home,
      children: [
        RedirectRoute(path: '', redirectTo: 'dashboard'),
        AutoRoute(path: 'dashboard', name: 'DashboardRoute', page: Dashboard),
        AutoRoute(
          path: 'catalog',
          page: EmptyRouterPage,
          name: 'CatalogRoute',
          children: [
            RedirectRoute(path: '*', redirectTo: 'products'),
            AutoRoute(
              path: 'products',
              name: "ProductsRoute",
              page: Products,
            ),
            AutoRoute(
              path: 'category',
              name: "CategoryRoute",
              page: Category,
            ),
          ],
        ),
        AutoRoute(
          path: 'orders',
          page: EmptyRouterPage,
          name: 'ordersRoute',
          children: [
            RedirectRoute(path: '*', redirectTo: 'active'),
            AutoRoute(
              path: 'active',
              name: "ActiveOrdersRoute",
              page: ActiveOrders,
            ),
            AutoRoute(
              path: 'pending',
              name: "PendingOrderRoute",
              page: PendingOrders,
            ),
          ],
        ),
      ],
    ),
  ],
)
class $AppRouter {}
```

Here's my AutoTabsScaffold code:
```
      routes: [
        DashboardRoute(),
        CatalogRoute(),
        OrdersRoute(),
      ],
      drawer: Responsive.isMobile(context) ? SideBar() : null,
      builder: (context, child, animation) {
        return Responsive.isMobile(context)
            ? Scaffold(
                drawer: SideBar(),
                appBar: AppBar(
                  title: Text(context.topRoute.path),
                  actions: [],
                ),
                body: child,
              )
            : Row(children: [
                SideBar(),
                Expanded(
                  flex: 4,
                  child: Scaffold(
                    appBar: AppBar(
                      title: !Responsive.isMobile(context)
                          ? Text(context.topRoute.path)
                          : null,
                      centerTitle: false,
                      actions: [],
                    ),
                    body: child,
                  ),
                ),
              ]);
      },
    );
```

I'm using the below code to navigate to the deep nested route.
`
context.navigateTo( CatalogRoute(children: [ ProductsRoute() ] ));
`

**Comment by mghase** [comment]
i have the same problem

**Comment by ricksondpenha** [comment]
@Milad-Akarie any solutions for this? Am i missing something here?

**Comment by mghase** [comment]
> Hi, I've made a repo to reproduce this issue here: [auto_route_bug](https://github.com/ricksondpenha/auto_route_bug)
> 
> Here's the video of this issue:
> 
>  auto_route_bug.mp4 
> So basically I've used your bottom navigation bar example from docs to build a sidebar, but sidebar builds only if its in desktop mode, when switched to mobile resolution a drawer is used instead. but when I'm inside a deep nested route, ie: /orders/active only /orders route is shown. Looks like the route gets stuck at EmptyPageRouter, but if i switch back to another deep nested route and resize my app window, the nested route which was previously not shown is rendered.
> 
> Here's my AutoRouter code:
> 
> ```
> @CustomAutoRouter(
>   replaceInRouteName: 'Page,Route',
>   routes: <AutoRoute>[
>     AutoRoute(
>       path: '/',
>       name: 'HomeRoute',
>       initial: true,
>       page: Home,
>       children: [
>         RedirectRoute(path: '', redirectTo: 'dashboard'),
>         AutoRoute(path: 'dashboard', name: 'DashboardRoute', page: Dashboard),
>         AutoRoute(
>           path: 'catalog',
>           page: EmptyRouterPage,
>           name: 'CatalogRoute',
>           children: [
>             RedirectRoute(path: '*', redirectTo: 'products'),
>             AutoRoute(
>               path: 'products',
>               name: "ProductsRoute",
>               page: Products,
>             ),
>             AutoRoute(
>               path: 'category',
>               name: "CategoryRoute",
>               page: Category,
>             ),
>           ],
>         ),
>         AutoRoute(
>           path: 'orders',
>           page: EmptyRouterPage,
>           name: 'ordersRoute',
>           children: [
>             RedirectRoute(path: '*', redirectTo: 'active'),
>             AutoRoute(
>               path: 'active',
>               name: "ActiveOrdersRoute",
>               page: ActiveOrders,
>             ),
>             AutoRoute(
>               path: 'pending',
>               name: "PendingOrderRoute",
>               page: PendingOrders,
>             ),
>           ],
>         ),
>       ],
>     ),
>   ],
> )
> class $AppRouter {}
> ```
> 
> Here's my AutoTabsScaffold code:
> 
> ```
>       routes: [
>         DashboardRoute(),
>         CatalogRoute(),
>         OrdersRoute(),
>       ],
>       drawer: Responsive.isMobile(context) ? SideBar() : null,
>       builder: (context, child, animation) {
>         return Responsive.isMobile(context)
>             ? Scaffold(
>                 drawer: SideBar(),
>                 appBar: AppBar(
>                   title: Text(context.topRoute.path),
>                   actions: [],
>                 ),
>                 body: child,
>               )
>             : Row(children: [
>                 SideBar(),
>                 Expanded(
>                   flex: 4,
>                   child: Scaffold(
>                     appBar: AppBar(
>                       title: !Responsive.isMobile(context)
>                           ? Text(context.topRoute.path)
>                           : null,
>                       centerTitle: false,
>                       actions: [],
>                     ),
>                     body: child,
>                   ),
>                 ),
>               ]);
>       },
>     );
> ```
> 
> I'm using the below code to navigate to the deep nested route.
> `context.navigateTo( CatalogRoute(children: [ ProductsRoute() ] ));`

any solution plz

**Comment by fabirt** [comment]
Same problem here. I'm using Flutter web.

**Comment by AscentionOne** [comment]
I have the same issue here. I am using Flutter web.

**Comment by ArneSaknussemm89** [comment]
Running into the same thing on mobile too. Very frustrating, even moving the "responsive" stuff out of the AutoTabsScaffold and into the screen itself produces almost the same result - blank white screen.

DevTools inspector shows the AutoRouter widget, but it has no children. Hot Restart app, and the AutoRouter has the child widgets until I rotate the phone.

**Comment by vgtle** [comment]
Having the same problem. When switching from mobile to tablet, the underlying router scope loses its stack (hasEntries returns false). Therefore instead of rendering the page, a placeholder in the AutoRouteNavigator is passed to the Navigator widget.

**Comment by vgtle** [comment]
Having the same problem. When switching from mobile to tablet, the underlying router scope loses its stack (hasEntries returns false). Therefore instead of rendering the page, a placeholder in the AutoRouteNavigator is passed to the Navigator widget.

**Comment by vgtle** [comment]
I solved the problem for my case, where the state of the Autorouter widget was lost, when switching between mobile and tablet view. The solution was to make the state persistent by providing the AutoRouter widget a key. I used `GlobalObjectKey(__name__) `.

**Comment by fabirt** [comment]
> I solved the problem for my case, where the state of the Autorouter widget was lost, when switching between mobile and tablet view. The solution was to make the state persistent by providing the AutoRouter widget a key. I used `GlobalObjectKey(__name__) `.
Solved!!! thank you so much

**Comment by fabirt** [comment]
> I solved the problem for my case, where the state of the Autorouter widget was lost, when switching between mobile and tablet view. The solution was to make the state persistent by providing the AutoRouter widget a key. I used `GlobalObjectKey(__name__) `.

Solved!!! Thank you so much.

**Comment by resfandiari** [comment]
> > I solved the problem for my case, where the state of the Autorouter widget was lost, when switching between mobile and tablet view. The solution was to make the state persistent by providing the AutoRouter widget a key. I used `GlobalObjectKey(__name__) `.
> 
> Solved!!! Thank you so much.

How do I use this key? Could you send me part of the code?

**Comment by fabirt** [comment]
> > > I solved the problem for my case, where the state of the Autorouter widget was lost, when switching between mobile and tablet view. The solution was to make the state persistent by providing the AutoRouter widget a key. I used `GlobalObjectKey(__name__) `.
> > 
> > 
> > Solved!!! Thank you so much.
> 
> How do I use this key? Could you send me part of the code?

I set the same key when switching routers
```dart
class AuthLayout extends StatelessWidget {
  const AuthLayout({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;

    final routerKey = GlobalObjectKey('auth_router');

    return Scaffold(
      body: size.width >= 1000
          ? AuthLargeScreenLayout(
              child: AutoRouter(key: routerKey),
            )
          : AuthSmallScreenLayout(
              child: AutoRouter(key: routerKey),
            ),
    );
  }
}
```

**Comment by ricksondpenha** [comment]
Adding a GlobalObjectKey is working.. I'm closing this issue. Thanks @vgtle

**Comment by magician20** [comment]
@ricksondpenha  in your case, where did you add the Key ??
i'm using  AutoTabsScaffold  with Drawer.

**Comment by semsturgut** [comment]
@ricksondpenha  @magician20 Have you found the solution for AutoTabsScaffold?

**Comment by vgtle** [comment]
> @ricksondpenha @magician20 Have you found the solution for AutoTabsScaffold?

I would recommend to refactor your AutoTabsScaffold to a Widget with Scaffold, AutoTabsRouter and BottomNavigationBar. This would look similar to this:

```class DashboardPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AutoTabsRouter(
      key: GlobalObjectKey("tabs-router") // Add the key here. This is the important step.
      routes: const [
        UsersRoute(),
        PostsRoute(),
        SettingsRoute(),
      ],
      builder: (context, child, animation) {
        final tabsRouter = AutoTabsRouter.of(context);
        return Scaffold(
            body: 
              child: child,
            bottomNavigationBar: BottomNavigationBar(
              currentIndex: tabsRouter.activeIndex,
              onTap: (index) {
                tabsRouter.setActiveIndex(index);
              },
              items: [
                BottomNavigationBarItem(label: 'Users',...),
                BottomNavigationBarItem(label: 'Posts',...),
                BottomNavigationBarItem(label: 'Settings',...),
              ],
            ));
      },
    );
  }
}```

I hope that this helps you.

**Comment by semsturgut** [comment]
@vgtle Thank you. And I found a way to solve this even on the `AutoTabsScaffold`


```dart
return AutoTabsScaffold(
  routes: _routes,
  builder: (context, widget, animation) {
    final _widget = KeyedSubtree(key: _routerKey, child: widget);
    return ResponsiveBuilder(
      mobile: _widget,
      web: _widget,
    );
  },
);
```

**Comment by markbulingit** [comment]
> 

This will cause an error on hot reload

`Another exception was thrown: Multiple widgets used the same GlobalKey.`

**Comment by markbulingit** [comment]
> @vgtle Thank you. And I found a way to solve this even on the `AutoTabsScaffold`
> 
> ```dart
> return AutoTabsScaffold(
>   routes: _routes,
>   builder: (context, widget, animation) {
>     final _widget = KeyedSubtree(key: _routerKey, child: widget);
>     return ResponsiveBuilder(
>       mobile: _widget,
>       web: _widget,
>     );
>   },
> );
> ```

That will cause an error on hot reload.

`Another exception was thrown: Multiple widgets used the same GlobalKey.`

**Comment by magician20** [comment]
@markbulingit you must give each widget (Page) a GlobalKey different from the other one.
