### ISSUE TITLE
What is the point of these ...Argument classes since 0.4.3?

### ISSUE THREAD

**Issue by saschaernst** [Milad-Akarie/auto_route_library#59]
Hey,

since introduction of these argument classes, it is really hard to just call different routes by name receiving the same type of arguments. Is there any reason for this change to the previous version? It is still only a runtime check.

Cheers, Sascha

**Comment by Milad-Akarie** [comment]
Hey @saschaernst we've discussed this
 here https://github.com/Milad-Akarie/auto_route_library/issues/50

**Comment by saschaernst** [comment]
I am not convinced. Right now I am generating my app structure tree from a config, so at runtime I have a couple of different pages all expecting the same argument. When using the navigator I only know the target id from my config and some payload they all agree on. Unfortunately now I have to know the exact type of Argument class when making the push call. Is there any way that I can define my own argument classes manually?

**Comment by Milad-Akarie** [comment]
@saschaernst Just go back to the previous version for now I'll make the whole thing optional..how does that sound?

**Comment by saschaernst** [comment]
sounds good to me, thanks!

**Comment by Milad-Akarie** [comment]
Hey Sasch, as promised, generating args holder for single parameter routes is now optional
just set generateArgsHolderForSingleParameterRoutes to false in MaterialAutoRouter()
it's true by default.
auto_route 0.4.4
auto_route_generator 0.4.4
enjoy!
