### ISSUE TITLE
(help needed): context.pushRoute produces The method 'pushRoute' isn't defined for the type 'BuildContext'

### ISSUE THREAD

**Issue by YuriHeiko** [Milad-Akarie/auto_route_library#591]
I made changes according to the [documentation](https://autoroute.vercel.app/introduction/installation_and_usage).   
```dart
import 'package:flutter/material.dart';

import 'app_router.gr.dart';
import 'constants/app_colors.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
      title: 'MyApp',
      theme: ThemeData(
        primarySwatch: AppColors.brown,
        accentColor: Colors.blue,
        canvasColor: Colors.white,
        fontFamily: 'Poppins',
      ),
    );
  }
}

```

When I try to use `context.pushRoute(RouteName)` I'm getting the compile error:  
`The method 'pushRoute' isn't defined for the type 'BuildContext'`
However, `AutoRouter.of(context).push(RouteName)` works as expected. 
What step did I miss?

**Comment by Joel-Jensen** [comment]
Android Studio couldn't find it for me either but after throwing some code around it suddently worked. I think the missing part is to import it.
`import 'package:auto_route/auto_route.dart';`

**Comment by YuriHeiko** [comment]
@Joel-Jensen Yeap, you are right. Thank you!
