### ISSUE TITLE
navigate directly from parent to child sub route

### ISSUE THREAD

**Issue by nachten** [Milad-Akarie/auto_route_library#592]
Hi There,

I can i directly navigate from MasterScreen to MenuItemTemplate -> Tabs route ? 

I tried: 

`AutoRouter.innerRouterOf(context, MasterScreenRoute.name)!
            .navigateNamed(
          '/app/$slaveId/view/$viewTypeId/module/$moduleId/menu/${menuItemConfig.path}/tab/$tabId',
        )`

`@AdaptiveAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    // home
    AutoRoute(
      fullscreenDialog: true,
      initial: true,
      path: '/app',
      page: MasterScreen,
      children: [
        AutoRoute(
          fullscreenDialog: true,
          path: '',
          page: HomeTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId',
          page: FarmviewTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId/quickmenu',
          page: QuickmenuTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId/manuals',
          page: ManualsTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId/graphs',
          page: GraphsTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId/alarmview',
          page: AlarmViewTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path:
              ':slaveId/view/:viewTypeId/module/:moduleId/template/:templateId',
          page: ModuleTemplate,
          children: [],
        ),
        AutoRoute(
          fullscreenDialog: true,
          path: ':slaveId/view/:viewTypeId/module/:moduleId/menu/:menuPath',
          page: MenuItemTemplate,
          children: [
            AutoRoute(
              fullscreenDialog: true,
              path: 'tab/:tabId',
              page: Tabs,
              children: [],
            ),
            AutoRoute(
              fullscreenDialog: true,
              path: 'template/:templateId',
              page: TabTemplate,
              children: [],
            )
          ],
        ),
        RedirectRoute(path: '*', redirectTo: ''),
      ],
    ),

    // redirect all other paths
    RedirectRoute(path: '*', redirectTo: '/app'),
    //Home
  ],
)
class $AppRouter {}`

**Comment by gurupras** [comment]
Did you ever figure this out?
