### ISSUE TITLE
Rename router.dart to router.g.dart

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#6]
Maybe this can be renamed, it seems to be a convention for generated files.

Currently one has to manually add `router.dart` to .gitignore where as `router.g.dart` would often be ignored by default.
In my case I have to also change build files in CI because `router.dart` doesn't match the pattern.

Maybe even allow changing the file name and path by adding an `@AutoRouter()` annotation or something like this.

```dart
/// /lib/foo/bar_router.dart
import 'package:auto_route/auto_route_annotation.dart';

part 'bar_router.g.dart';

@AutoRouter()
class BarRouter with _BarRouter {
}
```

**Comment by Milad-Akarie** [comment]
Hey @kuhnroyal! as stated in the docs I shouldn't use the `.g.dart` extension unless I'm using a SharedPartBuilder, because other libraries might use the same file to generate their part of code.
I thought of renaming it to something like GRouter or GeneratedRouter  to indicate that it's generated, but that still won't help with .gitignore part and that can be a pain if you don't manually ignore it.

**Comment by kuhnroyal** [comment]
Yea you are right, that's why I suggested the code sample above which would make it a `SharedPartBuilder`.

I also noted another issue today which I didn't think of before. I am working a lot with `build_runner watch`. Now having a couple of pages/routes, anytime I change something unrelated to routing in one of these pages, it get's regenerated. Not sure how to solve this other then creating wrapper widgets for every page.

**Comment by Milad-Akarie** [comment]
@kuhnroyal  watch mode literally watches the file system for changes.
What do you think of having all the Routes declaration in one file instead of annotating the actual route widgets? 

I'm thinking something like a route-config file

@AutoRoutes(..global-config)
const List<AutoRoute> = [
InitialRoute(HomeScreen),
AutoRoute(SecondScreen, ....explicit route config),
]

**Comment by kuhnroyal** [comment]
I think this would help a lot.
Maybe you can support both ways, and then just merge all and check for duplicates.

**Comment by Milad-Akarie** [comment]
I'm having second thoughts about this. The whole idea was to not get distracted from the working source file (Your Widget) but not you have to open the route-config file and edit it.

**Comment by kuhnroyal** [comment]
With support for both ways, this would still be possible.
I love the whole idea of having the annotation on the class, but it is unusable with watch mode.

**Comment by Milad-Akarie** [comment]
Even with the single config file approach the watch mode problem still persists.

**Comment by kuhnroyal** [comment]
Yea, since the generator checks for arguments. It probably needs to cache those and abort if there are no changes to the constructor signature.

**Comment by kuhnroyal** [comment]
I just removed the generator, now the watch mode causes a re-run of all generators on changes but all my other generators notice that nothing needs to be done - it takes < 1 sec.

With the auto_route generator, when I change something completely unrelated, it re-runs several times and takes > 30sec.

**Comment by Milad-Akarie** [comment]
@kuhnroyal  I was just focused on making it work, I'm working on a new approach now, maybe you can help me test it out. ...How many screens do you have? also how does this look?

@autoRouter
class _$Router {
  @initial
  HomeScreen homeScreenRoute;
  SecondScreen secondScreenRoute;
}

**Comment by Milad-Akarie** [comment]
@kuhnroyal  please check out version 0.2.0 whenever you get the chance and share your thoughts.

**Comment by kuhnroyal** [comment]
This looks really good, no more endless rebuilds.
Still not sure if this is a good way to go with having to import the generated router file.

**Comment by Milad-Akarie** [comment]
@kuhnroyal  What do you have in mind?

**Comment by kuhnroyal** [comment]
Looking at this I feel this should become a shared part builder but I am not sure how to solve the name conflict of the route declaration/string name and the imports of the generated routes argument classes.

**Comment by Milad-Akarie** [comment]
The main problem here is that part files can not import anything and as you can see I'm doing all of importing in the generated file.

**Comment by kuhnroyal** [comment]
Yea I have looked at it and I am not sure how to solve it. I will think about it a little more.

**Comment by Milad-Akarie** [comment]
I appreciate the effort. let me know if you come up with something.

**Comment by windrunner414** [comment]
If I remember correctly, .g.dart and all generated code is recommended to check in

**Comment by Milad-Akarie** [comment]
@windrunner414  is it? can you please link me to a documentation or something?

**Comment by windrunner414** [comment]
@Milad-Akarie sorry I was mistaken :) already edited

**Comment by Milad-Akarie** [comment]
@windrunner414 it's okay. I think it's time I closed this one anyways
