### ISSUE TITLE
[Question] Nested route within modal sheet

### ISSUE THREAD

**Issue by petrnymsa** [Milad-Akarie/auto_route_library#602]
I use this package https://pub.dev/packages/modal_bottom_sheet. There is also example with nested navigation within modal sheet. 

I've read the documentation on github and I've managed to get a working nested router between pages, but I can't figure out how to use it with a modal sheet. 

My idea is -> open modalSheet and there put AutoRouter() widget.
We have DetailPage with ItemId - there is displayed some info about item. From there, i can click on button which will open modal sheet with contacts. Form there i can go to contact detail (within modal sheet). 

So my router setup is 
```dart
 AutoRoute(
      path: '/detail/:id',
      page: DetailPage,
      children: [
        AutoRoute(path: 'contacts', page: ContactsList),
        AutoRoute(path: 'contacts/detail', page: ContactsDetail),
      ],
    ),
```
I get following error
```
RouterData operation requested with a context that does not include and RouteData. The context used to retrieve the RouteData must be that of a widgets that is a descendant of a AutoRoutePage ... So somehow i need to pass "DetailPage" context to modal sheet? 
````
I am opening modal sheet like this: 

```dart
// TextButton is part of Detailpage widget tree. Context is from // build() method of DetailPage
  child: TextButton(
              child: Text('Modal'),
              onPressed: () {
                showMaterialModalBottomSheet(
                    context: context,
                    builder: (context) {
                      return AutoRouter();
                    });
              },
            ),
```

Any help welcome. Thank you

**Comment by semsturgut** [comment]
Same here 😕
Hey, @petrnymsa Did you find the solution?

**Comment by petrnymsa** [comment]
> Same here 😕
> Hey, @petrnymsa Did you find the solution?

@semsturgut  Well yes, but not :D We ended up with custom Navigator for modal sheets, outside we still use Auto_route... it is not a best solution but at least it works now..

**Comment by Limbou** [comment]
Would be great to see some official solution here, I think it is quite common problem.

**Comment by jtdLab** [comment]
Yeah, solution to this would be nice.

**Comment by SpaceWaffles** [comment]
I also need to do this; any updates here?

**Comment by aytunch** [comment]
How can we use modal sheets along with auto router? what is the recommended way for the urls and back/forward buttons to work as expected in web?

**Comment by Milad-Akarie** [comment]
@aytunch try using a custom route with customRouteBuilder
Then return the bottom sheet route (should be shipped with the bottom sheet package) as custom route

**Comment by birdycn** [comment]
how now
