### ISSUE TITLE
CustomAutoRouter ignores reverseDurationInMilliseconds

### ISSUE THREAD

**Issue by khainke** [Milad-Akarie/auto_route_library#603]
As i understand it, reverseDurationInMilliseconds should effect the animation duration on a "pop" / "back" interaction on the page. Im using it as follows (i essentially want to disable any animation):

```dart
@CustomAutoRouter(
  replaceInRouteName: 'Page,Route',
  transitionsBuilder: TransitionsBuilders.fadeIn,
  durationInMilliseconds: 0,
  reverseDurationInMilliseconds: 0,
  routes: <AutoRoute>[
    AutoRoute(
      page: HomePageWrapper,
      path: '/',
      initial: true,
      children: [
        AutoRoute(path: '', page: HomePage),
        AutoRoute(path: 'list', page: ListPage),
        AutoRoute(
          path: 'settings',
          page: SettingsPageWrapper,
          children: [
            RedirectRoute(path: '', redirectTo: 'user'),
            AutoRoute(path: 'user', page: UserSettingsPage),
            AutoRoute(path: 'server', page: ServerSettingsPage),
          ],
        ),
      ],
    ),
    AutoRoute(page: LoginPage, path: '/login'),
  ],
)
class $AppRouter {}
```

But when i run it in Chrome any "forward" animation is instant, but the reverse animation still persist for a while, looks like the `reverseDurationInMilliseconds` property is ignored, even though `transitionsBuilder` is given. Even every positive value does not seem to have any effect. Am I missing something, or how can i disable animations on a "back" / "previous page" transition?

**Comment by Milad-Akarie** [comment]
@khainke if you don't want any transitions just leave the transitions builder empty in CustomRoute

**Comment by harkairt** [comment]
Happens for me as well. 
The issue still stands. Users of this library might want an entry animation, but an instant pop.

Many thanks btw, my life is much easier with `auto_route`

**Comment by khainke** [comment]
> 
> 
> @khainke if you don't want any transitions just leave the transitions builder empty in CustomRoute

This will not change the default reverse transition... (at least for web, back button/navigation in browser will still fade to the last route). 

(i tried both specifying `null` and not specifying the parameter)

**Comment by Tienisto** [comment]
Can confirm this in `3.2.2`.

Even the simplest configuration has a delay on pop. This makes it unusable in Flutter Web...

```dart
@CustomAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: FirstPage, initial: true),
    AutoRoute(page: SecondPage),
  ],
)
```

**Comment by khainke** [comment]
if there was no recent changes, then this is still an open issue. (this is a bump, so this issue stays open.)

**Comment by eXifreXi** [comment]
Pretty sure I'm still witnessing this on latest.

**Comment by khainke** [comment]
pretty sure, this is still an issue ...

**Comment by MohamadTheWarrior** [comment]
If you want to disable animations you can use `customRoute` with `transitionBuilder`:

```
CustomRoute<void>(
  page: YourPage,
  transitionsBuilder: TransitionsBuilders.noTransition,
)

```

**Comment by khainke** [comment]
just wanna say, im pretty sure, this issue still stands, if nothing was done about it. And @MohamadTheWarrior even if this was the case, it would still be misleading to have a parameter that does not what its supposed to do. (and im pretty sure your solution does not work, if nothing was changed with regard to this issue). 
But in the meantime i moved on to another package and i dont have the motivation to test this issue every 2 months and post about. And im not so sure about a bot, which mindlessly closes issues that are not addressed...

**Comment by eXifreXi** [comment]
Yeah that sadly happens on nearly (?) every REPO on GitHub. If you don't constantly push an Issue, it's just going to be closed.
Probably cause the general consent is "Oh, no one is posting about it, so it must have vanished." :P
