### ISSUE TITLE
[FeatureRequest] Dynamically set inital route of AutoTabsRouter

### ISSUE THREAD

**Issue by antholeole** [Milad-Akarie/auto_route_library#604]
hi there! thanks for the awesome lib. 

For my use case, I'd like when my app closes and relaunches, to have the same tab up as the one that was open when the app closed. Unfortunately, with autoTabsRouter, there's no way to do this: the initial route is hardcoded. 

I'd like an API that looks like this:

```dart
AutoTabsRouter(
        initalRoute: FooRoute,
        routes: [
          FooRoute(),
          BarRoute(),
        ],
      )
```

or even 

```dart
AutoTabsRouter(
        routes: [
          FooRoute(),
          BarRoute(),
        ],
      )..route = FooRoute
```

let me know if you're open to a PR for this!

**Comment by Milad-Akarie** [comment]
@antholeole have you tried using the declarative version?
