### ISSUE TITLE
ExtendedNavigator or navigation without context

### ISSUE THREAD

**Issue by mars3142** [Milad-Akarie/auto_route_library#605]
I'm using redux as state management and used Flutter 1.x with auto_route 1.x. Now I wanted to upgrade to Flutter 2 incl. all dependencies. The problem is, that I used ExtendedNavigator within my redux middleware (because I don't want to pass the context in the actions). 

What's the best practice to use the latest auto_route (because of null safety) and navigation without passing context around? My problem is I can't use AutoRoute.of(context) or context.push - because I don't have access to the context within redux (without passing BuildContext around).

**Comment by RemeJuan** [comment]
You should not be navigating from within your state, that is a very bad mixing of UI and Business logic.

Not sure about Redux, have not used it, but in BLoC there is a `BlocListener ` widget which is a listen argument which on the UI side that would provide the state and the context and this is where one would be doing the navigation.

```dart
BlocListener<BlocA, BlocAState>(
  bloc: blocA,
  listener: (context, state) {
    // do stuff here based on BlocA's state
  },
  child: Container()
)
```

Your UI would look something like that and in the listener, you would perform UI logic based on state updates.

Assuming you are trying to redirect on successful login you may have state values such as `LoggingIn`, `LoginSuccess`, and `LoginFailure`.

You could then do

```dart
  listener: (context, state) {
    if (state is LoginSuccess) context.push(LoggedInRoute());
    if (state is LoginFailure) context.push(LoginRoute());
  },
```

One would hope redux also has something like this, but I was also making heavy use of the ExtendedNavigator, 99% of the time unnecessarily, but one use case which had to be refactored post-upgrade was similar to the one I described, on the network layer I had the session expired logic which at that point would redirect the user back to the login screen, having already had a global state to contain the few things that needed to be accessible by nearly every view I reworked the failure logic back into the BLoC and added `AuthenticationFailure` to the enums for that state and did the navigation that way.

As `auto_route` was rewritten to align internally closer to Navigator 2, I assume there was a good reason that had to be taken out, so I would not expect it to come back, so if Redux does not have something similar to the listener, you would have to find some other way of instructing your UI to do UI logic based on updates within your Business logic.

**Comment by Kuodster** [comment]
I'll leave this comment for anyone using auto_route 2.0 with flutter_bloc package.

1. Create new BLoc that will contain the following code (for example - AppRouterBloc):

An event to fire whenever we need to do navigation outside of the AutoRoute context:

``` lang-dart
typedef AsyncCallbackWithRouter = Future<void> Function(AppRouter);

class RoutingEvent extends AppRouterEvent {
  final AsyncCallbackWithRouter callback;

  const RoutingEvent({
    required this.callback,
  });

  @override
  List<Object?> get props => [callback];
}
```

A state that will just act as a trigger:

``` lang-dart
class AppRouterCallback extends AppRouterState {
  final AsyncCallbackWithRouter callback;

  const AppRouterCallback({
    required this.callback,
  });

  @override
  List<Object> get props => [callback];
}
```

3 lines of code inside the main BLoc class:

``` lang-dart
    if (event is RoutingEvent) {
      yield AppRouterCallback(callback: event.callback);
    }
```

2. Use get_it package or anything similar that can act as a container (**Be sure to inject the BLoc as soon as possible in to the container, so that it will be available to use during any call. You can even to this in your main() function**):

``` lang-dart
getIt.registerSingleton<AppRouterBloc>(AppRouterBloc());
```

3. Wrap the entire MaterialApp in a BlocListener widget linked to the bloc that is inside the container:

``` lang-dart
BlocListener(
      bloc: getIt.get<AppRouterBloc>(),
      listener: (context, state) {
        if (state is AppRouterCallback) {
          state.callback(_appRouter); // <- this is the same AppRouter that is created before the MaterialApp() itself
        }
      },
      child: MaterialApp.router(...),
)
```

4. Use routing without context:

``` lang-dart
             getIt.get<AppRouterBloc>().add(
                RoutingEvent(
                  callback: (router) async {
                    router.push(...);
                  },
                ),
              )
```

Hope this will help you solve the problem.
