### ISSUE TITLE
Error on int query parameters

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#606]
I'm getting the following error when pushing a route with an int query parameter:

```
The following _TypeError was thrown during a scheduler callback:
type 'int' is not a subtype of type 'Iterable<dynamic>'

When the exception was thrown, this was the stack: 
#0      _Uri._makeQuery.<anonymous closure> (dart:core/uri.dart:2167:18)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#2      _Uri._makeQuery (dart:core/uri.dart:2163:21)
#3      new _Uri (dart:core/uri.dart:1427:13)
#4      UrlState._buildUri (package:auto_route/src/router/parser/route_information_parser.dart:91:12)
...
```

Are query parameters forced to be strings ?

**Comment by Herrera93** [comment]
This is a `Dart` issue:
https://github.com/dart-lang/sdk/issues/46251

Looks like allow `dynamic` value to allow multiple string as a value. Would be nice if `auto_route` could check for this

**Comment by Milad-Akarie** [comment]
@Herrera93 I don't get it, where does this happen? how do I reproduce?

**Comment by Herrera93** [comment]
@Milad-Akarie sorry for the ambiguity, it's on web when pushing a route with an int query parameter

**Comment by Milad-Akarie** [comment]
@Herrera93 Fixed, will be included in next build
Thanks for reporting.
