### ISSUE TITLE
Android Back Button closes entire app

### ISSUE THREAD

**Issue by QuirijnGB** [Milad-Akarie/auto_route_library#609]
Heya!

Im having an issue I cant really figure out.

My `MainScreen` has 5 tabs, and `TabA` has 2 children.
If i navigate from `PageA` to `PageB` and hit the back button on Android the entire app closes.
I've attempted to catch it with a `WillPopScope` but I can't seem trigger that callback either.

```dart
        CustomRoute(
          transitionsBuilder: TransitionsBuilders.fadeIn,
          path: '',
          page: MainScreen,
          name: 'MainScreenRouter',
          children: <AutoRoute>[
            AdaptiveRoute(
              path: '',
              name: 'TabA',
              page: EmptyRouterPage,
              children: <AutoRoute>[
                AdaptiveRoute(path: '', page: PageA),
                AdaptiveRoute(path: 'pageB', page: PageB),
              ],
            ),
            AdaptiveRoute(path: 'tabB', page: TabB),
            AdaptiveRoute(path: 'tabC', page: TabC),
            AdaptiveRoute(path: 'tabD', page: TabD),
            AdaptiveRoute(path: 'tabE', page: TabE),
          ],
        ),
```

**Comment by rvndsngwn** [comment]
Same issue with me I'm using `router.push(BooksListRoute())  ` & `AutoRouter.of(context)
                                              .push(SearchRoute());` router types , when I'm click back button on android phone app directly closed.  Issue with only on Android phones.

**Comment by rvndsngwn** [comment]
@QuirijnGB can find any solution of this issue ?
@Milad-Akarie help in this issue.

**Comment by Milad-Akarie** [comment]
@rvndsngwn @QuirijnGB it works just fine, do you know how I can reproduce this? 

https://user-images.githubusercontent.com/55059449/128511698-b12d825a-8efa-4fe9-86cb-2f40d29cd942.mp4

**Comment by QuirijnGB** [comment]
Sorry I left the project where i was having the issue, so no longer have access to the code

**Comment by ariefwijaya** [comment]
> @rvndsngwn @QuirijnGB it works just fine, do you know how I can reproduce this?
> 
>  auto_route_back_button.mp4

When pop back in **Profile** should be navigated to **Books** , don't close the entire apps. is it possible to do that?

**Comment by Milad-Akarie** [comment]
@ariefwijaya That's a different use-case, anyways, in the latest release you can set homeIndex  to whatever index you want your TabsRouter to reset to before it can pop

```dart
AutoTabsRouter(
    homeIndex: 0,
    ...
   )
// or
AutoTabsScaffold(
    homeIndex: 0,
    ...
   )
```
```yaml
 auto_Route: 2.4.0
 auto_route_generator: 2.4.0
```
