### ISSUE TITLE
Argument to initial route

### ISSUE THREAD

**Issue by atoumbre** [Milad-Akarie/auto_route_library#61]
Hello 

How to pass arguments to the initial route?

BR,

**Comment by Milad-Akarie** [comment]
Hey @atoumbre 
Since ExtendedNavigator navigates to the initial route automatically you need to pass them to it
`ExtendedNavigatore<Router>(router:router,  initialRouteArgs: YOURARGS)`

**Comment by atoumbre** [comment]
Nice, but works from 0.4.3, right?
