### ISSUE TITLE
Application Resets to initRoute on Hot Reload or Hot Restart

### ISSUE THREAD

**Issue by GiteshDalal** [Milad-Akarie/auto_route_library#610]
I am using Bloc and Auto Route and everything works great but its very tedious during development when the URL resets to initRoute on every hot reload.

```
AppRouter _router = RootAppRouter();

MaterialApp.router(
      // Router Config
      routeInformationParser: _router.defaultRouteParser(),
      routerDelegate: AutoRouterDelegate.declarative(
        _router,
        routes: (_) => [
          if (context.read<SessionCubit>().state.isLoggedIn)
            GAppRouter()
          else if (!context.read<SessionCubit>().state.isLoadingSession)
            GAuthRouter(children: const [GLoginRoute()]),
        ],
      ),
      // App Config
      title: 'Application',
 );
```

**Comment by princestha** [comment]
I think I am having the exact same issue, did you solve this? Basically, when I restart or hot reload, it removes all the widgets below MaterialApp for me. It's so weird. I have been trying to debug this, but it's not working out.

**Comment by princestha** [comment]
@GiteshDalal  I can't believe I missed this but this is working for me now. Try this. Move the state up: 
https://github.com/Milad-Akarie/auto_route_library/issues/584
