### ISSUE TITLE
auto_route_generator test

### ISSUE THREAD

**Issue by vasilich6107** [Milad-Akarie/auto_route_library#614]
Hi @Milad-Akarie 

I'm actively maintaining `Atremis` code generator.
I noticed that you do not have any tests for `auto_route` generator.

We have som https://github.com/comigor/artemis/tree/master/test

Are you interested in adding test?
If yes - I can try to start adding them...

**Comment by Milad-Akarie** [comment]
Hello @vasilich6107 I'm very interested, I was waiting for someone to offer to help.

**Comment by vasilich6107** [comment]
Ok,I’ll try to add first one :-)

**Comment by vasilich6107** [comment]
#617 is ready for review and discussion

**Comment by vasilich6107** [comment]
Could you also merge my PRs #613 and #616

**Comment by Milad-Akarie** [comment]
@vasilich6107 Thank you very much, please understand that I'm on my honeymoon and it might take me a sometime to get a chance to revise your PR's.

**Comment by vasilich6107** [comment]
Congrats ;-)
Thanks for responding.
I will wait)
Hope this will happen this month ;-)

**Comment by vasilich6107** [comment]
Hi @Milad-Akarie 
Do you have any updates about getting back from vacation?

In the meantime I have a solution that will give us a possibility to avoid splitting `annotations` into separate package.

**Comment by Milad-Akarie** [comment]
@vasilich6107 technically I'm back now but have to deal with some pending work for my paying job.

**Comment by vasilich6107** [comment]
Good news!
I will prepare the updated sample with tests.
The next move is to setup PR checks

**Comment by vasilich6107** [comment]
Hi @Milad-Akarie 
I fixed and reworked test approach
Could you check, please)
