### ISSUE TITLE
EmptyRouterPage push blank screen for a sec

### ISSUE THREAD

**Issue by Vasco-90** [Milad-Akarie/auto_route_library#619]
Hey there,

I have a bottom navigation bar and each Tab has its own Route with an EmptyRouterPage as initial Page. But on each tab there is for a second a blank page. How to avoid this behavior ?

Here my router file, its not the full file.
```dart
@MaterialAutoRouter(
  preferRelativeImports: true,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute<AutoRoute>(
      page: DashboardPage,
      initial: true,
      path: '/',
      maintainState: true,
      children: [
        AutoRoute<dynamic>(
          name: 'HomeTab',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: HomePage),
            AutoRoute<dynamic>(page: ProductPage, path: 'article/:id'),
          ],
        ),
        AutoRoute<dynamic>(
          name: 'SearchTab',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(
              page: SearchPage,
              path: 'search-page',
              initial: true,
            ),
            AutoRoute<dynamic>(page: SearchResultsPage, path: 'searchResult'),
            AutoRoute<dynamic>(page: ProductPage, path: 'article/:id'),
          ],
        ),
```

My implementation:
```dart
@override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      routes: const [
        HomeTab(),
        SearchTab(),
        CartTab(),
        AccountTab(),
        MoreTab(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
            return DashboardBottomNavigation(tabsRouter: tabsRouter);
      },
    );
  }
```
        
The Problem I have, when I delete the EmptyPageRoute and replace it with the "HomePage", or the "SearchPage" which both are the initialPage of Its not possible to navigate to the inner page "ProductPage". In the log, the Exception looks like "Router cannot navigate to ProductPage". I already tried to add the parameter "initial: true".

Thanks

**Comment by Milad-Akarie** [comment]
@FunkyMan4415 is your scaffold background different then the tabs background?

**Comment by FunkyMan4415** [comment]
@Milad-Akarie  sorry, could you explain the question a bit? Background color? or what do you mean with "background" ?

**Comment by Milad-Akarie** [comment]
@FunkyMan4415 yes

**Comment by FunkyMan4415** [comment]
@Milad-Akarie Yes I have different backgrounds and different appbars on each tab. Tab 1 has an Appbar with a logo and Tab 2 has an Appbar with a search field. But the Scaffoldbackground color are the same. 

The main problem here is the flickering. on each tab before the initial route is loaded.

**Comment by ObserverMoment** [comment]
@Milad-Akarie @Vasco-90 Did anyone else solve this? I'm still getting white flashes when I first load the app - being caused by rendering an AutoRouter widget (or an AutoTabsRouter). 

Is there some issue with using CupertinoApp (which I am) instead of Material App? As soon as you remove the AutoRouter widget the flash is gone and the page loads as normal.

Is AutoRouter getting its background color from Material ThemeData regardless of whether we use Cupertino or not?

I have one background color for my CupertinoPageScaffolds - set in CupertinoThemeData.

Any ideas? 

Thanks

**Comment by jlnrrg** [comment]
This can be solved by setting `lazyLoad: true` in the `AutoTabsScaffold`
(giving that you are using this :smile:)

**Comment by jlnrrg** [comment]
I think it is not only an issue of the background color, but that an initial page is pushed in the first place.
This creates the build of a seperate screen which in turn looks like a flash in between the intended page to be pushed.

(Maybe a transparent screen might solve it 🤔 have to try it)

**Comment by ObserverMoment** [comment]
Hi @Milad-Akarie , thank for the update!

When you say default scaffolds background colour - does this take into account CupertinoThemeData? Or does it look ONLY for a Material ThemeData object and get its background colour from that?

My app dos not have a Material app or a Material ThemeData in it...all my theming is done via CupertinoApp and CupertinoThemeData.

Should I try wrapping my AuthedRoutesWrapperPage in a Theme object - or something similar?

**Comment by guyluz11** [comment]
Try setting you AppRouter() as `static`.


``` dart
class AppWidget extends StatelessWidget {
  static final _rootRouter = AppRouter();

  @override
  Widget build(BuildContext context) { ...... }
```

**Comment by EhabSalah** [comment]
Facing the same issue I think! 
A black screen displays to the user. It usually goes away fast, but sometimes stays! See screenshot.

![Screenshot_20220210-174829_Flash](https://user-images.githubusercontent.com/24505720/161765278-c7363087-366e-4527-9820-29e646f8d2d4.jpg)

**Comment by Milad-Akarie** [comment]
@EhabSalah does your authGuard take sometime to resolve inside of onNavigation?

**Comment by EhabSalah** [comment]
Yes, but same problem happens with another route which has no guards!

**Comment by GitRubb** [comment]
Is it possible to reopen this? It's still an issue.

**Comment by abcdurga** [comment]
> Hey there, I could solve this issue by adding the `animationDuration` property.
> 
> ```dart
>  return AutoTabsScaffold(
> 
>       animationDuration: const Duration(microseconds: 0), // This  solved my flashing issue
>       routes: const [
>         HomeTab(),
>         SearchTab(),
> 
>       ],
>       bottomNavigationBuilder: (_, tabsRouter) {
>         return DashboardBottomNavigation(tabsRouter: tabsRouter);
>       },
>     );
> ```

This solution resolved my issue as well. Thank you @Vasco-90 . The problem occurs only when I use multiple app bars in each page. The animation is smooth if I use single app bar for the entire app. But my app requirement is to use different app bars. So the blank screen(for micro seconds) issue while tapping different bottom tabs is solved by putting the value 0 instead of 400.

**Comment by PawlikMichalMiquido** [comment]
Hey @Milad-Akarie this is still happening. 
Settings `lazyLoad: false` indeed helps, but it's a not a feasible workaround if one is making a lot of network requests on each tab
