### ISSUE TITLE
How to use with CupertinoTabView?

### ISSUE THREAD

**Issue by bizz84** [Milad-Akarie/auto_route_library#62]
I was using version `0.2.2` of this package, with the following setup
```dart
  final Map<TabItem, WidgetBuilder> widgetBuilders;
  final Map<TabItem, GlobalKey<NavigatorState>> navigatorKeys;

  // in build method:
        return CupertinoTabView(
          navigatorKey: navigatorKeys[item],
          builder: (context) =>  widgetBuilders[item](context),
          onGenerateRoute: CupertinoTabViewRouter.onGenerateRoute,
        );

// where
@CupertinoAutoRouter()
class $CupertinoTabViewRouter {
  @CupertinoRoute(fullscreenDialog: false)
  JobEntriesPage jobEntriesPage;
}
```
However, in recent versions, the generated`CupertinoTabViewRouter.onGenerateRoute` is no longer a static method.

So, how should I use the new API?
I've seen that the documentation shows some example code with `MaterialApps(builder: ExtendedNavigator<Router>(router: Router()))`.

But this doesn't work in my case as I have multiple `CupertinoTabView`s, each with its own `widgetBuilder`. 

If the solution is indeed to use `ExtendedNavigator`, how can I adapt it to work with multiple tabs?

**Comment by Milad-Akarie** [comment]
Hey @bizz first for all, thanks for all the great tuts! keep them coming!
please help me understand what's going on here.
CupertinoTabView is just a wrapper for Navigator, is every tab you in your App a nested navigator? 
if yes, are you trying to use the same router for all the nested navigators you have?

**Comment by bizz84** [comment]
@Milad-Akarie thank you.
Yes, my goal is to have nested navigators.
For context, this is an implementation of my code that doesn't use `auto_route`:

```
class CupertinoTabViewRoutes {
  static const jobEntriesPage = '/job-entries-page';
}
class CupertinoTabViewRouter {
  static Route generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case CupertinoTabViewRoutes.jobEntriesPage:
        final job = settings.arguments;
        return CupertinoPageRoute(
          builder: (_) => JobEntriesPage(job: job),
          settings: settings,
          fullscreenDialog: true,
        );
    }
    return null;
  }
}
class CupertinoHomeScaffold extends StatelessWidget {
  CupertinoHomeScaffold({
    Key key,
    @required this.currentTab,
    @required this.onSelectTab,
    @required this.widgetBuilders,
    @required this.navigatorKeys,
  }) : super(key: key);

  final TabItem currentTab;
  final ValueChanged<TabItem> onSelectTab;
  final Map<TabItem, WidgetBuilder> widgetBuilders;
  final Map<TabItem, GlobalKey<NavigatorState>> navigatorKeys;

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        key: Key(Keys.tabBar),
        items: [
          _buildItem(TabItem.jobs),
          _buildItem(TabItem.entries),
          _buildItem(TabItem.account),
        ],
        onTap: (index) => onSelectTab(TabItem.values[index]),
      ),
      tabBuilder: (context, index) {
        final item = TabItem.values[index];
        return CupertinoTabView(
          navigatorKey: navigatorKeys[item],
          builder: (context) => widgetBuilders[item](context),
          onGenerateRoute: CupertinoTabViewRouter.generateRoute,
        );
      },
    );
  }
```
Would it make sense for me to have three `ExtendedNavigator<Router>(router: Router()))`, instead of the current `widgetBuilders`?

**Comment by Milad-Akarie** [comment]
@bizz84 Of course it would, like I said CupertinoTabView is just a wrapper for Navigator. 

This's how I image your setup to be

```dart
 tabBuilder: (context, index) {
        final item = TabItem.values[index];
        return ExtendedNavigator(
          key: navigatorKeys[item]
          router: nestedRouters[item],
        );
      },
```
also If I understand your code correctly, the builder in CupertinoTabView is just responsible for building you initial page which simply could be your initial route. so you don't actually need the builder

**Comment by bizz84** [comment]
@Milad-Akarie that makes sense. Thanks for the explanation :)
