### ISSUE TITLE
Issue with ModalBottomSheet

### ISSUE THREAD

**Issue by Hrishi1999** [Milad-Akarie/auto_route_library#621]
Hi, I have an issue where pressing back button when a modalsheet is open would pop the route instead of closing the sheet. I am creating a Flutter Web app. 

My routes are defined as 
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: EntryPoint, path: '/', initial: true),
    AutoRoute(page: Home, path: '/home', guards: [IfAuth]),
    AutoRoute(
        page: File,
        path: 'file/users/:id',
        guards: [IfAuth]),
    AutoRoute(
        page: Plan,
        path: '/plan/users/:id',
        guards: [
          IfAuth
        ],
        children: [
          AutoRoute(page: Planner, initial: true, guards: [IfAuth])
          AutoRoute(
              page: Calculator,
              path: 'calculator/:id',
              guards: [IfAuth]),
        ]),
  ],
)
```

Where I try to push/replace by ```context.router.navigate(Calculator(id: "test"));``` from Plan, and the Calculator page will have the ModalBottomSheets. Pressing back would just take me back to Plan screen (parent) instead of closing the sheet.

**Comment by NachiketaVadera** [comment]
@Milad-Akarie Hey. I also have the same issue. Can you help out with this?

**Comment by Milad-Akarie** [comment]
@NachiketaVadera I can't reproduce the issue on my machine, could you show me some code?

**Comment by Hrishi1999** [comment]
Hi, I show the bottom sheet using 
```
showModalBottomSheet(
                                    isScrollControlled: true,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.only(
                                        topLeft: Radius.circular(30.0),
                                        topRight: Radius.circular(30.0),
                                      ),
                                    ),
                                    context: context,
                                    builder: (context) =>
                                        XYZForm());
```

**Comment by Milad-Akarie** [comment]
@Hrishi1999 How does your Router setup look like? where are you showing the modal sheet

**Comment by Hrishi1999** [comment]
I've shown my router setup above. I display the modal sheet in Plan > Calculator.

**Comment by Milad-Akarie** [comment]
@Hrishi1999 your back button is inside of HomeRoute?

**Comment by Hrishi1999** [comment]
@Milad-Akarie I do not have any back button, I mean the physical back button. I am opening a modal sheet in Calculator (child of Planner), the modal sheet should pop/close when the physical button is pressed, but instead, it pops Calculator route too.

**Comment by Milad-Akarie** [comment]
@Hrishi1999 `BottomModalSheets` and `Dialogs` use the root navigator by default that's why they can't be seen inside of the nested router's controller.

all you have to do is set `useRootNavigator` to false

```dart
   showModalBottomSheet(
        context: context,
        useRootNavigator: false, // set this to false
...
)
```
Thanks to this issue #647

**Comment by Hrishi1999** [comment]
@Milad-Akarie  `useRootNavigator` is false by default. Doesn't work.

**Comment by AliEasy** [comment]
@Hrishi1999 Did you find anything?!
