### ISSUE TITLE
update analyzer dependency constraints to ^2.0.0

### ISSUE THREAD

**Issue by dokinkon** [Milad-Akarie/auto_route_library#623]
Looks like auto_route is not compatible with the latest "analyzer" library:

```Because auto_route_generator >=0.6.10 depends on analyzer >=0.40.0 <2.0.0 and json_serializable >=5.0.0 depends on analyzer ^2.0.0```

Please consider update this dependency constraints, thanks.

**Comment by JonasKuschel** [comment]
Yes please. I am still on analyzer 1.5.0 because of the following auto route generator error:

QueryParams must be nullable or have default value
```
@QueryParam('location') this.location = '1',
```

**Comment by Bryant-Yang** [comment]
Have to write complex json loader and dumper of class without json_serializable by now, really looking forward to this update.

**Comment by Milad-Akarie** [comment]
On it

**Comment by Milad-Akarie** [comment]
@Bryant-Yang @dokinkon the new flutter version still constrained to meta 1.3.0, analyzer 2.0.0 depends on meta 1.7.0.
you can always override the analyzer dependency in your pubspec.

**Comment by Bryant-Yang** [comment]
@Milad-Akarie thanks. BTW: Is it possible to make the generated router config file more clean and readable?

**Comment by Milad-Akarie** [comment]
@Bryant-Yang could you give an example?

**Comment by Bryant-Yang** [comment]
@Milad-Akarie I mean the generated router file imports all file as alias, it's not a big deal.
![image](https://user-images.githubusercontent.com/1195951/127768510-547b024b-5148-48e8-8788-960ca211111e.png)

**Comment by arafaysaleem** [comment]
> @Bryant-Yang @dokinkon the new flutter version still constrained to meta 1.3.0, analyzer 2.0.0 depends on meta 1.7.0.
> you can always override the analyzer dependency in your pubspec.

how can we do that?

**Comment by Milad-Akarie** [comment]
@arafaysaleem
> how can we do that?

in your pubspec file
```yaml
dependency_overrides:
  analyzer: 1.5.0
```

**Comment by arafaysaleem** [comment]
> @arafaysaleem
> 
> > how can we do that?
> 
> in your pubspec file
> 
> ```yaml
> dependency_overrides:
>   analyzer: 1.5.0
> ```

this throws an error regarding `flutter_test` depending on meta 1.3.0

**Comment by NarHakobyan** [comment]
> ```yaml
> dependency_overrides:
>   analyzer: 1.5.0
> ```

dependency_overrides:
  analyzer: 1.5.0
  meta: 1.3.0

**Comment by NarHakobyan** [comment]
> > @arafaysaleem
> > > how can we do that?
> > 
> > 
> > in your pubspec file
> > ```yaml
> > dependency_overrides:
> >   analyzer: 1.5.0
> > ```
> 
> this throws an error regarding `flutter_test` depending on meta 1.3.0

```yaml
dependency_overrides:
  analyzer: 1.5.0
  meta: 1.3.0
```

**Comment by payam-zahedi** [comment]
Same issue. 
And `dependency overrides` will not work in all situations. Because the analyzer has some breaking changes. I have some conflict with `json_serializable`, `freezed` and `sealed_generator`.

**Comment by Milad-Akarie** [comment]
@payam-zahedi do all of these packages depend on analyzer 2.0.0?

**Comment by Milad-Akarie** [comment]
@NarHakobyan try this 
```yaml
dependency_overrides:
   meta: 1.7.0
```

**Comment by NarHakobyan** [comment]
@Milad-Akarie thanks, but I'll be waiting for new version of auto_route, in new version of analyzer they have breaking changes, so it's not possible to use autoroute with the dependency overrides.

**Comment by Milad-Akarie** [comment]
@NarHakobyan the latest version of FLUTTER still constrained to meta 1.3.0, I can't simply upgrade.

**Comment by NarHakobyan** [comment]
@Milad-Akarie what about of having an alpha branch for it and update it in separate branch? I don't know why, but freezed and json_annotation updated their libs to analizer's new version.

**Comment by Milad-Akarie** [comment]
@NarHakobyan ya I still have no idea how they got it to work with analyzer 2.0. I must be missing something.

**Comment by NarHakobyan** [comment]
@Milad-Akarie this override is working for me, but autoroute gives us an error because of analyzer's breaking change (they removed one of their fields).

```yaml
dependency_overrides:
  analyzer: 2.0.0
  meta: 1.7.0
```

**Comment by payam-zahedi** [comment]
> 
> 
> @payam-zahedi do all of these packages depend on analyzer 2.0.0?

Yes they are. 
for conflict of the `meta` package, I think you should only upgrade the analyzer. 
[json_serialiable](https://github.com/google/json_serializable.dart/blob/cb1e5b5c8d82afcffdd3306cd6a2a369c836cc33/json_serializable/pubspec.yaml#L19) and [freezed](https://github.com/rrousselGit/freezed/blob/728ee08b0596d17d51187c81e3d628968a8de913/packages/freezed/pubspec.yaml#L16)  have kept their meta dependency on `1.3.0` version.

**Comment by Milad-Akarie** [comment]
@NarHakobyan what field?

**Comment by Milad-Akarie** [comment]
@payam-zahedi I'm not directly depending on `meta` package, `analyzer` is.

**Comment by NarHakobyan** [comment]
@Milad-Akarie they removed  FunctionType.element and FunctionType.typeArguments. 😄

**Comment by luqmanhakem** [comment]
Hi @NarHakobyan, seems that I've occur the same issues with the **analyzer 2.0.0**, **json_serializable 5.0.0** and **meta 1.7.0**

Trying to find a workaround for this issue while waiting any patch from @Milad-Akarie  


![image](https://user-images.githubusercontent.com/29282371/128462949-4d785c1b-afd6-4d0f-ab5b-9c6a8d30dc77.png)

**Comment by luqmanhakem** [comment]
#648

**Comment by francipvb** [comment]
Hello,

I think this issue can be closed.

Now the migration must be to analyzer v4.
