### ISSUE TITLE
PageRouteInfo.fromMatch - missed arguments

### ISSUE THREAD

**Issue by furaiev** [Milad-Akarie/auto_route_library#626]
Hello, 
Thank you for your package and work.

I've found that there are missed arguments in the PageRouteInfo.fromMatch factory. Is it a bug or there is a reason for this?

https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/lib/src/route/page_route_info.dart#L106

**Comment by Milad-Akarie** [comment]
@furaiev if you're talking about the "args" property then it's left out for a reason, fromMatch constructor is used with a route is parsed from URL and urls can not have typed arg data.

**Comment by furaiev** [comment]
Make sense, thank you.
