### ISSUE TITLE
Empty query parameter included on URL

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#630]
When adding.a query parameter with `null` value, it includes it on the URL. For example this route:

```
ChatView({
    @PathParam() this.conversationId,
    @QueryParam(messageIdQueryParam) this.messageId,
  });
 ```
 
 When I navigate to it with `messageId` set to `null` this is the URI:  `/123?messageId`
 
 I think it's weird to add it. Since `URI` is expecting a `dynamic` it "works" but base don `Dart` documentation they're really expecting `String` or `Iterable<String>`.
 
We should remove/check for non-string values here:
https://github.com/Milad-Akarie/auto_route_library/blob/6ed33c4f3c491a6510e561e8f448712ace7893c4/auto_route/lib/src/router/parser/route_information_parser.dart#L84

**Comment by Milad-Akarie** [comment]
@Herrera93 make sense, I'll handle it.

**Comment by Herrera93** [comment]
Solved on latest release
