### ISSUE TITLE
Providing same BLoC to different routes

### ISSUE THREAD

**Issue by NachiketaVadera** [Milad-Akarie/auto_route_library#632]
Hey, so [BLoC documentation](https://bloclibrary.dev/#/recipesflutterblocaccess?id=generated-route-access) gives us a cool way to use the same BLoC variable and pass it via `BlocProvider.value()` constructor. How can I achieve the same thing using auto_route?

**Comment by Milad-Akarie** [comment]
@NachiketaVadera you can either pass your bloc as a parameter to then next page then provide it as a value using `AutoRouteWrapper` or put all of the pages that use this bloc in a sub-stack and provide the bloc above all of them.

**Comment by NachiketaVadera** [comment]
@Milad-Akarie Thanks. Put them in a sub-stack how? I can't use bloc as parameter because some of these widgets are nested too deep. And passing around things as parameters doesn't seem scalable.

**Comment by Milad-Akarie** [comment]
by deep nested widgets you mean pages?

**Comment by Milad-Akarie** [comment]
@NachiketaVadera  using AutoRouteWrapper you're providing the value of the passed bloc to the page's context. 
meaning it will still be available to all the widgets inside that page no matter how deep.

**Comment by NachiketaVadera** [comment]
Got it. Thank you.
