### ISSUE TITLE
Incorrect arguments generated when using type List<Color>

### ISSUE THREAD

**Issue by yura2000** [Milad-Akarie/auto_route_library#636]
Hey! I have an issue with code generating. I have an argument of type List<Color> in a screen and when I'm trying to generate `router.gr.dart` it shows: 
![image](https://user-images.githubusercontent.com/11773084/127169682-9691ccb9-9271-47a6-bd80-d123147844ae.png)

How I'm passing an arg:
![image](https://user-images.githubusercontent.com/11773084/127169777-3ef56689-a12b-4ebc-855f-c5d58f713311.png)

How I'm using this screen in the 'router.dart': 
![image](https://user-images.githubusercontent.com/11773084/127169891-cfef19ef-d08c-4bb7-996d-4f7f3b5bc9bc.png)

Probably the `router.gr.dart` should look like this:
![image](https://user-images.githubusercontent.com/11773084/127170088-55919c10-6745-4dac-96d4-e89ed73c806a.png)

**Comment by Milad-Akarie** [comment]
@yura2000 yup, unforntually that's a limiation for me as default values are presented as strings by the analyzer

**Comment by Milad-Akarie** [comment]
closing this for now.
