### ISSUE TITLE
type '_Type' is not a subtype of type 'PageRouteInfo<CategoriesScreen>' in type cast

### ISSUE THREAD

**Issue by kasrasaeed** [Milad-Akarie/auto_route_library#639]
this is the file that i want to generate auto route from it:
@MaterialAutoRouter(
```dart
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: SplashScreen,
    ),
    AutoRoute(
      path: 'mainScreen',
      page: NavBuilderScreen,
      children: [
        AutoRoute(
          path: 'home',
          page: HomeScreen,
          name: 'HomeTab',
        ),
        AutoRoute(
          path: 'profile',
          page: ProfileScreen,
          name: 'ProfileTab',
        ),
        AutoRoute(
          path: 'categories',
          page: CategoriesScreen,
          name: 'categoriesScreen',
        ),
        RedirectRoute(
          path: '*',
          redirectTo: '/',
        ),
      ],
    ),
    RedirectRoute(
      path: '*',
      redirectTo: '/',
    ),
  ],
)
```
class $AppRouter {}
i use below piece if code in onPressed:
AutoRouter.of(context).push<PageRouteInfo>(CategoriesScreen as PageRouteInfo);
then i get this error:
type '_Type' is not a subtype of type 'PageRouteInfo<CategoriesScreen>' in type cast 
why?

**Comment by Milad-Akarie** [comment]
`replaceInRouteName` should only have two segments ( comma separated) 
change this `replaceInRouteName: 'Page,Route,Screen',` to `replaceInRouteName: 'Screen,Route',` which mean replace the word screen with route then your `CategoriesScreen` generated route name will be `CategoriesRoute`
which you can push without casting
`AutoRouter.of(context).push(CategoriesRoute());`

**Comment by kasrasaeed** [comment]
thank  you sir for your note; however i found the solution, its simple, i didn't put parentheses in front of CategoriesScreen.
but there is one problem. i used CategoriesRoute() but the matter is that it dose not exist. kindly check [attachment,]
![CategoriesScreen](https://user-images.githubusercontent.com/67544634/127698486-ab81d1d5-0589-4f11-848b-6ac888da0637.jpg)
