### ISSUE TITLE
context.router.pop to close dialog

### ISSUE THREAD

**Issue by RakaAlrian** [Milad-Akarie/auto_route_library#640]
I have a dialog which I want to prevent user to close it, except user click a button inside the dialog. here is my dialog code look like

```
showDialog(
      context: context!,
      barrierDismissible: false, // prevent user to close dialog using tap outside the dialog
      barrierColor: Colors.black45,
      useSafeArea: true,
      useRootNavigator: true,
      builder: (context) {
        return WillPopScope(
          onWillPop: () async => false, // prevent user to close dialog using default back button 
          child: AlertDialog(
            content: text ?? Text(message!),
            actions: [
              TextButton(
                onPressed: () async {
                  context.router.pop(); // the only way user can close the dialog
                  if (onPressed != null) onPressed();
                },
                child: Text(textButton?.toUpperCase() ?? S.of(context).ok.toUpperCase()),
              ),
            ],
          ),
        );
      },
    );
```
`context.router.pop()` is not working to close dialog, I already tried to use `context.router.root.pop()` but it doesn't work either, any suggestion please

**Comment by Milad-Akarie** [comment]
@RakaAlrian please share you router setup and where are you showing the dialog from?

**Comment by RakaAlrian** [comment]
Here is my main file look like where I setup the router
```
class MainWidgetApp extends StatefulWidget {
  const MainWidgetApp({Key? key}) : super(key: key);

  @override
  _MainWidgetAppState createState() => _MainWidgetAppState();
}

class _MainWidgetAppState extends State<MainWidgetApp> {

  final _appRouter = AppRouter();
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: _appRouter.defaultRouteParser(),
      routerDelegate: _appRouter.delegate(),
      title: 'My App',
      builder: (context, child) {
        return child!;
      },
    );
  }
}
```

And I showing the dialog from bloc listener state changes.

Seems like `onWillPop: () async => false` is the reason why `context.router.pop()` doesn't work, because it works when I remove `WillPopScope` widget, but again I need to prevent user to close dialog from default back button. For now I'm using `Navigator.pop(context)` to close dialog.

**Comment by Milad-Akarie** [comment]
@RakaAlrian I got it, the next build will have a `router.popForced();` method.

**Comment by RakaAlrian** [comment]
Thank you, I really waiting for the new build😁

**Comment by nolandg** [comment]
Does this work in the browser? `showDialog` doesn't modify the URL at all so when I press the browser's back button, it goes to the previous page (it doesn't just close the dialog as it should).

Is this `auto_route`'s fault?
