### ISSUE TITLE
Initial route based on app settings

### ISSUE THREAD

**Issue by slavap** [Milad-Akarie/auto_route_library#644]
I'm trying to find out the proper way to have dynamic initial route.
Currently I'm doing it that way (there is no initial: true in routes definitions):
```dart
class AppRouterEx extends AppRouter {
  AppRouterEx([GlobalKey<NavigatorState>? navigatorKey]) : super(navigatorKey);

  @override
  List<RouteConfig> get routes {
    var lst = super.routes;
    PageRouteInfo landing = NavigFlow.landing;
    lst.removeWhere((e) => e.name == landing.routeName);
    lst.add(RouteConfig(landing.routeName, path: '/'));
    lst.add(RouteConfig('#redirect', path: landing.path, redirectTo: '/', fullMatch: true));
    return lst;
  }
}
```
That way it works, the only issue is that I can see the "full" initial route name in address bar when navigating to that route as: AutoRouter.of(context).push(route), i.e. instead of just /, I see /my-route-name

**>> UPDATE:** improved code even more with adding RouteConfig('#redirect', ...)

The question is - probably there is a better way to implement such functionality ?

**Comment by Milad-Akarie** [comment]
hmmm I can't say I thought about such usecase before, are you saying it's showing full url when you call PUSH? or is it when the initial route is resolved?

**Comment by slavap** [comment]
@Milad-Akarie initial route resolves as /, the only minor cosmetic problem on push. And if I type /my-route-name manually in address bar it resolves to /, thanks to redirect.
