### ISSUE TITLE
Persist router stack when activity is killed by android os

### ISSUE THREAD

**Issue by rokk4** [Milad-Akarie/auto_route_library#646]
Hi, first I want to thank you for this great package, it provides a great value for the ecosystem.

I am currently facing the issue, that (if RAM is low etc.) Android may kill the Flutter Activity. I can  persist the state of my widgets etc. with no problem, but the current route history always is lost and the app starts again at the initial route.

Is there some way to persist the current stack of the router?

**Comment by Milad-Akarie** [comment]
@rokk4 I don't have that much experience in state restoring yet, do you have a suggestion?

**Comment by rokk4** [comment]
@Milad-Akarie sorry for the late reply, you are too quick :D 

For state restoring you serialize the state object and save it to disk and load it back on resume.

So for the router, we just would need to serialize the stack/history and  reload it on resume, right? 
Or is there some more state of the navigation somewhere? 

For this we would need a call during router object construction, which checks for existing state on disk and then loads this as the initial history/stack and another call which saves the stack on every change.

Since the stack is small (is it?) and hive is quite fast I would not suspect a noticeable performance impact. Doing it like hydrated_bloc and using hive as a storage.

**Comment by bounty1342** [comment]
Not sure the DB is the right way to do it, and if it is would consider this : https://objectbox.io/flutter-databases-sqflite-hive-objectbox-and-moor/

Looking at the flutter doc for Scaffold, you'll find :
  /// Restoration ID to save and restore the state of the [Scaffold].
  ///
  /// If it is non-null, the scaffold will persist and restore whether the
  /// [drawer] and [endDrawer] was open or closed.
  ///
  /// The state of this widget is persisted in a [RestorationBucket] claimed
  /// from the surrounding [RestorationScope] using the provided restoration ID.
  ///
  /// See also:
  ///
  ///  * [RestorationManager], which explains how state restoration works in
  ///    Flutter.
  final String? restorationId;

Maybe the easiest and flutteriest way will be to use the [RestorationMixin](https://api.flutter.dev/flutter/widgets/RestorationMixin-mixin.html) 

There is a [RestorableRouteFuture](https://api.flutter.dev/flutter/widgets/RestorableRouteFuture-class.html) that might do just that but seems to old only one route, so [RestorableProperty](https://api.flutter.dev/flutter/widgets/RestorableProperty-class.html) might be necessary.

Hope that give some pointer.

**Comment by Milad-Akarie** [comment]
@rokk4 @bounty1342 does that mean we have to serialize all the argument classes?

**Comment by bounty1342** [comment]
Most certainly, and with both methods... [Freezed](https://pub.dev/packages/freezed) generate JsonSerializable annotation, to get those toJson, fromJson, that's could be inspirational. 😀

**Comment by Lingareddyvinitha** [comment]
@Milad-Akarie any update on router stack implementation in auto_route

**Comment by fnicastri** [comment]
@Milad-Akarie any update/documentation on this?
