### ISSUE TITLE
Nested route and AlertDialog issue

### ISSUE THREAD

**Issue by bounty1342** [Milad-Akarie/auto_route_library#647]
Hi,

The alert Dialog is place directly on the material app, using the back button (Physical button on android device) of the device pop all the nested route before the Alert.

![](https://cdn.discordapp.com/attachments/821361382188253224/873561014652792832/unknown.png)

Is there a way to change this behaviour and close the Alert first ?

**Comment by bounty1342** [comment]
Not an Autoroute issue !

Fix by using useRootNavigator: false, in the AlertDialog.

**Comment by harkairt** [comment]
When I use `useRootNavigator: false` then when a dialog is open the `barrier` (greyed out background) does not cover the bottom navigation bar. 
Is there a solution to that?
