### ISSUE TITLE
specify type on a route?

### ISSUE THREAD

**Issue by jamesdixon** [Milad-Akarie/auto_route_library#65]
Hi again,

Is there a way to specify a type on a specific route?

For example...

```dart
// widget.dart
class UserProfileScreen<T extends User<T>> extends StatelessWidget { ... }
```

```dart
// router.dart
class $Router {
  UserProfileScreen userProfileScreen;
}
```

```dart
// customer.dart
ExtendedNavigator.of(context).pushNamed<Customer>(Routes.userProfileScreen);
```

**Comment by Milad-Akarie** [comment]
Hey @jamesdixon This is a little difficult to active  since there's no way to pass a type parameter  to onGenerateFunction.
also 
The Type parameter in pushNamed is for route result type
`ExtendedNavigator.of(context).pushNamed<T is Result type>(Routes.userProfileScreen);`

**Comment by theweiweiway** [comment]
Closing due to:
- stale issue
