### ISSUE TITLE
AutoTabsScaffold: app bar PreferredSize issue

### ISSUE THREAD

**Issue by shubham030** [Milad-Akarie/auto_route_library#652]
Currently the AutoTabsScaffold takes PreferredSize as kToolbarHeight internally as a result we are not able to modify the app bar height while using the AutoTabsScaffold.

Can we have a fix or if you need me to create a PR let me know.

**Comment by Milad-Akarie** [comment]
Did you try to wrap your Appbar with PreferedSize widget?

**Comment by shubham030** [comment]
Yes I tried that, didn't workout. Then i tried modifying in the library and it works.

**Comment by MichieldeVries** [comment]
This has already been fixed in 
https://github.com/nank1ro/auto_route_library/pull/1/files

Update your package to the latest version. My question is where the changelog is located? I can't seem to find it.

**Comment by shubham030** [comment]
I will surely try it in upcoming weeks for now I am have modified the package and using it locally.
