### ISSUE TITLE
Scope is being reinstantiated

### ISSUE THREAD

**Issue by inulugbek** [Milad-Akarie/auto_route_library#653]
Sample route configuration:

```
 AutoRoute(
      path: '/',
      name: 'HomeRouter',
      page: HomeScope,
      guards: [AuthGuard],
      children: [
        RedirectRoute(path: '', redirectTo: 'home'),
        AutoRoute(
          path: 'home',
          page: HomePage,
          children: [
             RedirectRoute(path: '', redirectTo: 'dashboard'),
             AutoRoute(
                path: 'dashboard',
                page: DashboardPage,
                name: 'DashboardTab',
             ),
             AutoRoute(
                path: 'account',
                page: AccountPage,
               name: 'AccountTab',
             ),
          ],
        ),
        CupertinoRoute(
          path: 'home/account/changeEmail',
          page: ChangeEmailPage,
        ),
      ],
    ),
```
- inside HomeScope in initState method dependencies (blocs, repositories) are created. 
- HomePage is a page with bottom navigation with dashboard and account tabs.

**Problem:**
let's assume user is on HomePage (doesn't matter on which tab). when I want to navigate to ChangeEmailPage it seems like the whole HomeRouter branch is reinstantiated (because HomeScope is reinstantiated i.e. initState is called again and dependencies are also recreated respectvely).  

Is it an expected behaviour? I don't think that HomeScope should be reinstantiated again because it leads to losing the state of the whole branch

**Comment by Milad-Akarie** [comment]
@inulugbek of course it shouldn't, let me envisage this.

**Comment by Milad-Akarie** [comment]
@inulugbek I recreated the above router setup and it worked as expected, HomeScope was not re-initiating, it wasn't even rebuilding.
can you please share a gist to reproduce this?

**Comment by BenevidesLecontes** [comment]
I think I'm having this issue too, my StatefullWidgets initState are being called when i navigate to another route.

**Comment by inulugbek** [comment]
After investigation I have found out, that this behaviour is happening when extensions are used for navigation. i.e.
`context.router.root.pushNamed(...)` - scope is reinstantiated
`AutoRouter.of(context).pushNamed(..)` - scope is not reinstantiated
