### ISSUE TITLE
[Question] How best to support BottomNavigationBar?

### ISSUE THREAD

**Issue by edwardaux** [Milad-Akarie/auto_route_library#66]
I'm just kicking around ideas on the best way to support navigating wtith a `BottomNavigationBar`.

I'm wondering whether it is better to have one root `ExtendedNavigator` that contains the navigation bar, or whether each tab should have its own? 

There's probably no "right" answer, but I'm interested to know if there's a particular pattern you'd start with?

BTW, thanks for a great library. I love it.

**Comment by Milad-Akarie** [comment]
Hey again @edwardaux  I'd go with your first approach, have a root navigator that holds your tabs page then each tab should have it's own. this way you can easily push routes and show your dialogs above your tabs page
unless you're pretty sure that you don't need a root navigator

**Comment by edwardaux** [comment]
he he... as it turns out, I don't (currently) need a root navigator, so I'm currently just creating a new `ExtendedNavigator` for each of my tabs. 

It is working really well ... with one small wrinkle.  Because of the way that Flutter route names work, if they contain a leading slash, then Flutter assumes they are a "deeplink" and tries to make sure that there are screens pushed for all the intermediate routes. eg. if I have a route named `/home/account`, when this route gets pushed, Flutter will first make sure theres a `/` screen in the stack, followed by `/home`, and then finally followed by `/home/account`.

This convention doesn't work very well, though, in the context of tabbed navigation because I can't have a different `/` route for each tab.

The good news is that we can stop Flutter from treating the routes as deeplinks by just not using a leading slash. The bad news is that auto_route is hard-coded to generate link names with a leading slash.

I can fix this by making sure I explicitly annotate all my routes to make sure I specify the name without a slash. It is a bit painful in that it is a heap of boilerplate plus easy to forget. eg.

```
@MaterialAutoRouter()
class $Router {
  @MaterialRoute(name: 'account')
  AccountScreen accountScreen;
}
```

I'll raise another issue to see if we could do something like `MaterialAutoRouter(leadingSlashes: false)`

Thanks for your feedback on the original question though.

**Comment by Milad-Akarie** [comment]
@edwardaux  sounds good. I'll look into it.
