### ISSUE TITLE
[Documentation] Tabs Navigation

### ISSUE THREAD

**Issue by abahnj** [Milad-Akarie/auto_route_library#663]
I think the documentation around tabs navigation needs to be improved because it wasn't apparent to me that each tab need to be instatiated with an EmptyRoutePage to allow access to child navigation of the tab children.

**Comment by k-s-t-i** [comment]
Can I get a code snippet? I am stuck on this right now. @abahnj

**Comment by abahnj** [comment]
https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing
