### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by Vinzent03** [Milad-Akarie/auto_route_library#668]
My routing configuration:
```dart
@AdaptiveAutoRouter(
  replaceInRouteName: "Page,Route",
  routes: [
    AdaptiveRoute(
      page: Home,
      initial: true,
      guards: [AuthGuard],
      name: "HomeRoute",
      path: "/app",
      children: [
        AdaptiveRoute(page: OverviewPage),
        AdaptiveRoute(page: MarketPlace, name: "MarketplaceRoute"),
        AdaptiveRoute(
            page: SettingsView, name: "SettingsRoute", path: "settings"),
      ],
    ),
    AdaptiveRoute(
      page: EmptySettings,
      path: "/settings",
      children: [
        AdaptiveRoute(page: EditProfilePage, initial: true),
      ],
    ),
  ],
)
class $AppRouter {}
```
My `Home` widget is a `AutoTabsRouter` with its children listed above as tabs. When I push in `SettingsView` via
```dart
context.router.push(EmptySettings(children: [EditProfileRoute()]))
```
to `EditProfilePage` I don't have a back button in the top left corner. Even with the `AutoBackButton` widget leading in the `AppBar`.
Is this the expected behavior? Or is this caused, because the path goes back and forth? Or because of the `AutoTabsRouter`?

`EmptySettings` is just a Provider wrapper around `AutoRouter()`.

**Comment by Milad-Akarie** [comment]
Show me EmptySettings page please

**Comment by Vinzent03** [comment]
Thanks for the quick answer!
```dart
class EmptySettings extends StatelessWidget {
  const EmptySettings({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) =>
          Controller(di<GetProfile>(), di<SaveProfile>(), di<SignOut>()),
      child: const AutoRouter(),
    );
  }
}
```

**Comment by Milad-Akarie** [comment]
You need to wrap your change notifer with a scaffold that has an AppBar with AutoBackButton as leading widget

**Comment by Vinzent03** [comment]
Cant live the scaffold in the children? How can I stack multiple pages together then? If I have Widget in a  children in a children wouldn't I have two AppBars?

**Comment by Milad-Akarie** [comment]
Hmm right now EmptyProfileRoute is the only entry in the substack so normally it can't be popped that's why it doesn't show the BackButton but your use case is pretty valid

For now you can make your own  back botton and have it appear if 
(router.canPopSelfOrChildern || (router.parent?.canPopSelfOrChilder == true))

I can't test this right now, let me know if it worked for you

**Comment by Vinzent03** [comment]
Yeah, that works, thanks! But now I have the next issue. For cupertino I use `CupertinoNavigationBarBackButton` as widget, but that's too far right, when used as leading in `CupertinoNavigationBar`, but that's not the issue of this package.
For those that are reading this issue later, it's:
```dart
if (scope.controller.canPopSelfOrChildren || scope.controller.parent()?.canPopSelfOrChildren == true) {
```
