### ISSUE TITLE
How to do for when use auto_route don't rebuild the other widgets(pages) in stack?

### ISSUE THREAD

**Issue by polpenyarrojaNik** [Milad-Akarie/auto_route_library#671]
Hi there!

I have implemented Navigation 2.0 with auto_route package and when I push or pop a page, all the widgets in the widget tree are rebuilt and I lose the state of a form because formKey changes.
Also, when I don't use auto_route and use a Navigator, this doesn't happen

How can I make that when I push or pop elements in the widget tree are not rebuilt when using auto_route?

**Comment by for-meng** [comment]
have same problem!
