### ISSUE TITLE
Compile failure: routerReportsNewRouteInformation - type not provided

### ISSUE THREAD

**Issue by jcamorgan** [Milad-Akarie/auto_route_library#672]
Flutter 2.6.0-1.0.pre.81
auto_route: ^2.3.0
auto_route_generator: ^2.3.0

The app will not compile due to the required parameter 'type' in routerReportsNewRouteInformation not being provided.

_Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
../../../../../.pub-cache/hosted/pub.dartlang.org/auto_route-2.3.0/lib/src/router/widgets/auto_router_delegate.dart:43:43: Error: Required named parameter 'type' must be provided.
        ?.routerReportsNewRouteInformation(
                                          ^
Failed to compile application.
Exited (sigterm)_

**class AutoRouterDelegate lines 40-48**
```
  static reportUrlChanged(BuildContext context, String url) {
    Router.of(context)
        .routeInformationProvider
        ?.routerReportsNewRouteInformation(
          RouteInformation(
            location: url,
          ),
        );
  }
```

**Comment by PlugFox** [comment]
#659
