### ISSUE TITLE
Error in app_router.gr when using Default Value in Page

### ISSUE THREAD

**Issue by schlotterich** [Milad-Akarie/auto_route_library#677]
I always get an error when I try to call a route that has an default value... Is there any way to load Default Values in the constructor when using AutoRoute or is that not possible?

**Page:**
```
class Page extends ConsumerWidget {
  final String title;
  final IconData icon;


 const Page(this.primaryButtonFunction, this.secondaryButtonText,
      {this.title = 'test',
      required this.icon,});
```

**AutoRoute Definition:**
`
AutoRoute(path: 'errorPage', page: ErrorPage)
`

**Error:**
```
lib/routes/app_router.gr.dart:278:14: Error: The parameter 'title' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
      String title,
```

**Comment by mirkancal** [comment]
I have the same problem, when I provide default value, I get the same warning on generated file. Right now I use build_runner when I don't have the default value and using this parameter as required. After that I edit it back to default value version.

**Comment by Milad-Akarie** [comment]
@schlotterich @mirkancal are you overriding analyzer package?

**Comment by mirkancal** [comment]
@Milad-Akarie No, I'm manually editing the generated file everytime I run the build_runner.
