### ISSUE TITLE
Generate platform-specific routes

### ISSUE THREAD

**Issue by edwardaux** [Milad-Akarie/auto_route_library#68]
I see that we can pass a specific annotation to generate either an explicit `MaterialAutoRouter` or a `CupertinoAutoRouter`, however, what would be nice is if there was an additional annotation called `PlatformSpecificAutoRouter` which would create a `CupertinoPageRoute` or a `MaterialPageRoute` at runtime depending on whether we're running on iOS or Android.

I'm happy to create a PR, but wanted to check and see if this is a) something you're interested in, and b) is how you'd approach it.

**Comment by Milad-Akarie** [comment]
Hey @edwardaux I though about it when I first started working on the lib but, I later figured out that MaterialRoute is actually an adaptive route, meaning it behaves like a CupertinoRoute on IOS platform and I'm guessing the same goes for all other supposed platforms.
do you still think there's a need for an adaptive router?

**Comment by edwardaux** [comment]
hi @Milad-Akarie ... well, that's what the documentation says ... in reality, though, it isn't what they actually do.. ha ha 😂  

A video would be better, but hopefully these couple of screenshots will help illustrate the difference. Here's what it looks like on iOS:

Initial screen | Cupertino Route | Material Route
:---------:|:-----------:|:-----------:
This is what the original screen looks like before the transition. The other two show what happens when you transition by pressing the Details button | When using a CupertinoRoute, as the new screen slides across, the screen underneath gets pushed across using a parallax effect | When using a MaterialRoute, the new screen just slides straight over the top of the bottom screen
![original](https://user-images.githubusercontent.com/1574429/79618100-852c6c00-814c-11ea-8429-b101640a64ac.png) | ![cupertino](https://user-images.githubusercontent.com/1574429/79618113-88bff300-814c-11ea-85f4-0586487e9547.png) | ![material](https://user-images.githubusercontent.com/1574429/79618119-8b224d00-814c-11ea-8dec-b2694a4fa637.png)

I know it doesn't look massively different, but iOS users will definitely notice and feel like something is wrong (even if they can't put their finger on it).

FWIW, on Android, it behaves "normally" (or, at least, how I'd expect):
* Using CupertinoRoute - Has the same parallax effect as on iOS
* Using MaterialRoute - Slides up from the bottom

So, where this leaves us is that if we truly want iOS transitions on iOS, using CupertinoRoutes is the only choice.  However, if we hard-code them to CupertinoRoute, this will feel equally as weird for Android users... hence the idea of generating code that chooses at runtime depending on the platform.

**Comment by Milad-Akarie** [comment]
@edwardaux Thanks a good observation! I haven't noticed that before, Thanks for your hard work.. I'll be working on that.

**Comment by mxkacsa** [comment]
Yes it's a very important feature.
I think this is the best routing solution for flutter, but without this feature I don't know how can I use this library in my cross platform application.

**Comment by Milad-Akarie** [comment]
@edwardaux  @mxkacsa  Check out AdaptiveAutoRouter and AdaptiveRoute in 
auto_route: 0.4.5
auto_route_generator: 0.4.7
Thanks for your patience!

**Comment by edwardaux** [comment]
Works perfectly @Milad-Akarie (including the leading slash change). Thanks so much for the quick changes (and a great library) 🎉
