### ISSUE TITLE
Navigate to url when from address bar

### ISSUE THREAD

**Issue by Slexom** [Milad-Akarie/auto_route_library#681]
I'd like to navigate to correct route when write the url in the address bar and press enter.
After some tests, and lots of `cannot resolve initial route`, I've found a possible solution(the _condition_ variable is a just placeholder)
```dart
import 'package:auto_route/auto_route.dart';
import 'package:dynamic_routes/routes.gr.dart';
import 'package:flutter/material.dart';

class PageWrapper extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    final condition = true;
    return Scaffold(
      body: AutoRouter.declarative(
        routes: (context) {
          return [
            if (condition) context.router.current.route.children!.first.toRoute() else HomeRoute(),
          ];
        },
      ),
    );
  }
}

```

_routes.dart_
```dart
import 'package:auto_route/auto_route.dart';
import 'package:auto_route/annotations.dart';
import 'package:dynamic_routes/src/home_screen.dart';
import 'package:dynamic_routes/src/item_screen.dart';
import 'package:dynamic_routes/src/login_screen.dart';
import 'package:dynamic_routes/src/wrapper.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(
      initial: true,
      page: PageWrapper,
      path: '/',
      children: [
        AutoRoute(page: LoginScreen, path: "login"),
        AutoRoute(page: HomeScreen, path: "home"),
        AutoRoute(page: ItemScreen, path: "item/:id"),
      ],
    ),
  ],
)
class $AppRouter {}
```
The screens just print their path.
If I type _/item/123_ on the address bar and press enter it correctly show the ItemScreen with the id printed in the middle. 
But, I think this solution could not be the correct one. Is there a better way to achieve this result?

**Comment by Milad-Akarie** [comment]
@Slexom When you using declarative approach navigating using the url bar will trigger the onNavigate callBack and pass the pre-matched routes but it's up to whether or not to include the routes in your declarative stack. 
p.s onNavigate is also called when router.navigate() is triggered on a declarative router

```dart
class PageWrapper extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AutoRouter.declarative(
       onNavigate: (matches, initial){
          // matches are the parsed routes from url
          }
        routes: (context) {
          // ....
        },
      ),
    );
  }
}

```

**Comment by Slexom** [comment]
@Milad-Akarie Thank you so much for the answer. I've tried at first for a non-declarative way, but I was getting the following error
```
Error: Can not resolve initial route
    at Object.throw_ [as throw] (http://localhost:59358/dart_sdk.js:5041:11)
    at auto_router_delegate.AutoRouterDelegate.new.setInitialRoutePath (http://localhost:59358/packages/auto_route/src/router/widgets/auto_back_button.dart.lib.js:3068:19)
    at _RootZone.runUnary (http://localhost:59358/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:59358/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:59358/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:59358/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:59358/dart_sdk.js:32943:23)
    at http://localhost:59358/dart_sdk.js:32884:39
    at SynchronousFuture.new.then (http://localhost:59358/packages/flutter/src/foundation/synchronous_future.dart.lib.js:36:22)
    at _Future.new.[_chainForeignFuture] (http://localhost:59358/dart_sdk.js:32880:18)
    at Function._propagateToListeners (http://localhost:59358/dart_sdk.js:33116:44)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59358/dart_sdk.js:32824:27)
    at Object._microtaskLoop (http://localhost:59358/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:59358/dart_sdk.js:37532:13)
    at http://localhost:59358/dart_sdk.js:33303:9
```

with the following setup
_routes.dart_
```dart
import 'package:auto_route/auto_route.dart';
import 'package:auto_route/annotations.dart';
import 'package:dynamic_routes/src/home_screen.dart';
import 'package:dynamic_routes/src/item_screen.dart';
import 'package:dynamic_routes/src/login_screen.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomeScreen, path: '/'),
    AutoRoute(page: LoginScreen, path: 'login'),
    AutoRoute(page: ItemScreen, path: 'item/:id'),
  ],
)
class $AppRouter {}

```

_main.dart_
```dart
import 'package:dynamic_routes/routes.gr.dart';
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:auto_route/auto_route.dart';

void main() {
  setUrlStrategy(PathUrlStrategy());
  runApp(App());
}

class App extends StatelessWidget {
  final _appRouter = AppRouter();

  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: AutoRouterDelegate(_appRouter),
      routeInformationParser: _appRouter.defaultRouteParser(includePrefixMatches: true),
    );
  }
}
```
Fort that reason I've tried the declarative way.

Extra info
flutter **doctor**
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Versione 10.0.19042.1165], locale it-IT)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bcarm\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\bcarm\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\bcarm\AppData\Local\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\bcarm\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

```

**Comment by Milad-Akarie** [comment]
@Slexom is this the full router setup? 

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(page: HomeScreen, path: '/'),
    AutoRoute(page: LoginScreen, path: 'login'),
    AutoRoute(page: ItemScreen, path: 'item/:id'),
  ],
)
class $AppRouter {}

```
Because you can't define root-routes without a forward slash
'login' should be '/login'
'item/:id' shouldbe '/item:id'
the generator should throw, are you sure you re-ran the generator after your last changes?

**Comment by stefannovak** [comment]
> @Slexom is this the full router setup?
> 
> ```dart
> @MaterialAutoRouter(
>   replaceInRouteName: 'Screen,Route',
>   routes: <AutoRoute>[
>     AutoRoute(page: HomeScreen, path: '/'),
>     AutoRoute(page: LoginScreen, path: 'login'),
>     AutoRoute(page: ItemScreen, path: 'item/:id'),
>   ],
> )
> class $AppRouter {}
> ```
> 
> Because you can't define root-routes without a forward slash
> 'login' should be '/login'
> 'item/:id' should be '/item:id'
> the generator should throw, are you sure you re-ran the generator after your last changes?

I didn't realise this. I also have paths such as "sign-in" and "pin-code" without any errors

**Comment by Slexom** [comment]
> @Slexom is this the full router setup?
> 
> ```dart
> @MaterialAutoRouter(
>   replaceInRouteName: 'Screen,Route',
>   routes: <AutoRoute>[
>     AutoRoute(page: HomeScreen, path: '/'),
>     AutoRoute(page: LoginScreen, path: 'login'),
>     AutoRoute(page: ItemScreen, path: 'item/:id'),
>   ],
> )
> class $AppRouter {}
> ```
> 
> Because you can't define root-routes without a forward slash
> 'login' should be '/login'
> 'item/:id' should be '/item:id'
> the generator should throw, are you sure you re-ran the generator after your last changes?

I use `watch` as argument for the build_runner, so it keep rebuilding on changes.

**Comment by stefannovak** [comment]
> > @Slexom is this the full router setup?
> > ```dart
> > @MaterialAutoRouter(
> >   replaceInRouteName: 'Screen,Route',
> >   routes: <AutoRoute>[
> >     AutoRoute(page: HomeScreen, path: '/'),
> >     AutoRoute(page: LoginScreen, path: 'login'),
> >     AutoRoute(page: ItemScreen, path: 'item/:id'),
> >   ],
> > )
> > class $AppRouter {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Because you can't define root-routes without a forward slash
> > 'login' should be '/login'
> > 'item/:id' should be '/item:id'
> > the generator should throw, are you sure you re-ran the generator after your last changes?
> 
> I didn't realise this. I also have paths such as "sign-in" and "pin-code" without any errors

Wanted to tag onto this, was doing a lot of AutoRoute work this week. We had a problem where every time we wanted write the address for the web, such as 'localhost:5000/sign-in', the app would crash with 'Could not resolve initial route'. Fixed it by giving all top level route paths a forward slash to start with.

'profile' became '/profile' for example, and it worked. Took a long time to figure out until I found this post.
