### ISSUE TITLE
pushPath vs pushNamed

### ISSUE THREAD

**Issue by pxsanghyo** [Milad-Akarie/auto_route_library#682]
I recently upgraded from `1.0.2` to `2.3.0` where `pushPath` was deprecated for `pushNamed` but they don't behave the same.

I used `pushPath` for deep links like:

```dart
// `token.data.uri.resource` is `/pass?apiKey=123&continueUrl=123`
_router.pushPath(
  token.data.uri.resource,
  includePrefixMatches: true,
);
```

Changing to `pushNamed` breaks app saying cannot navigate to path.

I got it to work by removing the preceding `/` from the link but is that the case all the time now?

**Comment by Milad-Akarie** [comment]
@pxsanghyo is this a root router?  also is your root route '/' marked as fullMatch?

**Comment by pxsanghyo** [comment]
@Milad-Akarie yeah this is root router, I have only root router, which looks like this:

```dart
@AdaptiveAutoRouter(
  routes: [
    AdaptiveRoute(
      initial: true,
      fullMatch: true,
      page: Home,
    ),
  ],
)
```

**Comment by Milad-Akarie** [comment]
@pxsanghyo using full match is what's causing the error, if you've used it to avoid pushing the homePage( root page at '/') then you may remove it and use router.navigateNamed() instead, 
navigate/navigateNamed will only update existing routes and not push them.

**Comment by pxsanghyo** [comment]
@Milad-Akarie Thank! I'll try that out.
