### ISSUE TITLE
Hot reload makes web app to go to initial page

### ISSUE THREAD

**Issue by davidcz95** [Milad-Akarie/auto_route_library#684]
Hello,
I know that there are at least 3 issues related with this problem but I tried all the solutions suggested in them and still every hot reload makes my web app go to initial page which is a bit annoying.

Here is my app class:

```
final appRouter = AppRouter();

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      theme: ThemeData(
        appBarTheme: const AppBarTheme(color: Color(0xFF13B9FF)),
        colorScheme: ColorScheme.fromSwatch(
          accentColor: const Color(0xFF13B9FF),
        ),
      ),
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      routeInformationParser: appRouter.defaultRouteParser(),
      routerDelegate: appRouter.delegate(),
      debugShowCheckedModeBanner: false,
    );
  }
}
```

**Comment by Milad-Akarie** [comment]
@davidcz95 how do I reproduce this? do you have a gist or something?

**Comment by davidcz95** [comment]
hi @Milad-Akarie you can clone it from my github directly, just started it so I have nothing to hide 😂 
https://github.com/davidcz95/elektryk_website

**Comment by Milad-Akarie** [comment]
@davidcz95 I just tested with empty flutter App and it restarted when I hit the hot-reload button ( state was lost) , not sure if it's a flutter issue or the flutter dev tool.

**Comment by alvinthen** [comment]
On the `generate: true`? It's the new recommended method to do localization

Step 2 in https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages

**Comment by fdelucchijr** [comment]
Interesting, same error here, someone has a clue?

**Comment by Milad-Akarie** [comment]
@fdelucchijr you're not initializing the router inside of the build method are you?

**Comment by fdelucchijr** [comment]
> @fdelucchijr you're not initializing the router inside of the build method are you?

Nop, I initialize the router in the initState, but I also tried to add it as a class variable in the Stateful Widget. Doesnt seems to work, and only happen in Flutter Web.

**Comment by mregandla** [comment]
Facing the same issue. Hot reload is not working for Flutter web. The app is restarting and the state is lost. But no issues with the android emulator.

**Comment by Vinzent03** [comment]
@mregandla That's because of Flutter web. See the [faq](https://docs.flutter.dev/development/platform-integration/web#does-hot-reload-work-with-a-web-app). That's not because of this plugin.
