### ISSUE TITLE
Unable to doubly nest routers with autotabscaffold

### ISSUE THREAD

**Issue by Giulio-Grassi** [Milad-Akarie/auto_route_library#685]
I can't manage to get the notification routes to work for some reason. Is there a limit to how many nested routers there can be? I am not really sure what else I could be doing wrong...
i have tried to comment out the message route in the autoTabsScaffold and switch it with the Notification router and that works fine,(navbar.dart line 9)  but when i do try with the current setup it doesn't work 

Please see attached the following gist
https://gist.github.com/Giulio-Grassi/cf989061079ef9f9e8d97e133c195ae3

Also, two images of the app and notifications for reference:

![image](https://user-images.githubusercontent.com/57862094/132237724-994f202f-c62f-4379-8942-b5f0be87b5e7.png)
![image](https://user-images.githubusercontent.com/57862094/132237746-853b6589-22f7-4945-968d-f7688bc67af6.png)

**Comment by Milad-Akarie** [comment]
@Giulio-Grassi it seems to me that the sub-stack in which notification route exists is used for tab-routes, are you trying to push it to the tab-routes stack?
