### ISSUE TITLE
iOS and Android pop function works differently 

### ISSUE THREAD

**Issue by irizzka** [Milad-Akarie/auto_route_library#686]
https://youtu.be/eI33NRqd2Y8

Used context.router.push() for navigation to the next page

**Comment by Milad-Akarie** [comment]
@irizzka turns out it's a known issue, I guess back gesture was not made with nesting in mind.  
Please confirm the fix and close
```yaml
auto_route v2.3.2
auto_route_generator v2.3.2
```
