### ISSUE TITLE
[Feat] Adding option to annotate the actual page/widget

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/auto_route_library#694]
Hello Auto Routers,
There's some neat feature I've been thinking to add to auto_route for a while now and I guess I just need a little motivation to get it done...

Simply put, instead of putting all the routes in one class we annotate the actual widget with `@AutoRoute()` which by the way was the very first approach for auto_route but it had some generation issues back then.

so to annotate the routes we use the same `AutoRoute()` class we've been working with before, it should throw or print a warning  if properties like `page` or `children` is used.

```dart
@AutoRoute(initial: true)
class MainTabsPage extends StatelessWidget {...}

@AutoRoute(path: '/login')
class LoginPage extends StatelessWidget {...}
```
The real challenge here is 'Nested Routes', I've seen a similar  web lib use a parent layout annotation  and I guess it's not so bad, so to assign a route to a parent you'd add a `@Parent(<Type>)` annotation and specific that parent, specifying a parent from a path should be possible as well. 

```dart
@Parent(MainTabsPage) // specifying a parent by type
@AutoRoute(path: 'home')
class HomeTab extends StatelessWidget {...}

@Parent.path('/') //specifying a parent by path
@AutoRoute(path: 'settings')
class SettingsTab extends StatelessWidget{...}
```
instead of creating the parent annotation every time we could assign it to a const variable and give it a descriptive name then use it to annotate child routes

```dart
const mainTabRoute = Parent(MainTabsPage);

@mainTabRoute
@AutoRoute(path: 'profile')
class ProfileTab extends StatelessWidget{...}
```
The generated router should be outputted to a default path e.g `lib/generated/router.dart ` and there should be an option to change that, plus  the generated router name which can be defaulted to 'AppRouter'.

I'd love to hear your thoughts about this, plus any challenges you might foresee.

**Comment by NachiketaVadera** [comment]
This seems like a great idea. The only thing that I'd miss about the current approach is that I had the whole route hierarchy laid out in a single file. This made it really easy to get people (developers and otherwise) up to speed with how the app's navigation is set up.

**Comment by Milad-Akarie** [comment]
@NachiketaVadera That's a good point, I guess a site map can be generated as header or something.
