### ISSUE TITLE
Need to namespace `Routes` for each Router

### ISSUE THREAD

**Issue by ozburo** [Milad-Akarie/auto_route_library#70]
I like to use multiple routers and push routes by name, something like:

```
MyRouter.navigator.pushNamed(Routes.myPage);
```

However since all routers use `Routes` to define their routes we get a name conflict when we import more than one router.

I tried to live w/ this and use `generateNavigationHelperExtension` so I didn't need to use Routes directly but this falls short when I need something more complex than `pushNamed`, i.e. `pushNamedAndRemoveUntil`

Can we get these `Routes` namespaced per router, i.e. `MyRouterRoutes`?

Also I see that for generating `generateNavigationHelperExtension` you are using an `extension` which doesn't seem to offer any type-safety; I can use any named route on any router.

Thanks! 👍

**Comment by Milad-Akarie** [comment]
Hey, @ozburo I was ignoring this until something said something lol 
Do you have any suggestion other than MyRouterRoutes? because that's a bit long. "RouterRoutes" sounds weird.
How about passing the routes class names to the AutoRouter?
something like
`MaterialAutoRouter(routesClassName:"NestedRoutes")`

for now you could use an import alias to import your nested routers 
```dart
import 'package:example/nested_router.gr.dart' as nestedRouter;
```
then
`nestedRouter.Router... `

**Comment by ozburo** [comment]
> Hey, @ozburo I was ignoring this until something said something lol

I'm glad I'm the one to bring this to your attention 🥰 

> Do you have any suggestion other than MyRouterRoutes? because that's a bit long. "RouterRoutes" sounds weird.

Yes, you're right that *is* a bit long. I was prepared to live with that since we're using code-generation...

> How about passing the routes class names to the AutoRouter?
> something like
> `MaterialAutoRouter(routesClassName:"NestedRoutes")`

...however, this is a good idea 👍  For those that want nicer class names we can just assign it!

I guess if we're going to do that we could just leave the default as `Routes` as it is now, that way
it wouldn't bug others that just use one router etc.

> for now you could use an import alias to import your nested routers
> 
> ```dart
> import 'package:example/nested_router.gr.dart' as nestedRouter;
> ```
> 
> then
> `nestedRouter.Router...`

That's exactly what I'm doing! 😄 

Thanks for the quick reply and really useful package!

**Comment by Milad-Akarie** [comment]
Hey @ozburo! Implemented in 
auto_route: 0.4.5
auto_route_generator: 0.4.7
Check it out!

**Comment by ozburo** [comment]
Perfecto! Thanks so much 👍
