### ISSUE TITLE
Doesn't build on FLutter channel master

### ISSUE THREAD

**Issue by abahnj** [Milad-Akarie/auto_route_library#700]
Running Gradle task 'assembleDevelopmentDebug'...
../../.pub-cache/hosted/pub.dartlang.org/auto_route-2.3.2/lib/src/router/widgets/auto_router_delegate.dart:43:43: Error: Required named parameter 'type' must be provided.
        ?.routerReportsNewRouteInformation(
                                          ^

The build fails with the above error

**Comment by Ruzo** [comment]
#659

**Comment by matekdk** [comment]
Same behavior on the current beta channel. Works fine on stable.

**Comment by Milad-Akarie** [comment]
@abahnj @matekdk I can't update this in master unless it's on stable, maybe the best thing to do here is to fork the package and update your selfs? or maybe I can make the changes in a different branch?

**Comment by matekdk** [comment]
@Milad-Akarie : Thanks for quick response. This is a very cool library and you guys do a lot - so maybe the least amount of work is to describe what the workaround around this bug is. If its only about adding additional argument ?

**Comment by Ruzo** [comment]
https://github.com/Milad-Akarie/auto_route_library/issues/659#issuecomment-906828351

**Comment by Vinzent03** [comment]
The issue is on Flutter beta track now. Some advice to fix it locally would be great.

**Comment by k-s-t-i** [comment]
Bump, having issue on beta as well

**Comment by PlugFox** [comment]
Same issue here, on Beta Channel
