### ISSUE TITLE
Push a widget instead of a route

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#702]
Hey,
I can't see an option to push a widget which is not defined in the routes list.
The use-case for this is when you want to show the user a page which should not have a url (like a modal).
Are there plans to add this functionality? 
I currently use Navigator.of(context).push() to do this, but I need to push without context and I also prefer to use your package for routing logic.

Please consider adding this,
Thanks

**Comment by Milad-Akarie** [comment]
Hmm I don't know about this one, how about passing the widget as ab argument to a general route that displays it?

If i add an api for this I'm gonna gave to handle different route transactions and stuff.

**Comment by naamapps** [comment]
Hey @Milad-Akarie ,
I understand what you mean, but this General route will also have a url.. Everyone with a link will be able to enter this route and face exceptions because no widget was given. 

Right now I added all my widgets that do not need routes to the root, but this is not desirable because of the same reason, everyone can access those routes with a link.

My thoughts on how to implement:
Maybe implementing this only for root pushes will make it easier? I mean, my use case is for root pushes of modal views, so nested pushes can be ignored. 

I think this feature will be really good for this package. 
Thanks

**Comment by naamapps** [comment]
@Milad-Akarie Another thing to note is that currently dialogs and bottom sheets doesn't play nicely with nested routes when pushing them with root navigator `Navigator.of(context, rootNavigator: true).push(...)`
So if the feature of pushing a widget is added we could push a dialog like this:
```
router.push(
  DialogRoute(
        context: context,
        builder: (context) => SomeWidget(),
      ),
);
```

Also when I say pushing a widget I really mean pushing a route with a builder (like how you push with the normal Navigator.of(context)).

Right now I'm pushing a dialog by adding a custom route, 
This works, but it seems like a workaround for me because I really don't need paths for dialogs and also it adds complexity in my opinion because most of the developers won't think to do something like this in the first place (like I didn't think of it until I saw an issue with a similar example)
```
class AutoDialogRoute<T> extends CustomRoute<T> {
  const AutoDialogRoute({
    required Type page,
    String? path,
    String? name,
  }) : super(
          page: page,
          name: name,
          path: path,
          customRouteBuilder: dialogRouteBuilder,
          barrierDismissible: true,
        );

  // must be static and public
  static Route<T> dialogRouteBuilder<T>(
    BuildContext context,
    Widget child,
    CustomPage<T> page,
  ) {
    if (platform(context) == PlatformTarget.android) {
      return DialogRoute<T>(
        context: context,
        settings: page,
        builder: (context) => child,
      );
    } else {
      return CupertinoDialogRoute<T>(
        context: context,
        settings: page,
        builder: (context) => child,
      );
    }
  }
}
```

I really hope you consider adding this,
Thanks!

**Comment by Milad-Akarie** [comment]
@naamapps I've been considering this for a while now ( pushing paged but pathless modals 'dialogs/sheets' ) it's not as straightforward as it seems but I'm willing to give it a try.

**Comment by naamapps** [comment]
@Milad-Akarie Really nice to see your detication to this package. Appreciate it 👍
For now I found a workaround other than the one I wrote above (an empty route that pushes a dialog/sheet with root navigator false - this work better than expected, but it's very hacky).. 
Looking forward seeing your solution. 

Another thing I had a question about, why when pushing a dialog with root navigator true, and tapping the android back button pops the underlying route instead of popping the dialog? Why auto route can't know that there is a root page that is currently visible? 
And if I put the solution I wrote in my other comment in the root and push with autoRouter instead of navigator it will know to pop the dialog. 
Just wanted to know the reason behind this..

**Comment by Milad-Akarie** [comment]
@naamapps right now auto_route calculates the topMost router based on it's own pages stack, PAGELESS dialogs/modals are pushed directly by the native navigator so auto_route doesn't know that a new entry was added.

**Comment by Milad-Akarie** [comment]
I haven't put enough work into this so I don't know if can be fixed yet.

**Comment by naamapps** [comment]
Oh got it.
But how does the back button does work when not using the root navigator?
Flutter's navigator adds to the stack of autoRoute?

**Comment by Milad-Akarie** [comment]
@naamapps it's the other way around actually, auto_route adds to the stack of navigator, I've done some works and now dialogs and bottom sheet play nicely with auto_route. also I've added a way to push an unrouteable widget -> router.pushWidget() 
I'm gonna have to do some tests and clean up before I push the next release so stay tuned

**Comment by naamapps** [comment]
Wow nice, waiting for this!
So after the update we should be able to use root navigator to push dialogs/sheets and the android back button will be able pop the dialog/sheet instead of the nested routes?

And about pushWidget, Is it going to work with nested routes or just the root?
For example, pushing a widget in nested routes will not hide the bottom navigation bar, but if pushing with the rootRouter (without context) it will push to the root.

Well done @Milad-Akarie,
Appreciate your work 👍

**Comment by Milad-Akarie** [comment]
@naamapps yes and yes, pushWidget will push to whatever router you're calling from
```dart
router.pushWidget() // will push to current
router.parentAsStackRouter?.pushWidget() // will push to parent
router.root.pushWidget() // will push too root
```

**Comment by Milad-Akarie** [comment]
@naamapps implementation added in v2.4.1

**Comment by naamapps** [comment]
@Milad-Akarie 
Everything works really well - dialogs, sheets and widget pushes.
One thing I don't understand is what if I want to call pushWidget with Cupertino route with fullscreenDialog set to true.
I currently can't decide those parameters. 
If I write 
```
router.pushWidget(CupertinoPageRoute(
      builder: (context) => SomeWidget(), fullscreenDialog: true,);
```

It shows this error 
`The argument type 'CupertinoPageRoute<dynamic>' can't be assigned to the parameter type 'Widget'.`

Do I need to do this with Navigator.of(context)?
If so, it really makes router.pushWidget redundant unfortunately. 

Nevertheless, thank you for your help and support 💯

**Comment by Milad-Akarie** [comment]
@naamapps guess I'm gonna have to add another method `pushNativeRoute()` because the current one get's the route type from the theme.

**Comment by Milad-Akarie** [comment]
@naamapps pushNativeRoute was implemented in v2.4.2

**Comment by naamapps** [comment]
Wow that was quick!
I'll check it right away :)
Thanks

**Comment by naamapps** [comment]
@Milad-Akarie,
Works good.
Sorry for the inconvenience but I found an issue,
When pushing a widget/native route, the router the pushed the widget is not marked as canPopSelfOrChildren.
I have a custom logic to my back button all across the app and I check if the current route can be popped before popping.
But as I said canPopSelfOrChildren is false.

When pushing a regular route with a path, it is marked as can popped true.

**Comment by Milad-Akarie** [comment]
@naamapps  oh right... that should be an easy fix

**Comment by naamapps** [comment]
Hey @Milad-Akarie, any news on this?

**Comment by irizzaflutter** [comment]
Could you help with situation when we call few dialogs (example: loader , success popup) how to check previous one / or how to close both (without using router pop function)?
