### ISSUE TITLE
How navigate between routers with history saved

### ISSUE THREAD

**Issue by liri2006** [Milad-Akarie/auto_route_library#705]
@Milad-Akarie Hi,

I'm having a routing set up, where there is a bottom nav routes and couple of top level routes, smt like this:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page|Screen,Route',
  routes: <AutoRoute<dynamic>>[
    AutoRoute<dynamic>(
      path: '/',
      initial: true,
      page: HomeScreen,
      guards: <Type>[AuthGuard],
      children: <AutoRoute<dynamic>>[
        AutoRoute<dynamic>(
          path: '',
          name: 'FeedRouter',
          page: EmptyRouterPage,
          children: <AutoRoute<dynamic>>[
            AutoRoute<dynamic>(
              path: 'feed',
              initial: true,
              page: FeedPage,
            ),
            AutoRoute<dynamic>(
              path: 'p/:id',
              usesPathAsKey: true,
              page: PostDetailsPage,
            ),
            // RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        //...other tab routes
      ],
    ),
    AutoRoute<bool>(
      guards: <Type>[AuthGuard],
      path: '/notifications',
      page: NotificationsPage,
    ),
  ],
)
class $AppRoutes {}
```

So basically Feed, Post and Notification page. 
Post is opened inside HomeRoute, so that bottom nav item is selected. 
Notifications page is opened on the top level, so it hides the bottom nav.

Now I want to open a post page from the Notifications page and because this is a cross route navigation I have to provide full hierarchy:

```
context.navigateTo(
      HomeRoute(children: <PageRouteInfo<dynamic>>[
        FeedRouter(children: <PageRouteInfo<dynamic>>[
          PostDetailsRoute(id: id),
        ]),
      ]),
    );
```

And this works, but if I press back button, then I'm returned to Feed instead of Notifications page.
And this is a case at least back button is shown (probably because of triple nesting), but in case where it is just parent/child, back button is not shown in AppBar and back is not working as I would expect it would (return to the screen which pushed the new route).

Can you please point out what I'm doing wrong here?

**Comment by Milad-Akarie** [comment]
@liri2006 you're not doing anything wrong, this is the expected behavior, back button simply pops the top route.
Implementing an actual back to previous location functionality is not that simply especially when working with nested routers but I'll give it a try.
