### ISSUE TITLE
[Feature request] Add option to allow generation of route names without leading slash

### ISSUE THREAD

**Issue by edwardaux** [Milad-Akarie/auto_route_library#71]
As mentioned in https://github.com/Milad-Akarie/auto_route_library/issues/66#issuecomment-615496648, it would be good if we could get the generated route names to optionally exclude the leading slash.

Perhaps something like: `MaterialAutoRouter(leadingSlashes: false)`

**Comment by Milad-Akarie** [comment]
@edwardaux  The initial route must be '/' other wise the back button will show.

**Comment by edwardaux** [comment]
yeah, that makes sense. I'd imagine that that flag would be ignored if the route is tagged using the `@initial` annotation. 

eg. something like:
```
@MaterialAutoRouter(leadingSlashes: false)
class $Router {
  @inital
  HomeScreen homeScreen;
  AccountScreen accountScreen;
}```
would generate `'/'` and `'accountScreen'`.

**Comment by Milad-Akarie** [comment]
Hey @edwardaux added in 
auto_route: 0.4.5
auto_route_generator: 0.4.7
`AutoRouter(useLeadingSlashes: false)`
Thanks for your hard work
