### ISSUE TITLE
Widget no rebuild in new version 2.4.0

### ISSUE THREAD

**Issue by famarrero** [Milad-Akarie/auto_route_library#713]
In previous version when a route was popped () the widget was rebuild, now that is not working and I need that behavior, some way to use that again. I used in inner routes

**Comment by Milad-Akarie** [comment]
Yes, that's an intentional improvement, you could wait for the push method to be notified when the route pops, or if you specifically want something like the previous behavior you could use
 context.watchRouter or 
AutoRouter.of(ctx, watch: true);  
When pushing the route.

**Comment by famarrero** [comment]
Thanks, work fine 👌👌👌
