### ISSUE TITLE
Navigation rail implementation 

### ISSUE THREAD

**Issue by angwandi** [Milad-Akarie/auto_route_library#715]
How do we go about implementing navigation rail?

**Comment by Milad-Akarie** [comment]
I'd first create a model for my destinations that has a `PageRouteInfo` and anything related to the destination item.
it'd look something like this.
```dart
class RouteDestination {
  final PageRouteInfo route;
  final IconData icon;
  final String label;

  const RouteDestination({
    required this.route,
    required this.icon,
    required this.label,
  });
}
```

```dart
class _DashboardState extends State<HomePage> {
  final destinations = const [
    RouteDestination(
      route: BooksTab(),
      icon: Icons.source,
      label: 'Books',
    ),
    RouteDestination(
      route: ProfileTab(),
      icon: Icons.person,
      label: 'Profile',
    ),
    RouteDestination(
      route: SettingsTab(),
      icon: Icons.settings,
      label: 'Settings',
    ),
  ];

  @override
  Widget build(context) {
    
    // builder will rebuild everytime this router's stack
    // updates
    // we need it to indicate which NavigationRailDestination is active
    return AutoRouter(builder: (context, child) {
      
      // we check for active route index by using
      // router.isRouteActive method
      var activeIndex = destinations.indexWhere(
        (d) => context.router.isRouteActive(d.route.routeName),
      );
      // there might be no active route until router is mounted 
      // so we play safe
      if (activeIndex == -1) {
        activeIndex = 0;
      }
      return Row(
        children: [
          NavigationRail(
            destinations: destinations
                .map((item) => NavigationRailDestination(
                      icon: Icon(item.icon),
                      label: Text(item.label),
                    ))
                .toList(),
            selectedIndex: activeIndex,
            onDestinationSelected: (index) {
              // use navigate instead of push so you won't have
              // many useless routes stacks
              context.navigateTo(destinations[index].route);
            },
          ),
          // child is the rendered route stack
          Expanded(child: child)
        ],
      );
    });
}
```

**Comment by angwandi** [comment]
@Milad-Akarie Thank you. Works very well with navigation rail. 
One issue, however: I am using a navigation rail for a bigger screen and a bottom nav bar for small screens. 
The routes do not seem to be in working.

**Comment by Milad-Akarie** [comment]
@angwandi in case of bottom nav bar do you want to keep state of tabs?
show me your implementation please.

**Comment by angwandi** [comment]
`import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:animations/animations.dart';
import 'package:auto_route/auto_route.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:dynamic_themes/dynamic_themes.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:icofont_flutter/icofont_flutter.dart';
import 'package:myjiji_client/routes/router.gr.dart';
import 'package:myjiji_client/services/authentication_service.dart';
import 'package:myjiji_client/ui/components/profile_avatar.dart';
import 'package:myjiji_client/ui/shared/app_colors.dart';
import 'package:salomon_bottom_bar/salomon_bottom_bar.dart';

import '../../app.dart';

class RouteDestination {
  final PageRouteInfo route;
  final IconData icon;
  final String label;
  final IconData selectedIcon;

  const RouteDestination({
    required this.route,
    required this.icon,
    required this.selectedIcon,
    required this.label,
  });
}

bool _isLargeScreen(BuildContext context) {
  return MediaQuery.of(context).size.width > 960.0;
}

bool _isMediumScreen(BuildContext context) {
  return MediaQuery.of(context).size.width > 640.0;
  //return MediaQuery.of(context).size.width > 800.0;
}

/// See bottomNavigationBarItem or NavigationRailDestination
class AdaptiveScaffoldDestination {
  final String title;
  final IconData selectedIcon;
  final IconData? icon;

  const AdaptiveScaffoldDestination({
    required this.title,
    required this.selectedIcon,
    this.icon,
  });
}

final destinations = const [
  RouteDestination(
    route: AllEventsRouter(),
    icon: Icons.home,
    selectedIcon: Icons.home_filled,
    label: 'All Events',
  ),
  RouteDestination(
    route: NotificationsRouter(),
    icon: Icons.notifications_none,
    selectedIcon: Icons.notifications,
    label: 'Notifications',
  ),
  RouteDestination(
    route: HotEventRouter(),
    icon: IcoFontIcons.fireBurn,
    selectedIcon: IcoFontIcons.fire,
    label: 'Hot Events',
  ),
  RouteDestination(
    route: SearchRouter(),
    icon: Icons.search,
    selectedIcon: IcoFontIcons.search1,
    label: 'Search',
  ),
  RouteDestination(
    route: MoreRouter(),
    icon: IcoFontIcons.navigationMenu,
    selectedIcon: IcoFontIcons.settings,
    label: 'More',
  ),
];

/// [NavigationRail], or [BottomNavigationBar]. Navigation destinations are
/// defined in the [destinations] parameter.
class AdaptiveScaffoldRails extends StatefulWidget {
  final Widget? title;
  final Widget? body;
  final int? currentIndex;
  final ValueChanged<int>? onNavigationIndexChange;
  final Widget? floatingActionButton;
  final bool? extended;

  AdaptiveScaffoldRails({
    this.title,
    this.body,
    this.extended,
    this.onNavigationIndexChange,
    this.floatingActionButton,
    this.currentIndex,
  });

  @override
  _AdaptiveScaffoldRailsState createState() => _AdaptiveScaffoldRailsState();
}

class _AdaptiveScaffoldRailsState extends State<AdaptiveScaffoldRails>
    with SingleTickerProviderStateMixin {
  bool extended = true;
  late ValueNotifier<bool> isExtended;

  @override
  void initState() {
    super.initState();
    isExtended = ValueNotifier<bool>(extended);
  }

  final selectedColor = myjiji_deep_orange_900;
  AuthenticationService authenticationService = AuthenticationService();

  //final unselectedColor = myjiji_deep_orange_500;
  final unselectedColor = Color(0xff8b8787);

  @override
  Widget build(BuildContext context) {
    final labelStyle = Theme.of(context).textTheme.subtitle1!.copyWith(
          fontWeight: FontWeight.w400,
          fontFamily: 'VarelaRound',
        );
    // Show a navigation rail
    if (_isLargeScreen(context)) {
      return AutoRouter(
        builder: (context, child) {
          // we check for active route index by using
          // router.isRouteActive method
          var activeIndex = destinations.indexWhere(
            (d) => context.router.isRouteActive(d.route.routeName),
          );
          // there might be no active route until router is mounted
          // so we play safe
          if (activeIndex == -1) {
            activeIndex = 0;
          }
          return Scaffold(
            body: Row(
              children: [
                LayoutBuilder(
                  builder: (context, constraints) => Container(
                    color: Theme.of(context).colorScheme.background,
                    child: ConstrainedBox(
                      constraints: BoxConstraints(
                        minHeight: constraints.maxHeight,
                      ),
                      child: IntrinsicHeight(
                        child: ValueListenableBuilder<bool>(
                            valueListenable: isExtended,
                            builder: (context, value, child) {
                              return NavigationRail(
                                leading: _NavigationRailHeader(
                                  extended: isExtended,
                                ),
                                // trailing: _NavigationRailFolderSection(),
                                extended: isExtended.value,
                                selectedLabelTextStyle:
                                    labelStyle.copyWith(color: selectedColor),
                                unselectedLabelTextStyle:
                                    labelStyle.copyWith(color: unselectedColor),
                                selectedIconTheme: IconThemeData(
                                  color: selectedColor,
                                ),
                                unselectedIconTheme: IconThemeData(
                                  color: unselectedColor,
                                ),
                                destinations: destinations
                                    .map((item) => NavigationRailDestination(
                                          icon: Icon(item.icon),
                                          label: Text(item.label),
                                          selectedIcon: Icon(item.selectedIcon),
                                        ))
                                    .toList(),
                                selectedIndex: activeIndex,
                                onDestinationSelected: (index) {
                                  // use navigate instead of push so you won't have
                                  // many useless routes stacks
                                  context.navigateTo(destinations[index].route);
                                },
                              );
                            }),
                      ),
                    ),
                  ),
                ),
                const VerticalDivider(
                  width: 1,
                  thickness: 1,
                  //color: Colors.grey[300],
                ),
                Expanded(
                  child: Center(
                    child: ConstrainedBox(
                      constraints: const BoxConstraints(maxWidth: 1340),
                      child: _SharedAxisTransitionSwitcher(defaultChild: child),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      );
    }
    // Show a bottom app bar
    return AutoTabsScaffold(
      // very important as noted
      /* appBarBuilder: (_, tabsRouter) => AppBar(
        title: const Text('Client'),
        centerTitle: true,
        leading: const AutoBackButton(),
      ),*/
      routes: const [
        AllEventsRouter(),
        NotificationsRouter(),
        HotEventRouter(),
        SearchRouter(),
        MoreRouter(),
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return Material(
          color: Theme.of(context).bottomAppBarColor,
          //color: Colors.transparent,
          elevation: 12,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(0.0),
              topRight: Radius.circular(0.0),
            ),
          ),
          child: SalomonBottomBar(
            selectedItemColor: selectedColor,
            unselectedItemColor: unselectedColor,
            margin: const EdgeInsets.symmetric(
              horizontal: 10,
              vertical: 10,
            ),
            currentIndex: tabsRouter.activeIndex,
            onTap: tabsRouter.setActiveIndex,
            items: [
              SalomonBottomBarItem(
                icon: Icon(Icons.home),
                title: Text('Events'),
                activeIcon: Icon(Icons.home_filled),
              ),
              SalomonBottomBarItem(
                icon: Icon(Icons.notifications_none),
                title: Text('Alerts'),
                activeIcon: Icon(Icons.notifications),
              ),
              SalomonBottomBarItem(
                icon: Icon(IcoFontIcons.fireBurn),
                title: Text('Hot'),
                activeIcon: Icon(IcoFontIcons.fire),
              ),
              SalomonBottomBarItem(
                icon: Icon(Icons.search),
                title: Text('Search'),
                activeIcon: Icon(IcoFontIcons.search1),
              ),
              SalomonBottomBarItem(
                icon: Icon(IcoFontIcons.navigationMenu),
                title: Text('More'),
                activeIcon: Icon(IcoFontIcons.settings),
              ),
            ],
          ),
        );
      },
      floatingActionButton: widget.floatingActionButton,
    );
  }
}
`

**Comment by angwandi** [comment]
@Milad-Akarie  I simply would like to keep the same state and page index when moving from bottom nav bar to navigation rail when transitioning from small screen to big screen.

**Comment by Milad-Akarie** [comment]
@angwandi  you need to decide whether you want to keep tabs state or not.
 in case you don't, just use AutoRouter for both layouts and decide the layout inside of the AutoRouter's builder function
 in case you do, use AutoTabsRouter for both layouts  and decide the layout inside of the AutoTabsRouter's builder function
```dart
class _AdaptiveScaffoldRailsState extends State<AdaptiveScaffoldRails>
    with SingleTickerProviderStateMixin {
  bool extended = true;
  late ValueNotifier<bool> isExtended;

  @override
  void initState() {
    super.initState();
    isExtended = ValueNotifier<bool>(extended);
  }

  final selectedColor = myjiji_deep_orange_900;
  AuthenticationService authenticationService = AuthenticationService();

  //final unselectedColor = myjiji_deep_orange_500;
  final unselectedColor = Color(0xff8b8787);

  @override
  Widget build(BuildContext context) {
    final labelStyle = Theme
        .of(context)
        .textTheme
        .subtitle1!
        .copyWith(
      fontWeight: FontWeight.w400,
      fontFamily: 'VarelaRound',
    );

    return AutoRouter(
      builder: (context, child) {
        // we check for active route index by using
        // router.isRouteActive method
        var activeIndex = destinations.indexWhere(
              (d) => context.router.isRouteActive(d.route.routeName),
        );
        // there might be no active route until router is mounted
        // so we play safe
        if (activeIndex == -1) {
          activeIndex = 0;
        }

        final isLargeScreen = _isLargeScreen(context);

        return Scaffold(
          body: isLargeScreen ?
          Row(
            children: [
              LayoutBuilder(
                builder: (context, constraints) =>
                    Container(
                      color: Theme
                          .of(context)
                          .colorScheme
                          .background,
                      child: ConstrainedBox(
                        constraints: BoxConstraints(
                          minHeight: constraints.maxHeight,
                        ),
                        child: IntrinsicHeight(
                          child: ValueListenableBuilder<bool>(
                              valueListenable: isExtended,
                              builder: (context, value, child) {
                                return NavigationRail(
                                  leading: _NavigationRailHeader(
                                    extended: isExtended,
                                  ),
                                  // trailing: _NavigationRailFolderSection(),
                                  extended: isExtended.value,
                                  selectedLabelTextStyle:
                                  labelStyle.copyWith(color: selectedColor),
                                  unselectedLabelTextStyle:
                                  labelStyle.copyWith(color: unselectedColor),
                                  selectedIconTheme: IconThemeData(
                                    color: selectedColor,
                                  ),
                                  unselectedIconTheme: IconThemeData(
                                    color: unselectedColor,
                                  ),
                                  destinations: destinations
                                      .map((item) =>
                                      NavigationRailDestination(
                                        icon: Icon(item.icon),
                                        label: Text(item.label),
                                        selectedIcon: Icon(item.selectedIcon),
                                      ))
                                      .toList(),
                                  selectedIndex: activeIndex,
                                  onDestinationSelected: (index) {
                                    // use navigate instead of push so you won't have
                                    // many useless routes stacks
                                    context.navigateTo(
                                        destinations[index].route);
                                  },
                                );
                              }),
                        ),
                      ),
                    ),
              ),
              const VerticalDivider(
                width: 1,
                thickness: 1,
                //color: Colors.grey[300],
              ),
              Expanded(
                child: Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 1340),
                    child: _SharedAxisTransitionSwitcher(defaultChild: child),
                  ),
                ),
              ),
            ],
          ) :
          // if small screen render child for a body
          child,
          // conditionally render bottom nav bar
          bottomNavigationBar: isLargeScreen ? BottomNavigationBar(
            // use same activeIndex 
            currentIndex: activeIndex,
            // navigate the same way 
            onTap: (index) {
              context.navigateTo(
                  destinations[index].route);
            },
            items: destinations
                .map((item) =>
                BottomNavigationBarItem(
                  icon: Icon(item.icon),
                  label: item.label,
                  activeIcon: Icon(item.selectedIcon),
                ))
                .toList(),
          ) : null,

        );
      },
    );
    
```

**Comment by Milad-Akarie** [comment]
using AutoTabsRouter should look something like this.
```dart
class _AdaptiveScaffoldRailsState extends State<AdaptiveScaffoldRails>
    with SingleTickerProviderStateMixin {
  bool extended = true;
  late ValueNotifier<bool> isExtended;

  @override
  void initState() {
    super.initState();
    isExtended = ValueNotifier<bool>(extended);
  }

  final selectedColor = myjiji_deep_orange_900;
  AuthenticationService authenticationService = AuthenticationService();

  //final unselectedColor = myjiji_deep_orange_500;
  final unselectedColor = Color(0xff8b8787);

  @override
  Widget build(BuildContext context) {
    final labelStyle = Theme
        .of(context)
        .textTheme
        .subtitle1!
        .copyWith(
      fontWeight: FontWeight.w400,
      fontFamily: 'VarelaRound',
    );

    return AutoTabsRouter(
      builder: (context, child, animation) {
        final isLargeScreen = _isLargeScreen(context);
        return Scaffold(
          body: isLargeScreen ?
          Row(
            children: [
              LayoutBuilder(
                builder: (context, constraints) =>
                    Container(
                      color: Theme
                          .of(context)
                          .colorScheme
                          .background,
                      child: ConstrainedBox(
                        constraints: BoxConstraints(
                          minHeight: constraints.maxHeight,
                        ),
                        child: IntrinsicHeight(
                          child: ValueListenableBuilder<bool>(
                              valueListenable: isExtended,
                              builder: (context, value, child) {
                                return NavigationRail(
                                  leading: _NavigationRailHeader(
                                    extended: isExtended,
                                  ),
                                  // trailing: _NavigationRailFolderSection(),
                                  extended: isExtended.value,
                                  selectedLabelTextStyle:
                                  labelStyle.copyWith(color: selectedColor),
                                  unselectedLabelTextStyle:
                                  labelStyle.copyWith(color: unselectedColor),
                                  selectedIconTheme: IconThemeData(
                                    color: selectedColor,
                                  ),
                                  unselectedIconTheme: IconThemeData(
                                    color: unselectedColor,
                                  ),
                                  destinations: destinations
                                      .map((item) =>
                                      NavigationRailDestination(
                                        icon: Icon(item.icon),
                                        label: Text(item.label),
                                        selectedIcon: Icon(item.selectedIcon),
                                      ))
                                      .toList(),
                                  selectedIndex: context.tabsRouter.activeIndex,
                                  onDestinationSelected: (index) {
                                   context.tabsRouter.setActiveIndex(index);
                                );
                              }),
                        ),
                      ),
                    ),
              ),
              const VerticalDivider(
                width: 1,
                thickness: 1,
                //color: Colors.grey[300],
              ),
              Expanded(
                child: Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 1340),
                    child: _SharedAxisTransitionSwitcher(defaultChild: child),
                  ),
                ),
              ),
            ],
          ) :
          // if small screen render child for a body
          child,
          // conditionally render bottom nav bar
          bottomNavigationBar: isLargeScreen ? BottomNavigationBar(
            currentIndex:  context.tabsRouter.activeIndex,
            onTap: (index) {
              context.tabsRouter.setActiveIndex(index);
            },
            items: destinations
                .map((item) =>
                BottomNavigationBarItem(
                  icon: Icon(item.icon),
                  label: item.label,
                  activeIcon: Icon(item.selectedIcon),
                ))
                .toList(),
          ) : null,

        );
      },
    );
    
```

**Comment by angwandi** [comment]
Thank you @Milad-Akarie 
Let me give it a try. 

Basically trying to achieve this: https://gallery.flutter.dev/#/reply

**Comment by Milad-Akarie** [comment]
@angwandi  yes, that's totally doable, using both AutoTabsRouter and AutoRouter. 
if you want to keep tab's content state while switching between tabs use AutoTabsRouter otherwise using AutoRouter

**Comment by angwandi** [comment]
@Milad-Akarie 
Thank you. Works perfectly well.

Really appreciate

**Comment by Milad-Akarie** [comment]
@angwandi  you're welcome.
