### ISSUE TITLE
Cannot push to route from the same route

### ISSUE THREAD

**Issue by RakaAlrian** [Milad-Akarie/auto_route_library#717]
Hi I have app that have a gridview which the item lead to detail screen on tap, and inside the detail screen I have another grid view that do the same thing, lead to detail screen. So I want it to open detail screen again and again as far as user need. It does work previously, but now it is not working. I tried to downgrade the auto_route version to 2.2.0 but still not working. I would thankful if there anyone can help me with my problem.

here is my flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale id-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.60.1)
[√] Connected device (1 available)

• No issues found!
```

and this is repo that I use to reproduce the bug https://github.com/RakaAlrian/learn_autoroute/tree/produce_bug

**Comment by RakaAlrian** [comment]
I found that I cannot back to previous version, it keep using auto_route version 2.4.0 even if I delete the cache directory in AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org. I already tried to run `flutter pub cache repair` and `flutter clean`, but then after I run `flutter pub get`, auto_route version 2.4.0 is appearing again in AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org. Fyi, I use FVM on my windows, and set stable flutter version(2.5.1) as global, do you think this bug is from FVM? What should I do?

**Comment by Milad-Akarie** [comment]
@RakaAlrian  Thanks for the reproduce gist. it's been fixed locally

**Comment by RakaAlrian** [comment]
@Milad-Akarie glad its help. thanks!

**Comment by TarekkMA** [comment]
I still have this issue, when calling `replaceAll([MainScreen])` all routes are replaced but the main screen is the same.
