### ISSUE TITLE
AutoTabsScaffold Preload Pages

### ISSUE THREAD

**Issue by tengyeekong** [Milad-Akarie/auto_route_library#718]
Hope AutoTabsScaffold allows us to set a number to indicate how many preloaded tabs needed, for example like Viewport's cacheExtent.
In my case I need my home page to have all 3 tabs to load before user even go to tab 2 or 3. Thanks!

**Comment by alphamanorg** [comment]
Yes totally agree with you. This option should be there as it hangs the whole dashboard loading all pages at once. There should be an option to specify which pages to preload.

**Comment by Milad-Akarie** [comment]
@tengyeekong @alphamanorg right now there's an option to preload all tabs 
lazyLoad: false

**Comment by tengyeekong** [comment]
@Milad-Akarie ohh didn't know that, thanks for pointing out!
