### ISSUE TITLE
Not able to push page after using AutoRouterDelegate.declarative

### ISSUE THREAD

**Issue by combi-35** [Milad-Akarie/auto_route_library#721]
I am not able to push a new Page when using `AutoRouterDelegate.declarative` instead of `_appRouter.delegate()` as routerDelegate, described here [auto_route auth](https://autoroute.vercel.app/advanced/authentication).

Router:
```dart
MaterialApp.router(
      debugShowCheckedModeBanner: false,
      //routerDelegate: _appRouter.delegate(),
      routerDelegate: AutoRouterDelegate.declarative(
        _appRouter,
        routes: (_) => [
          if (authState)
            const MyHomeRouter()
          else
            const AuthRouter(),
        ],
      ),
      routeInformationParser: _appRouter.defaultRouteParser(includePrefixMatches: true),
)
```

router.dart

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: MyHomePage,
      name: "MyHomeRouter",
      initial: true,
      children: [
        AutoRoute(
          page: HomePage,
          path: "home",
          name: "HomeRouter",
        ),
        AutoRoute(page: NotificationPage, path: "notification"),

      ],
    ),
    AutoRoute(
      page: LoginPage,
      path: "/auth",
      name: "AuthRouter",
      children: [
        AutoRoute(page: SignupPage, path: "signup"),
      ],
    ),
  ],
)
class $AppRouter {}
```

When using `routerDelegate: _appRouter.delegate()` I am able to push to new page like `context.router.pushNamed("/notification")`. After using `AutoRouterDelegate.declarative` I get this error when trying to push to new page
```
Unhandled Exception: 'package:auto_route/src/router/controller/routing_controller.dart': Failed assertion: line 861 pos 7: '!managedByWidget': Pages stack can be managed by either the Widget (AutoRouter.declarative) or Router
```

Why is it not possible to push new page when using declarative approach?

**Comment by Milad-Akarie** [comment]
@combi-35 you should be able to push to `MyHomeRouter` not the root router. 
what widget are you pushing from?

**Comment by combi-35** [comment]
Hi @Milad-Akarie,
how would I do that?

I am pushing from onPressed action
```dart
IconButton(
    icon: const Icon(Icons.notifications),
    onPressed: () => context.router.pushNamed("/notification")
)
```

**Comment by Milad-Akarie** [comment]
@combi-35 what screen/route are you pushing from? 
I need to know hierarchy

**Comment by combi-35** [comment]
@Milad-Akarie I am pushing from `HomePage` to `NotificationPage`.
`MyHomePage` is root router with `BottomNavigationBar`, it contains `HomePage` and `NotificationPage`.

**Comment by Milad-Akarie** [comment]
PushNamd('notification') without forward slash

**Comment by Milad-Akarie** [comment]
Or use navigateNamed

**Comment by combi-35** [comment]
`context.router.pushNamed('notification')` throws an error

`context.navigateNamedTo('notification')` is working

But what happens in first place? It was working with `context.router.pushNamed('notification')` when I used `routerDelegate: _appRouter.delegate()`.

**Comment by Milad-Akarie** [comment]
@combi-35  obviously you're not obtaining the right router.

**Comment by tapizquent** [comment]
@Milad-Akarie can you please elaborate or provide an example on how to actually move across screens within routers that have been added with AutoRouterDelegate.declarative?

I also keep getting errors saying that I can't push when routes because the router is declarative.

Same scenario as @combi-35

**Comment by alexisenp** [comment]
Same problem here, and cant find a solution.
im check authentication like this example https://autoroute.vercel.app/advanced/authentication but now cant use 
context.router.pushNamed("/notification") and i dont know how to navigate between my routes. A little help would be great, im stuck on this.

**Comment by tapizquent** [comment]
Still waiting on this

**Comment by gabsn** [comment]
getting the same error when using the declarative auth... 
```sh
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: 'package:auto_route/src/router/controller/routing_controller.dart': Failed assertion: line 1095 pos 7: '!managedByWidget': Pages stack can be managed by either the Widget (AutoRouter.declarative) or Router
```

**Comment by soliev01** [comment]
Same here

**Comment by soliev01** [comment]
Has anyone solved this issue yet?

**Comment by tapizquent** [comment]
Not stale. Still waiting

**Comment by Milad-Akarie** [comment]
This is not a bug, it's an intended behavior.
Pages stack can only be managed by widget or push pop and friends
Can't managed by both in the same controller

**Comment by tapizquent** [comment]
@Milad-Akarie thank you so much for replying. I guess in that case what we need is maybe more examples on how to achieve the same or a similar behavior.

**Comment by Milad-Akarie** [comment]
I'm trying to squeeze sometime for auto_route hopefully in the near future will be more examples

**Comment by SharbelOkzan** [comment]
> @combi-35 obviously you're not obtaining the right router.

@Milad-Akarie Could you please elaborate on this?
One line of code or a link to some related docs would help us a lot.

Thanks for your efforts

**Comment by dipak-pd** [comment]
Please provide some proper documentation, I'm not able to push any page.

**Comment by dickermoshe** [comment]
Guys, declarative nativation means that you can't push or pop anything.
You have to declare a list of routes that change based on state. You can still push using the a parent router
