### ISSUE TITLE
dynamically change initial route from splashscreen to mainpage

### ISSUE THREAD

**Issue by fullflash** [Milad-Akarie/auto_route_library#722]
Hi,
is it possible to change initial route to homepage or swap initial route ?
we need it in order to change initial SplashScreen route to mainpage.

is there any function for such case or we should implement by ourselfs ?

**Comment by Milad-Akarie** [comment]
@fullflash My first advice would be to use a native splash screen.
https://flutter.dev/docs/development/ui/advanced/splash-screen
https://pub.dev/packages/flutter_native_splash

if you still want to use a flutter widget just call `router.replace(HomeRoute()) `from your splash screen

**Comment by fullflash** [comment]
thanks for awesome native splash screen plugin advice and replace
