### ISSUE TITLE
App with Dynamic links and authentication

### ISSUE THREAD

**Issue by Miiel** [Milad-Akarie/auto_route_library#728]
Hi, I have implemented authentication  in my app using  AutoRouterDelegate.declarative() as stated [here](https://autoroute.vercel.app/advanced/authentication).
In another branch, I have implemented Firebase Dynamic links as explained here: https://github.com/Milad-Akarie/auto_route_library/issues/461#issuecomment-818628516.

So, I fetch the deeplink from Firebase Dynamic links before running my app widget:

```
PendingDynamicLinkData? initialLink = await FirebaseDynamicLinks.instance.getInitialLink();

  runApp(EasyLocalization(
      path: 'assets/translations',
      supportedLocales: [
        Locale('en'),
        Locale('nl'),
        Locale('es'),
      ],
      child: ProviderScope(
        child: MyApp(initialDeepLink: initialLink?.link.toString()),
      )));
```

In my AppState, I return this widget in the build function:
```
 return MaterialApp.router(
          debugShowCheckedModeBanner: false,
          title: config.appName,
          theme: context.read(appThemeProvider).getAppThemedata(context, _appThemeState),
          routerDelegate: AutoRouterDelegate.declarative(
            _appRouter,
            routes: (_) => [
              if (_authState.isAuthenticated)
                HomeRoute()
              else
                LoginRoute(),
            ],
            navigatorObservers: () => [
              AutoRouteObserver(),
              FirebaseAnalyticsObserver(analytics: analytics),
            ],
            // initialDeepLink: widget.initialDeepLink,
          ),
          routeInformationProvider: _routeProvider,
          routeInformationParser: _appRouter.defaultRouteParser(),
          localizationsDelegates: context.localizationDelegates,
          supportedLocales: context.supportedLocales,
          locale: context.locale,
        );
```

Before implementing authentication, I could pass an initialDeepLink into my AutoRouterDelegate since I didn't use declarative yet. So my question is, how can I use AutoRouterDelegate.declarative **and** pass an initialDeepLink object into my AutoRouterDelegate?

**Comment by Milad-Akarie** [comment]
@MXMMD  hmmmm I guess you could use the route info provider to deliver the deep link but if the user is not logged in and you don't render the HomeRoute first the deep link will be lost

try to add this 

```dart
 routeInformationProvider: _appRouter.routeInfoProvider(
        initialRouteInformation: AutoRouteInformation(
          location: '/deep/location/here',
        ),
      ),
```
also consider using `_appRouter.declarativeDelegate()` so you won't have different instance everytime.

**Comment by alexanderytaylor** [comment]
I'm having this same issue. I opened this issue: https://github.com/Milad-Akarie/auto_route_library/issues/1327

Is there a solution yet?
