### ISSUE TITLE
How can I disable BottomNavigationBar on a specific page?

### ISSUE THREAD

**Issue by sh4msi** [Milad-Akarie/auto_route_library#732]
hi,
How can I disable BottomNavigationBar on a specific page?
(Nested Routes)

**Comment by Milad-Akarie** [comment]
@sh4msi  
try doing something like this before rendering your bottom nav

```dart
bool renderNavBar = true;
 if(context.topRouteMatch.name == MyFullScreenPage.name){
   renderNavBar = false;
 }

```

**Comment by SelcukKomurcu** [comment]
Hey @Milad-Akarie , i have follow-up question here regarding this.
I have complex nested routes tree with multiple routers inside tabsRouter. For some pages inside nested tree want to show bottom navigation and for some want to hide. To able to achieve this don't want to write every page name to function like above. Can we have option like fullScreenDialog to be defined on generated routes so i can add my state management to decide bottom navigation or not regarding that option?

**Comment by Milad-Akarie** [comment]
Hello, I've actually been working on something that can help with this, it will probably be shipped with the next release. 
The whole idea is being able to pass meta/extra data to the route annotation and have it passed to the generated route configs.


```dart
  AutoRoute(
   path: ':id',
   page: BookDetailsPage,
   meta: {'hideBottomNav': true},
  ),
```
and you check for the flag in ui like 
```dart
 final hideBottomNav = context.topRouteMatch.meta['hideBottomNav'] == true;
```

**Comment by SelcukKomurcu** [comment]
Awesome! That's what i needed, thanks.

**Comment by tapkain** [comment]
hello, where to put this if statement? I'm putting it inside bottomNavigationBuilder of AutoTabsScaffold and between page navigation it does not invoke this method, therefore the check is not executed.

**Comment by madatr** [comment]
hi, is there any progress on this?

**Comment by madatr** [comment]
Salam!
Is there any progress on this?

> Hello, I've actually been working on something that can help with this, it will probably be shipped with the next release. The whole idea is being able to pass meta/extra data to the route annotation and have it passed to the generated route configs.
> 
> ```dart
>   AutoRoute(
>    path: ':id',
>    page: BookDetailsPage,
>    meta: {'hideBottomNav': true},
>   ),
> ```
> 
> and you check for the flag in ui like
> 
> ```dart
>  final hideBottomNav = context.topRouteMatch.meta['hideBottomNav'] == true;
> ```

**Comment by tahaaslam1** [comment]
> Hello, I've actually been working on something that can help with this, it will probably be shipped with the next release. The whole idea is being able to pass meta/extra data to the route annotation and have it passed to the generated route configs.
> 
> ```dart
>   AutoRoute(
>    path: ':id',
>    page: BookDetailsPage,
>    meta: {'hideBottomNav': true},
>   ),
> ```
> 
> and you check for the flag in ui like
> 
> ```dart
>  final hideBottomNav = context.topRouteMatch.meta['hideBottomNav'] == true;
> ```

Any progress on this?

**Comment by hussain-abbas-06228** [comment]
> Hello, I've actually been working on something that can help with this, it will probably be shipped with the next release. The whole idea is being able to pass meta/extra data to the route annotation and have it passed to the generated route configs.
> 
> ```dart
>   AutoRoute(
>    path: ':id',
>    page: BookDetailsPage,
>    meta: {'hideBottomNav': true},
>   ),
> ```
> 
> and you check for the flag in ui like
> 
> ```dart
>  final hideBottomNav = context.topRouteMatch.meta['hideBottomNav'] == true;
> ```

Hi,
Is there any Update on this?

**Comment by Milad-Akarie** [comment]
İt's already done
