### ISSUE TITLE
Tabsrouter with nested routes pop until root

### ISSUE THREAD

**Issue by kevin1232sn1** [Milad-Akarie/auto_route_library#737]
Hi,

I'm having a TabsRouter containing a couple of tabs. 
In each tab it is possible do navigate to multiple children for this tab.
I want to go to the main tab page when pressing a tabs button again.

Don't know if this is possible but I can pop the top route with tabsRouter.popTop().
Only can do this once even when I put it in a loop.

Is there a way to pop my routes until I come across the desired route?

**Comment by Milad-Akarie** [comment]
@kevin1232sn1 @antonkrasov  that can be done by getting the stack router of the selected index using `stackRouterOfIndex` then calling `popUntilRoot()` on it. 

```dart
onTap: (index) {
  if (index != tabsRouter.activeIndex) {
    tabsRouter.setActiveIndex(index);
  }else{
   tabsRouter.stackRouterOfIndex(index)?.popUntilRoot();
  }
```

**Comment by antonkrasov** [comment]
@Milad-Akarie that works, thank you very much for your job!
