### ISSUE TITLE
How can I get the previous route?

### ISSUE THREAD

**Issue by sh4msi** [Milad-Akarie/auto_route_library#739]
Hi,
How can I get the previous page (previous root)?

(I want to do something different in BottomNavigationBar than last page)

**Comment by Milad-Akarie** [comment]
@sh4msi not sure what you're trying to do but you can have access to the whole stack by going 
`router.stackData `
which is a list of RouteData, and the previous route would be `stackData[stackData.length -2]`

hope this helps.

**Comment by sh4msi** [comment]
How can I send a flag and get it on onTap?
