### ISSUE TITLE
How to use auto_route while writing widget tests?

### ISSUE THREAD

**Issue by Thesmader** [Milad-Akarie/auto_route_library#745]
Router:
```dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute<void>(path: '/', page: EmptyRouterPage, initial: true, children: [
      AutoRoute<void>(path: '', page: SplashScreen),
      AutoRoute<void>(path:'intro', page: IntroScreen),
      AutoRoute<void>(path:'login', page: LoginScreen),
      AutoRoute<void>(path:'home', page: HomeScreen),
    ]),
  ]
)
class $AppRouter {}
```

MaterialApp:
```dart
  final router = AppRouter();
  ...
  MaterialApp.router(
    routeInformationProvider: router.routeInfoProvider(),
    routeInformationParser: router.defaultRouteParser(),
    routerDelegate: router.delegate(),
  )
  ...
```
- I have this as my current setup. The app starts on `SplashScreen` and goes to the `Intro Screen` for user onboarding. 
- I have a button on `IntroScreen`, that navigates to `LoginScreen` or `HomeScreen` based on a condition. 
- I want to test the behaviour of this button in a widget test. For that, I would like to pump just the `IntroScreen` widget during the test, mock its dependencies and then verify at least that `context.router.replace()` is called with the correct route.

However, with the current setup, the app will always open on `SplashScreen`, which means I will have to mock the dependencies for `SplashScreen` and then go on to `IntroScreen`. This approach quickly becomes unfeasible with deeper nesting.

Is there a better approach to this?

**Comment by biscottis** [comment]
@Thesmader 



I have the same issue, but seeing as I have the same use case as you, I don't need to actually route (push/pop/replace) anything, but only verify that it has taken place. This is something hacky I did:

I am using https://pub.dev/packages/mocktail btw.

```dart
import 'package:auto_route/auto_route.dart';
import 'package:mocktail/mocktail.dart';

class MockStackRouter extends Mock implements StackRouter {}

class FakePageRouteInfo extends Fake implements PageRouteInfo {}
```

```dart
void main() {
  setUpAll(() {
    registerFallbackValue(FakePageRouteInfo());
  });
  
  testWidgets('Routing test', (tester) async {
    final mockStackRouter = MockStackRouter();
    when(() => _mockStackRouter.push(any())).thenAnswer((_) async {});

    await tester.pumpWidget(
      MaterialApp(
        title: 'Routing Test',
        home: StackRouterScope(
          controller: mockStackRouter,
          segmentsHash: 0,
          child: PageYouWantToTest(),
        ),
      ),
    );

    await tester.tap(find.byType(SomeButtonThatPushes));

    final captured = verify(() => _mockStackRouter.push(captureAny())).captured;
    print(captured); // will print details of PageRouteInfo
  });
}
```

**Comment by biscottis** [comment]
> @biscottis Thanks a ton for the snippet. This way does work. I do not need the router actually to navigate in widget tests. I want to verify if the navigation methods are called with the correct arguments. Successfully mocking the router does achieve that.

Great library by the authors, however I really wished there were more support for widget testing. I have not yet found a way to do the actual routing and not merely do mocking, not to mention the approach I shown does not work for more advanced stuff like nested/tab navigation and route guards.

**Comment by jeremiahlukus** [comment]
```
The following TestFailure was thrown running a test:
No matching calls (actually, no calls at all).
(If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:137:31)
#1      _VerifyCall._checkWith (package:mocktail/src/mocktail.dart:722:7)
#2      _makeVerify.<anonymous closure> (package:mocktail/src/mocktail.dart:515:18)
``` 

Seems like this doesn't work anymore?

**Comment by ncuillery** [comment]
I watched this issue a couple of weeks ago 👀 so nope, not stale, my project needs this.

**Comment by tfreebern2** [comment]
I can mock the AppRouter just like it's been suggested but then I'm failing the test because I can't mock `NavigationHistory`.

```
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'NavigationHistory'
```

```
  TestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();

  final appRouter = MockAppRouter();

  setUp(() {
    locator.registerSingleton<AppRouter>(appRouter);
  });

  tearDown(() {
    locator.unregister<AppRouter>();
  });
  
  final widget = MaterialApp.router(
    localizationsDelegates: [AppLocalizations.delegate],
    routerDelegate: AutoRouterDelegate(
      appRouter,
      navigatorObservers: () => [AutoRouteObserver()],
    ),
    routeInformationParser: appRouter.defaultRouteParser(),
    builder: (context, _) {
      return AccountView();
    },
  );
  
  await tester.pumpWidget(widget);
```

**Comment by babirms** [comment]
> I can mock the AppRouter just like it's been suggested but then I'm failing the test because I can't mock `NavigationHistory`.
> 
> I'm not able to import it since it's not a part of the export file.
> 
> ```
> The following _TypeError was thrown running a test:
> type 'Null' is not a subtype of type 'NavigationHistory'
> ```
> 
> ```
>   TestWidgetsFlutterBinding.ensureInitialized();
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   final appRouter = MockAppRouter();
> 
>   setUp(() {
>     locator.registerSingleton<AppRouter>(appRouter);
>   });
> 
>   tearDown(() {
>     locator.unregister<AppRouter>();
>   });
>   
>   final widget = MaterialApp.router(
>     localizationsDelegates: [AppLocalizations.delegate],
>     routerDelegate: AutoRouterDelegate(
>       appRouter,
>       navigatorObservers: () => [AutoRouteObserver()],
>     ),
>     routeInformationParser: appRouter.defaultRouteParser(),
>     builder: (context, _) {
>       return AccountView();
>     },
>   );
>   
>   await tester.pumpWidget(widget);
> ```

I'm having the same problem. Does anybody have a solution for this?

**Comment by jeremiahlukus** [comment]
I’ve been using a method called pumpRouterApp

https://github.com/jeremiahlukus/guitar_tabs/blob/master/test/utils/router_test_utils.dart

Then pushing a route first that way it’s not null

https://github.com/jeremiahlukus/guitar_tabs/blob/master/test/backend/songs/core/presentation/song_drawer_test.dart#L96

**Comment by ntaworking** [comment]
This issue should be re-opened.

**Comment by kevin4hig** [comment]
Any solution? It's 2025.

**Comment by jeremiahlukus** [comment]
go_router
