### ISSUE TITLE
Is it possible to use AutoRoute() in CustomScrollView or NestedScrollView?

### ISSUE THREAD

**Issue by tamasoszko** [Milad-Akarie/auto_route_library#754]
Hello,

I wonder if there is solution to use AutoRoute() as sliver. I'm getting exception because AutoRoute() produces RenderBox instead of RenderSliver. Is there a way to map it? 
SliverToBoxAdapter(child: AutoRoute()) does not work
 
I want something like this:

@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: null,
        body: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(...),

            // TODO: add autoroute here as sliver somehow
            AutoRoute(), 

            SliverFillRemaining(...),
          ],
        ));

**Comment by Milad-Akarie** [comment]
@tamasoszko I think SliverToBoxAdapter is what you need, I haven't played with this but I believe the issue here is that you need to specific a height for AutoRouter() Widget, if assuming you want it to take full screen height.
```dart
SliverToBoxAdapter(child: SizedBox(
  height: MediaQuery.of(context).size.height,
  child:AutoRoute(),
)
```
It's not tested but I believe it will work.

**Comment by mrverdant13** [comment]
Milads's answer might be enough for some use cases, but there are other complex scenarios where it would not suffice.
For them, you could use [`NestedScrollView`](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html). It is specifically useful when using more slivers as nested navigation content.
