### ISSUE TITLE
AutoRouteInformationProvider.routerReportsNewRouteInformation doesn't have the named parameter 'type'

### ISSUE THREAD

**Issue by nibo** [Milad-Akarie/auto_route_library#755]
* EDIT running on beta channel
In the current Version is an error in `AutoRouteInformationProvider`when overriding the `routerReportsNewRouteInformation`method. The required Paramter `RouteInformationReportingType` is missing.

To fix this, you have to add the ´RouteInformationReportingType´to this method.

 ```
@override
  void routerReportsNewRouteInformation(RouteInformation routeInformation,
      {required RouteInformationReportingType type,bool isNavigation = true}) {
    var replace = false;
    if (routeInformation is AutoRouteInformation) {
      replace = routeInformation.replace;
    }
    SystemNavigator.selectMultiEntryHistory();
    SystemNavigator.routeInformationUpdated(
      location: routeInformation.location!,
      state: routeInformation.state,
      replace: replace || !isNavigation,
    );
    _value = routeInformation;
  }```

**Comment by LenWdk** [comment]
Wow, that looks like a serious bug and should definitely be addressed soon

**Comment by vgtle** [comment]
I had the same problem. This fixed this for now, but would be great to have this fixed in the package.

**Comment by nibo** [comment]
@akshaybhange I was running on beta channel, when you run on flutter-stable everything should work as expected

**Comment by tommcamm** [comment]
It is possible to fix this without going to stable?
Thanks!

**Comment by Hu-Wentao** [comment]
> It is possible to fix this without going to stable? Thanks!

see PR: https://github.com/Milad-Akarie/auto_route_library/pull/756/commits

**Comment by Agondev** [comment]
> > It is possible to fix this without going to stable? Thanks!
> 
> see PR: https://github.com/Milad-Akarie/auto_route_library/pull/756/commits
> 
> just add code to `pubspec.yaml` , override `auto_route` dependency.
> 
> ```yaml
> dependency_overrides:
>   auto_route:
>     git:
>       url: https://github.com/nibo/auto_route_library
>       path: auto_route
> ```
> 
> it work for me.

Updated to account for new version:

```yaml
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```

**Comment by Hu-Wentao** [comment]
It’s better to add the version number，thank for your work

**Comment by Hu-Wentao** [comment]
@Agondev It’s better to add the version number，thank for your work

**Comment by agordeev** [comment]
When using https://github.com/Agondev/auto_route_library the project builds fine, but the framework throws this error:

```
The following assertion was thrown while dispatching notifications for _DeclarativeAutoRouterDelegate:
setState() or markNeedsBuild() called during build.

This Router<Object> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Router<Object>
    dependencies: [UnmanagedRestorationScope]

```

**Comment by Agondev** [comment]
> When using https://github.com/Agondev/auto_route_library the project builds fine, but the framework throws this error:
> 
> ```
> The following assertion was thrown while dispatching notifications for _DeclarativeAutoRouterDelegate:
> setState() or markNeedsBuild() called during build.
> 
> This Router<Object> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
> The widget on which setState() or markNeedsBuild() was called was: Router<Object>
>     dependencies: [UnmanagedRestorationScope]
>     state: _RouterState<Object>#6cfe2
> The widget which was currently being built when the offending call was made was: StackRouterScope
> When the exception was thrown, this was the stack
> #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4261:11)
> #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4276:6)
> #2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
> #3      _RouterState._handleRouterDelegateNotification (package:flutter/src/widgets/router.dart:704:5)
> #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
> #5      AutoRouterDelegate._handleRebuild (package:auto_route/src/router/controller/auto_router_delegate.dart:121:5)
> #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
> #7      NavigationHistory._onNewUrlState (package:auto_route/src/router/controller/navigation_history.dart:26:7)
> #8      NativeNavigationHistory._onNewUrlState (package:auto_route/src/router/controller/navigation_history.dart:120:11)
> #9      StackRouter.updateDeclarativeRoutes (package:auto_route/src/router/controller/routing_controller.dart:948:23)
> #10     _AutoRouteNavigatorState._updateDeclarativeRoutes (package:auto_route/src/router/widgets/auto_route_navigator.dart:45:21)
> #11     _AutoRouteNavigatorState.didChangeDependencies (package:auto_route/src/router/widgets/auto_route_navigator.dart:36:7)
> #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4749:11)
> #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
> ...     Normal element mounting (380 frames)
> #393    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
> ...     Normal element mounting (9 frames)
> #402    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
> #403    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
> #404    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
> #405    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:495:11)
> #406    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
> #407    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
> #408    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
> #409    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:395:11)
> ...     Normal element mounting (7 frames)
> #416    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
> ...     Normal element mounting (7 frames)
> #423    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
> #424    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
> #425    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
> #426    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
> #427    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:495:11)
> #428    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
> #429    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
> #430    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
> #431    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:395:11)
> ...     Normal element mounting (7 frames)
> #438    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
> ...     Normal element mounting (9 frames)
> #447    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
> #448    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
> #449    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
> #450    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
> #451    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
> #452    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
> #453    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
> #454    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
> #455    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
> (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
> The _DeclarativeAutoRouterDelegate sending notification was: Instance of '_DeclarativeAutoRouterDelegate'
> ```

Would be good to provide the stack in your code that lead to this error.

**Comment by dishankjj** [comment]
I recently upgraded my project to flutter 2.8.1 and i am facing the same error as written in title
