### ISSUE TITLE
nested tab router bug

### ISSUE THREAD

**Issue by masoudk2000** [Milad-Akarie/auto_route_library#757]
I have a problem with nested tabs. When I enter the program and want to exit the program, it seems that the home screen has been run twice. I uploaded the video of this problem

i used 2.4.2 version and flutter version 2.5.2

https://files.fm/u/dkdud8ajs

**Comment by Milad-Akarie** [comment]
@masoudk2000 it seemed to me like you closed your App? what  are you expecting to happen?

**Comment by rd-martin-jaeger** [comment]
[This](https://github.com/Milad-Akarie/auto_route_library/issues/893) is probably the same bug and some provided samples
