### ISSUE TITLE
Run Debug Mode - Hot restart causes white screen

### ISSUE THREAD

**Issue by RaineHolgado** [Milad-Akarie/auto_route_library#759]
I'm running on debug mode but when I pressed hot restart it will cause white screen. Any fixes on this?

**Comment by savy-91** [comment]
The same happens to me, how did you fix it? @RaineHolgado

**Comment by RaineHolgado** [comment]
`class MyWidget extends StatelessWidget {
  final _appRouter = AppRouter();
  @override
  Widget build(BuildContext context) {
  ........`
  
  Above the `build` method
