### ISSUE TITLE
A good way to create tabs in web application?

### ISSUE THREAD

**Issue by AscentionOne** [Milad-Akarie/auto_route_library#760]
Hi @Milad-Akarie, 

I have a general question about how to implement tabs in web applications. For example, in web app, we usually have a top navigation bar or side menu that navigates between different pages (route). My first intuition is that we can use tabsRouter like in a mobile app.  However, AutoTabsScaffold seems not to work well if I want to put the navigation bar somewhere else (top, or side) and since the `bottomNavigationBuilder` exposes the `tabsRouter` that we can use. 

My question is how to implement tabs like a navigation bar? 
I had try `AutoTabsRouter()`, which will work. 

However, there is another question. If I want to implement whether the current tab is active (the button is highlighted with color or text is bold). How can I implement that? I try using `AutoTabsRouter()` in my web app, which works if I click the button to navigate to a different page using `AutoTabsRouter.of(context).setActiveIndex(index);`.  After I click the back button (from Chrome back button) on the web page it goes to the previous page, but the tabs are not highlighted correctly (it doesn't know the page had changed).

I try using getting the current route path and compare the name of the route and update the highlight accordingly, kinda work. But is there a better way? Thanks!

**Comment by AscentionOne** [comment]
@Milad-Akarie I am using `context.navigateTo()` in my web application now. How can I make the page rebuild every time I navigate to a route? For example, every time I navigate (click `BooksTab`) to the /book route. The first time it will build the page. However, when I click it again I want it to rebuild the page again. Since I have pagination in it. I want the pagination page to be set to 1 (user might be at page 2, or 3 .etc) every time I click the book `BooksTab`. Thanks! 😁

**Comment by Milad-Akarie** [comment]
Hell, @AscentionOne hmm this's a tough one, I don't think this's possible with the current setup, the tabsRouter will only be notified when the active tab is changed which makes sense because it's a change notifier. guess you're gonna have to depend on your state management package to handle this.

**Comment by AscentionOne** [comment]
@Milad-Akarie Thanks, I am agree with your suggestion. Need the state management to manage this. 😊

**Comment by AscentionOne** [comment]
Hi, @Milad-Akarie back to the `willPopScopes` question. I am trying to implement a setting page that will warn users when they are leaving the page and ask them if they want to save the changes. Like the gif below I record from gmail. How to implement this with `auto_route` in web application? Will the router know when the user is navigating to other routes? Thank you😁

![navigate_to_other_page](https://user-images.githubusercontent.com/44708790/141878501-529cb323-d3b7-4b68-bd40-a4756bfca702.gif)

**Comment by IvPod** [comment]
> > @AscentionOne You tend to open issues only when I'm super busy lol. AutoTabsRouter() has an activeIndex property which you can compare with your tab widgets index's
> > `AutoTabsRouter.of(context).activeIndex`
> > if you don't want to depend on routes index directly you could have something like this:
> > ```dart
> > class _HomePageState extends State<HomePage> {
> > 
> >   final destinations = [
> >     RouteDestination(
> >       route: BooksTab(),
> >       icon: Icons.source,
> >       label: 'Books',
> >     ),
> >     RouteDestination(
> >       route: ProfileTab(),
> >       icon: Icons.person,
> >       label: 'Profile',
> >     ),
> >     RouteDestination(
> >       route: SettingsTab(tab: 'default'),
> >       icon: Icons.settings,
> >       label: 'Settings',
> >     ),
> >   ];
> > 
> >   @override
> >   Widget build(context) {
> >     // builder will rebuild everytime this router's stack
> >     // updates
> >     // we need it to indicate which NavigationRailDestination is active
> >     return  AutoTabsRouter(builder: (context, child, animation) {
> >             // we check for active route index by using
> >             // router.isRouteActive method
> >             var activeIndex = destinations.indexWhere(
> >               (d) => context.tabsRouter.isRouteActive(d.route.routeName),
> >             );
> >             // there might be no active route until router is mounted
> >             // so we play safe
> >             if (activeIndex == -1) {
> >               activeIndex = 0;
> >             }
> >             return Row(
> >               children: [
> >                 NavigationRail(
> >                   destinations: destinations
> >                       .map((item) => NavigationRailDestination(
> >                             icon: Icon(item.icon),
> >                             label: Text(item.label),
> >                           ))
> >                       .toList(),
> >                   selectedIndex: activeIndex,
> >                   onDestinationSelected: (index) {
> >                     // use navigate instead set active index
> >                     context.navigateTo(destinations[index].route);
> >                   },
> >                 ),
> >                 // child is the rendered route stack
> >                 Expanded(child: child)
> >               ],
> >             );
> >           });
> > }
> > ```
> 
> If you put a Transition on these Routes e.g Fadeup, the Navigation Rail will also get animated

The easiest solution to get rid of such animation is to wrap child in ClipRect.

Expanded(child: ClipRect(child: child)),
