### ISSUE TITLE
possible bug when handling web URLs in version 2.4.2

### ISSUE THREAD

**Issue by raduungurean** [Milad-Akarie/auto_route_library#763]
Hello,

As mentioned [in this comment](https://github.com/Milad-Akarie/auto_route_library/issues/540#issuecomment-841354776) the most suitable way for restoring the app state after refreshing the web page is to use the `AutoRouter.declarative` feature.

But with auto_route 2.4.2 I did experience this:

- I implemented onNavigate and when pressing back in the browser, `onNavigate` is triggered twice causing the URL to blink for a second.
- also another strange behavior is this:
-- 1 I click a book in the list 
-- 2 after refreshing the page it stays at /book/1 (and the app state seems correctly loaded - I see the book and the back button in the appBar)
-- 3 when hovering the mouse over anything in the webpage it changes the url to homepage (/), but without changing the content. Basically it works fine but the URL is wrong (/ - homepage instead of book/1). It is weird that this only happens when hovering the page

I switched to 2.3.1 and everything seems to be working fine

Also I suspect that parts of this behavior is also happening when using `initialDeepLink` instead of declarative routes.

```dart
class _BooksPageWrapperState extends State<BooksPageWrapper> {
  int? _id;
  @override
  Widget build(BuildContext context) {
    return AutoRouter.declarative(
      onPopRoute: (RouteMatch route, results) {
        if (BookDetailsRoute.name == route.routeName) {
          setState(() {
            _id = null;
          });
        }
      },
      onNavigate: (List<RouteMatch> matches, initial) {
        if (matches.isNotEmpty) {
          if (BookDetailsRoute.name == matches.last.routeName) {
            // print('when pressing back I see this message two times');
            if (matches.last.pathParams.get('id') != null) {
              _id = int.parse(matches.last.pathParams.get('id'));
            }
          } else if (BooksListRoute.name == matches.last.routeName) {
            _id = null;
          }
        }
        if (!initial) {
          setState(() {});
        }
      },
      routes: (BuildContext context) {
        return [
          BooksListRoute(onNext: (result) {
            setState(() {
              _id = result;
            });
          }),
          if (_id != null) BookDetailsRoute(id: _id),
        ];
      },
    );
  }
}
```

This is my app router code:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page|Screen,Route',
  // transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
  // routes: <AutoRoute>[
  //   AutoRoute(page: BooksListPage, path: '/books', initial: true),
  //   AutoRoute(page: BookDetailsPage, path: '/books/:id'),
  // ],
  routes: <AutoRoute>[
    AutoRoute(
      path: "/",
      initial: true,
      page: BooksPageWrapper,
      children: [
        AutoRoute(
          page: BooksListPage,
          path: '',
        ),
        CustomRoute(
          page: BookDetailsPage,
          path: 'book/:id',
          transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
        ),
      ],
    ),
  ],
)
class $AppRouter {}
```

Cheers!

**Comment by bartekpacia** [comment]
I'm also experiencing this problem.

@Milad-Akarie We'd appreciate your response:)
