### ISSUE TITLE
Improve helper functions

### ISSUE THREAD

**Issue by TarekkMA** [Milad-Akarie/auto_route_library#77]
I really like the helper functions feature since it can encourage type safety. And I have a few features that I think can make helper functions more useful.

- Add ``@required`` annotation for required types, the arguments have the required annotations correctly but the helper functions lack it.
- Add the option to define a return type for routes. right now all helper functions have ``Future<dynamic>`` return. It would be much better if the return type of a route is defined optionally in ``MaterialRoute | CupertinoRoute | CustomRoute`` annotations.
```dart
@MaterialAutoRouter()
class $Router {
  @MaterialRoute(resultType: User)
  LoginScreen loginScreenRoute;
}
```
- Add more helper function. Right now the generated code only supports ``push***``, I suggest we add more functions. like ``popAndPush***`` , ``push***AndRemoveUntil`` , ``pushReplacement***``

What do you think about them?

**Comment by Milad-Akarie** [comment]
Hey @TarekkMA Thanks for your hard work!
I'll be working on the @required part. 
as for the resultType it's already there under returnType.

I'm not sure about generating all 3 push methods for every route. maybe if we can somehow make them optionals? as in the user choses what extension methods to generate for what route?

**Comment by TarekkMA** [comment]
Yeah, I see there is a ``returnType`` field. The README doesn't mention it. and we can add an option on ``@AutoRouter`` to generate them for all routes or by route basis with the ``@AutoRoute`` annotation.

I don't know how it should look like. but this form comes to my mind.
```dart
//helperExtensions deafults to having only PUSH, if generateNavigationHelperExtension is true
//we can also infer that ``generateNavigationHelperExtension`` is true when helperExtensions is set to something
//if not defined by ``Route`` it should inherit options from the ``Router``
//and in this form we can have the option to generate only for one route.
@MaterialAutoRouter(
  generateNavigationHelperExtension: true
  helperExtensions:[
    PUSH,
    POP_AND_PUSH,
    PUSH_AND_REMOVE_UNTIL,
    PUSH_REPLACEMENT,
  ]
)
class $Router {
  @initial
  SplashScreen splashScreen;

  @MaterialRoute(
    helperExtensions:[
      PUSH,
      PUSH_REPLACEMENT,
    ]
  )
  HomeScreen homeScreen;
}
```

**Comment by theweiweiway** [comment]
closing due to:
- stale issue
- 1.0.x has more helper extensions
