### ISSUE TITLE
Allow code splitting

### ISSUE THREAD

**Issue by dochan-consultis** [Milad-Akarie/auto_route_library#777]
It would be helpful if we could split code based on routes. It would mean that first page can load drastically faster because other routes and their dependecies wouldn't be loaded yet. This would affect only web version.

 Since[ flutter has already support for it](https://github.com/flutter/flutter/issues/50196#issuecomment-582503489) make this happen would be easy with old generator.

Instead of this:

```dart

import 'package:auto_route/auto_route.dart' as _i1;
import 'home/view/home_page.dart' as _i3;

@override
final Map<String, _i1.PageFactory> pagesMap = {
  HomeRoute.name: (routeData) {
    return _i1.MaterialPageX<Object>(
      routeData: routeData,
      child: const _i3.HomePage(),
    );
  }
};

```

We could do this:
```dart

import 'package:auto_route/auto_route.dart' as _i1;
import 'package:flutter/material.dart' as _i2;
import 'home/view/home_page.dart' deferred as _i3; //deferred is the secret sauce

@override
final Map<String, _i1.PageFactory> pagesMap = {
  HomeRoute.name: (routeData) {
    return _i1.MaterialPageX<Object>(
      routeData: routeData,
      child: FutureBuilder(
        future: _i3.loadLibrary(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return _i3.HomePage();
          } else {
            return _i2.Center(child: _i2.CircularProgressIndicator());
          }
        },
      ),
    );
  }
};
```

I'm not sure if this can be achieved when router is used with `part of` though.

**Comment by dochan-consultis** [comment]
This comparison contains 18 pages of various complexity. Unfortunately I can't share code of this test. I've tried to create this comparison on example included in this project but pages included in example are so simple that it resulted in bigger size when split.


Here are test results.

## Files:
### Without splitting:
![1 without_splitting_canvaskit](https://user-images.githubusercontent.com/51478129/139813378-6dcee32f-8c64-4ad7-8c2d-def9ac9e1c60.png)

### With splitting:
![1 with_splitting_canvaskit](https://user-images.githubusercontent.com/51478129/139813413-81bc2a53-33da-4746-8ff7-f3ba80b1a9c9.png)

## Load times:

### Without splitting:
![3 load without_splitting_canvaskit](https://user-images.githubusercontent.com/51478129/139813452-9b059daa-1f98-42a1-930a-0d6c84a99aff.png)

### With splitting:
![3 load with_splitting_canvaskit](https://user-images.githubusercontent.com/51478129/139813478-050d5d33-8085-4a57-b3d0-7c3e7b15a3f4.png)

**Comment by slavap** [comment]
I have the problem with deferredLoading and AutoRouteWrapper - wrappedRoute() method is never called!

CustomRoute(page: HomePage, deferredLoading: true, )

class HomePage extends StatelessWidget implements AutoRouteWrapper {
  @override
  Widget wrappedRoute(BuildContext context) {}
}

**Comment by ranulfo** [comment]
so for me to enable code splitting just use  `deferredLoading: true` or do I have to do some other configuration? does this in itself already guarantee me a performance gain in flutter web in production?

**Comment by olegyablokov** [comment]
What is `pagesMap`? I cannot find it in docs. I use `@override final List<AutoRoute> routes = [...]`
