### ISSUE TITLE
AutoTabsRouter is not invoking builder when children are pushed inside tab

### ISSUE THREAD

**Issue by tapkain** [Milad-Akarie/auto_route_library#779]
Hi, the issue name is self-explanatory. Why this matters - I want to hide the bottom tab bar when a specific route is being pushed but it does not invoke the build method. Maybe for this specific case to hide the bottom tab bar it would nice to provide a callback which is invoked each time the navigation stack is updated?

**Comment by markbulingit** [comment]
HEY FLUTTER WEB DEVS! After days of toubleshooting I've found the problem, when dealing with meta on a child route, make sure the child route has a path name like /task.
