### ISSUE TITLE
Custom naming for initial Routes

### ISSUE THREAD

**Issue by igoriuz** [Milad-Akarie/auto_route_library#78]
I would prefer to have more flexibility regarding nested named root routes. Therefore it would be awesome, if i could name the root route different than "/" when using sub navigators so i dont get routes like `main-route//`.

Neither `@initial` nor `@CustomRoute` allows to be named **and** initial. 

And btw: Thanks for this package. Great work ;)

**Comment by Milad-Akarie** [comment]
Hey @igoriuz try not annotating the route with @ initial then manually set the initialRoute in your ExtendedNavigator. 
I'm working on making leading slashes optional for non initial routes.

**Comment by FilledStacks** [comment]
Any update on this. The leading slash is causing the initial route to always be pushed even if you set the starting route to a different route. Which is what I usually do during development. 

Flutter does a deep link style navigation so having the '/' infront of the route name will always push initialRoute then actual route. When I don't mark an initial route and press back on the first route it shows me the red screen where I would expect it to close the app. 

I can file a different issue for that if you'd like.

**Comment by theweiweiway** [comment]
newest auto route version and issue #518 demonstrates how to fix this (scroll down) 

For convenience:
```dart
              AutoRoute<dynamic>(
                path: 'overview',
                page: EmptyPage2,
               initial: true, // will auto_generate  RedirectRoute(path: '', redirectTo: 'overview'),
              ),
```
