### ISSUE TITLE
router.push will push the route behind the current widget route

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#782]
Hey again,
The last updates introduced a new bug with pushWidget.
The actual pushing of widget is working fine, the bug itself happen when pushing a route when the current page is a widget and not a route.

So the flow is like this:
Initial route -> Push widget -> Push route -> the pushed route is not showing -> popping the widget route -> the pushed route is showing.

It's like auto route doesn't acknowledge the pushed widget is in the stack.

Also worth noting that the route I'm trying to push is defined in the root, so there shouldn't be a problem of nesting. 

Please help,
Thanks

**Comment by proninyaroslav** [comment]
I faced the same problem. I have a button that creates a dropdown menu using a modal window. When an item inside a dialog is clicked, another window is opened using `auto_route`, and the modal window should be closed. At this point,  `setState() or markNeedsBuild() called during build` error occurs. As it turned out, this is due to the fact that I call `setState`  inside the button widget to hide the modal window.

**Comment by naamapps** [comment]
@Milad-Akarie Sorry for the delay,
I have been busy with work.

I managed to replicate both issues (push behind and the error thrown).

Here is the repo https://github.com/naamapps/auto_route_bug
For you to see both issues I wrote a comment inside the code (`first_page.dart`) but I'll write it here too just in case:
1. To see the first main issue (push behind current route) - Change the `useRootNavigator` to true in the showDialog function.
2. To see the `setState() or markNeedsBuild() called during build` error, change the `useRootNavigator` to false.

After you see the dialog, tap the "open second page" button, and you'll see that the nested route is pushed behind the dialog if the useRootNavigator is true.
And if it's false, the correct (root) route is pushed instead of the nested one but an error is thrown.

The desired behaviour is when setting useRootNavigator to true and then pushing the route, it will be above the dialog. And if setting useRootNavigator to false, the error should not be thrown.

Thanks

**Comment by naamapps** [comment]
@Milad-Akarie, This bug is **not fixed** with latest version 3.1.1!
Please advise :)
Thanks

**Comment by Milad-Akarie** [comment]
@naamapps I forgot to write a replay so I apologize for that.
I fixed the error when useRootNavigator is set to false.

regarding the other case

**Pages proceeded with '*' are the visible ones**

in your example your hierarchy looks something like this
```
"root"{
   * "home":{  
      * "page_one"
   }
}
```
both `root/home` and `home/page_one` are topmost in their stacks therefor visible

then you add a dialog to the root stack and now your hierarchy looks like this
```
"root"{
   "home":{
      * "page_one"
   },
*  "dialog"
}
```
the topmost/visible routes are now `root/dialog` and `home/page_one`

then you add page_two to the home stack and now your hierarchy looks like this

```
"root"{
   "home":{
      "page_one"
   * "page_two"
   },
  *  "dialog"
}
```
I hope that helps you understand what's going on.
if you have any other questions don't hesitate to ask

**Comment by naamapps** [comment]
Hey @Milad-Akarie,
The `setState() or markNeedsBuild() called during build` error is indeed fixed. 👍 

The other case however I can't seem to understand your explanation.

First of all, In versions prior to 3.0.0 this behaviour didn't happen (Pushing with root navigator and then pushing a route worked as expected).

Second of all, even if I push without root navigator but with HomeRouter buildContext like so:
```
context: (appRouter.innerRouterOf(HomeRouter.name) as StackRouter?)?.navigatorKey.currentContext!,
useRootNavigator: false
```

the dialog is above all routes (like it should), but when pushing the second page it's pushing under the dialog (in the nested route).

I have updated the example  https://github.com/naamapps/auto_route_bug
Now it is more like in my application.

The thing I don't understand is why the route is pushed behind the dialog when I pushed the dialog with the context of HomeRouter.
The SecondRoute is declared both in the FirstRouter and HomeRouter, I expect autoRoute to acknowledge that if I push with the context of HomeRouter, then the second route declared in HomeRouter will be used in the push operation instead of the nested one.

I hope that make sense.
Thanks

**Comment by naamapps** [comment]
@Milad-Akarie I have found another bug.
Updated the example with a new button.
a push with HomeRouter doesn't open the second page but opens the nested route instead.

Maybe this is connected with the problem I wrote above.

**Comment by naamapps** [comment]
@Milad-Akarie Hey, did you get the chance to take a look at this?

**Comment by naamapps** [comment]
@Milad-Akarie  ?

**Comment by Milad-Akarie** [comment]
@naamapps  I got really busy, sorry about that.

Is the nested page an initial page?

**Comment by naamapps** [comment]
@Milad-Akarie No it is not.

**Comment by Milad-Akarie** [comment]
Please share route set-up and push action

**Comment by naamapps** [comment]
@Milad-Akarie It's all in the repo I shared.
https://github.com/naamapps/auto_route_bug

**Comment by Milad-Akarie** [comment]
I'll take a look

**Comment by Milad-Akarie** [comment]
@naamapps newer versions of auto_route try to automatically find the right router/scope that can handle the pushed route, no matter where you're pushing it from, this works great for almost all use cases, the logic is simple, it checks if the top most router can handle the passed route if not it delegates the navigation action to parent and so on, in your case you have a route that can be handled by two routers, and the very top one has  the  highest priority.
and the way to handle this is by giving the router the parent route as well like follows

`context.navigateTo(const HomeRouter(children: [SecondRoute()]));
`
here I used `navigate` instead of `push` so the HomeRouter won't get re-pushed if it's already in stack. 

also, if this is how your actual route setup is I think you maybe using unnecessary extra router which is `HomeRouter`

**Comment by naamapps** [comment]
@Milad-Akarie, It still doesn't make sense to me.
Why is the route is pushed under the dialog even if it the top most route (root navigator)?
Or is it the other way around, the topmost route is first child (under every other route) in the stack?

Even so, I think the logic to determine which route to use needs an improvement (or needs to go back to the way it used to be), in my opinion it should always use the context for reference where in the stack the current route is.

It doesn't make sense to me that I'm passing the root router (or home router) context to AutoRouter.of(context) and eventually the route that is being push is under the root navigator. It should use the context for that and acknowledge that I'm in the root navigator right now and it should push the correct route.

And even when pushing specifically from homeRouter, it still pushes the nested route!
`(appRouter.innerRouterOf(HomeRouter.name) as StackRouter?).push(...)`

I think AutoRoute should give the developers freedom to determine which route to use by the context/router they use.
The option you suggested does work
`context.navigateTo(const HomeRouter(children: [SecondRoute()]));`
But, I need to be able to push the same route over and over again (like Instagram) and I can't use push because it will push HomeRouter again!

Could you please explain why those changes was made in the newer versions of AutoRoute?
It worked perfect before and now my app is really buggy since upgrading.

About the HomeRouter:
I have two root routes HomeRouter and AuthRouter - I have guards for both of them so if I remove HomeRouter I need to put the guard in every declared route, which I tried to prevent from doing.

**Comment by naamapps** [comment]
@Milad-Akarie Friendly ping :)

**Comment by naamapps** [comment]
Hey @Milad-Akarie,
This issue still exists in latest version!
Please help

**Comment by naamapps** [comment]
@Milad-Akarie I have updated the bug repo https://github.com/naamapps/auto_route_bug.
Updated to latest auto_route 5.0.0 and flutter 3.0.

My main issue is with the first button.
1. Open dialog
2. Press open second page
3. The second page will appear behind the dialog! even when it is considered root (it hides the nav bar).

Please help!
How to fix this? I tried everything.
It always appear behind the dialog no matter what.

**Comment by naamapps** [comment]
@Milad-Akarie Please take a look at this.
I can't seem to figure out the cause of this.
Surely a bug in the package.
