### ISSUE TITLE
Navigation issue: context.router.pop()

### ISSUE THREAD

**Issue by TaejunLim7588** [Milad-Akarie/auto_route_library#789]
Hi! I'm developing a web app using auto route and have an issue regarding navigation. I wish to use context.router.pop(); as a back button to go back to the previous page. But when I used it, a new page is pushed to the stack. Could you please give me any hints on this issue? Thanks a lot!!
![화면 기록 2021-10-26 오후 5 30 31](https://user-images.githubusercontent.com/70195559/138845128-72150fff-9d6c-4bd6-8811-a85f3c2bd3fc.gif)
!

**Comment by TaejunLim7588** [comment]
So, is it impossible to implements the browser's back button with auto route?

**Comment by Hennythehun** [comment]
I don't think it's possible with AutoRoute. A quick search on the web doesn't seem like there is an easy way for flutter in general. However, if you're serious about it, you might be able to find a way to store the navigation history in your app's memory. You'd probably want to figure out how to distinguish a user's session, and within each session, you'd want to keep track of the browser's history and sync it with the browser. I hope that make sense.

I found this [video](https://www.youtube.com/watch?v=05Eeum2QMkc) that could get you in the right direction.
