### ISSUE TITLE
wrappedRoute BuildContext

### ISSUE THREAD

**Issue by moti0375** [Milad-Akarie/auto_route_library#79]
Hi, 

I have a question about the wrappedRoute option

When using wrappedRoute, Is there a way to add option to forward the buildContext so it will be available for wrapping the route?
Something like this:

    `abstract class AutoRouteWrapper {
  
      Widget wrappedRoute(BuildContext context);

     }`

Then in the widget:

    `
     @override
     Widget wrappedRoute(BuildContext context) {
     var service = InheritedWidgetService.of(context); //Right now, this will be null as the context not 
      available

     return BlocProvider<PageBloc>(
         create(_) => MyBloc(service: service),
         child: this
     );
     }`

Then in the generated code it should be like this:

    `case Routes.loginPage:
           return MaterialPageRoute<dynamic>(
           builder: (**context**) => <WidgetInstance>(). wrappedRoute(**context**),
            settings: settings,
         )`

Thanks, 
Moti.

**Comment by Milad-Akarie** [comment]
Hey Moti, you can't use the BlocProvider's context? 
I'll include it anyways.

**Comment by moti0375** [comment]
Hi Milad,

Thanks for your response!

I've tried this and and seems to be null or not higher enough in my case,
you may try to make some small example.

Nevertheless, even if the provider context not null, it might be different
than the context forward by the Navigator which is much higher in the
widget tree.
Therefore it is better to use it for accessing services higher in the tree
such as Localization or Theme.

What do you think?

Regards,
Moti.



בתאריך שבת, 25 באפר׳ 2020, 22:08, מאת Milad Alakarie ‏<
notifications@github.com>:

**Comment by Milad-Akarie** [comment]
@moti0375 it makes sense to provide the route's context to the wrappedRoute anyways. 
It will be included in the next build. 
Thanks for your report.

**Comment by moti0375** [comment]
Hi Milad,

Thanks for your support and I'am glad you agree.

Regards,
Moti.

**Comment by Milad-Akarie** [comment]
Hey @moti0375  implemented in 
auto_route: 0.4.5
auto_route_generator: 0.4.7

**Comment by moti0375** [comment]
Awesome thanks!

Regards,
Moti.

בתאריך יום ב׳, 27 באפר׳ 2020, 00:06, מאת Milad Alakarie ‏<
notifications@github.com>:
