### ISSUE TITLE
AutoRoute and bloc pattern

### ISSUE THREAD

**Issue by lhengl** [Milad-Akarie/auto_route_library#792]
Hi Milad,

Amazing package. I've started using this and it's a breeze to navigate between pages. However, I've hit a wall trying to convert to a bloc pattern using AutoRoute with my login module. I've tried for days to find a solution. I've tried your tutorial on declarative routing, but it doesn't show me how I would detect other events from a bloc such as when the user "pressLogout", or "invalidated", or "deleted" (from a ban for example).

I would like to avoid using setState/StatefulWidgets because as I said I'm moving to bloc pattern. I'm using the official bloc tutorial on building a login module [here](https://bloclibrary.dev/#/flutterlogintutorial). Snippets where I'm trying to detect the user change event so that I can do something with the route:

```
class _AppViewState extends State<AppView> {
  final _navigatorKey = GlobalKey<NavigatorState>();

  NavigatorState get _navigator => _navigatorKey.currentState!;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: _navigatorKey,
      builder: (context, child) {
        return BlocListener<AuthenticationBloc, AuthenticationState>(
          listener: (context, state) {

              // Here is where I'd want to reset and push different route based on login state
              // However, autoRoute.delegate must be instantiated at the app instantiation
              // So there isn't a way for bloc states to dictate the route to rebuild. Or is there?

            switch (state.status) {
              case AuthenticationStatus.authenticated:
                _navigator.pushAndRemoveUntil<void>(
                  HomePage.route(),
                  (route) => false,
                );
                break;
              case AuthenticationStatus.unauthenticated:
                _navigator.pushAndRemoveUntil<void>(
                  LoginPage.route(),
                  (route) => false,
                );
                break;
              default:
                break;
            }
          },
          child: child,
        );
      },
      onGenerateRoute: (_) => SplashPage.route(),
    );
  }
}
```
Can you please give me some guidance as to how I can use AutoRoute in a bloc pattern as per the above comment?

Sorry for the long post, but I'm at my wits end. Thanks for reading this far.

**Comment by henk-lim** [comment]
@tahaaslam1 I no longer have a working code anymore as it has been a long time, however, these are the codes that I've been able to salvage for you. I think I updated the code to only need 2 routers - main router, and a authRouter that gates the entry into the main router. Good luck.

app_router.dart
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    authRouter,
    mainRouter,
  ],
)
class $AppRouter {}

const authRouter = AutoRoute(
  name: 'AuthRouter',
  page: AuthWrapperPage,
  path: '/auth',
  children: [
    AutoRoute(
      path: 'login',
      page: LoginPage,
      initial: true,
    ),
    AutoRoute(
      path: 'signup',
      page: SignUpPage,
    ),
    RedirectRoute(path: '*', redirectTo: ''),
  ],
);

const mainRouter = AutoRoute(
  initial: true,
  name: 'MainRouter',
  page: MainWrapperPage,
  children: [
    RedirectRoute(path: '*', redirectTo: ''),
    // ...
  ],
);
```

auth_wrapper_page.dart
```
class AuthWrapperPage extends StatelessWidget {
  const AuthWrapperPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AppCubit, AppState>(
      listener: (context, state) {
        state.whenOrNull(
          authenticated: (_) => context.router.root.replaceAll([const MainRouter()]),
        );
      },
      builder: (context, state) {
        return state.map(
          loading: (_) => const LoadingPage(),
          authenticated: (_) => const LoadingPage(),
          unAuthenticated: (_) => const AutoRouter(),
        );
      },
    );
  }
}
```



main_wrapper_page.dart
```
class MainWrapperPage extends StatelessWidget {
  const MainWrapperPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AppCubit, AppState>(
      listener: (context, state) {
        state.whenOrNull(
          unAuthenticated: (_) => context.router.root.replaceAll([const AuthRouter()]),
        );
      },
      builder: (context, state) {
        return state.map(
          loading: (_) => const LoadingPage(),
          authenticated: (_) => BlocProvider(
            create: (context) => TasksCubit(appCubit: context.read<AppCubit>()),
            child: const AutoRouter(),
          ),
          unAuthenticated: (_) => const LoadingPage(),
        );
      },
    );
  }
}
```

**Comment by tahaaslam1** [comment]
> @tahaaslam1 I no longer have a working code anymore as it has been a long time, however, these are the codes that I've been able to salvage for you. I think I updated the code to only need 2 routers - main router, and a authRouter that gates the entry into the main router. Good luck.
> 
> app_router.dart
> 
> ```
> @MaterialAutoRouter(
>   replaceInRouteName: 'Page,Route',
>   routes: [
>     authRouter,
>     mainRouter,
>   ],
> )
> class $AppRouter {}
> 
> const authRouter = AutoRoute(
>   name: 'AuthRouter',
>   page: AuthWrapperPage,
>   path: '/auth',
>   children: [
>     AutoRoute(
>       path: 'login',
>       page: LoginPage,
>       initial: true,
>     ),
>     AutoRoute(
>       path: 'signup',
>       page: SignUpPage,
>     ),
>     RedirectRoute(path: '*', redirectTo: ''),
>   ],
> );
> 
> const mainRouter = AutoRoute(
>   initial: true,
>   name: 'MainRouter',
>   page: MainWrapperPage,
>   children: [
>     RedirectRoute(path: '*', redirectTo: ''),
>     // ...
>   ],
> );
> ```
> 
> auth_wrapper_page.dart
> 
> ```
> class AuthWrapperPage extends StatelessWidget {
>   const AuthWrapperPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return BlocConsumer<AppCubit, AppState>(
>       listener: (context, state) {
>         state.whenOrNull(
>           authenticated: (_) => context.router.root.replaceAll([const MainRouter()]),
>         );
>       },
>       builder: (context, state) {
>         return state.map(
>           loading: (_) => const LoadingPage(),
>           authenticated: (_) => const LoadingPage(),
>           unAuthenticated: (_) => const AutoRouter(),
>         );
>       },
>     );
>   }
> }
> ```
> 
> main_wrapper_page.dart
> 
> ```
> class MainWrapperPage extends StatelessWidget {
>   const MainWrapperPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return BlocConsumer<AppCubit, AppState>(
>       listener: (context, state) {
>         state.whenOrNull(
>           unAuthenticated: (_) => context.router.root.replaceAll([const AuthRouter()]),
>         );
>       },
>       builder: (context, state) {
>         return state.map(
>           loading: (_) => const LoadingPage(),
>           authenticated: (_) => BlocProvider(
>             create: (context) => TasksCubit(appCubit: context.read<AppCubit>()),
>             child: const AutoRouter(),
>           ),
>           unAuthenticated: (_) => const LoadingPage(),
>         );
>       },
>     );
>   }
> }
> ```

Thanks @henk-lim this has been really helpfull <3
