### ISSUE TITLE
Web browser back and forward buttons are grey out after reloading flutter web 

### ISSUE THREAD

**Issue by alvindrakes** [Milad-Akarie/auto_route_library#793]
Good day sir, when I reload flutter web in browser, the browser's back and forward buttons are grey out even though I have pushed the stack correctly using "includePrefixMatches: true".

Here's a video showing the result:
https://www.loom.com/share/8a761d3d761d4401aca2b40e95c05f4d

Here's my router setup and app_router file. 
![image](https://user-images.githubusercontent.com/13532268/139072469-c0c27e51-13dc-4247-882b-0a0cb56e5cc7.png)

![image](https://user-images.githubusercontent.com/13532268/139072358-1c0fb26c-86bd-4ffa-b498-83933725ba72.png)

`Auto_router version: 2.4.2`

Is this caused by flutter web itself? 
Or a bug in the package? 

Thank you.

**Comment by rayk** [comment]
see [https://api.flutter.dev/flutter/widgets/BackButtonDispatcher-class.html](url)
