### ISSUE TITLE
How to pop AuthGuard Page on success login?

### ISSUE THREAD

**Issue by alejandrogiubel** [Milad-Akarie/auto_route_library#794]
When I use guard it push my LoginPage on logged out state but on success login LoginPage remain there after navigate to Secure Page and on back button take me to LoginPage again.

**Comment by deive** [comment]
I am having this issue as well. 
I have created a simple project that shows this problem at https://github.com/deive/test_auto_route

The login remains in the stack, and the home page has an up navigation button.

**Comment by deive** [comment]
I have just manually worked a way around this I think, by manually calling `AutoRouter.of(context).popForced();` just before whatever code causes the auth guard to change state.
I don't know if this is recommended or not as I have only just started learning Navigation 2 and this library.
See https://github.com/deive/test_auto_route/commit/6c9a0670da1968412b77821c4ef7db6f130e3c85

**Comment by deive** [comment]
This still leaves the back button on the web active though and causes a crash when the user tries to use it.

**Comment by Milad-Akarie** [comment]
@deive try calling removeLast then router.markUrlStateForReplace

**Comment by deive** [comment]
removeLast() works and seems like a better method to be calling here than popForced()!
However markUrlStateForReplace() doesn't remove the browsers back entry for me.
I have updated the test code if you wouldn't mind taking a look?
Thanks!

**Comment by alejandrogiubel** [comment]
AutoRouter.of(context).removeLast(); works for me. Thanks.

**Comment by deive** [comment]
> could you please provide code sample with working solution? I'm struggling with this problem now and nothing works for me
Have you checked https://github.com/deive/test_auto_route which shows this?
