### ISSUE TITLE
Dynamic index for dynamic routes

### ISSUE THREAD

**Issue by danielgchap** [Milad-Akarie/auto_route_library#797]
Hi there! 
You guys are awesome.
I worked with @Milad-Akarie in regards to passing dynamic routes to the AutoTabsScaffold and the tabsRouter updating appropriately:

https://github.com/Milad-Akarie/auto_route_library/issues/783

Thank you again for fixing that.
 
I have a new request/issue in regards to the link above, however.

It is in regards to the homeIndex or possible the activeIndex.

Here is the scenario:
We have a tab by default that we want the app to flip to upon load - lets say tab 3.

Now as mentioned in the issue above, we are awaiting a feature flag async call to return to update the routes for the AutoTabsScaffold depending on the response that depicts the users access controls to certain tabs in the app.

It seems that when those routes are updated, the tabsRouter doesn't care about homeIndex and just moves the selected tab to the first screen every time.

Desired:
Default tab, 'History' screen, is in tab 1. 
Routes has 2 screens in it, that's passed to AutoTabsScaffold. History is the second in the array, thus, tab 1.
Async call returns and puts 2 more screens in the routes array, now 4 screens.
Assuming those screens are put in front of the History screen (they are) in the array order, the desired homeIndex/activeIndex (not sure which) should now be 4.
tabsRouter just always moves it to first position.

Is this something you can do in that the homeIndex/activeIndex (whichever is relevant, not sure) is updated in accordance with the array?

I have a workaround for this currently but it's a bit verbose. 

Thanks!

**Comment by danielgchap** [comment]
@Milad-Akarie Hey brospeh, just checking in my friend. Any word?

**Comment by Milad-Akarie** [comment]
@danielgchap sorry for the delay, I got super busy.

**Comment by danielgchap** [comment]
@Milad-Akarie no worries brother. I appreciate the update! Let me know. Thank you so much!

**Comment by Milad-Akarie** [comment]
@danielgchap  the fix is in the dev branch btw.

**Comment by Milad-Akarie** [comment]
@danielgchap sorry for the delay, the update should be in the new version
```yaml
auto_route: 3.1.0
auto_route_generator: 3.1.0
```
