### ISSUE TITLE
Go back to current route when accessing a child route of another route

### ISSUE THREAD

**Issue by markbulingit** [Milad-Akarie/auto_route_library#798]
This is from ResoCoder AutoRoute Tutorial

_In this app we are navigating to routes that are located in the same router. If you want to navigate from a page in one navigation tab/router to a page in another navigation tab/router you can do that as well. Suppose you wanted to navigate from a UserProfileRoute to SinglePostRoute, you could do it like this:_

`context.navigateTo(PostsRouter(children: SinglePostRoute(postId: id))).`

The problem is, if I click the back button I don't redirect to my previous route (ProfilePage) but on the parent of the child route where I navigate (SinglePostRoute > PostsRouter)

**Comment by Milad-Akarie** [comment]
@markbulingit navigateBack was improved in the new version 
```yaml
auto_route: 3.1.0
auto_route_generator: 3.1.0
```
closing this for now.
