### ISSUE TITLE
Add fullscreenDialog to @CustomRoute

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#8]
`fullscreenDialog` is only available in `@MaterialRoute` and `@CupertinoRoute` but should also be supported by a custom route with `PageRouteBuilder`.

**Comment by Milad-Akarie** [comment]
Never saw it there before you've mentioned it lol
It should be included in the next build.
Again, Thanks for your notes.

**Comment by Milad-Akarie** [comment]
done in version 0.2.1.
