### ISSUE TITLE
Initial route with parameters

### ISSUE THREAD

**Issue by VatsalBhesaniya** [Milad-Akarie/auto_route_library#802]
Is there any way to pass arguments in initial route?
What is the proper way of passing arguments in initial route?

**Comment by Milad-Akarie** [comment]
@VatsalBhesaniya  sure,
`delegate(initialRoutes: [HomeRoute(args)]);`

**Comment by VatsalBhesaniya** [comment]
Thanks for the quick response.
I tried this and it works perfectly. But when I set the type of initialRoutes list it is showing me this error - The argument type 'dynamic' can't be assigned to the parameter type 'List<PageRouteInfo<dynamic>>?'

`initialRoutes: PageRouteInfo<dynamic>[
          HomePageRoute(
            title: widget.config.appTitle,
          ),
        ],`

Please let me know what my mistake is.

**Comment by Milad-Akarie** [comment]
I think you're missing a type brackets
replace this `PageRouteInfo<dynamic> `with this `<PageRouteInfo<dynamic>>`

**Comment by VatsalBhesaniya** [comment]
> I think you're missing a type brackets replace this `PageRouteInfo<dynamic> `with this `<PageRouteInfo<dynamic>>`

Yes, I am missing type brackets. Thanks.

**Comment by VatsalBhesaniya** [comment]
I also wanted to know that if I set the initial route in delegate then do we need to set the initial route in the routes list? I just want to confirm what is the best practice here.

My question is do we need to add HomePage route here?

`@MaterialAutoRouter(
  routes: <AutoRoute<dynamic>>[
    AutoRoute<HomePage>(
      path: '/',
      page: HomePage,
    ),
  ],
)
class $AppRouter {}`

**Comment by Milad-Akarie** [comment]
@VatsalBhesaniya yes you do, you won't have a `HomePageRoute` class if you don't add it to routes list.

**Comment by VatsalBhesaniya** [comment]
I am using [https://pub.dev/packages/flutter_i18n](url) and I wanted to wrap HomePage with I18n Widget.
To do this I should use HomeWrapperPage, right?

**Comment by Milad-Akarie** [comment]
@VatsalBhesaniya  shouldn't this widget be wrapping the whole App?

**Comment by VatsalBhesaniya** [comment]
> @VatsalBhesaniya shouldn't this widget be wrapping the whole App?

It is recommended to wrap the widget tree with the I18n widget, below the MaterialApp.
```
@override
Widget build(BuildContext context) {
  return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', "US"),
        const Locale('pt', "BR"),
      ],
      home: I18n(
        child: HomePage(),
      ),
  );
}
```

But with `auto_route` we use `MaterialApp.router` which does not have the `home` parameter. And we can not wrap the `HomePageRoute` in the `I18n` widget in `initialRoutes`.

Please let me know what should be the proper way of wrapping the `HomePage` with `I18n`.

**Comment by Milad-Akarie** [comment]
@VatsalBhesaniya use the builder property inside of material app 
`builder:(context,child) => I18n(child: child!);`

**Comment by VatsalBhesaniya** [comment]
my_app.dart
```
class MyApp extends StatefulWidget {
  const MyApp(this.config);

  final FlavorConfig config;

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  final AppRouter _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
      title: 'Auto route demo app',
      localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: supportedLocales,
      theme: widget.config.lightTheme,
      darkTheme: widget.config.darkTheme,
      themeMode: ThemeMode.system,
      locale: context.watch<MyAppBloc>().state.selectedlocale,
      builder: (BuildContext context, Widget? child) {
        return Overlay(
          initialEntries: <OverlayEntry>[
            OverlayEntry(
              builder: (BuildContext context) => I18n(
                child: HomePage(title: widget.config.appTitle),
              ),
            ),
          ],
        );
      },
      debugShowCheckedModeBanner: false,
      localeResolutionCallback:
          (Locale? locale, Iterable<Locale> supportedLocales) {
        if (locale != null) {
          context
              .read<MyAppBloc>()
              .add(MyAppEvent.localeChanged(selectedLocale: locale));
        }
      },
    );
  }
}
```

I need to use `overlay` widget because of this exception - Tooltip widgets require an Overlay widget ancestor for correct operation
I am using tooltip in `FloatingActionButton`.

router.dart
```
@MaterialAutoRouter(
  routes: <AutoRoute<dynamic>>[
    AutoRoute<HomePage>(
      path: '/',
      page: HomePage,
    ),
    AutoRoute<SettingsPage>(
      path: 'settings',
      name: 'SettingsRouter',
      page: SettingsPage,
    ),
  ],
)
class $AppRouter {}
```

router.gr.dart
```
class AppRouter extends _i3.RootStackRouter {
  AppRouter([_i4.GlobalKey<_i4.NavigatorState>? navigatorKey])
      : super(navigatorKey);

  @override
  final Map<String, _i3.PageFactory> pagesMap = {
    HomePageRoute.name: (routeData) {
      final args = routeData.argsAs<HomePageRouteArgs>();
      return _i3.MaterialPageX<_i1.HomePage>(
          routeData: routeData,
          child: _i1.HomePage(key: args.key, title: args.title));
    },
    SettingsRouter.name: (routeData) {
      return _i3.MaterialPageX<_i2.SettingsPage>(
          routeData: routeData, child: const _i2.SettingsPage());
    }
  };

  @override
  List<_i3.RouteConfig> get routes => [
        _i3.RouteConfig(HomePageRoute.name, path: '/'),
        _i3.RouteConfig(SettingsRouter.name, path: 'settings')
      ];
}

/// generated route for [_i1.HomePage]
class HomePageRoute extends _i3.PageRouteInfo<HomePageRouteArgs> {
  HomePageRoute({_i4.Key? key, required String title})
      : super(name, path: '/', args: HomePageRouteArgs(key: key, title: title));

  static const String name = 'HomePageRoute';
}

class HomePageRouteArgs {
  const HomePageRouteArgs({this.key, required this.title});

  final _i4.Key? key;

  final String title;
}

/// generated route for [_i2.SettingsPage]
class SettingsRouter extends _i3.PageRouteInfo<void> {
  const SettingsRouter() : super(name, path: 'settings');

  static const String name = 'SettingsRouter';
}
```

home_page.dart
```
ElevatedButton(
   onPressed: () {
      context.router.push(
         const SettingsRouter(),
      );
   },
   child: Text('Settings'),
),
```

On `submit` button click I am getting this exception - AutoRouter operation requested with a context that does not include an AutoRouter.

Could you please explain what is the mistake here?

**Comment by Milad-Akarie** [comment]
this child here is the router widget, you're ignoring the router and passing a home widget.
```dart
    builder: (BuildContext context, Widget? child) {
        return Overlay(
          initialEntries: <OverlayEntry>[
            OverlayEntry(
              builder: (BuildContext context) => I18n(
                child: HomePage(title: widget.config.appTitle),
              ),
            ),
          ],
        );
      },
```
try this
```dart
    builder: (BuildContext context, Widget? router) {
        return Overlay(
          initialEntries: <OverlayEntry>[
            OverlayEntry(
              builder: (BuildContext context) => I18n(
                child: router!,
              ),
            ),
          ],
        );
      },
```
why do you need an Overlay widget? MaterialApp has an Overlay widgets.

**Comment by VatsalBhesaniya** [comment]
When I am passing the router widget like this.
```
builder: (_, Widget? router) {
   return I18n(
      child: router!,
   );
},
```
I am getting this exception - HomePageRouteArgs can not be null because it has a required parameter.
And couldn't load the `HomePage`.

**Comment by thestiv** [comment]
> @VatsalBhesaniya sure, `delegate(initialRoutes: [HomeRoute(args)]);`

Be great if this could be added to the docs...took me a while to find this! :)

**Comment by JonasJW** [comment]
> Is there any way to pass arguments in initial route? What is the proper way of passing arguments in initial route?

I don't really understand how/where I apply this, could someone give me a practical code snippet?
