### ISSUE TITLE
Router pop method should not fire the WillPopScope callback

### ISSUE THREAD

**Issue by jopmiddelkamp** [Milad-Akarie/auto_route_library#803]
The `WillPopScope` Widget callback should not fire when the `router.pop()` gets called. In one of my projects, I've to write a workaround to keep track of certain states which I never had to before. 

To give an example of default Flutter behaviour:
https://dartpad.dev/?id=af9cb60426a0b353af19e3032b02f993&null_safety=true

**Comment by Milad-Akarie** [comment]
@jopmiddelkamp in `auto_route` that's called `popForced():`

**Comment by jopmiddelkamp** [comment]
Thanks for the quick reaction @Milad-Akarie. What is the reason it's set up like it is?  Still think it's a bit strange that the default behaviour of Flutters pop doesn't match the auto_route pop. 

Is it not an idea to change this to be the default for pop as well? I think most people would expect the router pop to behave the same as Flutter's navigator pop. It would make more sense to me that pop behave the same and that there would be an alternative method (for whatever reason this is needed) that would always trigger the WillPopScope.

If yes or no, either way I think it good to add this to the documentation on https://autoroute.vercel.app/

**Comment by Milad-Akarie** [comment]
@jopmiddelkamp To be honest when I first implemented this I thought `Navigator.mayPop` didn't pop if there's only one route left in stack, I thought both methods were intercepted by `willPopScope`.

**Comment by jopmiddelkamp** [comment]
Ahh ok. But don't you agree it makes more sense to rename the router `pop` to `maybePop` and `popForced` to `pop`?

**Comment by Milad-Akarie** [comment]
@jopmiddelkamp I thought about it before, after all of this time I feel like it may confuse users now.

**Comment by jopmiddelkamp** [comment]
@Milad-Akarie well some clarification in the breaking changes section of the release notes and the problem is solved, right? Now I think many of the new uses will be confused.

**Comment by Milad-Akarie** [comment]
@jopmiddelkamp will see what I can do.

**Comment by xiprox** [comment]
Popping in (pun unintended) to say I lost a few hours to this yesterday when `pop` wasn't working in a page. Didn't see `popForced` as I was looking at `context.` and not `context.router.`. In the end diving deeper into the navigator code revealed the problem.

If the decision ends up being not changing the package after all, adding a note to the documentation would certainly be helpful.

**Comment by zeshanghayoomi** [comment]
@Milad-Akarie I believe there is a bug when `context.router.pop()` using flutter's new widget `PopScope`. So basically what happens is if a `@RoutePage()` making use of `PopScope` widget and if you try to pop this route then `onPopInvoked()` gets called infinitely without popping the current page.
