### ISSUE TITLE
popUntilRouteWithName with result parameter

### ISSUE THREAD

**Issue by tengyeekong** [Milad-Akarie/auto_route_library#804]
Is there any way to pass data back to a page with popUntil or popUntilRouteWithName?

**Comment by Milad-Akarie** [comment]
@tengyeekong  sorry for the delay, I had to test it first.
try this

```dart
   context.router.popUntil((route) {
            if (route.settings.name == TargetRoute.name) {
              route.didPop('Result');
              return true;
            }
            return false;
        });
```

**Comment by tengyeekong** [comment]
Thanks @Milad-Akarie!
Unfortunately your code sample doesn't seems to work well on my app, it pops further after reaching TargetRoute.
By referring to your code sample, I've come out with this and it works well!
`
final stackData = appRouter.stackData;
final mainRouteIndex = stackData.indexWhere((e) => e.name == MainRoute.name);
final popRouteIndex = mainRouteIndex + 1;

if (stackData.length > popRouteIndex) {
  final popRoute = stackData[popRouteIndex];
  appRouter.popUntil((route) {
    if (route.settings.name == popRoute.name) {
      return route.didPop('Result');
    }
    return false;
  });
}
`

**Comment by rd-martin-jaeger** [comment]
reoccurring case 👋🏿

**Comment by artem-romanov** [comment]
@Milad-Akarie your example seems not working. Same problems as @tengyeekong. With freezing the UI.

**Comment by artem-romanov** [comment]
In case if anyone still looking for solution. Just tried to write this extension which can pop until route name and provide data.

```
extension RouterUtils<T extends Object?> on StackRouter {
  void popUntilNamed(
    String routeName,
    T? result, {
    bool forced = false,
  }) {
    final appRouter = this;
    final stackData = appRouter.stackData;
    final mainRouteIndex = stackData.indexWhere((e) => e.name == routeName);
    final popRouteIndex = mainRouteIndex + 1;
    final popRouteName = stackData[popRouteIndex].route.name;

    if (stackData.length <= popRouteIndex) {
      return;
    }

    for (var i = stackData.length - 1; i >= 0; i--) {
      final routeName = stackData[i].route.name;
      if (routeName == popRouteName) {
        forced ? popForced(result) : pop(result);
        break;
      }

      forced ? popForced(result) : pop(result);
    }
  }
}
```

You can use it like this:

```
context.router.popUntilNamed('HomeRoute', true, forced: true);
```

Might be buggy, not enough tested yet.
