### ISSUE TITLE
How to nest path parameter routes

### ISSUE THREAD

**Issue by xiprox** [Milad-Akarie/auto_route_library#805]
I've been struggling to achieve this and haven't been able to find a solution in the docs or in the issues.

I'm trying to do something like `/journeys/:journeyId/:weekId/:dayId`.

I've come up with various route configurations and gotten various errors and issues during my attempts and I haven't noted them all down, so apologies for not being concrete enough, but currently, this is my setup:

```dart
...
        AutoRoute(
          path: 'journeys',
          name: 'JourneysRouter',
          page: JourneysWrapperPage,
          children: [
            AutoRoute(path: '', page: JourneysPage),
            AutoRoute(
              path: ':journey',
              page: JourneyDetailsPage,
              children: [
                AutoRoute(
                  path: ':week',
                  page: WeekPage,
                  children: [
                    AutoRoute(path: ':day', page: DayPage),
                  ],
                ),
              ],
            ),
          ],
        ),
...
```

Might be worth noting that the parent route of `JourneysRouter` is used for Bottom Navigation with `AutoTabsScaffold`.

I mainly decided to open an issue to learn if this is doable at all. If it is, I would greatly appreciate a pointer to the right direction as I'm quite confused at this point.

**EDIT:** I think I narrowed it down to `books/:bookId/somepage` not working. The navigate call seems to work and the page url is updated to the desired page, but the actual page isn't pushed to the screen.

**Comment by Milad-Akarie** [comment]
@xiprox it makes sense that your nested routes won't render, nested routes need an AutoRouter widget to render them. e.g in your JourneyDetailsPage you need an AutoRouter Widget to render the WeeksPage and so on, 
with that being said I don't believe the above setup will you give what you want. 

your setup should look like this 

```dart
    AutoRoute(
      path: 'journeys',
      name: 'JourneysRouter',
     // assuming JourneysWrapperPage builds an AutoRouter Widget 
     //  all nested routes are rendered here
      page: JourneysWrapperPage, 
      children: [
        AutoRoute(path: '', page: JourneysPage),
        AutoRoute(path: ':journey', page: JourneyDetailsPage),
        AutoRoute(path: ':journey/:week', page: WeekPage),
        AutoRoute(path: ':journey/:week/:day', page: DayPage),
      ],
    ),
    
```

you also need to have constructor params that correspond with the path params your route have
e.g your DayPage's constructor should look something like this

```dart
class DayPage extends StatefulWidget {
  DayPage({
    Key? key,
    @pathParam this.journey = '', // give default value or make field nullable
    @pathParam this.week = '',
    @pathParam this.day = '',
  }) : super(key: key);
}
```

**Comment by xiprox** [comment]
Ohhh. I see. That looks so much better! Will give it a shot. Thanks!

**Comment by xiprox** [comment]
It works. Thanks once again. Closing this...

**Comment by btkramm-odd** [comment]
What would happen if the `JourneysWrapperPage` needs `:journey` as param? A wrapper that all his children are about a specific `:journey` and as a wrapper shows, for example, the name of the journey.

**Comment by Milad-Akarie** [comment]
you could have something like this
```dart
AutoRoute(
      path: 'journeys/:journey',
      name: 'JourneysRouter',
      page: JourneysWrapperPage, 
      children: [
        AutoRoute(path: '', page: JourneyDetailsPage),
        AutoRoute(path: ':week', page: WeekPage),
        AutoRoute(path: ':week/:day', page: DayPage),
      ],
    ),
```
then inside of any child let's say `JourneyDetailsPage`

```dart
class JourneyDetailsPage extends StatelessWidget{
    // adding the annotation will inject 'joureny' path param from parent
   JourneyDetailsPage(@PathParam('journey') this.journey);
   
   // or read it your self  from route data
   Widget build(context){
       context.routeData.inheritedPathParams.getString('joureny');
     // or
       context.routeData.parent?.getString('joureny');
       // or read router routeData
       context.router.routeData.pathParams.getString('journey');
      // ....
    }
 }

```
