### ISSUE TITLE
Guard not intercepting

### ISSUE THREAD

**Issue by predeepravi** [Milad-Akarie/auto_route_library#808]
Hi, i added a Guard for the route, but then if i  navigate to that route its not intercepted by the Guard. This is my sample code

`AutoRoute(
          path: 'profile',
          name: 'ProfilesRouter',
          page: ProfilePage,
          guards: [AuthGuard],
        )`

**Comment by Milad-Akarie** [comment]
@predeepravi  are you sure you've re-generated the source code after adding the guard?

**Comment by predeepravi** [comment]
@Milad-Akarie yes i have regenerated the code.

**Comment by Milad-Akarie** [comment]
@predeepravi  can you make sure the guard is passed to the route in generated routes map?

**Comment by predeepravi** [comment]
@Milad-Akarie yes am passing the guard when creating the router.

**Comment by Milad-Akarie** [comment]
@predeepravi please share the generated router.

**Comment by predeepravi** [comment]
@Milad-Akarie here you go`// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

import 'package:auto_route/auto_route.dart' as _i4;
import 'package:flutter/material.dart' as _i11;
import 'package:nft/pages/feeds/feeds_page.dart' as _i5;
import 'package:nft/pages/home/home_page.dart' as _i3;
import 'package:nft/pages/login/login_page.dart' as _i2;
import 'package:nft/pages/market/market_item_page.dart' as _i10;
import 'package:nft/pages/market/market_page.dart' as _i9;
import 'package:nft/pages/profile/profile_page.dart' as _i6;
import 'package:nft/pages/splash/splash_screen_page.dart' as _i1;
import 'package:nft/pages/store/store_item_page.dart' as _i8;
import 'package:nft/pages/store/store_page.dart' as _i7;
import 'package:nft/routes/auth_guard.dart' as _i12;

class AppRouter extends _i4.RootStackRouter {
  AppRouter(
      {_i11.GlobalKey<_i11.NavigatorState>? navigatorKey,
      required this.authGuard})
      : super(navigatorKey);

  final _i12.AuthGuard authGuard;

  @override
  final Map<String, _i4.PageFactory> pagesMap = {
    SplashScreenRoute.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i1.SplashScreenPage());
    },
    LoginRoute.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i2.LoginPage());
    },
    HomeRoute.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i3.HomePage());
    },
    StoreRouter.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i4.EmptyRouterPage());
    },
    MarketRouter.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i4.EmptyRouterPage());
    },
    FeedsRouter.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i5.FeedsPage());
    },
    ProfilesRouter.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i6.ProfilePage());
    },
    StoreRoute.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i7.StorePage());
    },
    StoreItemRoute.name: (routeData) {
      final pathParams = routeData.pathParams;
      final args = routeData.argsAs<StoreItemRouteArgs>(
          orElse: () =>
              StoreItemRouteArgs(storeId: pathParams.getInt('storeId')));
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData,
          child: _i8.StoreItemPage(key: args.key, storeId: args.storeId));
    },
    MarketRoute.name: (routeData) {
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData, child: const _i9.MarketPage());
    },
    MarketItemRoute.name: (routeData) {
      final pathParams = routeData.pathParams;
      final args = routeData.argsAs<MarketItemRouteArgs>(
          orElse: () =>
              MarketItemRouteArgs(marketId: pathParams.getInt('marketId')));
      return _i4.AdaptivePage<dynamic>(
          routeData: routeData,
          child: _i10.MarketItemPage(key: args.key, marketId: args.marketId));
    }
  };

  @override
  List<_i4.RouteConfig> get routes => [
        _i4.RouteConfig(SplashScreenRoute.name, path: '/'),
        _i4.RouteConfig(LoginRoute.name, path: '/login'),
        _i4.RouteConfig(HomeRoute.name, path: '/home', children: [
          _i4.RouteConfig(StoreRouter.name,
              path: 'store',
              parent: HomeRoute.name,
              children: [
                _i4.RouteConfig(StoreRoute.name,
                    path: '', parent: StoreRouter.name),
                _i4.RouteConfig(StoreItemRoute.name,
                    path: ':storeId', parent: StoreRouter.name)
              ]),
          _i4.RouteConfig(MarketRouter.name,
              path: 'market',
              parent: HomeRoute.name,
              children: [
                _i4.RouteConfig(MarketRoute.name,
                    path: '', parent: MarketRouter.name),
                _i4.RouteConfig(MarketItemRoute.name,
                    path: ':marketId', parent: MarketRouter.name)
              ]),
          _i4.RouteConfig(FeedsRouter.name,
              path: 'feeds', parent: HomeRoute.name),
          _i4.RouteConfig(ProfilesRouter.name,
              path: 'profile', parent: HomeRoute.name, guards: [authGuard])
        ])
      ];
}

/// generated route for [_i1.SplashScreenPage]
class SplashScreenRoute extends _i4.PageRouteInfo<void> {
  const SplashScreenRoute() : super(name, path: '/');

  static const String name = 'SplashScreenRoute';
}

/// generated route for [_i2.LoginPage]
class LoginRoute extends _i4.PageRouteInfo<void> {
  const LoginRoute() : super(name, path: '/login');

  static const String name = 'LoginRoute';
}

/// generated route for [_i3.HomePage]
class HomeRoute extends _i4.PageRouteInfo<void> {
  const HomeRoute({List<_i4.PageRouteInfo>? children})
      : super(name, path: '/home', initialChildren: children);

  static const String name = 'HomeRoute';
}

/// generated route for [_i4.EmptyRouterPage]
class StoreRouter extends _i4.PageRouteInfo<void> {
  const StoreRouter({List<_i4.PageRouteInfo>? children})
      : super(name, path: 'store', initialChildren: children);

  static const String name = 'StoreRouter';
}

/// generated route for [_i4.EmptyRouterPage]
class MarketRouter extends _i4.PageRouteInfo<void> {
  const MarketRouter({List<_i4.PageRouteInfo>? children})
      : super(name, path: 'market', initialChildren: children);

  static const String name = 'MarketRouter';
}

/// generated route for [_i5.FeedsPage]
class FeedsRouter extends _i4.PageRouteInfo<void> {
  const FeedsRouter() : super(name, path: 'feeds');

  static const String name = 'FeedsRouter';
}

/// generated route for [_i6.ProfilePage]
class ProfilesRouter extends _i4.PageRouteInfo<void> {
  const ProfilesRouter() : super(name, path: 'profile');

  static const String name = 'ProfilesRouter';
}

/// generated route for [_i7.StorePage]
class StoreRoute extends _i4.PageRouteInfo<void> {
  const StoreRoute() : super(name, path: '');

  static const String name = 'StoreRoute';
}

/// generated route for [_i8.StoreItemPage]
class StoreItemRoute extends _i4.PageRouteInfo<StoreItemRouteArgs> {
  StoreItemRoute({_i11.Key? key, required int storeId})
      : super(name,
            path: ':storeId',
            args: StoreItemRouteArgs(key: key, storeId: storeId),
            rawPathParams: {'storeId': storeId});

  static const String name = 'StoreItemRoute';
}

class StoreItemRouteArgs {
  const StoreItemRouteArgs({this.key, required this.storeId});

  final _i11.Key? key;

  final int storeId;
}

/// generated route for [_i9.MarketPage]
class MarketRoute extends _i4.PageRouteInfo<void> {
  const MarketRoute() : super(name, path: '');

  static const String name = 'MarketRoute';
}

/// generated route for [_i10.MarketItemPage]
class MarketItemRoute extends _i4.PageRouteInfo<MarketItemRouteArgs> {
  MarketItemRoute({_i11.Key? key, required int marketId})
      : super(name,
            path: ':marketId',
            args: MarketItemRouteArgs(key: key, marketId: marketId),
            rawPathParams: {'marketId': marketId});

  static const String name = 'MarketItemRoute';
}

class MarketItemRouteArgs {
  const MarketItemRouteArgs({this.key, required this.marketId});

  final _i11.Key? key;

  final int marketId;
}
 `

**Comment by Milad-Akarie** [comment]
@predeepravi  the generated router looks fine, please share the AuthGuard implementation

**Comment by predeepravi** [comment]
@Milad-Akarie 

`class AuthGuard extends AutoRouteGuard {

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    print('interceptor validation'); //Its not hitting here
    bool authenticated = false;
    print("---");
    if (authenticated) {
      resolver.next(true);
    } else {
      router.pushNamed("/login");
    }
  }
}`

**Comment by Milad-Akarie** [comment]
@predeepravi that's very weird, everything looks fine, what are you using to navigate? push? pushNamed?

**Comment by predeepravi** [comment]
@Milad-Akarie this is a part of the bottom navigation bar

`return AutoTabsScaffold(
      appBarBuilder: (_, tabsRouter) => AppBar(
        backgroundColor: AppTheme.topBarColor,
        title: const Text('FlutterBottomNav'),
        centerTitle: true,
        leading: const AutoBackButton(),
      ),
      routes: const [
        StoreRouter(),
        MarketRouter(),
        FeedsRouter(),
        ProfilesRouter()
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return BottomNavigationBar(
          backgroundColor: AppTheme.topBarColor,
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: const Icon(Icons.local_offer_outlined),
              label: 'Menu1',
            ),
            BottomNavigationBarItem(
              icon: const Icon(Icons.store_mall_directory_outlined),
              label: 'Menu2',
            ),
            BottomNavigationBarItem(
              icon: const Icon(Icons.featured_play_list_outlined),
              label: 'Menu3',
            ),
            BottomNavigationBarItem(
              icon: const Icon(Icons.person_pin_outlined),
              label: 'Menu4',
            ),
          ],
          type: BottomNavigationBarType.fixed,
          currentIndex: tabsRouter.activeIndex,
          onTap: tabsRouter.setActiveIndex,
        );
      },
    );`

**Comment by Milad-Akarie** [comment]
@predeepravi ohh I didn't know you `ProfileRouter` was a Tab route, tab routes can not have guards, you should get an exception explaining that, it weird you didn't get it.

**Comment by predeepravi** [comment]
thanks @Milad-Akarie
