### ISSUE TITLE
PathParam for child page not working

### ISSUE THREAD

**Issue by jpunz** [Milad-Akarie/auto_route_library#809]
Hi,

I'm trying to use path parameters for child pages without success. Here is my router.dart:
```
@MaterialAutoRouter(
    replaceInRouteName: 'Page, Route',
    routes: [
      AutoRoute(page: MainLayout, initial: true, children: [
        AutoRoute(page: UserOverview, initial: true, path: "users"),
        AutoRoute(page: QuestionsOverview, path: "questions"),
        AutoRoute(page: FeedbackOverview, path: "feedback", children: [
          AutoRoute(name: "FeedbackDetails", page: FeedbackOverview, path: ":feedbackId") // 1st problem:  /feedback/1dc677e0-39c8-4b8e-994a-9d08c0b764ef not working
        ]),
      ]),
      AutoRoute(name: "UserQuestionsOverview", page: QuestionsOverview, path: "users/:userId/questions") // 2nd problem but solved
    ])
class $AppRouter{}
```

To 1st problem:
Why is this not working? Following your examples and instructions, this should work. Of course i can solve this by using the same workaround as in 2nd problem. feedbackId remains null in FeedbackOverview.

To 2nd problem:
This is working - but is there another solution e.g. using it as child of /users? I already tried this, invested a lot of time and chose the workaround.

In both cases I'm using @PathParam annotation, e.g.:
`const FeedbackOverview({Key? key, @PathParam('feedbackId') this.id}) : super(key: key); `

Kind regards,
Jürgen

**Comment by Milad-Akarie** [comment]
@jpunz does this page  `FeedbackOverview` include an AutoRouter widget to render child routes?

**Comment by jpunz** [comment]
No it doesn't include an AutoRouter Widget, as i thought, this isn't required in that case (MainLayout has AutoRouter Widget).
The main difference between both routes is, that the first is just a List and the second is the same and expands one entry (for given id) in the list.

It could be, that this is my fault, because I'm new to AutoRouter ;)
