### ISSUE TITLE
Can you also add an example on implementing Tabs inside a page with nested Navigation and also maintain state in nested Navigation

### ISSUE THREAD

**Issue by spike04** [Milad-Akarie/auto_route_library#81]
Hi, I was trying to implement a flow in which I login to the application with Plain MaterialAutoRouter to HomePage which contains BottomNavigationBar with 3 options (Dashboard, Notification, and Settings). The first tab contains the nested navigation which I was able to implement which goes to Detail Page. I implemented AdaptiveAutoRouter for Nested Navigation inside the Dashboard Tab. Default settings indicated maintainState to true but I am not able to maintain the required state. For Tabs, I implemented Switch to swap between Pages. And I think this is the reason I am not able to maintain State. I could not find any alternative than that.

My Problems is:

When in Detail Page switching Tabs to say notification and back to Dashboard does not persist the Navigation State. I was expecting to be back in Details page but the output is I am in Dashboard Page with everything reset.

**Comment by Milad-Akarie** [comment]
Hey @spike04 Are you using a TabBarView?  it's infamous for not keeping the state of It's children.  so this has nothing to do with ExtendedNavigator.

This's how it's usually handled
Make sure your tab pages are Stateful and Implement this mixin
```dart
class TabPageState extends State<TabPage> with AutomaticKeepAliveClientMixin {
   @override
  Widget build(BuildContext context) {
// make sure you call super.build here
    super.build(context);
    return Container(...);
  }

  @override
  bool get wantKeepAlive => true;
 
}
```
Hope this helps
