### ISSUE TITLE
How do I print the current path?

### ISSUE THREAD

**Issue by ChauCM** [Milad-Akarie/auto_route_library#810]
I'm working on mobile app so there is no URL address bar. Is there a way to print the current path like "/books/3" everytime the path change so I can know if the current route correct?

**Comment by Milad-Akarie** [comment]
@ChauCM one way to do it is by listening to AutoRouterDelegate changes
```dart
final routerDelegate = AutoRouterDelegate.of(context);
routerDelegate.addListener(() => print(routerDelegate.urlState.url));
```
