### ISSUE TITLE
Auto generated route class ignores nullable argument

### ISSUE THREAD

**Issue by utekau** [Milad-Akarie/auto_route_library#811]
Hi,

Here is my router declaration:
```
@AdaptiveAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: ChronoCategoriesScreen),
    AutoRoute(page: PlayScreen),
    AutoRoute(page: OnboardingScreen),
  ],
)
class $AppRouter {}
```

This is my screen page widget which I want to navigate.

```
class ChronoCategoriesScreen extends StatelessWidget {
  final List<Tuple2<ChronoCategory?, int>> _highestScores;

...
```

As you can see, I identified this property as tuple and the first item might be nullable. I also used that one in constructor as positional argument, there is no other argument which we can pass.

When I run _flutter packages pub run build_runner build_, auto generation runs without any issue but the nullable property becomes lost in that auto generated router.

```
/// generated route for [_i1.ChronoCategoriesScreen]
class ChronoCategoriesScreenRoute
    extends _i4.PageRouteInfo<ChronoCategoriesScreenRouteArgs> {
  ChronoCategoriesScreenRoute(
      {required List<_i6.Tuple2<_i7.ChronoCategory, int>> highestScores})
      : super(name,
            path: '/chrono-categories-screen',
            args:
                ChronoCategoriesScreenRouteArgs(highestScores: highestScores));

  static const String name = 'ChronoCategoriesScreenRoute';
}

class ChronoCategoriesScreenRouteArgs {
  const ChronoCategoriesScreenRouteArgs({required this.highestScores});

  final List<_i6.Tuple2<_i7.ChronoCategory, int>> highestScores;
}
```

To overcome this issue, I manually added question marks to code but it seems that something is wrong during the auto generation.

Note: ChronoCategory is just an enum. My flutter version is 2.5.0, dart version is 2.14.0 and auto_route is 3.0.4.

**Comment by Milad-Akarie** [comment]
@utekau  fixed in 
```yaml
auto_route: 3.1.0
auto_route_generator: 3.1.0
```
