### ISSUE TITLE
Can we reuse AutoRoutes?

### ISSUE THREAD

**Issue by Yusuf007R** [Milad-Akarie/auto_route_library#812]
Basically I'm doing a type of gallery app, in this app, I would want to push `n` numbers of the route, so every time a user search for a tag, I will push a new instance of the route with the new tag,

I have a AutoRoute called  `PostRoute`  with nested routes inside, that contain the gallery_screen and the gallery_fullscreen, `PostRoute` also have a route wrapper for a bloc provider.

as I said everytime an user search for a new tag, I would want to push him another instance of the `PostRoute`, is this possible?

**Comment by Milad-Akarie** [comment]
@Yusuf007R of course, you can add as many routes to the stack as you want.

**Comment by Yusuf007R** [comment]
I just tried to implement it and partially succeeded, basically I can push the AutoRoute but when I pop some weird things happend.

thats my MaterialAutoRouter

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(
      name: "PostRouter",
      page: BlocWrapper,
      children: [
        AutoRoute(page: PostScreen, initial: true),
        AutoRoute(
          page: PostDetailScreen,
        ),
      ],
    )
  ],
)
class $AppRouter {}
```

https://user-images.githubusercontent.com/45109516/140623652-62a8551c-329e-4944-8d19-3ed118b802b0.mp4

As you see here, I can navigate on the AutoRoute pages without problem, I can go to the fullscreen page, 
```
/*code that I use to navigate to the fullscreen page, 
here I use "navigate" because I want to navigate in the same instance of AutoRoute, 
so I can access the bloc provider. */

 AutoRouter.of(context).navigate(
            PostRouter(children: [PostDetailRoute(initialIndex: widget.index)]), // widget.index is the index of the image
          );

```
everything works.

in this demo when you press the menu button on the navbar I push a new instance of the `PostRouter`
```
// this is the code that I use to push a new instance of PostRouter
  AutoRouter.of(context).push(
                        const PostRouter(),
                      );
```

in the new instance Everything work perfectly again, you can navigate to the fullscreen page no problems, but when you pop back, in the previous instance of AutoRoute you can not navigate to the fullscreen, it just doesnt work.
