### ISSUE TITLE
Allow pages to stop from navigating away, e.g. if there are unsaved state changes

### ISSUE THREAD

**Issue by Josua2012** [Milad-Akarie/auto_route_library#815]
Hello,
I am going to start a web project with Flutter, for another project use the Fluro library, however, I could not solve the following problem:
If a user is on a page that contains a form and is making modifications is said form, I would like that if he tries to exit without having saved the modifications (either by putting another url, with the browser's backbutton, ...) it would show him an alertdialog giving him the possibility of canceling the navigation to the new url or, on the contrary, of canceling the modifications and staying on the same page where he is.
The question is, can I do this with auto_route?
auto_route has any mechanism by which this functionality can be achieved?
Please, if this functionality is possible with auto_route could you give me some indications.
Thank you so much for all the help.
Regards,
Jose

**Comment by arsamme** [comment]
@Josua2012 You could use `onWillPop` in your `Scaffold`
