### ISSUE TITLE
Feature Request: Path Parameters support for `RedirectRoute`

### ISSUE THREAD

**Issue by MichaelDark** [Milad-Akarie/auto_route_library#818]
Currently `RedirectRoute` has support only for wildcards (`*`) and static routes (`predefined/static/path`).

But there is a case when it is needed to cover the vast majority of routes by redirecting preserving route parameters like in the example below:

```
RedirectRoute(
  path: '/users/:userId',
  redirectTo: '/users/:userId/details',
)
```

Thus produced a new test case, that is not yet covered by `auto_route`:

Expected:
- Navigate manually to `users/xxx`
- Redirected to `users/xxx/details` 

Actual:
- Navigate manually to `users/xxx`
- Redirected to `users/:userId/details` 

_offtop_
@Milad-Akarie Thank you for this library! I believe that you can help with the case described above in a short time! ❤️

**Comment by Milad-Akarie** [comment]
@MichaelDark  you got it.

**Comment by Milad-Akarie** [comment]
@MichaelDark  implemented in 
```yaml
auto_route: 3.1.0
auto_route_generator: 3.1.0
```
