### ISSUE TITLE
Unused args causes tests and code analyse to fail

### ISSUE THREAD

**Issue by moti0375** [Milad-Akarie/auto_route_library#82]
Hi, 

Currently my routes doesn't use any arguments.
In the generated router.gr.dart file there is  ` final args = settings.arguments;`  in the `onGenerateRoute` method which then marked as unused variable.

This will cause CI/CD code analyse to fail.  Currently I delete it manually. 

Is there a way to omit this field in case no arguments are in use?

Regards,
Moti.

**Comment by Milad-Akarie** [comment]
@moti0375 noted. I'll look into it.

**Comment by Milad-Akarie** [comment]
fixed in auto_route_generator 0.4.8
Thanks for reporting
