### ISSUE TITLE
Problem with nested route

### ISSUE THREAD

**Issue by minhnhatvdl** [Milad-Akarie/auto_route_library#825]
I have a route as:
CupertinoRoute<dynamic>(
      path: '/conversation/:conversationId/:subConversationId',
      page: ConversationScreen,
    ),

I want to make:
/conversation/:conversationId -> go to ConversationScreen
/conversation/:conversationId/:subConversationId -> go to ConversationScreen too

But the first case (/conversation/:conversationId) is not working for me. That works ok for second case.

Anyone has the same problem ?

**Comment by Milad-Akarie** [comment]
@minhnhatvdl I can think of couple ways you can handle this 
1- let subConversationId be a query param instead of path param, so your path would look something like this
`'/conversation/3?subConversationId=3'` 
this way /conversation/:id will be matched with or without the queryParam. 

2- use a redirect route
`RedirectRoute(path: '/conversation/:conversationId, redirectTo: '/conversation/:conversationId/DefaultValue')`
downside: you need a default 'subConversationId' value that would be visible in url

3- create two routes that map to the same screen 
```dart
routes: [
   AutoRoute(path: '/conversation/:conversationId', page: ConversationScreen),
   AutoRoute(path: '/conversation/:conversationId/:subConversationId', page: ConversationScreen),
]
```

**Comment by minhnhatvdl** [comment]
> @minhnhatvdl I can think of couple ways you can handle this 1- let subConversationId be a query param instead of path param, so your path would look something like this `'/conversation/3?subConversationId=3'` this way /conversation/:id will be matched with or without the queryParam.
> 
> 2- use a redirect route `RedirectRoute(path: '/conversation/:conversationId, redirectTo: '/conversation/:conversationId/DefaultValue')` downside: you need a default 'subConversationId' value that would be visible in url
> 
> 3- create two routes that map to the same screen
> 
> ```dart
> routes: [
>    AutoRoute(path: '/conversation/:conversationId', page: ConversationScreen),
>    AutoRoute(path: '/conversation/:conversationId/:subConversationId', page: ConversationScreen),
> ]
> ```

Hello @Milad-Akarie !

The solution 3 doesn't work for me. I have an issue when i generate routes: "Duplicate route names must have the same path!".

Yeah, the solution 2 isn't not perfect, because we can see  a default 'subConversationId' in the url.

The solution 1 seems the best in this situation, but i prefer a route as '/conversation/:conversationId/:subConversationId'.
If we can't find another solution as i wish, the solution 1 is good for me.

Thank you very much for your answer.

Have a nice day!

**Comment by Milad-Akarie** [comment]
@Milad-Akarie  for the third solution just use a different name
```dart
routes: [
   AutoRoute(name: 'ConverstionRoute', path: '/conversation/:conversationId', page: ConversationScreen),
   AutoRoute(name: 'ConverstionWithSubRoute',  path: '/conversation/:conversationId/:subConversationId', page: ConversationScreen),
]
```
