### ISSUE TITLE
PageRouteBuilder ctx instead of context

### ISSUE THREAD

**Issue by moti0375** [Milad-Akarie/auto_route_library#83]
Milad Hi,

Regarding last update for the wrappedRoute with context, which looks great!
However, in the `router.gr.dart` file when it uses a `PageRouteBuilder` like this:

`PageRouteBuilder<dynamic>(
     pageBuilder: (ctx, animation, secondaryAnimation) => Page().wrappedRoute(context),
          settings: settings,
          transitionsBuilder: slideTransition,
        );`

Please notice that in the builder signature it uses **ctx** while in the `wrappedRoute()` is use **context**
This causing a compilation error. 

Currently I am fixing it manually. 

Appreciate if you can check this. 
Moti.

**Comment by Milad-Akarie** [comment]
Hey @moti0375 I'll look into it. this should be an easy fix.
Thank for reporting.

**Comment by Milad-Akarie** [comment]
Fixed in auto_route_generator 0.4.8
