### ISSUE TITLE
navigateNamedTo did not work in version 3.1.2 in the web

### ISSUE THREAD

**Issue by resfandiari** [Milad-Akarie/auto_route_library#831]
navigateNamedTo method does not work after updating to a new version.
What has changed?

**Comment by Milad-Akarie** [comment]
Are you getting an error? What's happening?

**Comment by resfandiari** [comment]
Thanks for your answer. I tried getting an error, but I couldn't. I used the on failure function in navigateNamedTo and try/catch, but nothing happened

**Comment by ariefwijaya** [comment]
This problem still exists in 3.1.3 @Milad-Akarie
