### ISSUE TITLE
I need writing double MaterialApp filelds because of the MaterialApp.router usage

### ISSUE THREAD

**Issue by jinjilynn** [Milad-Akarie/auto_route_library#835]
this will cause a white screen splash and duplicated code

**Comment by Milad-Akarie** [comment]
@jinjilynn care to explain?

**Comment by jinjilynn** [comment]
just in the case that MaterialApp.router() is not the root widget but a child of a MaterialApp. For simple, if i have a MaterialApp widget on top of the tree and set 'debugShowCheckedModeBanner' field to 'false', this will not work. I have to set the field to false again in MaterialApp.router.

**Comment by jinjilynn** [comment]
besides, i have done as the link https://autoroute.vercel.app/basics/wrapping_routes, and its great. but when i navigate between sub-routes, the entire screen animates. However, I thought it is the wrapped part that should animate. its just an advice.

**Comment by Milad-Akarie** [comment]
@jinjilynn I'm not sure I understand what you're trying to do, but if you need to render a router without using MaterialApp.router you could just use a Router widget  the one coming from flutter material

**Comment by Milad-Akarie** [comment]
@jinjilynn are you navigating using the sub router? show me some code

**Comment by jinjilynn** [comment]
my route config
`import 'package:auto_route/annotations.dart';
  import 'package:offline_solution/pages/auth_wraper/auto_wraper.dart';
  import 'package:offline_solution/pages/login/view/view.dart';
  import 'package:offline_solution/pages/pages.dart';
  
  
  @MaterialAutoRouter(
    replaceInRouteName: 'View,Route',
    routes: <AutoRoute>[
      AutoRoute(
          path: "/",
          page: AuthWraperView,
          children: [
            AutoRoute(
              initial: true,
              path: 'Home',
              page: HomeView,
            ),
            AutoRoute(path: 'Messages', page: NotificationView),
            AutoRoute(path: 'CM', page: CMView),
            AutoRoute(path: 'PM', page: PMView),
          ]),
      AutoRoute(path: '/login', page: LoginView),
    ],
  )
  class $AppRouter {}
`
AutoRouter exists in below

`import 'package:auto_route/auto_route.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter_screenutil/flutter_screenutil.dart';
  import 'package:offline_solution/global_respository/common.dart';
  import 'package:flutter_bloc/flutter_bloc.dart';
  
  import 'bottom_nav/nav.dart';
  import 'header_info/info.dart';
  import 'routes_switcher.dart';
  
  class MainContent extends StatelessWidget {
    final double slide;
    final double scale;
    final AnimationController controller;
    _toggleAnimation() {
      controller.isDismissed ? controller.forward() : controller.reverse();
    }
  
    const MainContent(this.controller,
        {Key? key, this.slide = 0.0, this.scale = 0.0})
        : super(key: key);
  
    @override
    Widget build(BuildContext context) {
      MaterialColor textColor =
          context.read<CommonRespository>().textColor['white']!;
      return Transform(
        transform: Matrix4.identity()
          ..translate(slide)
          ..scale(scale),
        alignment: Alignment.center,
        child: Scaffold(
          backgroundColor: context.read<CommonRespository>().basicColor[600],
          appBar: PreferredSize(
            preferredSize: Size.fromHeight(220.sp),
            child: Container(
              padding: EdgeInsets.only(left: 20.sp, right: 20.sp),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  ConstrainedBox(
                      constraints: BoxConstraints(
                          minHeight: ScreenUtil().statusBarHeight + 70.sp,
                          minWidth: 1.sw),
                      child: Stack(alignment: Alignment.bottomLeft, children: [
                        SizedBox(
                            height: 60.sp,
                            width: 1.sw,
                            child: Align(
                                alignment: Alignment.topCenter,
                                child: Text('APM(HK Biomed)',
                                    style: TextStyle(
                                        fontSize: 40.sp, color: textColor[50])))),
                        IconButton(
                          iconSize: 40.sp,
                          onPressed: _toggleAnimation,
                          icon: AnimatedIcon(
                            color: textColor[600],
                            icon: AnimatedIcons.menu_close,
                            progress: controller,
                          ),
                        ),
                      ])),
                  Expanded(child: HeaderInfo())
                ],
              ),
            ),
          ),
          body: Container(
            padding: EdgeInsets.only(top: 40.sp, left: 10.sp, right: 10.sp),
            decoration: BoxDecoration(
                color: textColor[100],
                borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(40.sp),
                    topRight: Radius.circular(40.sp))),
            child: AutoRouter(),
          ),
          bottomNavigationBar: BottomNav(),
        ),
      );
    }
  }
 `
BottomNav
`
import 'package:auto_route/auto_route.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:offline_solution/config/bottom_bar.dart';
import 'package:offline_solution/generated/l10n.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/routes/bloc/bloc.dart';

class BottomNav extends StatelessWidget {
  BottomNav({Key? key}) : super(key: key);
  Map<String, String> localMap = {
    "Home": S.current.Home,
    "CM": "CM",
    "PM": "PM",
    "Messages": S.current.Messages
  };
  @override
  Widget build(BuildContext context) {
    return ConvexAppBar.badge(
      const {3: '99+'},
      backgroundColor: context.read<CommonRespository>().basicColor[600],
      badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
      style: TabStyle.react,
      items: bottomBar.values
          .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
          .toList(),
      initialActiveIndex: 0,
      onTap: (index) {
        context.router.pushNamed('/CM');
      },
    );
  }
}
`

**Comment by jinjilynn** [comment]
my route config
`import 'package:auto_route/annotations.dart';
  import 'package:offline_solution/pages/auth_wraper/auto_wraper.dart';
  import 'package:offline_solution/pages/login/view/view.dart';
  import 'package:offline_solution/pages/pages.dart';
  
  @MaterialAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: [
  AutoRoute(
  path: "/",
  page: AuthWraperView,
  children: [
  AutoRoute(
  initial: true,
  path: 'Home',
  page: HomeView,
  ),
  AutoRoute(path: 'Messages', page: NotificationView),
  AutoRoute(path: 'CM', page: CMView),
  AutoRoute(path: 'PM', page: PMView),
  ]),
  AutoRoute(path: '/login', page: LoginView),
  ],
  )
  class $AppRouter {}
`
AutoRouter exists in below

`import 'package:auto_route/auto_route.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter_screenutil/flutter_screenutil.dart';
  import 'package:offline_solution/global_respository/common.dart';
  import 'package:flutter_bloc/flutter_bloc.dart';
  
  import 'bottom_nav/nav.dart';
  import 'header_info/info.dart';
  import 'routes_switcher.dart';
  
  class MainContent extends StatelessWidget {
  final double slide;
  final double scale;
  final AnimationController controller;
  _toggleAnimation() {
  controller.isDismissed ? controller.forward() : controller.reverse();
  }
  
  const MainContent(this.controller,
      {Key? key, this.slide = 0.0, this.scale = 0.0})
      : super(key: key);
  
  @override
  Widget build(BuildContext context) {
    MaterialColor textColor =
        context.read<CommonRespository>().textColor['white']!;
    return Transform(
      transform: Matrix4.identity()
        ..translate(slide)
        ..scale(scale),
      alignment: Alignment.center,
      child: Scaffold(
        backgroundColor: context.read<CommonRespository>().basicColor[600],
        appBar: PreferredSize(
          preferredSize: Size.fromHeight(220.sp),
          child: Container(
            padding: EdgeInsets.only(left: 20.sp, right: 20.sp),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                ConstrainedBox(
                    constraints: BoxConstraints(
                        minHeight: ScreenUtil().statusBarHeight + 70.sp,
                        minWidth: 1.sw),
                    child: Stack(alignment: Alignment.bottomLeft, children: [
                      SizedBox(
                          height: 60.sp,
                          width: 1.sw,
                          child: Align(
                              alignment: Alignment.topCenter,
                              child: Text('APM(HK Biomed)',
                                  style: TextStyle(
                                      fontSize: 40.sp, color: textColor[50])))),
                      IconButton(
                        iconSize: 40.sp,
                        onPressed: _toggleAnimation,
                        icon: AnimatedIcon(
                          color: textColor[600],
                          icon: AnimatedIcons.menu_close,
                          progress: controller,
                        ),
                      ),
                    ])),
                Expanded(child: HeaderInfo())
              ],
            ),
          ),
        ),
        body: Container(
          padding: EdgeInsets.only(top: 40.sp, left: 10.sp, right: 10.sp),
          decoration: BoxDecoration(
              color: textColor[100],
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.sp),
                  topRight: Radius.circular(40.sp))),
          child: AutoRouter(),
        ),
        bottomNavigationBar: BottomNav(),
      ),
    );
  }
  }
`
BottomNav

`

import 'package:auto_route/auto_route.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:offline_solution/config/bottom_bar.dart';
import 'package:offline_solution/generated/l10n.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/routes/bloc/bloc.dart';

class BottomNav extends StatelessWidget {
  BottomNav({Key? key}) : super(key: key);
  Map<String, String> localMap = {
    "Home": S.current.Home,
    "CM": "CM",
    "PM": "PM",
    "Messages": S.current.Messages
  };
  @override
  Widget build(BuildContext context) {
    return ConvexAppBar.badge(
      const {3: '99+'},
      backgroundColor: context.read<CommonRespository>().basicColor[600],
      badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
      style: TabStyle.react,
      items: bottomBar.values
          .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
          .toList(),
      initialActiveIndex: 0,
      onTap: (index) {
        context.router.pushNamed('/CM');
      },
    );
  }
}

`

**Comment by jinjilynn** [comment]
my route config
```dart
import 'package:auto_route/annotations.dart';
import 'package:offline_solution/pages/auth_wraper/auto_wraper.dart';
import 'package:offline_solution/pages/login/view/view.dart';
import 'package:offline_solution/pages/pages.dart';

@MaterialAutoRouter(
replaceInRouteName: 'View,Route',
routes: [
AutoRoute(
path: "/",
page: AuthWraperView,
children: [
AutoRoute(
initial: true,
path: 'Home',
page: HomeView,
),
AutoRoute(path: 'Messages', page: NotificationView),
AutoRoute(path: 'CM', page: CMView),
AutoRoute(path: 'PM', page: PMView),
]),
AutoRoute(path: '/login', page: LoginView),
],
)
class $AppRouter {}
```
AutoRouter exists in below

```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'bottom_nav/nav.dart';
import 'header_info/info.dart';
import 'routes_switcher.dart';

class MainContent extends StatelessWidget {
final double slide;
final double scale;
final AnimationController controller;
_toggleAnimation() {
controller.isDismissed ? controller.forward() : controller.reverse();
}

const MainContent(this.controller,
{Key? key, this.slide = 0.0, this.scale = 0.0})
: super(key: key);

@OverRide
Widget build(BuildContext context) {
MaterialColor textColor =
context.read().textColor['white']!;
return Transform(
transform: Matrix4.identity()
..translate(slide)
..scale(scale),
alignment: Alignment.center,
child: Scaffold(
backgroundColor: context.read().basicColor[600],
appBar: PreferredSize(
preferredSize: Size.fromHeight(220.sp),
child: Container(
padding: EdgeInsets.only(left: 20.sp, right: 20.sp),
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
ConstrainedBox(
constraints: BoxConstraints(
minHeight: ScreenUtil().statusBarHeight + 70.sp,
minWidth: 1.sw),
child: Stack(alignment: Alignment.bottomLeft, children: [
SizedBox(
height: 60.sp,
width: 1.sw,
child: Align(
alignment: Alignment.topCenter,
child: Text('APM(HK Biomed)',
style: TextStyle(
fontSize: 40.sp, color: textColor[50])))),
IconButton(
iconSize: 40.sp,
onPressed: _toggleAnimation,
icon: AnimatedIcon(
color: textColor[600],
icon: AnimatedIcons.menu_close,
progress: controller,
),
),
])),
Expanded(child: HeaderInfo())
],
),
),
),
body: Container(
padding: EdgeInsets.only(top: 40.sp, left: 10.sp, right: 10.sp),
decoration: BoxDecoration(
color: textColor[100],
borderRadius: BorderRadius.only(
topLeft: Radius.circular(40.sp),
topRight: Radius.circular(40.sp))),
child: AutoRouter(),
),
bottomNavigationBar: BottomNav(),
),
);
}
}
```
navigating between sub routes in BottomNav

```
import 'package:auto_route/auto_route.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:offline_solution/config/bottom_bar.dart';
import 'package:offline_solution/generated/l10n.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/routes/bloc/bloc.dart';

class BottomNav extends StatelessWidget {
BottomNav({Key? key}) : super(key: key);
Map<String, String> localMap = {
"Home": S.current.Home,
"CM": "CM",
"PM": "PM",
"Messages": S.current.Messages
};
@OverRide
Widget build(BuildContext context) {
return ConvexAppBar.badge(
const {3: '99+'},
backgroundColor: context.read().basicColor[600],
badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
style: TabStyle.react,
items: bottomBar.values
.map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
.toList(),
initialActiveIndex: 0,
onTap: (index) {
context.router.pushNamed('/CM');
},
);
}
}
```

**Comment by jinjilynn** [comment]
```dart
import 'package:auto_route/annotations.dart';
import 'package:offline_solution/pages/auth_wraper/auto_wraper.dart';
import 'package:offline_solution/pages/login/view/view.dart';
import 'package:offline_solution/pages/pages.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: <AutoRoute>[
    AutoRoute(
        path: "/",
        page: AuthWraperView,
        children: [
          AutoRoute(
            initial: true,
            path: 'Home',
            page: HomeView,
          ),
          AutoRoute(path: 'Messages', page: NotificationView),
          AutoRoute(path: 'CM', page: CMView),
          AutoRoute(path: 'PM', page: PMView),
        ]),
    AutoRoute(path: '/login', page: LoginView),
  ],
)
class $AppRouter {}

```
and 

```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'bottom_nav/nav.dart';
import 'header_info/info.dart';
import 'routes_switcher.dart';

class MainContent extends StatelessWidget {
  final double slide;
  final double scale;
  final AnimationController controller;
  _toggleAnimation() {
    controller.isDismissed ? controller.forward() : controller.reverse();
  }

  const MainContent(this.controller,
      {Key? key, this.slide = 0.0, this.scale = 0.0})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    MaterialColor textColor =
        context.read<CommonRespository>().textColor['white']!;
    return Transform(
      transform: Matrix4.identity()
        ..translate(slide)
        ..scale(scale),
      alignment: Alignment.center,
      child: Scaffold(
        backgroundColor: context.read<CommonRespository>().basicColor[600],
        appBar: PreferredSize(
          preferredSize: Size.fromHeight(220.sp),
          child: Container(
            padding: EdgeInsets.only(left: 20.sp, right: 20.sp),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                ConstrainedBox(
                    constraints: BoxConstraints(
                        minHeight: ScreenUtil().statusBarHeight + 70.sp,
                        minWidth: 1.sw),
                    child: Stack(alignment: Alignment.bottomLeft, children: [
                      SizedBox(
                          height: 60.sp,
                          width: 1.sw,
                          child: Align(
                              alignment: Alignment.topCenter,
                              child: Text('APM(HK Biomed)',
                                  style: TextStyle(
                                      fontSize: 40.sp, color: textColor[50])))),
                      IconButton(
                        iconSize: 40.sp,
                        onPressed: _toggleAnimation,
                        icon: AnimatedIcon(
                          color: textColor[600],
                          icon: AnimatedIcons.menu_close,
                          progress: controller,
                        ),
                      ),
                    ])),
                Expanded(child: HeaderInfo())
              ],
            ),
          ),
        ),
        body: Container(
          padding: EdgeInsets.only(top: 40.sp, left: 10.sp, right: 10.sp),
          decoration: BoxDecoration(
              color: textColor[100],
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.sp),
                  topRight: Radius.circular(40.sp))),
          child: AutoRouter(),
        ),
        bottomNavigationBar: BottomNav(),
      ),
    );
  }
}

```

```dart

import 'package:auto_route/auto_route.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:offline_solution/config/bottom_bar.dart';
import 'package:offline_solution/generated/l10n.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/routes/bloc/bloc.dart';

    class BottomNav extends StatelessWidget {
      BottomNav({Key? key}) : super(key: key);
      Map<String, String> localMap = {
        "Home": S.current.Home,
        "CM": "CM",
        "PM": "PM",
        "Messages": S.current.Messages
      };
      @override
      Widget build(BuildContext context) {
        return ConvexAppBar.badge(
          const {3: '99+'},
          backgroundColor: context.read<CommonRespository>().basicColor[600],
          badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
          style: TabStyle.react,
          items: bottomBar.values
              .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
              .toList(),
          initialActiveIndex: 0,
          onTap: (index) {
            context.router.pushNamed('/CM');
          },
        );
      }
    }

```

**Comment by jinjilynn** [comment]
> @jinjilynn I'm not sure I understand what you're trying to do, but if you need to render a router without using MaterialApp.router you could just use a Router widget the one coming from flutter material

many thanks
