### ISSUE TITLE
Leave transition

### ISSUE THREAD

**Issue by nothinggift** [Milad-Akarie/auto_route_library#84]
Is there a way to show custom transition on a special route leave.

PageRouteBuilder seems not work.

**Comment by Milad-Akarie** [comment]
@nothinggift This's a little tricky to achieve using named routes since you need to pass in the current widget to the PageRoute to apply transition. 

I'll give it a shot!

**Comment by scostagabriel** [comment]
It would be great if leaving tansitions were possible! 

A workaround that I'm doing right now for pages that need leaving transitions (most of them are modals) is using just push and passing a custom class extending PageRouteBuilder with my transitions logic that accepts my widget as a parameter.

**Comment by theweiweiway** [comment]
Hey @Milad-Akarie, 

Are we able to specify **leave only** transitions for auto_route 1.0.0?
