### ISSUE TITLE
Something is wrong with this plugin

### ISSUE THREAD

**Issue by JeSuisAlrick** [Milad-Akarie/auto_route_library#845]
Almost **every single time** you do a release something stops working or does not work as expected anymore.

I don't know if you are the only one working on this project, but you need someone you can trust to help. It is quite frustrating that people build applications with this plugin and it is not reliable.

**PLEASE** ask for help with testing a release and ensure that you have proper unit tests. If you find it hard to this then maybe you should give the project to someone who has the time and energy to make sure it works before release.

**Comment by naamapps** [comment]
I agree with this, unfortunately.
This is the best package I used for routing, it is simple and powerful at the same time.
However, every update breaks something in my application.

Unit test should help prevent these problems.

**Comment by samu-developments** [comment]
It's an open source project, Milad Akarie does a great job developing it. If you want to help it's just for you to make a PR (eg extend the already existing tests),  or report issues with detailed information..

**Comment by JeSuisAlrick** [comment]
@samu-developments This is truly awesome and the work Milad has does is way better than what the default implementation of Flutter provides, but just because the project is open source doesn't mean it's okay to release software that's broken.

That said, if @Milad-Akarie wants to have a team of people to review and test a release before he pushes, I'm available. There are plenty of other people who are willing to contribute, but he needs a partner he can trust who has the permission to review and merge code. 

One man can't do this all by himself seeing that so many people rely on this project.

**Comment by samu-developments** [comment]
> but just because the project is open source doesn't mean it's okay to release software that's broken.

Of course it is, and it happens all the time. You're also free to contribute to help fix those bugs, or choose to use another release version.
