### ISSUE TITLE
Set if we want the page/tab on AutoTabsScaffold persistent or not

### ISSUE THREAD

**Issue by maxusr** [Milad-Akarie/auto_route_library#847]
Is it possible to have a parameter `persistent` on `AutoTabsScaffold` and/or `AutoTabsRouter`  to have the tabs persistent or not so that each navigation between tab will rebuild the page/screen or not.

We have a stack like that

- Tab1
- Tab2
- Tab3
  - ChildPage31
  - ChildPage32
  - ChildPage33
- Tab4

When we navigate to Tab3, our initial is ChildPage31, we navigate then to ChildPage32 after that we navigate directly to Tab1 using the BottomNavigationBar. If we navigate again to Tab3, this Stack is already or always to ChildPage32 rather than ChildPage31.

Is it possible to make sub Navigator stack to reset when we change our tab ? Or avoid the pages or some pages to be persisted ?

**Comment by maxusr** [comment]
I've found a hack waiting for a response. Pass the `builder`  property of `AutoTabScaffold` and use 
```dart
      builder: (BuildContext context, Widget child, Animation<double> animation) {
        if (AutoTabsRouter.of(context).currentChild?.name ==
                YourRoute.name &&
            AutoTabsRouter.of(context).canPopSelfOrChildren) {
          print(
              'is archives screen and it can pop means it is not initial screen');
          AutoTabsRouter.of(context)
              .innerRouterOf(YourRoute.name)
              ?.pop();
        }
        return FadeTransition(
          scale: animation,
          child: child,
        );
      },
```

**Comment by Milad-Akarie** [comment]
@maxusr if you just want to pop current tab stack you could try something like this


```dart
onTap(index){
 if(WANT_TO_POP_STACK){
   tabsRouter.stackRouterOfIndex(index)?.popUntilRoot();
   }
   tabsRouter.setActiveIndex(index);
 }
```

**Comment by maxusr** [comment]
@Milad-Akarie  Thanks! That's perfect.
