### ISSUE TITLE
Android Studio suggesting an incorrect import statement

### ISSUE THREAD

**Issue by dJani97** [Milad-Akarie/auto_route_library#848]
Hey!

When I'm trying to use the extension functions, eg.: `context.pushRoute()`, Android Studio suggests to import the wrong dependency.

Instead of suggesting the package

    import 'package:auto_route/auto_route.dart';

... it suggests the implementation:

    import 'package:auto_route/src/router/auto_router_x.dart';

And then I get a message from Dart Analysis:

> ℹ️ Don't import implementation files from another package.

Not sure if this is an issue with this package, or Android Studio itself. Android Studio's suggestions usually work well, I've never had this problem before.

Is there a way to _"teach"_ Android Studio the right import statement?

**Comment by Milad-Akarie** [comment]
Hey @dJani97 as you can see from the attached image,` auto_router_x.dart` is exported in the auto_route library. it's an analyzer/tooling issue and it's being tracked if I'm not mistaken. 

![Screen Shot 2021-11-23 at 9 37 29 AM](https://user-images.githubusercontent.com/55059449/142986033-7b5ff505-3314-4c07-bd87-7d8a93efe909.png)

**Comment by axeis** [comment]
maybe this could be added to the docs that this is a known issue. but not an actual issue

**Comment by dJani97** [comment]
I also have the same problem with Riverpod now.

@Milad-Akarie you mentioned that this issue is being tracked somewhere, but I wasn't able to find it. Probably I'm missing the right keywords.

If anyone manages to find it, can you leave a link here?
