### ISSUE TITLE
BottomSheet problem

### ISSUE THREAD

**Issue by carmas123** [Milad-Akarie/auto_route_library#85]
Hi, when I use auto_route lib I cannot use again BottomSheet because it use a standard Navigator.
Do you have any solution for that?

**Comment by Milad-Akarie** [comment]
Hey @carmas123 Everything seems fine on my end.. Could you please share your code? 
or at least the error?

**Comment by moti0375** [comment]
Hi @carmas123, make sure you're using the right context for the bottom sheet.

**Comment by Milad-Akarie** [comment]
closing this for now
