### ISSUE TITLE
Tab transition between pages

### ISSUE THREAD

**Issue by ciriousjoker** [Milad-Akarie/auto_route_library#850]
We have a tab bar and two pages. If the user wants to navigate from the left page to the right page, we currently do a slide-fade transition between the pages.

How can we recreate this using AutoRouter?

The builder only provides a single child (not previouschild) or something like that and only one animation.

**Comment by Pliavi** [comment]
I'm having the same problem, but with a transition that has the button as starting point, in autoroute is not possible to access/pass the parameters in the transition builder, my way to solve was using Bloc state, but does not looks good .-.
