### ISSUE TITLE
Call stackRouterOfIndex(index) before accessing the route index

### ISSUE THREAD

**Issue by azliR** [Milad-Akarie/auto_route_library#851]
Hi, I have set up my tabs router and it works properly with a bottom navigation bar. But when I call these two functions, the `route` variable will be returning null.
```
context.tabsRouter.setActiveIndex(1);
final route = context.tabsRouter.stackRouterOfIndex(1); // this will be null
```
How do I implement this so I can access the route? Thank you.

**Comment by Milad-Akarie** [comment]
@azliR  do you want to access the route or the router associating with the index?
if you want to access the route you can go 
`tabsRouter.current `

**Comment by azliR** [comment]
@Milad-Akarie Thank you so much for the reply! I want to push to another page with it, here's the code of what I want to achieve
```
context.tabsRouter.setActiveIndex(1);
context.tabsRouter
  .stackRouterOfIndex(1)!
  .push(OrderStatusRoute(order: order));
```
I can't push to another page with `tabsRouter.current`
