### ISSUE TITLE
Exception caught while dispatching notifications for _DeclarativeAutoRouterDelegate

### ISSUE THREAD

**Issue by ishangavidusha** [Milad-Akarie/auto_route_library#853]
Hi @Milad-Akarie, 
Really appreciate your work on this awesome project. However there was some problem that I was facing while working with the package, please take a look.

I was trying to implement Login flow with the help of Declarative Routing. Authentication logic seems to work fine but I keep getting this exception when the AppState Object changed.

```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for _DeclarativeAutoRouterDelegate:
setState() or markNeedsBuild() called during build.

This Router<Object> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Router<Object>
    dependencies: [UnmanagedRestorationScope]
    state: _RouterState<Object>#f02e7
The widget which was currently being built when the offending call was made was: StackRouterScope
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
package:flutter/…/widgets/framework.dart:4305
#1      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4320
#2      State.setState
package:flutter/…/widgets/framework.dart:1108
#3      _RouterState._handleRouterDelegateNotification
package:flutter/…/widgets/router.dart:717
#4      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:308
#5      AutoRouterDelegate._handleRebuild
package:auto_route/…/controller/auto_router_delegate.dart:120
#6      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:308
#7      NavigationHistory._onNewUrlState
package:auto_route/…/controller/navigation_history.dart:26
#8      NativeNavigationHistory._onNewUrlState
package:auto_route/…/controller/navigation_history.dart:120
#9      StackRouter.updateDeclarativeRoutes
package:auto_route/…/controller/routing_controller.dart:954
#10     _AutoRouteNavigatorState._updateDeclarativeRoutes
package:auto_route/…/widgets/auto_route_navigator.dart:46
#11     _AutoRouteNavigatorState.didUpdateWidget
package:auto_route/…/widgets/auto_route_navigator.dart:57
#12     StatefulElement.update
package:flutter/…/widgets/framework.dart:4855
#13     Element.updateChild
package:flutter/…/widgets/framework.dart:3412
#14     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4690
#15     Element.rebuild
package:flutter/…/widgets/framework.dart:4355
......................................................etc....................................................................
#273    Element.updateChild
package:flutter/…/widgets/framework.dart:3412
#274    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4690
#275    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4840
#276    Element.rebuild
package:flutter/…/widgets/framework.dart:4355
#277    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2620
#278    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#279    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
#280    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#281    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
#282    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:863
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
The _DeclarativeAutoRouterDelegate sending notification was: Instance of '_DeclarativeAutoRouterDelegate'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════
setState() or markNeedsBuild() called during build.

```

App Main
```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late AppRouter _appRouter;
  late AppState _appState;

  @override
  void initState() {
    super.initState();
    _appRouter = AppRouter();
    _appState = AppState();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AppState>(create: (_) => _appState),
      ],
      child: Builder(
        builder: (BuildContext context) {
          return MaterialApp.router(
            title: 'My App',
            theme: ThemeData(
              primarySwatch: Colors.blue,
              visualDensity: VisualDensity.adaptivePlatformDensity,
            ),
            routerDelegate: AutoRouterDelegate.declarative(
              _appRouter,
              routes: (_) => [
                if (!context.watch<AppState>().initialized) const SplashRoute()
                else if (!context.watch<AppState>().loginState) const LogInRoute()
                else const HomeRoute()
              ]),
            routeInformationParser: _appRouter.defaultRouteParser(),
          );
        }
      ),
    );
  }
}
```

App Router

```
@MaterialAutoRouter(
    replaceInRouteName: 'Page,Route',
    routes: <AutoRoute>[
      AutoRoute(page: SplashPage, initial: true),
      AutoRoute(page: HomePage, path: homeRoutePath),
      AutoRoute(page: LogInPage, path: loginRoutePath),
      AutoRoute(page: SignUpPage, path: signUpRoutePath),
      AutoRoute(page: SettingsPage, path: settingsRoutePath),
      AutoRoute(page: NotFoundPage, path: "/404"),
      RedirectRoute(path: '*', redirectTo: "/404")
    ],
)
class $AppRouter {}
```
## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)      
[√] Connected device (4 available)
• No issues found!
```

I'm Using Auto Route version => 3.1.3

Thanks.

**Comment by ObserverMoment** [comment]
I'm also getting this error when trying to use declarative routing.

@Milad-Akarie, this looks the same bug as #838.

My top level looks very similar.

```
routerDelegate: AutoRouterDelegate.declarative(
              _appRouter,
              routes: (_) => [
                // if the user is logged in, they may proceed to the main App
                if (authState == AuthState.authed && authedUser != null)
                  const AuthedRouter()
                else if (authState == AuthState.loading)
                  const GlobalLoadingRoute()
                // if they are not logged in, bring them to the Login page
                else
                  const UnauthedLandingRoute(),
              ],
            ),
```

**Comment by hamishtech** [comment]
Exact same issue here, any updates on this?

**Comment by ojm-it** [comment]
Same issue

**Comment by artemmmon** [comment]
Same issue. It's a blocker for me right now.

**Comment by ObserverMoment** [comment]
Is everyone using the latest version or is this also present in older versions as indicated by https://github.com/Milad-Akarie/auto_route_library/issues/838#issuecomment-983384524.

Also blocking me releasing an app update so would really like to get this one resolved.

@Milad-Akarie, or any other contributors - are you able to assist or give pointers as to where we should be looking?

**Comment by ojm-it** [comment]
> Is everyone using the latest version or is this also present in older versions as indicated by [#838 (comment)](https://github.com/Milad-Akarie/auto_route_library/issues/838#issuecomment-983384524).

I'm having this issue using the latest version: `auto_route: ^3.1.3` and `auto_route_generator: ^3.1.0`

**Comment by erecord** [comment]
I was experiencing this issue all day.

[Almighty-Alpaca's post](https://github.com/Milad-Akarie/auto_route_library/issues/873) helped me resolve the issue.

I updated my pubspec.yaml to `auto_route: 3.1.2`
- Please note the '^' symbol isn't there on purpose. 

Maybe it will help others resolve the issue until a fix is made?

**Comment by ObserverMoment** [comment]
Dropping down to exact version 3.1.2 has also stopped this error from happening for me. Still testing but it does look like the bug is introduced in `3.1.3`.

**Comment by attitudeboymuzahid-blip** [comment]
<span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="font-family: Verdana; font-weight: normal; font-size: 18pt; color: red;">Server Error in '/' Application.<hr width="100%" size="1" color="silver"></h1><h2 style="font-family: Verdana; font-weight: normal; font-size: 14pt; color: maroon;"><i>Exception of type 'Framework.Notifications.Lib.Exceptions.MOIMobileNotFoundException' was thrown.</i></h2></span><span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif " style="color: rgb(0, 0, 0); font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Description:<span> </span></b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Exception Details:<span> </span></b>Framework.Notifications.Lib.Exceptions.MOIMobileNotFoundException: Exception of type 'Framework.Notifications.Lib.Exceptions.MOIMobileNotFoundException' was thrown.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source Error:</b><br><br>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--


<br><hr width="100%" size="1" color="silver"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Version Information:</b> Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4676.0</font>
