### ISSUE TITLE
Can't replace route by same route with different param without replacing pages

### ISSUE THREAD

**Issue by adimshev** [Milad-Akarie/auto_route_library#854]
Route path: `'/booking/search/!/:departureCode/:arrivalCode/:date/:passengers'`.
I want to change the date so that the date changes in the url and the page keeps the state.
I do not want one route to be visually replaced by another, I just want to change the url.
Is it possible?

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(path: '/', page: HomeScreen, initial: true),
    AutoRoute(
      fullMatch: true,
      path: '/booking/search/!/:departureCode/:arrivalCode/:date/:passengers',
      page: FlightResultsOutboundScreen,
      guards: [DirectionsGuard],
      usesPathAsKey: true,
    ),
    RedirectRoute(path: '*', redirectTo: '/'),
  ],
)
```

When `usesPathAsKey: true` routes visually replace each other (unwanted behavior).
When `usesPathAsKey: false` route visually stay same (desired behavior), guard `onNavigation` fires and `resolver.route.pathParams.get('date')` has updated date (desired behavior), but url has old date from previous route (unwanted behavior).

P.S. I only use guards (and auto_route_library) to restore the state of the website after the user has refreshed the page and to handle deep links for both mobile apps and the site.

Maybe this is the wrong way, so help me please.

**Comment by rbarbosas** [comment]
up

**Comment by payam-zahedi** [comment]
@Milad-Akarie  is there any solution for it?
I had a same issue. I want to update my URL and change query parameters when some state changes in the same page.

**Comment by Milad-Akarie** [comment]
Did you tye navigating to the same page with updated params?
router.navigateNamed('current-path?query=q')

**Comment by payam-zahedi** [comment]
@Milad-Akarie 
This method does not work.
Is there any solution for it.

**Comment by Milad-Akarie** [comment]
@payam-zahedi what happens?

**Comment by payam-zahedi** [comment]
@Milad-Akarie 
The Query parameter change in the widget and routeData, but the URL does not change.
I can log them using
``` dart
context.routeData.queryParams
```

and in widget 

``` dart
widget.id
```

But the URL is still the same.

**Comment by MiaYi** [comment]
Same here, when using `navigateNamed()` to the same path with different query params, the `@QueryParam` in the widget can get  new value but the URL in the browser dose not updated.

**Comment by Milad-Akarie** [comment]
İ can't reproduce this, please share an example.

**Comment by payam-zahedi** [comment]
@Milad-Akarie any update on this?

**Comment by isurugg** [comment]
any update on this?

**Comment by pshastov** [comment]
I'm having the same issue. Any updates on this?

**Comment by ariefwijaya** [comment]
Any update on this?

**Comment by mugikhan** [comment]
Enabling usesPathAsKey and using replaceNamed() does not work.

**Comment by ariefwijaya** [comment]
**[UPDATE]**
I found this worked, but it just invoke `build(context) method` so, we need to put any callback we want on that build method. Not a best practices but we can use it for a while

**Comment by mugikhan** [comment]
> **[UPDATE]** I found this worked, but it just invoke `build(context) method` so, we need to put any callback we want on that build method. Not a best practices but we can use it for a while

That is very bad practice. So you are manually triggering the build function? Might as well do it on navigation which should be handled by the package.

**Comment by ariefwijaya** [comment]
Yes, it is. But we can use it until we have better options. 
Not triggering it manually, when you navigate to the same route, `build` function will be triggered automatically. So, we can use it to refresh our screen or do anything

**Comment by Milad-Akarie** [comment]
@krejko by completely reloading do you mean the initState method of a StatefulWidget is recalled?

**Comment by krejko** [comment]
@Milad-Akarie  Thank you for your comment. I had made the mistake of trying to add this functionality to a StatelessWidget which of course would of course recreates the entire thing. After converting to a StatefulWidget and moving my run-once logic out of the constructor and into the initState method it is now no longer being called more than once.  Given this does seem to be working as expected and this was user-error, I believe this can be re-closed.

**Comment by pnc022022** [comment]
Can you reopen this issue. When I use pushRoute to same screen with difference input. It not replace or reload value of variable

**Comment by VincentDR** [comment]
I got the same issue navigating to the same page, only changing query params.
I think queryParams doesn't count with "usesPathAsKey" as query is not part of the path.

Example:
Opening the app with
http://localhost:8080/messages?missionId=79469&propertyId=417143
then navigating to another page with a button navigating back with a new propertyId
http://localhost:8080/messages?missionId=79469&propertyId=417166

give this output:

```
Build MessagesPages
79469
417143
Build MessagesPages
79469
417143
/messages?missionId=79469&propertyId=417166
UPDATE
417143
417143
Build MessagesPages
79469
417143
```

As you see, the "/messages?missionId=79469&propertyId=417166" is done by the button starting the new navigation.
The update shows that's the widget still hold the same value from QueryParam.


The page with the query params
```
@RoutePage()
class MessagesPage extends StatefulWidget {
  static const String messagesRoutePagePath = 'messages';
  static const String messagesRoutePagePathMissionIdParamName = 'missionId';
  static const String messagesRoutePagePathPropertyIdParamName = 'propertyId';

  final int? missionId;
  final String? propertyId;

  const MessagesPage({
    super.key,
    @QueryParam(messagesRoutePagePathMissionIdParamName) this.missionId,
    @QueryParam(messagesRoutePagePathPropertyIdParamName) this.propertyId,
  });

  @override
  State<MessagesPage> createState() => _MessagesPageState();
}

class _MessagesPageState extends State<MessagesPage> {

  @override
  void didUpdateWidget(covariant MessagesPage oldWidget) {
    super.didUpdateWidget(oldWidget);
    print("UPDATE");
    print(oldWidget.propertyId);
    print(widget.propertyId);
  }

  @override
  Widget build(BuildContext context) {
    print("Build MessagesPages");
    print(widget.missionId);
    print(widget.propertyId);
    return MissionsMessagesCubitsWrapper(
      toSelectMissionId: widget.missionId,
      toSelectPropertyId: widget.propertyId,
      child: MultiResolution(
        large: MessagesPageDesktop(
          missionId: widget.missionId,
        ),
        exceptLarge: const MessagesPageMobile(),
      ),
    );
  }
}

```

The button navigating

```
print(NavigationHelper.createDesktopRouteToMessages(
            missionId:
                missionSelectState is MissionSelectWithValueState ? missionSelectState.selectedMission.missionId : null,
            propertyId: propertyId,
          ));
          context.router.navigateNamed(
            NavigationHelper.createDesktopRouteToMessages(
              missionId: missionSelectState is MissionSelectWithValueState
                  ? missionSelectState.selectedMission.missionId
                  : null,
              propertyId: propertyId,
            ),
          );
```


I tried to play with keepHistory, maintainState and usePathAsKey but with no luck.
I don't really understand what's happening.

**Comment by dawid-niedzwiecki** [comment]
@VincentDR have you found out how to do that? I am having the exact same issue as you do. Please someone answer this, it's so common and there is no answer on the internet.

**Comment by VincentDR** [comment]
> missionSelectState is MissionSelectWithValueState
>                   ? missionSelectState.selectedMission.missionId
>                   : null,

Well, I can't access my old professionnal repo to see the git history to confirm it but I vaguely remember that I switched to a Stateless widget. Maybe I refacto some others things...
If I remember the complete solution, I will post it.

**Comment by Che-ekU** [comment]
Use popAndPush

**Comment by jesus-gueyp** [comment]
Maybe I'm a little bit late for the party but for more people facing this challenge (it is not a bug or a missing feature), I've been working on a Flutter web app and of course **managing correctly the navigation history plus url updates is a must**. 

When working on web we must consider these scenarios for nested content with path params:
1. User signs in with fresh state
2. User refreshes the app / changes the url manually
3. User apply changes to the app which affects the path params / query params

With these scenarios we have to always know how we should react to the app state and url changes without losing the user requested url. In my case I have a resource called 'business' as parent of a lot of more resources, whenever the user change of selected business I must update the app and the url, so I solved it with this little piece of code:
```dart
final router = context.router;

final dest = router.current.route.copyWith(pathParams: Parameters({'businessId': business.id})).toPageRouteInfo();

router.navigate(dest);
```

And that's it! Pure magic without overengineering :) .

Of course, It would vary based on your routing configuration and from where your are calling this `router.current`, in my case, I'm calling it in a child widget of my `AutoTabsRouter` so it will always contain the shell route and the current children.

This is my router config:
```dart
AutoRoute(
  initial: true,
  path: BusinessRoutes.business.path, // '/business' -> Root shell
  page: BusinessShellRoute.page,
  guards: [
    AuthGuard(
      authenticationBloc: _authenticationBloc,
      resolve: (final resolver, final router, final isAuthenticated) {
        if (isAuthenticated) {
            return resolver.next();
         }

          resolver.next(false);
          router.replaceAll([const SignInRoute()]);
        },
      ),
    ],
    children: [
      AutoRoute(
        path: DashboardRoutes.dashboard.path, // ':businessId' -> Path param here
        page: DashboardShellRoute.page,
        children: [
            AutoRoute(initial: true, path: EmployeeRoutes.employees.path, page: EmployeeRoute.page), // 'employees'
            AutoRoute(path: ApiKeyRoutes.apiKeys.path, page: ApiKeysRoute.page), // 'api-keys'
         ],
       ),
       RedirectRoute(path: '', redirectTo: '/business/:businessId/employees'),
     ],
)
```

Hope to help and happy coding :)
