### ISSUE TITLE
AutoTabsScaffold clearing state not working

### ISSUE THREAD

**Issue by olegys** [Milad-Akarie/auto_route_library#855]
Good evening!
Now my AutoTabScaffold saves the state of the initial screen and also the state of all open screens.
How can I make a forced cleanup so that when I navigate through the tabs, initeState works for me?

- key: UniqueKey() for my HomePage doesn't work
- lazyLoad: false for AutoTabScaffold does not work
- AutoRoute (
               maintainState: false, - also does not work
               page: HomePage,
             ),

The state of the tabs is always saved ...
How can I change this behavior?

**Comment by Milad-Akarie** [comment]
@olegys if you require un-maintained state for all of your tab routes you should use an `AutoRouter` instead of `AutoTabsRouter`

**Comment by olegys** [comment]
> @olegys if you require un-maintained state for all of your tab routes you should use an `AutoRouter` instead of `AutoTabsRouter`

Can you please show an example?

**Comment by deezaster** [comment]
I have the same Problem. 

Following example: on Tab1 the actual state is on a child (DetailPage with id=**10**). I switch to Tab2. Then i want to navigate back to DetailPage of Tab1, but with ID=**20**. The switch works but shows the DetailPage with id=10.

Is there a way to overwrite the current state when switching?

```
context.navigateTo(StageRouter(
   children: [StageDetailRoute(stageId: 20)]
));
```

**Comment by markbulingit** [comment]
> > @olegys if you require un-maintained state for all of your tab routes you should use an `AutoRouter` instead of `AutoTabsRouter`
> 
> @Milad-Akarie Can you please show an example?

```
class AuthPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
      return Scaffold(
          body: Row(
            children: [
              Expanded(
                  child: Image.asset(
                "images/purple-bg.jpg",
                fit: BoxFit.cover,
              )),
              Expanded(child: AutoRouter())
            ],
          ),
        );
  }
}
```

**Comment by devyev** [comment]
@Milad-Akarie , what if we want un-maintained state for selected tabs (not all)? Could we use NavigationObserver to reset state for specific routes?

We are trying to fulfill the following use case: show a message every time someone comes to a specific tab route, but not when someone "pops back" to the same route from the list details page, for example, from within the nested route.
