### ISSUE TITLE
Make it possible to pass PreferredSizeWidget nullable for AutoTabsScaffold. 

### ISSUE THREAD

**Issue by darkan23** [Milad-Akarie/auto_route_library#856]
Good evening! 
At the moment, not possible to pass a null PreferredSizeWidget value to AutoTabsScaffold in appBarBuilder.

https://github.com/Milad-Akarie/auto_route_library/blob/955cad85d63778c24340bbd50aff01dfeaa12f6f/auto_route/lib/src/router/widgets/auto_tabs_scaffold.dart#L6

An example of how now :
```
AutoTabsScaffold(
appBarBuilder: (_, tabsRouter) =>
            tabsRouter.topMatch.meta['hideAppBar'] == true
                ? PreferredSize(...)
                : AppBar(...),
      routes: const [...],
      bottomNavigationBuilder: (_, _) {  ...  },
    );
```
Why this is important - we need to not just hide  the appBar, but not create it . It might be a good idea for this particular case to provide a pass of a null PreferredSizeWidget
For Example: 
```
typedef AppBarBuilder = PreferredSizeWidget? Function(
  BuildContext context,
  TabsRouter tabsRouter,
);
```
```
AutoTabsScaffold(
appBarBuilder: (_, tabsRouter) =>
            tabsRouter.topMatch.meta['hideAppBar'] == true
                ? null
                : AppBar(...),
      routes: const [...],
      bottomNavigationBuilder: (_, _) {  ...  },
    );
```

**Comment by ferrerogg** [comment]
I have the same requirement, at the moment I'm using this workaround for returning a "null" appbar in appBarBuilder

```
class NullAppBar extends StatelessWidget implements PreferredSizeWidget {
  const NullAppBar({Key? key}) : super(key: key);

  @override
  Size get preferredSize => const Size.fromHeight(0);

  @override
  Widget build(BuildContext context) => const SizedBox.shrink();
}
```
