### ISSUE TITLE
Blank page in AutoRouter widget when switch between different layouts

### ISSUE THREAD

**Issue by proninyaroslav** [Milad-Akarie/auto_route_library#857]
I'm using roughly the following code:
```Dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[

    ...

    AutoRoute(
      page: SettingsPage,
      path: '/settings',
      children: [
        AutoRoute(
          page: SettingsPagesListPage,
          initial: true,
        ),
        AutoRoute(
          path: 'appearance',
          page: AppearanceSettingsPage,
        ),
       AutoRoute(
          path: 'behavior',
          page: BehaviorSettingsPage,
        ),
      ],
    ),
  ],
)
class $AppRouter {}
```

```Dart
ScreenTypeLayout(
  mobile: AutoRouter(),
  tablet: _TwoPaneBody(),
);
```
`ScreenTypeLayout` is a regular `LayoutBuilder` that determines the screen size and displays the desired widget. On the mobile version I use `AutoRouter`, on the tablet two-pane version I use `AutoTabsRouter` (inside `_TwoPaneBody` widget). When I switch between layouts from tablet mode to phone, I get a blank screen in the mobile version (in `AutoRouter`), although logically it should display the initial route:

![untitled](https://user-images.githubusercontent.com/7840559/143675336-ee04449f-9753-4e5a-9028-1fa727978003.gif)

I also get this exception, but it may not be relevant to this problem:

```
════════ Exception caught by scheduler library ═════════════════════════════════
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
```

**Comment by proninyaroslav** [comment]
@Milad-Akarie 
Pay attention on this please.

**Comment by zippka224** [comment]
@proninyaroslav I had a similar issue.
What I did was wrap the parent widget with AutoRouter and then inject the widget parameter from AutoRouters builder callback down to the widget that needs to render the page.
So, instead of AutoRouter() you would put the widget from
`AutoRouter(builder: (context, WIDGET) => MainMenuScreen(currentPage: WIDGET))`
 and then pass it down where you need it
