### ISSUE TITLE
Navigating to a child route from parent route throwing an exception.

### ISSUE THREAD

**Issue by Simouche** [Milad-Akarie/auto_route_library#861]
I have this router:
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      page: LoginPage,
      initial: true,
      children: [
        AutoRoute(page: OnBoardingPage),
      ],
    ),
    AutoRoute(
      page: RegisterPage,
      children: [
        AutoRoute(page: ActivateAccountDialogPage),
      ],
    ),
    AutoRoute(page: SmartLockerListPage),
  ],
)
class AppRouter extends _$AppRouter {}
```
When i'm on the `LoginPage`, which is the parent of the `OnBoardingPage`, and i try to navigate to the `OnBoardingPage`, with:
`onPressed: () => context.router.push(const OnBoardingRoute()),`
it throws and error:
```
E/flutter (21422): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 
E/flutter (21422): Looks like you're trying to navigate to a nested route without adding their parent to stack first
E/flutter (21422): try navigating to LoginRoute -> OnBoardingRoute
```
how should i navigate?

**Comment by HSCOGT** [comment]
From the docs: To render/build nested routes we need an AutoRouter widget that works as an outlet or a nested router-view inside of our dashboard page.

Use `AutoRoute` inside of your widget tree to render the views. You can see an example here: [https://pub.dev/packages/auto_route#nested-navigation](url), in the second code snippet of the Nested Navigation section.
