### ISSUE TITLE
Application doesn't start with code according to your documentation

### ISSUE THREAD

**Issue by pueffl** [Milad-Akarie/auto_route_library#87]
When I try to switch to auto_route, everything works fine but when I want to start my application, I get the following exception: 

The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#d4d9e):

If no route is provided using home, routes, onGenerateRoute, or onUnknownRoute, a non-null callback for the builder property must be provided, and the other navigator-related properties, navigatorKey, initialRoute, and navigatorObservers, must have their initial values (null, null, and the empty list, respectively).
'package:flutter/src/widgets/app.dart':
Failed assertion: line 192 pos 10: '(home != null ||
          routes.isNotEmpty ||
          onGenerateRoute != null ||
          onUnknownRoute != null)
         ||
         (builder != null &&
          navigatorKey == null &&
          initialRoute == null &&
          navigatorObservers.isEmpty)'

The code of main.dart is as follows:
```
Widget build(BuildContext context) {
    return MaterialApp(
      title: 'eight',
      initialRoute: _getStartupRoute(),
      builder: ExtendedNavigator<Router>(router: Router()),
      localizationsDelegates: [
        const L10nDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
...
```
So according to the exception, I need at least the following parameters set:

- builder
- navigatorKey
- initialRoute

At the moment, I can set the builder according to your documentation, I can also set the initialRoute, but I have no Idea how to set navigatorKey (according to a tutorial with an older version of auto_route (https://resocoder.com/2020/01/10/flutter-zero-boilerplate-router-with-auto-route-flutter-navigation-tutorial/) this was generated once, but not with the version I use (0.4.5)

I don't think that auto_route is not working at all, I think that the documentation just needs a more complete exampte in 'Finalize the Setup', the example you provide definitely doesn't work and I have no idea, how to fix this.

**Comment by Milad-Akarie** [comment]
Hey @pueffl The Video by Reso is a bit outdated, sorry about that!
Maybe I'll try to make my own updated Video. 

Anyways
try setting the initialRoute in the ExtendedNavigator not the MaterialApp, I believe that's what's causing the error.
Tip: You don't actually need to set the initialRoute if you annotate your HomePage with @Initial

**Comment by pueffl** [comment]
You are right, without initialRoute everything works so far :-)

Documenting this and documenting the arguments of ExtendedNavigator would be helpful. Needed some time to find out that I can specify initialRoute as argument of ExtendedNavigartor.

Thx.
