### ISSUE TITLE
Back button for nested routes?

### ISSUE THREAD

**Issue by wiradikusuma** [Milad-Akarie/auto_route_library#870]
I have two routes, simple and nested:

```
    AutoRoute(
      page: ProfilePage,
      path: '/profile',
    ),
    AutoRoute(
      children: [
        AutoRoute(page: AddressesPage, path: ''),
        AutoRoute(page: AddressesAddPage, path: 'add'),
      ],
      name: 'AddressRouter',
      page: EmptyRouterPage,
      path: '/addresses',
    ),
```

The back button is only shown in `ProfilePage`, despite both using `Scaffold` with app bar. If this is the expected behaviour, how do I force show the back button in nested route?

**Comment by wiradikusuma** [comment]
I notice that the back button also disappears when a page is made into a guard.

**Comment by Milad-Akarie** [comment]
@wiradikusuma  did you want the back button to be in the wrapper page 'AddressRouter'?

**Comment by wiradikusuma** [comment]
@Milad-Akarie I think so, because: 

1. We can't be sure which page will be opened first. 
2. But we still want to be able to go back (in Android, you can press Back button).

But any solution (however hackish) works for me.

**Comment by wiradikusuma** [comment]
Hi @Milad-Akarie , just wondering if you have update on this? Basically any page with a Back button, once become a guard, will stop having the Back button.

**Comment by Milad-Akarie** [comment]
@wiradikusuma have you tried using AutoBackButton() as leading widget in your app bar?
