### ISSUE TITLE
How to pass Key parameter in .navigateNamedTo()

### ISSUE THREAD

**Issue by deezaster** [Milad-Akarie/auto_route_library#872]
For cross-tab navigation I have the methods **.navigateTo()** and **.navigateNamedTo()**.

```
context.navigateNamedTo('stage/4');

context.navigateTo(StageRouter(
    children: [StageDetailRoute(key: UniqueKey(), stageId: 4)]
));
```

With .navigateTo I can pass the key parameter. How can I do this with .navigateNamedTo?

**Comment by cfregin** [comment]
[Working with Paths](https://autoroute.vercel.app/basics/working_with_paths) should give you the answer. Are you missing the `@PathParam` ?

**Comment by deezaster** [comment]
No, I have not forgotten `@PathParam`

```
class StageDetailPage extends StatefulWidget {
  final int stageId;

  const StageDetailPage({
    Key? key,
    @PathParam() required this.stageId,
  }) : super(key: key);

  @override
  _StageDetailPageState createState() => _StageDetailPageState();
}
```

I do not know how to define **multiple parameters**

```
:
CustomRoute(
    path: ':stageId',
    page: StageDetailPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
),
:
```

I don't think that is possible

`path: ':stageId:key',`

or 

`path: ':stageId?key',`

**Comment by Milad-Akarie** [comment]
@deezaster named navigation only allows path/query parameters therefor it only allows arguments that can be parsed from string values e.g (String, bool, int,double)
is there a reason why you shouldn't use object navigation?

**Comment by deezaster** [comment]
Yes, I want to make the navigation fully dynamic. i.e. I get the path from the backend (via REST API). Example: In the backend the navigation to a specific app page is defined per news article.

With context.navigateNameTo() I can define the path as a variable (url).

`context.navigateNamedTo(url);`

How can I do this with the object navigation? I don't want a page long if/else construct.

**Comment by Milad-Akarie** [comment]
@deezaster I see, the best approach I can think of giving current info is to pass your unique key as query param (String) and build it inside of the widget


```dart
  final uri = Uri.parse(url)
    ..queryParameters['uniqueKey'] = UniqueKey().toString();
  final urlWithKey = uri.toString();
  context.navigateNamedTo(urlWithKey);
```

then inside of your widget

```dart
class UniquePage extends StatefulWidget {
  UniquePage({ @queryParam required String uniqueKey})
      :super(key: ValueKey(uniqueKey),);
}
```
