### ISSUE TITLE
Page Stack when using AutoRouter.declarative

### ISSUE THREAD

**Issue by MartiSilvio** [Milad-Akarie/auto_route_library#873]
Hello everyone, 

I am using the solution provided in #792 to route between pages, in my case for authentication. My issue is that when each page is pushed it replaces the previous one in the stack, resulting in a page stack contains only one page at a time. Is it possible that each page can be simply pushed on top of the last one? That way i can have back functionality without emitting a new state.

Thank you

**Comment by Almighty-Alpaca** [comment]
Looks related to #838 and #853

**Comment by Almighty-Alpaca** [comment]
I've just implemented something similar myself, and at least the solution by @ronba in #792 works if you pin the version of `auto_route` to `3.1.2`

**Comment by cfregin** [comment]
> I've just implemented something similar myself, and at least the solution by @ronba in #792 works if you pin the version of `auto_route` to `3.1.2`

That solution does not fix the setState bug for me neither.

**Comment by erecord** [comment]
@cfregin I've had this same issue and thought @Almighty-Alpaca's advice didn't work either.

However, I was changing my pubspec.yaml to this:
`auto_route: ^3.1.2`

When actually I **shouldn't** have used the '^' symbol. 

I no longer got the error when I updated it to this:
`auto_route: 3.1.2`

Maybe you did the same as me and this may help you?

**Comment by cfregin** [comment]
> @cfregin I've had this same issue and thought @Almighty-Alpaca's advice didn't work either.
> 
> However, I was changing my pubspec.yaml to this: `auto_route: ^3.1.2`
> 
> When actually I **shouldn't** have used the '^' symbol.
> 
> I no longer got the error when I updated it to this: `auto_route: 3.1.2`
> 
> Maybe you did the same as me and this may help you?

I can confirm that. 3.1.2 is not throwing that exception.

**Comment by Milad-Akarie** [comment]
should be fixed in version 3.2.0
sorry for the delay.

**Comment by cfregin** [comment]
Thank you @Milad-Akarie ! That seems to fix #853 and #838 as well.
