### ISSUE TITLE
what is the best way to extend the book demo to handle doubly-nested routes?

### ISSUE THREAD

**Issue by wombat888** [Milad-Akarie/auto_route_library#875]
I would like to know how to properly handle doubly-nested routes using autoroute.

The demo has been [slightly extended](https://github.com/wombat888/autoroute-test) to display a list of publishers for each book in the book details page and add navigation to a publisher details page. I am not sure how to properly navigate to the publisher details page. I would expect the URL might look like `http://localhost:60408/books/:bookid/publishers/:publisherid`. An error is reported when trying to navigate to the publisher details page from the publisher list in the book details page:

```text
Looks like you're trying to navigate to a nested route without adding their parent to stack first
try navigating to BookDetailsRoute -> BookPublishers -> BookPublisherDetailsRoute
```

I'm not sure whether this would require modifying the router specification, changing the way that the routes are traversed in the pages, or perhaps both.

```text
@MaterialAutoRouter(
  replaceInRouteName: 'Page|Dialog,Route',
  routes: <AutoRoute>[
    // app stack

    AutoRoute<String>(
      path: '/',
      page: HomePage,
      // guards: [nAuthGuard],
      children: [
        AutoRoute(
          path: 'books',
          page: EmptyRouterPage,
          name: 'BooksTab',
          initial: true,
          children: [
            AutoRoute(
              path: '',
              page: BookListPage,
            ),
            AutoRoute(path: ':bookId', page: BookDetailsPage, meta: {
              'hideBottomNav': true
            }, children: [
              AutoRoute(
                path: 'bookPublishers',
                page: EmptyRouterPage,
                name: 'BookPublishers',
                children: [
                  AutoRoute(
                      path: ':bookPublisherId', page: BookPublisherDetailsPage),
                ],
              ),
            ]),
          ],
        ),
        profileTab,
        AutoRoute(
          path: 'settings/:tab',
          page: SettingsPage,
          name: 'SettingsTab',
        ),
      ],
    ),
    userDataRoutes,
    // auth
    AutoRoute(page: LoginPage, path: '/login'),
    RedirectRoute(path: '*', redirectTo: '/'),
  ],
)
class $RootRouter {}
``

If someone can extend the demo properly it would be appreciated.

thanks!

**Comment by Milad-Akarie** [comment]
@wombat888  just like when using strings you need to go 'publishers/publishers_id'
you need to push parent route (`BookPublishers`) then it's child (`BookPublisherDetailsRoute`)

`router.push(BookPublishers(children:[BokPublishersDetailsRoute()bookPublisherId: bookPublisherId)]);`
