### ISSUE TITLE
replaceInRouteName replace should be limited to last occurence

### ISSUE THREAD

**Issue by bounty1342** [Milad-Akarie/auto_route_library#876]
@Milad-Akarie,

This is a funny one, it tooks me like 2minutes to find my router 😄 

`With   replaceInRouteName: 'View,Route', CreationPdfViewerView became CreationPdfRouteerRoute
`

Could those String be regex maybe ? Or replace the last occurence instead of all of them ?

Regards

**Comment by Milad-Akarie** [comment]
Hey @bounty1342  I'll see what I can do about this.
