### ISSUE TITLE
Is it safe to inject this router?

### ISSUE THREAD

**Issue by ericel** [Milad-Akarie/auto_route_library#877]
I am not sure if this has been answered yet, I am injecting my router as follows:
```
@module
abstract class RegisterCoreDependencies {
  static final AppRouter appRouter =
      AppRouter(authGuard: AuthGuard(), loginAuthGuard: LoginAuthGuard());
}
```

Then in main.dart
```
return Consumer<AppStateNotifier>(
              builder: (context, appState, child) {
            return LocalizationProvider(
              state: LocalizationProvider.of(context).state,
              child: MultiProvider(
                providers: [
                  StreamProvider<UserModel?>.value(
                    value: AuthService().documentStream,
                    catchError: (_, __) => null,
                    initialData: null,
                    lazy: true,
                  ),
                  child:
                     MaterialApp.router(
                      routerDelegate: locator<AppRouter>().delegate(
                       navigatorObservers: () => [
                         AutoRouteObserver(),
                        locator<AnalyticsService>().getAnalyticsObserver(),
                      ],
                    ),
                   routeInformationParser: locator<AppRouter>().defaultRouteParser(),
                   localizationsDelegates: [ ....
```
My question is, is this even advisable? And what possible drawbacks are there?
I first did it this way because I want to handle push notifications and app was in development. Now that it's about to be released to production.
Is this an okay or good setup? Thanks

**Comment by Milad-Akarie** [comment]
@ericel I personally think it's fine  especially if you're going to use it for deep-links  (navigating from root) just make sure it's a singleton or a lazySingleton so it's only initiated once. 

in older versions I advised against using none-scoped injection for nested routers but now auto_roue  tries to automatically find the right scope of the pushed route so it should be fine.

**Comment by ericel** [comment]
Thanks, @Milad-Akarie. I will keep it as it is for now then. I need the deep-links functionality unless there is any other way to deal with the deep-links navigation?
