### ISSUE TITLE
'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'type' after upgrading to Flutter 2.8

### ISSUE THREAD

**Issue by Chinmay-KB** [Milad-Akarie/auto_route_library#878]
This issue was earlier reported #755 , which was caused while running on beta channel. Now after upgrading to Flutter 2.8 stable release, this issue has resurfaced. I'm currently using `auto_route:^3.1.3`

Flutter doctor
```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.8.0 at /Users/user/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Nokia 5 4 (mobile) • PD21ADD664007704 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 96.0.4664.93
    ! Error: User’s iPhone is not connected. Xcode will continue when User’s iPhone is connected. (code -13)

• No issues found!
```

**Comment by marenovakovic** [comment]
Same error here....

```
../../.pub-cache/hosted/pub.dartlang.org/auto_route-3.1.0/lib/src/router/provider/auto_route_information_provider.dart:28:8: Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'type' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
  void routerReportsNewRouteInformation(RouteInformation routeInformation,
       ^
../../flutter/packages/flutter/lib/src/widgets/router.dart:1329:8: Context: This is the overridden method ('routerReportsNewRouteInformation').
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {required RouteInformationReportingType type}) {}
       ^
../../.pub-cache/hosted/pub.dartlang.org/auto_route-3.1.0/lib/src/router/controller/auto_router_delegate.dart:26:43: Error: Required named parameter 'type' must be provided.
        ?.routerReportsNewRouteInformation(
```

**Comment by N1ght-Fury** [comment]
Same here. I guess ill downgrade flutter back to 2.5.3 untill it gets fixed

**Comment by DanielToubul** [comment]
Same :D

**Comment by lcdsmao** [comment]
Seems there are already some PRs to fix this:
- https://github.com/Milad-Akarie/auto_route_library/pull/880
- https://github.com/Milad-Akarie/auto_route_library/pull/839
- https://github.com/Milad-Akarie/auto_route_library/pull/756
- https://github.com/Milad-Akarie/auto_route_library/pull/712

**Comment by Chinmay-KB** [comment]
The issue can be solved by adding a simple parameter, for which multiple PRs are already open. The issue is when I tried to add `auto_route` as a git repo in pubspec.yaml, because I am also using auto_route_generator, there's some kind of conflict which pub cannot resolve, and the only way I could find is downloading a copy of the code and adding the packages to pubspec as a local import, which is too much work for an issue this small imo.

**Comment by Milluz** [comment]
For now you can make an dependency override.
Putting this on the pubspec.yaml

```yaml
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```

**Comment by CassiusPacheco** [comment]
> For now you can make an dependency override. Putting this on the pubspec.yaml
> 
> ```yaml
> dependency_overrides:
>   auto_route:
>     git:
>       url: https://github.com/Agondev/auto_route_library
>       path: auto_route
> ```

How would you make this work with `auto_route_generator` @Milluz? It depends on `auto_route` and because `auto_route` is fetched, `auto_route_generator` can't resolve it by path, git or hosted.

**Comment by StraussPorcupine** [comment]
Best solution found so far is to downgrade to 2.5.3 and force your CI to 2.5.3

**Comment by Milluz** [comment]
> > For now you can make an dependency override. Putting this on the pubspec.yaml
> > ```yaml
> > dependency_overrides:
> >   auto_route:
> >     git:
> >       url: https://github.com/Agondev/auto_route_library
> >       path: auto_route
> > ```
> 
> How would you make this work with `auto_route_generator` @Milluz? It depends on `auto_route` and because `auto_route` is fetched, `auto_route_generator` can't resolve it by path, git or hosted.

Weird one, it's works fine for me... Maybe because I point to the auto_route_generator version?

```dart
dev_dependencies:
  auto_route_generator: ^3.1.0
```

**Comment by chaonan-artera** [comment]
Same here. We are downgrade to 2.5.3 until it's fixed.

**Comment by lloydrichards** [comment]
I've tried downgrading to fix the same issue but get the following error:
```
Running "flutter pub get" in hive-connector...                  
Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.
pub get failed (1; Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.)
exit code 1
```
any fixes?

**Comment by N1ght-Fury** [comment]
> I've tried downgrading to fix the same issue but get the following error:
> 
> ```
> Running "flutter pub get" in hive-connector...                  
> Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.
> pub get failed (1; Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.)
> exit code 1
> ```
> 
> any fixes?

I guess by mistake you tried to downgrade auto_route package instead of Flutter. Add `auto_route: ^3.1.3` as dependency and try to downgrade flutter by typing `flutter downgrade`

**Comment by lloydrichards** [comment]
🤦‍♂️ yep, thats what happened

> > I've tried downgrading to fix the same issue but get the following error:
> > ```
> > Running "flutter pub get" in hive-connector...                  
> > Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.
> > pub get failed (1; Because hive_connector depends on auto_route ^2.5.3 which doesn't match any versions, version solving failed.)
> > exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > any fixes?
> 
> I guess by mistake you tried to downgrade auto_route package instead of Flutter. Add `auto_route: ^3.1.3` as dependency and try to downgrade flutter by typing `flutter downgrade`

🤦‍♂️ yep, thats what happened

**Comment by masoudk2000** [comment]
Same here 
@Milad-Akarie

**Comment by Hatem-Saad** [comment]
@masoudk2000 
just replace it with the previous one
here:
https://github.com/flutter/flutter/blob/2.5.3/packages/flutter/lib/src/widgets/router.dart

**Comment by jumamz01** [comment]
hi @Milad-Akarie any fix? this is a bug that needs to address. hope you address it very soon thanks

**Comment by Milad-Akarie** [comment]
I apologize for the delay guys, I moved to a new country and I've been settling down for the last couple days.
a new build is coming...

**Comment by Milad-Akarie** [comment]
Should be fixed in update 3.2.0

**Comment by CassiusPacheco** [comment]
Thanks Milad, you’re great! 🙏

**Comment by RicardoRB** [comment]
Getting this error now:

```
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: Type 'RouteInformationReportingType' not found.
      {required RouteInformationReportingType type}) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:29:8: Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'isNavigation' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
  void routerReportsNewRouteInformation(RouteInformation routeInformation,
       ^
/C:/flutter/flutter/packages/flutter/lib/src/widgets/router.dart:1340:8: Context: This is the overridden method ('routerReportsNewRouteInformation').
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {bool isNavigation = true}) {}
       ^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/controller/auto_router_delegate.dart:30:17: Error: Getter not found: 'RouteInformationReportingType'.
          type: RouteInformationReportingType.navigate,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/controller/auto_router_delegate.dart:30:11: Error: No named parameter with the name 'type'.
          type: RouteInformationReportingType.navigate,
          ^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: 'RouteInformationReportingType' isn't a type.
      {required RouteInformationReportingType type}) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:31:27: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
 - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
    var replace = type == RouteInformationReportingType.neglect ||
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:32:18: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
 - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
        (type == RouteInformationReportingType.none &&
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by Chinmay-KB** [comment]
> Getting this error for fluter 2.5.3:
> 
> ```
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: Type 'RouteInformationReportingType' not found.
>       {required RouteInformationReportingType type}) {
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:29:8: Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'isNavigation' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
>   void routerReportsNewRouteInformation(RouteInformation routeInformation,
>        ^
> /C:/flutter/flutter/packages/flutter/lib/src/widgets/router.dart:1340:8: Context: This is the overridden method ('routerReportsNewRouteInformation').
>   void routerReportsNewRouteInformation(RouteInformation routeInformation, {bool isNavigation = true}) {}
>        ^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/controller/auto_router_delegate.dart:30:17: Error: Getter not found: 'RouteInformationReportingType'.
>           type: RouteInformationReportingType.navigate,
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/controller/auto_router_delegate.dart:30:11: Error: No named parameter with the name 'type'.
>           type: RouteInformationReportingType.navigate,
>           ^^^^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: 'RouteInformationReportingType' isn't a type.
>       {required RouteInformationReportingType type}) {
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:31:27: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
>  - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
>     var replace = type == RouteInformationReportingType.neglect ||
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:32:18: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
>  - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
>         (type == RouteInformationReportingType.none &&
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ```

Using version 3.1.3 should fix this.

**Comment by lloydrichards** [comment]
> Getting this error for fluter 2.5.3:

you might also need to do a `flutter clean` + `flutter pub get` to make sure nothing is in your cache

**Comment by raduungurean** [comment]
Hi @Milad-Akarie ,

I'm getting something similar but with isNavigation parameter


../flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.0/lib/src/router/provider/auto_route_information_provider.dart:29:8: Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'isNavigation' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
  void routerReportsNewRouteInformation(RouteInformation routeInformation,

Thanks

**Comment by Sang-Nguyen-ADVN** [comment]
I have the same case
<img width="1403" alt="Screen Shot 2021-12-27 at 08 26 37" src="https://user-images.githubusercontent.com/15792841/147425335-d247e8f8-efb5-4964-afd4-27e83674025b.png">
