### ISSUE TITLE
Give optional Prefix to Router annotation

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#88]
Sometimes we wish to add a prefix like : "/myModule" to each screen that comes inside the specific module.
We need an optional prefix option to the Router annotation , so that all the generated routes inside the router come with that prefix.

Example : 

```
@MaterialAutoRouter(prefix="/myModule"){
    MyScreen myhomepage ;
}
```

So generated Routes would look like : 

```
Routes{
   static const myhomepage = '/myModule/myhomepage' ;
}
```

**Comment by nateshmbhat** [comment]
this can also help to some extent in nested routing

**Comment by Milad-Akarie** [comment]
@nateshmbhat That's actually a good idea. 
guess we could also omit the useLeadingSlashes option for this.

**Comment by nateshmbhat** [comment]
Yes, removing useLeadingSlashes makes a lot of sense since it would raise ambiguity otherwise.

If that's removed, user can specify leading Slash himself anyway
