### ISSUE TITLE
Customizable placeholder for AutoTabsRouter

### ISSUE THREAD

**Issue by DenRbkv** [Milad-Akarie/auto_route_library#881]
Hello @Milad-Akarie ! I have an issue. Not a bug, but an issue related mostly to AutoTabsRouter.
**Here's the case:** I've got some pages in my AutoTabsRouter(duration is set to zero), each page has a separate Scaffold, AppBar and BottomBar. All AutoTabsRouter's pages have different appbars and some of them have nested pages with different appbars too. So I considered separate Scaffolds as a good approach here. 
**Here's the issue:** As we all know, AutoTabsRouter have got a lazyLoad property. It also gives us a bit of an undesired(to my taste) behavior when page show us an empty screen before being loaded, which also quite noticeable even in the release build. 
Example: we've got some pages in AutoTabsRouter, lazyLoad is enabled -> we are starting from the initial page which belongs to AutoTabsRouter too -> we **initially** go to the next page -> we see the blank screen(which has a configurable color through theme I believe) for less than a second -> we got our next page loaded.
I know this behavior could be avoided by setting up lazyLoad to false, but I would like to keep lazyLoad to increase speed of the apps and reduce amount of server requests in production applications(actually I'm already using AutoRouter for prod).
I've also had set up the custom autoroute observer(which extends the default AutoRouteObserver) to get some nice logs in console. So, I noticed that quite a lot of transitions are going to the _PlaceHolderPage before going to the actual page, which I believe is the actual empty screen that we see between the lazy tabs(though I'm still not sure). I did a bit of investigation and found out it depends on the placeholder of the AutoRouteNavigator which is getting placeholder from the AutoRouterDelegate's constructor. But for some reason custom delegate's placeholder is working only before the initial route. I guess it's happening because of some internal check which I haven't discovered yet.
**Desired behavior:** Would be pretty cool if we could've set up a custom separated placeholder for each of the lazy tabs. I don't know if there is currently a way to make a custom placeholders on current AutoRoute version(I'm using the latest version), but for now I haven't found any.

I've also made a [tiny video](https://youtu.be/NINarePx8_0) on it so issue could be more understandable.

You can contact me if you need any additional info. Thank you.

**Comment by Milad-Akarie** [comment]
Hello @DenRbkv I read your issue after publishing a new build, in the new build placeholders are handled differently, ( they won't  show in the log) because they're not page-based-placeholders any more. 
could you check if you're still have the flicker with the new update?

**Comment by DenRbkv** [comment]
Hello again @Milad-Akarie Just checked it out, the flicker still appears and still noticeable. Thx for quick response

**Comment by DenRbkv** [comment]
@Milad-Akarie Hello. Just updated to 3.2.3+1. The lazyLoad's flicker still appears in this version.
