### ISSUE TITLE
make onGenerateRoute method as static

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#89]
There are certain use cases where we will not be using ExtendedNavigator and would be using our own custom navigator that handles the navigation and some other business logic.

In these cases we need access to the onGenerateRoute function inside the router classes. 

So please either make it `static` or give optional parameter in `Router` annotation to make it static .

**Comment by Milad-Akarie** [comment]
@nateshmbhat it was static at some point then after some discussions with a number of you users we decided to make it concrete class so it's test friendly. 
Any ways. I was thinking of a way to make the generated Router independent of the ExtendedNavigator and that's still in progress. 

What you can do for now is 

```dart
MaterialApp(
      onGenerateRoute: Router().onGenerateRoute,
)
```
But then you won't be able to use Route guards or any other extended feature.

**Comment by nateshmbhat** [comment]
ok cool , for now i can access this function using the `Router()` object anyway 👍
