### ISSUE TITLE
Add "context" to AutoRouteGuard

### ISSUE THREAD

**Issue by tomasweigenast** [Milad-Akarie/auto_route_library#890]
Add `BuildContext` reference to `AutoRouteGuard` `onNavigation`. 
I have a sidebar with a list of items that change their colors when an item is selected and redirected to a route. I use `provider` to update the state, but if I go to a specific url in the browser, the sidebar is not updated. I can do that using RouteGuards and updating state when navigating, but I need `context`

**Comment by bounty1342** [comment]
You could have it like this :  final BuildContext? context = router.navigatorKey.currentContext;

But on the 2.2.0, my context it empty :/

**Comment by bounty1342** [comment]
@markokosticdev, in fact, it's empty until the first build. So if you guard the login page, it's not very practical... 

https://api.flutter.dev/flutter/widgets/GlobalKey/currentContext.html

**Comment by Milad-Akarie** [comment]
@TomasWeg @bounty1342 please consider injecting your service classes directly to the guard, this's a safer and cleaner approach.
in older versions I did some workarounds to make sure `navigatorKey.currentContext` is always available but that  introduced some difficulties in other areas.

This how I would do it
assuming my service class is provided above `App Widget`

```dart
class AppState extends State<App> {
  late final AppRouter appRouter;
  @override
  void initState() {
    super.initState();
   final authService = Provider.of<AuthService>(context,listen: false);
    appRouter = AppRouter(authGuard: AuthGuard(authService));
  }
...
}
```

**Comment by TomasWeg** [comment]
@Milad-Akarie thanks you!!!
