### ISSUE TITLE
Expected a value of type "CustomPage<dynamic>"

### ISSUE THREAD

**Issue by MkamaAFM** [Milad-Akarie/auto_route_library#892]
I upgraded flutter to 2.8.0. after that, my app just shows a red screen with text `Expected a value of type 'CustomPage<dynamic>', but got one of type 'AdaptivePage<dynamic>'`

I use autoroute v 3.2.0

**Comment by deive** [comment]
I am using a fairly simple @AdaptiveAutoRouter and it is working perfectly on all platforms, except for web - where it is giving me this error as well.

**Comment by Filip7656** [comment]
I have the same issue, only workaround I found i to manually change all AdaptivePage to CustomPage

**Comment by Milad-Akarie** [comment]
@MkamaAFM @deive @Filip7656  should be fixed in version 3.2.1

**Comment by deive** [comment]
My @AdaptiveAutoRouter is now working across the board, thanks!
