### ISSUE TITLE
FlutterError - Bad state: No element

### ISSUE THREAD

**Issue by westito** [Milad-Akarie/auto_route_library#896]
```dart
throw FlutterError(
            "\nLooks like you're trying to navigate to a nested route without adding their parent to stack first \n"
            "try navigating to ${path.map((e) => e.name).reduce((a, b) => a += ' -> ${b}')}");
```

This exception fail to throw because of empty reduce. Console prints unmeaning error:

```
The following StateError was thrown building RootPage:
Bad state: No element
```

**Comment by joprice** [comment]
I get this as well when I have a page with children that uses `AutoTabsScaffold`, and one of the tabs routes to a route that is not one of the page's children. This makes sense, but maybe the error could also hint toward it (besides fixing the empty reduce), as it's not obvious and there's no compile time check.
