### ISSUE TITLE
Prefix route constants in generated router switch statements with router class

### ISSUE THREAD

**Issue by kuhnroyal** [Milad-Akarie/auto_route_library#9]
I just had a conflict with a route named `settings`. This conflicts in the generated router class with `RouteSettings settings`.

This can simply be fixed by always prepending the router class to all constant expressions:
```dart
case settings: // conflict
// to
case AppRouter.settings:
```

**Comment by Milad-Akarie** [comment]
I'll take a look at it.

**Comment by Milad-Akarie** [comment]
done in version 0.2.1.
