### ISSUE TITLE
Add a getter in Router class to get all Routes

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#90]
The use case is that given a set of Router objects , I need to check if a given route String belongs to a certain router.

For this you would need to expose a method or `getter` that return all routes that are being handled by that `Router`.

If you add such a method , it would add that missing link between Router class and Route class for the user of your API.

**Comment by Milad-Akarie** [comment]
Hey @nateshmbhat 
Thanks for your efforts!
This might help
```dart
@MaterialAutoRouter(
    generateRouteList: true
    )
```
This will generate a list of all generated routes inside of  the "Routes" class

**Comment by nateshmbhat** [comment]
Yes I'm asking that the Router class would have a getter for the routes list.

**Comment by nateshmbhat** [comment]
But make sure that you add this getter method to the RouterBase class itself since, the whole point of writing this method is to access the routes during run time.

An interface in the baseclass is needed for this :)

**Comment by nateshmbhat** [comment]
I think it's a small feature and easy to implement but covers some good use cases

**Comment by Milad-Akarie** [comment]
That's a good idea. I'll be adding it to the next build. 
Thanks again.

**Comment by nateshmbhat** [comment]
sure , my pleasure 😄 
waiting patiently for the build 🧘

**Comment by nateshmbhat** [comment]
@Milad-Akarie also there's one small change that can slightly optimize things.

Instead of generating a List of Routes , you could generate a `Set` since the order in which the routes are declared is irrelavant.

This would mean that any lookup operations would take O(1) or Constant time .

Likewise i would suggest adding the appropriate getter method in Router to get `Set<Routes>` instead of `List<Routes>`
