### ISSUE TITLE
Generated .gr file is not consistent anymore

### ISSUE THREAD

**Issue by Tiska** [Milad-Akarie/auto_route_library#900]
Hi :) In last version of generator 3.2.0, generation of the .gr file is not consistent anymore. If I change code in my app, the file change even if this files has nothing to do with navigation objects. In previous version file generation was consistent.

**Comment by Milad-Akarie** [comment]
@Tiska you mean it regenerates when you work with none routable widgets or non-widget classes?

**Comment by Tiska** [comment]
yes that's it, the file changes every time I change any dart file on the project, even if it's not a widget referenced in a router
