### ISSUE TITLE
Pass parameters to first child

### ISSUE THREAD

**Issue by NajdatA** [Milad-Akarie/auto_route_library#901]
When I am putting children inside a route the parent route by default returning first child without being able to pass required params to it, how can I solve this problem?

`AutoRoute(
      page: ParentPage,
      children: [
        AutoRoute(page: ChildOnePage,path: ''),
        AutoRoute(page: ChildTwoPage),
        AutoRoute(page: ChildThreePage),
      ],
    ),`

`class ChildOnePage extends StatefulWidget {
  final Widget x;
  const ChildOnePage({Key? key, required this.x}) : super(key: key);

  @override
  _ChildOnePageState createState() => _ChildOnePageState();
}
`
how can I pass data to (x)?

**Comment by Seanhjlo** [comment]
I have the same question, @NajdatA did you ever figure it out?

**Comment by nzkn** [comment]
I have the same question. Is there any solution for this?

**Comment by Milad-Akarie** [comment]
router.push(parentRoute(children:[ChildRoute(childParam)]))
