### ISSUE TITLE
 Failed assertion: line 1538 pos 14: '_effectiveRouteInformationProvider != null': is not true.

### ISSUE THREAD

**Issue by fadibouteraa** [Milad-Akarie/auto_route_library#905]
I always get this error trying to run my app when using auto_route.
version : auto_route: ^3.2.0
MaterialApp.router(
                      supportedLocales: S.delegate.supportedLocales,
                      routerDelegate: _appRouter.delegate(),
                      routeInformationParser: _appRouter.defaultRouteParser(),
/..................

**Comment by Milad-Akarie** [comment]
@fadibouteraa  are you on the latest stable flutter version?

**Comment by fadibouteraa** [comment]
@Milad-Akarie 
yes when i insert this code , the problem is solved 
routeInformationProvider: _appRouter.routeInfoProvider(),
i have another question plz 
 With modular architecture , is it possible to add argument in pushname
knowing that i'm using : auto route (MaterialAutoRouter) in lib
thank you in advance
