### ISSUE TITLE
How to push routes based on firebase auth's authstate? 

### ISSUE THREAD

**Issue by Wizzel1** [Milad-Akarie/auto_route_library#906]
My current configuration looks like this: 

```
@CustomAutoRouter(
  customRouteBuilder: myCustomRouteBuilder,
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      path: '/',
      name: 'AuthRoute',
      page: EmptyRouterPage,
      children: [
        RedirectRoute(path: '', redirectTo: 'login'),
        AutoRoute(path: 'login', page: LoginPage),
      ],
    ),
    AutoRoute(
      path: '/',
      page: ResponsiveLayoutPage,
      guards: [AuthGuard],
      children: [
        RedirectRoute(path: '', redirectTo: 'dashboard'),
        AutoRoute(
          path: 'dashboard',
          page: DashboardPage,
          guards: [AuthGuard],
        ),
      ],
    ),
  ],
)
```

on my `LoginPage` I manually call `context.replaceRoute(const ResponsiveLayoutRoute());` after I awaited the `signInWithEmailAndPassword` call but I feel like there has to be a better solution. 
Is there a way to build the routes based on `authStateChanges` `User` ?

**Comment by Milad-Akarie** [comment]
@Wizzel1  have you tried the `AutoRedirectGuard` ? it's not yet in the docs but you can find a working version in the example.

**Comment by Wizzel1** [comment]
@Milad-Akarie I haven't, thanks for pointing it out. Will try that asap.

Thanks for your hard work and have a happy new year!

**Comment by Wizzel1** [comment]
@Milad-Akarie  Okay so I tried it and it seems like it is exactly what I needed. 

However, I have noticed an unexpected behavior: 

My AuthGuard now looks like this
```dart
class AuthGuard extends AutoRedirectGuard {
  final ProviderRef ref;

  AuthGuard(this.ref) {
    ref.watch(authRepositoryProvider).authStateChanges.listen((event) {
      reevaluate();
    });
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final user = ref.read(authRepositoryProvider).getCurrentUser();

    if (user != null) {
      resolver.next();
    } else {
      redirect(const AuthRoute(children: [LoginRoute()]), resolver: resolver);
    }
  }
}
```

My AutoRoute is the same as above. 

So when I am at the  `LoginPage` and type `/dashboard` to the Url-Field, the Url immediately changes to `/login` (as expected).

However, when I type `/dashboard`  again, it stays like this. (But doesn't actually navigate). So in this scenario, the user would be on the `LoginPage` but the Url says `/dashboard`. Do you have any Idea why the redirect doesn't work as expected in this case?

**Comment by alijamal6459** [comment]
have you managed to figure it out? im trying to figure the same thing

**Comment by Wizzel1** [comment]
Actually, this works now: 

```dart
class AuthGuard extends AutoRedirectGuard {
  final ProviderRef ref;

  AuthGuard(this.ref) {
    ref.read(authRepositoryProvider).authStateChanges.listen((event) {
      reevaluate();
    });
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final user = ref.read(authRepositoryProvider).getCurrentUser();

    if (user != null) {
      resolver.next();
    } else {
      redirect(const AuthRoute(children: [LoginRoute()]), resolver: resolver);
    }
  }
}
```
Maybe calling .watch() instead of .read() on the provider was the problem
