### ISSUE TITLE
CustomRoute Staggered Animation in Page Transition.

### ISSUE THREAD

**Issue by fmatuszewski** [Milad-Akarie/auto_route_library#908]
What I want to achieve is Staggered Animation of independent page widgets during page transition.
Example of what I want to achieve is shown here https://www.youtube.com/watch?v=C7CAMPdUu8o&t=345s.

In core flutter Navigator there is a PageRouteBuilder that takes two builders as a parameters 
pageBuilder: (context, animation, secondaryAnimation) => childWidget
transitionBuilder: (context, animation, secondaryAnimation, child) => childWidget

Auto Route has only second parameter - transitionBuilder.

First solution presented in this video is to pass animation to child widget returned by pageBuilder function.
I tried to pass animation to child widget with Provider package (Inherited Widget) but it failed.

So I decided to omit child parameter and created page in the builder like so:

Widget provideAnimation(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
  return ListenableProvider(create: (context)=>animation, child: const BookmarksPage(),);
}

But it seems like a hack and not decent solution.

I also was thinking about using Navigation Observers and AutoRouteAware mixin to listen for route changes.
with 
// only override if this is a tab page    
   @override    
   void didChangeTabRoute(TabPageRoute previousRoute) {}  
this function to trigger animations in component itself.

But I need to listen for enter and exit events.

First solution seems leaner.

What do you think?
Which one is better.
Maybe you can think of better solution?

exposing pageBuilder in the api could be another solution.

or maybe it is a way to pass animation to already created widget?

If I find better solution I will let you know.

**Comment by ronba** [comment]
Hi @fmatuszewski - not package author but I was just going over some issues here - and thought I'd reply.

FWIW - you can provide a `PageRouteBuilder` to your CustomRoute in the customRouteBuilder param.

I ran into a similar issue and my solution is what I did in #795 - which uses an inherited widget - I guess that might be similar to your listenable provider?
