### ISSUE TITLE
Looks like you're trying to navigate to a nested route without adding their parent to stack first

### ISSUE THREAD

**Issue by Turbozanik** [Milad-Akarie/auto_route_library#909]
**Error:**
Looks like you're trying to navigate to a nested route without adding their parent to stack first.

**Description:**
I am navigating from `SplashPage `to `HomePage`(HomeRoute) using this line
`Timer(Duration(seconds: 3), () => context.router.push(HomeRoute()));`

And it throws `"Looks like you're trying to navigate to a nested route without adding their parent to stack first"` exception, which makes no sense as I am doing this call from `SplashPage `which is the `HomePages `parent.

Also I am sure that `SplashPage `is in stack, as I have checked it with debuger.
Adding my route file too.

Also, I have seen this issue https://github.com/Milad-Akarie/auto_route_library/issues/861 . And I have tried code from the DOCS, but it is not working. 
And it makes no sense again, how can my page implementation affect the navigation if it is not found and not opened.

Maybe someone knows how can I fix this?

```dart
class SplashPage extends StatefulWidget {
  @override
  _SplashPageState createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  @override
  void initState() {
    super.initState();
    Timer(Duration(seconds: 3), () => context.router.push(HomeRoute()));
  }

  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      backgroundColor: Colors.white,
      body: Image.asset('assets/images/splash_background.png',
          fit: BoxFit.cover, height: double.infinity, width: double.infinity, alignment: Alignment.center),
    );
  }
}

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(path: '/', page: SplashPage, children: [
      AutoRoute(path: 'login', page: LoginPage),
      AutoRoute(path: 'home', page: HomePage, children: [
        AutoRoute(
            path: 'difficulty',
            name: GAME_ROUTER,
            page: EmptyRouterPage,
            children: [AutoRoute(path: '', page: SelectGameDifficultyPage)]),
        AutoRoute(
            path: 'profile', name: PROFILE_ROUTER, page: EmptyRouterPage, children: [AutoRoute(path: '', page: ProfilePage)])
      ]),
      AutoRoute(path: 'game', page: GamePage)
    ])
  ],
)
class $AppRouter {}


```

**Comment by Milad-Akarie** [comment]
@Turbozanik  In order for the above setup to work you'd need an AutoRouter() widget inside of your splash screen

try the following changes: 
```dart
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    // the empty router widget has an AutoRouter widget to render child routes
    AutoRoute(path: '/', page: EmptyRouterWidget, children: [
      AutoRoute(path: '', page: SplashScreen), // auto_route will treat this as initial page since it has an empty path
      AutoRoute(path: 'login', page: LoginPage),
      AutoRoute(path: 'home', page: HomePage, children: [
        AutoRoute(
            path: 'difficulty',
            name: GAME_ROUTER,
            page: EmptyRouterPage,
            children: [AutoRoute(path: '', page: SelectGameDifficultyPage)]),
        AutoRoute(
            path: 'profile', name: PROFILE_ROUTER, page: EmptyRouterPage, children: [AutoRoute(path: '', page: ProfilePage)])
      ]),
      AutoRoute(path: 'game', page: GamePage)
    ])
  ],
)
class $AppRouter {}
```

**Comment by Turbozanik** [comment]
Hi @Milad-Akarie I have tried this, and there are few issues.
1) I wasn't able to find `EmptyRouterWidget`. 
There is no such class in this repo, and you are the only one who have mentioned it https://github.com/Milad-Akarie/auto_route_library/issues/462 . Maybe I need to add more dependencies?
I have used `EmptyRouterPage` instead. 
2) Still having the same error with your setup:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    // the empty router widget has an AutoRouter widget to render child routes
    AutoRoute(path: '/', page: EmptyRouterPage, children: [
      AutoRoute(path: '', page: SplashPage), // auto_route will treat this as initial page since it has an empty path
      AutoRoute(path: 'login', page: LoginPage),
      AutoRoute(path: 'home', page: HomePage, children: [
        AutoRoute(
            path: 'difficulty',
            name: GAME_ROUTER,
            page: EmptyRouterPage,
            children: [AutoRoute(path: '', page: SelectGameDifficultyPage)]),
        AutoRoute(
            path: 'profile', name: PROFILE_ROUTER, page: EmptyRouterPage, children: [AutoRoute(path: '', page: ProfilePage)])
      ]),
      AutoRoute(path: 'game', page: GamePage)
    ])
  ],
)
class $AppRouter {}
```

Also, I am now a bit confused about the library logic.

I will make analogies with native android development, as I am more experienced with it, and it seems like you know how to work with native android too.

From the example I assumed that thils lib works more like fragmentManager, but now it seems like it is closer to native android NavigationComponent.

You need a root container(widget) isnide which all the navigation is made, is this right?

If so, and we are dependent on some auto_route widget.
It would be great, if you could share some "best practice" approach to navigation, as it is becoming really convoluted for me, and I assume for many others too.
We can use my case as an example. It is close enough to any production app.

**Comment by Turbozanik** [comment]
One more addition, maybe it is important. 
I am using AutoRouter in my App. So using it again inside pages seems to be an overkill?

```
class MyApp extends StatelessWidget {
  final _mAppRouter = AppRouter();

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return PlatformProvider(
        settings: PlatformSettingsData(platformStyle: PlatformStyleData(web: PlatformStyle.Cupertino)),
        builder: (context) => PlatformApp.router(
              localizationsDelegates: context.localizationDelegates,
              supportedLocales: context.supportedLocales,
              locale: context.locale,
              routerDelegate: _mAppRouter.delegate(),
              routeInformationParser: _mAppRouter.defaultRouteParser(),
            ));
  }
}
```

**Comment by RageshAntony** [comment]
> @Turbozanik In order for the above setup to work you'd need an AutoRouter() widget inside of your splash screen
> 
> try the following changes:
> 
> ```dart
> @MaterialAutoRouter(
>   replaceInRouteName: 'Page,Route',
>   routes: <AutoRoute>[
>     // the empty router widget has an AutoRouter widget to render child routes
>     AutoRoute(path: '/', page: EmptyRouterWidget, children: [
>       AutoRoute(path: '', page: SplashScreen), // auto_route will treat this as initial page since it has an empty path
>       AutoRoute(path: 'login', page: LoginPage),
>       AutoRoute(path: 'home', page: HomePage, children: [
>         AutoRoute(
>             path: 'difficulty',
>             name: GAME_ROUTER,
>             page: EmptyRouterPage,
>             children: [AutoRoute(path: '', page: SelectGameDifficultyPage)]),
>         AutoRoute(
>             path: 'profile', name: PROFILE_ROUTER, page: EmptyRouterPage, children: [AutoRoute(path: '', page: ProfilePage)])
>       ]),
>       AutoRoute(path: 'game', page: GamePage)
>     ])
>   ],
> )
> class $AppRouter {}
> ```

Works . But how to pass a argument from `EmptyRouterPage` to `SplashScreen` ? @Milad-Akarie

**Comment by Turbozanik** [comment]
@RageshAntony Can you please share, how you made it to work?

**Comment by RageshAntony** [comment]
> @RageshAntony Can you please share, how you made it to work?

I am using AutoTabsScafflold 

I added EmptyRouterPage as the tab instead of the original tab

In routers map , I added the original tab as children of EmptyRouterPage 

The EmptyRouterPage contains only a container with AutoRouter widget

**Comment by Milad-Akarie** [comment]
> @RageshAntony Can you please share, how you made it to work?

You need to make SplashScreen a sibling  to HomeScreen instead of a parent

**Comment by RageshAntony** [comment]
> > @RageshAntony Can you please share, how you made it to work?
> 
> You need to make SplashScreen a sibling to HomeScreen instead of a parent

@Milad-Akarie 
How to pass args  to EmptyRouterPage's  initial children ?

```
 AutoRoute(
            page: EmptyRouterPage,
            children: [
          AutoRoute(page: NotificationsView,initial: true,), // need to pass a Class object here ex:  NotificationsView({ this.cable});
          AutoRoute(page: InfoView),
          AutoRoute(page: NavView),

        ]),
```

**Comment by Milad-Akarie** [comment]
EmptyRouterPage is just a helper widget that builds nothing but an AutoRouter() widget

You can create your own and have it build an AutoRouter() widget that's supposed to render child routes

**Comment by RageshAntony** [comment]
@Milad-Akarie 

will you please provide an example ?

I just need to pass args to NotificationsView via EmptyRouterPage ?

**Comment by Milad-Akarie** [comment]
Class NotificationsRouterPage extends StatelessWidget{
 Final Args args;
// Add args to constructor


 Build(...) => AutoRouter();
}


Then inside an child route you can go

/Accessing parent route data
context.router.routeData.args

Or 
context.routeData.parent

**Comment by RageshAntony** [comment]
@Milad-Akarie 

Ok. How to type cast the args ?

```
     print (context.router.routeData.args.toString());
    Cable cable =  context.router.routeData.args as Cable;
    print( "name ${cable.cableName}");
```

Log:

```
I/flutter (29506): ListHolderRouteArgs{cable: Instance of 'Cable'}

======== Exception caught by widgets library =======================================================

The following _CastError was thrown building NotificationsView(dirty):
type 'ListHolderRouteArgs' is not a subtype of type 'Cable' in type cast
```

**Comment by RageshAntony** [comment]
@Milad-Akarie 

Well. Got it 

`  print((context.routeData.parent?.args as ListHolderRouteArgs).cable.cableName); .. working`

@Milad-Akarie 

Thanks . But one question.

How to access the parent route data without Context , that is , we only able  to get the Args inside build(context) method 

But need them in initstate only . You know why !

is it possible  ?

**Comment by Milad-Akarie** [comment]
You can get them in initState method using context no problem

**Comment by RageshAntony** [comment]
> You can get them in initState method using context no problem

initState don't have context param in its method . Then how?

I tried get_it method in the Docs

```
void main() async {
 
  getIt.registerSingleton<FlutterRouter>(FlutterRouter());

  runApp(const ProviderScope(child: MyApp()));
}

class _MyAppState extends State<MyApp> {
  late FlutterRouter _flutterRoute;



  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(



      routeInformationParser: _flutterRoute.defaultRouteParser(),
      routerDelegate: AutoRouterDelegate(_flutterRoute),
      builder: (context, router) => router!,
    );
  }

  @override
  void initState() {
     _flutterRoute = getIt<FlutterRouter>();

  }
}
```

print((getIt<FlutterRouter>().routeData.parent?.args as ListHolderRouteArgs).cable.cableName);

But , getting error :

type 'Null' is not a subtype of type 'ListHolderRouteArgs' in type cast

Why routeArgs null when accessed through get_it ?


Please provide an example to get directly ? @Milad-Akarie

**Comment by Milad-Akarie** [comment]
getit< FlutterRouter>() will get you the root router, you don't want to access the root router you want a nested router.

every-time you add an AutoRouter() to your widgets tree you're adding a nested router. 

I believe you can could just access the parent route args by calling 
`context.router.routeData.args;`
iniside of initState method.

**Comment by RageshAntony** [comment]
> `context.router.routeData.args;`
@Milad-Akarie 
Okay. You referred that global variable context , not   Widget build(BuildContext context) 

Yeah . it's working 
```
  @override
  void initState() {
    cable = (context.routeData.parent?.args as ListHolderRouteArgs).cable;
    print((context.routeData.parent?.args as ListHolderRouteArgs).cable.cableName);
  }
```
Thanks .

But I heard using global context variable is not good practice . What about that ?

**Comment by Milad-Akarie** [comment]
@RageshAntony true, using global context is not a good practice, but a context of a StatefulWidget is not global it's the context of the tree element at that node.

**Comment by RageshAntony** [comment]
> @RageshAntony true, using global context is not a good practice, but a context of a StatefulWidget is not global it's the context of the tree element at that node.

Thanks. 

Also please update these things in main documentation so it's useful for beginners . I spent nearly 8 hours in fixing this routing problem alone

**Comment by IdemenB** [comment]
Hi everyone, my issue is also related with this. I have a home page with 3 tabs and in all tabs there is a bottom navigation bar. This is done through a wrapper page tab pages are children to the wrapper. This wrapper provides the shared appbar and the bottom navigation bar for all tabs.

However, I don't want a direct switch to the Tab 3 made by  AutoTabsScaffold. Instead,  in whatever page currently I am (Page 1 or Page 2), I first want to show to modal bottom sheet with 2 options in it, and only after that navigate to the selection.

With the settings below I've managed to show the bottom sheet and then switch to the Option1 or Option2 pages using EmptyRouterPage. However, this is just a blank white page and AutoTabScaffold switches to that blank white page view and only after that I can navigate to options. 

Already Tried 1) I tried to show the modal sheet in the current page and prevented AutoTabScaffold from making the switch to the empty page. However, this results in the "Looks like you're trying to navigate to a nested route without adding their parent to stack first" error.

Already Tried 2) I wanted to customize EmptyRouterRoute by making it a full page transparent container using the builder parameter of AutoRouter(), thinking that when it is added on top of the stack, the transparency would show the last item before that anyway. However this is not happening either.


Any help would be highly appreciated.

```
const afterLoginHomeRouter = AutoRoute(
  // name: 'AfterLoginHomeRouter',
  page: AfterLoginHomeWrapperPage,
  children: [
    AutoRoute(
      page: AfterLoginPage1,
    ),
    AutoRoute(
      page: AfterLoginPage2,
    ),
   bottomSheetRouter,

  ],
);


const bottomSheetRouter = AutoRoute(
 
  page: EmptyRouterPage,
  children: [
    AutoRoute(
      page: BottomSheetPageOption1,
      initial: true,
    ),
    AutoRoute(
      page: BottomSheetPageOption2,
    ),
  ],
);


 routes: [
        AfterLoginRoute1( ),
         AfterLoginRoute2,   
        const EmptyRouterRoute(),

      ],

```






  and when we click on some of the items in the navigation, a bottom sheet appears (using the modal_bottom_sheet package)

I've managed to

**Comment by Turbozanik** [comment]
@Milad-Akarie Hi again! it seems like I had some sort of a tunnel vision at the beginning.
Finnaly I was able to make everything work. 

And I am stuck again with one more question.

I have the following router. And I would like to pass arguments to the `SelectGameDifficultyPage`. How can I do that?
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    // the empty router widget has an AutoRouter widget to render child routes
    AutoRoute(path: '/', page: EmptyRouterWidget, children: [
      AutoRoute(path: '', page: SplashPage), // auto_route will treat this as initial page since it has an empty path
      AutoRoute(path: 'login', page: LoginPage),
      AutoRoute(path: 'home', page: HomeAutoRoutePage, children: [
        AutoRoute(
          path: 'difficulty',
          name: GAME_ROUTER,
          page: EmptyRouterPage,
          children: [
            AutoRoute(path: '', page: SelectGameDifficultyPage),
            AutoRoute(path: 'topic', page: GameTopicPage),
            AutoRoute(path: 'question_set', page: QuestionSetPage)
          ],
        ),
        AutoRoute(
          path: 'profile',
          name: PROFILE_ROUTER,
          page: EmptyRouterPage,
          children: [AutoRoute(path: '', page: ProfilePage)],
        )
      ]),
      AutoRoute(path: 'game', page: GamePage)
    ])
  ],
)
class $AppRouter {}

class EmptyRouterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AutoRouter();
  }
}
```

I was trying to solve it like this, but it seems not to be the right way.

```
    return PlatformProvider(
      settings: PlatformSettingsData(platformStyle: PlatformStyleData(web: PlatformStyle.Cupertino)),
      builder: (context) => PlatformApp.router(
        material: (_, __) => MaterialAppRouterData(theme: lightTheme),
        routerDelegate: _mAppRouter.delegate(initialRoutes: [
          SelectGameDifficultyRoute(
              bloc: DiContainer.instance.getOrCreateSelectDifficultyInjector().get<SelectDifficultyPageBloc>())
        ]),
        routeInformationParser: _mAppRouter.defaultRouteParser(),
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
      ),
    );
```

**Comment by lodisy** [comment]
I am not sure if I understood correctly from the doc.

So nested router only works with different parts of the same page?

Got the same error with the following config when router from `UsersPage` to `UserDetailPage`:
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: AuthPage,
      initial: true,
    ),
    AutoRoute(
      page: UsersPage,
      path: '/users',
      children:[
          AutoRoute(
              page: UserDetailPage,
              path: ':id',
          )
      ]
    ),
  ],
)
class $AppRouter {}
```

it's resolved with the following:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
      path: '/',
      page: AuthPage,
      initial: true,
    ),
    AutoRoute(
      page: UsersPage,
      path: '/users',
    ),
    AutoRoute(
      page: UserDetailPage,
      path: '/users/:id',
    )
  ],
)
class $AppRouter {}
```

**Comment by nokia6290** [comment]
why was this closed? its a broken feature
