### ISSUE TITLE
Error running AutoRouteGenerator : The getter 'source' was called on null.

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#91]
Getting the following error when I run the build_runner :

`flutter packages pub run build_runner build --delete-conflicting-outputs`

```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/router/my_bus_router.dart:
Error running AutoRouteGenerator
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
[INFO] Running build completed, took 39.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 62ms

[SEVERE] Failed after 39.8s
pub finished with exit code 1
```

### my_bus_router.dart :
```
@MaterialAutoRouter(routesClassName: 'BusRoute' , generateRouteList: true)
class $MyBusRouter{
  BusBoardingDropScreen boardingDropPointSelection;
  BusFilterScreen busFilterScreen ;
}
```

## Flutter Doctor : 

Flutter 1.17.0-3.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (13 hours ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

Running flutter doctor...
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.2 19C57, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (4 available)
```

### auto route version i am using :
  auto_route: ^0.4.5
  auto_route_generator: ^0.4.8

**Comment by Milad-Akarie** [comment]
@nateshmbhat What kinda parameters are you passing to your routes? typeDefs aren't supported!

**Comment by nateshmbhat** [comment]
Ohh I might have missed it in the api docs. Is this documented ?

**Comment by nateshmbhat** [comment]
Actually I don't have any typedefs in my screens : 

There are my screens : 
What am I missing here ? 🤔 

```
class BusBoardingDropScreen extends StatefulWidget {
  final Int64 tripId;
  final PaginationRequest paginationRequest;
  final void Function(LocationItem) onSelected;

  const BusBoardingDropScreen(
      {Key key, @required this.tripId, this.paginationRequest, @required this.onSelected})
      : super(key: key);


  @override
  _BusBoardingDropScreenState createState() => _BusBoardingDropScreenState();
}
```



```
class BusFilterScreen extends StatefulWidget {
  final Int64 tripId;
  final FilterScreenManager<BusSortFilterResponse> filterScreenManager;

  const BusFilterScreen(
      {Key key, @required this.tripId, @required this.filterScreenManager})
      : super(key: key);

  @override
  _BusFilterScreenState createState() => _BusFilterScreenState();
}
```

**Comment by nateshmbhat** [comment]
As mentioned in the #35 , there are many many use cases for sending a callback function to a Screen.

For example : 

I can have multiple callback functions sent to my screens : 
say onSubmitForm  and onFormError and formValidator function

that uses the data in the previous screen inside those callbacks. Also we might have business logic inside the Screens that wraps or uses these callbacks as and when needed.

This is a very crucial feature that we need in 'auto_route' to make it a "must have" library for routin.

**Comment by nateshmbhat** [comment]
But this issue may be something else since it doesn't even finish the "build" process and gives that `source was called on null` issue.

**Comment by nateshmbhat** [comment]
is this issue something that you will be looking into in the near future ? 
this is an awesome package , one that we want to use in our company but this issue is a blocker for us :/

**Comment by Milad-Akarie** [comment]
@nateshmbhat It's not that I don't want to support it, for some reason I can't obtain the source it there for I can't generate the required import statement. 

but If you're using just Function() it should work fine..I may have messed with something in the previous updates.
