### ISSUE TITLE
How to listen to path param change?

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#911]
Hey,
I encountered an issue when navigating (not pushing) to a path while it is the active route with different arguments, in this case a different path param, it doesn't update the page with the new information.

How can I listen to changes in the arguments, so I could change the page based on the new data?

Thanks

**Comment by nikolaihen** [comment]
Make sure the page is a ``StatefulWidget`` and add a listener to the router inside ``initState`` and do the check there, like so:

```dart
String _search;

void _didSearchChange() {
  final params = AutoRouter.of(context).current.pathParams;

  // e.g. the param "search" changed
  final search = params.getString('search');

  // Do nothing if the search haven't changed
  if (search == _search) return;

  setState(() => _search = search); // Rebuild with new search
}

@override
void initState() {
  super.initState();

  AutoRouter.of(context).addListener(_didSearchChange);
}

@override
void dispose() {
  AutoRouter.of(context).removeListener(_didSearchChange);
  super.dispose();
}
```

Remember to remove the listener on ``dispose()``

**Comment by naamapps** [comment]
Thanks @nikolaihen,
This works, but with some caveats.
If the route exists more than once in the stack, they all will listen and react to path param changes.
I would like that only the top (visible) route would react to changes.

It would be great if you have an example for this scenario too.  

Anyways, thanks for your help :)

**Comment by naamapps** [comment]
Got it working,
All you have to do is to make your widget stateful, override `didUpdateWidget` and check if the values are different:
```
  @override
  void didUpdateWidget(TestView oldWidget) {
    if (oldWidget.id != widget.id) {
      reload();
    }
    super.didUpdateWidget(oldWidget);
  }
```
