### ISSUE TITLE
A navigation example for Wrapping Routes

### ISSUE THREAD

**Issue by AlastorReach** [Milad-Akarie/auto_route_library#916]
Hi!. Let me say you have done a great job! This package is awesome. I really appreciate it.

I have been reading the documentation about Wrapping Routes, but I do not understand how can we navigate to a Wrapped screen. In docs there is the following code:

NavLink(label: 'Users', destination: const UsersRoute()),

But NavLink seems not to be an existing class.

Please add a section about navigating with these kind of Wrapped screens.

**Comment by NaoyaRuike** [comment]
Hello, I got the same problem and figured out the latest release 2.1.0 does not contain NavLink.
Maybe NavLink exists on the latest master branch.

I found the document for v2.1.0 below and it worked.
https://github.com/Milad-Akarie/auto_route_library/tree/v2.1.0#nested-routes

Thanks for this nice package, I also appreciate it!
