### ISSUE TITLE
stackRouterOfIndex is still null after setActiveIndex

### ISSUE THREAD

**Issue by YDA93** [Milad-Akarie/auto_route_library#922]
I did:
`context.tabsRouter.setActiveIndex(3);`

Now when I try: 
`final result = context.tabsRouter.stackRouterOfIndex(3);`

The result is null, unless I:

```
await Future.delayed(const Duration(milliseconds: 500));
final result = = context.tabsRouter.stackRouterOfIndex(3);
```

Which is understandable but some mobiles might take longer to build the stackRouter.

How can I determine when the stack is built? without setting AutoTabsScaffold lazyLoad to false.

Maybe something like
`await context.tabsRouter.setActiveIndex(3);`

Thanks and appreciated!

**Comment by nzkn** [comment]
I experience the same issue. Need to add at least 5 ms delay to navigate inside tabs after initially switching to a tab

**Comment by YDA93** [comment]
> I experience the same issue. Need to add at least 5 ms delay to navigate inside tabs after initially switching to a tab

You can't predict how much milliseconds exactly.

If the device has poor performance or the RAM is at max this might take more than 5 ms.

**Comment by Milad-Akarie** [comment]
@nzkn  @YDA93 You just need to navigate inside the  stack of target tab?

**Comment by Milad-Akarie** [comment]
The StackRouter is initialized with the host widget.

**Comment by YDA93** [comment]
> @nzkn  @YDA93 You just need to navigate inside the  stack of target tab?

In my trying to:

switch tab > obtain its stack router > navigate.

The problem when the stack router is still null even after we activated its tab.
