### ISSUE TITLE
UI don't re-render when using flutter_screen_util

### ISSUE THREAD

**Issue by Hoang-Nguyenn** [Milad-Akarie/auto_route_library#923]
Hi teams, i've a problem when using with flutter screen_util to responsive in web when we drag to scale up and down but seem UI on screen don't rebuild when screenUtil already rebuild, have tried add maintainState = false on route but seem can't work. When refresh it'll get new responsive information.

**Comment by Hoang-Nguyenn** [comment]
as i see it's still called didUpdateWidget and build in class _AutoRouteNavigatorState but don't re-render UI on each screen

**Comment by Tokenizer94** [comment]
flutter_screenutil package init function is not working with this package.

**Comment by Tokenizer94** [comment]
Any update?
