### ISSUE TITLE
Exception caught by Gesture: Unexpected null value

### ISSUE THREAD

**Issue by Wizzel1** [Milad-Akarie/auto_route_library#926]
So I have this AppRouter: 
```dart
@CustomAutoRouter(
  customRouteBuilder: myCustomRouteBuilder,
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      path: '/',
      name: 'AuthRoute',
      page: EmptyRouterPage,
      children: [
        RedirectRoute(path: '', redirectTo: 'login'),
        AutoRoute(path: 'login', page: LoginPage),
        AutoRoute(path: 'signup', page: SignupPage),
      ],
    ),
    AutoRoute(
      path: '/',
      page: ResponsiveLayoutPage,
      guards: [AuthGuard],
      children: [
        RedirectRoute(path: '', redirectTo: 'dashboard'),
        AutoRoute(
          path: 'dashboard',
          page: DashboardPage,
          guards: [AuthGuard],
        ),
        AutoRoute(
          path: 'analytics',
          page: AnalyticsPage,
          guards: [AuthGuard],
          children: [
            RedirectRoute(path: '', redirectTo: 'overview'),
            AutoRoute(
              path: 'overview',
              page: AnalyticsOverviewPage,
              guards: [AuthGuard],
            ),
            AutoRoute(
              path: 'details',
              page: DesignDetailsPage,
              guards: [AuthGuard],
            ),
          ],
        ),
      ],
    ),
  ],
)

// extend the generated private router
class AppRouter extends _$AppRouter {
  final AuthGuard guard;
  AppRouter({required this.guard}) : super(authGuard: guard);
}

```
and this is my authguard: 

```dart
class AuthGuard extends AutoRedirectGuard {
  final ProviderRef ref;

  AuthGuard(this.ref) {
    ref.listen(userStreamProvider, (_, __) => reevaluate());
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    ref.read(userStreamProvider).whenOrNull(
      data: (user) {
        if (user != null) {
          resolver.next();
        } else {
          redirect(
            const AuthRoute(children: [LoginRoute()]),
            resolver: resolver,
          );
        }
      },
    );
  }
}
```
My loginButton on ```LoginPage``` calls  ``` context.replaceRoute(const ResponsiveLayoutRoute())```

After that, when I am trying to navigate between DashboardPage and AnalyticsPage with 
```context.replaceRoute(const AnalyticsRoute()); ```
```context.replaceRoute(const DashboardRoute()); ```

I am getting an 
```
════════ Exception caught by gesture ═══════════════════════════════════════════
Unexpected null value.
════════════════════════════════════════════════════════════════════════════════
``` 

on the first click. If I run the navigation again, it works. So I have to press my navigationbutton twice in order to navigate. What am I doing wrong?

**Comment by k-ahmednagy** [comment]
> So I have this AppRouter:
> 
> ```dart
> @CustomAutoRouter(
>   customRouteBuilder: myCustomRouteBuilder,
>   replaceInRouteName: 'Page,Route',
>   routes: [
>     AutoRoute(
>       path: '/',
>       name: 'AuthRoute',
>       page: EmptyRouterPage,
>       children: [
>         RedirectRoute(path: '', redirectTo: 'login'),
>         AutoRoute(path: 'login', page: LoginPage),
>         AutoRoute(path: 'signup', page: SignupPage),
>       ],
>     ),
>     AutoRoute(
>       path: '/',
>       page: ResponsiveLayoutPage,
>       guards: [AuthGuard],
>       children: [
>         RedirectRoute(path: '', redirectTo: 'dashboard'),
>         AutoRoute(
>           path: 'dashboard',
>           page: DashboardPage,
>           guards: [AuthGuard],
>         ),
>         AutoRoute(
>           path: 'analytics',
>           page: AnalyticsPage,
>           guards: [AuthGuard],
>           children: [
>             RedirectRoute(path: '', redirectTo: 'overview'),
>             AutoRoute(
>               path: 'overview',
>               page: AnalyticsOverviewPage,
>               guards: [AuthGuard],
>             ),
>             AutoRoute(
>               path: 'details',
>               page: DesignDetailsPage,
>               guards: [AuthGuard],
>             ),
>           ],
>         ),
>       ],
>     ),
>   ],
> )
> 
> // extend the generated private router
> class AppRouter extends _$AppRouter {
>   final AuthGuard guard;
>   AppRouter({required this.guard}) : super(authGuard: guard);
> }
> ```
> 
> and this is my authguard:
> 
> ```dart
> class AuthGuard extends AutoRedirectGuard {
>   final ProviderRef ref;
> 
>   AuthGuard(this.ref) {
>     ref.listen(userStreamProvider, (_, __) => reevaluate());
>   }
> 
>   @override
>   void onNavigation(NavigationResolver resolver, StackRouter router) {
>     ref.read(userStreamProvider).whenOrNull(
>       data: (user) {
>         if (user != null) {
>           resolver.next();
>         } else {
>           redirect(
>             const AuthRoute(children: [LoginRoute()]),
>             resolver: resolver,
>           );
>         }
>       },
>     );
>   }
> }
> ```
> 
> My loginButton on `LoginPage` calls ` context.replaceRoute(const ResponsiveLayoutRoute())`
> 
> After that, when I am trying to navigate between DashboardPage and AnalyticsPage with `context.replaceRoute(const AnalyticsRoute()); ` `context.replaceRoute(const DashboardRoute()); `
> 
> I am getting an
> 
> ```
> ════════ Exception caught by gesture ═══════════════════════════════════════════
> Unexpected null value.
> ════════════════════════════════════════════════════════════════════════════════
> ```
> 
> on the first click. If I run the navigation again, it works. So I have to press my navigationbutton twice in order to navigate. What am I doing wrong?

same issue here , did you fix this issue or found where is it ?

**Comment by Wizzel1** [comment]
Hi, sorry for the late reply. 

I am currently using this as authGuard, seems to work for now. 

```dart

import 'package:auto_route/auto_route.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:podsuite/repositories/auth_repository.dart';
import 'package:podsuite/router/app_router.dart';

class AuthGuard extends AutoRedirectGuard {
  final ProviderRef ref;

  AuthGuard(this.ref) {
    ref.read(authRepositoryProvider).authStateChanges.listen((event) {
      reevaluate();
    });
  }

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final user = ref.read(authRepositoryProvider).getCurrentUser();

    if (user != null) {
      resolver.next();
    } else {
      redirect(const AuthRoute(children: [LoginRoute()]), resolver: resolver);
    }
  }
}
```

**Comment by k-ahmednagy** [comment]
> Hi, sorry for the late reply. @k-ahmednagy
> 
> I am currently using this as authGuard, seems to work for now.
> 
> ```dart
> import 'package:auto_route/auto_route.dart';
> import 'package:hooks_riverpod/hooks_riverpod.dart';
> import 'package:podsuite/repositories/auth_repository.dart';
> import 'package:podsuite/router/app_router.dart';
> 
> class AuthGuard extends AutoRedirectGuard {
>   final ProviderRef ref;
> 
>   AuthGuard(this.ref) {
>     ref.read(authRepositoryProvider).authStateChanges.listen((event) {
>       reevaluate();
>     });
>   }
> 
>   @override
>   void onNavigation(NavigationResolver resolver, StackRouter router) {
>     final user = ref.read(authRepositoryProvider).getCurrentUser();
> 
>     if (user != null) {
>       resolver.next();
>     } else {
>       redirect(const AuthRoute(children: [LoginRoute()]), resolver: resolver);
>     }
>   }
> }
> ```

thanks
