### ISSUE TITLE
Deeplink navigation replacing entire stack

### ISSUE THREAD

**Issue by coccyx-cyst** [Milad-Akarie/auto_route_library#929]
Hello.

I have Scaffold Drawer global navigation with every menu item's own nested navigation stack.
So when I try to navigateNamed/pushNamed previous stack isn't replacing by a new from deeplink, however, it pushes a second stack,
so if I go back with Android back button (for example), it navigates me to the previous stack.

Is it possible to just replace entire stack of app with deeplink? @Milad-Akarie 

replaceNamed method doesn't work for some reasons.

`@CustomAutoRouter(
  transitionsBuilder: TransitionsBuilders.fadeIn,
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(
        //guards: [AuthGuard],
        page: HomePage,
        initial: true,
        path: '/',
        children: [
          ///Notifications
          AutoRoute(
              initial: true,
              page: NotificationsRootPage,
              path: 'notifications',
              children: [
                AutoRoute(page: NotificationsPage, path: '', initial: true),
                AutoRoute(page: NotificationDetailPage, path: ':id'),
                ///Homeworks
          AutoRoute(page: HomeworksRootPage, path: 'homeworks', children: [
            AutoRoute(page: HomeworksPage, path: ''),
            AutoRoute<bool>(page: HomeworkDetailPage, path: 'detail'),
            AutoRoute<bool>(
                page: HomeworkPerfomanceMonitoringPage,
                path: 'perfomance-monitoring'),
            AutoRoute<String>(
                page: HomeworkChangeDescPage, path: 'change-description'),
            AutoRoute<bool>(page: HomeworkCopyPage, path: 'copy'),
            AutoRoute<bool>(page: HomeworkFilesPage, path: 'files'),
            AutoRoute<bool>(page: HomeworkCreateEditPage, path: 'create'),
          ]),
        ]),`
  
  Here is a part of my routes, so I am trying to Navigate from nested HomeworkFilesPage to deeplinked route
  
  `await getIt<AppRouter>()
        .root
        .navigateNamed('/notifications/${data.id}', includePrefixMatches: true);`

**Comment by coccyx-cyst** [comment]
I figured out that I got redundant HomeRoute that was preventing the normal work of raplaceNamed.

But now I am facing the two problems.

1. I am presenting back IconButton depending on AutoRouter.of(context).canPopSelfOrChildren, so when I am using replaceNamed('/notifications/${data.id}', includePrefixMatches: false); there's no back button on Scaffold AppBar, that is correct, but if replaceeNamed('/notifications/${data.id}', includePrefixMatches: true) I am getting the stack of two pages (what's I am expecting), and after I am popping NotificationDetailPage there must be no back button, but it is.
AutoRouter.of(context).canPopSelfOrChildren is returning true in this case.

2. If I am currently at NotificationsRoute, and I am trying to replaceeNamed('/notifications/${data.id}', includePrefixMatches: true), nothing happens. Expecting that it will push NotificationDetailPage.

**Comment by wackazong** [comment]
i have the same question: how to delete the current navigation stack when coming into the app from a deep link?

**Comment by coccyx-cyst** [comment]
@wackazong I got a feeling that there must me some parameter for path navigation methods (or another deep-link special methods) which will give the opportunity for replacing entire stack or pushing new.

Also, in my case here is a problem:
If my path is already '/notifications/63636' and i want to deep-link into 'notifications/272727' (to another id), nothing happens.

**Comment by bharath-doshi** [comment]
> @wackazong I got a feeling that there must me some parameter for path navigation methods (or another deep-link special methods) which will give the opportunity for replacing entire stack or pushing new.
> 
> Also, in my case here is a problem: If my path is already '/notifications/63636' and i want to deep-link into 'notifications/272727' (to another id), nothing happens.

Hey I'm still facing the same issue. Did you find a way to fix it?
