### ISSUE TITLE
custom transitionBuilder Secondary Animation value is always 0

### ISSUE THREAD

**Issue by BabkenM** [Milad-Akarie/auto_route_library#932]
Starting from auto_route version 3.2.1 the custom transitionBuilder secondaryAnimation value is always 0.
I tried to downgrade the lib and stoped on 3.2.0 for both auto_route and auto_route_generator, on this version secondaryAnimation works as expected but, I don't know why, when I'm trying to do the same thing with Navigator, like
                            
 ```
                    Navigator.push(
                      context,
                      PageRouteBuilder(
                        pageBuilder: (context, animation, secondaryAnimation) {
                          return const PersonalInfoScreen();
                        },
                        transitionsBuilder:
                            (context, animation, secondaryAnimation, child) {
                          return SlideTransition(
                                     position: Tween<Offset>(
                                       begin: const Offset(0.0, 1.0),
                                       end: Offset.zero,
                                     ).animate(animation),
                                     child: SlideTransition(
                                       position: Tween<Offset>(
                                         begin: Offset.zero,
                                         end: const Offset(0.0, 1.0),
                                       ).animate(secondaryAnimation),
                                       child: child,
                                     ),
                              );
                        },
                      ),
                    );
```

it does not work and same vice versa, if I'm trying to push route with Navigator on versions 3.2.2 auto_route and 3.2.1 auto_route_generator , it works

`flutter doctor -v`

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale ru-RU)
    • Flutter version 2.8.1 at A:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at A:\sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = A:\Sdk
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (1 available)
    • SM A730F (mobile) • 52007d66ee1f55e5 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by alexgarbarev** [comment]
Hi @BabkenM, I faced with exactly same issue. 
The only workaround I found so far is to use custom `customRouteBuilder`

```dart
CustomRoute(
  page: LoginPage,
  path: '/login',
  customRouteBuilder: slideUpAndDown,
)
```

```dart
  Route<T> slideUpAndDown<T>(
    BuildContext context,
    Widget child,
    CustomPage<T> page,
  ) {
    return PageRouteBuilder(
      settings: page,
      pageBuilder: (context, animation, animation2) {
        final curveTween = CurveTween(curve: Curves.easeInOut);
        return SlideTransition(
          position:
              Tween(begin: const Offset(0.0, 1.0), end: Offset.zero).animate(
            CurvedAnimation(parent: animation, curve: curveTween.curve),
          ),
          child: SlideTransition(
            position:
                Tween(begin: Offset.zero, end: const Offset(0.0, 1.0)).animate(
              CurvedAnimation(
                parent: animation2,
                curve: curveTween.curve,
              ),
            ),
            child: page.buildPage(context),
          ),
        );
      },
    );
  }
```

**Comment by NextBabken** [comment]
Sorry for late answer.
Just want to say that now I'm using `auto_route: 5.0.1` version and the same version for `auto_route_generator` but I believe the previous versions, after buged version that I opened this issue, also had no problem with secondaryAnimation, so for now I can say that everything is working fine.

**Comment by BabkenM** [comment]
Sorry for late answer.
Just want to say that now I'm using auto_route: 5.0.1 version and the same version for auto_route_generator but I believe the previous versions, after buged version that I opened this issue, also had no problem with secondaryAnimation, so for now I can say that everything is working fine.
