### ISSUE TITLE
Get Page name from Route

### ISSUE THREAD

**Issue by prijupaul** [Milad-Akarie/auto_route_library#933]
Hi,

I'm trying to log the page names on every `didPush`.  I have implemented a callback listener using `AutoRouterObserver`. This works fine, I'm not able to get the page name from the Route. 
```
class MyObserver extends AutoRouterObserver {    
  @override    
  void didPush(Route route, Route? previousRoute) {   
     
    print('New route pushed name: ${route.settings.name}');    
    print('New route pushed arguments: ${route.settings.arguments}');    
    print('New route pushed toString: ${route.toString()}');    
    print('New route pushed arguments currentResult: ${route.currentResult}');    
    print('Tab route re-visited: ${route.currentResult}');    
  } 
}
```

How do we get the page name from the route?

**Comment by yoodame** [comment]
I would like to know the very same thing as well. Hoping to use the observer to track analytics.

**Comment by yoodame** [comment]
@prijupaul or anyone interested - here's what I have been able to figure out to obtain the path. Hopefully, it helps out. The route name can be obtained with `route.settings.name`. 

```
@override
  void didPush(Route route, Route? previousRoute) {
    final context = route.navigator!.context;
    print(AutoRouter.of(context)
        .navigationHistory
        .urlState
        .path);
  }
```

**Comment by niwaguan** [comment]
try `(route.settings as MaterialPageX).routeData`
