### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rd-martin-jaeger** [Milad-Akarie/auto_route_library#936]
We started to develop a web and mobile app with a lot of screens, nested navigations, auth with a declarative router, bottom navigation, tabs etc - so the full package.

auto_route really helped to get started very fast and to avoid writing a lot of boilerplate code for flutter navigation 2.0, but the more complex the app becomes, the more complex the work with auto route becomes. I stumbled upon some issues, like double drawn routers in some cases or difficulties to nest nested routers. Searching for solutions i checked the readme, the documentation and the sample to help myself. In some cases it worked - although you have to search for all information with some effort - in some cases i ended here - in the issue tracker. 

I found some issues which also concerns me - but most unanswered and unsolved. 
I checked the PRs and recognized there are still some open and unhandled since august last year.
I checked the insights and recognized not much contribution within the last months or even years.

Don't get me wrong - you really created a gem here and i really would love to see this approach as the frameworks build-in navigation 3.0 - however, doubts arise as to whether this lib is still a good fit for our application or not. Nothing would be more dangerous for us, than using a core library which has long since ceased to be maintained.

Best and thank you

**Comment by ntfnd404** [comment]
The library is poorly documented...I'm already looking in the direction of go_route

**Comment by rd-martin-jaeger** [comment]
@ntfnd404 Already some experiences with go_route?

**Comment by StanevPrime** [comment]
I checked it out.
In general looks promising, but from what I'v seen it is way basic comparing to: https://autoroute.vercel.app/advanced/declarative_routing

**Comment by svenjacobs** [comment]
It seems like comments have been deleted from this thread, possibly referring to other routing libraries? @StanevPrime answer now doesn't make any sense without prior posts. @rd-martin-jaeger concerns are valid, so let's please keep this a fair and open discussion.
