### ISSUE TITLE
"The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'isNavigation' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.   void routerReportsNewRouteInformation(RouteInformation routeInformation, "  after upgrading to auto router version 3.2.2

### ISSUE THREAD

**Issue by Dagmawi-Asfaw-CH** [Milad-Akarie/auto_route_library#943]
this is the error i am getting. 

../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: Type 'RouteInformationReportingType' not found.
      {required RouteInformationReportingType type}) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart:29:8: Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'isNavigation' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
  void routerReportsNewRouteInformation(RouteInformation routeInformation,
       ^
/C:/src/flutter/packages/flutter/lib/src/widgets/router.dart:1340:8: Context: This is the overridden method ('routerReportsNewRouteInformation').
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {bool isNavigation = true}) {}
       ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/controller/auto_router_delegate.dart:30:17: Error: Getter not found: 'RouteInformationReportingType'.
          type: RouteInformationReportingType.navigate,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/controller/auto_router_delegate.dart:30:11: Error: No named parameter with the name 'type'.
          type: RouteInformationReportingType.navigate,
          ^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart:30:17: Error: 'RouteInformationReportingType' isn't a type.
      {required RouteInformationReportingType type}) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart:31:27: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
 - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
    var replace = type == RouteInformationReportingType.neglect ||
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart:32:18: Error: The getter 'RouteInformationReportingType' isn't defined for the class 'AutoRouteInformationProvider'.
 - 'AutoRouteInformationProvider' is from 'package:auto_route/src/router/provider/auto_route_information_provider.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/auto_route-3.2.2/lib/src/router/provider/auto_route_information_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'RouteInformationReportingType'.
        (type == RouteInformationReportingType.none &&
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by sammrafi** [comment]
@Dagmawi-Asfaw-CH  I fixed this issue by this......

I remove the **required** from the function and set **none**. Here is the example

![Screenshot 2022-02-04 215354](https://user-images.githubusercontent.com/31324166/152561008-b37352ba-b780-4db1-9e73-e8dac0ba0b3f.png)

**Comment by BelfDev** [comment]
@Dagmawi-Asfaw-CH and @sammrafi just update your Flutter SDK version to >=2.8.0

Tips:
- Clean the cache with `flutter cache clean`
- If you choose to update Flutter to the latest version (2.10.0), set the project env SDK version to `sdk: ">=2.16.0 <3.0.0"`

**Comment by Saiprasad122** [comment]
@sammrafi  i updated the code like you said but still facing the issue 
Anybody had faced the issue and solved it?
