### ISSUE TITLE
Is there a way to not maintain state on one of the nav tabs  (AutoTabsRouter)?

### ISSUE THREAD

**Issue by devyev** [Milad-Akarie/auto_route_library#948]
Hi, we are using AutoTabsScaffold and would like to refresh state when clicking on one of the navigation tabs. We tried setting maintainState: false on the nav tab route, without success? Is there a better approach?

**Comment by Milad-Akarie** [comment]
@devyev you can simply listen for tabs changing inside of initState method

final tabsRouter = context.tabsRouter;
tabsRouter.liaten((){
If(tabsRouter.activeIndex == ThisTabIndex){

  resetState();
}

});

**Comment by devyev** [comment]
Perfect, thank you!
