### ISSUE TITLE
Push Child Route without its Parent 

### ISSUE THREAD

**Issue by markbulingit** [Milad-Akarie/auto_route_library#949]
Is it possible to push a child route without its parent? e.g On E-commerce Home Page the user will click on a Featured Product and will be pushed to Product details, when the user clicks the back button they should be redirected on home page not on Product List Page

Home Page
      - Product List
             - Product Details
             
I want to bypass product list page.

**Comment by Milad-Akarie** [comment]
@markbulingit  how are your routes setup?
