### ISSUE TITLE
Issues with wrapping Widgets with BlocProvider using AutoRouteWrapper

### ISSUE THREAD

**Issue by rahulnakre** [Milad-Akarie/auto_route_library#95]
I wanted to use flutter_bloc (4.0.0) with auto_route (0.4.5), and to wrap it, I had done this

![image](https://user-images.githubusercontent.com/28615350/81215415-506f4000-8fa7-11ea-8b38-306727294071.png)

However, I'd run into this issue:
![image](https://user-images.githubusercontent.com/28615350/81215536-814f7500-8fa7-11ea-8d2b-fb390d62b8ea.png)

I did a hacky fix to combat that issue, which was modifying the auto generated file directly: 
![image](https://user-images.githubusercontent.com/28615350/81215667-a80dab80-8fa7-11ea-9384-1b1bc4ef011c.png)
I basically wrapped the widget manually myself, and I was wondering if I was doing something wrong in how I used wrappedRoute()? Or if there was an issue with wrapping itself.

Thanks in advance

**Comment by rafaelmpessoa** [comment]
@rahulnakre maybe you are doing a wrong call. 

Your wrapping Router is in your SearchPage? should be.


```
class SeachPage extends StatelessWidget with AutoRouteWrapper {

@override
  Widget wrappedRoute(BuildContext context) {
    return BlocProvider(

   create: (_) => AuthBloc(),
   child: this
 

   );
    }
}
```

**Comment by rahulnakre** [comment]
Ah, I simply did my @override in my SearchState, rather than the StatefulWidget, thanks for the help!
