### ISSUE TITLE
How can i add Adguard to Nested Bottom Navigation Tab?

### ISSUE THREAD

**Issue by ybaser** [Milad-Akarie/auto_route_library#952]
Hi to all, Thanks for that wonderfull library. My question is:

There are some nested bottom tab routes.  Some tabs needs authenticate and some tabs dont need. I can add adguard to main routes, there is no problem but adguard class couldnt handle that nested bottom tab route which needs auth.

So how can i add adguard to nested bottom tabs? 

`@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      page: LoginView,
      path: '/login',
    ),
    AutoRoute(
page: BottomView, path: '/',
 guards: [AuthGuard],  

children: [ AutoRoute(
          path: 'myorders',
          page: EmptyRouterPage,
          name: 'MyOrdersRouter',
          guards: [
            AuthGuard
          ],
          children: [
            AutoRoute(
              path: '',
              page: MainOrdersPage,
            ),
            AutoRoute(
              path: 'orderdetail',
              page: OrderDetailPage,
            ),
            AutoRoute(
              path: ':orderNo',
              page: ShipmentPage,
            )
          ]),
      AutoRoute(
          path: 'mygarage',
          page: EmptyRouterPage,
          name: 'MyGarageRouter',
          children: [
            AutoRoute(path: '', page: MainGaragePage),
            AutoRoute(
              path: 'addvehicle',
              page: AddVehiclePage,
            ),
            AutoRoute(
              path: 'searchresult',
              page: SearchResultPage,
            ),
            AutoRoute(
              path: 'deletevehicle',
              page: DeleteVehiclePage,
            ),
            AutoRoute(
              path: 'vehicleproducts',
              page: VehicleProductsPage,
            )
          ]),
    ])
  ],
)
class $AppRouter {}`

Adguard:

`class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    if (locator<UserManager>().isAuthenticated) {
      resolver.next();
    } else {
      router.push(LoginViewRoute(onResult: (success) {
        resolver.next(success);
      }));
    }
  }
}`

LoginView:

`class LoginView extends StatefulWidget with InputValidation {
  final Function(bool) onResult;
  const LoginView({Key? key, required this.onResult}) : super(key: key);

  @override
  _LoginViewState createState() => _LoginViewState();
}
... some codes...
....
..
 onTap: () {
..
widget.onResult(true);
..},`

BottomView:

`class BottomView extends StatelessWidget {
  const BottomView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AutoTabsScaffold(
      routes: const [
        HomePageRouter(),
        MarkalarRouter(),
        MyCartRouter(),
        MyOrdersRouter(),
        MyGarageRouter()
      ],
      bottomNavigationBuilder: (_, tabsRouter) {
        return Container(
          child: BottomNavigationBar(
            currentIndex: tabsRouter.activeIndex,
            onTap: tabsRouter.setActiveIndex;
            items: _items,
            unselectedLabelStyle: const TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.w500,
                color: CustomColors.bottomLabelGrey),
            selectedLabelStyle: const TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.w500,
                color: CustomColors.lightOrange),
          ),
        );
      },
    );
  }
}

List<BottomNavigationBarItem> _items = [
  BottomNavigationBarItem(
.....
  ),
...
....
];`

**Comment by ayushin** [comment]
Yes, auth guards dont seem to work with tabs

**Comment by IamSAL** [comment]
You can add a listener to tabsRouter, when tab changes you can decide whether to allow the user depending on authentication status

**Comment by IamSAL** [comment]
AuthGuard doesn't seem to work on tabs, but there's a workaround: You can add a listener to tabsRouter, when tab changes you can decide whether to allow or navigate to login screen depending on authentication status . You can pass a call back to login page so that it takes back user to target tab after login is successful.
