### ISSUE TITLE
Prevent Youtube playing on background 

### ISSUE THREAD

**Issue by markbulingit** [Milad-Akarie/auto_route_library#954]
I have this route
```
Home
    -  Pillar Details
            - Blog Task
            - Video Task
Blog
Profile

```

When I go to Blog route from Video Task route, the video is still playing. How to solve this?

**Comment by Babwenbiber** [comment]
You should take a look at [Route aware widgets](https://medium.com/nerd-for-tech/flutter-how-to-implement-route-aware-widgets-af8ce7843852).
Make sure to stop your video on leaving the page.
