### ISSUE TITLE
flutter build web

### ISSUE THREAD

**Issue by ekoRemDev** [Milad-Akarie/auto_route_library#958]
When i run the project locally on the browser it works as expected, However, it throws the below error  when i want to build the project for web

Error: The required named parameter 'type' in method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' is not required in overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
      {required RouteInformationReportingType type}) {
                                              ^
../../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/router.dart:1329:8:
Info: This is the overridden method ('routerReportsNewRouteInformation').
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {RouteInformationReportingType type = RouteInformationReportingType.none}) {}
       ^
Error: Compilation failed.

**Comment by Milad-Akarie** [comment]
@ekoRemDev  That's really wried, I double checked and it is 'required' in the abstract class
 ```dart
 /// For more information on how [Router] determines a navigation event, see
  /// the "URL updates for web applications" section in the [Router]
  /// documentation.
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {required RouteInformationReportingType type}) {}
```

I removed the required keyword anyways, it should work in the next build
check out version 3.2.3

**Comment by ekoRemDev** [comment]
That solves the issue, i don't get this error anymore. Thank you very much
