### ISSUE TITLE
Is there a way to override the AutoTabsScaffold?

### ISSUE THREAD

**Issue by madqueendany** [Milad-Akarie/auto_route_library#959]
In my `home_screen` widget, I have an `AutoTabsScaffold` setup so it'll be persistent across my main screens (from the nav). Now on the detail pages, I'd like to implement a `CustomScrollView` with a stylized and flexible app bar. When I do just that, the auto tabs scaffold **and** my flexible SliverAppBar is showing.

Is there a way to override the Appbar painted by  the AutoTabsScaffold on certain (specifically child) screens?

**Comment by kerberk** [comment]
Did someone find a solution for this?
I also have the exact same problem.

**Comment by iEricKoh** [comment]
I am facing the same problem, how I solve it temporally is changing the appbar in`AutoTabsScaffold.appBarBuilder`, tho the animation doesn't looks good.

hope there's some other workaround that the child screen is able to override the parent appbar.
