### ISSUE TITLE
Routes with dependencies and arguments

### ISSUE THREAD

**Issue by MotiBartov** [Milad-Akarie/auto_route_library#96]
Hi Milad,

I have a question about routes and their dependencies.

Consider a route that have dependencies in its constructor (i.e arguments), but these dependencies aren't available when the route is created.. for example: 

- A route that requires dependency in its constructor (e.g. a Bloc, AnalyticsService etc'), but this dependency is taken from its wrapper Consumer.

- The route is an **initial route** in the Router, therefore it wont created or navigated by ExtendedRoute.ofRoute(Router).pushNamed(Routes.name, **arguments: RouteArguments(bloc: PageBloc())**) and therefore, the arguments cannot be forward to it. 

Therefore, such dependencies can provided in the wrappedRoute function scope right?

However, when such route is defined, the router.gr file, creates the RouteArguments class but because nobody provided an instance of it, it creates an empty instance which has all the members null. 
Then, it creates the instance of the actual route but fills the dependencies with these null values.

Currently, I did some workaround for this by creating a `static PageRoute create(Service service)`  method in the destination route, this method will  create a totally new instance of the route (instead the **this** created by the navigator) with all the required dependencies, wrap it with Provider and Consumer if required rather the one given by the Router (the **this**).

This method will be called from the wrappedRoute method and will return a route with all the dependencies. 

I hopped maybe you can suggest a better way to provide such dependencies  ?

Overall, I am really love to use this library in my project.
Thanks for your support,
Moti. 

`

**Comment by theweiweiway** [comment]
Closing due legacy generator not being supported anymore - please open a new issue for AutoRoute 2.x if you are still having problems!
