### ISSUE TITLE
Multiple owners claimed child RestorationBuckets with the same IDs.

### ISSUE THREAD

**Issue by Lingareddyvinitha** [Milad-Akarie/auto_route_library#963]
When we try to navigate the home to nested route we got this error 
```
final _appRouter = AppRouter();
@override
  Widget build(BuildContext context) {
    return  MaterialApp.router(
        restorationScopeId: "root",
        title: 'Sample',
        routerDelegate: _appRouter.delegate(),
        routeInformationParser: _appRouter.defaultRouteParser(),
      ),
    }
    ```
    
Error:
The following assertion was thrown during a scheduler callback:
Multiple owners claimed child RestorationBuckets with the same IDs.
The following IDs were claimed multiple times from the parent RestorationBucket(restorationId: Root,
owner: NavigatorState#11018(tickers: tracking 2 tickers)):

**Comment by francipvb** [comment]
Same issue here, tabs router involved.

**Comment by kane-knowby** [comment]
Is this issue resolved? I seem to be getting the same error, can we reopen? @Milad-Akarie
