### ISSUE TITLE
Method toPageRouteInfo from RouteMatcher is deprecated

### ISSUE THREAD

**Issue by limonadev** [Milad-Akarie/auto_route_library#966]
The method `toPageRouteInfo` appears as deprecated in the latest version of the package, and the suggestion for replacement points to the same method:

https://pub.dev/documentation/auto_route/latest/auto_route/RouteMatch/toPageRouteInfo.html

**Comment by Milad-Akarie** [comment]
@limonadev  @furaiev  Thank you for reporting, it's fixed in the new build
