### ISSUE TITLE
Nested router inside tab using AutoTabsScaffold

### ISSUE THREAD

**Issue by coldstar96** [Milad-Akarie/auto_route_library#967]
Hi, I recently discovered auto_route and very pleased about the feature it supports. Thanks for creating this! I'm trying to integrate auto_router to my existing project and having some difficulty around nested router. I tried reading all nested related docs but I'm not sure how to achieve the goal.

My project setup is
* bottom navigation bar(4 bar items and a button in the middle)
* each tab has its own navigator.
* When some child widget of a page inside a tab pushes a route, it pushes within the page -> tab still visible, each tab has its own stack of routes, switching between tabs keeps its stack.

My simplified AppRouter looks like the following
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    ...manyRoutes,
    CustomRoute<dynamic>(
      page: TabPage,
      path: '/',
      initial: true,
      children: [
        CustomRoute<dynamic>(
          path: 'first',
          page: FirstTabPage,
          children: [...manyRoutes ],
        ),
        CustomRoute<dynamic>(
          path: 'second',
          page: SecondTabPage,
          children: [...manyRoutes ],
        ),
        CustomRoute<dynamic>(
          path: 'third',
          page: ThirdTabPage,
          children: [...manyRoutes ],
        ),
        CustomRoute<dynamic>(
          path: 'fourth',
          page: FourthTabPage,
          children: [...manyRoutes ],
        ),
      ],
    ),
  ],
)
```

For the AutoTabsScaffold, I exactly followed the doc described in [here](https://pub.dev/packages/auto_route#tab-navigation).

When I launch the app, and try to push a route from the FirstTabPage by calling context.router from the inner widget of FirstTabPage, context.router is the root router instead of FirstTabRouter. And I looked at the Router state and I only see root router with 1 child(TabsRouter). I'm guessing I set it up incorrectly. Can you help me with properly setting up the nested router for this use case?

* context.router from the one of widgets inside FirstTabPage returns the nested router for the FirstTab.

**Comment by Milad-Akarie** [comment]
Hello @coldstar96 do your tab pages have a an AutoRouter widget to render child routes?

**Comment by coldstar96** [comment]
Thanks for the reply! I tried adding ```AutoRouter``` but it's unclear where to add them. ```AutoRouter``` widget provides ```builder``` and ```placeholder``` parameters. If I return```FirstPageTab``` from the ```builder``` param, the router won't push a new route. If I return ```FirstTabPage``` for ```placeholder``` param, pushed route becomes the only page and can't navigate back to the initial page. Is there an example or wiki around the ```AutoTabsScaffold``` setup?

**Comment by Milad-Akarie** [comment]
@coldstar96  You don't need to use the builder or placeholder in your case 
please refer to this example
https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/screens/home_page.dart
also there's a good tutorial by Reso coder addressing bottom navigation using auto_route
https://www.youtube.com/watch?v=9oH42_Axr3Q&t=2399s

**Comment by coldstar96** [comment]
Thanks for the example! That really helped. To recap, 

1. Use EmptyRouterPage for each tab page route in the @MaterialAppRouter. Must provide ```name``` parameter to avoid the Route name conflict among each tab since all tabs are using the same EmptyRouterPage.
2. routes of AutoTabsScaffold should be the routes with EmptyRouterPage rather than the first page(using the name I provided).
