### ISSUE TITLE
Sharing state between tabs

### ISSUE THREAD

**Issue by AAverin** [Milad-Akarie/auto_route_library#968]
I have this flow
```
    AutoRoute(page: GuideScreen, path: "/guide/:id", children: [
      AutoRoute(path: "overview", page: OverviewPage),
      AutoRoute(path: "spots", page: SpotsPage),
      AutoRoute(path: "map", page: MapPage),
      AutoRoute(path: "allSpotsGallery", page: AllSpotsGallery)
    ]),
```

Guide screen loads `guide` inside it and guide is supposed to be shared between all tabs.
With Navigator 1.0 what I was doing is just changing the selected page when route was triggered.
Now with `AutoTabsScaffold` it looks like triggering a new route doesn't just change the page, but also expect all the parameters to be passed to the route.

The exact use case is:
- there is a button on the SpotsPage
- pressing on the button should change bottom navigation to MapPage
- there is a shared GuideData that is passed to every subpage

What would be a good way to share GuideData between the tabs while still navigating with the Router and deeplinks?
Imaginable solution:
- triggering `/guide/:id/map` should create GuideScreen that will fetch GuideData and create all the subscreens, and final step of the navigation should be just changing selected tab in the bottom navigation.

**Comment by Milad-Akarie** [comment]
Hello @AAverin my first thought would be providing the GuidDate inside of GuidScreen through context using Provider, inherited state or such, so you have access to it anywhere down the widgets tree.

**Comment by AAverin** [comment]
@Milad-Akarie Looks like the only way to go is to make sure routes don't have parameters and share all the data some other way?
