### ISSUE TITLE
Nested Navigation error

### ISSUE THREAD

**Issue by udaymrx** [Milad-Akarie/auto_route_library#969]
Error:
Looks like you're trying to navigate to a nested route without adding their parent to stack first
try navigating to SettingsRoute -> MissingGroupRoute
![Screenshot from 2022-02-19 17-15-19](https://user-images.githubusercontent.com/80322241/154799396-c879c7e1-2b28-4f6c-ad03-62119135ce97.png)

**Comment by udaymrx** [comment]
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      children: [
        AutoRoute(
          path: 'home',
          name: 'GroupRouter',
          page: EmptyRouterPage,
          initial: true,
          children: [
            AutoRoute(
              path: '',
              page: GroupPage,
            ),
            AutoRoute(
              path: 'group/:name',
              page: GroupDetailPage,
            ),
            AutoRoute(
              path: 'explore',
              page: ExploreGroupPage,
            ),
            AutoRoute(
              path: 'suggestions',
              page: SuggestionPage,
              children: [
                // AutoRoute(
                //   path: ':name',
                //   page: OtherUserProfilePage,
                // ),
              ],
            ),
            AutoRoute(
              path: ':name',
              page: OtherUserProfilePage,
            ),
          ],
        ),
        AutoRoute(
          path: 'trending',
          name: 'TrendingRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: TrendingPage,
            ),
            AutoRoute(
              path: 'issues/:id',
              page: IssueDetailPage,
            ),
            AutoRoute(
              path: 'issues/:id',
              page: IssueYoutubeDetailPage,
            ),
            AutoRoute(
              path: 'panchayati/ongoing',
              page: PanchayatiPage,
            ),
            AutoRoute(
              path: 'panchayati/waiting',
              page: WaitingRoomPage,
            ),
          ],
        ),
        AutoRoute(
          path: 'notification',
          // name: 'NotificationRouter',
          page: NotificationPage,
        ),
        AutoRoute(
          path: 'profile',
          name: 'ProfileRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: UserProfilePage,
            ),
            AutoRoute(
              path: 'settings',
              page: SettingsPage,
              children: [
                AutoRoute(
                  path: 'missingGroup',
                  page: MissingGroupPage,
                  fullscreenDialog: true,
                ),
                AutoRoute(
                  path: 'edit',
                  page: EditUserProfilePage,
                ),
                AutoRoute(
                  path: 'verification',
                  page: VerificationPage,
                  fullscreenDialog: true,
                ),
                AutoRoute(
                  path: 'feedback',
                  page: FeedbackPage,
                ),
                // AutoRoute(
                //   path: 'about_us',
                //   page: WebScreen,
                // ),
              ],
            ),
            AutoRoute(
              path: 'share',
              page: ProfileSharePage,
            ),
            AutoRoute(
              path: 'edit',
              page: EditUserProfilePage,
            ),
            AutoRoute(
              path: 'connections',
              page: UserFollowersPage,
            ),
          ],
        ),
      ],
    ),
    AutoRoute(path: '/select_location', page: LocationPage),
    AutoRoute(path: '/signup', page: SignUpPage),
  ],
)
class $AppRouter {}

**Comment by udaymrx** [comment]
`
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: [
    AutoRoute(
      path: '/',
      page: HomePage,
      guards: [AuthGuard],
      children: [
        AutoRoute(
          path: 'home',
          name: 'GroupRouter',
          page: EmptyRouterPage,
          initial: true,
          children: [
            AutoRoute(
              path: '',
              page: GroupPage,
            ),
            AutoRoute(
              path: 'group/:name',
              page: GroupDetailPage,
            ),
            AutoRoute(
              path: 'explore',
              page: ExploreGroupPage,
            ),
            AutoRoute(
              path: 'suggestions',
              page: SuggestionPage,
              children: [
                // AutoRoute(
                //   path: ':name',
                //   page: OtherUserProfilePage,
                // ),
              ],
            ),
            AutoRoute(
              path: ':name',
              page: OtherUserProfilePage,
            ),
          ],
        ),
        AutoRoute(
          path: 'trending',
          name: 'TrendingRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: TrendingPage,
            ),
            AutoRoute(
              path: 'issues/:id',
              page: IssueDetailPage,
            ),
            AutoRoute(
              path: 'issues/:id',
              page: IssueYoutubeDetailPage,
            ),
            AutoRoute(
              path: 'panchayati/ongoing',
              page: PanchayatiPage,
            ),
            AutoRoute(
              path: 'panchayati/waiting',
              page: WaitingRoomPage,
            ),
          ],
        ),
        AutoRoute(
          path: 'notification',
          // name: 'NotificationRouter',
          page: NotificationPage,
        ),
        AutoRoute(
          path: 'profile',
          name: 'ProfileRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(
              path: '',
              page: UserProfilePage,
            ),
            AutoRoute(
              path: 'settings',
              page: SettingsPage,
              children: [
                AutoRoute(
                  path: 'missingGroup',
                  page: MissingGroupPage,
                  fullscreenDialog: true,
                ),
                AutoRoute(
                  path: 'edit',
                  page: EditUserProfilePage,
                ),
                AutoRoute(
                  path: 'verification',
                  page: VerificationPage,
                  fullscreenDialog: true,
                ),
                AutoRoute(
                  path: 'feedback',
                  page: FeedbackPage,
                ),
                // AutoRoute(
                //   path: 'about_us',
                //   page: WebScreen,
                // ),
              ],
            ),
            AutoRoute(
              path: 'share',
              page: ProfileSharePage,
            ),
            AutoRoute(
              path: 'edit',
              page: EditUserProfilePage,
            ),
            AutoRoute(
              path: 'connections',
              page: UserFollowersPage,
            ),
          ],
        ),
      ],
    ),
    AutoRoute(path: '/select_location', page: LocationPage),
    AutoRoute(path: '/signup', page: SignUpPage),
  ],
)
class $AppRouter {}
`

**Comment by Milad-Akarie** [comment]
MissingGroupRoute is a child of SettingsRoute, you need to push that too.

**Comment by andikanugraha** [comment]
Hi, can you elaborate example code to include children Route, because from the example below, I'm only get to the parent screen not the children screen.

`context.pushRoute(AccountRouter(
  children: [
    // push any sequence of Account routes here   
    // the last route will be the one that is currently visible
    AccountRoute(),
    AccountSettingsRoute()
  ]
));`

**Comment by udaymrx** [comment]
@Milad-Akarie SettingsRoute is not a TabRouter. It is just a simple page from white I want to navigate to MissingGroupPage.
And want the URL to change accordingly.. i.e /profile/settings/missing-group

**Comment by vstacked** [comment]
```dart
@MaterialAutoRouter(
replaceInRouteName: 'Page,Route',
    routes: <AutoRoute>[ 
        AutoRoute(
            path: "/settings",
            name: "SettingsRouter",
            page: EmptyRouterPage,
            children: [
                AutoRoute(path: '', page: SettingsPage),
                AutoRoute(path: 'missing-group', page: MissingGroupPage)
            ],
        ),
    ],
)
class $AppRouter {}
```
then if you want push to `MissingGroupPage` try use `context.push(MissingGroupRoute());`

Ref https://autoroute.vercel.app/basics/nested_routes
