### ISSUE TITLE
Support for complex function types . Types inside functional Parameters are not imported.

### ISSUE THREAD

**Issue by nateshmbhat** [Milad-Akarie/auto_route_library#97]
### Some examples : 
+ TypeA Function(TypeB , TypeA , { TypeC typec , TypeD typed });
+ TypeA Function<T,List\<R>,S>(TypeB , TypeA , [ TypeC typec , TypeD typed ] );
+ final void Function<G extends TypeA>(LocationItem , CheckListItem , G subTypeOfTypeA ,{Future<CoreConfig> a , CreateOrderRequest b} ) onChanged;

**Functions inside Function parameters** :

+ Future<TypeA> Function<T,List\<R>,S> (Function(TypeA , TypeB) , TypeC variable);
+ void Function<A,B,C,T,G extends TypeA ,F extends Function(TypeH)>(LocationItem , CheckListItem , T item , G subTypeOfTypeA , [int a , int b] ) onSelected;

### Here's a sum up of the things that need to supported should be included in the tests : 
+ Support generics or type parameterised functions
+ Support named , optional , and positional parameters for function types
+ Support importing return types for function types
+ Support nested FunctionType ( `void Function(Function(int) , double)` ) parameters
+ Support Future<FunctionType>
+ Support type parameters that extend that some super class type . So import should happen for this super class :  ( `void Function<T extends TypeA>( int a, Type B)` )

**Comment by nateshmbhat** [comment]
@Milad-Akarie i'm making progress on this issue , will raise a PR soon :) 
Once this is properly done , the library would be unstoppable :D

**Comment by Milad-Akarie** [comment]
Implemented in auto_route_generator 0.4.10 by @nateshmbhat.
