### ISSUE TITLE
Path param on root page of tab navigation

### ISSUE THREAD

**Issue by abdullah10182** [Milad-Akarie/auto_route_library#971]
Hi, 

I was wondering if it is possible to set a path param when you navigate to a tab. Ideally, I would like to pass an id to the root of the second tab.

```
routes: [
    AutoRoute(
      path: '/',
      page: MainNavigation,
      children: [
        AutoRoute(/* home tab */ ),
        AutoRoute(
          path: 'my-device/:serviceId',
          name: 'ServicesRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute(path: '', page: MyDeviceScreen),
          ],
        ),
      ],
    ),
 ],

```

The issue is that the navigation is being taken care of by the index in the bottom navigation component. So I have no idea how would you go about passing the params or updating these.

```
 BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (index) async {
        tabsRouter.stackRouterOfIndex(index)?.popUntilRoot();
        tabsRouter.setActiveIndex(index);
      },
      backgroundColor: Colors.white,
      items: RoutesData.routes.map((route) => BottomNavigationBarItem(icon: route.icon, label: route.label)).toList(),
 ),
```

Any help would be greatly appreciated.

**Comment by Milad-Akarie** [comment]
Hey @abdullah10182  you can also set/navigate to a certain tab using the navigate method
`tabsRouter.navigate(TabWithParam(param: 'data'))`

if your param already exists in the parent route you might access it using 
`context.routeData.parent?.pathParams`
or from the Router object
`context.router.routeData`
