### ISSUE TITLE
Nested Navigation not loading the initial child screen

### ISSUE THREAD

**Issue by riverscuomo** [Milad-Akarie/auto_route_library#972]
I want to set an initial Child screen inside of Parent screen using nested navigation. Here is my approuter:

```
@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute(path: "/", page: ParentScreen, children: [
        AutoRoute(path: '', page: ChildScreen, initial: true),
      ],),],)
```
For some reason, this only loads the Parent screen without the Child screen inside of it. Do you see anything wrong here? This should load the Child screen, right?

**Comment by Milad-Akarie** [comment]
Parent screen should have AutoRouter widget to render child roues

**Comment by riverscuomo** [comment]
One clue is that after the parent screen loads, if I reload the screen with ```context.router.pushNamed(childScreenName);``` pasted into the Parent screen build function, the Child Screen appears inside the Parent Screen. But if I include ```context.router.pushNamed(childScreenName);``` in the initial build, I get this error ```'Can not navigate to $path'```.
