### ISSUE TITLE
404 web page not found 

### ISSUE THREAD

**Issue by sunilkumawatandroid** [Milad-Akarie/auto_route_library#974]
@Milad-Akarie  I want to show a 404 page when user input the wrong route name in the address bar. is there any attribute we can set the error page for web.

**Comment by Milad-Akarie** [comment]
@sunilkumawatandroid 
just put a wildcard path at the end of your routes list.
routes: [
 //routes
 AutoRoute(path: '*', page: NotFoundPage);
]
