### ISSUE TITLE
Converting object to an encodable object failed

### ISSUE THREAD

**Issue by MattOutdore** [Milad-Akarie/auto_route_library#979]
Hi,

I have a single root router with no nesting and whenever I call context.router.pop(), I get an error stating

`Unhandled Exception: Converting object to an encodable object failed: Instance of '<ScreenRoute>Args'
`

**Comment by Milad-Akarie** [comment]
@MattOutdore  please share your router setup

**Comment by MattOutdore** [comment]
Thanks for the quick reply!

Here's my router setup

`
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(page: SplashScreen, initial: true),
    AutoRoute(page: OnboardingScreen),
    AutoRoute(page: HomeScreen),
    AutoRoute<SearchModel>(page: WhatScreen),
    AutoRoute<SearchModel>(page: DimensionsScreen),
    AutoRoute(page: WhenScreen),
    AutoRoute<SearchModel>(page: WhoScreen),
    AutoRoute(page: MapScreen),
    AutoRoute(page: CheckoutCamping),
    AutoRoute(page: CheckoutGlamping),
    AutoRoute(page: DetailsScreen),
    AutoRoute(page: FeedbackScreen),
    AutoRoute(page: TosScreen),
    AutoRoute(page: MyDetailsScreen),
    AutoRoute(page: ExtrasScreen),
    AutoRoute(page: SupportScreen),
    AutoRoute(page: SupportFeeScreen),
    AutoRoute(page: PaymentScreen),
    AutoRoute(page: SuccessScreen),
    AutoRoute(page: FiltersScreen),
    AutoRoute(page: OwnerRulesScreen),
    AutoRoute<DateTimeRange>(page: AvailabilityScreen),
  ],
)
class $AppRouter {}
`

**Comment by MattOutdore** [comment]
Thanks for the quick reply!

Here's my router setup,

`
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(page: SplashScreen, initial: true),
    AutoRoute(page: OnboardingScreen),
    AutoRoute(page: HomeScreen),
    AutoRoute<SearchModel>(page: WhatScreen),
    AutoRoute<SearchModel>(page: DimensionsScreen),
    AutoRoute(page: WhenScreen),
    AutoRoute<SearchModel>(page: WhoScreen),
    AutoRoute(page: MapScreen),
    AutoRoute(page: CheckoutCamping),
    AutoRoute(page: CheckoutGlamping),
    AutoRoute(page: DetailsScreen),
    AutoRoute(page: FeedbackScreen),
    AutoRoute(page: TosScreen),
    AutoRoute(page: MyDetailsScreen),
    AutoRoute(page: ExtrasScreen),
    AutoRoute(page: SupportScreen),
    AutoRoute(page: SupportFeeScreen),
    AutoRoute(page: PaymentScreen),
    AutoRoute(page: SuccessScreen),
    AutoRoute(page: FiltersScreen),
    AutoRoute(page: OwnerRulesScreen),
    AutoRoute<DateTimeRange>(page: AvailabilityScreen),
  ],
)
class $AppRouter {}

`

**Comment by MattOutdore** [comment]
Thanks for the quick reply!

Heres my router setup

```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(page: SplashScreen, initial: true),
    AutoRoute(page: OnboardingScreen),
    AutoRoute(page: HomeScreen),
    AutoRoute<SearchModel>(page: WhatScreen),
    AutoRoute<SearchModel>(page: DimensionsScreen),
    AutoRoute(page: WhenScreen),
    AutoRoute<SearchModel>(page: WhoScreen),
    AutoRoute(page: MapScreen),
    AutoRoute(page: CheckoutCamping),
    AutoRoute(page: CheckoutGlamping),
    AutoRoute(page: DetailsScreen),
    AutoRoute(page: FeedbackScreen),
    AutoRoute(page: TosScreen),
    AutoRoute(page: MyDetailsScreen),
    AutoRoute(page: ExtrasScreen),
    AutoRoute(page: SupportScreen),
    AutoRoute(page: SupportFeeScreen),
    AutoRoute(page: PaymentScreen),
    AutoRoute(page: SuccessScreen),
    AutoRoute(page: FiltersScreen),
    AutoRoute(page: OwnerRulesScreen),
    AutoRoute<DateTimeRange>(page: AvailabilityScreen),
  ],
)
class $AppRouter {}
```
