### ISSUE TITLE
Can't access navigatorKey

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [Milad-Akarie/auto_route_library#98]
Hi there,

It seems like the `Router.navigator.key` is no longer available, I read through the changelog but can't see anything obvious that indicates how to access it now, please advise :)

**Comment by Milad-Akarie** [comment]
@Ferdzzzzzzzz You don't need direct access to the key anymore if You're using the ExtendedNavigator() 
you can obtain your navigator state by calling 
`ExtendedNavigator.ofRouter<YourRouter>().push(...)`
or if you're using only one Navigator in your App
`ExtendedNavigator.rootNavigator.push(...)`

or using context 
`ExtendedNavigator.of(context).push...`

**Comment by Ferdzzzzzzzz** [comment]
So sorry I meant to close this issue a couple of hours ago, thanks so much...it's an amazing package, can't believe how clean it's making my work project 🔥

**Comment by visual-velocity** [comment]
How to use custom navigator key inside it

**Comment by visual-velocity** [comment]
Hi, I need direct access to the key for my production app
