### ISSUE TITLE
DefaultTabController sliding animation not working 

### ISSUE THREAD

**Issue by 0xPixelfrost** [Milad-Akarie/auto_route_library#980]
I have an app with tabs, similar to [flutters interactive sample](https://docs.flutter.dev/cookbook/design/tabs).

Using auto_route in combination with the `DefaultTabController` is technically working, but i don't get the default transition animation displayed. Setting custom transitions in `CustomRoute` is also not working. 

Anybody some ideas on this? Unfortunatelly, the documentation is not covering the case for normal tabs :(

```
class MainScreen extends StatelessWidget {
  const MainScreen({Key? key}) : super(key: key);

  static const _routes = [
    ChatTab(),
    ContactTab(),
  ];

  @override
  Widget build(BuildContext context) => AutoTabsRouter(
        routes: _routes,
        builder: (context, child, animation) {
          final tabsRouter = AutoTabsRouter.of(context);

          return DefaultTabController(
            length: _routes.length,
            child: Scaffold(
              appBar: AppBar(  
                bottom: TabBar(
                  onTap: tabsRouter.setActiveIndex,  
                  tabs: [
                    Tab(
                      icon: Text('Chat'),
                    ),
                    Tab(
                      icon: Text('Contact'),
                    ),
                  ],
                ),
              ),
              body: child,
            ),
          );
        },
      );
}
```

```
AutoRoute(
      path: '',
      page: MainPage,
      children: [
        AutoRoute(
           page: ChatPage,
           name: 'ChatTab',
           path: 'chats',
       ),
        AutoRoute(
           page: ContactPage,
           name: 'ContactTab',
           path: 'contacts',
       ),
      ],
    ),
```

**Comment by NielsSchneider** [comment]
Hello @0xPixelfrost, not sure it will work in your situation, but wrapping the child of line 'body: child' in an animation might do the trick,

For example:

`body: FadeTransition(
    opacity: animation,
    child: child,
)`

By default the AutoTabsRouter will have an animation duration of 300 milliseconds. You can change the duration by setting a different duration on the AutoTabsRouter widget.
