### ISSUE TITLE
What is the meta attribute in AutoRoute and can I use it on observers?

### ISSUE THREAD

**Issue by alejandrogiubel** [Milad-Akarie/auto_route_library#981]
What is the meta attribute in AutoRoute. Can I use it on observers?

```
AutoRoute<dynamic>(
  page: HomePage,
  initial: true,
  meta: <String, String>{
    'test': 'test'
  },
  guards: [AuthGuard],
),
```

**Comment by Milad-Akarie** [comment]
@alejandrogiubel it's just static data  you could pass to your route, think of it as annotating your route with something so you can treat a certain way. 
e.g in a tabs router if you want to hide the bottom nav for certain routes you can go 

```dart
AutoRoute(page: SomeRoute, meta: {'hideBottomNav' : true})
```

and then inside your widgets
```dart
final hideBottomNav = tabsRouter.topMatch.meta['hideBottomNav'] == true;
```

**Comment by alejandrogiubel** [comment]
I found meta in `onNavigate` of `routerDelegate` in `urlState`. 👍
