### ISSUE TITLE
Drawer and Bottom Navigation bar on same page

### ISSUE THREAD

**Issue by sunilkumawatandroid** [Milad-Akarie/auto_route_library#982]
@Milad-Akarie thanks for my last question answer.

I am trying to show **Drawer** and **Bottom navigation bar** on the same page.But I am confused that how can i use **AutoRouter for drawer** pages and **AutoTabsScaffold for Bottom navigation** widget on the same screen.

If I am go with the AutoRouter for both drawer and navigation bottom bar then when i am navigate from navigation bar it navigate me to the page but when i am press browser back button previews page show but the bottom navigation can not highlight previous tab. 

So i want to know that how can i achive this. or is there any **observer to track the route** so i can **highlight the bottom navigation** tab on back or forward on web.

**Comment by Milad-Akarie** [comment]
@sunilkumawatandroid  in this case you'll have to highlight the active route  ( for drawer ) or the bottomNav your self.
you could use 
` router.isRouteActive(MyRoute.name);`
or
`router.isPathActive('/tab1'); `

for sideNav it could be simple
```dart
  ListTile(
      title: Text('Route1'),
      style: ListTileStyle.drawer,
      selected: router.isRouteAcitve(RouteOne.name),
    );
```
for bottom nav i'd have a list of all tab routs 

`const tabRoutes = [TabRoute1,TabRoute2,..];`
navigate to tab route

`onTap(index) => router.navigate(tabRoutes[index]!);`

set active tab
```dart
 // we check for active route index by using
  var activeIndex = tabRoutes.indexWhere(
  (r) => router.isRouteActive(r.routeName),
 );
// there might be no active route until router is mounted
// so we play safe
 if (activeIndex == -1) {
 activeIndex = 0;
 }
```

**Comment by sunilkumawatandroid** [comment]
@Milad-Akarie thanks

Is this possible to use Drawer and navigation bottom bar on same page with AutoTabScaffold ?

**Comment by Ruslanbek0809** [comment]
@sunilkumawatandroid and whoever searching for the way of adding `Drawer` and opening it in `AutoTabsScaffold`, use `AutoTabsScaffold`'s `scaffoldKey` parameter to add your global scaffold key instead of  `AutoTabsScaffold`'s `key` parameter (which apparently doesn't work). Then, call your global scaffold key from wherever you want. 

1. Add it like this: 
```
AutoTabsScaffold(
      scaffoldKey: yourGlobalScaffoldKey,
```

2. Call it like this from whatever class you want:
```
homeScaffoldKey.currentState?.openDrawer();
```

PS: @sunilkumawatandroid Yes you can use both the drawer and bottom navigation bar.
