### ISSUE TITLE
How to replace the root route?

### ISSUE THREAD

**Issue by cdprete** [Milad-Akarie/auto_route_library#983]
Hi.
I'm using the version 3.2.4 of the library and I've the necessity to replace the root route with another one which is not an initial route.
The scenario is the following:
- a user gets the login page (root route)
- he/she logs in and he/she gets into the application (new route X)
- he/she can press the back button of the browser to go back at the login view an, if wanted, he/she can then press the forward button to go back to the view pointed by the route X completely ignoring the login.
I've tried with 
```
context.router.popUntilRoot();
context.router.replace(ContactsViewRoute());
```

but I can still go back.
Is there any way to prevent this?

**Comment by Milad-Akarie** [comment]
@cdprete  `router.replaceAll([NetRootRoute()])`
