### ISSUE TITLE
navigating from one tab route into another and goinng back successfully

### ISSUE THREAD

**Issue by virtz** [Milad-Akarie/auto_route_library#984]

**Comment by virtz** [comment]
I have four tabs each with at least two nested routes. I'm tryingto navigate from one tab route into the first;second or third child of the second tab route and going back successfully

Currently i move into another tab route with
context.navigateTo
and use context,navigateBack to go back.


But somethings the pop action doesn't happen as expected

**Comment by Milad-Akarie** [comment]
@virtz  what do you mean it doesn't work as expected?
