### ISSUE TITLE
AutoTabsScaffold and not updating Routes

### ISSUE THREAD

**Issue by matecode** [Milad-Akarie/auto_route_library#990]
Hi. I need some advice with this question, thank you for your help

I have an AutoTabsScaffold with routes containing one called with an argument wich i get from an provider (riverpod)

Here is some code:

```
class _NewsWrapperPageState extends ConsumerState<NewsWrapperPage>  {

  @override
  Widget build(BuildContext context) {
    var defaultChannel = ref.watch(defaultChannelProvider);
    return AutoTabsScaffold(
      routes: [
        NewsHomeRoute(channel: defaultChannel),
        const NewsChannelSelectionRoute(),
      ],
```

when the provider changes the NewsHomeRoute does not update the argument. Anything wrong from my side?

Again, thanks a lot for helping out.

**Comment by Shahmirzali-Huseynov** [comment]
@matecode  did you find solution ? @Milad-Akarie  can you help ? I also have this issue , arguments not updating when I run this command   
`context.router.navigate(HomeRoute(titleName: "Title 1")); or context.router.navigate(HomeRoute(titleName: "Title 2"));`


arguments or pages not updating at this time.

**Comment by magician20** [comment]
@matecode try read look at [this ](https://github.com/Milad-Akarie/auto_route_library/issues/719#issuecomment-928238491) maybe help you . also add your class $AppRouter
