### ISSUE TITLE
Get current path?

### ISSUE THREAD

**Issue by SpencerC** [Milad-Akarie/auto_route_library#991]
I'm writing an app that runs on web and mobile and wondering if there's a way to get the path of the resolved route. For top level pages, we can test URLs like so:
```dart
expect(rootRouter.current.match, equals('/page'));
```
However, for [tab pages](https://github.com/Milad-Akarie/auto_route_library#tab-navigation), the url might be `/parentPage/child1`, but `rootRouter.current.match = /parentPage`. This works though:
```dart
expect(appRouter.innerRouterOf<TabsRouter>(ParentPageRoute.name)!.current.match,
          equals('child1'));
```
Is there a more concise way to do this? Ideally, it would be something like:
```dart
expect(appRouter.fullPath, equals('/parentPage/child1'));
```

**Comment by SpencerC** [comment]
After a bit of reverse engineering, it appears `appRouter.navigationHistory.urlState.path` also works.

**Comment by ChauCM** [comment]
how is this?
```
final routerDelegate = AutoRouterDelegate.of(context);
print(routerDelegate.urlState.path));
```

**Comment by SpencerC** [comment]
@ChauCM IMHO that's definitely more concise, but still not very readable.
