### ISSUE TITLE
Is it possible to add 'barrierColor' to CustomRoute?

### ISSUE THREAD

**Issue by fior-di-latte** [Milad-Akarie/auto_route_library#996]
Hi,
Is it possible to add 'barrierColor' to CustomRoute? Or does s/o know a good workaround?

Thanks a lot!
Felix

**Comment by Milad-Akarie** [comment]
@fior-di-latte  I don't think it's added yet, but for now you can use the customRouteBuilder and build your own PageRouteBuilder

**Comment by Milad-Akarie** [comment]
@fior-di-latte  in the next version it can be added directly to customRoute as int color value.
