### ISSUE TITLE
How to clear sub-stack when changing between tabs?

### ISSUE THREAD

**Issue by RTsosssoldi** [Milad-Akarie/auto_route_library#998]
I'vs got 4 tabs with the relative nested page. What i'm trying to accomplish is:

1. navigatin to a subpage of Tab1
2. switching to Tab2 through the bottomBar
3. navigating again on Tab1 -> HERE i would like to see the root page of tab1 instead the one of the step1

is it possible?

**Comment by AlexDochioiu** [comment]
Probably a bit late, but you can change to pop on exit instead of entry
```dart
onTap: (index) { tabsRouter.stackRouterOfIndex(tabsRouter.activeIndex)?.popUntilRoot(); tabsRouter.setActiveIndex(index); },
```
